### PR TITLE
Fix Currency Mismatch in Order Editing Screen

### LINKED ISSUE #12865: Editing Order Details - Incorrect Currency Displayed When Order Currency Differs from Store Default
We consistently use the store's default currency when editing an order, even if the order was created in a different currency. This results in inconsistencies across various sections of the editable order screen, including Items, Custom Amounts, Discounts, Coupons, and Order Totals. Additionally, when adding new products to the order, prices are displayed in the store's default currency instead of the order's currency.

This inconsistency is confusing for users.

https://github.com/user-attachments/assets/abdc1217-476c-449e-abd6-68b06ee3e1fb

(Video from iOS device but relatable to Android)

Suggested Workaround to consider:
> To completely fix this issue, we would need to receive product prices in the order’s currency so we can display them correctly during product selection. Since the REST API does not currently provide this, I suggest disabling the Edit mode for orders in a currency different from the store’s default.
>
> Users would still be able to change the order status, create shipping labels, issue refunds, and add tracking, notes, and shipping details from the Order Details. They wouldn’t be able to add Custom Amounts, Discounts, Coupons, or new Items to the order. These actions aren’t very common for orders created on the storefront anyways.

peaMlT-XF-p2

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12865 

### Description

This PR ensures that product prices, custom amounts, and shipping lines remain consistent with the order's currency instead of defaulting to the store currency. Previously, editing an order would fetch products in the store’s default currency, causing inconsistencies in prices, totals, and tax calculations. This update aligns the behaviour by always passing the order’s currency when fetching products, searching for items, and handling order modifications.

### Changes Implemented
1. Pass order.currency to /products and /variations Endpoints

- When fetching products and variations in the order editing screen, the order's currency is now passed as a query parameter.

2. Pass order.currency While Searching for Products

- When searching for products in the order edit screen, we are passing order’s currency.

3. Handle Order Currency When Entering/Editing Custom Amounts

- Custom amounts entered in the order screen are now aligned with the order’s currency.

4. Handle Order Currency When Entering/Editing Shipping Lines

- Shipping charges are now handled in the order’s currency.

5. Add Unit Tests

#### Before: (Incorrect Behavior)
1. Order created in EUR, but editing an order fetches products in USD.
2. New products added to the order default to USD prices, leading to mismatches.
3. Custom amounts and shipping lines use store default currency instead of the order’s currency.

#### After: (Correct Behavior)
1. Order created in EUR, and all edits respect the order’s currency.
2. Product prices are fetched and displayed in EUR.
3. Custom amounts and shipping lines match the order currency.
4. All totals, taxes, and calculations remain consistent.

### Steps to reproduce

1. In your store viewfront, create an order with some items with a currency other than the default one. You can do that by accessing the store from a country with a different currency than the default one (better in Incognito mode in the browser). For that to work, you should have enabled the Automatically switch customers to their local currency if it has been enabled in the Multicurrency setting of WooCommerce wp-admin.
2. Open the app and go to orders.
3. Click on Edit orders
4. See that the currency displayed is not proper.

### Testing information

1. **Create an Order in a Non-Default Currency**

-  Place an order using a currency different from the store’s default from the web front end.
- Example: Store currency is USD, but order is placed in EUR.
- Edit the Order from the app

2.  **Open the order editing screen.**
- Ensure that all prices (products, custom amounts, shipping lines) are displayed in EUR.
- Search and Add a Product

3. **Search for a product in the order edit screen.**
- Ensure that the returned product prices are in EUR.
- Add the product to the order and confirm that totals are updated correctly.
- Modify Custom Amounts and Shipping

4. **Enter a custom amount and ensure it reflects EUR.**

5. **Modify shipping costs and confirm that the values remain in EUR.**

6. Ensure Adding products, variations and in general order creation and order editing has no regression

### Images/gif

https://github.com/user-attachments/assets/a1dae051-e820-4ccb-a886-6ffacbc36c7f

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt [hunk 1]
```diff
@@ -1165,69 +1174,72 @@ class OrderCreateEditFormFragment :
     @Suppress("ComplexMethod")
     private fun handleViewModelEvents(event: Event, binding: FragmentOrderCreateEditFormBinding) {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt:1175]: Refactored existing method to reduce cyclomatic complexity

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt [hunk 2]
```diff
@@ -246,77 +252,86 @@ class ProductSelectorViewModel @Inject constructor(
...
-                    selectedVariationIds = variationIds.intersect(selectedItems.variationIds.toSet()),
-                    selectionState = getProductSelection()
-                )
+                val selectedProductIds = selectedItems.map { it.id }.toSet()
+                if (selectedProductIds.contains(remoteId)) SELECTED else UNSELECTED
             }
         }
     }
 
+    private fun Product.formatPrice(): String? {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt:289]: Refactored existing code to reduce cyclomatic complexity

**Review by samiuelson — APPROVED** [review]
LGTM! :shipit:
