### PR TITLE
Ensures budget label doesn't get cut off in smaller screens

### LINKED ISSUE #12520: The stats label of the Blaze campaign item is cut off
**Describe the bug**
The second stats label of the Blaze campaign item is cut off

**To Reproduce**
1. Enable Blaze for your site from the web.
2. From the app, go to "Menu → Blaze" and create a campaign.
3. Scroll down to Blaze card on My Store tab.

**Screenshots**

**Expected behavior**
"Weekly" label should be a single line.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Galaxy S24
- Android version: 14
- WooCommerce Android version: 9.3.0-beta 1

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #12520

### Description

Fix UI glitch when displaying Blaze budget in small screens. It also improves how the Blaze stats are displayed in larger screens or tablets. 

### Testing information

1. Use a device with a small screen, an emulator should work. For example: `720x1280 - 4.6 inch` screen. 
2. Log into the app to a site with Blaze campaigns
3. Check the Blaze campaign stats are displayed without any cuts of like this: 

Additionally these changes shorten the figures displayed for impressions and clicks to avoid potential issues if this numbers are really big. Testing this will require to hardcode the `impressions` and `clicks` values. You can apply this patch for it: 

```diff
Subject: [PATCH] Shortens impressions and clicks numbers to avoid issues with spacing
---
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt	(revision ddf8cfd4c8d4f8898ce5d5724d2c9c9ff4ec01f0)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/BlazeUiMapper.kt	(date 1725466236462)
@@ -13,8 +13,8 @@
         ),
         status = CampaignStatusUi.fromString(uiStatus),
         isEndlessCampaign = isEndlessCampaign,
-        impressions = impressions.shortenToNearestThousand(),
-        clicks = clicks.shortenToNearestThousand(),
+        impressions = 5421134221L.shortenToNearestThousand(),
+        clicks = 35432L.shortenToNearestThousand(),
         formattedBudget = getBudgetValue(this, currencyFormatter),
         budgetLabel = getBudgetTitle(this)
     )

```

Screenshot 2024-09-04 at 18 08 10

### The tests that have been performed

Tested different label and value lengths as well as tested portrait and landscape orientations in different screen sizes: 

### Images/gif

https://github.com/user-attachments/assets/14603348-b419-4410-9f26-dab579ad792d

https://github.com/user-attachments/assets/66d8d278-1e9b-4122-86ec-c4d83a65eb08

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/234">20.3</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt [hunk 1]
```diff
@@ -37,4 +37,15 @@ infix fun <T> Comparable<T>?.lesserThan(other: T) =
     this?.let { it < other }
         ?: false
 
+/**
+ * The number is shortened to the nearest thousand or million. For example, 1,500 is shortened to 1.5k.
+ */
+fun Long.shortenToNearestThousand(): String = when {
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt]: We will have a localization issue with this function. Andoir already has a built-in feature, [CompactDecimalFormat](https://developer.android.com/reference/android/icu/text/CompactDecimalFormat). I think we can use it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt [hunk 2]
```diff
@@ -74,13 +76,19 @@ fun BlazeCampaignItem(
...
-                            campaign.impressions
                         )
                     )
-                    Spacer(modifier = Modifier.width(42.dp))
+                    val orientation = LocalConfiguration.current.orientation
+                    if (orientation == Configuration.ORIENTATION_PORTRAIT) {
+                        Spacer(modifier = Modifier.weight(1f))
+                    } else {
+                        Spacer(modifier = Modifier.width(16.dp))
+                    }
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt:89]: Have you considered using `land/dimens.xml`? I don’t think it would provide much benefit in this case, but I just wanted to remind you.

File: WooCommerce/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -3859,6 +3859,7 @@
     <string name="blaze_campaign_status_suspended">Suspended</string>
     <string name="blaze_campaign_status_ctr_label">Click-throughs</string>
     <string name="blaze_campaign_status_ctr_valur">%1$d ➔ %2$d</string>
```
Comment (irfano) [inline WooCommerce/src/main/res/values/strings.xml]: `blaze_campaign_status_ctr_valur` is unused now, we can remove it.

**Review by irfano — CHANGES_REQUESTED** [review]

File: WooCommerce/src/main/res/values/strings.xml (hunk 3 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/res/values/strings.xml]: Yeah, good catch. I actually left it to avoid extra conflicts once merging with [this](https://github.com/woocommerce/woocommerce-android/pull/12471#discussion_r1740727579).

Anyway I'll help deal with conflicts when `release-20.2` is merged back into `trunk`

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt:89]: Yeah, thanks for the reminder. I'm not using the actual `dimen.xml` values for compose for neither of the orientations, for reasons we already talked about. So, for this case is the same 🙂

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt (hunk 1 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt]: Very good point @irfano . I actually based this logic in the existing logic we have in [CurrencyFormatter](https://github.com/woocommerce/woocommerce-android/blob/66d162b2cfb007c7a75234eb8454a177f0c817ec/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt#L47) class, that we use everywhere 😅. 
Perhaps we should refactor that. 

I've applied a solution based on your suggestion. After reading the docs for , [CompactDecimalFormat](https://developer.android.com/reference/android/icu/text/CompactDecimalFormat) it seems is discouraged for newer versions. So I've added a compatibility function to shorten the numbers. Worked well in my tests. Let me know what you think: https://github.com/woocommerce/woocommerce-android/pull/12524/commits/0e50fed33b2f227969777caf7bcf4f4f03255656

Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NumberExt.kt]: I tested and verified it's localized now. Good job!

> Perhaps we should refactor that.

I opened an [issue](https://github.com/woocommerce/woocommerce-android/issues/12541) for it.

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻 I'm approving and it's good to merge after fixing failing unit tests.
