### PR TITLE
Show the confirm discard dialog when exiting product tags after adding new tags

### LINKED ISSUE #3095: Product tags doesn't show confirm discard when back button pressed
To reproduce:

- Go to product detail and choose to add tags
- Type a tag that doesn't already exist 
- Hit enter to add it as a chip
- Press the back button
- No "Confirm discard" dialog appears

However, one **does** appear if you add a tag by tapping it in the list.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Fixes #3095 

Currently when exiting the product tags screen after adding new tags (tags that don't exist in the server), the confirm discard dialog is not shown.
This PR fixes this.

**Testing**:
- Go to product detail and choose to add tags
- Type a tag that doesn't already exist
- Hit enter to add it as a chip
- Press the back button
- Check that the "Confirm discard" dialog appears

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 1]
```diff
@@ -1390,11 +1392,11 @@ class ProductDetailViewModel @AssistedInject constructor(
...
     /**
-     * Called when user exits the product tag fragment to clear the stored filter (otherwise it
-     * will be retained when the user returns to the tag fragment)
+     * Called when user exits the product tag fragment to clear the stored filter and the done button state
+     * (otherwise it will be retained when the user returns to the tag fragment)
      */
-    fun clearProductTagFilter() {
-        productTagsViewState = productTagsViewState.copy(currentFilter = "")
+    fun clearProductTagsState() {
+        productTagsViewState = productTagsViewState.copy(currentFilter = "", shouldDisplayDoneMenuButton = false)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:1399]: I added this, because after discarding changes, the `shouldDisplayDoneMenuButton` keeps its value `true`, if the user comes back to the tags screen, we would have an invalid state.

**Review by AmandaRiu — APPROVED** [review]
Code changes look good and everything works as described. Nice work! :shipit:
