### PR TITLE
[Product Selector] Fix selected items state serializing

### LINKED ISSUE #8623: Fix state preserving when exiting the app during product selection
When adding a new product and exiting the app mid-way (could be to answer a message or other reasons), then returning to the app, the app state is refreshed, and the merchant lands back on My Store instead. (this seems to only happen if there are products selected)

Source: pdcxQM-1Wb-p2
Reported by @jostnes

### PR DESCRIPTION
**Pull request by samiuelson**
This PR fixes 

Closes: #8623 

### Description

Bug: when in the Product selector screen (e.g. Orders > + > + Add products) and having some items selected and going out of the app (e.g. moving app to background) the app crashes.

The current implementation of `ProductSelectorViewModel` handles state of selected items using `Set` data structure. It turnes out the `Set` of `Parcelable` instances is not parcelable itself, resulting in the exception:
```kotlin
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = java.util.LinkedHashSet)
```
That's why I'm changing to using the `List` instead.

### Testing instructions

1. Go to the Product selector screen (e.g. Orders > + > + Add products)
2. Select some items
3. Go out of the app, and go back to the app
4. Verify that state of the selected items is preserved

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt [hunk 1]
```diff
@@ -75,7 +75,7 @@ class ProductSelectorViewModel @Inject constructor(
 
     private val searchQuery = savedState.getStateFlow(this, "")
     private val loadingState = MutableStateFlow(IDLE)
-    private val selectedItems = savedState.getStateFlow(viewModelScope, navArgs.selectedItems.toSet())
+    private val selectedItems = savedState.getStateFlow(viewModelScope, navArgs.selectedItems.toList())
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt]: While it works I can not understand a couple of things here:
* Original crash caused by `Caused by: java.io.NotSerializableException: com.woocommerce.android.ui.products.selector.ProductSelectorViewModel$SelectedItem$Product`, so why using `ArrayList` instead of `HashedLinkedList` works? Are items inside the `ArrayList` stored/restored as parseable, and in the set as Serializable?
* Before we were making a set out of the passed array, did we try to make sure that items are unique? We are changing this here - is this intentional?
* I noticed that if we do not pass `key` to `getStateFlow` then the class name is used and in our case, it's `kotlin.collections.EmptyList`. It feels like collision is quite possible with this approach, so maybe add custom key here?

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt]: Thanks for the review, @kidinov! 

> Are items inside the ArrayList stored/restored as Parceable, and in the set as Serializable?

Yes, that's true indeed - even though the `SelectedItem` class is Parcelable, if we use `Set` as a container it's treated as a Serializable value by SavedStateHandle and Bundle. 

**More details**: In the end it all comes down to Bundle's API. The `ArrayList` is a _first-class_ Parcelable [container](https://developer.android.com/reference/android/os/Parcel.html#parcelable-containers) supported by `Bundle`. We can also verify this by browsing the sources of [SavedStateHandle.kt](https://github.com/androidx/androidx/blob/androidx-main/lifecycle/lifecycle-viewmodel-savedstate/src/main/java/androidx/lifecycle/SavedStateHandle.kt) and [Bundle.java](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/os/Bundle.java#L366). Bundle has a special method for writing Parcelable items from `ArrayList` ([::putParcelableArrayList](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/os/Bundle.java#L514)), and in the case of `LinkedHashSet` it treats it as Serializable ([::putSerializable](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/os/Bundle.java#L589)) - and in our case, the Set doesn't contain Serializable items. That's the reason for the crash, and why `ArrayList` fixes the crash. 

> Before we were making a set out of the passed array, did we try to make sure that items are unique? We are changing this here - is this intentional?

It was for the sake of performance, IMO, redundant, because as you can see in the view model, in all the places we read the value of `selectedItems`, it's transformed to a Set as well for performance reasons of collections processing. In case of having duplicated items passed by mistake in navArgs, we wouldn't be hurt anyway, because we don't rely on the fact items are distinct anywhere.

> I noticed that if we do not pass key to getStateFlow then the class name is used and in our case, it's kotlin.collections.EmptyList. It feels like collision is quite possible with this approach, so maybe add custom key here?

Yes, the key can either be `EmptyList`, `List`, or even `MutableList`. I think there wouldn't be collisions since we don't (de)serialize any other collections with the same SaveStateHandle, but I agree it's safer to do it with a custom key. Fixed with a49890a8d33307eea356c2bd9171254e2c705e4c.

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt]: Thank you for the explanation! Got it... at least partially, because I couldn't understand within a short timespan how exactly `SavedStateHandle` stores the data into the bundle 🤷‍♂️

Anyway, the UI test caught a crash, that should be fixed before merging:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Set
at com.woocommerce.android.ui.products.selector.ProductSelectorFragment$setupObservers$1.invoke(ProductSelectorFragment.kt:70)
```

Other than that LGTM - marking the PR as approved

**Review by kidinov — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt (hunk 1 above)
Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/selector/ProductSelectorViewModel.kt]: Huh, these tests saved my butt 🤦🏼 

I forgot to adjust the type of the expected result of selected items. Fixed with 1374d46ec00c56046c97d736d2a633ae816144f0.
