### PR TITLE
Use the custom WCMaterialEditTextView for input fields in dialog

### LINKED ISSUE #2306: Support: Email field length ("0/50") in support email dialog never changes
**Describe the bug**

When I go to Help & Support > Contact email, a dialog appears where I can enter my email address. Under the email field, it looks like it's supposed to count the number of characters in my email address. However, it always says `0 / 50` — the number never updates while I'm typing or after I finish typing my email in that field.

**To Reproduce**

1. Go to Help (during login) or Help & Support (after login).
2. Select "Contact email."
3. Notice that a "Please enter your email address" dialog appears with `0 / 50` under the Email field.
4. Enter your email address in the email field. Notice the number `0 / 50` doesn't change.

**Screenshots**

**Expected behavior**

I expect the number `0` to update with the number of characters I type in the Email field.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.1-rc-1

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #2306 by swapping out the `TextInputLayout`'s in the support email dialog and replacing it with the custom `WCMaterialEditTextViews`'s. This is to give a more consistent UI and fixing the issue with the counter showing up when the name field is hidden, as well as fixing the way error messages are displayed.

Before | After 
-- | --
Screenshot_1587773236|Screenshot_1587772660
Screenshot_1587772725|Screenshot_1587772691

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedEditTextView.kt [hunk 1]
```diff
@@ -20,9 +20,20 @@ import com.woocommerce.android.R
...
+ * - Set the text on the child [TextInputEditText]
+ * - Set the selected text on the child [TextInputEditText]
  *
+ * The entire view acts as a single component. The following attributes have been exposed to this view as
+ * custom attributes and are used to interact with the nested [TextInputEditText] component:
+ * - [android:inputType]
+ * - [android:maxLength]
+ * - [android:enabled]
+ * - [android:text]
  */
```
Comment (anitaa1990) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedEditTextView.kt:37]: <3
