### PR TITLE
Fix deactivating shipping address not causing `Done` button to be visible

### LINKED ISSUE #5692: [Order Creation] Deactivating the shipping toggle doesn't trigger any changes
When inside the Order Creation form after submitting a different Billing and Shipping address, if we enter back the Address form to edit the current input, disabling the `Use a different Shipping address` doesn't trigger any changing detection, making it impossible to revert the Shipping address to be equal to the Billing address in an easy way.

https://user-images.githubusercontent.com/5920403/151240206-abeb8f13-650b-4d3d-a579-c152b242956b.mp4

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #5692 

### Description

This PR fixes an issue of not showing `Done` button (and allowing user to save change) if user entered `Edit` of Customer with shipping and billing addresses being different (see video).

### Testing instructions

1. Go to Order Creation
2. Add customer: make sure shipping and billing addresses are different
3. Save the change
4. **Assert that shipping and billing addresses are saved correctly**
5. Click on `Edit` for `Customer` section
6. **Assert the `Done` button is not visible**
7. Uncheck "Add a different shipping address" checkbox
8. **Assert the `Done` button is visible**

### Images/gif

https://user-images.githubusercontent.com/5845095/152539028-7b96efa6-4cdb-4a3e-b476-5b21c48e1173.mov

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt [hunk 1]
```diff
@@ -48,6 +50,19 @@ class AddressViewModel @Inject constructor(
...
+
+    val shouldShowDoneButton = isAnyAddressEdited.combineWith(
+        isDifferentShippingAddressChecked,
+        viewStateData.liveData.map { it.addressSelectionStates[AddressType.SHIPPING]?.address }
+    ) { isAnyAddressEdited, isDifferentShippingAddressChecked, shippingAddress ->
+        val isDifferentShippingAddressDisabled =
+            isDifferentShippingAddressChecked == false && (shippingAddress != Address.EMPTY)
+
+        isAnyAddressEdited == true || isDifferentShippingAddressDisabled
+    }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt:64]: This is kind of logic I wanted to not include into `AddressViewModel` as it only applies to address form in context of having 2 addresses on screen at once, but on the other hand adding this logic directly in `OrderCreationCustomerAddFragment` feels very wrong and makes testing much more complicated.

I believe it's okay to have it here.

**Review by ThomazFB — APPROVED** [review]
The fix is working nicely, @wzieba, thank you a lot for fixing this 🙇 . LGTM :shipit:
