### PR TITLE
issue/4200-save-as-draft-6.9

### LINKED ISSUE #4200: Products: Save as Draft Stopped Working in 6.9+
**Describe the bug**

The _Save as Draft_ button that is shown when navigating away from a new product detail page no longer saves the product as draft. 

Works fine in 6.8.

**To Reproduce**

1. Tap Products tab  → Big plus button
2. Enter a product title.
3. Navigate back 
4. A dialog will be shown. Tap on Save as Draft. 

Check the website. The product that was supposed to be a draft has been published.

**Screenshots**

**Expected behavior**

The product should not be visible on the website. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: 

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4200 - Note that this targets `release/6.9`. To test:

- In the product list, tap to create a product
- Start typing a title
- Hit the back button
- When the dialog below appears, choose "Save as draft"
- Verify that the product is saved as a draft rather than published

Screenshot_20210615_130945

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 1]
```diff
@@ -654,8 +653,8 @@ class ProductDetailViewModel @Inject constructor(
         }
     }
 
-    private fun startPublishProduct(exitWhenDone: Boolean = false) {
-        updateProductDraft(productStatus = PUBLISH)
+    private fun startPublishProduct(productStatus: ProductStatus = PUBLISH, exitWhenDone: Boolean = false) {
+        updateProductDraft(productStatus = productStatus)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:656]: Do you happen to know why we added this call to `updateProductDraft` here? from what I see it was added in this commit: 39f97646c0b16f3dccef54f83167003f4a8f1148, but I don't really understand its role.

I tested the app after removing only this line of code (and keeping the `updateProductDraft` call in the listener, and it seems to fix the issue, without impacting the variable product creation, I don't know if I'm missing an edge case or something.

If we want to keep the `updateProductDraft` here, I'm wondering if we shouldn't remove the call from this line: https://github.com/woocommerce/woocommerce-android/blob/a8547241529471b7e53e42bf0367e34eea90face/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt#L617 and make it similar to the dialog listener.

**Review by hichamboushaba — APPROVED** [review]
Thanks @nbradbury for working on this, the fix works without issues.
I just left one comment to discuss the cause of the issue, but it's not a blocker if we want to move forward with the fix.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:656]: > If we want to keep the updateProductDraft here, I'm wondering if we shouldn't remove the call from this line:

Oof, thank you for catching that - I should've caught that myself. Fixed in f77dc68.

> Do you happen to know why we added this call to updateProductDraft here?

~~My guess is Thomaz added `updateProductDraft(productStatus = PUBLISH)` to ensure the status was published, since we can't generate variations for draft products.~~

Scratch that, I'm not sure that's correct.

I think passing the product status to `startPublishProduct()` is good, but I'm fine to make your suggested changes if it's important.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:656]: Yes, I'm fine with that too, I asked just to know if there was a reason for it, because it's what caused the bug 🙂
