### PR TITLE
[WOO POS]M2: Prevent Multiple Instances of Card Reader Connect Dialog

### LINKED ISSUE #12203: [Woo POS] Multiple Instances of Card Reader Connection Dialog on Repeated Clicks of "Connect to Reader" Button
**Describe the bug**
When the "Connect to Reader" button is clicked multiple times in quick succession, it triggers the card reader connection dialog to open multiple instances. This behaviour is not expected, as it can confuse users and potentially lead to unintended interactions with the card reader.

**To Reproduce**
Steps to Reproduce:

1. Navigate to the settings screen and ensure you see Point of sale option
2. Click on the point of sale option
3. Ensure you see the "Connect to Reader" button is available.
4. Click on the "Connect to Reader" button multiple times quickly.
5. Observe that multiple instances of the card reader connection dialog are opened.

**Screenshots**

https://github.com/user-attachments/assets/f22cc1e2-5793-489d-8722-bc35ba2f3647

**Expected behavior**
Clicking the "Connect to Reader" button should only open a single instance of the card reader connection dialog. Subsequent clicks should be ignored.

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12203 

### Description

This PR addresses an issue where multiple successive clicks on the connect card reader button could create multiple instances of the card reader connect dialog. The solution ensures that only one instance of the dialog is created, preventing redundancy and improving the user experience.

Key Changes:

Implemented a mechanism to block multiple successive clicks that could trigger the dialog.
Ensured that only a single instance of the card reader connect dialog is displayed at a time.

### Steps to reproduce

1. Navigate to the POS mode from settings
2. Continuously click on the "Connect to card reader" button
3. Notice multiple instances of Card reader connect dialog appears on the screen

### Before
[Watch the before video](https://github.com/user-attachments/assets/994891a9-9690-46a4-b885-5491ab6f851a)

### After
[Watch the after video](https://github.com/user-attachments/assets/ce1e054a-4c16-4cce-947b-a0cef7a690f8)

- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt [hunk 1]
```diff
@@ -107,5 +123,12 @@ class WooPosToolbarViewModel @Inject constructor(
                 icon = R.drawable.woopos_ic_exit_pos,
             ),
         )
+
+        private const val DEBOUNCE_TIME_MS = 800L
+    }
+
+    override fun onCleared() {
+        super.onCleared()
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt]:
```suggestion
```
It does nothing and is not required by the parent class by @CallSuper annotation.

**Review by samiuelson — APPROVED** [review]
LGTM! :shipit: Left just a tiny, non-blocking nit-pick

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/toolbar/WooPosToolbarViewModel.kt]: Thanks for the suggestion. Removed it. https://github.com/woocommerce/woocommerce-android/pull/12218/commits/86983c819c629391e733ce1947e9a9438dfb0b80

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/229">19.9</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
