### PR TITLE
Media Upload: check url before marking upload as successful

### LINKED ISSUE #4336: EventBusException: Invoking subscriber failed
Sentry Issue: [WOOCOMMERCE-ANDROID-P](https://sentry.io/organizations/a8c/issues/1079436016/?referrer=github_integration)

```
NullPointerException: event.media.url must not be null
    at com.woocommerce.android.media.MediaFilesRepository.onMediaUploaded(MediaFilesRepository.kt:78)
...
(6 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:530)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:512)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:106)
...
(5 additional frame(s) were not displayed)
```

### LINKED ISSUE #4827: NullPointerException: this.fileName must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-2BP](https://sentry.io/organizations/a8c/issues/2662557274/?referrer=github_integration)

```
NullPointerException: this.fileName must not be null
    at com.woocommerce.android.model.ProductKt.toAppModel(Product.kt:555)
    at com.woocommerce.android.ui.products.ProductImagesViewModel$observeImageUploadEvents$2.invokeSuspend(ProductImagesViewModel.kt:197)
    at com.woocommerce.android.ui.products.ProductImagesViewModel$observeImageUploadEvents$2.invoke
    at com.woocommerce.android.ui.products.ProductImagesViewModel$observeImageUploadEvents$2.invoke
    at com.woocommerce.android.ui.media.MediaFileUploadHandler.observeSuccessfulUploads
...
(42 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #4336 and #4827

### Description
I couldn't reproduce any of the issues, but it seems that having `event.completed == true` is not enough to say that the upload succeeded, as we may still get a null `url` or `fileName` (I tried checking FluxC to see in what circumstances this would occur, but I can't figure it out)

And there will be more cases of the first issue #4336, since it was affecting only downloadable files, but it will impact image uploads as well in 7.6, since they use MediaFileRepository now.

Those issues haven't been causing crashes for image uploads before, because they were failing silently, since `ProductImageServices` was [posting](https://github.com/woocommerce/woocommerce-android/blob/698cfbce899d317bedd334b080ce865e22d1a1e1/WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesService.kt#L258) the events in a default `EventBus` instance, which means the exceptions were swallowed (`throwSubscriberException` is false by default), and the upload would fail silently, which is a bad user experience.

### Testing instructions
A small smoke test for image and downloadable file uploads should be enough.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt [hunk 1]
```diff
@@ -96,6 +100,7 @@ class MediaFilesRepository @Inject constructor(
                         event.media,
                         event.error.type,
                         event.error.message
+                            ?: resourceProvider.getString(R.string.product_image_service_error_uploading)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt:103]: I don't see any errors in Sentry because of this, but as it happened before, I'm following the same fix that was done in https://github.com/woocommerce/woocommerce-android/pull/4672

**Comment by hichamboushaba** [comment]
@jkmassel this PR targets 7.6, but I don't think it's too urgent, we can wait few days to see if there other issues that we should fix and include in the same build.

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:
