### PR TITLE
Barcode scanning - Handle failure case

### LINKED ISSUE #9073: Handle error case when the barcode scanning fails
The aim of this task is to handle the case when the barcode scanning fails. We will be showing a `Snackbar` with the "retry" action which retries the barcode scanning all over again when clicked.

More context: pecCkj-GT-p2

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #9073 

### Description

This PR handles failure when 
1. The barcode scanning fails
2. The product search by SKU fails

We show a `Snackbar` with a "retry" action in both cases. Clicking on the "retry" action will trigger the scanning process.

More context: pecCkj-GT-p2

#### Order listing screen
1. Navigate to the Orders tab
2. Click on the barcode icon present on the toolbar
3. Scan the barcode (Make sure to generate the barcode with an **invalid SKU** not present in your store - example: https://barcode.tec-it.com/en/?data=invalid_sku)
4. Ensure you see the snack bar
5. Ensure the retry action starts the scanning process again

#### Order detail screen
1. Navigate to the Order details screen (orders -> "+")
2. Click on the barcode icon present under the products section
3. Scan the barcode (Make sure to generate the barcode with an **invalid SKU** not present in your store - example: https://barcode.tec-it.com/en/?data=invalid_sku)
4. Ensure you see the snack bar
5. Ensure the retry action starts the scanning process again
### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/1331230/efab7c00-e539-4dd4-bd44-cb8f324beaae

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 1]
```diff
@@ -734,6 +760,18 @@ class OrderCreateEditViewModel @Inject constructor(
     }
 }
 
+data class OnBarcodeScanningFailed(
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Both these event models might look similar in code but their behavior might change in the near future. Also, the code can be confusing to understand when we merge both into one. Let me know your thoughts.

File: WooCommerce/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -548,6 +548,7 @@
     <string name="order_creation_customer_search_empty">No customers found</string>
     <string name="order_creation_customer_search_hint">Search customers</string>
     <string name="order_creation_change_product_quantity">Change the product quantity from %1$d to %2$d</string>
+    <string name="order_creation_barcode_scanning_unable_to_add_product">Product not found. Unable to add to new order</string>
```
Comment (kidinov) [inline WooCommerce/src/main/res/values/strings.xml:551]: Should it be "to the new order"? Or maybe just "to the order"?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 3]
```diff
@@ -351,9 +353,33 @@ class OrderCreateEditViewModel @Inject constructor(
...
+            } ?: run {
+                sendProductSearchBySKUFailedEvent()
             }
         }
     }
+
+    private fun sendBarcodeScanningFailedEvent(error: Throwable?) {
+        triggerEvent(
+            OnBarcodeScanningFailed(
+                error,
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Error property is never used in both events in the production code? In `OnBarcodeScanningFailed` and `OnProductSearchBySKUFailed`

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: I'd go with 1 event at the beggining, e.g. `OnAddingProductViaScaningFailed` (we don't only support barcodes but other types of encoding of the data) and will pass 2 different messages there: `Scanning failed with error: %s` and `Unable to find product with SKU: %s`. That should give more information to a user

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt [hunk 4]
```diff
@@ -21,7 +25,12 @@ class GoogleCodeScanner @Inject constructor(private val scanner: GmsBarcodeScann
                     this@callbackFlow.close()
                 }
                 .addOnFailureListener { throwable ->
-                    this@callbackFlow.trySend(CodeScannerStatus.Failure(throwable.cause))
+                    this@callbackFlow.trySend(
+                        CodeScannerStatus.Failure(
+                            error = throwable.message,
+                            type = errorMapper.mapGoogleMLKitScanningErrors(throwable as? MlKitException)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt]: If the throwable is not MlKitException then we always map it to "Other" and this doesn;t contain any information about what's happened. We may want to pass throwable to the mapper, and handle non MlKitException  it differently - at least pass them to "Other" so we can track it latter on to tracks

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleCodeScannerErrorMapper.kt [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+            UNAUTHENTICATED -> CodeScanningErrorType.UnAuthenticated
+            UNAVAILABLE -> CodeScanningErrorType.UnAvailable
+            UNIMPLEMENTED -> CodeScanningErrorType.UnImplemented
+            UNKNOWN -> CodeScanningErrorType.Unknown
+            else -> CodeScanningErrorType.Other
+        }
+    }
+
+    private companion object {
+        private const val ABORTED = 10
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleCodeScannerErrorMapper.kt]: We could use `MlKitException.ABORTED` and so on?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 6]
```diff
@@ -312,7 +314,7 @@ class OrderCreateEditViewModel @Inject constructor(
             codeScanner.startScan().collect { status ->
                 when (status) {
                     is CodeScannerStatus.Failure -> {
-                        // TODO handle failure case
+                        sendBarcodeScanningFailedEvent()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Now when we have more information on what exactly went wrong, would it make sense to show it to a user?

**Review by kidinov — COMMENTED** [review]
I left a few comments, please take a look

File: WooCommerce/src/main/res/values/strings.xml (hunk 2 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/res/values/strings.xml:551]: As per the design, it is "to the new order". I believe the thought process behind that is that the successful scanning results in the creation of new order. WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt (hunk 4 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/CodeScanner.kt]: Good point. Done here: https://github.com/woocommerce/woocommerce-android/pull/9082/commits/b3bf3e790f4704d3859ee0ceb8180debf6286724

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleCodeScannerErrorMapper.kt (hunk 5 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleCodeScannerErrorMapper.kt]: Oops. Not sure what I was thinking when I wrote this. Good suggestion. https://github.com/woocommerce/woocommerce-android/pull/9082/commits/300712411d648804c49f23427397c6f7055cf9e9

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 6 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Agree. However, I might need to discuss this with Ann before implementing this change since displaying quite a few words in a Snackbar might not be the best user experience. 

With that said, We will track all these errors in the first release. I'll discuss this with Ann and see how we can better inform users about the failures in the next release.

How does this sound?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 3 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Strange. I had already removed the error property from both events. In the latest file change, it's not shown.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 6 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Well, I would go right away with maybe not ideal, but at least some information given to the users, then with nothing, but this is your call at the end

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 7]
```diff
@@ -351,9 +353,21 @@ class OrderCreateEditViewModel @Inject constructor(
...
+            } ?: run {
+                sendAddingProductsViaScanningFailedEvent()
             }
         }
     }
+
+    private fun sendAddingProductsViaScanningFailedEvent() {
+        triggerEvent(
+            OnAddingProductViaScanningFailed(
+                string.order_creation_barcode_scanning_unable_to_add_product
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Now you show the same text `Product not found. Unable to add to new order` for both cases - when scanning failed (including when the scanning is not available at all) and when we could not find a product by SKU

**Review by kidinov — COMMENTED** [review]
I left a comment regarding the text currently used for error indication - it may be missliding

**Review by kidinov — COMMENTED** [review]
I left a comment regarding the text currently used for error indication - it may be missliding

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 7 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Added a separate message for both failure events here: https://github.com/woocommerce/woocommerce-android/pull/9082/commits/aaeccebf7300fdbf76e301691751280715928622

Right now, the messages are static without much information on what went wrong. This will be taken on priority and will be discussed with Ann and should be out by next week after the initial release.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 6 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Makes sense. I'll create a separate PR to do this and see if I can push this into this week's release. If not, it will go in next week's release.

**Review by kidinov — APPROVED** [review]
LGTM!
