### PR TITLE
[Receipts] IO Exception crash

### LINKED ISSUE #13410: FileNotFoundException:
Sentry Issue: [WOOCOMMERCE-ANDROID-JFX](https://a8c.sentry.io/issues/6252491481/?referrer=github_integration)

```
RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:598)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

InvocationTargetException: None
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

IOException: Failed to read content from receipt URL: <redacted>
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment.interceptAndModifyReceiptResponse(ReceiptPreviewFragment.kt:132)
    throw IOException("Failed to read content from receipt URL: ${request.url}", e)
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment.access$interceptAndModifyReceiptResponse(ReceiptPreviewFragment.kt:28)
    @AndroidEntryPoint
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment$initViews$1$1.shouldInterceptRequest(ReceiptPreviewFragment.kt:105)
    return interceptAndModifyReceiptResponse(request)

FileNotFoundException: <redacted>
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment.interceptAndModifyReceiptResponse(ReceiptPreviewFragment.kt:119)
    val inputStream = connection.getInputStream()
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment.access$interceptAndModifyReceiptResponse(ReceiptPreviewFragment.kt:28)
    @AndroidEntryPoint
    at com.woocommerce.android.ui.payments.receipt.preview.ReceiptPreviewFragment$initViews$1$1.shouldInterceptRequest(ReceiptPreviewFragment.kt:105)
    return interceptAndModifyReceiptResponse(request)
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #13410 

### Description

We are crashing on IOException when loading a receipt. The PR logs the case and return null which means keep loading

### Steps to reproduce

* Put break point on `openConnection`
* Load a receipt
* When break point hits it, disabled internet
* Resume -> Notice crash

### The tests that have been performed

Above

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/248">21.5 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewFragment.kt [hunk 1]
```diff
@@ -101,9 +106,12 @@ class ReceiptPreviewFragment : BaseFragment(R.layout.fragment_receipt_preview),
                     override fun shouldInterceptRequest(
                         view: WebView,
                         request: WebResourceRequest
-                    ): WebResourceResponse? {
-                        return interceptAndModifyReceiptResponse(request)
-                    }
+                    ): WebResourceResponse? =
+                        if (request.url.toString() == urlToLoad) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/receipt/preview/ReceiptPreviewFragment.kt:110]: The idea is to modify the response only on the root page. Otherwise, we change mimeType for all the page resources which externally placed (icons, css, js)

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this. LGTM :shipit:

**Comment by ThomazFB** [comment]
This is just an update that the changes introduced here are published as a beta through the version `21.5-rc2` and was merged back in the trunk through https://github.com/woocommerce/woocommerce-android/pull/13425
