### PR TITLE
[Blaze] Fix date formatting for the campaign creation API request

### LINKED ISSUE #12370: [Blaze] Update campaign creation request to respect the ISO date format
Currently, when sending the campaign creation request, the app sends the date formatted using the device's locale, which might result when using some languages such as Arabic in using digits other than regular Arabic numerals (for example: `٢٠٢٤-٠٧-٠٨`), which is not a standard ISO date format.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12370

### Description
This PR fixes the issue of the parent issue: which is to ensure the date formatting for the Blaze campaign request respects the ISO standard by using the regular Arabic numerals always.

This PR just updates FluxC, the actual fix is in FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3085

### Steps to reproduce
1. Using `trunk`
2. Switch your device (or the app) to the Arabic language (Choose **Arabic(Egypt) العربية(مصر)** to ensure using Indo-Arabic numerals).
3. Attempt to create a Blaze campaign.
4. Notice the failure.

### Testing information
1. Switch to this branch
2. Switch your device (or the app) to the Arabic language (Choose **Arabic(Egypt) العربية(مصر)** to ensure using Indo-Arabic numerals).
3. Attempt to create a Blaze campaign.
4. Confirm the creation succeeded.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/232">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt [hunk 1]
```diff
@@ -150,7 +150,9 @@ fun Toolbar(
                     Icon(
                         navigationIcon,
                         contentDescription = navigationIconContentDescription,
-                        modifier = Modifier.autoMirror()
+                        modifier = Modifier.then(
+                            if (navigationIcon.autoMirror) Modifier else Modifier.autoMirror()
+                        )
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt:155]: When using the app in Arabic, I noticed an issue with the navigation icon, this logic fixes it.

For context, the [PR](https://github.com/woocommerce/woocommerce-android/pull/11330) refactored the navigation icon to use the new `AutoMirrored` set, but since we already had our logic to `autoMirror` the icons manually, this meant the icons were going back to their original direction, with this check now, we ensure that the manual logic is still called when needed, but for the icons already auto-mirrored, we'll do nothing.

**Review by JorgeMucientes — APPROVED** [review]
Thanks for fixing this @hichamboushaba, I verified that the bug is fixed and campaigns can be created correctly. 
:shipit:
