### PR TITLE
Fix date range picker issues with TimeZone

### LINKED ISSUE #12885: Date Ranges picked using the date picker across the app can result in shifted dates in some timezones
Currently, the app has a few features that use a date range picker; we use the official material one, `MaterialDatePicker`, but the component has an issue with timezones that result in shifted dates when the timezone has a negative offset, this was reported as bug here https://github.com/material-components/material-components-android/issues/882, and although the ticket is closed, the issue is still reproducible.

##### Issue reported internally here p1730982809165539-slack-C6H8C3G23

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12885 

### Description
This PR fixes an issue with the `MaterialDatePicker`, as stated in the ticket above, the component is buggy, it uses UTC internally, so when we get the result from it (as epoch time), it ends up shifted depending on the device timezone.

The fix is to shift the time to UTC before passing it to the date picker, then shift it back to the device timezone when we get the picked date.

### Steps to reproduce
1. Set you phone to a US timezone (for example NewYork)
2. Open the app and make sure the performance card is added.
3. Select a custom range.
4. Confirm the dates shown in the card matches the picked dates in the picker.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/243">21.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt [hunk 1]
```diff
@@ -198,19 +201,38 @@ fun Fragment.showDateRangePicker(
...
+        // The timestamps returned by the MaterialDatePicker are in UTC timezone, if we use them directly
+        // we will get a shift in the selected range.
+        // To avoid this, we get the local date using UTC timestamps and then convert it to the selected timezone
+        // See: https://github.com/material-components/material-components-android/issues/882
+        val originalDateTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(time), originalZoneId).toLocalDateTime()
+        val targetDateTime = ZonedDateTime.of(originalDateTime, targetZoneId)
+        return targetDateTime.toInstant().toEpochMilli()
+    }
+
+    val deviceZoneId = ZoneId.systemDefault()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt:214]: We use the device timezone here, and I'll explain why below:
On my first attempt, I thought that since we want the date calculations to use the site timezone, then I'll pass it, but then it resulted in many issues, and the cause was that we use the device timezone for formatting the date later, and also before [passing](https://github.com/woocommerce/woocommerce-android/blob/01ed20fb72073d2054f89e6141ced69da33ff4ac/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/data/StatsRepository.kt#L86-L87) it to the API.

So, I then decided to use the device timezone, and hopefully this should work without issues for most of the cases\*, as the date format we pass to the API doesn't use any timezone information.

\* Using the device timezone could still cause issues where DST is involved, but fixing it would require all of our date handling to use the correct site timezone, which is a very significant change.

**Review by JorgeMucientes — APPROVED** [review]
Works great @hichamboushaba! 

Nice job discovering the cause of the date discrepancy and quickly resolving it! 
And kudos to @rossanafmenezes for reporting it!
