### PR TITLE
issue/3841-phoneno-format-nullpointer-fix

### LINKED ISSUE #3841: NullPointerException: if (Build.VERSION.SDK_IN…ber(number)
Sentry Issue: [WOOCOMMERCE-ANDROID-1FM](https://sentry.io/organizations/a8c/issues/2322974664/?referrer=github_integration)

```
NullPointerException: if (Build.VERSION.SDK_IN…ber(number)
            } must not be null
    at com.woocommerce.android.util.PhoneUtils.formatPhone(PhoneUtils.kt:14)
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.updateCustomerInfo(OrderDetailCustomerInfoView.kt:82)
    at com.woocommerce.android.ui.orders.details.OrderDetailFragment.showOrderDetail(OrderDetailFragment.kt:215)
    at com.woocommerce.android.ui.orders.details.OrderDetailFragment.access$showOrderDetail(OrderDetailFragment.kt:61)
    at com.woocommerce.android.ui.orders.details.OrderDetailFragment$setupObservers$1.invoke(OrderDetailFragment.kt:132)
...
(21 additional frame(s) were not displayed)

if (Build.VERSION.SDK_IN…ber(number)
            } must not be null
```

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3841. It looks like the method [PhoneNumberUtils.formatNumber(number,Locale.getDefault().country)](https://github.com/woocommerce/woocommerce-android/blob/714bc66bf8c77a450f0971ef336e39aeb4c51c18/WooCommerce/src/main/kotlin/com/woocommerce/android/util/PhoneUtils.kt#L15) returns a null value when the given phone number is not valid. This PR just updates the method to return the default phone number regardless of the exception that is thrown. 

#### To test
- Open an order from `wp-admin` of your test store.
- Enter a random phone number for the billing address. Sample: `85301473669909094861`.
- Open the order in the app and notice that the app no longer crashes.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/PhoneUtils.kt [hunk 1]
```diff
@@ -17,7 +17,7 @@ object PhoneUtils {
                 @Suppress("DEPRECATION")
                 PhoneNumberUtils.formatNumber(number)
             }
-        } catch (e: IllegalStateException) {
+        } catch (e: Exception) {
             WooLog.d(T.UTILS, "Unable to format phone number: $number")
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/PhoneUtils.kt]: np: Let's change this to `WooLog.e` and include the exception in the log. Also, while this is being changed we can get rid of the `Build.VERSION.SDK_INT` check since Lollipop is our min SDK version.

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/PhoneUtils.kt]: Good point! Fixed in 4f25b7c

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:
