### PR TITLE
Remove duplicate toolbar from package details screen

### LINKED ISSUE #12236: Toolbar appearing twice in Package details screen
**Describe the bug**
We are displaying Toolbar 2 times in package detail screen while creating Shipping label. 

**To Reproduce**
1. Navigate to order detail screen which is eligible for creating Shipping label
2. Click on Shipping Label button
3. Enter from and to address
4. Navigate to package detail screen
5. We see two toolbar instead of one

**Screenshots**
package_details_multiple_toolbar

**Expected behavior**
We should be seeing just a single toolbar in Package details screen

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12236 

### Description

This PR removes the duplicate toolbar from the Shipping Package Details screen.

### Steps to reproduce

1. Navigate to order detail screen which is eligible for creating Shipping label
2. Click on Shipping Label button
3. Enter from and to address
4. Navigate to package detail screen
5. We see two toolbar instead of one

### Testing information

I've tested this on my Pixel 4a device by navigating to Package details screen and ensured just a single toolbar is visible.

### The tests that have been performed

Ensure that single toolbar is shown in package details screen.

### Before
Before

### After
After

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt [hunk 1]
```diff
@@ -50,6 +51,9 @@ class EditShippingLabelPackagesFragment :
 
     private lateinit var doneMenuItem: MenuItem
 
+    override val activityAppBarStatus: AppBarStatus
+        get() = AppBarStatus.Hidden
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt]:
```suggestion
```
What do you think about switching from `BaseFragment` supertype to `Fragment`? This would allow us to reduce inheritance levels, and clean up the code. The main advantage of `BaseFragment` is that it provides the title and subtitle of the screen. In this case we rely on the Toolbar in `R.layout.fragment_edit_shipping_label_packages`, so it doesn't feel necessary to extend `BaseFragment`. Wdut?

**Review by samiuelson — COMMENTED** [review]
LGTM, however, I added a small suggestion to improve it further. Let me know what you think, @AnirudhBhat!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesFragment.kt]: Good point! I've made the changes as suggested here: https://github.com/woocommerce/woocommerce-android/pull/12489/commits/c06c3e8fa3a557b2511278473fd2a8e94441bf70

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/234">20.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — APPROVED** [review]
LGTM :shipit:
