### PR TITLE
Support decimal quantities in Orders, and fix shipping labels handling of them

### LINKED ISSUE #3808: Handle decimal quantities in order details
Related to #3611, we need to display the quantity as is in the order details, today, we are converting the quantity to Int, the conversion is done when mapping from data model to the business model, so it won't impact FluxC.

### LINKED ISSUE #4118: Shipping Labels: packaging step doesn't respect the items quantity
In the packaging step, we need to duplicate items depending on their quantity, currently this is not handled.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes #3808 and #4118.

Please don't merge before the FluxC's PR is merged: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2037

#### Testing
Please install the plugin [WPC Product Quantity for WooCommerce](https://wordpress.org/plugins/wpc-product-quantity/) in your store to use decimal quantities.

1. Create an order with decimal quantity > 1 in your store.
2. Go to order details in the app.
3. **Confirm** that you can see the correct quantity.
4. Click on "Create shipping label"
5. Pass the steps until you reach the packaging step.
6. **Confirm** that the items in the package are duplicated depending on their quantity.
7. Purchase the shipping label.
8. Open order details in the web client, and click on "View Details" of the label (https://d.pr/i/AmY0CH).
9. **Confirm** that the items match the correct quantity.
10. Go back to the order details in the app.
11. Click on "Issue a refund"
12. **Confirm** that the max quantity you can select is matching the integer part of the quantity.
13. Issue a refund with full max quantity.
14. In the order details: **Confirm** that the remaining quantity is correct, and that "issue a refund" is not visible

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt [hunk 1]
```diff
@@ -64,11 +64,12 @@ data class Order(
...
     val isAwaitingPayment = status == Pending || status == OnHold || datePaid == null
 
+    // Allow refunding only integer quantities
     @IgnoredOnParcel
-    val isRefundAvailable = refundTotal < total
+    val availableRefundQuantity = items.sumByFloat { it.quantity }.toInt()
 
     @IgnoredOnParcel
-    val availableRefundQuantity = items.sumBy { it.quantity }
+    val isRefundAvailable = refundTotal < total && availableRefundQuantity > 0
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt:72]: I changed the logic here to avoid showing "Issue a refund" button if we can't handle the refund in the app, this happens if the quantity is `null` or if it's < 1.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt [hunk 2]
```diff
@@ -178,7 +178,7 @@ class ShippingLabelRepository @Inject constructor(
                 serviceId = rate.serviceId,
                 serviceName = rate.serviceName,
                 carrierId = rate.carrierId,
-                products = labelPackage.items.map { it.productId }
+                products = labelPackage.items.map { item -> List(item.quantity) { item.productId } }.flatten()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt:183]: We identified the issue of the previous implementation just today: p1624622537119300/1624620001.117600-slack-C6H8C3G23

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt:183]: np: it would be great to maybe add a comment here to better understand the logic behind this change.

**Review by anitaa1990 — COMMENTED** [review]
The code changes look good @hichamboushaba! I have a few questions after testing though.

- When I have a product with quantity < 0, then that product is not eligible for refund. Is that correct? I found it a bit confusing that the product was not displayed in the refund list, even though it's displayed in the order detail.
- The quantity displayed in the refund screen is integers and not decimals.

#### Screenshot of order detail + refund screen
.

**Comment by hichamboushaba** [comment]
Thanks for the review Anitaa.
> When I have a product with quantity < 0, then that product is not eligible for refund. Is that correct? I found it a bit confusing that the product was not displayed in the refund list, even though it's displayed in the order detail.

This PR didn't make any change to this logic, and for me, the product isn't even displayed in the products section of the order details (because of [this](https://github.com/woocommerce/woocommerce-android/blob/5361df283ab23291e71795b6d5d693622b16cd69/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt#L105)). IMO we shouldn't spend a lot of time nor think a lot about negative quantities, as they are not supported in Woo Core, and refunding them using quantities in wp-admin doesn't work.

> The quantity displayed in the refund screen is integers and not decimals.

As we only support integer quantities for the refund, otherwise it would require bigger changes to the refund UI, I make sure the quantity passed to refund in integer, I'll see if changing the one displayed there to decimal while keeping the one used for refund is easy.

**Comment by hichamboushaba** [comment]
@anitaa1990 the commit 868985641f2963809e39e8dde06e0bec416d2ef2 updates the logic to allow displaying decimal quantities in refunds, while allowing refunding only integer values, please check it and let me know what you think

Screen Shot 2021-06-30 at 11 14 35

**Review by anitaa1990 — APPROVED** [review]
This works! Thanks @hichamboushaba! Definitely better than before :shipit:

**Comment by anitaa1990** [comment]
I'll wait for you to update the FluxC PR after merge and then merge this PR 👍

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/ShippingLabelRepository.kt:183]: Done 8702f46
