### PR TITLE
[Woo POS] UI issues fix with the cart screen

### LINKED ISSUE #12618: [Woo POS] UI issues with the cart screen
* Broken top shadow and maybe a missing bottom shadow for the cart products list
* The fade-out animation is too long -> get it back to 300
* The animation of the back arrow is too long -> get it back to 300
* And the cart not aligned with the products again

https://github.com/user-attachments/assets/d0c3ea8e-6eaa-4e4a-a53f-6accac400e8a

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12618

### Description

The PR:
* Fixes the broken top shadow and missing bottom shadow for the cart products list
* The fade-out animation is too long -> get it back to 300
* The animation of the back arrow is too long -> get it back to 300
* Changed outer padding from 32 to 24 on the products banner to match the design
* ~~And the cart not aligned with the products again~~ was fixed on the trunk already

### Testing information

Open the POS, notice the changes from the description. Try dark mode too

### The tests that have been performed

Only what in the testing information

### Images/gif

https://github.com/user-attachments/assets/83017b19-42fa-4a96-b2fc-619117c5f52b

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt [hunk 1]
```diff
@@ -64,110 +64,105 @@ fun WooPosBanner(
             modifier = Modifier
                 .fillMaxWidth()
         ) {
-            Box(
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosBanner.kt:67]: Redundant box was here

**Review by AnirudhBhat — APPROVED** [review]
LGTM :shipit:
