### PR TITLE
Address notifications

### LINKED ISSUE #12440: Verify destination address UI
Image

We should include the address status indicator to highlight whether the address is verified.

### LINKED ISSUE #12441: Missing destination address UI
Image

Design considerations:
> - Similar to unverified address
> - Empty state image and text change to suggest next action
> - Status indicator similar to unverified address
> - Make fields red only after a merchant unfocuses the field without filling in the info
> - But we can’t show shipping services until the address is filled out. So, we need to update the empty state graphic and text to prompt people to fill it in.

[More info](https://teameaglep2.wordpress.com/2024/08/19/shipping-label-purchase-flow-design-milestone-2-i1/#missing-destination-address)

### LINKED ISSUE #13322: Invalid/Not verified Ship from address
When the selected `ship-from` address is not valid or unverified, we should verify the address. Using a not valid address could make the shipping label purchase fail.

We don't have a design for this flow, but we can copy the same experience as in the `ship-to` address.

Image

https://teameaglep2.wordpress.com/2024/08/19/shipping-label-purchase-flow-design-milestone-2-i1/

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #12440
Closes: #12441
Closes: #13322

### Description
This PR adds the UI and logic to display the address notifications on top of the Shipment details sections. The PR includes the `GetAddressNotification` use case that will be in charge of triggering the notifications by analyzing the addresses and the previous notifications displayed. 

- Tapping on an error notification should navigate to the screen to update the address. 
- Tapping on the close button of an error notification should dismiss the notification
- If the issues with an error notification are fixed, we will show a success notification that will automatically disappear after a few seconds.

### Testing information
TC1

1. Open the orders tab
2. Tap on an order eligible for shipping label creation without a shipping address
3. Tap on Create shipping label
4. Check that the Missing address error notification is displayed

TC2

1. Open the orders tab
2. Tap on an order eligible for shipping label creation with an unverified shipping address
3. Tap on Create shipping label
4. Check that the Unverified address notification is displayed

TC3

1. Open the orders tab
2. Tap on an order eligible for shipping label creation with a verified shipping address
3. Tap on Create shipping label
4. Check that the Verified address notification is NOT displayed

TC4

1. Open the orders tab
2. Tap on an order eligible for shipping label creation with an unverified shipping address
3. Tap on Create shipping label
4. Check that the Unverified address notification is displayed
5. Tap on the notification
6. Update and verify the address
7. Check that the Verified address notification is NOT displayed

### The tests that have been performed
- Checked that the notifications are displayed
- Checked that a success notification is displayed after fixing the address
- Checked that success notification is auto-dismissed
- Checked that error notification can be dismissed

### Images/gif

https://github.com/user-attachments/assets/748d27a4-4db7-4a31-bb14-da5bc8540f7e

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.FlowPreview
+import javax.inject.Inject
+
+class GetAddressNotification @Inject constructor(
+    private val resourceProvider: ResourceProvider
+) {
+    @OptIn(ExperimentalCoroutinesApi::class, FlowPreview::class)
+    operator fun invoke(
+        addresses: WooShippingAddresses,
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt:10]: We need to receive the current address notifacion to check whether to display the success notification

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+}
+
+data class AddressNotification(
+    val isSuccess: Boolean,
+    val message: String,
+    val expireAfter: Long? = null,
+    private val timestamp: Long = System.currentTimeMillis(),
+    val isDestinationNotification: Boolean = false,
+) {
+    fun isExpired(): Boolean = expireAfter?.let {
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt:74]: Success notifications are auto-dismissable

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt [hunk 3]
```diff
@@ -67,10 +67,20 @@ private val darkGreen = Color(0xFF005C12)
 @Suppress("MagicNumber")
 private val lightGreen = Color(0xFFEDFAEF)
 
+@Suppress("MagicNumber")
+private val darkRed = Color(0xFFB32D2E)
+
+@Suppress("MagicNumber")
+private val lightRed = Color(0xFFF7EBEC)
+
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt]: Can we use [wc_colors_base.xml](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/res/values/wc_colors_base.xml) instead of adding hardcoded colors here. These colors are already defined there, making it easier to update the theme colors in the future. Same for `darkGreen` and `lightGreen`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt [hunk 4]
```diff
@@ -65,12 +82,15 @@ fun ShipmentDetails(
...
     shippingRateSummary: ShippingRateSummaryUI?,
+    addressNotification: AddressNotification?,
     modifier: Modifier = Modifier,
     isShipmentDetailsExpanded: Boolean = false,
     onShipmentDetailsExpandedChange: (Boolean) -> Boolean,
     onEditDestinationAddress: (DestinationShippingAddress) -> Unit,
+    onEditOriginAddress: (OriginShippingAddress) -> Unit,
     markOrderComplete: Boolean = false,
     onMarkOrderCompleteChange: (Boolean) -> Unit = {},
+    dismissAddressNotification: () -> Unit = {},
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt]: All events have the prefix `on`. I suggest renaming `dismissAddressNotification` to `onDismissAddressNotification`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt [hunk 5]
```diff
@@ -505,6 +545,106 @@ private fun ShipmentCostRow(
...
+                durationMillis = 90
+            )
+        ) + scaleOut(
+            animationSpec = androidx.compose.animation.core.tween(
+                durationMillis = 90
+            )
+
+        )
+    ) {
+        if (addressNotification != null && addressNotification.isExpired().not()) {
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:588]: > addressNotification != null && addressNotification.isExpired().not()

We used this condition here and also for `AnimatedVisibility`s `visible` property. Can we define a `visible` parameter at the top of the function and use it in both places?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt [hunk 6]
```diff
@@ -134,6 +142,22 @@ class WooShippingLabelCreationViewModel @Inject constructor(
         }
     }
 
+    @OptIn(FlowPreview::class, ExperimentalCoroutinesApi::class)
+    private suspend fun observeNotifications() {
+        shippingAddresses.filterNotNull()
+            .onStart { delay(NOTIFICATIONS_DELAY) }
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:155]: Why do we add delay? 🤔 Wouldn’t it be better to show the notification immediately whenever the data is ready?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt [hunk 7]
```diff
@@ -0,0 +1,88 @@
...
+import com.woocommerce.android.ui.orders.wooshippinglabels.WooShippingAddresses
+import com.woocommerce.android.viewmodel.ResourceProvider
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.FlowPreview
+import javax.inject.Inject
+
+class GetAddressNotification @Inject constructor(
+    private val resourceProvider: ResourceProvider
+) {
+    @OptIn(ExperimentalCoroutinesApi::class, FlowPreview::class)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: > OptIn(ExperimentalCoroutinesApi::class, FlowPreview::class)

The IDE shows a warning that this line is redundant.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt [hunk 8]
```diff
@@ -0,0 +1,88 @@
...
+            }
+
+            addresses.shipTo.isVerified &&
+                previousNotification?.let { it.isSuccess.not() && it.isDestinationNotification } == true -> {
+                AddressNotification(
+                    isSuccess = true,
+                    message = resourceProvider.getString(
+                        R.string.woo_shipping_address_notification_destination_verified
+                    ),
+                    expireAfter = 2_000,
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: np: We can use a const for `expireAfter = 2_000` in this class. It's also used below.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt [hunk 9]
```diff
@@ -0,0 +1,88 @@
...
+
+import com.woocommerce.android.R
+import com.woocommerce.android.ui.orders.wooshippinglabels.WooShippingAddresses
+import com.woocommerce.android.viewmodel.ResourceProvider
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.FlowPreview
+import javax.inject.Inject
+
+class GetAddressNotification @Inject constructor(
+    private val resourceProvider: ResourceProvider
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: I suggest not using `ResourceProvider` here. Since `ResourceProvider` is a context-aware class and we use `GetAddressNotification` class in view models, it's not ideal to use this in view models. This might cause issues when locales are changed. There is an open issue for this: #12116
We can use `StringRes` `int` values for `AddressNotification.message` as an alternative.

**Review by irfano — CHANGES_REQUESTED** [review]
Good job! It’s addressed in a clean way and works well. I’m adding some notes and issues I noticed.
- When I increased the font size, the notification box didn’t respond well. I think we should adjust its size accordingly.


- This is not related to this PR, but when I opened the “Edit Destination” screen, the country field didn’t turn red even though it’s required and empty.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt (hunk 3 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedScreen.kt]: Fixed here [dd69830](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/dd69830c67ca5d1efd1713785ddb5acd402f85ed)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt (hunk 4 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt]: Fixed here [ee92eb6](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/ee92eb6dc6037b18dd67c251130ae114a07667a6)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt (hunk 5 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:588]: > Can we define a visible parameter at the top of the function and use it in both places?

By saving the result in a variable, I will lose the smart-cast ensuring that `addressNotification` is not `null`. From both solutions, I will prefer having the null check on top of the if condition and forget about dealing with null checks, WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt (hunk 6 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:155]: > Wouldn’t it be better to show the notification immediately whenever the data is ready?

I decided to introduce a brief delay in requesting user attention after the UI loads, avoiding overwhelming them with too many changes at once when opening the screen.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt (hunk 7 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: Fixed here [d10fbb3](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/d10fbb3e840f05bb27c24efaacbf30c466b3cc04)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt (hunk 8 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: Fixed here [706e4d4](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/706e4d45647b4f9210e14edd1e951fc3b9ae0ba6)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt (hunk 9 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/address/GetAddressNotification.kt]: Fixed here [d10fbb3](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/d10fbb3e840f05bb27c24efaacbf30c466b3cc04)

**Comment by atorresveiga** [comment]
> This is not related to this PR, but when I opened the “Edit Destination” screen, the country field didn’t turn red even though it’s required and empty.

Good catch @irfano. I will fix this in a different PR

**Comment by atorresveiga** [comment]
@irfano Thanks for this great review! The PR is ready for another round

**Comment by atorresveiga** [comment]
> When I increased the font size, the notification box didn’t respond well. I think we should adjust its size accordingly.

Fixed here [5a46fee](https://github.com/woocommerce/woocommerce-android/pull/13651/commits/5a46fee24abd04d4237f3524ed33653e6edda3b4)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt (hunk 5 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:588]: Thanks for reviewing my comment and considering a solution. 

> I will prefer having the null check on top of the if condition and forget about dealing with null checks

This is the current code, right? Then, let's keep it as it is.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt (hunk 6 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:155]: Okay, I got it. So, it's a design decision. 👍🏻

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt [hunk 10]
```diff
@@ -100,14 +116,38 @@ fun ShipmentDetails(
...
+                                        onEditOriginAddress(shippingAddresses.shipFrom)
+                                    }
+                                }
+                            }
+                        }
+                    )
+
+                    Spacer(
+                        modifier = Modifier.size(
+                            dimensionResource(R.dimen.major_200) * LocalConfiguration.current.fontScale
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:148]: I guess multiplying the size of this `Space` causes an unintentionally large padding at the bottom.

|Defaulf font|Large font|
|-|-|
|||

**Review by irfano — APPROVED** [review]
Thanks for taking care of all changes. 🙇‍♂️
I've added one last comment. We're good to merge after you check it and fix the failing unit tests.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt (hunk 10 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:148]: > I guess multiplying the size of this Space causes an unintentionally large padding at the bottom.

The Spacer is only preventing the bottom sheet content from being displayed in the peek version. As this is a bottom sheet, the size is controlled by the peek size parameter, which I also multiplied by the font size. Because this is the last task from M2, I would prefer to close this PR and discuss the adjustments on the design review. WDYT?

Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/ShipmentDetails.kt:148]: Okay. Let's merge this. 👍🏻 🚢
