### PR TITLE
Product Creation with AI: miscellaneous fixes

### LINKED ISSUE #9838: Handle missing units (dimension, weight and currency)

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #9838 

### Description
This PR has three fixes:
1. The first one is about the main ticket, it adds logic for fetching dimension, weight and currency units if they are missing, and if we can't get them, it'll abort the generation.
2. Identify the language using the user's entered text instead of using the app's language.
3. Update the AI prompt to be clearer about asking the AI to exclude the currency symbol from the price, in my experience, the previous version worked most of the time, but sometimes the AI might still put the symbol in it.
If we still experience this, we might need to handle removing the symbol manually before parsing the price, but I prefer not doing it if we don't have to.

##### Change 1
1. Either clear the `WCSettingsModel` table using AS inspection tool before starting the creation
**or** apply the patch from below, then clear the app's data then sign in
2. Start AI product creation.
3. Confirm it works as expected, and the correct symbols are used in the price and shipping sections.

##### Change 2
1. Start AI product creation.
2. Enter title and keywords in non-English words
3. Confirm the generated product respects the language of the text.

##### Change 3
Just confirm the generation works successfully during multiple tests.

##### Patch for change 1
```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt	(revision f2283168921fea517c3b95412afd5b549932e509)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt	(date 1695768332023)
@@ -142,7 +142,7 @@
                             restartMainActivity()
                         }
                     }
-                    wooCommerceStore.fetchSiteGeneralSettings(it)
+                    // wooCommerceStore.fetchSiteGeneralSettings(it)
                     wooCommerceStore.fetchSiteProductSettings(it)
                 }
             }
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision f2283168921fea517c3b95412afd5b549932e509)
+++ b/build.gradle	(date 1695768414492)
@@ -27,7 +27,7 @@
     tasks.withType(KotlinCompile).all {
         kotlinOptions {
             jvmTarget = JavaVersion.VERSION_1_8
-            allWarningsAsErrors = true
+//            allWarningsAsErrors = true
             freeCompilerArgs += [
                     "-opt-in=kotlin.RequiresOptIn",
                     "-Xjvm-default=all-compatibility",
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt	(revision f2283168921fea517c3b95412afd5b549932e509)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt	(date 1695768332019)
@@ -71,21 +71,22 @@
     }
 
     private suspend fun getCurrencyCode(site: SiteModel): String {
-        val localSettings = wcStore.getSiteSettings(site)
-        if (localSettings != null) return localSettings.currencyCode
-
-        var currentDelay = BACKOFF_DELAY
-        var currencyCode = ""
-        for (i in 0 until BACKOFF_INTENTS) {
-            val settings = wcStore.fetchSiteGeneralSettings(site).model
-            if (settings != null) {
-                currencyCode = settings.currencyCode
-                break
-            }
-            delay(currentDelay)
-            currentDelay = (currentDelay * i)
-        }
-        return currencyCode
+//        val localSettings = wcStore.getSiteSettings(site)
+//        if (localSettings != null) return localSettings.currencyCode
+//
+//        var currentDelay = BACKOFF_DELAY
+//        var currencyCode = ""
+//        for (i in 0 until BACKOFF_INTENTS) {
+//            val settings = wcStore.fetchSiteGeneralSettings(site).model
+//            if (settings != null) {
+//                currencyCode = settings.currencyCode
+//                break
+//            }
+//            delay(currentDelay)
+//            currentDelay = (currentDelay * i)
+//        }
+//        return currencyCode
+        return ""
     }
 
     /**
```

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt [hunk 1]
```diff
@@ -44,30 +47,31 @@ class ProductPreviewSubViewModel(
...
-                tagsRepository.getProductTags().ifEmpty {
-                    tagsRepository.fetchProductTags()
-                    tagsRepository.getProductTags()
-                }
+            val categories = getCategories()
+            val tags = getTags()
+            val siteParameters = getSiteParameters() ?: run {
+                // We can't create a product without site parameters, so show an error and abort
+                // TODO show error alert
+                return@launch
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt:63]: If we can't generate a product without site parameters I wonder if it makes sense to have the user go through all the flow of adding product name and features only to tell them that it is not possible to generate a product. Seems like we are wasting their time, specially if when this error happens we don't provide a way for them to fix it. 

Unsure how to avoid this, other than implementing a way for users to update this site's parameters when the error happens. Anyway just some reflection we might want to discuss with Ann and the team.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt [hunk 2]
```diff
@@ -104,6 +108,57 @@ class ProductPreviewSubViewModel(
...
+
+    private suspend fun getSiteParameters(): SiteParameters? = withContext(Dispatchers.IO) {
+        fun predicate(parameters: SiteParameters): Boolean {
+            return parameters.weightUnit.isNotNullOrEmpty() &&
+                parameters.dimensionUnit.isNotNullOrEmpty() &&
+                parameters.currencyCode.isNotNullOrEmpty()
+        }
+
+        return@withContext parametersRepository.getParameters().takeIf(::predicate)
+            ?: parametersRepository.fetchParameters()
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt:142]: I think it's not enough with this call to refresh all the parameters values we need here. This will call `fetchSiteGeneralSettings` from `WooCommerceStore` . But that won't refresh the `weight` and `dimension` units. `weightUnit` and `dimensionUnit` are fetched with `WooCommerceStore.fetchSiteProductSettings()`. So, unless I'm missing something we'll need to add that call when missing weight or dimension units. 

In my test this results in an endless loading experience, but that is because we are not handling errors yet in line 61 of this file:

https://github.com/woocommerce/woocommerce-android/assets/2663464/dfd3b96e-cbac-4880-a0d9-1181390fc742

**Comment by JorgeMucientes** [comment]
Great work @hichamboushaba! Code looks great but there's a small issue I think we need to address before merging to fetch missing dimension and weight units. 
Let me know your thoughts.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt:142]: Great find @JorgeMucientes, I assumed all of the three values are from the same endpoint 🤦, I'll work on a fix, and then update the PR description, because it's the reason I didn't catch the issue.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/ProductPreviewSubViewModel.kt:142]: I hope https://github.com/woocommerce/woocommerce-android/pull/9839/commits/4ffe7d5d5248ef09a84c4149097bba23ec10cd3d fixes the issue, ready for another round.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for fixing it so quickly! Works perfectly now! :shipit:
