### PR TITLE
Product details: Do not show "one time shipping" label on Simple Product

### LINKED ISSUE #13027: One time shipping label remains visible when the product is changed to a simple product
**Describe the bug**
One time  shipping label is a feature for subscriptions. When a product is changed from a subscription to a simple product, the one-time shipping label remains visible.

**To Reproduce**
1. Go to Products tab.
2. Open an existing subscription product.
3. Tap "+ ADD MORE DETAILS" and add "Shipping".
4. Enable "One time shipping." and navigate back.
5. Tap "Product type."
6. Tap "Simple physical product" and select "YES, CHANGE" from the dialog.
7. Notice "One time shipping: Enabled" label.

**Screenshots**

**Expected behavior**
"One time shipping: Enabled" label should be gone.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 9 Pro Emulator
- Android version: 14
- WooCommerce Android version: 21.2-rc-2

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #13027

### Description

When a subscription product that has "One time shipping" enabled get converted into simple product, "One time shipping" label is still shown. This is incorrect because "one time shipping" is only supported in subscription product, not simple.

This PR adds the fix by checking product type and not showing the label if it's simple.

That issue is not tackled here yet.

### Steps to reproduce

1. Create a Simple Subscription product,
2. Go to Add More Details > Shipping,
3. Enter a weight value, and enable "One time shipping", then press back,
4. Confirm that "Shipping" card is shown with "One time shipping: Enabled" text shown,
5. Publish the product,
6. Once published, tap "Product Type" card and switch to "Simple Physical Product", confirm the change,
7. Check the "Shipping" card and ensure it now only says "Weight" and doesn't mention "One time shipping".

### Testing information

Tested in API 35 with Simulator.

I also discovered a separate issue when working on this:

[Given product details with "one time shipping" enabled but no other shipping values entered, when switching to simple product, Shipping card disappears](https://github.com/woocommerce/woocommerce-android/issues/13033)

This issue is not tackled in this PR.

### The tests that have been performed

The listed steps above.

### Images/gif

https://github.com/user-attachments/assets/8897e15d-5c6c-4dfb-8b4c-5cb676146454

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt [hunk 1]
```diff
@@ -471,21 +471,26 @@ class ProductDetailCardBuilder(
...
-                ),
-                Pair(
-                    resources.getString(string.subscription_one_time_shipping),
-                    buildOneTimeShippingDescription(subscription)
+                    viewModel.getShippingClassByRemoteShippingClassId(currentProduct.shippingClassId)
                 )
-            )
+
+                // Only add "One time shipping" info if product is Subscription types
+                if (currentProduct.productType == SUBSCRIPTION || currentProduct.productType == VARIABLE_SUBSCRIPTION) {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/details/ProductDetailCardBuilder.kt:487]: Good catch adding this check!

**Review by JorgeMucientes — APPROVED** [review]
Nice job @hafizrahman it works as expected and code looks good. Thanks for adding the unit tests. 

Btw I was about to report the weird issue about the shipping card being gone when switching the product from subscription to simple when I noticed you already created a GH issue for it. Anyway I think it is a very minor thing and very corner case for a user to land in that situation, so I wouldn't spend to much time fixing it, unless it is very straighforward :)

**Comment by hafizrahman** [comment]
> Btw I was about to report the weird issue about the shipping card being gone when switching the product from subscription to simple when I noticed you already created a GH issue for it. 

Yeah! I ended up working on it here https://github.com/woocommerce/woocommerce-android/pull/13035
