### PR TITLE
Issue/3240 bottom nav overlaps fab

### LINKED ISSUE #3240: Beta Bug: Products List: FAB partially hidden on first load
**Describe the bug**
When switching to the products tab for the first time after opening the app, the FAB to add a new product is partially hidden until scroll. 

**To Reproduce**
1. Start with the app closed completely. Open the app. 
2. Click on products tab. Notice the partially hidden FAB.

**Screenshots**

**Expected behavior**
The FAB is fully visible.

**Mobile Environment**
Please include:
- Device: Pixel 4
- Android version: 11
- WooCommerce Android version: 5.6-rc-1

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3240 - the only way I could reliably fix the overlapped FAB was to move it to the main activity, so it's a direct child of the `CoordinatorLayout`. Doing this also fixes another bug, where snackbars would overlap the FAB.

I made two other changes to the FAB in this PR:

- Use `show()` and `hide()` so the FAB animates
- Added missing `android:contentDescription` for accessibility

fab

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt [hunk 1]
```diff
@@ -441,12 +451,24 @@ class ProductListFragment : TopLevelFragment(R.layout.fragment_product_list),
...
+            if (addProductButton.isVisible) {
+                addProductButton.hide()
+            }
+        }
+
         when (show) {
             true -> {
                 showButton()
-                binding.addProductButton.setOnClickListener {
+                addProductButton.setOnClickListener {
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt:471]: This works fine now, but I can see how this could lead to a bug later since this FAB technically lives in the `MainActivity` and the click listener set here doesn't get removed when switching away from the product list tab. In the future we'll be adding the ability to add orders from the app so I recommend unsetting the listener when leaving the products list view, and then setting it again when returned. WDYT?

**Review by AmandaRiu — COMMENTED** [review]
@nbradbury Works great. Love the button animation ❤️  I left a code comment for your review.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt:471]: @AmandaRiu Good call! Added in 9a1af40.

**Review by AmandaRiu — APPROVED** [review]
Looks good! :shipit:
