### PR TITLE
Issue/5712 Specifc error message when not supported reader is used

### LINKED ISSUE #5712: [Mobile Payments] Custom alert if connecting unsupported reader
Card readers are only supported in specific countries:
- US: Chipper 2X, M2
- Canada: WisePad 3

Stripe will already reject payments with the wrong reader based on store location, but we should include a more helpful message when trying to connect to a reader if the model is not supported in the store's country.

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #5712

### Description

* Shows a toast message with an error message from the SDK
* Removes Canada IPP flag check on what type of readers we want to scan for 

### Testing instructions

* Try to collect payment with none Wisepad 3 readers in Canada store
* Notice a toast message

### Images/gif

https://user-images.githubusercontent.com/4923871/153865353-d6ac7823-2cf7-4e44-b9e1-55d3b6be76c3.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 1]
```diff
@@ -51,9 +47,6 @@ class CardReaderConnectViewModel @Inject constructor(
     private val locationRepository: CardReaderLocationRepository,
     private val selectedSite: SelectedSite,
     private val cardReaderManager: CardReaderManager,
-    private val inPersonPaymentsCanadaFeatureFlag: InPersonPaymentsCanadaFeatureFlag,
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:54]: ⚠️ Is the removal of the Canada IPP feature flag and other dependencies intentional?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 2]
```diff
@@ -237,26 +230,15 @@ class CardReaderConnectViewModel @Inject constructor(
         }
     }
 
-    private suspend fun getSupportedReaders() =
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:240]: ⚠️ Is the removal of this piece of code intentional? This adds the Wisepad 3 device to the US stores as well

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 3]
```diff
@@ -237,26 +230,15 @@ class CardReaderConnectViewModel @Inject constructor(
...
     private suspend fun listenToConnectionStatus() {
         cardReaderManager.readerStatus.collect { status ->
             when (status) {
                 is CardReaderStatus.Connected -> onReaderConnected(status.cardReader)
-                CardReaderStatus.NotConnected -> {
-                    if (connectionStarted) onReaderConnectionFailed()
-                    else Unit
+                is CardReaderStatus.NotConnected -> {
+                    if (connectionStarted) {
+                        status.errorMessage?.let { triggerEvent(ShowToastString(it)) }
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:239]: ❓ We initially had the intention to only show toast message if the merchant tries to connect to the card reader which isn't supported by their store location. With this code, the toast message will be shown to the user with the SDK thrown message every time the card reader fails to connect regardless of the reason. I'm thinking if this confuses the merchants since most of the SDK error messages might be cryptic to the end-user. WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 4]
```diff
@@ -468,15 +450,7 @@ class CardReaderConnectViewModel @Inject constructor(
     }
 
     private fun trackLocationFailureFetching(errorDescription: String?) {
-        tracker.trackFetchingLocationFailed(errorDescription,)
-    }
-
-    private suspend fun getStoreCountryCode(): String? {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:474]: ⚠️ Is the removal of this piece of code intentional?

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/config/CardReaderConfig.kt [hunk 5]
```diff
@@ -9,10 +9,4 @@ interface CardReaderConfig {
     val supportedReaders: List<SpecificReader>
     val paymentMethodType: List<PaymentMethodType>
     val isStripeExtensionSupported: Boolean
-    val allReaders: List<SpecificReader>
```
Comment (AnirudhBhat) [inline libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/config/CardReaderConfig.kt:12]: ⚠️ Is the removal of this piece of code intentional?

**Comment by AnirudhBhat** [comment]
@kidinov Thanks for working on this! I've tested the changes and it does show a toast message when we try to connect to an unsupported reader. I've left a few comments. Please have a look.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:54]: Thanks for clarifying about this in Slack. (We will display all the readers regardless of the store's location. Since this is a corner case, we won't put any effort into this unless data asks for it)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt (hunk 2 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:240]: Thanks for clarifying about this in Slack. (We will display all the readers regardless of the store's location. Since this is a corner case, we won't put any effort into this unless data asks for it)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt (hunk 4 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:474]: Thanks for clarifying about this in Slack. (We will display all the readers regardless of the store's location. Since this is a corner case, we won't put any effort into this unless data asks for it)

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/config/CardReaderConfig.kt (hunk 5 above)
Comment (AnirudhBhat) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/config/CardReaderConfig.kt:12]: Thanks for clarifying about this in Slack. (We will display all the readers regardless of the store's location. Since this is a corner case, we won't put any effort into this unless data asks for it)

**Review by AnirudhBhat — APPROVED** [review]
