### PR TITLE
Hotfix: NPE exception

### LINKED ISSUE #1778: NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
Sentry Issue: [WOOCOMMERCE-ANDROID-A1](https://sentry.io/organizations/a8c/issues/1410483221/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
    at org.wordpress.android.login.LoginMagicLinkRequestFragment.onSaveInstanceState(LoginMagicLinkRequestFragment.java:246)
    at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
    at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
    at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
    at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
...
(14 additional frame(s) were not displayed)

Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
```

First seen: Dec 29, 2019
Release: 3.2

### LINKED ISSUE #1779: NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
Sentry Issue: [WOOCOMMERCE-ANDROID-9Q](https://sentry.io/organizations/a8c/issues/1403827441/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
    at org.wordpress.android.login.LoginMagicLinkRequestFragment.onSaveInstanceState(LoginMagicLinkRequestFragment.java:246)
    at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
    at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
    at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
    at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
...
(15 additional frame(s) were not displayed)

Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
```

First seen: Dec 24, 2019
Release: 3.2

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1778 and fixes #1779 by checking if the view is null before attempting to access its properties. 

Notes:
- This is a hotfix so please notify me when the PR is approved and merged. 
- This PR includes changes to the login library, so additional work to merge into the login library repo and WPAndroid will need to be done post approval and merge.

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java [hunk 1]
```diff
@@ -38,10 +38,6 @@ void initiateDiscovery() {
     @SuppressWarnings("unused")
     @Subscribe(threadMode = ThreadMode.MAIN)
     public void onDiscoverySucceeded(OnDiscoveryResponse event) {
-        if (mLoginBaseDiscoveryListener == null) {
-            return;
-        }
-
```
Comment (anitaa1990) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java]: This was added as part of this fix [here](https://github.com/woocommerce/woocommerce-android/pull/1667).

Comment (AmandaRiu) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java]: Oh thank you for this catch! Fixed in 15774553eeef8b0a700a0fc414c0e71881d7364c

File: libs/login/WordPressLoginFlow/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -22,7 +22,7 @@
     <string name="open_mail">Open mail</string>
     <string name="alternatively">Alternatively:</string>
     <string name="enter_site_address_instead">Log in by entering your site address.</string>
-    <string name="enter_site_credentials_instead">Log in with site credentials.</string>
```
Comment (anitaa1990) [inline libs/login/WordPressLoginFlow/src/main/res/values/strings.xml]: This . was added since the `Login with Google` is displayed with a . but `Login with site credentials` was not.



Would it be possible to add it back? Or perhaps remove the . in `Login with Google` to make both buttons consistent?

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java [hunk 3]
```diff
@@ -154,8 +154,9 @@ protected void setupContent(ViewGroup rootView) {
         siteAddressView.setText(UrlUtils.removeScheme(UrlUtils.removeXmlrpcSuffix(mInputSiteAddress)));
         siteAddressView.setVisibility(mInputSiteAddress != null ? View.VISIBLE : View.GONE);
 
+        String inputSiteAddressWithoutProtocol = UrlUtils.removeScheme(mInputSiteAddress);
         mInputSiteAddressWithoutSuffix = (mEndpointAddress == null || mEndpointAddress.isEmpty())
-                ? mInputSiteAddress : UrlUtils.removeXmlrpcSuffix(mEndpointAddress);
```
Comment (anitaa1990) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java]: This was added as part of a fix for a bug where the forgot password link was not working correctly. Would it be possible to change this back? Adding the [related code](https://github.com/woocommerce/woocommerce-android/commit/1931740e84ead52ec8686be59265c65e396fb5a1#diff-166c35a606139a8560ff4ea9c4a195f3) for your reference

File: libs/login/WordPressLoginFlow/src/main/res/values/strings.xml (hunk 2 above)
Comment (AmandaRiu) [reply libs/login/WordPressLoginFlow/src/main/res/values/strings.xml]: Fixed in 824b2267440dd22bd3706156a5d5f59a66783244

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java (hunk 3 above)
Comment (AmandaRiu) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java]: Fixed in 824b2267440dd22bd3706156a5d5f59a66783244

**Review by anitaa1990 — APPROVED** [review]
LGTM :shipit:
