### PR TITLE
Issue/6209 order creation fee done button

### LINKED ISSUE #6209: Order Creation: Unclear behavior adding $0 fee to new order
**Describe the bug**

When you tap the "add fee" button in order creation, the "Done" button on the Add Fee screen is already enabled. Tapping "Done" doesn't show any fee added to the order, but the order acts like the fee was added (it syncs remotely and shows the "remove fee" option when you visit the Add Fee screen again).

**To Reproduce**
1. Go to the Orders tab and create a new order.
2. Select "Add fee".
3. Notice the amount is pre-filled with a 0 value and the "Done" button is enabled; tap "Done."
4. Notice the "add fee" button still appears in the Payment section, but the order syncs remotely.
5. Select "Add fee" again and notice the "Add fee" screen now shows a "Remove fee from order" button.

**Screenshots**

Add Fee with Done button enabled|No fee added but order syncs|Remove fee button
-|-|-
Screenshot_20220408-125627|Screenshot_20220408-125631|Screenshot_20220408-125635

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #6209 - previously when adding a fee in order creation, the Done button would be enabled even when the fee is zero. In this situation, tapping "Done" doesn't show any fee added to the order, but the order acts like the fee was added (it syncs remotely and shows the "remove fee" option when you visit the Add Fee screen again).

This PR resolves this by disabling the Done button when the fee is zero.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt [hunk 1]
```diff
@@ -47,6 +47,7 @@ class OrderCreationFeeViewModel @Inject constructor(
                 shouldDisplayPercentageSwitch = false,
                 feeAmount = currentFee,
                 feePercentage = calculatePercentageFromValue(currentFee),
+                isDoneButtonEnabled = currentFee > BigDecimal.ZERO,
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt]: I believe there is one issue with this, the Order Creation fees support negative amounts to be set as discounts, as it is, this verification would make the `done` button disabled for negative amounts, I believe it would be better to set all `isDoneButtonEnabled` changes as `currentFee != BigDecimal.ZERO`, WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt [hunk 2]
```diff
@@ -76,17 +77,20 @@ class OrderCreationFeeViewModel @Inject constructor(
...
     fun onFeePercentageChanged(feePercentageRaw: String) {
         // Only update when isPercentageSelected is enabled
         if (!viewState.isPercentageSelected) return
         val feePercentage = feePercentageRaw.toBigDecimalOrNull() ?: BigDecimal.ZERO
+        val feeAmount = calculateFeePercentage(feePercentage)
         viewState = viewState.copy(
             feePercentage = feePercentage,
-            feeAmount = calculateFeePercentage(feePercentage)
+            feeAmount = feeAmount,
+            isDoneButtonEnabled = feeAmount > BigDecimal.ZERO
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt]: same suggestion regarding the negative values

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt [hunk 3]
```diff
@@ -76,17 +77,20 @@ class OrderCreationFeeViewModel @Inject constructor(
         if (viewState.isPercentageSelected) return
         viewState = viewState.copy(
             feeAmount = feeAmount,
-            feePercentage = calculatePercentageFromValue(feeAmount)
+            feePercentage = calculatePercentageFromValue(feeAmount),
+            isDoneButtonEnabled = feeAmount > BigDecimal.ZERO
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModel.kt]: same suggestion regarding the negative values

**Review by ThomazFB — CHANGES_REQUESTED** [review]
Thanks @nbradbury for these changes, I believe there are some points that might need discussion before merging this PR, I left below some comments about the support for negative fees, but I also would like to suggest adding unit tests to the `OrderCreationFeeViewModelTest` considering that this change impacts the ability to submit the Fee and have three different spots verifying changing the done button visibility that can introduce bugs. I have a suggestion patch that you could use if you want to:
[Improve_OrderCreationFeeViewModelTest.txt](https://github.com/woocommerce/woocommerce-android/files/8656345/Improve_OrderCreationFeeViewModelTest.txt)

```
Index: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModelTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModelTest.kt b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModelTest.kt
--- a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModelTest.kt	(revision 926f8ae343a159e86b386edf5b71ed668423990e)
+++ b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/fees/OrderCreationFeeViewModelTest.kt	(date 1652145250548)
@@ -300,4 +300,102 @@
 
         assertThat(lastReceivedChange).isTrue
     }
+
+    @Test
+    fun `when fee value start as zero, then set isDoneButtonEnabled to false`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(BigDecimal.ZERO, BigDecimal.ZERO)
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isFalse
+    }
+
+    @Test
+    fun `when fee value starts as bigger than zero, then set isDoneButtonEnabled to true`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(DEFAULT_ORDER_SUB_TOTAL, DEFAULT_FEE_VALUE)
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isTrue
+    }
+
+    @Test
+    fun `when fee value starts as negative amount, then set isDoneButtonEnabled to true`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(DEFAULT_ORDER_SUB_TOTAL, BigDecimal(-25))
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isTrue
+    }
+
+    @Test
+    fun `when fee amount is set to a negative value, then set isDoneButtonEnabled to true`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(DEFAULT_ORDER_SUB_TOTAL, DEFAULT_FEE_VALUE)
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isTrue
+
+        sut.onFeeAmountChanged(BigDecimal(-25))
+
+        assertThat(lastReceivedChange).isTrue
+    }
+
+    @Test
+    fun `when fee amount is set to zero, then set isDoneButtonEnabled to false`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(DEFAULT_ORDER_SUB_TOTAL, DEFAULT_FEE_VALUE)
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isTrue
+
+        sut.onFeeAmountChanged(BigDecimal.ZERO)
+
+        assertThat(lastReceivedChange).isFalse
+    }
+
+    @Test
+    fun `when fee percentage is set to zero, then set isDoneButtonEnabled to false`() {
+        var lastReceivedChange: Boolean? = null
+        savedState = OrderCreationFeeFragmentArgs(DEFAULT_ORDER_SUB_TOTAL, DEFAULT_FEE_VALUE)
+            .initSavedStateHandle()
+        initSut()
+
+        sut.viewStateData.observeForever { _, viewState ->
+            lastReceivedChange = viewState.isDoneButtonEnabled
+        }
+
+        assertThat(lastReceivedChange).isTrue
+
+        sut.onPercentageSwitchChanged(true)
+
+        sut.onFeePercentageChanged("0")
+
+        assertThat(lastReceivedChange).isFalse
+    }
 }
```

**Comment by nbradbury** [comment]
@ThomazFB Thanks for the review! I've addressed the issues you raised.

**Review by ThomazFB — APPROVED** [review]
Thanks @nbradbury for applying the suggestions! The changes looks good to me! Should we just wait for [this discussion](https://github.com/woocommerce/woocommerce-android/issues/6209#issuecomment-1122737304) to unfold before merging this PR? I'm approving here anyway to unblock the PR.
