### PR TITLE
Shipping Labels Add New Package: Improve number input validation to deal with "." entries.

### LINKED ISSUE #4656: Shipping labels: app crash after entering "." in any numeric field on the Add new package screen
Steps to reproduce:

1. Create a label for any order, confirm addresses, and move on to package selection.
1. Tap "Package selected".
1. Observe that you arrive at the "Add a new package" screen
1. Note that the store in this example did not have any packages to start with (though I'm not sure if that's relevant).
1. Tap any numeric field, i.e. "Length" or "Empty package weight".
1. Add a "." to the field.
1. Crash.

**Result:** the app will crash after entering "." in any numeric field. ([41s](https://cloudup.com/cUOAQ5t2Z5d))

Screenshot_20210820-004609
<sup>Tested with WCAndroid 7.2-rc-2 and WooCommerce-pr-4596-build-45290.apk on Pixel 3 Android 11 logged in as testuser011121 using site hilarious-sea.jurassic.ninja running WordPress 5.8, Jetpack 10.0, WooCommerce 5.6.0, WooCommerce Shipping & Tax 1.25.18.</sup>

### PR DESCRIPTION
**Pull request by hafizrahman**
# What the PR does:
Fixes #4656 

1. In the Add new package screen, a singular `.` entry in the length/width/height/weight field will now show "This field is required" message instead of crashing the app.
2. a dot-something entry without a leading zero (like `.5`) will now be accepted as valid entry and be saved as such. This matches core behavior.

### Testing instructions

**Case 1**:

1. Create a label for any order, confirm addresses, and move on to package selection.
2. Tap "Package selected".
3. Go to "Add a new package" screen
4. Enter `.` to the length/width/height/weight field. 
5. Make sure that the app doesn't crash, and instead the field will say "This field is required".

**Case 2**:
1. Still on the "Add new package" screen, enter `.5` value to the length/width/height/weight field.
2. Fill in all remaining fields and tap "Done" to save the package.
3. Check in wp-admin (`wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`), and find the package you just created. Make sure that the "Dimensions" value is "0.5 x 0.5 x 0.5".

- [x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModelTest.kt [hunk 1]
```diff
@@ -101,6 +101,38 @@ class ShippingLabelCreateCustomPackageViewModelTest : BaseUnitTest() {
...
+        viewModel.onFieldTextChanged(".5", InputName.WIDTH)
+        viewModel.onFieldTextChanged(".5", InputName.HEIGHT)
+        viewModel.onFieldTextChanged(".5", InputName.EMPTY_WEIGHT)
+
+        assertThat(state!!.lengthErrorMessage).isEqualTo(null)
+        assertThat(state!!.widthErrorMessage).isEqualTo(null)
+        assertThat(state!!.heightErrorMessage).isEqualTo(null)
+        assertThat(state!!.weightErrorMessage).isEqualTo(null)
+    }
+
```
Comment (anitaa1990) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelCreateCustomPackageViewModelTest.kt:135]: <3 Nice! Thanks for adding the unit tests here ❤️

**Review by anitaa1990 — COMMENTED** [review]
LGTM :shipit: Thank you for the quick fix @hafizrahman!

**Review by anitaa1990 — APPROVED** [review]

**Comment by anitaa1990** [comment]
I'll wait for CI to finish before merging! cc @jkmassel this fix is getting merged to the release branch. Do you think we have time for another beta or can this be part of the 7.3 release?

**Review by anitaa1990 — APPROVED** [review]
