### PR TITLE
Remove existing product type from the Product Type Bottom Sheet

### LINKED ISSUE #3904: Selecting a product type shows the change confirmation dialog even when existing type is selected
To reproduce:

- Go to product detail
- Tap to change the product type
- Select the same product type the product already has
- Note the change confirmation dialog still appears

type

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #3904

### Description

Instead of removing the change confirmation dialogue when the user taps on a product type that is already set for that product, to match what we have on iOS, this PR removes the current product type from the productTypeBottomSheet. 

### Testing instructions

- Go to the product screen
- Tap on one of the existing products to display the Product detail screen
- Tap on the Product type
- note the current product type is not displayed in the product type bottom sheet

Also

- Go to the Products Screen
- tap to add a brand new product
- Check if the Product Type bottom sheet display all the product type options

### Images/gif

| Before | After |
| ---- | ---- |
|  |  |

- [ x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetFragment.kt [hunk 1]
```diff
@@ -25,7 +25,8 @@ class ProductTypesBottomSheetFragment : BottomSheetDialogFragment() {
         const val KEY_PRODUCT_TYPE_RESULT = "key_product_type_result"
     }
 
-    @Inject internal lateinit var navigator: ProductNavigator
+    @Inject
```
[the remark this answers is not in the document]
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetFragment.kt]: fixed

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModelTest.kt [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+        )
+        whenever(bottomSheetBuilder.buildBottomSheetList()).thenReturn(uiItems)
+
+        viewModel.loadProductTypes()
+
+        assertThat(viewModel.productTypesBottomSheetList.value!!.size).isEqualTo(uiItems.size - 1)
+    }
+
+    @Test
+    fun `when loading product types, then product types is filtered`() {
```
Comment (malinajirka) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModelTest.kt]: I forgot that we didn't get back to naming the test. Perhaps, something like this might work?
```suggestion
    fun `given current type is virtual, when loading product types, then only virtual type is filtered out`() {
```

Comment (rossanafmenezes) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModelTest.kt]: Yup, looks good. I have committed this change 😊. Thanks

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModel.kt [hunk 3]
```diff
@@ -34,16 +35,20 @@ class ProductTypesBottomSheetViewModel @Inject constructor(
...
-                .filter { it.isEnabledForAddFlow }
+            productTypeBottomSheetBuilder.buildBottomSheetList()
         } else {
-            ProductTypeBottomSheetBuilder().buildBottomSheetList()
+            productTypeBottomSheetBuilder.buildBottomSheetList()
+                .filter {
+                    val currentProductType = navArgs.currentProductType
+                        ?.let { nonNullProductType -> ProductType.fromString(nonNullProductType) }
+                    !(it.type == currentProductType && it.isVirtual == navArgs.isCurrentProductVirtual)
+                }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModel.kt:45]: oohh I think now I better understand all the discussion regarding productType over Slack p1644315213664549-slack-CGPNUU63E 😅 

Getting rid of the isVirtual and fixing the `fromString` method would have make all this simpler. Pity it was not possible in the end.

**Comment by JorgeMucientes** [comment]
Nice and clear! Tested it and works like a charm. Well done 👍🏼  Let's :shipit:

**Review by JorgeMucientes — APPROVED** [review]

**Comment by rossanafmenezes** [comment]
Thanks for reviewing it @JorgeMucientes  💯

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModel.kt (hunk 3 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductTypesBottomSheetViewModel.kt:45]: IKR?
