### PR TITLE
Crash: Media URL null returned by the API

### LINKED ISSUE #10264: EventBusException: Invoking subscriber failed
Sentry Issue: [WOOCOMMERCE-ANDROID-8KV](https://a8c.sentry.io/issues/4654622230/?referrer=github_integration)

```
NullPointerException: media.url must not be null
    at com.woocommerce.android.media.MediaFilesRepository$OnMediaUploadListener.onMediaUploaded(MediaFilesRepository.kt:148)
...
(15 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:537)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:519)
    at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:461)
    at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
    at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
...
(14 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:537)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:519)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
    at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #10264. The WCAndroid client works with the wrong assumption that the `MediaModel.url` cannot be null. This PR handles that case.

**To test:**
There's nothing to test since it's difficult to reproduce the scenario.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt [hunk 1]
```diff
@@ -145,7 +146,7 @@ class MediaFilesRepository @Inject constructor(
 
                 event.completed -> {
                     val media = event.media
-                    val channelResult = if (media != null && media.url.isNotBlank()) {
+                    val channelResult = if (media != null && media.url.isNotNullOrEmpty() && media.url.isNotBlank()) {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt]: Really minor np, so feel free to merge without applying. But maybe with the check `media.url.isNotNullOrEmpty()` should suffice? I can't think of a scenario where the URL value would be white spaces only.

**Review by JorgeMucientes — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt]: I agree, I just wanted to keep the original logic intact. I'll change it.

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/media/MediaFilesRepository.kt]: I've updated the code.

**Comment by JorgeMucientes** [comment]
Thanks for handling this @0nko. The changes look good. I wonder if we should add some tracking for the error case where the `URL == null`. I mention this because the fix will only hide the real issue where the media URL coming from a successful upload is unexpectedly null. In any case no need to handle this now. PR is good to go.
