### PR TITLE
Attempt to fix crash during Jetpack connection

### LINKED ISSUE #8049: IllegalArgumentException: Site not cached
Sentry Issue: [WOOCOMMERCE-ANDROID-5EG](https://sentry.io/organizations/a8c/issues/3785096532/?referrer=github_integration)

```
IllegalArgumentException: Site not cached
    at com.woocommerce.android.ui.login.jetpack.main.JetpackActivationMainViewModel$site$1.invokeSuspend(JetpackActivationMainViewModel.kt:78)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8049 

### Description
This PR is a second attempt to fix the above crash, our theory is that the cause is that the users enter the address of sites that are already connected to their account, but they add some random suffixes that prevents the below check from working:
https://github.com/woocommerce/woocommerce-android/blob/4b888fb4fda73f8bd22b0be2addd8bcce28256e6/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt#L148

The PR adds a second check for the site's existence, but this time it uses the URL we receive from the API, as it comes without those suffixes.

### Testing instructions
1. Make sure you are logged in using [WordPress.com](http://wordpress.com/)
2. Open site picker, and click on “Add a store”, then choose “Connect an existing store”
3. Enter the address of one of your stores, with any random path (just make sure it’s different than wp-admin and wp-login.php)
4. Notice the app takes you to the site picker, then switches automatically to the new site.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt [hunk 1]
```diff
@@ -161,6 +161,8 @@ class SitePickerSiteDiscoveryViewModel @Inject constructor(
                 analyticsTracker.track(
                     stat = AnalyticsEvent.SITE_PICKER_SITE_DISCOVERY,
                     properties = mapOf(
+                        "user_entered_address" to siteAddressFlow.value,
+                        "fetched_address" to siteAddress,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt:165]: I added those properties to help us reproduce the crash if this PR doesn't fully fix it.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for looking into this again 🙌🏼  @hichamboushaba. Let's hope this one helps fix the crash. Works as described :shipit:
