### PR TITLE
Issue/4131 product tags adapter illegal state

### LINKED ISSUE #4131: IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclervi...
Sentry Issue: [WOOCOMMERCE-ANDROID-1Q7](https://sentry.io/organizations/a8c/issues/2433231363/?referrer=github_integration)

```
IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{22ceef2 VFED..... ......ID 0,202-720,602 #7f0a04b6 app:id/productTagsRecycler}, adapter:com.woocommerce.android.ui.products.tags.ProductTagsAdapter@4c7b536, layout:androidx.recyclerview.widget.LinearLayoutManager@2cc37, context:com.woocommerce.android.ui.main.MainActivity@601448e
    at com.woocommerce.android.ui.products.tags.ProductTagsAdapter.setProductTags(ProductTagsAdapter.kt:58)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment.showProductTags(ProductTagsFragment.kt:162)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment.access$showProductTags(ProductTagsFragment.kt:30)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment$setupObservers$2.onChanged(ProductTagsFragment.kt:143)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment$setupObservers$2.onChanged(ProductTagsFragment.kt:30)
...
(114 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nbradbury**
Possibly fixes #4131 - I wasn't able to reproduce the problem, but I did notice that `setProductTags()` on the product tag adapter was always being called twice in rapid succession, which could lead to the problem.

My hopeful fix is to only call `notifyDataChanged()` when the list of tags changes from the current list, or the filter changes from the current filter.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductTag.kt [hunk 1]
```diff
@@ -28,6 +28,13 @@ data class ProductTag(
         selectedTags.remove(this)
         return selectedTags
     }
+
+    fun isSameTag(otherTag: ProductTag): Boolean {
+        return this.remoteTagId == otherTag.remoteTagId &&
+            this.name == otherTag.name &&
+            this.slug == otherTag.slug &&
+            this.description == otherTag.description
+    }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/ProductTag.kt]: Since this is a data class, and all properties are in the primary constructor, I think this function has the same functionality as the generated `equals`, and can be removed, WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt [hunk 2]
```diff
@@ -46,7 +47,14 @@ class ProductTagsAdapter(
         }
     }
 
+    private fun isSameList(newList: List<ProductTag>) =
+        this.productTags.areSameAs(newList) { this.isSameTag(it) }
+
     fun setProductTags(productsTags: List<ProductTag>) {
+        if (isSameList(productsTags)) {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt]: If we removed the `isSameTag` above, then we can simplify this to `this.productTags == productTags`, since the [`equals`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-abstract-list/equals.html) function of the list will do the job for us.

**Review by hichamboushaba — COMMENTED** [review]
The fix seems good to me, I just left some comments for a possible simplification of the logic 🙂.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt (hunk 2 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt]: Good call @hichamboushaba. I've made these changes.

**Review by hichamboushaba — APPROVED** [review]
LGTM :shipit:
