### PR TITLE
[IPP] Generic error when low batter during connection

### LINKED ISSUE #13596: [Woo POS/IPP] Generic Error When Low Batter During Connection
**Describe the bug**
When I attempt to connect to a reader with low battery, the app displays generic - "We couldn't connect your reader" error instead of a helpful message.

**Expected behavior**
The app should display an actionable error, something like 'Please charge your reader'.

> class=TerminalSession (Ask Gemini)
>                                                                                                     com.stripe.stripeterminal.external.models.TerminalException: Reader battery is critically low.
>                                                                                                     	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$9.accept(BbposAdapter.kt:433)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$9.accept(BbposAdapter.kt:428)
>                                                                                                     	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
>                                                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
>                                                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
>                                                                                                     	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
>                                                                                                     	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
>                                                                                                     	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #13596

### Description

The PR adds specific error handling for the cases when a reader with low battery level attempted to connect 

### Steps to reproduce

* Use a real reader with low batter charged
* Try to connect 
* Notice a dialog with specific message

### The tests that have been performed

Above

### Images/gif

https://github.com/user-attachments/assets/dfb25221-43c9-4415-9ac4-1720fbf0e2fb

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt [hunk 1]
```diff
@@ -480,10 +482,29 @@ class CardReaderConnectViewModel @Inject constructor(
...
+            else -> null
+        }
+        if (hintLabel == null && errorMessage != null) {
+            triggerEvent(ShowToastString(errorMessage))
+        }
+        viewState.value = ConnectingFailedState(
+            onPrimaryActionClicked = ::restartFlow,
+            onSecondaryActionClicked = ::onCancelClicked,
+            hintLabel = when (errorCode) {
+                CardReaderStatus.NotConnected.ErrorCode.BATTERY_CRITICALLY_LOW ->
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt]: 🔍 It seems we are defining the hint here as well as line 493, should we use $hintLabel instead?

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt [hunk 2]
```diff
@@ -1563,6 +1559,73 @@ class CardReaderConnectViewModelTest : BaseUnitTest() {
...
+            assertThat(state.hintLabel).isEqualTo(R.string.card_reader_connect_failed_battery_low_hint)
+        }
+
+    @Test
+    fun `given other error, when connecting fails, then hint label is null`() =
+        testBlocking {
+            init()
+            (viewModel.viewStateData.value as ExternalReaderFoundState).onPrimaryActionClicked.invoke()
+            readerStatusFlow.emit(CardReaderStatus.Connecting)
+            readerStatusFlow.emit(
```
Comment (malinajirka) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt:1587]: 🔍 Super nitpick: I believe we usually split the Given/When/Then sections by an empty line, so we might want to put an empty line above this line - and we could do the similar for the other tests. Feel free to ignore this, mostly sharing just to sync and bring more consistency/better-readability.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt [hunk 3]
```diff
@@ -480,10 +482,29 @@ class CardReaderConnectViewModel @Inject constructor(
...
+        errorCode: CardReaderStatus.NotConnected.ErrorCode? = null,
+        errorMessage: String? = null
+    ) {
         tracker.trackConnectionFailed()
         WooLog.e(WooLog.T.CARD_READER, "Connecting to reader failed.")
-        viewState.value = ConnectingFailedState(::restartFlow, ::onCancelClicked)
+        val hintLabel = when (errorCode) {
+            CardReaderStatus.NotConnected.ErrorCode.BATTERY_CRITICALLY_LOW ->
+                R.string.card_reader_connect_failed_battery_low_hint
+            else -> null
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt]: 💡 We might want to explicitly list all the other options (in this case just `Other`) to ensure that when someone introduces a new enum value is forced by the compiler to make an explicit decision. Wdyt?

**Review by malinajirka — APPROVED** [review]
Thanks @kidinov!

I've reviewed the code and tested the app and it seems to work as expected. I tested that the flow work in both IPP and POS, great job! :shipit: 

I've left a couple minor comments, so I'll leave the merge to you.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt]: Ouch, good catch!

29042fc96533a45aeb688acbfe901da1288586c8

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt (hunk 2 above)
Comment (kidinov) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModelTest.kt:1587]: Added spaces

0243b8f040f42e0e99190f574fd4d603db2d8351

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt (hunk 3 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/connect/CardReaderConnectViewModel.kt]: Yep, missed that

544b86c7775a3adb3ad93d2b2dbbd36340b51c67
