### PR TITLE
[Bugfix] Improve Error Handling and Path Validation for Large Image Uploads

### LINKED ISSUE #11375: RuntimeException: Canvas: trying to draw too large(254615400bytes) bitmap.
Sentry Issue: [WOOCOMMERCE-ANDROID-A3J](https://a8c.sentry.io/issues/5176454206/?referrer=github_integration)

```
RuntimeException: Canvas: trying to draw too large(254615400bytes) bitmap.
    at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
    at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:75)
    at com.google.android.material.shape.MaterialShapeDrawable.maybeDrawCompatShadow(MaterialShapeDrawable.java:1025)
    at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:975)
    at android.view.View.getDrawableRenderNode(View.java:24479)
...
(82 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by backwardstruck**
Closes: #11375  

### Description  

This PR addresses an issue where the app could crash due to large image uploads or inaccessible image metadata. 

I am open to adding a unit test for `FileUploadUtils` if we think it will be useful. 

### Steps to reproduce  

1. Upload multiple high-resolution images for a product at once.
2. Simulate different scenarios such as:
   - Invalid image paths.
   - Unsupported image formats.

### Testing information  

- Devices: Tested on emulator with limited storage and memory.
- Testing Scenarios:
  - Uploading batches of high-resolution images.
  - Uploading images from different directories.
  - Verifying app behavior when interacting with files such as TIFF and RAW.
- Edge Cases:
  - Handling images with missing metadata.
  - Ensuring graceful handling of unexpected file errors.
- Affected areas: 
  - Media upload functionalities in the product management section.
  - Exception handling during file operations.

### Images/gif  

N/A

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.  
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.  
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — APPROVED** [review]
LGTM :shipit: 

I tested uploading ~20MB files, followed by tapping and opening them.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt [hunk 1]
```diff
@@ -28,28 +28,31 @@ object FileUploadUtils {
...
-        // "fetch" the media - necessary to support choosing from Downloads, Google Photos, etc.
-        fetchMedia(context, localUri)?.let { fetchedUri ->
-            mediaPickerUtils.getFilePath(fetchedUri)?.let { filePath ->
-                val path = if (MediaUtils.isValidImage(filePath)) {
-                    // optimize the image if the setting is enabled
-                    getOptimizedImagePath(context, filePath)
-                } else {
-                    filePath
-                }
+        val fetchedUri = fetchMedia(context, localUri) ?: run {
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt:31]: Adding more context here, since I didn't include this in the original description. The use of run doesn't change the functionality but just makes the logging and error handling code easier to read and maintain. By using run, we can better structure the null checks and early returns, which enhances the overall clarity and readability of the code without altering its behavior.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt [hunk 2]
```diff
@@ -28,28 +28,31 @@ object FileUploadUtils {
...
+            WooLog.w(T.MEDIA, "mediaModelFromLocalUri > fetched media path is null or empty")
+            return null
+        }
 
-                val mimeType = getMimeType(context, localUri, fetchedUri) ?: return null
+        val filePath = mediaPickerUtils.getFilePath(fetchedUri) ?: run {
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/media/FileUploadUtils.kt:36]: The logic for determining the path remains unchanged. That's why it doesn't have any direct effect on crashes.

**Review by backwardstruck — COMMENTED** [review]
The fact that it seemed to resolve some issues during testing might have just been due to a race condition. Therefore, while the readability improvements are valuable, they do not completely address the underlying crash issue.
