### PR TITLE
Order List Management Step 5: Fix tests

### LINKED ISSUE #1533: Order List Management Step 5: Fix Tests
Some of the tests are failing due to all the changes to the order list such as the switch to MVVM and using the new list managment component. These tests need to be fixed or rewritten as necessary.

### PR DESCRIPTION
**Pull request by AmandaRiu**
This PR fixes #1538 and covers the following:

- Removed defunct order list tests related to the old MVP design
- Added unit tests in `OrderListViewModelTests`
- Refactored the order list-related instrumented tests to work with MVVP and fixed the broken tests.

### To Test

- Run tests in `OrderListViewModelTests`
- Run tests in `OrderListItemTest`
- Run tests in `OrderListNavigationTest`

### CODE REVIEW

File: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt [hunk 1]
```diff
@@ -38,6 +45,94 @@ object WcOrderTestUtils {
...
+        result.add(om5)
+        result.add(om6)
+        result.add(om7)
+
+        return result
+    }
+
     /**
      * Generates an array containing multiple [WCOrderModel] objects.
      */
```
Comment (anitaa1990) [inline WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt]: np: Since this is not being used anywhere can we delete this method?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 2]
```diff
@@ -47,27 +48,32 @@ typealias PagedOrdersList = PagedList<OrderListItemUIType>
...
     private val selectedSite: SelectedSite
 ) : ScopedViewModel(mainDispatcher), LifecycleOwner {
-    private val lifecycleRegistry: LifecycleRegistry by lazy {
+    protected val lifecycleRegistry: LifecycleRegistry by lazy {
         LifecycleRegistry(this)
     }
     override fun getLifecycle(): Lifecycle = lifecycleRegistry
 
-    private var pagedListWrapper: PagedListWrapper<OrderListItemUIType>? = null
+    @get:VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
```
Comment (anitaa1990) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt]: TIL <3

File: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt (hunk 1 above)
Comment (AmandaRiu) [reply WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/orders/WcOrderTestUtils.kt]: Surely, I'll do that in the next PR. Thanks for the catch!
