### PR TITLE
Fix order details performance transaction validation

### LINKED ISSUE #7428: Fix performance tracking of Order Details
**Describe the bug**

In #7242 we introduced conditional fetches of Order Details parts like shipping labels or shipment tracking.

Unfortunately, it brakes performance transactions introduced in #7069. The reason is that now we early quit functions like `fetchShipmentTrackingAsync`, which means that we never meet performance's satisfying conditions by executing  `onShipmentTrackingFetched`. This results in every transaction is not finished, which means that our next events will start measurement on the open of the screen and will finish at the end of the browsing, not at the end of the http calls.

**To Reproduce**
1. In debug, open any Order
2. In Sentry notice that transaction is not uploaded
3. Exit the Order Details
4. In Sentry, notice that transaction is uploaded. It's length is the time between steps 2 and 3. It's status is "ABORTED".

**Screenshots**
image

**Expected behavior**
Transaction satisfying methods like `onShipmentTrackingFetched` should be executed, even if a user does not have required plugin.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #7428

### Description

This PR makes plugin-related conditions of Performance Transaction Launcher satisfied in case, when user does not have shipping labels or shipment tracking plugins.

### Testing instructions

0. Disable shipping labels and/or shipment tracking (?) plugin (is there "shipment tracking" plugin?)
1. Open Order Details
2. Go to Sentry Performance.
3. Select OrderDetails transaction. Envirnoment: `debug`.
4. Select `Filter Recent Transaction`
5. Make sure that the new transaction is visible

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt [hunk 1]
```diff
@@ -642,28 +642,23 @@ class OrderDetailViewModel @Inject constructor(
...
-            }?.let {
-                // Fetch data only when the plugin is installed and active
-                return@async
-            }
-        val result = orderDetailRepository.fetchOrderShipmentTrackingList(navArgs.orderId)
-        appPrefs.setTrackingExtensionAvailable(result == SUCCESS)
-        orderDetailsTransactionLauncher.onShipmentTrackingFetched()
+        val plugin = pluginsInformation[WooCommerceStore.WooPlugin.WOO_SHIPMENT_TRACKING.pluginName]
+
+        if (plugin == null || plugin.isOperational) {
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt:647]: I refactored from the previous syntax as I believe this `if` makes things more readable.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncher.kt [hunk 2]
```diff
@@ -56,13 +56,13 @@ class OrderDetailsTransactionLauncher @Inject constructor(
 
     fun onOrderFetched() = satisfyCondition(Conditions.ORDER_FETCHED)
 
-    fun onShippingLabelFetched() = satisfyCondition(Conditions.SHIPPING_LABEL_FETCHED)
+    fun onShippingLabelFetchingCompleted() = satisfyCondition(Conditions.SHIPPING_LABEL_FETCHED)
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailsTransactionLauncher.kt:59]: I've renamed those method in a separate commit, for checking clue of this PR see 2f87456315b02ea2d4dcb0d39be974d142263cb7

**Review by wzieba — COMMENTED** [review]
Many kudos for unit tests @atorresveiga ! They helped me a lot in reproduction and adding new conditions.

Also, I learned the intended behavior then reading 
> when there is no info about the plugins, then optimistically fetch plugin data

description.

**Comment by atorresveiga** [comment]
>is there "shipment tracking" plugin?

The shipment tracking plugin name is `WooCommerce Shipment Tracking`. I believe you mean "Shipping Labels" plugin, because there is no "Shipping Labels" plugin indeed. Shipping labels is part of the `WooCommerceStore.WooPlugin.WOO_SERVICES` plugin and is displayed as "WooCommerce Shipping & Tax" in the installed plugins screen

**Review by atorresveiga — APPROVED** [review]
Great work @wzieba. I liked your improvements to the code and everything is working as expected. 🎉
