### PR TITLE
[Min-Max Quantities] M1 Fixes

### LINKED ISSUE #11818: [Min/Max Quantities] Beta Test Issues
pe5pgL-55p-p2#comment-4224

### PR DESCRIPTION
**Pull request by toupper**
Closes: #11818 

### Description

With this PR we fix two issues reported after the Min-Max Quantities Beta Testing:

- When the product or variation has no Quantity Rule set (but the plugin is installed and active), we show No Quantity Rules in the Product Detail.
- We follow this logic to show the Quantity Rules in variations:

> We show the Quantity Rules in the Product Variation Detail form if:
> 
> The product variation overrides the parent product rules (variation_quantity_rules to yes in [API](https://href.li/?https://woocommerce.com/document/minmax-quantities/#section-6)) AND
> The parent product doesn’t disable quantity rules (combine_variations to no in [API](https://href.li/?https://woocommerce.com/document/minmax-quantities/#section-6))

#### No Quantity Rule set

1. Set product without any Quantity Rules set (See screenshot)
2. Go to products
3. Tap on that product
4. We should show No Quantity Rules in the detail view (See screenshot)

image

#### Variations logic

These are the conditions to show the Quantity Rules in a variation detail view:

> The product variation overrides the parent product rules (variation_quantity_rules to yes in [API](https://href.li/?https://woocommerce.com/document/minmax-quantities/#section-6)) AND
> The parent product doesn’t disable quantity rules (combine_variations to no in [API](https://href.li/?https://woocommerce.com/document/minmax-quantities/#section-6

Test therefore these combinations:

1. The variation overrides the parent product rules and the parent product doesn’t disable quantity rules --> Shows the Quantity Rules row in the variation detail view
2. Any (or both) of these conditions are false --> Does not show the Quantity Rules row in the variation detail view

image

image

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/223">19.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            showTitle = true,
+            onClick = onClick
+        )
+    } else {
+        productProperty = ProductProperty.ComplexProperty(
+            title = R.string.product_quantity_rules_title,
+            value = resources.getString(R.string.no_quantity_rules),
+            icon = R.drawable.ic_gridicons_product,
+            onClick = onClick
+        )
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt:38]: np: We can group the whole idea into a when statement and return that: the code could look like:

```
return when {
   quantityRules.allRulesAreNull -> null
   quantityRules.hasAtLeastOneValidRule -> {
           val properties: Map<String, String> = buildMap ....
           ProductProperty.PropertyGroup(
            title = R.string.product_quantity_rules_title,
            icon = R.drawable.ic_gridicons_product,
            properties = properties,
            showTitle = true,
            onClick = onClick
    }
    else {
            ProductProperty.ComplexProperty(
            title = R.string.product_quantity_rules_title,
            value = resources.getString(R.string.no_quantity_rules),
            icon = R.drawable.ic_gridicons_product,
            onClick = onClick
        )
     }
}
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+fun generateQuantityRulesProductProperty(
+    quantityRules: QuantityRules,
+    resources: ResourceProvider,
+    onClick: (() -> Unit)
+): ProductProperty? {
+    if (quantityRules.allRulesAreNull) {
+        return null
+    }
+
+    var productProperty: ProductProperty
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt:15]: In Kotlin, you can assign a variable to the result of a conditional statement

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    return productProperty
+}
+
+private fun MutableMap<String, String>.putIfNotNullOrZero(vararg pairs: Pair<String, String?>) = apply {
+    pairs.forEach { pair ->
+        pair.second?.takeIf { it != "0" }?.let { put(pair.first, it) }
+    }
+}
+
+private val QuantityRules.hasAtLeastOneValidRule: Boolean
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt:50]: Nice!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt [hunk 4]
```diff
@@ -0,0 +1,54 @@
+package com.woocommerce.android.ui.products.models
+
+import com.woocommerce.android.R
+import com.woocommerce.android.viewmodel.ResourceProvider
+
+fun generateQuantityRulesProductProperty(
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExt.kt:6]: Does it make sense to have this function as an extension function of QuantityRules? Something like:  `QuantityRules.getProductProperty() { ...`

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExtTest.kt [hunk 5]
```diff
@@ -0,0 +1,69 @@
+package com.woocommerce.android.ui.products.models
```
Comment (atorresveiga) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/models/ProductPropertyExtTest.kt:1]: Nice!

**Review by atorresveiga — APPROVED** [review]
Great work @toupper!
I left a couple of suggestions but feel free to merge the code. The behavior is the expected.

LGTM! :shipit:

**Comment by toupper** [comment]
Thanks for the review and the tips @atorresveiga! Quite useful. I will merge this PR to make it into the release and add your improvements in a new PR.
