### PR TITLE
Issue/3127 hide already selected products

### LINKED ISSUE #3127: ProductsM5: Exclude Already-Selected Products from Product Selection
## Current Behavior

When adding linked products to a product with no pre-existing linked products, the product selection list still shows the products that the user has previously selected. 

This only happens if using the “Add Products” button and not the “Edit Products”. 

### Steps to Reproduce

1. Navigate to a product with no linked products.
2. Tap on Add More Details → Linked Products.
3. Tap on Upsells “Add Products” button. 
4. Tap on “Add Product”. The app should show the product selection page. 
5. Select the top 3 products and remember them. 
6. Tap Done. 
7. Tap on “Add Product” again. 
8. Notice that the previous 3 products that you selected are still visible in the list. 

## Expected Behavior

The product selection should be filtered so that the previously selected linked products should not be shown anymore.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3127 - previously, if you added linked products to a product that didn't have any and then returned to the product selector to add more, the previously selected ones would continue to appear. This PR corrects this by passing a list of excluded product IDs to the selector.

To test:

- Go to product detail for a linked product that has no cross-sells (or no upsells)
- Tap the "Add product" button below the cross-sells
- Add a product or two and click done
- Click "Edit product" below the cross-sells
- Choose to add a product and verify that the previously added products no longer appear

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt [hunk 1]
```diff
@@ -165,12 +165,18 @@ class ProductListRepository @Inject constructor(
         productFilterOptions: Map<ProductFilterOption, String> = emptyMap(),
         excludedProductIds: List<Long>? = null
     ): List<Product> {
+        // we need to pass null because FluxC crashes when an empty list is passed
+        val excludedIds = if (excludedProductIds?.isNotEmpty() == true) {
+            excludedProductIds
+        } else {
+            null
+        }
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt]: np: If think it's useful, you can take advantage of the `takeIf` to also imply a nullable condition clause
```suggestion
        val excludedIds = excludedProductIds?.takeIf { it.isNotEmpty() }
```

**Review by ThomazFB — DISMISSED** [review]
Hey @nbradbury, everything looks like it's working just fine. I've just left a minor np, but it's nothing important. Thanks for the great work here! I'll leave the PR pre-approved and let it up to you to decide if you think the suggestion is useful or not for what you want to express there.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListRepository.kt]: Thanks for the tip, that's a much cleaner approach! I made the change in 0b99bcf.

**Review by ThomazFB — APPROVED** [review]
Looking good, @nbradbury! :shipit:
