### PR TITLE
Shipping Labels: Finish Customs form

### LINKED ISSUE #4094: Shipping Labels: wrong product_id is passed for variations
When creating shipping labels, we are passing the wrong `product_id` if the item is a variation,

### PR DESCRIPTION
**Pull request by hichamboushaba**
Part 4 of #3526, this includes the following changes:
1. Wires the customs form to the rest of SL form.
2. Updates the rates and purchase endpoint calls to pass the customs data.
3. Updates the origin address validation to require a phone number when the shipment is international.
4. Updates the logic to "undone" the origin step if the shipment is changed to international after the destination step.
5. Fixes the bug #4094.

The logic of the point 4 will be updated in a separate PR to implement what @Garance91540 suggested in Slack:  p1622477175152100/1614252487.023600-slack-CGPNUU63E.

#### Testing
For all the following test cases, please use an order that's eligible for shipping label creation.

##### Customs form visibility
Play with different origin and destination countries, and confirm that the customs form is visible only for international shipments.

##### Origin address validation
Confirm that phone number is required in the origin address form if the shipment is international.

##### Customs data
Confirm that the customs form is pre-populated with data from the selected package and the order's items, and that the data is saved for edition after clicking on "done".

##### Data invalidation
Confirm that after making changes to the packages step, the customs form is being reset.

##### Shipping label purchase
Purchase an international shipping label, and confirm that the label contains customs data.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt [hunk 1]
```diff
@@ -17,30 +22,74 @@ data class CustomsPackage(
...
-) : Parcelable
+) : Parcelable {
+    fun toDataModel(): WCCustomsItem {
+        return WCCustomsItem(
+            productId = productId,
+            description = itemDescription,
+            hsTariffNumber = hsTariffNumber,
+            quantity = quantity,
+            value = value!!,
+            weight = weight!!,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt:57]: As we are validating the data on UI side, we can assume that this is not null here, and if for some reason it's null, early crashing is better than creating a label with wrong data, and will help us identify the bug earlier.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt [hunk 2]
```diff
@@ -190,9 +192,12 @@ class EditShippingLabelPackagesViewModel @AssistedInject constructor(
         }
 
         return ShippingLabelPackage.Item(
-            productId = productId,
+            productId = uniqueId,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/EditShippingLabelPackagesViewModel.kt:192]: This fixes #4094

**Review by Garance91540 — CHANGES_REQUESTED** [review]
Hi Hicham! The only thing I can see is that the text in the "Customs" row of the main Task List should update from "fill out customs form" to "Customs form completed" after it's completed https://d.pr/i/DELVMa

**Comment by hichamboushaba** [comment]
> Hi Hicham! The only thing I can see is that the text in the "Customs" row of the main Task List should update from "fill out customs form" to "Customs form completed" after it's completed https://d.pr/i/DELVMa

Thanks @Garance91540 for the review, I noticed it yesterday and fixed it in 0e2f9420d96e7f101f28674329e7cac924e0a9f5, but I didn't update the video 🤦 
Screen Shot 2021-06-03 at 17 45 50

**Review by Garance91540 — APPROVED** [review]
👏

**Comment by nbradbury** [comment]
@hichamboushaba Just a note that I've assigned myself to this and wanted to make sure you were aware of the conflicts.

**Comment by hichamboushaba** [comment]
> @hichamboushaba Just a note that I've assigned myself to this and wanted to make sure you were aware of the conflicts.

Thanks for the heads up @nbradbury, I'll fix them right now.

**Comment by nbradbury** [comment]
@hichamboushaba I found a couple of minor issues, feel free to address them separately if you'd rather not hold up this PR.

- If you enter information into the customs form and hit the back button, there's no "discard confirmation" - should one be necessary?
- If you fail to enter a required field, such as phone number or zip code, you get the warning that the field is required. But if you then type something, the warning doesn't go away. Also, the warning under the phone number is different than the rest and doesn't really make sense.
required

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/model/CustomsPackage.kt:57]: It'd be good to add this comment to the code, because looking at it I would think using `!!` on nullable values is a bug.

**Comment by hichamboushaba** [comment]
Thanks @nbradbury for the review.

> If you enter information into the customs form and hit the back button, there's no "discard confirmation" - should one be necessary?

We don't have them in any of the shipping labels form, if they are required, then we need to add them to all the screens, and we can do it in a separate PR, @Garance91540 WDYT about the necessity of "discard confirmation" dialogs here?

> If you fail to enter a required field, such as phone number or zip code, you get the warning that the field is required. But if you then type something, the warning doesn't go away. Also, the warning under the phone number is different than the rest and doesn't really make sense.

This is unrelated to this PR, and I noticed it too, fixing it would require some big changes to the logic of this screen, can you create a ticket for this one? or I can do it myself later 🙂

**Comment by nbradbury** [comment]
> This is unrelated to this PR, and I noticed it too, fixing it would require some big changes to the logic of this screen, can you create a ticket for this one?

Filed #4177 for this.

**Comment by hichamboushaba** [comment]
> Filed #4177 for this.

Thanks @nbradbury, I took the liberty to update the issue to mention that it happens in the Address form, and not the customs form 🙂.
Can you approve this PR now, or you are still checking something else? 🙏

**Review by nbradbury — APPROVED** [review]
Looks great! :shipit:
