### PR TITLE
Issue/6168 handling bug related to receipt email

### LINKED ISSUE #6168: Handling potential bug related to receipt email
Context - pdfdoF-Cx-p2

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #6168

### Description

The PR adds:
* Setting receipt emails when Stripe Plugin used
* Settings receipt email when WCPay version <4.0.0 is used

### Testing instructions

Stripe dashbaord can be used to verify that it works
* Try stripe payment, notice that receipt email is sent
* Try Wcpay payment, notice that receipt email is sent
* Try Wcpay payment with modified code:
```
val wcPayPluginInfo = wooStore.getSitePlugin(selectedSite.get(), WooCommerceStore.WooPlugin.WOO_PAYMENTS)
            ?.apply { version = "4.0.0" }
```
> CardReaderOnboardingChecker::95

notice that receipt email is not sent

image
image

### Images/gif

No visual changes this PR brings

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt [hunk 1]
```diff
@@ -232,6 +245,15 @@ class CardReaderOnboardingChecker @Inject constructor(
             status,
             preferredPlugin,
         )
+        if (version != null && preferredPlugin != null) {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt]: 🚫 Unless I'm missing something, we might end up in an inconsistent state. 
1. WCPay version 1.2.3 is used
2. We store `wcpay` and `1.2.3` into shared prefs
3. Stripe with unknown version is used
4. We store `stripe` and version `1.2.3` remains in the shared prefs

I'm not saying it's a real scenario, but the code seems to allow it.

💡 I'd personally vote for having only a single `set` method in the shared preferences - we originally had two methods, one for `plugin` and one of `onboardingState` and it bit us -> it became very difficult to follow and we sometimes ended up with inconsistent state stored in the shared prefs. If we are worried about the name, I think we can simply call it `setCardReaderOnboardingData` or something like that. Wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt [hunk 2]
```diff
@@ -157,6 +161,7 @@ class CardReaderPaymentViewModel
                 currency = order.currency,
                 orderKey = order.orderKey,
                 customerEmail = customerEmail.ifEmpty { null },
+                wcpayCanSendReceipt = isWCPayCanSendReceipts(site),
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: 💡 I'm wondering if a person without the domain knowledge would be able to follow this code. What if we renamed it to something like `pluginSendsReceiptsAutomatically` (I don't think we need to mention WCPay, since the method handles even Stripe Extension). Another option is to add a comment explaining the domain, wdyt?

**Review by malinajirka — CHANGES_REQUESTED** [review]
Thanks for working on this @kidinov! I've left a few suggestions, let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt]: I even was trying to make PluginType keeping the version but it was way to big of a change

Like your approach here - done 45f4a8de905e6ba169251072681507ca5a6ad864

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt (hunk 2 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: I think my naming is simply incorrect. This is indeed about if the plugin can send receipts or not. Fixed - 974fef80b13cf9ce2969e45e18168d4d0e8b159f

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt [hunk 3]
```diff
@@ -34,6 +34,8 @@ const val SUPPORTED_WCPAY_VERSION = "3.2.1"
 @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
 const val SUPPORTED_STRIPE_EXTENSION_VERSION = "6.2.0"
 
+const val WCPAY_STYLED_RECEIPTS_SUPPORT_VERSION = "4.0.0"
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt]: ❓ Sorry, I missed this during the first review. I'm wondering how this is related to `styled receipts` (except of the fact that the backend team worked on styled receipts at the same time)? Feels like this PR is about `automatic receipts` not `styled receipts`. What do you think about renaming this constant?

**Review by malinajirka — APPROVED** [review]
Thanks @kidinov! I've reviewed and tested the app and it all LGTM. Left one minor comment, but it's ready for merge even now.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt (hunk 3 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/onboarding/CardReaderOnboardingChecker.kt]: The style of the receipts changed when WCPay started to send them because WC email template is used, but I agree that the main here is the fact that WCPay can send a receipt. Renamed - 01d3da4d9eeb57f41b0ea222975df76bfeba71c0
