### PR TITLE
Fix/9262 tracking free trial created

### LINKED ISSUE #9262: Add new dedicated event to track how many free trial stores are created from mobile apps
The new event to be tracked: 
- **Name:** `_site_creation_free_trial_created_success`
- **Triggered** when requests /sites/new/ and /sites/$siteId/ecommerce-trial/add/ecommerce-trial-bundle-monthly/ are successful after the user clicked on “Try for free” CTA on store creation flow.
- **Properties:** `blog_id`: new site’s blog Id value `initial_domain`: the default domain added to the site upon creation

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #9262 

### Description

We need a straightforward way to measure how many free trial stores are created from mobile apps. When measuring this, we also want to have an easy way to know what stores exactly have been created from the apps. For that we are adding a new dedicated event with the following properties and behavior: 

- **Name:** `_site_creation_free_trial_created_success`
- **Triggered** when requests /sites/new/ and /sites/$siteId/ecommerce-trial/add/ecommerce-trial-bundle-monthly/ are successful after the user clicked on “Try for free” CTA on store creation flow.
- **Properties:** `new_site_id`: new site’s blog Id value `initial_domain`: the default domain added to the site upon creation

We want to release this ASAP to start gathering data. Thus, we are merging this to the current `release/14.1` branch.

### Testing instructions

Trigger store creation flow and check the following event is tracked: `Tracked: site_creation_free_trial_created_success, Properties: {"blog_id":220392323,"initial_domain":"woo-usually-zany-basement.wordpress.com","is_wpcom_store":true,"is_debug":true}`

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt [hunk 1]
```diff
@@ -176,9 +176,6 @@ class StoreCreationRepository @Inject constructor(
 
         return when (createSiteResult) {
             is Success -> {
-                val site = siteStore.getSiteBySiteId(createSiteResult.data)
-                val domain = Uri.parse(site?.url.orEmpty()).host.orEmpty()
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/StoreCreationRepository.kt:180]: There's no code responsible for saving the "new site" into the database after `/sites/new/`, so this 2 lines were not doing anything. `val site` is always null. 

I moved setting the new site's domain a few lines below, so that we can use `newStore.domain` value later on in the view model for tracking purposes.

**Review by hafizrahman — APPROVED** [review]
Works correctly in my test:

> 🔵 Tracked: site_creation_free_trial_created_success, Properties: {"blog_id":211272157,"initial_domain":"woo-exactly-steady-cycle.wordpress.com","is_wpcom_store":true,"is_debug":true}

Code changes are minimal and they make sense too. Nice quick work @JorgeMucientes

**Comment by hafizrahman** [comment]
> We want to release this ASAP to start gathering data. Thus, we are merging this to the current release/14.1 branch.

@jkmassel apologize for another ping, but can you also please add this into the a new beta cut for 14.1? Thanks in advance!
