### PR TITLE
Fixed crash when order note list adapter is null

### LINKED ISSUE #2153: TypeCastException: null cannot be cast to non-null type com.woocommerce.android.ui.orders.notes.OrderNotesAdapter
Sentry Issue: [WOOCOMMERCE-ANDROID-C7](https://sentry.io/organizations/a8c/issues/1493996307/?referrer=github_integration)

```
TypeCastException: null cannot be cast to non-null type com.woocommerce.android.ui.orders.notes.OrderNotesAdapter
    at com.woocommerce.android.ui.orders.notes.OrderDetailOrderNoteListView.updateView(OrderDetailOrderNoteListView.kt:63)
    at com.woocommerce.android.ui.orders.OrderDetailFragment.updateOrderNotes(OrderDetailFragment.kt:307)
    at com.woocommerce.android.ui.orders.OrderDetailPresenter.onOrderChanged(OrderDetailPresenter.kt:401)
...
(8 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:107)
...
(5 additional frame(s) were not displayed)

Invoking subscriber failed
```

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2153. I wasn't able to reproduce the crash 🤦‍♀but thought that initialising the adapter again if it is null would fix the crash.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderDetailOrderNoteListView.kt [hunk 1]
```diff
@@ -60,7 +60,7 @@ class OrderDetailOrderNoteListView @JvmOverloads constructor(ctx: Context, attrs
     }
 
     fun updateView(notes: List<OrderNote>) {
-        val adapter = notesList_notes.adapter as OrderNotesAdapter
+        val adapter = notesList_notes.adapter as? OrderNotesAdapter ?: OrderNotesAdapter()
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderDetailOrderNoteListView.kt]: You could further simplify the code and remove the adapter initialization from `initView()` and just call this function.

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/OrderDetailOrderNoteListView.kt]: Thanks for the review @0nko! Fixed in edc95e5
