### PR TITLE
Fix state selection incorrect data mapping

### LINKED ISSUE #5107: [Order Editing] Country State selection sometime appears as code instead of names
https://user-images.githubusercontent.com/5920403/139359701-b7a1d326-ad80-46a9-b4d5-66550209c1c3.mp4

### LINKED ISSUE #5108: [Order Editing] Country State code sometimes maps to an unrelated information
https://user-images.githubusercontent.com/5920403/139360022-64a205b2-9e17-4476-9fca-11b42352c103.mp4

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #5107 and #5108 by creating a mechanism to update the Country data before doing any change to the Country State code, this bug was happening because when we're doing this copy operation:

```
viewState = viewState.copy(
            countryLocation = getCountryLocationFromCode(countryCode),
            stateLocation = getStateLocationFromCode(stateCode)
        )
```

The `getStateLocationFromCode` function uses the Country code to update to the correct data:

```
dataStore.getStates(viewState.countryLocation.code).map { it.toAppModel() }
```

But if we're updating both Country and State at once, the Country location won't be updated into the ViewState yet, and the State location may be acquired from an outdated Country source.

How to Reproduce
==========
##Scenario 1 (#5108)
1. Go to an Order, select Shipping or Billing address, configure the Country as `Brazil` and the State as `Minas Gerais` and click `done`
2. Go back to the orders list, open back the same Order details, and open again the same Address editing view, verify that the state instead of showing `Minas Gerais`, will be displaying `Madagascar`, but Madagascar is a Country with no relation with Brazilian states. Minas Gerais state code is MG, and Madagascar country code is also MG, but since the state list wasn't updated yet during the `start` method, the State data list is a copy of the world country list, accidentally matching with an incorrect code.

##Scenario 2 (#5107)
1. Go to an Order, select Shipping or Billing address, configure the Country as `Brazil` and the State as `Amapá` and click `done`
2. Go back to the orders list, open back the same Order details, and open again the same Address editing view, verify that the state instead of showing `Amapá`, will be displaying `AP`, because since the State list isn't updated yet and contains the World country list, there's no Country matching the `AP` code, so the `getStateNameFromCode` returns the State code instead of the name.

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
Thanks for catching this @ThomazFB! Fix is good :shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt [hunk 1]
```diff
@@ -95,6 +89,24 @@ class AddressViewModel @Inject constructor(
...
+
+        viewState = viewState.copy(
+            countryLocation = countryLocation
+        )
+
+        viewState = this.copy(
+            countryLocation = countryLocation,
+            stateLocation = getStateLocationFromCode(stateCode)
+        )
+    }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt:108]: hi @ThomazFB 👋 I have non-urgent question - I'm having hard time to understand why do we need lines 100-102, doesn't it do the same as line 105?

If we'll have:

```kotlin
    private fun ViewState.applyCountryStateChangesSafely(countryCode: String, stateCode: String) {
        val countryLocation = getCountryLocationFromCode(countryCode)

        viewState = copy(
            countryLocation = countryLocation,
            stateLocation = getStateLocationFromCode(stateCode),
        )
    }
```

Could you provide a test case that will make any unwanted behaviour? Thanks in advance!

Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt:108]: Hey @wzieba 👋 The test case I recommend would be the ones detailed in the PR description. I'll walkthrough the issue using your code:

Let's say we have `countryCode` value as `BR` and `stateCode` as `MG` and the `start` method was just called, the view was just created and the `viewState` right now contains the initial state:

```
    @Parcelize
    data class ViewState(
        val countryLocation: Location = Location("", ""),
        val stateLocation: Location = Location("", ""),
        val isLoading: Boolean = false
    ) : Parcelable
```
After running `dataStore.fetchCountriesAndStates(selectedSite.get())` we will only have a Country list available at the ViewModel, because the state list depends on a selected State, which we don't have right now:

```
val states: List<Location>
        get() = dataStore.getStates(viewState.countryLocation.code).map { it.toAppModel() }
```

Now the `applyCountryStateChangesSafely` is called containing both countryCode and stateCode, with the values I said before. We call `getCountryLocationFromCode(countryCode)` and it returns what was found inside the `countries` properties. That will work, and it will return a Location containing information from `Brazil`. And now we go to the issue itself:

```
viewState = copy(
            countryLocation = countryLocation,
            stateLocation = getStateLocationFromCode(stateCode),
        )
```

We're creating a copy of the ViewState to overwrite the current empty Locations inside there, nice! The country will be updated just fine, and now at the same copy call, we call `getStateLocationFromCode(stateCode)`, the problem is what this method will return here:
```
    private fun getStateNameFromCode(stateCode: String): String {
        return states.find { it.code == stateCode }?.name ?: stateCode
    }
```

What's the current value of the `states` property here in this call? It won't be Brazilian states, but a list from a non-defined country:

```
   val states: List<Location>
        get() = dataStore.getStates(viewState.countryLocation.code).map { it.toAppModel() }
```

We didn't update the country code at the `viewState` yet, because the update is happening at the same copy call, so it will try to find the `MG` state inside a state list that is not the Brazilian one. The funny part is that the country/state datastore returns the full country list if we request states from an empty country code. So we will try to find the Brazilian state code `MG` from the country list, and `getStateNameFromCode` will return `Madagascar` instead of `Minas Gerais` 😅

I decided to fix this on the easy way since it was a Friday before releasing the Order Editing feature, so my solution was to update the country code first at the ViewState before requesting the state code. I hope this is enough to clarify the issue here 😬 Let me know if you need further details.

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/editing/address/AddressViewModel.kt:108]: Thank you @ThomazFB - I'll dive deep into this explanation in a few days as I'm just wrapping up before AFK but I appreciate you took time to write this comment 🙇 .
