### PR TITLE
Issue/5377 product tags adapter exception

### LINKED ISSUE #5377: IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclervi...
Sentry Issue: [WOOCOMMERCE-ANDROID-2EQ](https://sentry.io/organizations/a8c/issues/2694107600/?referrer=github_integration)

```
IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{b760ee3 VFED..... ......I. 0,279-1080,1200 #7f0a0592 app:id/productTagsRecycler}, adapter:com.woocommerce.android.ui.products.tags.ProductTagsAdapter@cfc04a6, layout:androidx.recyclerview.widget.LinearLayoutManager@f1cbee7, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@4ace8d5
    at com.woocommerce.android.ui.products.tags.ProductTagsAdapter.setProductTags(ProductTagsAdapter.kt:62)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment.showProductTags(ProductTagsFragment.kt:178)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment.setupObservers$lambda-4(ProductTagsFragment.kt:152)
    at com.woocommerce.android.ui.products.tags.ProductTagsFragment.lambda$V3Twk4e2IPgaxlYF3qGufxO70Lw
    at com.woocommerce.android.ui.products.tags.-$$Lambda$ProductTagsFragment$V3Twk4e2IPgaxlYF3qGufxO70Lw.onChanged
...
(118 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nbradbury**
This is an attempt to fix #5377, which so far we've not been able to reproduce but as of today it has been experienced by 127 users for a total of 1.1k events.

@wzieba I'm requesting your review since on the issue [you suggested](https://github.com/woocommerce/woocommerce-android/issues/5377#issuecomment-982372857):

1. > Changing `ProductTagsAdapter` to override from `androidx.recyclerview.widget.ListAdapter` so diff will be computed on the background thread
2. > Simplify `ProductTagsAdapter#setProductTags` - I think it could have only one line that delegates all diff calculations to `DiffUtil#calculateDiff`

This PR makes both those changes,

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt [hunk 1]
```diff
@@ -26,9 +26,11 @@ class ProductTagsAdapter(
         fun onProductTagRemoved(productTag: ProductTag)
     }
 
-    override fun getItemId(position: Int) = productTags[position].remoteTagId
+    fun setProductTags(productTags: List<ProductTag>) {
+        submitList(productTags)
+    }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt]: A minor - we could remove `setProductTags` and just use `submitList` where it's needed.

**Review by wzieba — APPROVED** [review]
Thanks @nbradbury - I hope it'll resolve the issue 🤞

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/tags/ProductTagsAdapter.kt]: Of course! Added in [3c9e794](https://github.com/woocommerce/woocommerce-android/pull/6113/commits/3c9e794dd8fd5a772a3deada14bc53bb361769dc).

**Comment by wzieba** [comment]
Thank you!
