### PR TITLE
Provide `debug` release variant for `debug` builds in Sentry

### LINKED ISSUE #4292: Do not create PR-based releases on Sentry
### Context

In `Releases` tab in Sentry there are some “releases” named e.g. `pr-4254-build-40412`. It’s because for release name [we provide `VERSION_NAME` constant](https://github.com/woocommerce/woocommerce-android/blob/9731fd0a2e12dd7e251c41f654100d71da61eb97/WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt#L30) and for .apk’s built on CI, this value [is calculated based on PR and build numbers](https://github.com/woocommerce/woocommerce-android/blob/develop/.circleci/config.yml#L122).

image

Those “releases” don’t have any issues because PR-generated APKs [are based on `jalapenoDebug` variant](https://github.com/woocommerce/woocommerce-android/blob/develop/.circleci/config.yml#L124) and [we disable crash logging by default for debug builds](https://github.com/woocommerce/woocommerce-android/blob/5a7805592814f6b994ddcd90fe38cbd70ba1c467/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt#L198).

### Task

This issue is about providing a default, commonized release in Sentry for `debug` variants of the app.

### PR DESCRIPTION
**Pull request by wzieba**
Closes #4292 

For context and reasons for this change please check the issue.

| Before | After |
| ---- | ---- |
| Screenshot 2021-06-28 at 17 31 42 | image |

### TC1 Debug variant 
1. Apply the attached `Patch` available at the bottom
2. Build debug variant and run the app
3. Go to `releases` on the Sentry dashboard
4. **Make sure there's `debug` release**
5. Go to `issues` on the Sentry dashboard
6. Select "This is test" issue
7. **Make sure it has `debug` release attached**
8. **Remove the issue**

### TC2 Release variant
1. Apply the attached `Patch` available at the bottom
2. Build release variant and run the app
3. Go to `issues` on the Sentry dashboard
4. Select "This is test" issue
5. **Make sure it has `6.9-rc-2` release attached**
6. **Remove the issue**

### TC3 Installable build
1. Run the app built by CI (link should be available in PRs comments)
2. Go to `releases` on the Sentry dashboard
3. Make sure there's no new release matching `pr-####-build-#####` schema

#### Patch

```
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt	(revision ea3a2b5bfac457a545a1ea99ff2745ab6bc7be56)
+++ WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt	(date 1624897863226)
@@ -47,7 +47,7 @@
     }
 
     override fun crashLoggingEnabled(): Boolean {
-        return appPrefs.isCrashReportingEnabled()
+        return true
     }
 
     override fun extraKnownKeys(): List<ExtraKnownKey> {
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt	(revision ea3a2b5bfac457a545a1ea99ff2745ab6bc7be56)
+++ WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt	(date 1624897863222)
@@ -176,6 +176,8 @@
         tabLayout.addOnTabSelectedListener(tabSelectedListener)
 
         refreshMyStoreStats(forced = this.isRefreshPending)
+
+        crashLogging.sendReport(message = "This is test")
     }
 
     private fun initTabLayout() {
```

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProviderTest.kt [hunk 1]
```diff
@@ -159,6 +170,24 @@ class WCCrashLoggingDataProviderTest {
         assertThat(extras).containsValue(generatedUuid)
     }
 
+    @Test
+    fun `should provide version name for release name for not debug build`() {
+        whenever(buildConfig.debug).thenReturn(false)
+
+        reinitialize()
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProviderTest.kt:177]: I had to reinitialize `WCCrashLoggingDataProvider` class as `WCCrashLoggingDataProvider#releaseName` is assigned in the construction phase so after it we can't mock/change `BuildConfigWrapper#debug` value.

Comment (hichamboushaba) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProviderTest.kt:177]: I face a similar issue for multiple tests, and this is why I tend sometimes to avoid the @Setup, and use a single initialization function that I can call at the right time.

**Review by hichamboushaba — APPROVED** [review]
Looks good, thanks for taking care of this @wzieba 🙏
