### PR TITLE
Fix crash when `adminUrl` is missing

### LINKED ISSUE #8428: NullPointerException: selectedSite.get().adminUrl must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-4S0](https://a8c.sentry.io/issues/3537242837/?referrer=github_integration)

```
NullPointerException: selectedSite.get().adminUrl must not be null
    at com.woocommerce.android.ui.moremenu.MoreMenuViewModel.onViewAdminButtonClick(MoreMenuViewModel.kt:140)
    at com.woocommerce.android.ui.moremenu.MoreMenuViewModel.access$getSelectedSiteAbsoluteUrl(MoreMenuViewModel.kt:32)
    at com.woocommerce.android.ui.moremenu.MoreMenuViewModel.access$onViewAdminButtonClick(MoreMenuViewModel.kt:32)
    at com.woocommerce.android.ui.moremenu.MoreMenuViewModel$generateMenuButtons$3.invoke(MoreMenuViewModel.kt:71)
    at com.woocommerce.android.ui.moremenu.MoreMenuViewModel$generateMenuButtons$3.invoke(MoreMenuViewModel.kt:71)
...
(82 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8428 

### Description
When accessing a site using site credentials, the property `adminUrl` will be missing (until we find a way to fetch it in the future), this causes a crash when trying to access the property in different places in the app (the main one is in the More screen).

### Testing instructions
1. Open the app then sign in using non-Jetpack site.
2. Open the More screen.
3. Click on "WC Admin"
4. Confirm a browser is opened and the app doesn't crash

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt [hunk 1]
```diff
@@ -35,3 +36,6 @@ fun SiteModel?.getTitle(default: String): String {
 // The isWPCom property is set as true only for pure WPCom sites that don't have Jetpack connection
 val SiteModel.isSimpleWPComSite
     get() = isWPCom
+
+val SiteModel.safeAdminUrl
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt]: If you have a suggestion for a better name please let me know 🙏

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/error/notwoo/LoginNotWooViewModel.kt [hunk 2]
```diff
@@ -44,7 +45,7 @@ class LoginNotWooViewModel @Inject constructor(
     fun openWooInstallationScreen() = launch {
         val site = wpApiSiteRepository.getSiteByUrl(siteUrl)
 
-        val installationUrl = (site?.adminUrl ?: siteUrl.slashJoin("wp-admin")).slashJoin(INSTALL_PATH)
+        val installationUrl = (site?.safeAdminUrl ?: siteUrl.slashJoin("wp-admin")).slashJoin(INSTALL_PATH)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/error/notwoo/LoginNotWooViewModel.kt]: We still use a manual construction here, it would happen if `site` is `null`, which should never happen, but still I don't think it's wise to change it in this PR targeting a frozen branch.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt (hunk 1 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt]: `nonNullableAdminUrl` or `notNullAdminUrl` ? 
Don't have a strong opinion on it, but the `safe` wording referred on a url variable could mean many things, like for example if the url is `https`.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for fixing this @hichamboushaba. Works well and the code looks good. I'll leave it up to you if you want to rename the variable 👍🏼

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/SiteModelExt.kt]: As discussed, I updated the name to `adminUrlOrDefault` in [71a0002](https://github.com/woocommerce/woocommerce-android/pull/8430/commits/71a00022e5abacbe65b873972e1c4b2a47c843aa)

**Comment by hichamboushaba** [comment]
@ParaskP7 the PR is merged, I think we can go ahead with a new RC release.

**Comment by ParaskP7** [comment]
👋 @hichamboushaba and thanks a lot for the ping! 💯 

> I think we can go ahead with a new RC release.

FYI: Currently the adoption of `12.5-rc-1` is at `2%` and the crash free session rate there looks good to me (`99.949%`). 

As such, do we really need a new `12.5-rc-2` release? Wouldn't it be better if we just create the `final` build on Friday (as scheduled) and then release the final `12.5` release next week, wdyt? 🤔

**Comment by hichamboushaba** [comment]
> As such, do we really need a new 12.5-rc-2 release? Wouldn't it be better if we just create the final build on Friday (as scheduled) and then release the final 12.5 release next week, wdyt?

Good point @ParaskP7, I was just looking for a way to confirm that the fix fixes all of the occurrences, but I don't think it's necessary, the fix is obvious, so we should be fine, it's OK to wait for the final release.

**Comment by ParaskP7** [comment]
> Good point @ParaskP7, I was just looking for a way to confirm that the fix fixes all of the occurrences, but I don't think it's necessary, the fix is obvious, so we should be fine, it's OK to wait for the final release.

You got it, thanks for confirming on that @hichamboushaba ! 🙇 🙏
