### PR TITLE
Issue/425 hide future orders

### LINKED ISSUE #425: Orders with `scheduled-payment` Order Status always appear in `Today` Orders View
### Expected behavior

Orders with `scheduled-payment` Order Status should not appear in `Today` Orders View. 

### Actual behavior

Orders with `scheduled-payment` Order Status always appear in `Today` Orders View:

Image Link: https://cloudup.com/cPQBs8lvlTY

Here is Order #1178 page:

Image Link: https://cloudup.com/cO2H8CIrHGH

Here is Order #1179 page:

Image Link: https://cloudup.com/cbarkDlDQC4

### Steps to reproduce the behavior

1) Download [WooCommerce Deposits](https://woocommerce.com/products/woocommerce-deposits/) extension.

2) Create a **Payment Plan** as follows:

Image Link: https://cloudup.com/cGwAhEGkNmc

3) Create a product and assign the Payment Plan to it in **Deposits** section:

Image Link: https://cloudup.com/c4vPhcfuP0M

4) Place an order for that product on the site. Select `Deposit` and `Payment Plan` upon placing item to the cart:

Image Link: https://cloudup.com/c3k0-RPN0cG

5) Once the order is placed, you should have the initial order for the item for which you paid the deposit + 3 orders that are visible in the **Payment Plan** section. The 3 orders should have a status `scheduled-payment`. In my case, it looks like this since I placed initial order on June 22, 2018:

**Payment Plan (has 2 orders but your view will have 3):**

Image Link: https://cloudup.com/c6AP50jkphZ

**Order 1176 (Deposit Payment - Payment 1) - placed on June 22, 2018:**

Image Link: https://cloudup.com/cboR3744oLY

**Order 1177 (Payment 2) - placed on August 22, 2018:**

Image Link: https://cloudup.com/cVB7-zlGuAt

**Order 1178 (Payment 3) - payment scheduled for October 22, 2018 - FUTURE DATE:**

Image Link: https://cloudup.com/c_OuC7IXX0A

**Order 1179 (Payment 4) - payment scheduled for December 22, 2018 - FUTURE DATE:**

Image Link: https://cloudup.com/cQ28K8FSX-m

6) Open the app and you will see that orders that are a part of the Payment Plan and have `scheduled-payment` Order Status appear in `Today` Orders View when they have future date as an Order Date. 

Image Link: https://cloudup.com/cPQBs8lvlTY

These orders will be appearing every day in `Today` Orders View section. I tested it for several days and they keep moving. 

Ideally, I think we should hide them until they are "placed" (go through as per Payment Plan) and will be actually relevant for `Today` view. 

### Tested in WooCommerce iOS App?

Yes. Same issue is present there. 

##### Tested on [device], Android [version], WCAndroid [version]

- Pixel 2
- Android v 9
- WCAndroid v 0.17

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #425 - mimicking the [iOS app](https://github.com/woocommerce/woocommerce-ios/pull/616), this PR hides orders with a future creation date unless it's today.

A simple way to test this is to change [this line](https://github.com/woocommerce/woocommerce-android/blob/c0a06dec915c2a0a68f3b42455d05e896dd6cc9b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt#L223) to the following and verify that orders in the past 30 days are hidden:

```
val calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"))
calendar.add(Calendar.DAY_OF_YEAR, -30)
val now = calendar.time
```

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt [hunk 1]
```diff
@@ -212,6 +215,25 @@ class OrderListPresenter @Inject constructor(
         }
     }
 
+    /**
+     * Removes orders with a future creation date so we don't show them in the order list
+     * https://github.com/woocommerce/woocommerce-android/issues/425
+     */
+    private fun removeFutureOrders(orders: List<WCOrderModel>): List<WCOrderModel> {
+        val now = DateTimeUtils.nowUTC()
```
Comment (aforcier) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListPresenter.kt]: We could shorten this up slightly/make it more idiomatic by using `orders.filter {}` instead - something like:

```kotlin
val now = DateTimeUtils.nowUTC()

return orders.filter {
  // make sure the creation date is before today, or is today
  val orderDate = DateTimeUtils.dateUTCFromIso8601(it.dateCreated) ?: Date()
  if (orderDate.time <= now.time || DateTimeUtils.daysBetween(orderDate, now) == 0) {
    true
  } else {
    WooLog.i(T.ORDERS, "Hiding future order ${it.dateCreated}")
    false
  }
}
```

Since we want to log the negative case though it's not much neater, and `filter` internally uses an `ArrayList()` anyway. So there isn't any particularly good reason to change it. Just wanted to find something to say on your PR 😀

**Comment by aforcier** [comment]
@nbradbury happy to merge this, but unfortunately we have another conflict with `RELEASE-NOTES.txt` that needs to be sorted first 🙃

**Comment by nbradbury** [comment]
@aforcier Just resolved the conflict, so good to go!

**Comment by aforcier** [comment]
:shipit:
