### PR TITLE
[Stats] Use summary stats endpoint to fetch total visitor count

### LINKED ISSUE #11171: Stats: Adding all visitors from different periods can create inaccurate total visitor count
Describe the bug

Right now, we're computing a site's total visitor count in the Stats screen by adding together the visitor count for each of the intervals within a given period.

However, calculating the total visitors this way can be inaccurate. As outlined in [this support doc](https://wordpress.com/support/stats/#views-and-visitors):

> - A view is counted when a visitor loads or reloads a page.
> - A visitor is counted when we see a user or browser for the first time in a selected time frame.

If I’m viewing my stats for today, I might see that I’ve had 3 visitors today. I might have 3 visitors every day for a week. However, my total visitors for a week won’t necessarily be a sum of the visitors I had for each day of that week (3 + 3 + 3 + 3 + 3 + 3 + 3 = 21 visitors). If I had 3 visitors every day, but they were the same 3 visitors, my total visitor count for the week should be 3 (instead of 21); this is the total we would get if we retrieved the total visitor count with the week granularity.

See also this internal discussion: pe5pgL-1eR-p2#comment-1286, pe5pgL-1p6-p2

###### Copied from https://github.com/woocommerce/woocommerce-ios/issues/8173

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #11171 

### Description
This PR uses https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2983 to use the summary stats endpoint to fetch the visitor's total count; the count is fetched only for predefined ranges.

In this PR, I also made changes to the granularity we use for `2 days` ranges, please check p1711724047631339-slack-C03L1NF1EA3 for more information.

### Testing instructions
I don't have any store that has enough visitor stats to showcase the difference between the `views` and `visitors`, but I think that's OK for now.

1. Open the app.
2. Test the predefined ranges, and confirm total visitors is shown.
3. Optionally: compare the visitor stats count with what's shown in Web and iOS.
4. Create a custom range with a single day.
5. Confirm the visitor's count is shown.
6. Create a custom range with 2 or more days.
7. Confirm the visitor's count is hidden.
8. Tap on a graph point.
9. Confirm the visitor's count is shown.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/204">18.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/ranges/StatsTimeRangeGranularities.kt [hunk 1]
```diff
@@ -35,3 +35,22 @@ val StatsTimeRangeSelection.visitorStatsGranularity: StatsGranularity
...
     }
+
+val StatsTimeRangeSelection.visitorSummaryStatsGranularity: StatsGranularity
+    get() = when (selectionType) {
+        SelectionType.TODAY, SelectionType.YESTERDAY -> StatsGranularity.DAYS
+        SelectionType.LAST_WEEK, SelectionType.WEEK_TO_DATE -> StatsGranularity.WEEKS
+        SelectionType.LAST_MONTH, SelectionType.MONTH_TO_DATE -> StatsGranularity.MONTHS
+        SelectionType.LAST_YEAR, SelectionType.YEAR_TO_DATE -> StatsGranularity.YEARS
+        SelectionType.LAST_QUARTER, SelectionType.QUARTER_TO_DATE ->
+            error("Summary visitor stats unsupported quarter ranges")
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/ranges/StatsTimeRangeGranularities.kt:46]: @atorresveiga this PR adds support for using the summary stats endpoint for visitors count, for now only in the MyStore screen.
When you try to integrate this to the Analytics Hub, please take a note of this limitation, the endpoint doesn't support the `quarter` periods, so you'll have to use something like what iOS are [using](https://github.com/woocommerce/woocommerce-ios/blob/a919ffc19eb6e0f3240707a1cf77a222d604d198/Yosemite/Yosemite/Stores/StatsStoreV4.swift#L250-L268), which is basically "summing up the monthly durations", this won't be as accurate as the monthly one, but it'll be close, see pe5uwI-5c-p2

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Great job, @hichamboushaba. The code looks clean and works well. 
The only issue I noticed is that we are not properly handling the errors when fetching stats. If the users doesn't have access to store stats like `shop manager` roles, then the visitor stats won't even show the dash. As mentioned over Slack, fixing this is out of scope for this PR so we can probably create another GH issue for it. 


https://github.com/woocommerce/woocommerce-android/assets/2663464/55f72973-2e6e-414e-8aa1-afb0265629bf
