### PR TITLE
[Push Notifications fix] Few improvements

### LINKED ISSUE #10327: [Hack Week] Offer a way to fix Cha-ching notification sound issue from the app
Some Android OEMs (and also the case for AOSP Android) make it very easy to change a notification channel to being silent, which could happen accidentally by the users, and could be the reason behind the reports we get about the missing cha-ching sound (#1076).

This task's goal is to offer a way for the users to fix the issue from the app if the change was done accidentally:

```[tasklist]
### Tasks
- [x] Refactor notifications to allow deleting and re-creating notification channels. #10322
- [x] Show an alert in the order list screen when we detect that the sound has been disabled. #10336
- [x] Add an entry to the app settings that allow fixing the sound #10341
- [x] Track the order notifications sound to identify how many users are facing the issues https://github.com/woocommerce/woocommerce-android/pull/11080
- [x] Allow fixing sound when the order notification sound is different from the default one https://github.com/woocommerce/woocommerce-android/pull/11080
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #10327 

### Description
This PR has three main changes:
1. Added a tracks event to track the order notification sound, the sound will be tracked in the event `NEW_ORDER_PUSH_NOTIFICATION_SOUND`, and will have a property `sound_status` that reflects the status of the sound.
2. Updated the logic of fixing notification sound to support the case where the sound was modified and not disabled.
3. Added tracking for the notification fixing solution.

**Some context regarding 2:**
When we implemented the first solution, we were focusing on accidental notification changes (more context here p1701328346130389-slack-C03L1NF1EA3), but since we are getting many complaints about the usage of the app's default sound, I updated the solution to support this case too. I added the logic to the settings entry, the dialog we show from the Orders list will still be shown only when sound is disabled, I think that showing it for anyone who changed the sound could be intrusive, but please let me know what you think.

##### TC 1: Tracking
1. Open the app.
2. Check logcat for an entry: `Tracked: new_order_push_notification_sound, Properties: {"sound_status": { DEFAULT | DISABLED | SOUND_MODIFIED }`

##### TC 2: Fix disabled sound from orders list
1. Open the notifications menu in App Information on your device.
2. Open the "New order alerts" entry, and disable its sound.
3. Open the app.
4. Navigate to orders list.
5. Notice the alert that explains the issue.
6. Confirm an event `new_order_push_notification_fix_shown` was tracked.
7. Tap on "Enable sound"
8. Confirm a Snackbar was shown.
9. Confirm an event `new_order_push_notification_fix_tapped` with `source = order_list` was tracked.

##### TC 3: Fix disabled sound from settings
1. Open the notifications menu in App Information on your device.
2. Open the "New order alerts" entry, and disable its sound.
3. Open the app.
4. Open app settings, then tap on Notifications.
5. Confirm the existence of a button "Enable Cha-Ching sound"
6. Tap on the button.
8. Confirm a Snackbar was shown.
9. Confirm an event `new_order_push_notification_fix_tapped` with `source = settings` was tracked.

##### TC 4: Fix modified sound from settings
1. Open the notifications menu in App Information on your device.
2. Open the "New order alerts" entry.
3. Select a different notification sound.
4. Repeat 3 - 9 from TC 3.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt [hunk 1]
```diff
@@ -680,6 +680,9 @@ class AnalyticsTracker private constructor(
         }
 
         fun track(stat: AnalyticsEvent, properties: Map<String, *> = emptyMap<String, String>()) {
+            if (instance == null && BuildConfig.DEBUG) {
+                error("event $stat was tracked before AnalyticsTracker was initialized.")
+            }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt]: I added this to warn developers about this potential issue, when I first added the notification tracking, I accidentally added it before the call to initialize Analytics, and I didn't notice the issue until I was checking for the event in Logcat.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt [hunk 2]
```diff
@@ -680,6 +681,9 @@ class AnalyticsTracker private constructor(
         }
 
         fun track(stat: AnalyticsEvent, properties: Map<String, *> = emptyMap<String, String>()) {
+            if (instance == null && BuildConfig.DEBUG && !PackageUtils.isTesting()) {
+                error("event $stat was tracked before AnalyticsTracker was initialized.")
+            }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt:687]: Good idea! 👍🏼

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt [hunk 3]
```diff
@@ -86,4 +104,17 @@ class NotificationChannelsHandler @Inject constructor(
...
     }
+
+    private fun NotificationChannel.getNewOrderNotificationSoundStatus(): NewOrderNotificationSoundStatus {
+        if (importance < NotificationManager.IMPORTANCE_DEFAULT) return NewOrderNotificationSoundStatus.DISABLED
+        return when (sound) {
+            context.getChaChingUri() -> NewOrderNotificationSoundStatus.DEFAULT
+            null -> NewOrderNotificationSoundStatus.DISABLED
+            else -> NewOrderNotificationSoundStatus.SOUND_MODIFIED
+        }
+    }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt]: Hmm, I think this is not working as expected. I'm seeing the following event upon starting the app: `Tracked: new_order_push_notification_sound, Properties: {"sound_status":"SOUND_MODIFIED"`. However, I have the `chaChing` sound enabled. 

When I debug this code I can see: 
`sound` = `android.resource://com.woocommerce.android.dev/2131886080`
`context.getChaChingUri()` = `android.resource://com.woocommerce.android.dev/2131951616`

Unsure why the `R.raw.cha_ching` is different

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 4]
```diff
@@ -764,17 +765,25 @@ class OrderListViewModel @Inject constructor(
...
                     messageId = R.string.cha_ching_sound_issue_dialog_message,
                     positiveButtonId = R.string.cha_ching_sound_issue_dialog_turn_on_sound,
                     negativeButtonId = R.string.cha_ching_sound_issue_dialog_keep_silent,
-                    positiveBtnAction = { _, _ -> recreateNotificationChannel() },
+                    positiveBtnAction = { _, _ ->
+                        analyticsTracker.track(
+                            AnalyticsEvent.NEW_ORDER_PUSH_NOTIFICATION_FIX_TAPPED,
+                            mapOf(AnalyticsTracker.KEY_SOURCE to "order_list")
+                        )
+                        recreateNotificationChannel()
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:786]: Minor, but the snackbar we are displaying upoin tapping this button is too fast. I didn't have enough time to click on `TEST SOUND`. I think it would make sense to increase the duration of it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 5]
```diff
@@ -764,17 +765,25 @@ class OrderListViewModel @Inject constructor(
             )
         }
 
-        if (!notificationChannelsHandler.checkNotificationChannelSound(NotificationChannelType.NEW_ORDER) &&
+        if (notificationChannelsHandler.checkNewOrderNotificationSound() == NewOrderNotificationSoundStatus.DISABLED &&
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:771]: Minor but with this logic, it will behave differently from Notification > Settings. Because here, we are not showing the explanatory dialog when the Notification sound has been changed only when its disabled, so user won't be able to restore the ChaChing sound from here.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Excellent job @hichamboushaba. I left some minor comments that it would be nice to address. However, I think its worth merging this asap, so it makes it in time for the freeze today. 
Let me know your thoughts so we can give green light to @samiuelson to start the freeze as soon as this is merged, or if he can proceed without merging this. PR.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt (hunk 5 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:771]: Yes, that was on purpose as I explained in the PR description, the disabling of the sound can happen accidentally (p1701347291432849/1701328346.130389-slack-C03L1NF1EA3) so we use this kind of "intrusive" dialog to let the user know about it, but the sound change shouldn't be (the tracks will help us confirm this), so we just add the Settings entry to allow the user to restore it without any disturb to their flow, WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt]: Oh, really, weird, I'll relax the condition a bit, and you can test it later.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt]: Can you test with the last commit 6357d2f4fd982d4ba6e62b2ec398bde360e700d6?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt (hunk 5 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:771]: True! I missed that. I got confused by following the last part of the testing instructions and missed that part of the descriptions. The current behavior makes sense. Sorry for the noise.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt (hunk 4 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:786]: The action snackbars all over the app [use](https://github.com/woocommerce/woocommerce-android/blob/df35ff5da8bb66c83130db084b7427acf5bfd158/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/base/UIMessageResolver.kt#L318) the default long duration, if you are OK with this, let's keep it as is, and if needed we can start a discussion internally about the duration for all of them, because the `Undo` snackbars are more important than this, and if the duration is short, then we need to increase it for them too.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt (hunk 3 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationChannelsHandler.kt]: Re tested! Works as expected now! Thanks for the quick fix 🙇🏼

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt (hunk 4 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:786]: Yes, that's true. Had not noticed that the SnackBar `event` doesn't accept setting the duration. I think the duration also should depend on the length of the message. We need to provide enough time for the user to read, and then think if they want to click on the CTA. 
For `UNDO` actions the current time might be enough, as there's clear context on what is going on. 
In any case this is a really minor thing and the refactor is bigger than I though, since we cannot pass a custom duration to the `SnackBar` event. So, its fine to leave it as it is.
