### PR TITLE
[Shipping labels] Handle purchasing errors

### LINKED ISSUE #13670: Purchasing a shipping label fails
When purchasing a shipping label in the purchase shipping label flow, we should display an error if the request fails.

Image

### PR DESCRIPTION
**Pull request by irfano**
Closes: #13670 

### Description

This PR addresses the error handling for the purchasing label. If the purchase label endpoint returns an error, a snackbar with a retry button will be displayed.

#### To create fake null response from /wcshipping/v1/label/purchase/
1. Go to Menu → Settings → Developer Options → API Faker
2. Tap + button.
3. Enter these settings:
```
Path: /wcshipping/v1/label/purchase/%
Status Code: 500
```

#### To reproduce error snackbar
1. Open the app
2. Navigate to the Orders section
3. Open an order eligible for shipping label creation
4. Tap on create shipping label
5. Tap on select a package
6. Select any package
7. Tap on a shipping rate
9. Tap on the purchase label

### Images/gif

[after.webm](https://github.com/user-attachments/assets/76d4cb63-3380-4c20-9c17-a98294ed1d57)

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt [hunk 1]
```diff
@@ -115,6 +115,12 @@ open class MultiLiveEvent<T : Event> : MutableLiveData<T>() {
         }
 
         data class ShowActionSnackbar(
+            @StringRes val message: Int,
+            @StringRes val actionText: Int,
+            val action: View.OnClickListener
+        ) : Event()
+
+        data class ShowActionStringSnackbar(
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/MultiLiveEvent.kt:123]: I renamed the existing `ShowActionSnackbar` to `ShowActionStringSnackbar` to introduce a new `ShowActionSnackbar` that uses StringRes parameters instead of `String`s.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt [hunk 2]
```diff
@@ -51,7 +51,7 @@ class CustomFieldsFragment : BaseFragment() {
                 is CustomFieldsViewModel.OpenCustomFieldEditor -> openEditor(event.field)
                 is CustomFieldsViewModel.CustomFieldValueClicked -> handleValueClick(event.field)
                 is MultiLiveEvent.Event.ShowSnackbar -> showSnackbar(getString(event.message))
-                is MultiLiveEvent.Event.ShowActionSnackbar -> showSnackbar(
+                is MultiLiveEvent.Event.ShowActionStringSnackbar -> showSnackbar(
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt:54]: np: Considering that the UI is in jetpack compose (jc), displaying the snack bar on the jc screen could help with maintainability and a consistent state (for instance preventing the retry snackbar to be displayed while the screen is loading)

**Review by atorresveiga — APPROVED** [review]
Great work @irfano, I just left a minor np that is not a blocker

LGTM!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt (hunk 2 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/customfields/list/CustomFieldsFragment.kt:54]: Good advice! I replaced the snackbar but didn’t revert my changes to ShowActionSnackbar since it might still be necessary for future use.
I adjusted the snackbar’s bottom padding based on the bottom sheet peek. You can see the screenshots below. The behavior remains the same.
