### PR TITLE
Beta Fix: Fix broken "reset password" link on site creds login screen

### LINKED ISSUE #3349: Login: Password reset link can't open on store credentials screen
**Describe the bug**

In the store address login flow, on the screen to enter your store credentials, the "Reset your password" link should open my site's password reset page. Instead, however, I get an error:

> Unable to open the link

The app logs show this error:

```
[Dec-18 13:08 UTILS e] No default app available on the device to open the link: rachelmcrtest.mystagingwebsite.com/wp-login.php?action=lostpassword - exception: No Activity found to handle Intent { act=android.intent.action.VIEW dat=rachelmcrtest.mystagingwebsite.com/wp-login.php?action=lostpassword (has extras) }
[Dec-18 13:08 UTILS e] StackTrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=rachelmcrtest.mystagingwebsite.com/wp-login.php?action=lostpassword (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2031)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1686)
	at android.app.Activity.startActivityForResult(Activity.java:4506)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4464)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4829)
	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
	at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:331)
	at com.woocommerce.android.util.ChromeCustomTabUtils.launchUrl(ChromeCustomTabUtils.kt:93)
	at com.woocommerce.android.ui.login.LoginActivity.forgotPassword(LoginActivity.kt:328)
	at org.wordpress.android.login.LoginUsernamePasswordFragment$2.onClick(LoginUsernamePasswordFragment.java:167)
	at android.view.View.performClick(View.java:6297)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
	at android.view.View$PerformClick.run(View.java:24797)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

I confirmed that the password reset link **does** work as expected on the WordPress.com email/password screen, so this is specific to the site credentials username/password screen. @AmandaRiu I think this was a side effect of stripping the site address protocol in https://github.com/woocommerce/woocommerce-android/pull/3236.

**To Reproduce**
1. Start logged out of the app.
2. Select "Enter your store address."
3. Enter your WooCommerce store address and select "Continue."
4. Select "Continue with store credentials."
5. Tap "Reset your password" (below the credential fields).
6. Notice a toast message with the error.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.7-rc-1

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #3349 The issue was stripping the protocol from the URL for the label but then using that same URL for routing to the reset password view. Logic has been updated to strip the protocol for display only when needed for display.

### To Test
1. Freshly install the app
2. Tap **Enter your store address**
3. Enter a store address and tap **Continue**
4. On the login email screen, verify the store address doesn't contain any protocol information like "http://" or "https://"). 
5. Tap **Continue with store credentials**
6. Tap **Reset your password** - verify a webview opens to the reset password page. 

cc: @AliSoftware for a beta release

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java [hunk 1]
```diff
@@ -201,8 +201,9 @@ protected void setupLabel(@NonNull TextView label) {
                 break;
             case WOO_LOGIN_MODE:
                 if (mOptionalSiteCredsLayout) {
+                    String siteAddressClean = mLoginSiteUrl.replaceFirst("^(http[s]?://)", "");
```
Comment (nbradbury) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java:204]: NP: Changes look good and I'll merge this, but wanted to mention that it would be good to move this logic to `StringUtils` since there's more than one place we remove the protocol for display.

**Review by nbradbury — APPROVED** [review]
:shipit:
