### PR TITLE
Extract JITM analytics into a separate class

### LINKED ISSUE #7668: Extract all the JITM analytics logic from Store view model into a separate class
**Describe the bug**
`MyStoreViewModel` class has lots of tracking codes related to the JITM. It will be maintainable to extract all the JITM tracking codes into a separate class.

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #7668 

### Description

This PR extracts all the analytics related JITM into a separate class `JitmTracker`.

The reason behind this refactoring is not to clutter `MyStoreViewModel` with too much JITM-related analytics logic.

### Testing instructions

Ensure CI is happy

Smoke test JITM and ensure tracks are being logged as expected.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+class JitmTracker @Inject constructor(
+    private val analyticsTrackerWrapper: AnalyticsTrackerWrapper
+) {
+    private fun track(
+        stat: AnalyticsEvent,
+        properties: Map<String, Any> = mapOf(),
+        errorType: String? = null,
+        errorDescription: String? = null,
+    ) {
+        val isError = !errorType.isNullOrBlank() || !errorDescription.isNullOrEmpty()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt:22]: Just looking into the API:

```
    fun trackJitmDismissFailure(
        source: String,
        jitmId: String,
        featureClass: String,
        errorType: WooErrorType?,
        errorDescription: String?
    )
```

So both `errorType` and `errorDescription` can be null? In this case we won't track this a an error even if `trackJitmDismissFailure` is the method that suppose to track errors?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+        if (isError) {
+            analyticsTrackerWrapper.track(
+                stat,
+                properties,
+                this@JitmTracker.javaClass.simpleName,
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt:27]: Before this PR "errorContext" was not tracked, right? 

> errorContext A string providing additional context (if any) about the error.

I know that it's done in `CardReaderTracker` but does putting there `JitmTracker` adds any additional context? Maybe put there part of a stack traces,e.g. a couple of stack frames?

**Review by kidinov — APPROVED** [review]
I tested it and looks like it works fine
```
Tracked: jitm_fetch_success, Properties: {"source":"my_store","jitm":"woomobile_ipp_barcode_users","count":1,"blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_displayed, Properties: {"source":"my_store","jitm_id":"woomobile_ipp_barcode_users","feature_class":"woomobile_ipp","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_fetch_failure, Properties: {"source":"my_store","error_context":"JitmTracker","error_description":"","error_type":"GENERIC_ERROR","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_cta_tapped, Properties: {"source":"my_store","jitm_id":"woomobile_ipp_barcode_users","feature_class":"woomobile_ipp","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_dismiss_failure, Properties: {"feature_class":"woomobile_ipp","source":"my_store","jitm_id":"woomobile_ipp_barcode_users","error_context":"JitmTracker","error_description":"","error_type":"GENERIC_ERROR","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_dismiss_success, Properties: {"source":"my_store","jitm_id":"woomobile_ipp_barcode_users","feature_class":"woomobile_ipp","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
Tracked: jitm_dismiss_tapped, Properties: {"source":"my_store","jitm_id":"woomobile_ipp_barcode_users","feature_class":"woomobile_ipp","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
```

Just left a couple of questions to think about

**Review by samiuelson — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jitm/JitmTracker.kt:22]: >So both errorType and errorDescription can be null?

Yeah. `errorDescription` can be empty or null (Your comment with logs has errorDescription as an empty string). I'm not so sure about errorType.  

I've added a default errorType of GENERIC for JITM dismiss failure [here](https://github.com/woocommerce/woocommerce-android/pull/7716/commits/eb5bf7814545f22b4debf7e5230d1ae67efc1da6)
