### PR TITLE
Betafix: Add back the orderRefreshLayout PTR handling.

### LINKED ISSUE #3335: Pull-to-refresh Takes A Long Time To Finish
I'm on version 5.7-rc-1 from Google Play (Beta?). I can confirm that this does not happen on 5.5 and 5.6.

## Steps to Reproduce

1. Pull to refresh on All Orders tab.

It takes forever on Android but about 4 seconds on iOS. 

However, if I do this, it finishes quickly:

1. Pull to refresh
2. Rotate to landscape.
3. Rotate back to portrait.

The loader animation disappears after 1 second. 

---

FYI @woocommerce/android-developers

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #3335. Adds back the `scrollUpChild` and `setOnRefreshListener` logic for the `orderRefreshLayout`. This logic was accidentally removed in this PR. **This PR merges into the current beta 5.7.**

cc: @AliSoftware -- will require a new beta cut

### To Test
- Scroll down the orders list a few pages and then scroll back to the top. Verify successful. 
- Open Flipper. Initiate a PTR on the orders list. Verify request is sent over the network. Verify the "refreshing" animation disappears when complete. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 1]
```diff
@@ -161,6 +161,14 @@ class OrderListFragment : TopLevelFragment(R.layout.fragment_order_list),
         _binding = FragmentOrderListBinding.bind(view)
         binding.orderListView.init(currencyFormatter = currencyFormatter, orderListListener = this)
         binding.orderStatusListView.init(listener = this)
+        binding.orderRefreshLayout?.apply {
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: Minor nit: The `?` isn't needed here.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: Fixed in 5f52760e9af54cad4d5b804a5741c172b82cfa5e

**Comment by AmandaRiu** [comment]
@nbradbury ready for another round! 👍

**Review by nbradbury — APPROVED** [review]
:shipit:
