### PR TITLE
Fix ANR about Zendesk SDK initialization

### LINKED ISSUE #12040: ApplicationNotResponding: Background ANR
Sentry Issue: [WOOCOMMERCE-ANDROID-9YE](https://a8c.sentry.io/issues/5139777870/?referrer=github_integration)

```
ApplicationNotResponding: Background ANR
    at com.woocommerce.android.support.zendesk.ZendeskSettings.setup(ZendeskSettings.kt:0)
    at com.woocommerce.android.support.zendesk.ZendeskSettings.setup(ZendeskSettings.kt:99)
    at com.woocommerce.android.support.zendesk.ZendeskSettings.setup$default(ZendeskSettings.kt:79)
    at com.woocommerce.android.AppInitializer.init(AppInitializer.kt:214)
    at com.woocommerce.android.WooCommerce.onCreate(WooCommerce.kt:46)
...
(53 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12040

### Description
This PR is an attempt to fix the ANR related to the Zendesk SDK initialization, the fix is to simply move the initialization to be run when creating the help activities, the SDK is not used anywhere else, and we don't need to initialize it when  creating the app, which can happen when the app is launched in the background, and where the changes of the ANR are higher. For more information on this ANR, please check p91TBi-bG1-p2.

While working on this, and trying to confirm if the SDK is being used outside of the help activities, I found out that we have some code leftovers to delete, in the past, we [removed](https://github.com/woocommerce/woocommerce-android/pull/8521) support for Zendesk push notification, so I deleted some unused code related to the same functionality in the commit 6fc8ae0

### Testing information
Smoke test the support ticket creation and confirm it works as expected.

@ThomazFB please suggest any other testing steps from your past experience on this area in the app.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskSettings.kt [hunk 1]
```diff
@@ -76,21 +75,18 @@ class ZendeskSettings @Inject constructor(
      * setup. It'll also enable Zendesk logs for DEBUG builds.
      */
     @JvmOverloads
+    @Synchronized
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/support/zendesk/ZendeskSettings.kt:78]: I made this a synchronized call just to avoid issues with the parameter `setupDone` if it gets called from multiple threads, even though this is not needed now, as the function is called only from the main thread.

**Review by ThomazFB — APPROVED** [review]
Thanks for this fix, @hichamboushaba! I can confirm the Zendesk is operating as expected, even when the user is logged out.

https://github.com/user-attachments/assets/6d53ca22-a631-4402-991c-725a31ecb842

Screenshot 2024-07-30 at 10 16 56

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/228">19.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
