### PR TITLE
[Woo POS] Crash when multiple connection flows are started and cancelled

### LINKED ISSUE #12028: [Woo POS] Crash when multiple connection flows are started and cancelled
**Describe the bug**
When I click on the 'Collect payment' button multiple times, the app starts multiple card reader connection flows => when I attempt to cancel them, the app sometimes crash.

**To Reproduce**
1. Go to More Menu -> POS
2. Add a product
3. Tap on 'Checkout'
5. Tap on 'Collect Payment' multiple times within a short timespan
6. Tap on cancel -> notice the app sometimes crashes.

**Expected behavior**
Multiple clicks on the collect payment button should still start only a single connection flow.

Logs
<details>
Process: com.woocommerce.android.prealpha, PID: 24752
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=75952946, result=0, data=null} to activity {com.woocommerce.android.prealpha/com.woocommerce.android.ui.woopos.root.WooPosActivity}: java.lang.IllegalStateException: Already resumed, but proposed with update Failure
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5362)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: Already resumed, but proposed with update Failure
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:559)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:524)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderFacade.onCreate$lambda$0(WooPosCardReaderFacade.kt:41)
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderFacade.$r8$lambda$PgLUY3675ous7MehkdBsT19nqtg(Unknown Source:0)
                                                                                                    	at com.woocommerce.android.ui.woopos.cardreader.WooPosCardReaderFacade$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8628)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5316)
</details>

### PR DESCRIPTION
**Pull request by backwardstruck**
**Closes:** #12028

### Description

This PR addresses the issue where clicking the 'Collect Payment' button multiple times quickly initiates multiple card reader connection flows. This can cause the app to crash when attempting to cancel these connections. This update ensures that multiple clicks on the 'Collect Payment' button will still start only a single connection flow, thus preventing such crashes.

### Steps to Reproduce

1. Go to More Menu -> POS.
2. Add a product.
3. Tap on 'Checkout'.
4. Tap on 'Collect Payment' multiple times quickly.
5. Tap on cancel.
6. Notice that the app sometimes crashes.

**Expected Behavior:**
- Multiple clicks on the 'Collect Payment' button should start only a single connection flow.

### Testing Information

- **Device Testing:** Test on various devices to ensure consistent behavior.

### Release Notes
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/228">19.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt [hunk 1]
```diff
@@ -153,4 +162,12 @@ class WooPosTotalsViewModel @Inject constructor(
         val orderId: Long = EMPTY_ORDER_ID,
         val productIds: List<Long> = emptyList()
     ) : Parcelable
+
+    private fun debounce(destinationFunction: () -> Unit) {
+        debounceJob?.cancel()
+        debounceJob = viewModelScope.launch {
+            delay(DEBOUNCE_TIME_MS)
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt]: ⚠️ This will block collect payment dialog from starting for 3 seconds. In other words, merchants will not see anything for 3 seconds when they click on collect payment button. This will make it look like the button isn't working.

How about we check for the debounceJob's status instead? 
```
private const val DEBOUNCE_TIME_MS = 800L


private fun debounce(destinationFunction: () -> Unit) {
        if (debounceJob?.isActive == true) {
            return
        }
        debounceJob = viewModelScope.launch {
            destinationFunction()
            delay(DEBOUNCE_TIME_MS)
        }
    }
```

We could then write tests like this

```
@Test
    fun `given vm created, when collect payment clicked multiple times within delay, then debounce prevents it`() =
        runTest {
            // GIVEN
            val productIds = listOf(1L, 2L, 3L)
            val parentToChildrenEventFlow = MutableStateFlow(ParentToChildrenEvent.CheckoutClicked(productIds))
            val parentToChildrenEventReceiver: WooPosParentToChildrenEventReceiver = mock {
                on { events }.thenReturn(parentToChildrenEventFlow)
            }
            val order = Order.getEmptyOrder(
                dateCreated = Date(),
                dateModified = Date()
            ).copy(
                totalTax = BigDecimal("2.00"),
                items = listOf(
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    ),
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    ),
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    )
                )
            )
            val totalsRepository: WooPosTotalsRepository = mock {
                onBlocking { createOrderWithProducts(productIds = productIds) }.thenReturn(
                    Result.success(order)
                )
            }
            val priceFormat: WooPosFormatPrice = mock {
                onBlocking { invoke(BigDecimal("2.00")) }.thenReturn("2.00$")
                onBlocking { invoke(BigDecimal("3.00")) }.thenReturn("3.00$")
                onBlocking { invoke(BigDecimal("5.00")) }.thenReturn("5.00$")
            }
            whenever(cardReaderFacade.collectPayment(any())).thenReturn(
                WooPosCardReaderPaymentResult.Success
            )

            // WHEN
            val viewModel = createViewModel(
                parentToChildrenEventReceiver = parentToChildrenEventReceiver,
                totalsRepository = totalsRepository,
                priceFormat = priceFormat,
            )
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)

            // THEN
            // Advance time by less than the debounce delay
            advanceTimeBy(800 / 2)
            verify(cardReaderFacade, times(1)).collectPayment(any())
            advanceUntilIdle()
            verify(cardReaderFacade, times(1)).collectPayment(any())

        }

    @Test
    fun `given vm created, when collect payment clicked multiple times after delay, then click event is handled for all of it`() =
        runTest {
            // GIVEN
            val productIds = listOf(1L, 2L, 3L)
            val parentToChildrenEventFlow = MutableStateFlow(ParentToChildrenEvent.CheckoutClicked(productIds))
            val parentToChildrenEventReceiver: WooPosParentToChildrenEventReceiver = mock {
                on { events }.thenReturn(parentToChildrenEventFlow)
            }
            val order = Order.getEmptyOrder(
                dateCreated = Date(),
                dateModified = Date()
            ).copy(
                totalTax = BigDecimal("2.00"),
                items = listOf(
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    ),
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    ),
                    Order.Item.EMPTY.copy(
                        subtotal = BigDecimal("1.00"),
                    )
                )
            )
            val totalsRepository: WooPosTotalsRepository = mock {
                onBlocking { createOrderWithProducts(productIds = productIds) }.thenReturn(
                    Result.success(order)
                )
            }
            val priceFormat: WooPosFormatPrice = mock {
                onBlocking { invoke(BigDecimal("2.00")) }.thenReturn("2.00$")
                onBlocking { invoke(BigDecimal("3.00")) }.thenReturn("3.00$")
                onBlocking { invoke(BigDecimal("5.00")) }.thenReturn("5.00$")
            }
            whenever(cardReaderFacade.collectPayment(any())).thenReturn(
                WooPosCardReaderPaymentResult.Failure
            )

            // WHEN
            val viewModel = createViewModel(
                parentToChildrenEventReceiver = parentToChildrenEventReceiver,
                totalsRepository = totalsRepository,
                priceFormat = priceFormat,
            )
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            advanceUntilIdle()
            verify(cardReaderFacade, times(1)).collectPayment(any())
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            advanceUntilIdle()
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            advanceUntilIdle()
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            advanceUntilIdle()
            viewModel.onUIEvent(WooPosTotalsUIEvent.CollectPaymentClicked)
            advanceUntilIdle()
            verify(cardReaderFacade, times(5)).collectPayment(any())
        }

```

Here's the patch file: 
[debounce.patch](https://github.com/user-attachments/files/16451768/debounce.patch)

Let me know what you think.

**Review by AnirudhBhat — COMMENTED** [review]
Thanks for working on this @backwardstruck. I've left one comment. Please take a look and let me know what you think. Thanks!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt (hunk 1 above)
Comment (backwardstruck) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt]: Thanks @AnirudhBhat I had missed that I was adding the delay incorrectly. Your patch is applied.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt [hunk 2]
```diff
@@ -298,11 +304,130 @@ class WooPosTotalsViewModelTest {
         assertThat(state.orderSubtotalText).isEqualTo("$3.00")
     }
 
+    @Test
+    fun `given vm created, when collect payment clicked multiple times within delay, then debounce prevents it`() =
```
Comment (backwardstruck) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModelTest.kt:308]: Thanks for adding this test as well!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt [hunk 3]
```diff
@@ -153,4 +162,14 @@ class WooPosTotalsViewModel @Inject constructor(
         val orderId: Long = EMPTY_ORDER_ID,
         val productIds: List<Long> = emptyList()
     ) : Parcelable
+
+    private fun debounce(destinationFunction: suspend () -> Unit) {
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt:166]: I also updated the debounce function to accept `suspend () -> Unit` for handling suspending operations directly, simplifying coroutine management. This eliminates the need for nested coroutine launches.

**Review by AnirudhBhat — APPROVED** [review]
Thanks for the changes @backwardstruck. LGTM 🚀
