### PR TITLE
Disable Volley debug logging on release builds

### LINKED ISSUE #817: java.lang.IllegalStateException: Marker added to finished log
From the logs, this looks like a case where the user has a very bad network connection (they were experiencing timeouts right before the crash).

I suspect this is Volley's bug, and not ours, but we may need more data – right now only a single user is experiencing it.

From Fabric:

Fatal Exception: java.lang.IllegalStateException: Marker added to finished log
       at com.android.volley.VolleyLog$MarkerLog.add(VolleyLog.java:132)
       at com.android.volley.Request.addMarker(Request.java:219)
       at com.android.volley.ExecutorDelivery.postError(ExecutorDelivery.java:66)
       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:165)
       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Source:** 5c66f956f8b88c2963f5a1fe-fabric

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #817 

This is a crash that is happening when Volley attempts to write to a finished log. We are seeing this crash only for a single user, and so far just 5 times. Some [StackOverflow](https://stackoverflow.com/questions/26350035/volley-bug-repeating-a-request-when-verbose-logging-is-enabled-fails/28110821#28110821) comments are recommending just setting `VolleyLog.DEBUG = false`. Looking at Volley's [VolleyLog](https://android.googlesource.com/platform/frameworks/volley/+/android-5.1.1_r13/src/com/android/volley/VolleyLog.java#127) code, they use `Log.isLoggable("Volley", VERBOSE)` to see if they should be logging. That method should return false since the default logging level for any tag is `INFO` unless a system property is explicitly set. I've run `adb shell getprop | grep log.tag` and nothing is forcing it to be set on my test devices. However, device manufacturers have been known to set their own system properties so I'm guessing this is either something the user is manually forcing by running `adb shell setprop tag.log.Volley VERBOSE`, or the device manufacturer (Proline tablet) has it set. If this is done by the device manufacturer then this PR will override that setting.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt [hunk 1]
```diff
@@ -98,6 +99,11 @@ open class WooCommerce : MultiDexApplication(), HasActivityInjector, HasServiceI
     override fun onCreate() {
         super.onCreate()
 
+        // Disables Volley debug logging on release build and prevents the "Marker added to finished log" crash
+        if (!BuildConfig.DEBUG) {
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt]: Wouldn't `VolleyLog.DEBUG = BuildConfig.DEBUG`  be better here? Also, I think it'd be okay to add a link to the issue URL for future devs.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt]: No, only because we don't necessarily _always_ want volley debugging enabled, even for debug builds. They set it at VERBOSE debugging...that's a lot of feedback. So I specifically disable it for release builds here to avoid crashes, but allow the normal logic to win if in a debug build.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt]: Added issue url in e804084541497098377b4bd1c8db413d6f25f315

**Comment by nbradbury** [comment]
Looks good :shipit:
