### PR TITLE
HACK Week: Add pagination support to attribute terms view

### LINKED ISSUE #9583: [Variable Product] - Existing options for an attribute are not displayed in add options if more than 10 options available
**Describe the bug**
Attributes are not displayed fully in add attribute option screen and only show up to 10 options, i.e. if there are more than 10 options, only the last 10 are displayed. 

This was first reported in 6605997-zen and I was able to reproduce the same issue with the steps below.

**To Reproduce**
1. Log in to a store that has more than 10 options for an attribute type in a variable product (e.g. 25 different colors)
2. Create New Variable Product > Add Variations > Select existing attribute (e.g. Color)
3. Scroll down on the attribute screen to select an existing option
4. See that not all options are displayed for that attribute

**Screenshots**

https://github.com/woocommerce/woocommerce-ios/assets/17252150/7ffebfba-bab3-4085-961d-a70184d547d1

**Expected behavior**
All options should be displayed and selectable from the add options screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 6a
- OS version: Android 12
- WooCommerce version: v14.8-rc-1 (current beta)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by ThomazFB**
⚠️ Depends of https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2848 and https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2850

Why
==========
Fix for issue https://github.com/woocommerce/woocommerce-android/issues/9583. 

The current attributes term fetching doesn't use any pagination strategy and the `per_page` default value is 10. Because of this limitation, some users report problems seeing all terms of an attribute. 

How
==========
This PR solves this problem by allowing pagination when interacting with any Global attributes configuration under the Variable Product feature.

To avoid making this PR way too big, unit tests are being introduced in https://github.com/woocommerce/woocommerce-android/pull/9754

Captures
==========
https://github.com/woocommerce/woocommerce-android/assets/5920403/29ed4d90-f8f2-4e3d-8755-f58890bfce81

How to Test
==========
1. Log in to a store that has more than 10 options for an attribute type in a variable product (e.g. 25 different colors)
2. Create New Variable Product > Add Variations > Select existing attribute (e.g. Color)
3. Scroll down on the attribute screen to select an existing option
4. See that *ALL* options are loaded and displayed for that attribute as you scroll through them

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+class AddAttributeTermsViewModel @Inject constructor(
+    savedState: SavedStateHandle,
+    private val termsListHandler: AttributeTermsListHandler
+) : ScopedViewModel(savedState) {
+    private val termsFlow = savedState.getStateFlow(
+        this,
+        emptyMap<Int, ProductAttributeTerm>()
+    )
+    val termsListState = termsFlow
+        .map { it.map { (_, term) -> term } }
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsViewModel.kt]: np: we can change  it.map { (_, term) -> term } -> it.values.toList()
```suggestion
        .map { it.values.toList() }
```

**Review by atorresveiga — APPROVED** [review]
Great work Thomaz! Everything is working as expected!.
Sorry for the late review 😞

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListHandler.kt [hunk 2]
```diff
@@ -0,0 +1,55 @@
+package com.woocommerce.android.ui.products.variations.attributes
+
+import com.woocommerce.android.model.ProductAttributeTerm
+import com.woocommerce.android.ui.products.ProductDetailRepository
+import kotlinx.coroutines.sync.Mutex
+import kotlinx.coroutines.sync.withLock
+import javax.inject.Inject
+
+class AttributeTermsListHandler @Inject constructor(
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListHandler.kt:9]: Thinking out loud: We can use [Paging 2](https://developer.android.com/topic/libraries/architecture/paging) to accomplish this pagination. In this case, I believe it could have helped you if you considered it a solution from the beginning.
Did you know we already have the Paging 2 dependency as part of FluxC? I learned it in my Hack Week.

**Review by atorresveiga — APPROVED** [review]
Everything is working as expected! Great work Thomas!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsViewModel.kt (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AddAttributeTermsViewModel.kt]: Good one! Thanks! Done in https://github.com/woocommerce/woocommerce-android/pull/9748/commits/d62aff9c8d73632e4a2d813c64359e42eece97ae.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListHandler.kt (hunk 2 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/AttributeTermsListHandler.kt:9]: Oh, I was unaware that FluxC is including the Paging 2 lib. I only attempted to check if Woo was using it 🤦. Well, now that everything is implemented, I'll keep this in mind for future opportunities and use it instead of the manual approach I just used.

Thanks, @atorresveiga!
