### PR TITLE
issue/2074-multi-click-event-crash-fix

### LINKED ISSUE #2074: Crash:  java.lang.IllegalStateException: Multiple observers registered but only one is supported.
When testing the products beta release, I experienced the following crash when clicking on two products from the products list, at the same time.

```
2020-03-17 11:55:52.305 8946-8946/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 8946
    java.lang.IllegalStateException: Multiple observers registered but only one is supported.
        at com.woocommerce.android.viewmodel.LiveDataDelegate.observe(LiveDataDelegate.kt:38)
        at com.woocommerce.android.ui.products.ProductDetailFragment.setupObservers(ProductDetailFragment.kt:100)
        at com.woocommerce.android.ui.products.ProductDetailFragment.initializeViewModel(ProductDetailFragment.kt:95)
        at com.woocommerce.android.ui.products.ProductDetailFragment.onViewCreated(ProductDetailFragment.kt:91)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

#### To reproduce
- Click on the `Products` tab.
- Click on two products at the same time from the list.
- Notice app crashes with the above exception.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2074. The app was crashing when multiple items are clicked simultaneously in the product list screen. This was because when 2 items were clicked, multiple fragments were opened and the `productDetailViewStateData` was being observed twice and there is logic in place to ensure that the `LiveDataDelegate` would only have single observer. More details on that can be found [here](https://github.com/woocommerce/woocommerce-android/blob/d6bad983c3f2844d2a7ee4df072d62e03e13be5c/WooCommerce/src/main/kotlin/com/woocommerce/android/viewmodel/LiveDataDelegate.kt#L22). 

Searching online, I found that this [SO answer](https://stackoverflow.com/a/36184567/9862062), that suggested that setting `setMotionEventSplittingEnabled` in the `RecyclerView` to false ensures that the RecyclerView children do NOT receive the multiple clicks and only processes the first click event.

#### To Test
- Click on the `Products` tab.
- Click on 2 product items from the list at the same time.
- Notice the app crashes.
- Pull changes from this PR and notice that the app no longer crashes. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt [hunk 1]
```diff
@@ -88,6 +88,11 @@ class ProductListFragment : TopLevelFragment(), OnProductClickListener,
                 )
         )
 
+        // Setting this field to false ensures that the RecyclerView children do NOT receive the multiple clicks,
+        // and only processes the first click event. More details on this issue can be found here:
+        // https://github.com/woocommerce/woocommerce-android/issues/2074
+        productsRecycler.isMotionEventSplittingEnabled = false
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt]: **TIL:** `isMotionEventSplittingEnabled`

**Comment by nbradbury** [comment]
@anitaa1990 Adding `isMotionEventSplittingEnabled = false` fixes the crash, but I think we should add it to the order list and review list as well. In those lists, clicking two items at the same time opens two fragments (ie: tap on two orders and two order fragments open).

**Comment by anitaa1990** [comment]
> Adding isMotionEventSplittingEnabled = false fixes the crash, but I think we should add it to the order list and review list as well. In those lists, clicking two items at the same time opens two fragments (ie: tap on two orders and two order fragments open).

Good point! I added it to orders/reviews and realised that we haven't added it to top earners and order product list (which would also lead to the same crash since both redirect to the product detail screen).

Ready for another round 👍
