### PR TITLE
Adjust Variation details recyclerview adapter to be updated through message enqueue

### LINKED ISSUE #6312: IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclervi...
Sentry Issue: [WOOCOMMERCE-ANDROID-3VY](https://sentry.io/organizations/a8c/issues/3201618963/?referrer=github_integration)

```
IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{5fddb04 VFE..V... ......ID 0,0-1080,1500 #7f0a01dc app:id/cardsRecyclerView}, adapter:com.woocommerce.android.ui.products.adapters.ProductPropertyCardsAdapter@ee9a8ed, layout:androidx.recyclerview.widget.LinearLayoutManager@f435322, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@6285822
    at com.woocommerce.android.ui.products.adapters.ProductPropertyCardsAdapter.update(ProductPropertyCardsAdapter.kt:20)
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment.showVariationCards(VariationDetailFragment.kt:304)
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment.setupObservers$lambda-1(VariationDetailFragment.kt:228)
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment.$r8$lambda$bo_WbGMNBFEZcIzsBlm2VOPoEZQ
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment$$InternalSyntheticLambda$0$7e45fd1daedab322ea8d740032454ca427462f2ec36a7f0e5b8121ffd38c6f8c$0.onChanged
...
(162 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Attempt to fix issue #6312 by adding the Adapter update to the message queue to avoid requesting the RecyclerView to be updated when a UI operation is happening inside of it. 

How to Test
==========
Since there's no reliable way to reproduce this crash, this is a shot to see if the [sentry issue](https://sentry.io/organizations/a8c/issues/3201618963/?referrer=github_integration) will report a decrease in the incidents counts.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt [hunk 1]
```diff
@@ -301,7 +301,7 @@ class VariationDetailFragment :
         }
 
         val recyclerViewState = binding.cardsRecyclerView.layoutManager?.onSaveInstanceState()
-        adapter.update(cards)
+        binding.cardsRecyclerView.post { adapter.update(cards) }
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: @ThomazFB I think this change is fine, but while testing I noticed `update(cards)` is being called twice when the fragment is shown. Perhaps that's the source of the problem?

Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: I notice the multiple calls too since the `showVariationCards` is attached to the `variationDetailCards` LiveData events, but since the update call goes through the `ProductPropertiesCardsDiffCallback` with the `DiffUtils` before submitting the changes, in theory, these multiple calls shouldn't affect the RecyclerView unless there's a real data change there wouldn't? Or am I missing something? 🤔

Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: I believe it is worth adding a comment to the code explaining why we are using the post function and maybe a link to the Sentry issue to help future maintainers to have more context and keep an eye on this bug.

> DiffUtils before submitting the changes, in theory, these multiple calls shouldn't affect the RecyclerView unless there's a real data change there wouldn't? Or am I missing something?

I found a similar solution on [StackOverflow](https://stackoverflow.com/questions/43221847/cannot-call-this-method-while-recyclerview-is-computing-a-layout-or-scrolling-wh), and one of the comments cached my attention.

> This seems to be a bug in the RecyclerView library when notifyDataSetChanged() is called either in quick succession (within 50 ms) or whilst scrolling -- even if it's called outside of onBindViewHolder(). For example, it happens when refreshing the whole list with notifyDataSetChanged(), not necessarily adding or removing items. The Runnable suggestion works well.

I note from @nbradbury comment that `update(cards)` is being called twice, so based on the comment above `...in quick succession within 50 ms`, I'm wondering if this could be the source of the problem too. I know that, in theory, `DiffUtils` should help update only the items that changed in the list, but I wonder if it calls a notify...X function that is throwing the exception even without changes.

Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: Thanks, @atorresveiga, for your input on this issue. Following the suggestions from you both, I decided to investigate what could be causing the multiple hits in the `update` method through the LiveData changes, and I've found that the main source of quick hits in the adapter is this part of the `VariationDetailViewModel` right here:
Screen Shot 2022-05-04 at 19 12 20

These two operations highlighted in red cause a double hit of the `updateCards` method, that will update the `_variationDetailCards` LiveData:

Screen Shot 2022-05-04 at 21 02 21

My solution to fix this double hit during the `loadVariation` call is to only allow the `variationViewStateData` onChange  lambda trigger the `updateCards` if the new set variation is different from the `originalVariation`, because if they're the same data, we can safely assume that the `updateCards` was already updated through the `originalVariation` set call.

Here's the proposed solution: https://github.com/woocommerce/woocommerce-android/pull/6429/commits/2237e4145a2f62bd59482108773258a3232636cb

Let me know what you folks think about it.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: Sorry for jumping in, but if we believe the source of the issue is this, I think an easy way to fix without complicating the ViewModel's logic would be to simply add a `distinctUntilChanged()` to the `LiveData` before observing it, I mean something like:
```kotlin
        viewModel.variationDetailCards.distinctUntilChanged().observe(viewLifecycleOwner) {
            showVariationCards(it)
        }
```

Just a suggestion, I don't know all the details 🙂.

Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: @ThomazFB I think your solution is fine, but I also like @hichamboushaba's suggestion of using `distinctUntilChanged`. Either way, I'll "pre-approve" this PR so you can merge it.

**Review by nbradbury — APPROVED** [review]
:shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt]: I also prefer @hichamboushaba solution. I considered using it but decided to investigate what was causing the double update in the end. The PR is now updated with the `distinctUntilChanged` approach. Thanks, everyone!
