### PR TITLE
IPP feedback survey bug fix

### LINKED ISSUE #8445: Fix IPP survey logic
## Description

We discovered various issues in the logic in deciding if, and which, In Person Payments feedback survey banner to show the user. Full context: pdfdoF-2pO-p2

To fix these issues and show the correct banners, we've decided to remove the usage of the `/payments/transactions/summary`  and instead make use of `receipt_url` and `paymentMethodID` to detect IPP transactions.

1. Remove the COD requirement for surveys 2 and 3.
2. Use Orders filtered to IPP-only for surveys 2 and 3 (instead of all WCPay Orders.)
3. Replace the filter which uses a server-localized string, paymentMethodTitle to use paymentMethodID instead, to avoid potential clashes with other plugins. (N.B. paymentMethodID is the same for IPP and web, so this isn’t sufficient to identify IPP transactions alone, but we use it in combination with the presence of receiptUrl, which is only set for IPP transactions within WCPay)

### PR DESCRIPTION
**Pull request by AnirudhBhat**
### Please make sure to review and merge the corresponding [fluxc PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2669) before merging this PR. Also, please update the fluxc hash and remove the "do not merge" label from this PR after merging the fluxc PR.

Closes: #8445 

### Description

This PR fixes the bug in the IPP feedback survey banner display logic.

**Before this PR**
1. We relied on `/payments/transactions/summary` for determining the IPP transaction. This is incorrect since the `/payments/transactions/summary` returns all WCPay transactions and not just the IPP transactions.
2. We made the "Cash On Delivery" setting mandatory for the banner to be shown. This is not required for `Beginner` and `Ninja` survey users. The COD setting is required just for the `Newbie` survey user.

**After this PR**
1. We are relying on the locally cached Orders database for identifying the IPP orders, we do this by ensuring the presence of the  "receipt_url" metadata for an order. Along with this, we also ensure the `PaymentMethod` is set to `woocommerce-payments`
2. Remove the requirement of COD setting for `Beginner` and `Ninja` survey users. 

Refer to this post for more context: pdfdoF-2pO-p2

### Testing instructions

**Using a US or CA based store**
No WCPay IPP orders (web orders are fine)
With COD enabled
Shows banner with the text "Share your own experience or how you collect in-person payments."

**Unit Test**
Screenshot 2023-03-06 at 2 43 40 PM

============================================================================================

Same store with COD turned off (you can toggle it in the Payments menu of the app)
Doesn't show a banner

**Unit Test**
Screenshot 2023-03-06 at 2 43 50 PM

============================================================================================

Using a US or CA based store with 1-9 WCPay IPP payments in the last 30 days
With COD enabled or disabled
Shows banner with text "Rate your first in-person payment experience."

**Unit Test**
Screenshot 2023-03-06 at 2 43 58 PM

============================================================================================

Using a US or CA based store with 10 or more WCPay IPP payments
With COD enabled or disabled
Shows banner with text "Tell us all about your experience with in-person payments."

**Unit Test**
Screenshot 2023-03-06 at 2 44 05 PM

============================================================================================

Using a US or CA based store with 1-9 WCPay IPP payments, all more than 30 days old
With COD enabled or disabled
Doesn't show a banner

**Unit Test**
Screenshot 2023-03-06 at 2 44 20 PM

============================================================================================

Using another country based store
Using one of the above banner-displaying stores, temporarily switched to a non-US in wc-admin
Doesn't show a banner

**Unit Test**
Screenshot 2023-03-06 at 2 47 19 PM

============================================================================================

**Update the app on top of the existing app**
Simply install this build on top of any old WooCommerce Android build. The app shouldn't crash, and the IPP feedback survey banner display logic should be working as expected.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt [hunk 1]
```diff
@@ -39,58 +43,52 @@ class GetIPPFeedbackBannerData @Inject constructor(
...
+        return when {
+            !hasWCPayIPPOrders && cashOnDeliverySettings.isCashOnDeliveryEnabled() -> {
                 IPP_NEWBIE_BANNER
             }
-            in IPP_BEGINNER_TRANSACTIONS_RANGE -> IPP_BEGINNER_BANNER
-            else -> IPP_NINJA_BANNER
+            hasIPPOrdersInLast30Days && ippOrdersInLast30Days in IPP_BEGINNER_TRANSACTIONS_RANGE -> {
+                IPP_BEGINNER_BANNER
+            }
+            wcPayIPPOrdersCount >= IPP_NINJA_TRANSACTIONS_THRESHOLD -> {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt]:
```suggestion
            wcPayIPPOrdersCount > IPP_BEGINNER_TRANSACTIONS_RANGE.last -> {
```
🔍 `IPP_NINJA_TRANSACTIONS_THRESHOLD` seems to be not necessary - we can refer to `IPP_BEGINNER_TRANSACTIONS_RANGE.last`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt [hunk 2]
```diff
@@ -39,58 +43,52 @@ class GetIPPFeedbackBannerData @Inject constructor(
...
+        it: OrderEntity,
+        timeWindowStartDate: Date?
+    ) = SimpleDateFormat(
+        "yyyy-MM-dd",
+        Locale.getDefault()
+    ).parse(it.datePaid)?.after(timeWindowStartDate) == true
 
-        return numberOfTransactions > 0
-    }
+    private fun isIPPOrders(it: OrderEntity) = it.getMetaDataList().any { wcMetaData ->
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:89]:
```suggestion
    private fun isIPPOrder(order: OrderEntity) = it.getMetaDataList().any { wcMetaData ->
```
🔍 If I understand correctly, this is just a typo. Could be also changed to extension (fun or prop):
```kotlin
private val OrderEntity.isIPP: Boolean
    get() = getMetaDataList().any { wcMetaData ->
        wcMetaData.key == "receipt_url"
    } && paymentMethod == WOOCOMMERCE_PAYMENTS_PAYMENT_TYPE
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt [hunk 3]
```diff
@@ -145,6 +143,7 @@ class GetIPPFeedbackBannerData @Inject constructor(
         private const val BANNER_MESSAGE_BEGINNER = R.string.feedback_banner_ipp_message_beginner
         private const val BANNER_MESSAGE_NINJA = R.string.feedback_banner_ipp_message_ninja
 
-        private val IPP_BEGINNER_TRANSACTIONS_RANGE = 1..10
+        private val IPP_BEGINNER_TRANSACTIONS_RANGE = 1..9
+        private const val IPP_NINJA_TRANSACTIONS_THRESHOLD = 10
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt]: 🔍 As mentioned before, it could be removed.

**Review by samiuelson — APPROVED** [review]
Thank you for fixing the IPP survey user group detection @AnirudhBhat ! The code looks good and works as expected. I left a couple of minor ideas for your consideration, non of them is blocking the merge 🟢

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt]: Added here: https://github.com/woocommerce/woocommerce-android/pull/8482/commits/b610dc23add12acd801ef2727185d28d326691eb

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt (hunk 3 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt]: https://github.com/woocommerce/woocommerce-android/pull/8482/commits/b610dc23add12acd801ef2727185d28d326691eb

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt (hunk 2 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:89]: Definitely a good suggestion. Thank you. I'll create a separate PR for this. I need to modify the fluxc code as well for this change.

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:89]: Let me clarify this a bit more @AnirudhBhat. I mean that the function name could be `isIPPOrder` instead of `isIPPOrders`. 

As for the idea to make it an extension instead, I don't think any changes are required in FluxC. We could simply declare the above private extension property in the `GetIPPFeedbackBannerData` class. This way `OrderEntity.isIPP` would be accessible only in the scope of `GetIPPFeedbackBannerData` class.
