### PR TITLE
[Stats] Fix issue with date formatting of selected dates

### LINKED ISSUE #11643: ParseException: Unparseable date: "2024-06-03"
Sentry Issue: [WOOCOMMERCE-ANDROID-AVD](https://a8c.sentry.io/issues/5340602872/?referrer=github_integration)

```
ParseException: Unparseable date: "2024-06-03"
    at com.woocommerce.android.util.DateUtils.getFriendlyDayHourString(DateUtils.kt:279)
    val date = originalFormat.parse(iso8601Date)
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsRangeFormatter.formatSelectedDate(DashboardStatsRangeFormatter.kt:33)
    SelectionType.TODAY -> dateUtils.getFriendlyDayHourString(dateString).orEmpty()
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsViewModel$dateRangeState$1.invokeSuspend(DashboardStatsViewModel.kt:88)
    selectedDateFormatted = selectedDate?.let { dateRangeFormatter.formatSelectedDate(it, selectedRange) }
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsViewModel$dateRangeState$1.invoke(DashboardStatsViewModel.kt:0)
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsViewModel$dateRangeState$1.invoke(DashboardStatsViewModel.kt:0)
...
(102 additional frame(s) were not displayed)

Date string argument is not of format yyyy-MM-dd HH: 2024-06-03
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #11643 

### Description
This PR fixes the linked issue, the cause of the date formatting failure is the following:
1. When the user selects a given date in the chart, the value is updated in the ViewModel.
2. Then when the user switches to a different tab, the selected date is cleared by the `View` itself.
3. (2) happens after the fact, and given the `combine` operator, we will try to format the selected date from the previous tab.

This PR updates the logic by making sure the selected date is cleared before, it's cleared whenever the selected range changes.

### Steps to reproduce
In `trunk`, these steps:
1. Use the Performance card in the dynamic dashboard.
2. Switch to a tab with some data.
3. Select an individual date.
4. Monitor `logcat`.
5. Switch to a different tab.
6. This will be logged:
`Date string argument is not of format...`
`Tracked: stats_unexpected_format...`

### Testing information
1. Switch to this branch.
2. Repeat 1-5 from above
3. Confirm no warning is logged in Logcat.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt [hunk 1]
```diff
@@ -52,10 +56,11 @@ class DashboardStatsViewModelTest : BaseUnitTest() {
...
     private val wooCommerceStore: WooCommerceStore = mock()
     private val selectedSite: SelectedSite = mock()
-    private val prefsChangesFlow = MutableSharedFlow<Unit>(extraBufferCapacity = 1)
     private val appPrefsWrapper: AppPrefsWrapper = mock {
-        on { observePrefs() } doReturn prefsChangesFlow
-        on { getActiveStoreStatsTab() } doReturn DEFAULT_SELECTION_TYPE.name
+        val prefsChangesFlow = MutableStateFlow(DEFAULT_SELECTION_TYPE.name)
+        on { observePrefs() } doAnswer { prefsChangesFlow.map { Unit } }
+        on { getActiveStoreStatsTab() } doAnswer { prefsChangesFlow.value }
+        on { setActiveStatsTab(any()) } doAnswer { prefsChangesFlow.value = it.getArgument(0) }
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt:63]: This change makes the `appPrefsWrapper` more of a fake than a mock, and it replicates better what the real implementation does, and allows us to remove the calls to `prefsChangesFlow.tryEmit` below.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt [hunk 2]
```diff
@@ -71,6 +76,10 @@ class DashboardStatsViewModelTest : BaseUnitTest() {
     private val parentViewModel: DashboardViewModel = mock {
         on { refreshTrigger } doReturn emptyFlow()
     }
+    private val dateRangeFormatter: DashboardDateRangeFormatter = mock {
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModelTest.kt:79]: I had to mock this, as we use internally `SimpleDateFormat` and it's not available on JVM's unit tests.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Great job, @hichamboushaba; thank you for quickly fixing this!! 🚢
