### PR TITLE
Issue/4114 selected site crashes

### LINKED ISSUE #4114: IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId 1.
Sentry Issue: [WOOCOMMERCE-ANDROID-1PN](https://sentry.io/organizations/a8c/issues/2430183642/?referrer=github_integration)

```
IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId 1.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
    at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:36)
    at com.woocommerce.android.ui.common.UserEligibilityFetcher.fetchUserInfo(UserEligibilityFetcher.kt:31)
    at com.woocommerce.android.ui.common.UserEligibilityFetcher$fetchUserEligibility$1.invokeSuspend(UserEligibilityFetcher.kt:27)
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #4114

### Description
This PR implements the suggested solution of using an `UncaughtExceptionHandler` to catch and recover from the Selected Site exceptions. peaMlT-6L-p2#comment-770

Please check the comments below for the reasoning behind some decisions.

##### TC1: crash on a background thread
1. Apply the following patch
<details>
<summary>Patch</summary>

```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt	(revision 5020b47aa0b0d595955c3226640c8a8bff1b4446)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt	(date 1703003158081)
@@ -26,6 +26,9 @@
                 // - During logout flow...
 
                 // Send an error report.
+
+                println("UncaughtErrorsHandler: SelectedSiteResetException")
+
                 crashLogger.sendReport(e)
 
                 recoverIfNeeded()
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(revision 5020b47aa0b0d595955c3226640c8a8bff1b4446)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(date 1703003401340)
@@ -32,6 +32,7 @@
 import androidx.fragment.app.Fragment
 import androidx.fragment.app.FragmentManager
 import androidx.fragment.app.FragmentManager.FragmentLifecycleCallbacks
+import androidx.lifecycle.lifecycleScope
 import androidx.navigation.NavController
 import androidx.navigation.NavDestination
 import androidx.navigation.fragment.FragmentNavigatorExtras
@@ -57,6 +58,7 @@
 import com.woocommerce.android.support.help.HelpActivity
 import com.woocommerce.android.support.help.HelpOrigin
 import com.woocommerce.android.tools.SelectedSite
+import com.woocommerce.android.tools.SelectedSite.SelectedSiteResetException
 import com.woocommerce.android.ui.analytics.ranges.StatsTimeRangeSelection
 import com.woocommerce.android.ui.appwidgets.WidgetUpdater
 import com.woocommerce.android.ui.base.BaseFragment
@@ -112,6 +114,8 @@
 import com.woocommerce.android.widgets.AppRatingDialog
 import com.woocommerce.android.widgets.DisabledAppBarLayoutBehavior
 import dagger.hilt.android.AndroidEntryPoint
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.launch
 import org.wordpress.android.login.LoginAnalyticsListener
 import org.wordpress.android.login.LoginMode
 import org.wordpress.android.util.NetworkUtils
@@ -704,6 +708,14 @@
         if (navPos == ORDERS) {
             viewModel.removeOrderNotifications()
         }
+
+        if (navPos == ORDERS) {
+            selectedSite.reset()
+            lifecycleScope.launch(Dispatchers.IO) {
+                selectedSite.get()
+            }
+            restart()
+        }
     }
 
     override fun onNavItemReselected(navPos: BottomNavigationPosition) {
```
</details>

2. Open the app then sign in.
3. Click on Orders tab.
4. Confirm the app restarts without crashing.
5. Check logcat for the presence of line `UncaughtErrorsHandler: SelectedSiteResetException`

##### TC2: crash on main thread
1. Apply the following patch
<details>
<summary>Patch</summary>

```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt	(revision 5020b47aa0b0d595955c3226640c8a8bff1b4446)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/UncaughtErrorsHandler.kt	(date 1703003158081)
@@ -26,6 +26,9 @@
                 // - During logout flow...
 
                 // Send an error report.
+
+                println("UncaughtErrorsHandler: SelectedSiteResetException")
+
                 crashLogger.sendReport(e)
 
                 recoverIfNeeded()
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(revision 5020b47aa0b0d595955c3226640c8a8bff1b4446)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(date 1703003842272)
@@ -32,6 +32,7 @@
 import androidx.fragment.app.Fragment
 import androidx.fragment.app.FragmentManager
 import androidx.fragment.app.FragmentManager.FragmentLifecycleCallbacks
+import androidx.lifecycle.lifecycleScope
 import androidx.navigation.NavController
 import androidx.navigation.NavDestination
 import androidx.navigation.fragment.FragmentNavigatorExtras
@@ -57,6 +58,7 @@
 import com.woocommerce.android.support.help.HelpActivity
 import com.woocommerce.android.support.help.HelpOrigin
 import com.woocommerce.android.tools.SelectedSite
+import com.woocommerce.android.tools.SelectedSite.SelectedSiteResetException
 import com.woocommerce.android.ui.analytics.ranges.StatsTimeRangeSelection
 import com.woocommerce.android.ui.appwidgets.WidgetUpdater
 import com.woocommerce.android.ui.base.BaseFragment
@@ -112,6 +114,8 @@
 import com.woocommerce.android.widgets.AppRatingDialog
 import com.woocommerce.android.widgets.DisabledAppBarLayoutBehavior
 import dagger.hilt.android.AndroidEntryPoint
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.launch
 import org.wordpress.android.login.LoginAnalyticsListener
 import org.wordpress.android.login.LoginMode
 import org.wordpress.android.util.NetworkUtils
@@ -704,6 +708,12 @@
         if (navPos == ORDERS) {
             viewModel.removeOrderNotifications()
         }
+
+        if (navPos == ORDERS) {
+            selectedSite.reset()
+            restart()
+            selectedSite.get()
+        }
     }
 
     override fun onNavItemReselected(navPos: BottomNavigationPosition) {
```
</details>

2. Open the app then sign in.
3. Click on Orders tab.
4. Confirm the app restarts without crashing.
5. Check logcat for the presence of line `UncaughtErrorsHandler: SelectedSiteResetException`

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/UnseenReviewsCountHandler.kt [hunk 1]
```diff
@@ -26,15 +26,12 @@ class UnseenReviewsCountHandler @Inject constructor(
...
         selectedSite.observe()
+            .filterNotNull()
             .flatMapLatest { site ->
-                if (site != null) {
-                    notificationStore.observeNotificationsForSite(
-                        site = site,
-                        filterBySubtype = listOf(STORE_REVIEW.toString())
-                    )
-                } else {
-                    flowOf(emptyList())
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/UnseenReviewsCountHandler.kt:36]: Emitting an `emptyList` here was causing a new event after logout in MoreMenuViewModel https://github.com/woocommerce/woocommerce-android/blob/5020b47aa0b0d595955c3226640c8a8bff1b4446/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt#L64-L69

This event caused accessing the `SelectedSite` after the logout, which caused throwing the Exception, and we want to reduce those cases even if the app doesn't crash.

In any case, we don't need to observe the number of reviews when the site is `null`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt [hunk 2]
```diff
@@ -102,4 +99,10 @@ class SelectedSite(
 
     @Deprecated("Event bus is considered deprecated.", ReplaceWith("observe()"))
     class SelectedSiteChangedEvent(val site: SiteModel)
+
+    open class SelectedSiteException(message: String? = null) : Exception(message)
+    class SelectedSiteResetException : SelectedSiteException()
+    class SelectedSiteMissingException(
+        val siteId: Int
+    ) : SelectedSiteException("Selected Site is missing, id: $siteId")
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/tools/SelectedSite.kt]: I created those separate Exceptions in order to differentiate between exceptions after a deliberate `reset` and the other cases, the app will ignore just the former ones, and will keep crashing for the other cases.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt [hunk 3]
```diff
@@ -276,9 +275,14 @@ class MoreMenuViewModel @Inject constructor(
...
-        planRepository.fetchCurrentPlanDetails(selectedSite.get())
-            ?.formattedPlanName.orEmpty()
+    private fun loadSitePlanName(): Flow<String> = selectedSite.observe()
+        .filterNotNull()
+        .map { site ->
+            if (site.connectionType == SiteConnectionType.ApplicationPasswords) return@map ""
+            planRepository.fetchCurrentPlanDetails(selectedSite.get())
+                ?.formattedPlanName.orEmpty()
+        }
+        .onStart { emit("") }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: This part is what helped me to find about this issue https://github.com/woocommerce/woocommerce-android/pull/10444/files#r1431684172, the previous usage of `transform` above meant that we'll re-execute the code for any change emitted by the `combine` operator, which is not needed unless it's a `SiteModel` change.

This usage of `transform` was added in https://github.com/woocommerce/woocommerce-android/pull/10346 to make sure we start with an empty state before loading the `sitePlanName`, while I reverted this to emit a `Flow`, I kept the same behavior using `onStart`.

I also added an additional improvement: the request won't be sent for sites accessed using Application Passwords.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/UnseenReviewsCountHandler.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/UnseenReviewsCountHandler.kt:36]: Nice observation!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt (hunk 3 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: > I also added an additional improvement: the request won't be sent for sites accessed using Application Passwords.

Just curious -- wouldn't the `?.formattedPlanName.orEmpty()` return an empty string for application password anyway?

**Review by 0nko — COMMENTED** [review]
Excellent work, @hichamboushaba!

While testing the 2nd scenario, however, I noticed the app crashes. The app does recover but when I remove the `recoverIfNeeded()` it just stops.
```
FATAL EXCEPTION: main
Process: com.woocommerce.android.dev, PID: 10972
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
Caused by: com.woocommerce.android.tools.SelectedSite$SelectedSiteResetException
	at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:62)
	at com.woocommerce.android.ui.main.MainActivity.onNavItemSelected(MainActivity.kt:715)
	at com.woocommerce.android.ui.main.MainBottomNavigationView.onNavigationItemSelected(MainBottomNavigationView.kt:142)
	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(NavigationBarView.java:291)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at com.google.android.material.navigation.NavigationBarMenuView$1.onClick(NavigationBarMenuView.java:139)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

**Comment by hichamboushaba** [comment]
Thanks @0nko for the review

> While testing the 2nd scenario, however, I noticed the app crashes. The app does recover but when I remove the recoverIfNeeded() it just stops.

Can you clarify what you mean? When the main thread is dead we can't recover from this in the same session, so the `recoverIfNeeded` handles this by closing and restarting the app.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: Yes, but we know there will be a failure, so why make the call in the first place.

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: I was thinking if terms of the code simplification, but you're right, it's unnecessary to make the network call 👍.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: Yes, good point about code simplification, just since users complain about the slowness of the app, I think we should avoid any unnecessary network calls (especially for self-hosted sites).
WDYT about moving the check to the Repository? it'll keep the logic simple in the ViewModel.

**Comment by 0nko** [comment]
Oh ok.. I wasn't totally sure what constitutes a "crash" in this case. I was mystified by the fatal exception in the logcat, thinking that if we used the exception handler, this wouldn't show up as uncaught exception like that.

**Comment by hichamboushaba** [comment]
@0nko great point about the logcat, this intrigued me, and I wanted to understand why the log even the app doesn't crash, and I found the explanation in Android's code, AOSP has a concept called `UncaughtExceptionPreHandler` which is called before calling the regular `UncaughtExceptionHandler`, so even though we attach ours and skip the exception, the exception is still [consumed](https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/lang/Thread.java;l=2296-2304?q=Thread.java&ss=android%2Fplatform%2Fsuperproject%2Fmain) by the `PreHandler`, and by default it's [used](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/com/android/internal/os/RuntimeInit.java;l=234?q=RuntimeInit) for logging.

I just wanted to confirm that this won't be counted as a crash, and Ithe above finding confirms it, and also it won't be logged by Sentry as a Crash, as we consume the exception, and we don't pass it to the `baseHandler`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: I moved the check to the Repository in 78893d8457171eb0a733296dd1d5d813ac1b67f please let me know what you think.

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: Yeah, that's perfect, thank you! 👍

**Review by 0nko — APPROVED** [review]
Excellent analysis and solution! 👏 

Hopefully, this will solve the issue once and for all!
