### PR TITLE
Adapt DateUtils to support nullable error handling

### LINKED ISSUE #2581: IllegalArgumentException: Date string argument is not of format YYYY-MM-DD: false
Sentry Issue: [WOOCOMMERCE-ANDROID-R3](https://sentry.io/organizations/a8c/issues/1741476632/?referrer=github_integration)

```
IllegalArgumentException: Date string argument is not of format YYYY-MM-DD: false
    at com.woocommerce.android.util.DateUtils.getLocalizedLongDateString(DateUtils.kt:165)
    at com.woocommerce.android.ui.orders.OrderDetailShipmentTrackingItemView.initView(OrderDetailShipmentTrackingItemView.kt:46)
    at com.woocommerce.android.ui.orders.OrderDetailShipmentTrackingListView$ShipmentTrackingListAdapter.onBindViewHolder(OrderDetailShipmentTrackingListView.kt:121)
    at com.woocommerce.android.ui.orders.OrderDetailShipmentTrackingListView$ShipmentTrackingListAdapter.onBindViewHolder(OrderDetailShipmentTrackingListView.kt:103)
...
(90 additional frame(s) were not displayed)

Date string argument is not of format YYYY-MM-DD: false
```

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes https://github.com/woocommerce/woocommerce-android/issues/2581 and cover a wide range of crashes that often happen when a Woo Store site returns any slightly different date pattern. Right now our app crashes with an `IllegalArgumentException` if there's any kind of date parsing issue, since this is a very easy kind of bug to be caused by a misconfigured plugin, it would be desirable to report the issue to Sentry but avoid interrupting the user experience, so this PR replaces all exceptions throwing with a Sentry report and a WooLog input.

How to Test
==========
Verify if the date information is properly presented in the following app Views:

1. My Store time period range and stats date for each tab (day, week, month and year)
2. Order Details Shipment, Order Status and Orders List
3. Review date below reviewer name

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt [hunk 1]
```diff
@@ -55,7 +59,16 @@ fun Date.formatToEEEEMMMddhha(locale: Locale): String {
     return dateFormat.format(this)
 }
 
-fun Date.isToday() = org.apache.commons.lang3.time.DateUtils.isSameDay(Date(), this)
+fun Date.isToday() =
+    try {
+        isSameDay(Date(), this)
+    } catch (e: Exception) {
+        with("Unable to match dateString with today date. (current dateString value: $this)") {
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt:66]: @ThomazFB I notice we're catching the exception here, but many of the `DateUtils()` methods we use elsewhere in this PR can throw an `IllegalArgumentException`. Should we be catching those, too?

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt:66]: Taking over while @ThomazFB is AFK.

> Should we be catching those, too?

`IllegalArgumentException` is a subclass of `Exception`, so this catch block will handle it.

**Review by nbradbury — APPROVED** [review]
:shipit:
