### PR TITLE
issue/1349-npe-get-note-text

### LINKED ISSUE #1349: IllegalStateException: addNote_editor must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-34](https://sentry.io/organizations/a8c/issues/1125506381/?referrer=github_integration)

```
IllegalStateException: addNote_editor must not be null
    at com.woocommerce.android.ui.orders.AddOrderNoteFragment.getNoteText(AddOrderNoteFragment.kt:149)
    at com.woocommerce.android.ui.orders.AddOrderNoteFragment.onSaveInstanceState(AddOrderNoteFragment.kt:143)
    at com.woocommerce.android.ui.main.MainActivity.onSaveInstanceState(MainActivity.kt:171)
...
(23 additional frame(s) were not displayed)

addNote_editor must not be null
```

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #1349 - handles the (rare) case that we attempt to access the note text when the view isn't available (due to the fragment not being added yet).

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteFragment.kt [hunk 1]
```diff
@@ -149,7 +149,9 @@ class AddOrderNoteFragment : BaseFragment(), AddOrderNoteContract.View, BackPres
         super.onSaveInstanceState(outState)
     }
 
-    override fun getNoteText() = addNote_editor.text.toString().trim()
+    override fun getNoteText(): String {
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteFragment.kt]: np: can be simplified to:
```
override fun getNoteText() = addNote_editor?.text?.toString()?.trim() ?: ""
```

Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderNoteFragment.kt]: Done in 90c8b33
