### PR TITLE
[Bug] Coupons dissapearing from order

### LINKED ISSUE #12687: Coupons disappearing from an order
**Describe the bug**
Using multiple coupons can lead to unexpected behaviors

**To Reproduce**
Create two coupons: One for a 10% discount and another for a 100% discount

1. Go to 'Orders
2. Start creating an order
3. Add a product to the order
4. Add the 10% coupon
5. Add the 100% coupon
6. Check that the 10% coupon is removed from the coupon list.
7. Add the 10% discount again
8. Check that the two coupons are displayed in the list of coupons in the order
9. Tap on the list of coupons
10. Press back 
11. Check that one of the coupons is removed from the order

**Screenshots**

https://github.com/user-attachments/assets/16efd3e4-f1e2-4104-a935-67056df68231

**Expected behavior**
Adding multiple coupons to an order displays ALL the coupons added

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device:  Pixel 6
- Android version: Android 12
- WooCommerce Android version: 20.4

### PR DESCRIPTION
**Pull request by samiuelson**
Closes: #12687

### Description

This PR fixes a navigation bug that wrongly and involuntarily removed coupons from the order. 
Additionally, coupon edition-related code was cleaned up in the `OrderCreateEditViewModel`.

### Steps to reproduce

Steps to reproduce on trunk:
1. Create a new order and add a product
2. Add two coupons – verify they're added to the order at the bottom totals sheet
3. Remove both coupons from order (by tapping "Coupon edit" in the totals sheet), selecting and clicking "Remove coupon ..."
4. Add these coupons again
5. Open the coupons edition screen again, but this time go back to the order creation without removing any of them.
6. Notice one of the coupons gets removed from the order

### Testing information

It's important to test if the above scenario is fixed and if the feature works as expected in general:
* Coupons are persisted in the order when adding other products
* Different types of coupons are working as expected
* Coupon removal works
* It's possible to have multiple coupons in the order

### The tests that have been performed

Device: Pixel 8, Android 14
I verified that the scenario described in the Steps to reproduce is fixed. Additionally, attempted to do some more exploratory testing around the coupons feature in order creation.

### Images/gif

|before|after|
|---|---|
|<video src=https://github.com/user-attachments/assets/9c732c92-a66e-4902-afd2-6d5ea64ac247/>|<video src=https://github.com/user-attachments/assets/019423b8-5da4-49f3-99bc-f150dd615879/>|

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt [hunk 1]
```diff
@@ -199,7 +201,7 @@ class OrderCreateEditFormFragment :
     }
 
     private fun handleCouponEditResult() {
-        args.couponEditResult?.let {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt:202]: The root problem was caused by the fact that if `args.couponEditResult` was set to `CouponEditResult.RemoveCoupon` once, it was persisted in saved state Bundle. Then the `viewModel.onCouponEditResult(it)` logic was executed every time the fragment was recreated.

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @samiuelson. LGTM :shipit:
