### PR TITLE
Remove Sort, Filters, bottom navigation bar and Add Product CTA from Product search

### LINKED ISSUE #3259: Products: Design bugs on product search screen
**Describe the bug**

As @Garance91540 reported:

When selecting search in the Product list, can we:

- Remove the bottom nav bar that’s sticky at the top of the keyboard
- Remove the Sort and Filters CTA
- Remove the “Create Products” CTA
- Remove the search icon in the search bar
- Add a text indicator in the search bar to convey to users they can start typing in the bar directly
- This is an improvement and can be tackled later, but on Android I noticed we don’t start showing products in the product list until users have at entered at least 3 letters in the search field. On iOS, we start by displaying the full product list when the search bar is empty and then start updating it as soon as there’s one letter entered

**Screenshots**

This is the screen I see:

**Expected behavior**

Design:

**Mobile Environment**
Please include:
- Device: 
- Android version: 
- WooCommerce Android version: 5.6-rc-1

### PR DESCRIPTION
**Pull request by ctarda**
Closes: #3259 

Or at least most of it.

https://user-images.githubusercontent.com/2722505/138733215-3204d797-b2ad-4b52-b3b2-610e16571226.mov

### Description
This PR hides the bottom navigation bar, the "Sort", "Filters" and "Add Product" buttons when searching products.

The original description also mentions removing the search icon, but the icon is not removed when searching orders either. I thought it would be better to tackle that in a separate PR.

## Changes
- Updated ProductListFragment to show/hide the bottom toolbar according to the status of the view model
- Updated the logic that handled the visibility of the Add Product button and the sort and filter options in the view model 

### Testing instructions
1. Navigate to the Products tab
2. Select search. 
3. Search for products, cancel the search, see that the buttons behave as expected (see #3259 )

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt [hunk 1]
```diff
@@ -272,6 +273,9 @@ class ProductListFragment :
             new.isAddProductButtonVisible?.takeIfNotEqualTo(old?.isAddProductButtonVisible) { isVisible ->
                 showAddProductButton(show = isVisible)
             }
+            new.isSearchActive?.takeIfNotEqualTo(old?.isSearchActive) { isSearchActive ->
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt]: 🔍 Nitpick: No action necessary, feel free to skip this comment. 

The view layer (fragment/activity) would ideally not contain any business logic. This is very minor, but technically the fragment needs to decide that when "search is active" the bottom bar should be hidden and when "search is not active" the bottom bar should be shown. 

In this specific case it doesn't really matter, because the logic is extremely simple. However, it's a start which can lead to temptation to add more business logic to the view layer.

We might want to consider introducing a new field in the view state, perhaps something like this:

```
 @Parcelize
    data class ViewState(
        ...
        val isSearchActive: Boolean? = null,
        ...
    ) : Parcelable {
        val isBottomNavBarVisible = isSearchActive != true
    }
```

Wdyt?

**Review by malinajirka — APPROVED** [review]
Great job @ctarda! It works as expected and the code is following the conventions used in the affected files 👏. I've left one super minor comment, feel free to merge this PR as is 🚢 .

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt (hunk 1 above)
Comment (ctarda) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt]: Makes sense, thanks! I'll update and merge later today.

**Comment by ctarda** [comment]
Thanks for the review @malinajirka . I pushed an update to incorporate your feedback, and will merge when CI is ✅
