### PR TITLE
[Shipping Labels Revamp] Introduce Printing networking layer and file creation support

### LINKED ISSUE #12288: After purchasing a shipping label UI
Image

Design considerations:

> - After purchasing, you’re no longer “creating a shipping label,” and I think the screen title should reflect this. This deviates from order creation, but I don’t think it feels unexpected.
> - As mentioned earlier, let’s keep the order details screen the same for now – with one exception: Change the text on the button and have it navigate to the success screen.

❗ We will work on the updated order details screen on M4

### LINKED ISSUE #12392: Printing Shipping Label
This task is for adding network support for printing a shipping label using the latest plugin endpoint `GET /wcshipping/v1/label/print`

Here is the endpoint's documentation
https://github.com/woocommerce/woocommerce-shipping/blob/trunk/docs/api/label-print.md

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #12392 and partially fix issue #12288 by introducing the networking layer and all File operations to display the Shipping Label for printing. 

This PR also connects the Printing action with the Purchased screen, but it's only to make it easy to test the Printing code. It doesn't implement anything regarding loading and error feedback. UI feedback and improvements will be added in the next PR for issue #12288. 

Screen Capture
==========
https://github.com/user-attachments/assets/0afcd884-c628-451e-a796-23b0270e638c

How to Test
==========
1. Open the main Shipping Label screen
2. Since the Purchased screen is only accessible from the landscape screen binding, switch the device to landscape mode
3. Hit the Purchase button
4. Once in the Purchased Screen, hit the Print Shipping Label and verify that for each of the Paper size, the Shipping Label is opened in a separate screen following the selected paper size.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>WooShippingLabelRestClient</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>WooShippingLabelPurchasedViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt [hunk 1]
```diff
@@ -187,8 +187,9 @@ class WooShippingLabelCreationViewModel @Inject constructor(
         triggerEvent(StartPackageSelection)
     }
 
+    // This is a arbitrary Label ID, we must replace this later with the full Shipping Labels data after the purchase
     fun onPurchaseShippingLabel() {
-        triggerEvent(LabelPurchased)
+        triggerEvent(LabelPurchased(labelId = 4158L))
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:192]: I'm hard coding this Shipping Label ID since the actual information will only be available once we have the purchase flow done. 

For testing purposes, it's useful to highlight that this ID exists in the Superlative Centaur store, so by testing this code against that store, it will be possible to generate the Shipping Label printing and test the actual printing mechanics without having to deal with any code changes.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+import dagger.hilt.android.lifecycle.HiltViewModel
+import kotlinx.coroutines.flow.update
+import kotlinx.coroutines.launch
+import kotlinx.parcelize.Parcelize
+import java.io.File
+import java.util.Locale
+import javax.inject.Inject
+
+@HiltViewModel
+class WooShippingLabelPurchasedViewModel @Inject constructor(
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModel.kt:22]: I'll be introducing a lot of changes to this ViewModel in the next PR, so I didn't add a Unit test class yet in this PR and focused on covering only the printing use case

**Review by atorresveiga — APPROVED** [review]
Great work @ThomazFB

LGTM! :shipit:
