### PR TITLE
Loading origin addresses fails

### LINKED ISSUE #13320: Loading origin addresses fails
When loading the origin addresses in the purchase shipping label flow, we should display an error if the request fails.

Image

https://teameaglep2.wordpress.com/2025/01/15/revamp-shipping-labels-recovering-from-errors/

### PR DESCRIPTION
**Pull request by irfano**
Closes: #13320

### Description

This adds functionality to the Retry button to update failed origin addresses.

#### To create a fake error response from the endpoint
1. Go to Menu → Settings → Developer Options → API Faker
2. Tap + button.
3. Enter these settings:
```
Type: WordPress REST API
Path: /wcshipping/v1/address/origins or /wcshipping/v1/account/settings
Status Code: 500
```
4. Tap Save.
5. Enable API Faker.

#### To test the retry screen
1. Log in to a site that is eligible for shipping labels.
2. Go to orders.
3. Create a new order and complete the payment.
4. Open the order details and tap the "Create shipping label" button.
5. Verify that the error screen appears when the API faker is enabled.
6. Disable the API faker by tapping the red bottom banner.
7. Tap the Retry button.
8. Verify that the error disappears.

### Testing information

To ensure this does not break the handling of store options errors, test these cases:
- [x] Failing `/wcshipping/v1/address/origins`
- [x] Failing `/wcshipping/v1/address/origins` and `/wcshipping/v1/account/settings`
- [x] Failing `/wcshipping/v1/account/settings`

### The tests that have been performed

Steps above

### Images/gif

[Screen_recording_20250220_185952.webm](https://github.com/user-attachments/assets/a4798ed9-bda9-44ac-b892-31d64884f966)

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt [hunk 1]
```diff
@@ -105,7 +105,7 @@ class WooShippingLabelRepository @Inject constructor(
                 ?.takeIf { response.isError.not() }
                 ?.let {
                     addressDataStore.saveOriginAddresses(it)
-                }
+                } ?: addressDataStore.clearOriginAddresses()
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/networking/WooShippingLabelRepository.kt:108]: I decided to clear the data store if the new remote data returns an error.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt [hunk 2]
```diff
@@ -503,14 +510,23 @@ class WooShippingLabelCreationViewModel @Inject constructor(
...
         launch {
             val result = fetchAccountSettings().getOrNull()
             storeOptions.value = StoreOptionsModel.EMPTY
             storeOptions.value = result
         }
+
+        // Fetch origin address and inform `getShippingAddresses()` via `forceFetchedShippingAddresses`
+        launch {
+            fetchOriginAddresses()
+            forceFetchedShippingAddresses.emit(Unit)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt]: We're already observing changes of origin addresses in `getShippingAddresses()`, but `fetchOriginAddresses()` does not trigger `observeOriginAddresses()`, which is used in `getShippingAddresses()`. This happens because `observeOriginAddresses()` is triggered only when the cached data changes. For example, if the cached data is `null`, and the new data is also `null`, `observeOriginAddresses()` is not triggered, causing the Loading state to never end. 
To resolve this, I used `forceFetchedShippingAddresses.emit(Unit)` to trigger `getShippingAddresses()`.

Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt]: We have a similar issue with the settings retry. Maybe we can use this strategy for both cases, having a single  `forceRefresh` (name could be different 😅 ) flow triggered from the retry method and observed as part of observeShippingLabelInformation(). WDYT?

**Review by atorresveiga — APPROVED** [review]
Excellent work, @irfano! I added a minor comment that isn't a blocker for this PR.
LGTM! :shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt (hunk 2 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt]: I updated the logic and added a new trigger `loadTrigger = MutableSharedFlow<Unit>()`. This won't trigger `getShippingAddresses()`, as if `originAddress` changes, it will already be triggered.
Now, `loadTrigger` triggers only `observeShippingLabelInformation()`, which is currently responsible for updating the uiState.
I believe this solution is better and safer. There are so many async calls in this view model to load the UI, which is why it took some time to find the optimal solution for me. @atorresveiga, could you please review my latest commit?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt [hunk 3]
```diff
@@ -503,13 +510,21 @@ class WooShippingLabelCreationViewModel @Inject constructor(
...
+            try {
+                joinAll(
+                    launch { getOrderInformation() },
+                    launch { fetchAccountSettings() },
+                    launch { fetchOriginAddresses() }
+                )
+            } catch (e: CancellationException) {
+                WooLog.d(WooLog.T.ORDERS, "CancellationException while retrying: $e")
+            } finally {
+                loadTrigger.emit(Unit)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:526]: Triggering loadTrigger after all fetch jobs are completed.

**Comment by atorresveiga** [comment]
Great work @irfano. LGTM! :shipit:
