### PR TITLE
Issue/766 inflate exception top earners

### LINKED ISSUE #766: InflateException in DashboardTopEarnersView
Only one report of this:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}:
 android.view.InflateException: Binary XML file line #54: Binary XML file line #54:
 Error inflating class com.woocommerce.android.ui.dashboard.DashboardTopEarnersView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2750)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2811)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6316)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

http://crashes.to/s/777acc83825

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #766 - I wasn't able to reproduce the inflate exception, but I'm fairly confident this PR fixes it. A common cause of these exceptions is running out of memory loading images, and it turns out the way we were attempting to reduce the size of top earner images doesn't work with all sites.

This PR corrects this by using Photon to request images at the exact size needed.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt [hunk 1]
```diff
@@ -169,8 +169,7 @@ class DashboardTopEarnersView @JvmOverloads constructor(ctx: Context, attrs: Att
             holder.totalSpendText.text = total
             holder.divider.visibility = if (position < itemCount - 1) View.VISIBLE else View.GONE
 
-            // strip the image query params and add a width param that matches our desired size
-            val imageUrl = UrlUtils.removeQuery(topEarner.image) + "?w=$imageSize"
+            val imageUrl = PhotonUtils.getPhotonImageUrl(topEarner.image, imageSize, 0)
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardTopEarnersView.kt]: TIL'd about Photon! 👍
