### PR TITLE
[Better Tablet Products] Fixes for 2<->1 panes transitions

### LINKED ISSUE #10978: [Better Tablet Products] Fix back navigation after transiction from 2 panes to 1 on screen size change

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10978

### Description

* Back arrow shown after 2 -> 1 pane transition on the product details screen
* If the product details screen was opened in 1 pane and then configuration changed to show 2 panes, then currently open product will be selected
* If after being in 2 pane mode, 1 pane mode shows products details, then back navigation will hide product details fragment and show product lists
(Infinite loading after coming back from details screen and config change is fixed in https://github.com/woocommerce/woocommerce-android/pull/11144)

### Testing instructions

Using a big phone, where in portrait mode 1 pane mode is used, and in landscape, 2 pane mode is used, try different combinations 1<->2 panes transactions and notice that they all make sense now

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/f2d890d7-2de2-486c-9f8d-cbbf0310c04b

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Followed testing instructions and those work fine.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailsToolbarHelper.kt [hunk 1]
```diff
@@ -80,7 +80,7 @@ class ProductDetailsToolbarHelper @Inject constructor(
                         null
                     }
                 }
-                fragment?.findNavController()?.hasBackStackEntry(R.id.products) == true -> {
+                isPartOfProductListFlow() -> {
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailsToolbarHelper.kt:83]: I think this new method makes sense.

**Review by backwardstruck — APPROVED** [review]
