### PR TITLE
Shipping Labels: international requirements for DHL

### LINKED ISSUE #4195: Internation shipping labels purchase fails if destination phone number is missing and `DHL` is selected
When trying to create an international shipping label, if `DHL` is selected and the destination address is missing a phone number, the purchase will fail, we need to implement the following changes:

- [ ] Prefill the phone number if it was entered by the user.
- [ ] Require the phone number if `DHL` is selected.

The issue is happening in the web client as well: https://github.com/Automattic/woocommerce-services/issues/2276

### PR DESCRIPTION
**Pull request by hichamboushaba**
Fixes #4195, this PR has two big changes:
1. Adds prefilling of the destination address phone number, the phone number is added by WCS, and it's part of the order's meta data.
2. Update the Shipping Label creation form to require a non-empty phone number when the shipment is international, and the carrier is DHL.

This depends on the PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2029, please don't merge until it's merged, and the FluxC's hash is updated.

#### Testing
1. Make sure your store is ready for WCS testing.
2. Create an **international** order eligible for shipping label creation and ensure that a phone number is entered in the shipping address.
3. Open the other details in the app*.
4. Click on "Create shipping label".
5. When getting to the destination address step, **confirm** that the phone number is prefilled.
6. Clear the phone number.
7. In the packaging step, please make sure to select a custom package or a DHL package.
8. Finish the customs step.
9. Make sure to select DHL at the carriers step.
10. Notice that the app will invalidate the destination address.
11. Open the destination address, and confirm that it asks you to enter a phone number.
12. Enter a phone number.
13. Continue the label purchase.
14. Confirm that it works without issues.

*. When getting to the step 3, if you decided to use an old order for testing, please make sure that you refresh it in the app, to make sure that the metadata is fetched.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt [hunk 1]
```diff
@@ -0,0 +1,65 @@
+package com.woocommerce.android.model
+
+import android.os.Parcel
+import android.os.Parcelable
+import android.os.Parcelable.Creator
+import org.wordpress.android.fluxc.model.WCMetaData
+import java.io.Serializable
+
+// we can's use Parcelize here for the generic type due to this bug: https://youtrack.jetbrains.com/issue/KT-42652
+data class MetaData<T : Any>(
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt:10]: I decided to make this class generic to allow reusing it for other features, for example when we get to working on Order Addon's, we would need to fetch the Product's `metadata`, and the `value`s their are objects, so we can use this class to hold them as well.

**Comment by hafizrahman** [comment]
Testing instructions work as mentioned 🥳 

Some thoughts about the UI:

> Make sure to select DHL at the carriers step.
> Notice that the app will invalidate the destination address.

After selecting DHL and tapping "Done", I am returned to the main "Create Shipping label" screen with only the "Ship to" section now opened and having the "Continue" button. I feel this should intuitive enough for most users that the next action they should do is to tap "Continue" there (to fill in the destination phone number). However, I worry that some users will not realize that they need to do that, because the app does not say anything.

Next if I tap continue, the "Ship to" screen has the phone field empty but no indication that user should be filling it, the error message only shows up if they tap "Done". Screenshots below:

| screenshot | notes |
| - |  -  |
| image | This screen does not have any indication that choosing DHL means user now have to go back to the destination field and enter phone number |
| image | After tapping Continue on the previous screen, the phone field does not give any indication yet that it needs to be filled. |
| image | The phone field error message only shows up if user taps "Done" on top right. |
 
What would be a good way for us to make the next step be more obvious to users? cc @woocommerce/mobile-designers

**Comment by hichamboushaba** [comment]
Thanks @hafizrahman for the review.

> This screen does not have any indication that choosing DHL means user now have to go back to the destination field and enter phone number

This was already discussed, and we agreed that we will just `undo` the steps that have to be redone, this happens too for origin address if it's missing a phone number (discussion: p1622222707138200/1614252487.023600-slack-CGPNUU63E)
Let's also keep in mind that there are all very edge cases, normally we will prefill the phone number using the one entered by the user.

>  After tapping Continue on the previous screen, the phone field does not give any indication yet that it needs to be filled.

The EditAddress screen needs some love, and I already created a ticket to tackle those separately when we finish the more prioritized issues: #4177, I will update the ticket to mention showing the `validation` errors directly when it's opened.

**Comment by hafizrahman** [comment]
> This was already discussed, and we agreed that we will just undo the steps that have to be redone

Thanks for that link! If it's already gotten a design discussion then it's all good 👍🏼 

>  #4177, I will update the ticket to mention showing the validation errors directly when it's opened

Thanks for documenting that in the issue!

With these two concerns I agree that these are edge cases, and while they might slow down some user or prevent them from successfully finishing it, it's likely quite rare because if they do proceed with the steps, the error message eventually do appear.

Checking code now 👀

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt [hunk 2]
```diff
@@ -523,7 +526,14 @@ class ShippingLabelsStateMachine @Inject constructor() {
...
             override val status: StepStatus,
             override val data: List<ShippingRate>
-        ) : Step<List<ShippingRate>>()
+        ) : Step<List<ShippingRate>>() {
+            /**
+             * Checks if one of the selected carriers requires a destination phone number
+             * if the shipment is international
+             */
+            val requiresDestinationPhoneNumber
+                get() = data.any { it.carrierId.contains("dhl", ignoreCase = true) }
```
Comment (hafizrahman) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt:535]: Should we make this a constant instead? I understand this might be unlikely to change frequently, it's just that in my experience as newcomer, seeing a constant with descriptive name helps me understand what a particular value is for, and hunting them down while troubleshooting is a bit faster.

File: WooCommerce/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -477,7 +477,8 @@
     <string name="shipping_label_address_suggestion_entered_address">Entered address</string>
     <string name="shipping_label_address_suggestion_suggested_address">Suggested address</string>
     <string name="shipping_label_address_phone_required">A phone number is required because this shipment requires a customs form</string>
-    <string name="shipping_label_address_phone_invalid">Customs forms require a 10-digit phone number</string>
+    <string name="shipping_label_origin_address_phone_invalid">Customs forms require a 10-digit phone number</string>
+    <string name="shipping_label_destination_address_phone_invalid">Please enter a valid phone number</string>
```
Comment (hafizrahman) [inline WooCommerce/src/main/res/values/strings.xml:481]: Here can we inform users what a valid phone number should look like? Although it seems we only check if there's any digits, so not sure what to say here. Maybe something like "Entered phone number has unsupported characters" can be more descriptive about what's wrong?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressValidator.kt [hunk 4]
```diff
@@ -26,61 +25,65 @@ class ShippingLabelAddressValidator @Inject constructor(
...
-                    selectedSite.get(),
-                    address.toShippingLabelModel(),
-                    type.toDataType()
-                )
-            }
+        return when {
+            isNameMissing(address) -> ValidationResult.NameMissing
+            requiresPhoneNumber && !address.hasValidPhoneNumber(type) -> ValidationResult.PhoneInvalid
+            else -> verifyAddress(address, type)
+        }
```
Comment (hafizrahman) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelAddressValidator.kt:34]: I like the simplification here, much easier to read.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt:535]: I don't think it's mandatory, yes constants for unclear literals make the code more readable, but having a constant `const val DHL = "dhl"` will just add to the noise, and doesn't bring anything useful 🙂

File: WooCommerce/src/main/res/values/strings.xml (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/res/values/strings.xml:481]: EasyPost accept other characters in the phone number, and will throw an error if it doesn't contain any digits, so saying "Entered phone number has unsupported characters" is misleading, frankly I don't see a way to improve the message without being too verbose, and I don't think it will be hard for anyone to not understand that a phone number has to contain digits 🙂

Comment (hafizrahman) [reply WooCommerce/src/main/res/values/strings.xml:481]: Oh yeah, that makes sense.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt (hunk 2 above)
Comment (hafizrahman) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/ShippingLabelsStateMachine.kt:535]: I was thinking of making a list of carriers with this requirement, but I agree. Also feels like premature optimization for me.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+        parcel.writeString(key)
+        parcel.writeSerializable(value::class.java)
+        parcel.writeValue(value)
+    }
+
+    override fun describeContents(): Int {
+        return 0
+    }
+
+    companion object CREATOR : Creator<MetaData<*>> {
```
Comment (hafizrahman) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt:33]: More of a question: why is "CREATOR" uppercased here?

**Comment by hafizrahman** [comment]
This is now all LGTM, I left a question but more for my own learning.

Still figuring out how to check Tracks-related items [as mentioned by the bot](https://github.com/woocommerce/woocommerce-android/pull/4216#issuecomment-862339707), and can approve afterward.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt (hunk 5 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/model/MetaData.kt:33]: The convention is to uppercase names of constants, and `CREATOR` is a constant here, but here it's not just to respect the convention, but to make it work, as `Parcelable` requires the static `CREATOR`:
> Classes implementing the Parcelable interface must also have a non-null static field called CREATOR of a type that implements the Parcelable.Creator interface.
https://developer.android.com/reference/android/os/Parcelable

This is new in our repo, as we are using @Parcelize which generates it for us for all the other `Parcelable` classes.

**Review by hafizrahman — APPROVED** [review]
All good including Tracks.
