### PR TITLE
issue/834-notification-review-detail

### LINKED ISSUE #834: Tapped notification doesn't open detail
In #832 we fixed a crash that could occur when opening a notif, but another problem remains: tapping a notif opens the app but doesn't always open the detail.

To repro this, force close the app then generate a notif and tap on it.

**Update:** We originally thought the problem was due to the notif list fragment not being added yet, but that's not the case. The real problem is that [MainPresenter.getNotificationByRemoteNoteId()](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainPresenter.kt#L61) is returning null in this situation, so no notif detail is opened. Note that this happens for orders as well, so it's not specific to reviews.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #834 - Injects the notification store so it's available when notification is received while app isn't loaded. Hat tip to @aforcier for the solution!

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt [hunk 1]
```diff
@@ -47,6 +48,8 @@ class NotificationHandler @Inject constructor(
     private val siteStore: SiteStore,
     private val dispatcher: Dispatcher
 ) {
+    @Inject lateinit var notificationStore: NotificationStore
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt]: This should just be added to the constructor since the whole class is injected: 

```
@Singleton
class NotificationHandler @Inject constructor(
    private val siteStore: SiteStore,
    private val dispatcher: Dispatcher,
    private val notificationStore: NotificationStore // Required to ensure instantiated    
) {
    companion object {
```
Just like in the example, I recommend adding a code comment so it's not removed later for not being used.

Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt]: I'll make this change in one of the open notif PRs since this was merged.
