### PR TITLE
Fix crashes related to calling `onBackPressed` directly

### LINKED ISSUE #13226: IllegalStateException: FragmentManager is already executing transactions
Sentry Issue: [WOOCOMMERCE-ANDROID-H98](https://a8c.sentry.io/issues/6133005911/?referrer=github_integration)

```
IllegalStateException: FragmentManager is already executing transactions
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment.setupObservers$lambda$24(VariationDetailFragment.kt:320)
    is Exit -> requireActivity().onBackPressedDispatcher.onBackPressed()
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment.$r8$lambda$6j_9a98nQXRa_5YR2Y_XIxTyzTw(VariationDetailFragment.kt:0)
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment$$ExternalSyntheticLambda14.invoke(VariationDetailFragment:0)
    at com.woocommerce.android.ui.products.variations.VariationDetailFragment$sam$androidx_lifecycle_Observer$0.onChanged(VariationDetailFragment.kt:0)
    at com.woocommerce.android.viewmodel.MultiLiveEvent.observe$lambda$0(MultiLiveEvent.kt:43)
    observer.onChanged(t)
...
(52 additional frame(s) were not displayed)
```

### LINKED ISSUE #13289: IllegalStateException: FragmentManager is already executing transactions
Sentry Issue: [WOOCOMMERCE-ANDROID-H7H](https://a8c.sentry.io/issues/6126911132/?referrer=github_integration)

```
IllegalStateException: FragmentManager is already executing transactions
    at com.woocommerce.android.ui.products.variations.VariationsBulkUpdateBaseFragment.observeEvents$lambda$0(VariationsBulkUpdateBaseFragment.kt:71)
    is MultiLiveEvent.Event.Exit -> requireActivity().onBackPressedDispatcher.onBackPressed()
    at com.woocommerce.android.ui.products.variations.VariationsBulkUpdateBaseFragment.$r8$lambda$13C8fOyumvZ0-fg2digfBoV-LeI(VariationsBulkUpdateBaseFragment.kt:0)
    at com.woocommerce.android.ui.products.variations.VariationsBulkUpdateBaseFragment$$ExternalSyntheticLambda0.invoke(VariationsBulkUpdateBaseFragment:0)
    at com.woocommerce.android.ui.products.variations.VariationsBulkUpdateBaseFragment$sam$androidx_lifecycle_Observer$0.onChanged(VariationsBulkUpdateBaseFragment.kt:0)
    at com.woocommerce.android.viewmodel.MultiLiveEvent.observe$lambda$0(MultiLiveEvent.kt:43)
    observer.onChanged(t)
...
(52 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #13289 
Closes: #13226 

### Description
This PR is a second attempt to fix the above two crashes, the attempt we did last time didn't work.

This time, I spend some trying to find the root cause, and I think it comes down to using `onBackPressed` directly instead of using `findNavController().navigateUp()`, the `onBackPressed()` callback doesn't work well when we have multiple concurrent navigation events, which can occur in some cases:
1. In the `VariationDetailFragment`: if the loading fails, the `viewModel` will trigger the `Exit` event, so if this happens at the same time with another navigation event, it will cause a crash.
2. In `VariationsBulkUpdateBaseFragment`: Same but here the `Exit` event is triggered when saving the changes finishes.

The easiest approach to reproduce the crash in both cases is to send the app to background during the loading, and then resume it after it's done, this will cause two navigation events (or multiple): handling the `Exit` event + restoring the fragments. I'll post below the exact steps.

The last [commit](https://github.com/woocommerce/woocommerce-android/pull/13584/commits/e70d1651f00d351443752b53f0d341fb69722882) of the PR fixes an issue with Toolbar visibility in the variation bulk update screens, it was broken in tablets when the two-pane layout was used.

### Steps to reproduce
**TC1**: Confirm the fix
1. Open a variable product.
2. Open the variations list.
3. Tap on the menu, and choose "Bulk Update"
4. Choose the Price option.
5. Enter a new price, then tap "Done"
6. Send the app to background.
7. Wait a little bit for the request to finish, then open the app.
8. Confirm the app crashes in `trunk` and not in this branch.

**TC2**: Non-regression (using a **tablet**)
Just to confirm that `navigateUp` works without issue in the two-pane layout:
- Test navigation back in `VariationDetailFragment `
- Test opening an `AddProductCategoryFragment`, then make some edits and navigate back, then discard the changes.

### Testing information
- Confirm the fix works as expected.
- Confirm there is no regression with the changes in the two-pane layout.

### The tests that have been performed
^

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryFragment.kt [hunk 1]
```diff
@@ -181,7 +181,7 @@ class AddProductCategoryFragment :
         viewModel.event.observe(viewLifecycleOwner) { event ->
             when (event) {
                 is ShowSnackbar -> uiMessageResolver.showSnack(event.message)
-                is Exit -> requireActivity().onBackPressedDispatcher.onBackPressed()
+                is Exit -> findNavController().navigateUp()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/categories/AddProductCategoryFragment.kt:184]: This wasn't causing any crashes from what I see, but I don't see any reason for this to use `onBackPressed` instead of `navigateUp`, and from the git history, there was no reason.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt [hunk 2]
```diff
@@ -113,9 +113,7 @@ class VariationDetailFragment :
             onMenuItemSelected = ::onMenuItemSelected,
             onCreateMenu = { toolbar ->
                 toolbar.setNavigationOnClickListener {
-                    if (onRequestAllowBackPress()) {
-                        findNavController().navigateUp()
-                    }
+                    viewModel.onExit()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailFragment.kt:116]: I don't think there is real reason to complicate the navigation logic here, so I simplified to can directly call the `viewModel` to keep a single flow for events.
I also simplified the `onRequestAllowBackPress` below by always calling the `viewModel`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt [hunk 3]
```diff
@@ -46,7 +45,6 @@ abstract class BaseProductFragment : BaseFragment, BackPressListener {
         viewModel.event.observe(viewLifecycleOwner) { event ->
             when (event) {
                 is ShowSnackbar -> uiMessageResolver.showSnack(event.message)
-                is Exit -> requireActivity().onBackPressedDispatcher.onBackPressed()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/BaseProductFragment.kt:49]: Forgot to mention this, I was just looking at the different calls to `onBackPressed` that we had, and saw this, and found out that it's not used for anything, the `ProductDetailViewModel` doesn't trigger the `Exit` event for anything, it uses its specific version `ProductExit`.

**Review by JorgeMucientes — APPROVED** [review]
Works great @hichamboushaba! Thanks for finding the root cause and also addressing the issue around the missing toolbar on tablet layouts.
