### PR TITLE
[Shipping Labels] Handle loading order error

### LINKED ISSUE #13317: Loading order detail fails
When loading the order details in the purchase shipping flow, we should exit the flow if the order is not found.

Image

https://teameaglep2.wordpress.com/2025/01/15/revamp-shipping-labels-recovering-from-errors/

### PR DESCRIPTION
**Pull request by irfano**
Closes: #13317

### Description

This handles an error when retrieving the order on the shipping label creation screen. Since the creation flow starts from the order detail screen and the order is fetched from the local database, this error is not expected to occur in the released version. However, it is handled as a precaution. If the order from the database is null, we display an “Unable to load the order” error and navigate back.

### Steps to reproduce

- To force the database return a null order, apply this patch:[_Force_the_database_to_return_a_null_order_in_the_shipping_label_creation.patch](https://github.com/user-attachments/files/18847056/_Force_the_database_to_return_a_null_order_in_the_shipping_label_creation.patch)
- Log in to a site that is eligible for shipping labels.
- Go to orders.
- Create a new order and complete the payment.
- Open the order details and tap the "Create shipping label" button.

### The tests that have been performed

Steps above.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt [hunk 1]
```diff
@@ -113,7 +114,12 @@ class WooShippingLabelCreationViewModel @Inject constructor(
     }
 
     private suspend fun getOrderInformation() {
-        orderDetailRepository.getOrderById(navArgs.orderId).let { order.value = it }
+        orderDetailRepository.getOrderById(navArgs.orderId)?.let {
+            order.value = it
+        } ?: run {
+            triggerEvent(Event.ShowSnackbar(R.string.woo_shipping_labels_loading_order_error))
+            postTriggerEvent(Event.Exit)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationViewModel.kt:121]: `postTriggerEvent()` was introduced in this PR because it was necessary to trigger Exit later, rather than immediately. Otherwise, the snackbar cannot be displayed.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/251">21.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by atorresveiga — APPROVED** [review]
Great work @irfano! Code looks good and is working as expected

LGTM! :shipit:
