### PR TITLE
Register fcm token for a site only if it exists

### LINKED ISSUE #4584: IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
Sentry Issue: [WOOCOMMERCE-ANDROID-22R](https://sentry.io/organizations/a8c/issues/2564688252/?referrer=github_integration)

```
IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
    at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:36)
    at com.woocommerce.android.push.NotificationRegistrationHandler.onNewFCMTokenReceived(NotificationRegistrationHandler.kt:27)
    at com.woocommerce.android.push.FCMRegistrationIntentService$onHandleWork$1.onComplete(FCMRegistrationIntentService.kt:33)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #4584 

### Description
This PR checks if a site exists before trying to register a FCM token for that site. This was caused by the changes in [this PR](https://github.com/woocommerce/woocommerce-android/pull/4526). I failed to add the `selectedSite.exists()` check to the code when cleaning up the notification service 🤦‍♀️ . 

**Since this is an important fix it should be merged to the release branch.**

cc @jkmassel this would require a new beta to be released, since this affects users during startup. Thank you do much 🙇‍♀️ 

### Testing instructions
- Try to login to a site using the magic link flow and you will notice the app crashing consistently.
- Pull the changes from this PR and ensure that the app no longer crashes.
- Run `NotificationRegistrationHandlerTest`.
- It would be good to check that FCM registration is successful after login and after selecting site.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt [hunk 1]
```diff
@@ -17,8 +17,8 @@ class NotificationRegistrationHandler @Inject constructor(
     private val selectedSite: SelectedSite
 ) {
     fun onNewFCMTokenReceived(token: String) {
-        // Register for WordPress.com notifications only if user is logged in
-        if (accountStore.hasAccessToken()) {
+        // Register for WordPress.com notifications only if user is logged in & if site exists
+        if (accountStore.hasAccessToken() && selectedSite.exists()) {
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt:21]: Good fix! I've checked [the old code](https://github.com/woocommerce/woocommerce-android/pull/4526/files#diff-4976a1af14bd7d915c81355e36335c1453cca1a7223cb95b77ee05c3431594c9L65) and previously we were checking for those both conditions.

🌱 I wonder for the future - should we really crash app if selected site can't be found? This seems like a really harsh behaviour. Maybe we agree on some other solution.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationRegistrationHandlerTest.kt [hunk 2]
```diff
@@ -40,9 +42,24 @@ class NotificationRegistrationHandlerTest {
         verify(dispatcher, never()).dispatch(any())
     }
 
+    @Test
+    fun `do not register new fcm token if site does not exist`() {
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/push/NotificationRegistrationHandlerTest.kt:46]: 💯 Thanks for adding test!

**Review by wzieba — APPROVED** [review]
I'm having difficulties with testing the fix, I'm getting:

```
Tracked: login_magic_link_failed, Properties: {"error":"You’re not allowed to request a login link for this account.","is_debug":true}
```

but I don't want to block this PR because of that. I think change looks good and there's coverage with unit test. LGTM! :shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt (hunk 1 above)
Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationRegistrationHandler.kt:21]: Once we start support notifications for multiple stores, we won't be sending the selected site when registering FCM so this is just temporary 😄

**Comment by anitaa1990** [comment]
Thank you for the review @wzieba! I'll merge this PR now 🙇‍♀️
