### PR TITLE
Fix NoSuchElementException on the site picker screen

### LINKED ISSUE #10553: NoSuchElementException: Collection contains no element matching the predicate.
Sentry Issue: [WOOCOMMERCE-ANDROID-8J5](https://a8c.sentry.io/issues/4641555369/?referrer=github_integration)

```
NoSuchElementException: Collection contains no element matching the predicate.
    at com.woocommerce.android.ui.sitepicker.SitePickerViewModel.onContinueButtonClick(SitePickerViewModel.kt:466)
    at com.woocommerce.android.ui.sitepicker.SitePickerViewModel.onContinueButtonClick$default(SitePickerViewModel.kt:465)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment.updateStoreListView$lambda$3(SitePickerFragment.kt:247)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment.$r8$lambda$1KVl_jOqxi2Szi9OEHJvfQGRjlA(SitePickerFragment.kt:0)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment$$InternalSyntheticLambda$1$9287dcfcb461aad35295102d63e0b960f6c8c41b26af1f2238e09591e6a8223e$0.onClick(R8$$SyntheticClass:0)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by irfano**
Closes: #10553 

### Description

In low memory conditions, the "Continue" button may stay visible even if the screen is in the loading state. This PR fixes this case and aims to prevent the [Sentry crash](https://a8c.sentry.io/issues/4641555369/?referrer=github_integration) that is thrown after the continue button is tapped. 

I couldn't reproduce the crash but there's a possibility this fixes the Sentry issue.

### Steps to reproduce

To reproduce the visible Continue button case, use the `trunk` branch.
1. Enable "Don't keep activities" from the device's "Developer settings".
2. Go to Menu and tap the first button to open the Site Picker screen.
3. After sites are loaded, open the device's Home screen.
4. Open the Woo app again.
 
[bug.webm](https://github.com/user-attachments/assets/50b03138-e283-4496-b59c-4ad7ccf89b4a)

### Testing information

Repeat the "Steps to reproduce" and verify that the "Continue button" is not visible when loading. Please also test when "Don't keep activities" is disabled.

### The tests that have been performed

Explained in "Testing information".

### Images/gif

|before|after|
|-|-|
|||

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/235">20.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt [hunk 1]
```diff
@@ -140,7 +140,10 @@ class SitePickerViewModel @Inject constructor(
     }
 
     private suspend fun fetchSitesFromApi(showSkeleton: Boolean) {
-        sitePickerViewState = sitePickerViewState.copy(isSkeletonViewVisible = showSkeleton)
+        sitePickerViewState = sitePickerViewState.copy(
+            isSkeletonViewVisible = showSkeleton,
+            isPrimaryBtnVisible = false
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt:145]: ❓ What do you think about adding unit test for this business logic? Ensuring that primary button's state is hidden when we are fetching sites from API.

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @irfano. I've couldn't reproduce the crash but I verified that Continue button is not shown when the sites are being fetched from API. 

I've left one comment about adding unit test.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt (hunk 1 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt:145]: I couldn't handle it. I added a fake delay to `repository.fetchWooCommerceSites()` but I'm unable to observe the view state before `repository.fetchWooCommerceSites()` runs. I'm merging this since the code freeze is approaching, and I will continue investigating this unit test afterward.
