### PR TITLE
Fix/12470 display click through rate correctly

### LINKED ISSUE #12470: Bugfix: Switch the order in which impressions and clicks are displayed for Blaze campaigns.
We currently updated the UI for Blaze campaigns to display the click-though rate [here](https://github.com/woocommerce/woocommerce-android/issues/12389). However, in that liked PR I applied some changes coming from feedback suggestions. In those changes I accidentally introduced a bug: https://github.com/woocommerce/woocommerce-android/pull/12433/commits/ee27a142b1c15ed3a74b31ad0b420752e7897997 and now clicks are displayed before impressions, when it should be the other way around:

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #12470

### Description

We currently updated the UI for Blaze campaigns to display the click-though rate [here](https://github.com/woocommerce/woocommerce-android/issues/12389). However, in that liked PR I applied some changes coming from feedback suggestions. In those changes I accidentally introduced a bug: https://github.com/woocommerce/woocommerce-android/pull/12433/commits/ee27a142b1c15ed3a74b31ad0b420752e7897997 and now clicks are displayed before impressions, when it should be the other way around: 

  
  

### Testing information

1. Check the campaign list and verify that impressions are displayed before clicks in the Click through column

If you don't have any campaign with non-zero impressions and clicks, you have 2 options: 
- Trust the change works, as it is super straightforward and clear. And trust I tested it and works. 
- Ask me and I can invite you to a site with Blaze campaigns with non zero values. 

### The tests that have been performed

Loaded Blaze campaigns and checked that the stats are displayed correctly. 

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

12470

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/233">20.2 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt [hunk 1]
```diff
@@ -75,8 +75,8 @@ fun BlazeCampaignItem(
                         statName = stringResource(R.string.blaze_campaign_status_ctr_label),
                         statValue = stringResource(
                             id = R.string.blaze_campaign_status_ctr_valur,
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt]: There is a typo in `blaze_campaign_status_ctr_valur`; it should be `_value`. I’m not merging it in case you want to fix it here.

**Review by irfano — APPROVED** [review]
Thank you for fixing this! Looks good to me. I’m approving. I added a comment, but it’s just a typo. If this needs to be merged for release, anyone can go ahead and merge it.
