### PR TITLE
[Woo POS] Fix for broken Home screen state after Activity death.

### LINKED ISSUE #12027: [Woo POS] Flow broken when Activity dies
**Describe the bug**
When the user is located on the product selection screen, they put the app into the background and the activity dies, the recreated state doesn't have `checkout` button (it seems to be in the checkout stage even though the rest of the screen is still in the product selection stage).
**To Reproduce**
1. Enable 'Don't keep activities' in dev settings
2. Open POS
3. Select a product
4. Put the app into the background
5. Bring it back to the front
6. Notice "Checkout button" is missing and the cart has "back" arrow.

**Screenshots**
image

**Expected behavior**
The state should be identical even after recreation - teh checkout button should be visible and back arrow on the cart should be hidden.

### PR DESCRIPTION
**Pull request by samiuelson**
Fix for broken Home screen state after Activity death.

Closes: #12027

### Description

This PR fixes the way the state is recreated after Activity is recreated. 
* View models are now storing the state using SavedStateBundle.
* `HomeViewModel` ignores Products pane state events if Products pane is not currently visible (in the Checkout state). Previously it was wrongly modifying the Cart pane state.

### Steps to reproduce

On `trunk`:
1. Enable 'Don't keep activities' in dev settings
2. Open POS
3. Select a product
4. Click check out
5. Put the app into the background
6. Bring it back to the front
7. Notice "Checkout button" is missing and the cart has "back" arrow.

### Testing information

Verify that the Home screen is in the correct state after returning back to the app.

### Images/gif

|Before|After|
|---|---|
||Screenshot_20240801_152148|

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt [hunk 1]
```diff
@@ -25,11 +27,17 @@ class WooPosProductsViewModel @Inject constructor(
...
     private val fromChildToParentEventSender: WooPosChildrenToParentEventSender,
     private val priceFormat: WooPosFormatPrice,
-    private val preferencesRepository: WooPosPreferencesRepository
+    private val preferencesRepository: WooPosPreferencesRepository,
+    savedStateHandle: SavedStateHandle,
 ) : ViewModel() {
     private var loadMoreProductsJob: Job? = null
 
-    private val _viewState = MutableStateFlow<WooPosProductsViewState>(WooPosProductsViewState.Loading())
+    private val _viewState: MutableStateFlow<WooPosProductsViewState> = savedStateHandle.getStateFlow(
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt]: ⚠️ Saving complete ViewState into the Bundle can lead to TransactionTooLarge crashes, affect performance, and is in general discouraged ([more context here](https://github.com/woocommerce/woocommerce-android/pull/12105)). Have you considered recreating it after the process death instead of storing it?

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt]: Good point @malinajirka, restoring of the products pane state is not necessary.

I reverted storing of the Products state in fe5b44c73f9ed44b4a781234e8246f0a64f4f7b1 and 80d918104d27d30918bfd21814b8973d404fb709.

We still store `WooPosCartState` in Bundle which can potentially exhaust capacity of Bundle though. I'd personally improve this (e.g. write the cart's state into DB) later in the next iterations. Let me know what you think!

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt]: Thanks @samiuelson !

> We still store WooPosCartState in Bundle which can potentially exhaust capacity of Bundle though. I'd personally improve this (e.g. write the cart's state into DB) later in the next iterations. Let me know what you think!

I think we might want to consider storing only product-ids instead of storing the complete state. 

I'm fine if we improve it later on, however, I'm slightly worried these types of changes are often forgotten and overall lead to a lower quality of the codebase. 

Having said that, as long as we at least record an issue with a proposal on how to iterate on it, it's fine with me.

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewModel.kt]: I added the [issue](https://github.com/woocommerce/woocommerce-android/issues/12209) to the project board.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt [hunk 2]
```diff
@@ -129,6 +133,7 @@ class WooPosHomeViewModel @Inject constructor(
     }
 
     private fun handleProductsStatusChanged(event: ChildToParentEvent.ProductsStatusChanged) {
+        if (state.value.screenPositionState is WooPosHomeState.ScreenPositionState.Checkout) return
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt]: Tbh I'm not sure I follow this code, I'm wondering if comments or refactoring might help here. To me it seems, we are handling `Checkout.NotPaid` and `Checkout.Paid` states in the `when` condition below, but we are exiting the method just above it and ignoring these states. Wdyt?

What is also a bit confusing is that it seems we use `_state` and `state` interchangeably, is that intentional?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt [hunk 3]
```diff
@@ -32,10 +30,9 @@ sealed class WooPosProductsViewState(
         WooPosProductsViewState(reloadingProductsWithPullToRefresh)
 }
 
-@Parcelize
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt:35]: Is this change intentional?

**Review by malinajirka — COMMENTED** [review]
Thanks for working on this @samiuelson !

I've left a couple questions in the in-code comments. I'm also wondering whether you considered adding unit tests for this scenario - I'm not sure if it's feasible/worth it, but I was wondering if you gave it a though.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt (hunk 3 above)
Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/products/WooPosProductsViewState.kt:35]: Yes. AFAICS, implementing `Parcelable` by `WooPosProductsListItem` is redundant, because it's not serialized and stored into `Bundle` anywhere.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt (hunk 2 above)
Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt]: I cleaned up the code in ffd17b6ee3f79c66b0e7d2351ea8e8bd014cfced. I believe the method is more readable now. It should result in the same effect though. 

In addition to that I added a test case (44b8c7934cf1b962f0c652726af55a99d41fb9ed) to document the intended behavior – when Products status is changed, in case Home screen is at the Checkout position, screen position state should not be modified. 

Let me know if you feel additional comment to the method is still nice to have.

**Comment by samiuelson** [comment]
> Thanks for working on this @samiuelson !
> 
> I've left a couple questions in the in-code comments. I'm also wondering whether you considered adding unit tests for this scenario - I'm not sure if it's feasible/worth it, but I was wondering if you gave it a though.

Thank you for review, @malinajirka 🙌🏼 

I addressed your comments. Since you reported the code is confusing I improved its style and added the test method for the sake of making its intent explicit. Let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt [hunk 4]
```diff
@@ -129,17 +133,23 @@ class WooPosHomeViewModel @Inject constructor(
     }
 
     private fun handleProductsStatusChanged(event: ChildToParentEvent.ProductsStatusChanged) {
+        val screenPosition = _state.value.screenPositionState
         val newScreenPositionState = when (event) {
-            ChildToParentEvent.ProductsStatusChanged.FullScreen -> WooPosHomeState.ScreenPositionState.Cart.Hidden
+            ChildToParentEvent.ProductsStatusChanged.FullScreen -> {
+                when (screenPosition) {
+                    is WooPosHomeState.ScreenPositionState.Cart -> WooPosHomeState.ScreenPositionState.Cart.Hidden
+                    is WooPosHomeState.ScreenPositionState.Checkout -> screenPosition
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModel.kt:141]: In case the Home screen is at the Checkout position, we don't want to change it in the event of the Products VM being recreated after activity death, emitting the `ChildToParentEvent.ProductsStatusChanged` event.

**Comment by malinajirka** [comment]
Thanks for working on this @samiuelson and thank you for the changes! The code looks great to me! 🙇 


It seems it fixes the original issue, but most of the times when the activity gets recreated the `cart` is greyed out for some reason - clicking on the items still works, but it looks like if it was disabled - Emulator API 33 and OnePlus API 34.


Screenshot_1723145480

**Comment by samiuelson** [comment]
> It seems it fixes the original issue, but most of the times when the activity gets recreated the `cart` is greyed out for some reason - clicking on the items still works, but it looks like if it was disabled - Emulator API 33 and OnePlus API 34.

Thanks, @malinajirka for a thorough check—good catch 🙇🏼  I believe the best solution is to move control over the Cart overlay's opacity from Home to Cart because Home doesn't really know if the Cart is empty or not. Fixed in this commit - 3297e5c

Let me know what you think!

**Review by malinajirka — APPROVED** [review]
LGTM, thanks @samiuelson !
