### PR TITLE
[Better Tablet Products] Fix blaze opening crash in the 2 pane layout. Fix bottom sheet height on tablets

### LINKED ISSUE #10874: [Better Tablet Products] Fix blaze opening crash in the 2 pane layout

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10874
Closes: #[10890](https://github.com/woocommerce/woocommerce-android/issues/10890)

### Description

The PR fixes:
* Crash on tablets when "promote with blze" clocked
* Height of the bottom sheet of the new product creation flow

### Testing instructions

* With FF ON open products
* Click on a product => promote with blaze
* Notice that it's open
* Click on FAB -> manual -> notice that bottom sheet properly visible

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/b3c69de7-d647-4761-ae28-cba2259ee8f3

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/196">17.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCBottomSheetDialogFragment.kt [hunk 1]
```diff
@@ -41,11 +39,7 @@ open class WCBottomSheetDialogFragment : BottomSheetDialogFragment {
             dialog?.setOnShowListener {
                 val dialog = it as BottomSheetDialog
                 dialog.findViewById<View>(org.wordpress.aztec.R.id.design_bottom_sheet)?.let { sheet ->
-                    dialog.behavior.peekHeight = if (DisplayUtils.isXLargeTablet(requireContext())) {
-                        sheet.height
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCBottomSheetDialogFragment.kt:45]: When the bottom sheet contains recyclerview then height is calculated without it. As we set peek height here I think the simple and yet effective approach would be just to limit it to the half of the screen height on the tablets

**Comment by backwardstruck** [comment]
Code change looks fine. I don't see the option to Blaze my products though...

**Comment by kidinov** [comment]
@backwardstruck I invited you to the store I used for testing

**Review by backwardstruck — APPROVED** [review]
Able to reproduce the crash on `trunk`. 

Tested:

Screenshot_20240301_141316
