### PR TITLE
Fix order status on creation flow

### LINKED ISSUE #7394: Order Creation: Custom status is used during the sync
**Describe the bug**

During order creation process order is created on backend to calculate taxes and totals. To prevent this "temp" data appearing to user, we hide it with `auto-draft`.
I noticed that the behavior is correct when the status is "Pending payment" (default one). But when I change it to "Processing" it immediately applied and I got notification on different device about new order for a taxes sync operation.
Creation flow should wait final creation step to apply custom status. All intermediate steps should use "auto-draft".

**To Reproduce**

0. Prepare 2 separate devices/simulators. Or observe order status from wp-admin.
1. Start order creation.
2. Add some products and custom shipping line to trigger sync.
3. On 2nd device: notice that there is no notification or order in the list.
4. Update status to anything else ("Processing" for example).
5. Update shipping line to trigger sync.
6. On 2nd device: receive notification about new order + see it in the list of orders with selected custom status.

**Screenshots**

Android | iOS
--|--
|

**Expected behavior**
Step 6 shouldn't happen.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Android Emulator
- Android version: 12.0
- WooCommerce Android version: 10.3-rc-1

**WordPress Environment**
<details>
WP 6.0.2, WC 6.9.1, Jetpack 11.4-a.3.
</details>

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #7394

### Description
When the order is on creation flow, a draft order is created on the backend to calculate the taxes and product totals. To prevent this draft order is displayed to the user, we hide it under the `auto-draft` status, indicating that this order is under creation. If during the order creation process, we update the order status and then one of the price modifiers (fee, shipping, or products), the backend will change the auto-draft status for the new one, showing the draft order if the app is opened on a different device. To solve this issue, the current PR always maintains the auto-draft/pending status on requests updating the order's draft price modifiers (requests of the order creation flow).

### Testing instructions
TC1

1. Prepare 2 separate devices/simulators. Or observe order status from wp-admin.
2. Start order creation.
3. Add some products and custom shipping line to trigger sync.
4. On 2nd device: notice that there is no notification or order in the list.
5. Update status to anything else ("Processing" for example).
6. Update shipping line to trigger sync.
7. On 2nd device: notice that there is no notification or order in the list.

TC2

1. Open orders list
2. Select an order
3. Tap on EDIT
4. Tap on the pencil icon in the order status
5. Change the order status and press APPLY
6. Press DONE
7. Check that the order status is updated to the status selected

### Images/gif

https://user-images.githubusercontent.com/18119390/191113415-d38ee1f0-2f95-4d33-a447-6013203883ab.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt [hunk 1]
```diff
@@ -154,20 +148,29 @@ class OrderCreateEditRepository @Inject constructor(
...
+        isAutoDraftSupported?.let { return it }
         val version = withContext(dispatchers.io) {
             wooCommerceStore.getSitePlugin(selectedSite.get(), WooCommerceStore.WooPlugin.WOO_CORE)?.version
                 ?: "0.0"
         }
-        return version.semverCompareTo(AUTO_DRAFT_SUPPORTED_VERSION) >= 0
+        val isSupported = version.semverCompareTo(AUTO_DRAFT_SUPPORTED_VERSION) >= 0
+        isAutoDraftSupported = isSupported
+        return isSupported
     }
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt:161]: In the previous version, we were requesting this data from the DB on every order change. With this update, we will save the result in memory and query the DB only when needed.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt [hunk 2]
```diff
@@ -154,20 +148,29 @@ class OrderCreateEditRepository @Inject constructor(
...
     private suspend fun Order.Status.toDataModel(): WCOrderStatusModel {
         val key = this.value
-        return withContext(dispatchers.io) {
-            // Currently this query will run on the current thread, so forcing the usage of IO dispatcher
-            orderStore.getOrderStatusForSiteAndKey(selectedSite.get(), key)
-                ?: WCOrderStatusModel(statusKey = key).apply { label = key }
+        return when {
+            key == AUTO_DRAFT && isAutoDraftSupported() -> WCOrderStatusModel(AUTO_DRAFT)
+            // If AUTO_DRAFT is not supported, use PENDING state
+            key == AUTO_DRAFT && isAutoDraftSupported().not() -> WCOrderStatusModel(CoreOrderStatus.PENDING.value)
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditRepository.kt:168]: If `auto-draft` is not supported, we should use the `pending` status.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 3]
```diff
@@ -370,7 +372,15 @@ class OrderCreateEditViewModel @Inject constructor(
...
         viewModelScope.launch {
-            val changes = if (mode is Mode.Edit) _orderDraft.drop(1) else _orderDraft
+            val changes =
+                if (mode is Mode.Edit) {
+                    _orderDraft.drop(1)
+                } else {
+                    // When we are in the order creation flow, we need to keep the order status as auto-draft.
+                    // In this way, when the draft of the created order needs to synchronize the price modifiers,
+                    // the application does not send notifications or synchronize its status on other devices.
+                    _orderDraft.map { order -> order.copy(status = orderCreationStatus) }
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt:382]: Do we need to check if auto draft is supported here?

Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt:382]: >Do we need to check if auto draft is supported here?

I believe we are fine leaving the specifics of managing API-supported versions only on the repository (OrderCreateEditRepository`), that is the class responsible for making the request. This view model is bigger than others because it handles the interaction with two flows (creation/editing), so I will vote to keep it as small as possible. WDYT?

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:
