### PR TITLE
Perform mark complete swipe action

### LINKED ISSUE #7035: [Bulk Order Actions] Perform Mark To Complete action
# Description

When the user triggers the "Mark as Completed" action we need to perform that action remotely

# Task

- [x] Fire the mark as completed request when the users triggers the  "Mark as Completed" action.
- [x] Optimistically update the order to the complete status
- [x] Revert to the initial status in case of any error

### LINKED ISSUE #7036: [Bulk Order Actions] Present  Notices
# Description

After the "Mark as Completed" action has been triggered we need to properly inform the user about it.

# Tasks

- [x] Show success notice with an **Undo action** after the order has been marked successfuly.
- [x] Show error notice with a "Retry action"after whe order fails to update.

**Success Message:** `Order #1234 marked as completed`
**Error Message:** `Error updating Order #1234`

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #7035
Closes: #7036

‼️ PR depends on [this fix](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2475) on FluxC

### Description
This PR updates the order's status when you swipe the order to the left. With these changes, the app retrieves the order id, position, and current status to the ViewModel once the Order item is swiped. With this information, the ViewModel optimistically changes the order status locally to _completed_, shows a message indicating the change to the merchant (with an undo action), and performs a request on the API to update the status. 
If the request fails, it displays a retry SnackBar to the merchant so he can retry the action. 
If the merchant presses the undo action, the order status changes to the previous status.

The Add (+) FAB button should be a direct child of a CoordinatorLayout to let the layout handles the coordinated animation when the SnackBar is shown, but I will create a different issue for this fix because is out of the scope of this PR.

### Testing instructions
TC1 
1. Open orders
2. Swipe a non-completed order
3. Check that the order changes status to completed 
4. Check that the app shows "Order #OrderId marked as completed"
5. Press undo in the snack bar
6. Check that the order updates the status to the status before

TC2 
1. Open orders
2. Turn on airplane mode
3. Swipe a non-completed order
4. Check that the order maintains the current status
5. Check that an error message is displayed

TC3
Run [OrderListViewModelTest](https://github.com/woocommerce/woocommerce-android/blob/4ab2eca382af369b0af915b82160496c8a278915/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/OrderListViewModelTest.kt)

#### Swipe-To Complete success

https://user-images.githubusercontent.com/18119390/182223840-8e497973-358b-4daf-b2a0-e0a0746c8256.mp4

#### Swipe-To Complete fail

https://user-images.githubusercontent.com/18119390/182223885-8f9dd4c5-c3ca-4913-a536-2a93e222b71c.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+sealed class OrderStatusUpdateSource(open val oldStatus: String, open val newStatus: String) : Parcelable {
+    @Parcelize
+    data class SwipeGesture(
+        val orderId: Long,
+        val orderPosition: Int,
+        override val oldStatus: String
+    ) : OrderStatusUpdateSource(
+        oldStatus = oldStatus,
+        newStatus = CoreOrderStatus.COMPLETED.value
```
Comment (Ecarrion) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt:15]: I'm not sure if I understand this correctly 😅 
But are we passing the new status as a parameter but not using it and assigning always the `Completed` status?

**Review by Ecarrion — COMMENTED** [review]
Hey @atorresveiga all tests were good except that I couldn't make the error snack bar to be shown. Could that be because I did the test in the simulator?

@ThomazFB Alejandro mentioned that the changes were big and suggested to leave the actual code review to you!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt (hunk 1 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt:15]: Hi @Ecarrion! I understand your confusion, and that is why I will rename the SwipeGesture -> SwipeToCompleteGesture to make it more evident what is the class's main responsibility.

>But are we passing the new status as a parameter but not using it and assigning always the Completed status?

This is because `SwipeGesture` (that will become SwipeToCompleteGesture in no time) inherits from [OrderStatusUpdateSource](https://github.com/woocommerce/woocommerce-android/blob/5f3d64555b9be863f72fc0eb7cdde2404afc5495/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt), which is a sealed class we use in the code to identify the source from where we are updating the order status. This `OrderStatusUpdateSource` always receives 2 value properties, `oldStatus` and `newStatus`, that are useful to implement functions as the `undo` when the status updates successfully.
Here in the code, what it was trying to express is that the source of the order status change was a SwipeGesture and as this gesture was only meant to complete the order, as also happened to be the case of FullFillScreen (another update status source). I hope that helps 😁

Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt:15]: >all tests were good except that I couldn't make the error snack bar to be shown

That's weird 🤔. Here tried the changes in a Pixel 5 emulator turning airplane mode on, and I could see the error message. Could you walk me through the steps you are following for this test?

[emulator.webm](https://user-images.githubusercontent.com/18119390/182604587-04ce4d33-1dce-43cb-9344-cc7cef1066d2.webm)

Comment (Ecarrion) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderStatusUpdateSource.kt:15]: Not sure what happened before but I can't reproduce it now, so I guess we are good!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 2]
```diff
@@ -488,13 +493,109 @@ class OrderListViewModel @Inject constructor(
...
+                        message = resourceProvider.getString(
+                            R.string.orderlist_updating_order_error,
+                            gestureSource.orderId
+                        ),
+                        retry = { onSwipeStatusUpdate(gestureSource) }
+                    )
+                )
+            }
+        )
+    }
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt]: This function as it is is a little bit hard to read since there's a lot going on, do you think it would benefit with a code extraction at least on the success and fail implementations?

**Review by ThomazFB — APPROVED** [review]
The feature is working nicely. I've managed to reproduce both scenarios without issues. I've left just one suggestion on extracting some parts to make the readability a bit better, but overall, LGTM! 

I'm leaving this PR just approved so you can choose when to merge the FluxC part that this PR depends on.
