### PR TITLE
[In Person Payments] Transactions below minimal amount,  error message is missing

### LINKED ISSUE #13110: [IPP] Transactions below minimal amount error message missing
### Problem

- [ ] In case of payment amount below minimal allowed amount (e.g. $0.20) payment fails but we don't get a dedicated error message. Instead we show generic "Sorry, this payment couldn't be processed"

Goal - investigate if this is a backend or app issue.

- [ ] In case of payment amount below minimal allowed amount (e.g. $0.20) payment fails the first time. However, it succeeds during the second attempt. 

Goal - investigate if this is correct

### Context
The issue was discovered when testing failed payment state in POS: https://github.com/woocommerce/woocommerce-android/pull/13057#issuecomment-2536542389

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #13110

### Description

The PR implements the changes brought by WooPayments - now we have the data in the error response when the amount is too small and we can use this data to display correct error message to the users

Also, as for the case of Stripe plugin, we keep getting error during intent creation, this PR handles it

https://github.com/Automattic/woocommerce-payments/pull/10112

### Steps to reproduce

For both WooPayments and Stripe plugins installed on a site:
* Create an order < 50 cents in the states
* Try to collect it using a card reader (can be emulated)
* Notice error that is clear about what happened

### The tests that have been performed

Above

### Images/gif

https://github.com/user-attachments/assets/48d0e97e-3c51-4f8b-875a-b9aa8e62fe37

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/253">22.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt [hunk 1]
```diff
@@ -64,23 +66,26 @@ class CardReaderPaymentErrorMapper @Inject constructor(
...
-            resources.getString(R.string.card_reader_payment_failed_amount_too_small)
-                .format(minChargeAmountString)
+        val message = resources.getString(R.string.card_reader_payment_failed_amount_too_small)
+            .format(minChargeAmountString)
 
         return PaymentFlowError.AmountTooSmall(UiStringText(message))
     }
+
+    private fun generateAmountToSmallErrorFor(data: AmountTooSmallStripe): PaymentFlowError.AmountTooSmall {
+        return PaymentFlowError.AmountTooSmall(UiStringText(data.message))
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/payment/CardReaderPaymentErrorMapper.kt:89]: So, we have two options for the stripe case:
* Use the error message the stripe API returns us -> it won't be localized
* Use the hardcoded amount in the code to construct the message -> localized, but if the amount changes, it will be incorrect

Both are not ideal, but one doesn't require maintenance on our side, so I am going with 1 here

**Comment by kidinov** [comment]
@coderabbitai review

**Review by malinajirka — APPROVED** [review]
LGTM, thanks for working on this!
