### PR TITLE
Hide the shipment tracking if the order has only virtual products

### LINKED ISSUE #3255: Hide shipment tracking for virtual products
The shipment tracking section is being displayed for orders with virtual products: https://href.li/?https://d.pr/i/VyqBNl
It seems like a regression from #1233

### PR DESCRIPTION
**Pull request by hichamboushaba**
Fixes #3255 

The change is to make sure that the shipment tracking section is hidden if the order has only virtual products.

**Testing**
1. Create an order that has only virtual products.
2. Open the order details.
3. Confirm that the shipment tracking section is not displayed.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt [hunk 1]
```diff
@@ -193,7 +193,8 @@ class OrderDetailViewModel @AssistedInject constructor(
     fun hasVirtualProductsOnly(): Boolean {
         return if (order.items.isNotEmpty()) {
             val remoteProductIds = order.items.map { it.productId }
-            orderDetailRepository.getProductsByRemoteIds(remoteProductIds).all { it.virtual }
+            val products = orderDetailRepository.getProductsByRemoteIds(remoteProductIds)
+            products.isNotEmpty() && products.all { it.virtual }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt:197]: I did this change to align with the fact that we return `false` if the items list is empty, it was needed to fix the tests.

**Review by nbradbury — APPROVED** [review]
Fix is good! :shipit:
