### PR TITLE
Check for FCM token presence

### LINKED ISSUE #4600: RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
Sentry Issue: [WOOCOMMERCE-ANDROID-232](https://sentry.io/organizations/a8c/issues/2568275125/?referrer=github_integration)

```
IOException: SERVICE_NOT_AVAILABLE
    at com.google.firebase.iid.GmsRpc.handleResponse(com.google.firebase:firebase-iid@@21.0.0:84)
    at com.google.firebase.iid.GmsRpc.lambda$extractResponseWhenComplete$0$GmsRpc(com.google.firebase:firebase-iid@@21.0.0:94)
    at com.google.firebase.iid.GmsRpc$$Lambda$0.then
    at com.google.android.gms.tasks.zzd.run
    at com.google.firebase.iid.FirebaseIidExecutors$$Lambda$0.execute
...
(19 additional frame(s) were not displayed)

RuntimeExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
    at com.woocommerce.android.push.FCMRegistrationIntentService$onHandleWork$1.onComplete(FCMRegistrationIntentService.kt:29)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #4600

### Description

This PR adds a check for success of reciving FCM token. If token has not been received, don't crash the app and send report to Sentry.

#### Make sure you can reproduce the original issue
1. Check-out `release/7.3` branch
1. Go to `build.gradle` 
1. Comment lines `393-404` (those responsible for using shared debug key). This will make Google Cloud Messaging to return error `403`
1. Install `vanillaDebug` variant on the device (just to force error from Google Cloud Messaging, not to test `vanillaDebug` itself)
1. Run the app
1. Assert the app crashed

#### Check fix
1. Check-out `fix/crashing_on_reciving_firebase_notif_error` branch
1. Repeat steps 2-5 from above
1. Assert the app did not crash

#### Test devices without Google Play Services:

App won't crash on devices without Google Play Services, Firebase checks automatically for that earlier in the lifecycle and logs `Google Play services missing or without correct permission.`.

You can check that by installing this PR on emulator (without Google Play Services).

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt [hunk 1]
```diff
@@ -24,22 +27,23 @@ class FCMRegistrationIntentService : JobIntentService() {
...
-                    notificationRegistrationHandler.onNewFCMTokenReceived(it)
-                } ?: run {
-                    WooLog.w(WooLog.T.NOTIFS, "Empty FCM token, can't register the id on remote services")
-                    notificationRegistrationHandler.onEmptyFCMTokenReceived()
-                }
+        FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
+            if (!task.isSuccessful) {
+                val message = "Fetching FCM registration token failed"
+                WooLog.e(WooLog.T.NOTIFS, message, task.exception)
+                crashLogging.sendReport(task.exception, message = message)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt]: I noticed that we hit this line even when the device is offline, with the error `SERVICE_NOT_AVAILABLE`, WDYT about filtering this error out to avoid spamming Sentry with it?

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt]: I agree - offline device is a good case to filter out 👍 . 

I've checked what happens when device doesn't have Google Play Services for this very reason but we don't reach `onComplete` in such case.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt [hunk 2]
```diff
@@ -24,22 +28,28 @@ class FCMRegistrationIntentService : JobIntentService() {
...
-                    WooLog.w(WooLog.T.NOTIFS, "Empty FCM token, can't register the id on remote services")
-                    notificationRegistrationHandler.onEmptyFCMTokenReceived()
+        FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
+            if (!task.isSuccessful) {
+                val message = "Fetching FCM registration token failed"
+                val exception = task.exception
+                WooLog.e(WooLog.T.NOTIFS, message, exception)
+
+                if (NetworkUtils.isNetworkAvailable(this)) {
+                    crashLogging.sendReport(exception = exception, message = message)
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt]: I wonder though what should we do as the exception is `java.io.IOException` with message `SERVICE_NOT_AVAILABLE`:
1. should we check for this message or
2. should we check for internet connection with `NetworkUtils#isNetworkAvailable`

I'm afraid that the first one will shadow some of the other issues as it's quite generic, that's why I suggested 2 option but I'm not totally convinced to it too. WDYT @hichamboushaba ?

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt]: Personally I would filter all `SERVICE_NOT_AVAILABLE`, because even if the device is not offline, the error makes it seem like the device couldn't reach the servers, and even if they are down, we don't need the error in Sentry for them.

But it's just my opinion, `NetworkUtils#isNetworkAvailable` is a good filter too for most cases.

**Review by hichamboushaba — APPROVED** [review]
Thanks for working on this @wzieba, it works as expected.

I'm approving, and I'll leave it for you to decide whether to keep filtering using `NetworkUtils#isNetworkAvailable` or to use `SERVICE_NOT_AVAILABLE`.
Feel free to merge this.

**Comment by hichamboushaba** [comment]
FYI I created an issue https://github.com/woocommerce/woocommerce-android/issues/4600, and linked it to this PR.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt (hunk 2 above)
Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/FCMRegistrationIntentService.kt]: > the error makes it seem like the device couldn't reach the servers, and even if they are down, we don't need the error in Sentry for them.

On second thought, that's totally reasonable. I'll filter out by `SERVICE_NOT_AVAILABLE`, thanks!
