### PR TITLE
Fix the end sale date button removal

### LINKED ISSUE #2247: Products M1 release: remove end date option is displayed when there is no end date
While testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/2231), I noticed that the `Remove end date` option in Product pricing screen is displayed when there is no end date for the sale. I'm pretty sure this was fixed in [this PR](https://github.com/woocommerce/woocommerce-android/pull/2125) so maybe the changes were missed or reverted during dark mode changes 🤷

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #2247.

This PR fixes the `Remove end date` button in the Product pricing screen.

To test:
1. Go to a product detail screen
2. Tap on the Price card
3. Switch on the Schedule sale switch
4. Select a start date & end date
5. Notice the `Remove end date` is visible
6. Tap on the button
7. Notice the end date is gone and the button is hidden

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt [hunk 1]
```diff
@@ -60,8 +60,8 @@ data class Product(
     val numVariations: Int,
     val images: List<Image>,
     val attributes: List<Attribute>,
-    val dateOnSaleToGmt: Date?,
-    val dateOnSaleFromGmt: Date?,
+    val saleEndDateGmt: Date?,
+    val saleStartDateGmt: Date?,
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt:64]: Good call on renaming these 👍
