### PR TITLE
Issue/7299 site credentials mismatch

### LINKED ISSUE #7299: [Login] Redirect to account mismatch error during site credentials when needed
During site credentials login, if these conditions are satisfied:
1. We detect that the site has Jetpack and is connected using the `site-info` endpoint.
2. The XMLRPC response doesn't contain `jetpack_user_email`

Then we need to redirect to the account mismatch error.

The current behavior is incorrect as we show the "Jetpack Required" error.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #7299 

### Description
This PR fixes the above issue by making sure we show the account mismatch screen when connecting using site-credentials to a site that has Jetpack connected to a different account.

The message was updated to reflect that it's not an account mismatch per se, but it's the fact that the used credentials are for an account that's not connected to Jetpack.
The screen doesn't allow much now, but it will be improved in upcoming PRs, and it's still better than the misleading "Jetpack Required" screen that we were using before.

### Testing instructions
1. Prepare a site that has two accounts, where one of them is connected to Jetpack.
2. Open the app, and sign in using the site address.
3. Use site credentials for login, and enter credentials of the non-connected account.
4. Confirm the app shows the correct error screen.

### Images/gif

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt [hunk 1]
```diff
@@ -18,7 +19,7 @@ class AccountRepository @Inject constructor(
     private val accountStore: AccountStore,
     private val dispatcher: Dispatcher
 ) {
-    fun getUserAccount() = accountStore.account
+    fun getUserAccount(): AccountModel? = accountStore.account.takeIf { it.userId != 0L }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/AccountRepository.kt:22]: The AccountStore adds a default account, and we don't want it to be returned here.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerRepository.kt [hunk 2]
```diff
@@ -29,6 +29,10 @@ class SitePickerRepository @Inject constructor(
     suspend fun getSites() = withContext(Dispatchers.IO) { siteStore.sites }
 
     fun getSiteBySiteUrl(url: String) = SiteUtils.getSiteByMatchingUrl(siteStore, url)
+        .takeIf {
+            // Take only sites returned from the WPCom /me/sites response
+            it?.origin == SiteModel.ORIGIN_WPCOM_REST
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerRepository.kt:34]: When the user signs in using site credentials, we retrieve the site using XMLRPC, then we cache it, but for the site picker, we care only about sites that were returned using the WPCom API /me/sites, as they are the ones we can connect to.

File: WooCommerce/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -229,7 +229,8 @@
     <string name="login_nostores_content_description">No WooCommerce stores</string>
     <string name="login_with_a_different_account">Login with a different account</string>
     <string name="login_no_stores">We didn\'t find WooCommerce stores connected to this account.</string>
-    <string name="login_not_connected_to_account">It looks like %1$s is connected to a different WordPress.com account.</string>
+    <string name="login_wpcom_account_mismatch">It looks like %1$s is connected to a different WordPress.com account.</string>
+    <string name="login_jetpack_not_connected">It looks like your account is not connected to %1$s\'s Jetpack</string>
```
Comment (hafizrahman) [inline WooCommerce/src/main/res/values/strings.xml:233]:
```suggestion
    <string name="login_jetpack_not_connected">Sorry, only the account on %1$s that is connected to the Jetpack plugin is able to manage the store in this app.</string>
```

What do you think about rewording the message this way?

- I think it gives better clarity on what's happening. Instead of only saying the account is not connected to JP, we also explain what it means if the account is connected.
- If the merchant copies the error text and shared it to our support, I think it might help troubleshoot the exact issue better.

Comment (hafizrahman) [reply WooCommerce/src/main/res/values/strings.xml:233]: I also wonder if we can reword the button "Login with another account" to "Login with the connected account" to make the next action be super clear to the merchants.

**Review by hafizrahman — CHANGES_REQUESTED** [review]

File: WooCommerce/src/main/res/values/strings.xml (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/res/values/strings.xml:233]: As I explained on the PR description, this state is temporary, we will be providing a way to connect the account to Jetpack from the app, so the wording you suggested won't work with it (check https://github.com/woocommerce/woocommerce-android/pull/7342).
The "Login with another account" button is a secondary action only if they used the wrong account, but managing the site using the entered account is the primary action, and will be supported soon.

Comment (hichamboushaba) [reply WooCommerce/src/main/res/values/strings.xml:233]: @hafizrahman did you get a chance to check my reply here? 🙏

**Review by hafizrahman — APPROVED** [review]
Thanks for the explanation! :) All good from my end, then.
