### PR TITLE
Fix analytics performance measurements

### LINKED ISSUE #8355: Analytics Hub performance transactions report false results.
**Describe the bug**

The reason for false reports is that the conditions of transactions are marked as executed prematurely. Let's take e.g. fetching data about Orders.

We run `onOrdersFetched` method as soon as `ordersState` is of type `Available` ([here](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubViewModel.kt#L162)) but the `Available` is a state that this `Flow` starts with ([here](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/sync/UpdateAnalyticsHubStats.kt#L31)).

So instead of measuring network communication, we only measure how quickly the device renders a default, empty view.

This ends up with measuring not what we really want to measure - an end to end user experience when opening this screen.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #8355

### Why
We were marking prematurely as executed the conditions of transactions in Analytics Hub because we were taking into account the empty initial state. This results in creating false performance reports.

### Description
This PR solves this issue by dropping the first state that we know is the empty initial state. With this change, we are now taking into account real transactions and measuring the end-to-end user experience when opening the Analytics screen.

### Testing instructions
Check that we are not marking as executed the conditions of transactions in Analytics Hub on the empty initial state

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by wzieba** [comment]
I'm testing this PR, but there's something wrong with Sentry configuration. I'm trying to debug it. @atorresveiga could you please 

1. Uninstall the app
2. ~Apply patch~ edit: it's not even needed
3. Open Flipper
4. Log in (via WPCOM flow)
5. See if after typing password the app crashes with: `Caused by: java.lang.ClassNotFoundException: Didn't find class "io.sentry.android.core.SentryLogcatAdapter"`

If yes, can you do the same test on `trunk` ?

<details><summary>PATCH</summary>

```PATCH
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt	(revision eaaf9aa881553a3fb5957408ce13018a6537a3d5)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/SpecifyPerformanceMonitoringConfig.kt	(date 1685964301031)
@@ -11,13 +11,13 @@
 ) {
 
     private companion object {
-        const val PERFORMANCE_MONITORING_SAMPLE_RATE = 0.01
+        const val PERFORMANCE_MONITORING_SAMPLE_RATE = 1.0
     }
 
     operator fun invoke(): PerformanceMonitoringConfig {
         val userEnabled = analyticsWrapper.sendUsageStats
 
-        return if (!userEnabled || buildConfig.debug) {
+        return if (!userEnabled) {
             PerformanceMonitoringConfig.Disabled
         } else {
             PerformanceMonitoringConfig.Enabled(PERFORMANCE_MONITORING_SAMPLE_RATE)
```
</summary>

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt [hunk 1]
```diff
@@ -443,10 +444,10 @@ class AnalyticsHubViewModelTest : BaseUnitTest() {
 
         sut = givenAViewModel()
 
-        verify(transactionLauncher).onRevenueFetched()
-        verify(transactionLauncher).onOrdersFetched()
-        verify(transactionLauncher).onProductsFetched()
-        verify(transactionLauncher).onSessionFetched()
+        verify(transactionLauncher, times(1)).onRevenueFetched()
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsHubViewModelTest.kt]: WDYT about removing `times(1)` arguments? Citing Mockito documentation on `verify(mock)`

image

I'm afraid that adding `times(1)` might give someone who reads the codebase, that plain `verify(mock)` methods doesn't check for a single invocation, but multiple ones.

**Review by wzieba — APPROVED** [review]
AnalyticsHub transaction seems to be recorded correctly - both http requests are recorded

image

Flipper for comparassion

image

**Comment by wzieba** [comment]
I was testing this change with merge from `trunk` because of the issue we talked on Slack.
