### PR TITLE
[HACK] Fix whats new dialog size on big screens

### LINKED ISSUE #12676: Whats new dialog is too narrow on a tablet
image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12676 

### Description

The PR makes whats new dialog look ok on the bigger screens

### Steps to reproduce

I was using code modification, but naturally, this should be reproducible via updating an older app to a new version
[Simulate_Announcement_pop_up.patch](https://github.com/user-attachments/files/17129430/Simulate_Announcement_pop_up.patch)

### Testing information

* Try different screen sizes in both landscape and portrait orientation
* Notice that it looks ok now

### The tests that have been performed

The once above

### Images/gif

image
image
image
image
image
image

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>FeatureAnnouncementSizeSetupHelper</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/239">20.7</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt [hunk 1]
```diff
@@ -12,15 +14,11 @@ import com.woocommerce.android.R
...
+import javax.inject.Inject
 
 @AndroidEntryPoint
 class FeatureAnnouncementDialogFragment : DialogFragment() {
-    companion object {
-        const val TAG: String = "FeatureAnnouncementDialog"
-        const val TABLET_LANDSCAPE_WIDTH_RATIO = 0.25f
-        const val TABLET_LANDSCAPE_HEIGHT_RATIO = 0.8f
-    }
+    @Inject lateinit var sizeSetup: FeatureAnnouncementSizeSetupHelper
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt:21]: np, I don't think we need to use Dagger to inject these dependencies, since they are used directly inside the dialog, instantiating them directly will have less overhead (here I mean build-time overhead, even if it's negligible for a single dependency, it does add up).

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt [hunk 2]
```diff
@@ -0,0 +1,22 @@
+package com.woocommerce.android.ui.whatsnew
+
+import android.content.Context
+import com.woocommerce.android.ui.woopos.util.ext.getScreenHeightDp
+import com.woocommerce.android.ui.woopos.util.ext.getScreenWidthDp
+import javax.inject.Inject
+import kotlin.math.min
+
+class FeatureAnnouncementDisplayAsDialog @Inject constructor(private val context: Context) {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt:9]: np, why make this a separate class? Personally I think if it was a private function inside `FeatureAnnouncementSizeSetupHelper` it would have been easier to follow as the logic of sizing will be on the same place.

**Review by hichamboushaba — APPROVED** [review]
Nice work @kidinov, it works well in my testing.
I left two np comments, but none is a blocker, so I'm pre-approving, feel free to ignore them if you want.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt (hunk 2 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt:9]: Mainly testability (btw I forgot to add a test, done now - f36b5d5d69a51968c63c54ae15ca4b3d52c3fed6) 

But there are more - separating concerns/encapsulation. This is to decide if to apply dialog while helper is to decide  how to setup the UI for dialog/full screen

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt:21]: That's a good point, but I am not sure if it's a good trade-off. Even now, with this simple dependency graph, it is already:
```
    private val sizeSetup = FeatureAnnouncementSizeSetupHelper(
        displayAsDialog = FeatureAnnouncementDisplayAsDialog(
            context = requireContext()
        )
    )
```

And any change to those will require modifying this code. If those require something to be injected, then we will have to inject it in the dialog first anyway

**Comment by kidinov** [comment]
@hichamboushaba could you also please check those checkmarks?

> Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt:21]: Personally, I still think we shouldn't inject those 🙂, and if the length of the instantiation above is a concern (it's not IMO), then the point below (making `FeatureAnnouncementDisplayAsDialog` as function) would make it better.

Anyway, it's a minor point, let's proceed without it 🙂

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/whatsnew/FeatureAnnouncementDisplayAsDialog.kt:9]: > Mainly testability

You can test it even if it was a function, I'm not sure what I'm missing here.

Anyway, as stated above, both are minor points 🙂
