### PR TITLE
Issue/6339 react to beta switch

### LINKED ISSUE #6339: [Coupons] - Coupons menu item not immediately displayed after turning on from Beta Features
**Describe the bug**
When the Coupon Management feature is turned on for the first time from Beta Features, it does not immediately appear on the hub menu. To make it appear on the hub menu, kill the app and return or wait for ~2 minutes. Also super nit, the Beta feature reads `Coupons Management`, it should be `Coupon Management`

**To Reproduce**
1. Go to Settings > Beta Features
2. Turn on Coupon Management 
3. Go back to the hub menu screen
4. See that the Coupons menu item is not on the hub menu
5. Kill the app and return - Coupons menu item is now on the hub menu

**Screenshots**

https://user-images.githubusercontent.com/17252150/164584751-bf012ee2-9f36-4113-8ae2-5ea1225f3900.mp4

**Expected behavior**
Coupons should appear on the hub menu after turning it on from Beta features.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Oppo Reno6 Z 5G
- Android version: 12
- WooCommerce Android version: Pre-Alpha build - woocommerce-installable-build-pr6318-20b1d27.apk

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #6339

### Description
This PR adds a way to listen to preferences changes using the AppPrefsWrapper, which allows reacting to the changes and refreshing the UI, the goal here is to fix the issue of not refreshing the menu buttons when the coupon toggle is refreshed.

### Testing instructions
1. Make sure "Don't keep activities" is disabled (this was necessary to reproduce the original issue)
2. Go to Settings > Beta Features
3. Turn on Coupon Management
4. Go back to the hub menu screen
5. Confirm the coupons button is visible correctly.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt [hunk 1]
```diff
@@ -117,4 +123,20 @@ class AppPrefsWrapper @Inject constructor() {
...
+            val listener = OnSharedPreferenceChangeListener { _, key ->
+                trySend(key)
+            }
+            AppPrefs.getPreferences().registerOnSharedPreferenceChangeListener(listener)
+
+            awaitClose {
+                AppPrefs.getPreferences().unregisterOnSharedPreferenceChangeListener(listener)
+            }
+        }
+    }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: This couples the listeners to the keys, which are private in most cases (I'm not sure they should be 🤔), but I think it's OK for most cases.

We can also create different versions of the `observeXXX` functions for each preference we want to observe, but IMO it doesn't scale well.

Let me know what you think 🙏.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt [hunk 2]
```diff
@@ -15,33 +14,31 @@ import com.woocommerce.android.analytics.AnalyticsTracker.Companion.VALUE_MORE_M
...
+    unseenReviewsCountHandler: UnseenReviewsCountHandler,
+    private val appPrefsWrapper: AppPrefsWrapper
 ) : ScopedViewModel(savedState) {
     val moreMenuViewState =
         combine(
             unseenReviewsCountHandler.observeUnseenCount(),
-            selectedSite.observe().filterNotNull()
-        ) { count, selectedSite ->
+            selectedSite.observe().filterNotNull(),
+            appPrefsWrapper.observePrefs().filter { it == "IS_COUPONS_ENABLED" }.map {}.onStart { emit(Unit) }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt]: I didn't want to make DeletablePrefKey public (I don't know why they have to be private, but I don't want to go ahead with changing it in this PR), so I'm using the plain String value of the key, I don't like it, but I think it does the job.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt [hunk 3]
```diff
@@ -94,7 +91,7 @@ class MoreMenuViewModel @Inject constructor(
             name
         }
 
-    private fun SiteModel.getSelectedSiteAbsoluteUrl(): String = url.toUri().host ?: ""
+    private fun SiteModel.getSelectedSiteAbsoluteUrl(): String = runCatching { URL(url).host }.getOrDefault("")
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/MoreMenuViewModel.kt:98]: I had to resort to java.net.URL to make the class testable.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt (hunk 1 above)
Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: WDYT about rather using [`DataStore` ](https://developer.android.com/topic/libraries/architecture/datastore), a recommended successor of SharedPreferences with built-in reactiveness? There are a few benefits:

image

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: > We can also create different versions of the observeXXX functions for each preference we want to observe, but IMO it doesn't scale well.

IMO it's a better solution to provide separate `observeXXX` functions. In its current form, ViewModels will have to know the keys of shared preferences which are an implementation detail of the data layer. WDYT?

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: Thanks for chiming in @wzieba .
> WDYT about rather using [DataStore](https://developer.android.com/topic/libraries/architecture/datastore)

This is a bigger project, if the team wants to migrate all the preferences to DataStore then it has to be done as part of a hack week or a separate project, but moving just a unique preference to have observability will just cause more inconsistencies IMO 🙂.

> ViewModels will have to know the keys of shared preferences which are an implementation detail of the data layer

Why do you think the keys are an implementation detail? the preferences are a store of key-value, and IMO the `key` is part of the contract, where how data is saved is the implementation detail.
Exposing the keys won't cause any tight coupling with the implementation of the data layer, we can easily migrate to another `key-value` store like the `DataStore`'s `Preferences` for example.
This reasoning is why I said the remark:
>  I'm not sure they should be 🤔

but if I'm wrong, I'd love to hear your arguments 🙂.

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: > This is a bigger project, if the team wants to migrate all the preferences to DataStore then it has to be done as part of a hack week or a separate project 

Gotcha, I just want to mention that we already use DataStore for saving values for WCTracker so there's a setup for that. I don't think we have to migrate all SharedPreferences at once - I believe we can do this one by one and add new values to DataStore. I think it would be great to start using DataStore 🙂 WDYT?

> Why do you think the keys are an implementation detail?

IMO ViewModel shouldn't know that the data layer uses a key-value strategy (or any other). Let's take e.g. different storage - Firebase Remote Config. If we'll decide to use it at some point (to enable/disable features remotely) and we'll want to re-use the same key as we do for local key-store values. This will end up with defining Firebase Remote Config keys in the presentation/domain layers of the Woo app, which doesn't sound right.

Another argument would be to wonder what if SharedPreferences had a different API. E.g. let's imagine that SharedPrefences use `kapt` for generating getters. Would we still use a key-value strategy? Probably not, we probably would just cover those generated methods via an interface. This would mean that SharedPreferences API indicates our domain implementation and this concludes (to me) that using keys is an implementation detail.

Also, as you say, we will be able to easily migrate to another key-value store, but what about others, non-key-value storage?

That's why I believe keys are private in `AppPrefs` and values are exposed via methods. WDYT?

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: > I don't think we have to migrate all SharedPreferences at once

This is where we have different opinions, I think we should migrate the preferences all at once for consistency, or at least we spend enough time to design the API before the migration.
And personally, I don't think the advantages of DataStore warrants an urgent migration, SharedPreferences when not abused, still does a good job, the issue with it was for apps that used it to store large objects of data, which wasn't what it was designed for.

> IMO ViewModel shouldn't know that the data layer uses a key-value strategy

Thanks so much for the long answer, I truly appreciate it.
While I see your point, I still don't agree with it 😅:
- Most (if not all) preferences frameworks use key-value storage (NSUserDefaults in iOS, localStorage for web...), and this is why even multiplatform frameworks expose a key-value API (for example: https://github.com/florent37/Multiplatform-Preferences), which means exposing the keys doesn't add any coupling to the platform nor the framework.
- Exposing the keys allows some flexible ways for observing changes, you can design your keys in a way that allows grouping them into different categories (prefixes or suffixes), and observe a bulk of them directly.

Still, I decided to remove exposing the keys in this PR, so now the API exposes just a `Flow<Unit>`, and it's up to the client to check which values did change (similar to what `PreferencesDataStore` does), check the commit: cd69710.

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: > This is where we have different opinions, I think we should migrate the preferences all at once for consistency, or at least we spend enough time to design the API before the migration.

I get your point but I think it'll be difficult to do. I think that this migration can be easily done step-by-step instead all at once - the same as we didn't migrate to Kotlin all at once but step by step (starting with writing new classes in Kotlin).

> Most (if not all) preferences frameworks use key-value storage

I understand but I still stand on the point that the data layer shouldn't dictate our API, even if the majority of frameworks use key-value (or our domain/presentation dictate data-specific keys).

> Still, I decided to remove exposing the keys in this PR, so now the API exposes just a Flow<Unit>, and it's up to the client to check which values did change

I see, nice idea! I think it fixes my main concern about exposing keys but I still would vote to move it to some repository to hide it from VM and expose only `observeCouponBetaSwitch` (like `DataStoreTrackerRepository#observeLastSendingDate`).

> While I see your point, I still don't agree with it 😅:

My ego screams 😄 but it's a good thing I believe!

> Thanks so much for the long answer, I truly appreciate it.

Thank you too for the discussion! It gave me more light on how we should/could approach keeping preferences in our app. 🙌

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefsWrapper.kt]: > I get your point but I think it'll be difficult to do

We don't have that many preferences, it shouldn't be that hard, I think it's manageable in a hack week if we decide the advantages of DataStore are worth the migration 🙂.

Thanks again for the discussion @wzieba 🙏

**Comment by hichamboushaba** [comment]
@0nko FYI, I've refactored the logic a bit after the merge to fix the conflicts, as a Repository was added, I moved the logic to it, and this also aligns with Wojtek's opinion above.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepository.kt [hunk 4]
```diff
@@ -25,4 +30,9 @@ class MoreMenuRepository @Inject constructor(
                 wooCommerceStore.getSitePlugin(selectedSite.get(), WOO_CORE)?.version ?: "0.0"
             currentWooCoreVersion.semverCompareTo(INBOX_MINIMUM_SUPPORTED_VERSION) >= 0
         }
+
+    fun observeCouponBetaSwitch() = appPrefsWrapper.observePrefs()
+        .onStart { emit(Unit) }
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/moremenu/domain/MoreMenuRepository.kt:35]: Clever!

**Review by 0nko — APPROVED** [review]
An elegant way to add reactiveness. Nice work! 👍
