### PR TITLE
[Mobile Payments] Simple payments tax calculation total bug fix

### LINKED ISSUE #9825: Simple payments tax calculation bugs
A user reported they are not able to disable taxes when selling using simple payments on Android.

Steps to reproduce:

* Tax rates are defined in wp-admin
* Create simple payment, with the “Charge taxes” toggle disabled
* Click “Take payment” and notice the amount includes taxes

(reproducible in ~80% of cases)

peaMlT-9Q-p2

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #9825

### Description

Simple payments with tax calculations enabled on the backend were showing the wrong amount to be collected on the payment method selection screen. The reason was that we were navigating to the payment method selection screen right after order was updated locally. Locally updated order doesn't update "order total". The PR brings a change that we navigate to the next screen only after order successful updated on the backed and orders total updated locally after that

### Testing instructions

Follow the flow:
* Tax rates are defined in wp-admin
* Create simple payment, with the “Charge taxes” toggle disabled
* Click “Take payment” and notice the amount includes taxes
* Notice that on the payments method selection screen title matches the order's total

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/5083bc5c-769b-4874-a145-221b1fe6cc40

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/simplepayments/SimplePaymentsViewModel.kt [hunk 1]
```diff
@@ -138,41 +137,16 @@ class SimplePaymentsFragmentViewModel @Inject constructor(
...
-                            triggerEvent(ShowTakePaymentScreen)
-                        }
-                    }
-                }
-                is UpdateOrderResult.RemoteUpdateResult -> {
-                    if (result.event.isError) {
-                        AnalyticsTracker.track(
-                            AnalyticsEvent.PAYMENTS_FLOW_FAILED,
-                            mapOf(
-                                AnalyticsTracker.KEY_SOURCE to AnalyticsTracker.VALUE_SIMPLE_PAYMENTS_SOURCE_AMOUNT,
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/simplepayments/SimplePaymentsViewModel.kt:165]: "amount" as `source` was tracked before, which looks like a bug. Fixed that - now "summary" tracked here

**Comment by kidinov** [comment]
@samiuelson please pay attention on the release notes version before merging. If you take this this week, then let me know - I'll move release notes to 15.6

**Review by samiuelson — APPROVED** [review]
LGTM 🙌🏼
