### PR TITLE
Fix MainBottomNavigationView NPE

### LINKED ISSUE #11063: NullPointerException
Sentry Issue: [WOOCOMMERCE-ANDROID-8NP](https://a8c.sentry.io/issues/4672877433/?referrer=github_integration)

```
NullPointerException: None
    at com.woocommerce.android.ui.main.MainBottomNavigationView.onNavigationItemSelected(MainBottomNavigationView.kt:140)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #11063

### Description

The issue was a `NullPointerException` occurring when attempting to use a NavController that might not have been initialized at the time of navigation item selection. This was leading to crashes in the app. The provided fix introduces safe handling of the nullable navController throughout the MainBottomNavigationView class.

There could be another issue that is causing this. I wasn't able to reproduce the issue when using the app. 

### Testing instructions
Smoke test the navigation bar to ensure that it works as expected. 

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
This fix doesnt resolve the underlying issue so I am looking at more logging details to see if I can determine how it is being caused. Any additional insights are appreciated.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt [hunk 1]
```diff
@@ -25,7 +25,7 @@ class MainBottomNavigationView @JvmOverloads constructor(
 ) : BottomNavigationView(context, attrs),
     OnItemSelectedListener,
     OnItemReselectedListener {
-    private lateinit var navController: NavController
+    private var _navController: NavController? = null
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt]: I'm just curious, why do you want to change the name?

Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainBottomNavigationView.kt]: Good catch. I was using this as a backing property and then removed that solution for another idea I had but removed it so I can revert this change.

**Review by samiuelson — APPROVED** [review]
I wasn't able to reproduce the bug. However, this looks like a way to mitigate the impact of the crash.

**Comment by malinajirka** [comment]
@jd-alexander  @samiuelson I might be missing something, but I'm not sure this fix will work. Here is my train of thoughts, please correct me if I'm wrong.

The crash we are seeing is NPE => however, the field this PR changes used to be non-nullable, so it couldn't have failed with NPE, right? IMO it could have crashed with `property not initialized` exception, but that's not what we are seeing in Sentry. 

Moreover, I don't think that can ever happen as we initialize the property in the `init` block and use it on line 53 so it would have either crashed on line 53 or it must have been initialized. (Update: It's actually not Kotlin init block but a custom one, so this paragraph is wrong)

**Comment by malinajirka** [comment]
I'm not sure how it can happen, especially all of this should be on the same thread, but I think this might potentially be relevant.

[The Kotlin documentation says](https://kotlinlang.org/docs/null-safety.html#nullable-types-and-non-nullable-types):


`The only possible causes of an NPE in Kotlin are:.... An uninitialized this available in a constructor is passed and used somewhere (a "leaking this") .... . `


Notice [this line](https://github.com/woocommerce/woocommerce-android/blob/9c2c62f0a91a31531a7642c9f952d098582fd8a3/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L306), we are passing MainActivity (`this`) before the MainActivity is initialized => it crashes in `onNavigationItemSelected` line 140, however, I believe it crashes because it attempts to put non-nullable `listener` on the stack and it's still `null` because `MainActivity` hasn't finished initializing yet.

**Comment by malinajirka** [comment]
Ok, I take the second comment back - I guess it's too late, the code is onCreate not in the constructor, so that part should be fine. This issue is very interesting. I'm quite curious if the fix will work or not.

My new personal bet is that the MenuItem is null -> it comes from Java, so there is no guarantee it's not null (the calling site uses @NonNull annotation, but that's not a guarantee). 

This seems relevant https://issuetracker.google.com/issues/232348785, specifically [this part](https://issuetracker.google.com/issues/232348785#comment13) - Joel mentioned that the logs contain backPressed records. Potentially also [this part](https://issuetracker.google.com/issues/232348785#comment22).

Update: I'm relatively confident that the NPE happens in the library - `navController.currentDestination` is null (this matches the stack trace in Google Play) => however, it seems the issue is caused by our app -> we get the app into a state with an invalid back stack.

**Comment by jd-alexander** [comment]
Thanks for sharing these thoughts @malinajirka I will explore them tomorrow.
