### PR TITLE
[Woo POS] Remove usage of BaseUnitTest that comes from the main app

### LINKED ISSUE #11771: [Woo POS] Consider removing usage of BaseUnitTest that comes from the main app
To be discussed in the POS meeting: https://docs.google.com/document/d/10JKyruY8xHMMTV3RRGlPkVeTh-wiVMtzSaN-lgIN6DU/edit

```[tasklist]
### Tasks
- [x] WooPosRootViewModelTest
- [x] WooPosHomeViewModelTest
- [x] WooPosCartViewModelTest
- [x] WooPosProductsViewModelTest
- [x] WooPosTotalsViewModelTest
```

### LINKED ISSUE #12012: [Woo POS] M2: Testing, remove reflective code used for handling coroutine exceptions
Per [this](https://github.com/woocommerce/woocommerce-android/pull/11976#discussion_r1678080282) discussion:

Remove the reflective code used for handling coroutine exceptions and rely on straightforward coroutine testing practices.

#### Why It's Problematic
1. **Non-Public API Use**

2. **Potentially Masking Real Issues**

#### Long-Term: Fix the Underlying Issues
Rather than relying on this workaround, a more sustainable approach would be to identify and fix the individual tests that are causing issues with coroutine exceptions. This aligns with best practices for writing robust and maintainable test code.
    - Check that all `coroutineScope` blocks are properly managing their exceptions.
    - Ensure all flows and coroutine launches are properly handled and do not leak unhandled exceptions.

### PR DESCRIPTION
**Pull request by backwardstruck**
Closes: #11771

### Description:
Refactor the POS unit tests to remove the dependency on `BaseUnitTest` from the main app.  This new base class encapsulates the setup commonly required in POS unit tests.

This change simplifies the test setup for individual POS unit tests, ensuring better modularity and maintainability. 

### Steps to reproduce:
1. Review the newly introduced `WooPosBaseUnitTest` class.
2. Review the refactored test classes.
3. Ensure that all tests continue to pass. 

### Testing information:
N/A

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/226">19.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosBaseUnitTest.kt [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+         * throw exceptions to fail. Previously test methods that threw exceptions would not prevent
+         * tests from passing, which was a bug in kotlinx.coroutines that has now been fixed. However,
+         * some of our tests are currently failing because of this change.
+         *
+         * See the following issue for more details: https://github.com/Kotlin/kotlinx.coroutines/issues/1205.
+         */
+
+        Class.forName("kotlinx.coroutines.test.TestScopeKt")
+            .getDeclaredMethod("setCatchNonTestRelatedExceptions", Boolean::class.java)
+            .invoke(null, false)
```
Comment (backwardstruck) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosBaseUnitTest.kt]: Not sure if we want to replace this:
https://github.com/woocommerce/woocommerce-android/issues/11771#issuecomment-2221638307

Comment (kidinov) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosBaseUnitTest.kt]: I think we don't need any base class at all for WooPOS tests:

When a specific rule needed for a test e.g. `InstantTaskExecutorRule` we should just apply to a specific test.

We certainly should not have that in here:

```
Class.forName("kotlinx.coroutines.test.TestScopeKt")
            .getDeclaredMethod("setCatchNonTestRelatedExceptions", Boolean::class.java)
            .invoke(null, false)
```

to avoid writing tests that crashes inside of coroutines.

And instead of calling that

```
protected fun testBlocking(block: suspend TestScope.() -> Unit) = runTest(testDispatcher) { block() }
```

We should just call `runTest`

@samiuelson @backwardstruck wdyt about that?

Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosBaseUnitTest.kt]: Thank you for the feedback. I agree that applying specific rules directly in each test class and removing non-idiomatic code will improve the clarity and maintainability of our tests.

### Planned Changes:

1. I will update the test classes to apply rules like `InstantTaskExecutorRule` directly where needed.
2. I will remove the reflective code used for handling coroutine exceptions and rely on straightforward coroutine testing practices.
3. Instead of custom wrapper functions, I will call `runTest` directly in coroutine tests.

Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/WooPosBaseUnitTest.kt]: I was able to remove most of the reflective code. However, some cases still remain that require further attention. I've created a follow-up issue to address these remaining instances:

https://github.com/woocommerce/woocommerce-android/issues/12012

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt [hunk 2]
```diff
@@ -8,20 +9,37 @@ import com.woocommerce.android.ui.woopos.home.ParentToChildrenEvent
...
+
+    private val testDispatcher = UnconfinedTestDispatcher()
+
+    @Rule
+    @JvmField
+    val rule = InstantTaskExecutorRule()
+
+    @Rule
+    @JvmField
+    val coroutinesTestRule = CoroutineTestRule(testDispatcher)
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt]: That's the rule from the main app, as we move from the base unit test, maybe make sense to have our own rule for this in the the POS module

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt [hunk 3]
```diff
@@ -1,18 +1,36 @@
...
 
-@OptIn(ExperimentalCoroutinesApi::class)
-class WooPosHomeViewModelTest : BaseUnitTest() {
+@ExperimentalCoroutinesApi
+@RunWith(MockitoJUnitRunner::class)
+class WooPosHomeViewModelTest {
+
+    init {
+        Class.forName("kotlinx.coroutines.test.TestScopeKt")
+            .getDeclaredMethod("setCatchNonTestRelatedExceptions", Boolean::class.java)
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt]: I think we should just fix the tests, instead of keeping it, otherwise we will keep adding more tests in those classes that crash inside of coroutines, wdyt?

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt (hunk 2 above)
Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModelTest.kt]: Good point.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt (hunk 3 above)
Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/home/WooPosHomeViewModelTest.kt]: Yep. I went ahead and updated those. I was going to do it [later](https://github.com/woocommerce/woocommerce-android/issues/12012) but might as well get it out of the way.

**Comment by backwardstruck** [comment]
FYI @kidinov this has been updated to address your latest suggestion.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+import kotlinx.coroutines.test.TestDispatcher
+import kotlinx.coroutines.test.resetMain
+import kotlinx.coroutines.test.setMain
+import org.junit.rules.TestWatcher
+import org.junit.runner.Description
+
+@ExperimentalCoroutinesApi
+class WooPosCoroutineTestRule(val testDispatcher: TestDispatcher) : TestWatcher() {
+    override fun starting(description: Description?) {
+        super.starting(description)
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt:15]: np: do we need to call super methods?

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.test.TestDispatcher
+import kotlinx.coroutines.test.resetMain
+import kotlinx.coroutines.test.setMain
+import org.junit.rules.TestWatcher
+import org.junit.runner.Description
+
+@ExperimentalCoroutinesApi
+class WooPosCoroutineTestRule(val testDispatcher: TestDispatcher) : TestWatcher() {
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt]: I am wondering if we have a need to pass something except `UnconfinedTestDispatcher` here? If not, maybe to declare it with default param, so no need to create a dispatcher in every test class, wdyt?

`class WooPosCoroutineTestRule(val testDispatcher: TestDispatcher = UnconfinedTestDispatcher())`


```
    @Rule
    @JvmField
    val coroutinesTestRule = WooPosCoroutineTestRule()
```

**Review by kidinov — APPROVED** [review]
LGTM! I Left a couple of minor comments, please take a look. Also there is a conflict to resolve

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt (hunk 4 above)
Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt:15]: It seems that we should even though the tests may pass without it. In other places we are also doing the same, e.g. `CardReaderCoroutineTestRule`

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt (hunk 5 above)
Comment (backwardstruck) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/woopos/util/WooPosCoroutineTestRule.kt]: That was a good idea to use a default parameter for that. [Removed](https://github.com/woocommerce/woocommerce-android/pull/11976/commits/2fdf5a05ec8c4b69b3216b8f0d076636b85225da) quite a few lines.
