### PR TITLE
Order Navigation Nullpointer Logs

### LINKED ISSUE #11063: NullPointerException
Sentry Issue: [WOOCOMMERCE-ANDROID-8NP](https://a8c.sentry.io/issues/4672877433/?referrer=github_integration)

```
NullPointerException: None
    at com.woocommerce.android.ui.main.MainBottomNavigationView.onNavigationItemSelected(MainBottomNavigationView.kt:140)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #11063 

### Description

The objective of this PR is to implement logging to effectively capture how navigation between order details, order lists, and returning to the main activity may operate differently across various devices due to the crash taking place.

However, I'm not entirely sure that the logging I've implemented will facilitate the debugging process. Therefore, I would greatly appreciate it if you could review my work. 

Furthermore, in my attempt to access more detailed information, I resorted to using restricted APIs. This resulted in warnings from the linter, which I chose to suppress. However, this approach is not something I'm entirely comfortable with. I contemplated whether the benefits of obtaining valuable information would justify this method, with the possibility of removing it in future updates. I'm keen to get feedback.

### Testing instructions
1. Navigate to the Order Details on an order. 
2. Press back to the Order List. 
3. Press back to the My Store.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>OrderNavigationLogger</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/204">18.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 1]
```diff
@@ -181,6 +185,7 @@ class OrderListFragment :
                             findNavController().popBackStack()
                         }
                     }
+                    orderNavigationLogger.logBackStack(findNavController(), "After navigating back from OrderList")
```
Comment (jd-alexander) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: I should add a before log here as well. Evaluating the efficacy and need of this to be sure the placement makes sense. If it doesn't I will remove its usage from the Order Details.

Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: I should probably do some logging in Main Activity as well, or the My Store fragment.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+import com.automattic.android.tracks.crashlogging.CrashLogging
+import kotlinx.coroutines.flow.StateFlow
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@Singleton
+class OrderNavigationLogger @Inject constructor(private val crashLogging: CrashLogging) {
+
+    @SuppressLint("RestrictedApi")
+    fun logBackStack(navController: NavController, actionDescription: String) {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt:17]: 💡 We might want to consider wrapping this whole method into `try/catch(Exception)` to ensure we don't end up introducing another crash with a code which sole purpose is to help us identify another crash. Wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+        val backStackEntries: StateFlow<List<NavBackStackEntry>> = navController.currentBackStack
+        val backStackDescriptions = backStackEntries.value.joinToString(separator = ", ") { entry ->
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: ❤️ Nice idea to record the stacktrace!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+            val label = destination.label ?: "No label"
+            val className = destination.javaClass.simpleName
+            "ID=$id, Label=$label, Class=$className"
+        } ?: "No start destination"
+
+        val logMessage = "$actionDescription: NavGraph=${rootGraph?.displayName}, " +
+            "StartDestination={$startDestinationDetails}, " +
+            "BackStackEntries=[$backStackDescriptions]"
+
+        crashLogging.recordEvent(logMessage)
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: ⚠️ I'm a bit worried this might consume our quota in Sentry - AFAIU this will send events from all devices, even those which do not crash. What if we logged it only into the app logs?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt (hunk 1 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: Hmm, this is a tricky one. First thought that came to my mind was that if it crashes during the navigation - nothing will be logged. Perhaps, we could move the log to the beginning of the method and add lightweight logs to all the if-statements, wdyt?

Something like:
```
requireActivity().onBackPressedDispatcher.addCallback(
            this,
            object : OnBackPressedCallback(true) {
                override fun handleOnBackPressed() {
                    orderNavigationLogger.logBackStack(findNavController(), "Before navigating back from OrderList")
                    selectedOrder.selectOrder(-1L)
                    if (requireContext().windowSizeClass != WindowSizeClass.Compact) {
                        WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #1")
                        if (!binding.detailPaneContainer.findNavController().popBackStack()) {
                            WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #2")
                            findNavController().popBackStack()
                        }
                    } else if (isSearching) {
                        WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #3")
                        handleSearchViewCollapse()
                    } else {
                        WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #4")
                        val result =
                            _binding?.detailPaneContainer?.findNavController()?.navigateUp() ?: false
                        val isCompactScreen = requireContext().windowSizeClass == WindowSizeClass.Compact
                        if (!result && _binding?.listPaneContainer?.isVisible != true && isCompactScreen) {
                            WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #5")
                            // There are no more fragments in the back stack, UI used to be a two pane layout (tablet)
                            // and now it's a single pane layout (phone), e.g. due to a configuration change.
                            // In this case we need to switch panes – show the list pane instead of details pane.
                            adjustUiForDeviceType(savedInstanceState)
                        } else {
                            WooLog.d(WooLog.T.ORDERS, "Before navigating back from OrderList: Location #6")
                            findNavController().popBackStack()
                        }
                    }
                   WooLog.d(WooLog.T.ORDERS, "After navigating back from OrderList")
                }
            }
        )
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt [hunk 5]
```diff
@@ -296,11 +300,14 @@ class OrderDetailFragment :
         } else {
             binding.toolbar.navigationIcon = AppCompatResources.getDrawable(requireActivity(), R.drawable.ic_back_24dp)
             binding.toolbar.setNavigationOnClickListener {
+                orderNavigationLogger.logBackStack(findNavController(), "Before navigating back from OrderDetail")
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt]: 📓 I believe this piece of code is invoked only on `up` navigation and isn't invoked on `back` navigation. Wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+        val rootGraph = navController.graph as? NavGraph
+        val startDestination = rootGraph?.findNode(rootGraph.startDestinationId)
+        val startDestinationDetails = startDestination?.let { destination ->
+            val id = destination.id
+            val label = destination.label ?: "No label"
+            val className = destination.javaClass.simpleName
+            "ID=$id, Label=$label, Class=$className"
+        } ?: "No start destination"
+
+        val logMessage = "$actionDescription: NavGraph=${rootGraph?.displayName}, " +
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: 📓 It seems we use `,` as separator for both separating one backstack entry from another as well as separating details of each backstack entry. The result is quite difficult to read: 
`
BackStackEntries=[ID=2131363568, Label=No label, Class=NavGraph, ID=2131362710, Label=fragment_my_store, Class=Destination, ID=2131363727, Label=fragment_order_list, Class=Destination, ID=2131363571, Label=No label, Class=NavGraph, ID=2131363679, Label=No label, Class=Destination]
`

We might want to consider using two different separators to increase readability. Wdyt?

**Review by malinajirka — COMMENTED** [review]
Thanks for working on this @jd-alexander. I've left some comments, let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt (hunk 4 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: I understandable your point of view. I leveraged this approach because I was hoping to only send these events when the crash occurs. This is the description of the method. 

```
    /**
     * Records a breadcrumb during the app lifecycle but doesn't report an event. This basically
     * adds more context for the next reports created and sent by [sendReport] or an unhandled
     * exception report.
     *
     * @param[message] The message to attach to a breadcrumb
     * @param[category] An optional category
     */
    fun recordEvent(
        message: String,
        category: String? = null
    )
```

However, I am not against utilization of the app logs if that works better because I have never used this `recordEvent` before so I am thinking I would also need to throw an exception or something to simulate a report for verification purposes.

Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: I used `WooLog` instead. Thanks for the tip.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt (hunk 2 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt:17]: Agreed!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt (hunk 6 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: I think that would help with readability for sure.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt (hunk 1 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: Good idea!

**Comment by jd-alexander** [comment]
> Thanks for working on this @jd-alexander. I've left some comments, let me know what you think.

Thanks for the feedback on this PR. I am going to address all the changes in totality and request another review soon.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt (hunk 4 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderNavigationLogger.kt]: > I understandable your point of view. I leveraged this approach because I was hoping to only send these events when the crash occurs. This is the description of the method.

Ohh, very good point. Sorry, I missed that. I thought the method with this behavior was called recordBreadcrumb, but it is called recordEvent. In that case, I believe using recordEvent would be fine. Having said that, especially considering we'll remove this code after we fix this bug => let's use what we have in the code right now, which is WooLog.

**Review by malinajirka — APPROVED** [review]
Thanks for implementing the suggestions! LGTM
