### PR TITLE
Design review issues fix

### LINKED ISSUE #1726: Refund by items: design review issues
[This design review](https://github.com/woocommerce/woocommerce-android/pull/1710#pullrequestreview-332730928) from @kyleaparker: originally appeared on #1710 and I was going to take it over, but it turned out to be much more involved than I expected. Given that the holidays & vacation are right around the corner, it was decided that we should merge that master branch into `develop` and hide the "Issue Refund" button behind a feature flag that's only enabled in debug builds. @0nko Can take this over when he returns

------------------------------------------------------

I found a few things that will need to be fixed:

1. After refunding several items, we aren't updating the quantities in the products to fulfil list: 
Screenshot_20191216-120223

In the designs there was separation between items to fulfil and refunded items: 

Refunds   Cancelations 2019-12-16 12-07-07

2. On the refund summary,  under each product title we only need to show the quantity refunded, right now we are showing the total quantity ordered:

Screenshot_20191216-120244

Designs:

Refunds   Cancelations 2019-12-16 12-08-54

3. At one point I was able to click through without having any items selected: 

Screenshot_20191216-115755

4. We need to show the refund method in the "refund via" section: 

Screenshot_20191216-120131

Design: 
Refunds   Cancelations 2019-12-16 12-11-13

5. Related to the above screenshot, we don't need to show the text that automatic refunds are not supported when the payment method is manual (Cash, check, bank deposit). In this example, the payment method is cash on delivery so it should look like this: 

Refunds   Cancelations 2019-12-16 12-13-38

However, if the payment was via a credit card that does not support automatic refunds, in that case we need to show the message so they can manually process the refund through the credit card providers. Examples include Stripe, Paypal, etc

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #1726. All mentioned issues should be fixed now. Also, a confirmation dialog was added to the refund flow.

image

image

image

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
I have an order which I already refunded
Screenshot_1576951734

**Comment by nbradbury** [comment]
I refunded all the products for an order the tapped "Issue Refund" again and ended up seeing this screen:

Screenshot_1576951734

**Comment by nbradbury** [comment]
In this refund screen, I selected to refund the product but the "Products refund" at the bottom of the screen shows $0. I believe it's because the product was already refunded, but if that's the case should "issue refund" be hidden?

Note that this was order #4422 in the "Bananza World Zhhhh" test store.


Screenshot_1576952236

**Comment by 0nko** [comment]
Thank you @kyleaparker and @nbradbury. The refund button and refund product count errors should be fixed now and the PR's ready for another round.

I've also updated the refund info and refund item layout based on the design updates:

image

One thing I wanted to mention - I've removed the feature flag in this PR before I left in December. Is it still OK or should I add it back?

File: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt [hunk 1]
```diff
@@ -31,10 +30,10 @@ final class MockedProductDetailViewModel @AssistedInject constructor(
         currencyFormatter,
         wooCommerceStore
 ) {
-    override val viewStateData: LiveDataDelegate<ViewState> =
-            LiveDataDelegate(arg0, ViewState(), "", onChange = {
-                combineData(it.product!!, Parameters("$", "oz", "in"))
-            })
+//    override val viewStateData: LiveDataDelegate<ViewState> =
```
Comment (nbradbury) [inline WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt]: Should this be removed rather than commented out?

**Comment by nbradbury** [comment]
@0nko This issue may be unrelated to this PR, or not even an issue at all, but I wanted to make sure.

I generated an order for three of the same product, which cost 0.10 each. I then refunded two of them, as shown below.

refund

I then went to fulfill the order, and the total shows as the original unrefunded 0.30. Shouldn't this be showing 0.10 instead?

fulfill

File: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt]: This connected test that uses this class has been failing for a while, this was just so that the build works. We should address those eventually but probably not in this PR.

**Comment by nbradbury** [comment]
This is more of a question for @kyleaparker, but the confirmation dialog states that the refund "can't be undone," then if you confirm it the next thing you see is a snackbar with an Undo button on it.

dialog

Screenshot_1580157484

**Comment by 0nko** [comment]
@nbradbury You seem to be testing an older commit. The layout of the refund item in order detail has changed.

File: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/androidTest/kotlin/com/woocommerce/android/ui/products/MockedProductDetailViewModel.kt]: Okay, perhaps add a `TODO` here then?

**Comment by nbradbury** [comment]
> You seem to be testing an older commit. The layout of the refund item in order detail has changed.

Yeah, noticed that right after I posted :) But I have the latest changes and same problems exist.

**Comment by kyleaparker** [comment]
>This is more of a question for @kyleaparker, but the confirmation dialog states that the refund "can't be undone," then if you confirm it the next thing you see is a snackbar with an Undo button on it.

I think we can remove the undo from the snackbar 👍

**Comment by nbradbury** [comment]
The wording here for a manual refund is wonky. Should "via" be removed from the end here?

via

**Comment by nbradbury** [comment]
This may not be an issue since it sounds like we're removing the Undo button, but if I undo a refund I then get stuck in the refund fragment. I can try to back out, but it keeps me on the same screen and just shows a toast stating, "Refund in progress please wait."

Screenshot_1580157752

**Comment by nbradbury** [comment]
I'm trying to figure out why there's no Issue Refund button here. This is the previously-mentioned order for three items, two of which were refunded. I don't see a way to refund the remaining item. I **can** refund it in web app.

Screenshot_1580158391

**Comment by nbradbury** [comment]
@0nko Done with my first round!

**Comment by 0nko** [comment]
Thanks for the review, @nbradbury!

> I then went to fulfill the order, and the total shows as the original unrefunded 0.30. Shouldn't this be showing 0.10 instead?

Yes. This is fixed now.

> I think we can remove the undo from the snackbar 👍

Done.

> The wording here for a manual refund is wonky. Should "via" be removed from the end here?

This was caused by the empty payment gateway title, which is weird because I can see from other screenshots it's supposed to be COD. I added a logic that can handle it now, though.

> I'm trying to figure out why there's no Issue Refund button here. 

This was caused by a condition that only shows the button if there is a recorded payment from the customer. The web allows to refund items even if there is none so I've now removed it.

I also fixed the refund list reordering issue in order detail that @kyleaparker found.

Ready for another round 🤞 .

**Comment by nbradbury** [comment]
You'll be happy to hear we can :shipit:

**Comment by nbradbury** [comment]
@0nko Oh, wait - I see this is going to be merged into `release/3.5` which is already frozen. Should this be merged into `develop` instead? If it really should be in `release/3.5` feel free to merge it yourself since I've approved it.

**Comment by 0nko** [comment]
I've talked to @jkmassel about this PR and we're going to release a new beta after it is merged.
