### PR TITLE
Issue/859 rapid review moderation woes

### LINKED ISSUE #859: Problems when rapidly moderating reviews
The notification list has a couple of issues if you trash multiple reviews very quickly (before the snackbar has a chance to disappear):

* Sometimes the wrong review will be trashed
* Sometimes the previously trashed review will return to the list

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #859 - the problems caused by rapidly trashing reviews were due to previous trash requests not completing before the notif list was refreshed. To solve this, we now maintain a list of removed notif IDs and make sure they don't reappear.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt [hunk 1]
```diff
@@ -55,20 +56,29 @@ class NotifsListAdapter @Inject constructor() : SectionedRecyclerViewAdapter() {
...
+        val newList = ArrayList<NotificationModel>()
+        if (removedRemoteIds.isNotEmpty()) {
+            notifs.forEach { notif ->
+                if (!removedRemoteIds.contains(notif.remoteNoteId)) {
+                    newList.add(notif)
+                }
+            }
+        } else {
+            newList.addAll(notifs)
+        }
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt]: This could be simplified a bit: 
`val newList = notifs.filter { !removedRemoteIds.contains(it.remoteNoteId) }`

**Comment by nbradbury** [comment]
> I'm not sure if it's related to this PR but I was able to crash the app:

Oh, yuck. That's not related to this PR but needs to be fixed quickly. I opened [a FluxC issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1153) for this.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/notifications/NotifsListAdapter.kt]: Good call - added in 8e0f030.
