### PR TITLE
ContinuationWrapper

### LINKED ISSUE #3762: java.lang.IllegalStateException: Already resumed, but proposed with update
There are aa bunch of crashes with the same stacktrace but in different parts of the app, mostly related to products.

```
java.lang.IllegalStateException: Already resumed, but proposed with update true
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.ui.products.ProductShippingClassRepository.onProductShippingClassesChanged(ProductShippingClassRepository.kt:91)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update https://tmabazzar.in/wp-content/uploads/2021/03/dreamstime_l_5556861-1.jpg
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.media.MediaFilesRepository.onMediaUploaded(MediaFilesRepository.kt:74)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update SUCCESS
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.ui.orders.tracking.OrderShipmentProvidersRepository.onOrderShipmentProviderChanged(OrderShipmentProvidersRepository.kt:93)
```

```
java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[java.lang.Exception: BAD_REQUEST, cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received]
    at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:335)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:330)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
    at com.woocommerce.android.media.MediaFilesRepository.onMediaUploaded(MediaFilesRepository.kt:66)
```

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #3762 A possible remedy for fixing some of the coroutine continuation woes.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
@0nko This looks good to me, but on Slack I've asked someone with more coroutine experience to also take a look.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    private var timeout: Long = 0
+    private var continuation: CancellableContinuation<T>? = null
+    private val mutex = Mutex()
+
+    suspend fun callAndWaitUntilTimeout(
+        timeout: Long = AppConstants.REQUEST_TIMEOUT,
+        asyncAction: () -> Unit
+    ): ContinuationResult<T> {
+        mutex.withLock {
+            this.timeout = timeout
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: 🔍  Nitpick: We might want to consider removing this method and adding a default `timeout = 0` parameter to `callAndWait`. We wouldn't need to store `timeout` in a field and we wouldn't need to use lock for this scenario. 

Option 2: If you introduced it because of the `AppConstants.REQUEST_TIMEOUT`, I'd consider creating an additional method instead of removing this one.

```
suspend fun callAndWaitUntilTimeout(
        timeout: Long = AppConstants.REQUEST_TIMEOUT,
        asyncAction: () -> Unit
    ): ContinuationResult<T> {
           callAndWait(asyncAction, timeout)
    }
    
suspend fun callAndWait(asyncAction: () -> Unit): ContinuationResult<T> {
                   callAndWait(asyncAction, 0)
}
   
private fun callAndWait(asyncAction: () -> Unit, timeout: Long) { ... }
```

Wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+                } else {
+                    suspendCoroutine(asyncAction)
+                }
+                Success(continuationResult)
+            } catch (e: CancellationException) {
+                WooLog.e(tag, e)
+                Cancellation<T>(e)
+            }
+
+            continuation = null
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: We might want to consider wrapping this line with `finally` block to make sure we clear the field even if the coroutine throws an unhandled exception, wdyt?
`+` we could remove `result` and return the whole `try/catch` after this change.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt [hunk 3]
```diff
@@ -89,15 +75,11 @@ class WPMediaPickerRepository @Inject constructor(
...
-                    it.resume(false)
-                } else {
-                    canLoadMoreMedia = event.canLoadMore
-                    it.resume(true)
-                }
-            }
+        if (event.isError) {
+            loadContinuation.continueWith(false)
+        } else {
+            canLoadMoreMedia = event.canLoadMore
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt:81]: ⚠️  I'm not sure if it's intended or if it matters, but this code slightly changes the current behavior. Consider the following scenario:
1. We start the job
2. It times out
3. onMediaListFetched gets invoked
4. we update `canLoadMoreMedia` but since "loadContinuation.continueWith(true)" doesn't do anything after timeout, the result is ignored. 

Is it ok, that we update `canLoadMoreMedia` even when the OnMediaListFetched event was ignored?

**Review by malinajirka — CHANGES_REQUESTED** [review]
Thanks @0nko! It looks good to me overall - I have left a few questions/suggestions, let me know what you think. 

Also I think it'd be really good to introduce tests for this new class, since it'll be used throughout the codebase. Wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: That's what I had initially but after @nbradbury's suggestion I added the timeout method with a default REQUEST_TIMEOUT interval. Option 2 makes sense 👍.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt (hunk 2 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: Great point!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt (hunk 3 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaPickerRepository.kt:81]: I've added a way to check if a continuation is still active and updated the handler to use it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+    }
+
+    private suspend fun callAndWait(asyncAction: () -> Unit, timeout: Long): ContinuationResult<T> {
+        suspend fun suspendCoroutine(asyncRequest: () -> Unit) = suspendCancellableCoroutine<T> {
+            continuation = it
+            asyncRequest()
+        }
+
+        return try {
+            continuation?.cancel()
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: ❓ Since this block is not synchronized (wrapped in mutex) anymore, I'm wondering if it'll work as expected. AFAIU `cancel` is not a synchronous operation -> what if we reach `continuation = it` sooner than the previous coroutine gets canceled and when it gets canceled it sets `continuation = null` in the finally block. We'd lose reference to the current `continuation` in such scenario. Do you think it could happen?

1. Coroutine A starts and sets continuation to ACont
2. Coroutine B invokes ACont.cancel and sets continuation to BCont
3. A is canceled sets continuation to null (it override BCont to null 💥) 

----------------------------

I'm wondering if the following code would work, wdyt?
```
        continuation?.cancel()
        mutex.withLock {
            return try { ... } finally { ...} 
         }
```

**Review by malinajirka — COMMENTED** [review]
Thanks @0nko! I've left one more question/suggestions - these types of synchronization issues are always tricky. Perhaps, I'm overthinking this. Let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt (hunk 4 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: You're right. I've removed the mutex as per your previous suggestion but it's still required. It's back now and it should address the scenario above.

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: Ohh, sorry for the confusion. I wasn't suggesting we should remove it here - I was suggesting that we wouldn't need it to protect "this.timeout = timeout".  Thanks for the fix!

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/ContinuationWrapper.kt]: @0nko I think we need to move "continuation.cancel()" outside of the lock, wdyt?

**Review by malinajirka — APPROVED** [review]
Thanks for all the improvements ;). LGTM
