### PR TITLE
Send Tracks events for Upgrade flow result (triggered from Preview)

### LINKED ISSUE #8736: Track if user upgraded a plan starting from the store preview banner
### Describe the bug
After tapping on the "Upgrade" action in the free trial banner in the "store preview" feature, we don't track if a user successfully upgraded a plan.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #8736

### Description

This PR introduces usage of StartUpgradeFlow use case from the Preview screen. This change will result with the Tracks events sent in case if user successfully upgrades a plan or abandones it during the process, when it started from the Preview screen.

### Testing instructions

- [ ] With a site in Free Trial, open the "Preview" and press "Upgrade" on the top banner. Upgrade the site and verify that there's `plan_upgrade_success` event recorded.
- [ ] With a site in Free Trial, open the "Preview" and press "Upgrade" on the top banner. Abandon the process and verify that there's `plan_upgrade_abandoned` event recorded.

### Images/gif

https://user-images.githubusercontent.com/5845095/229747009-661543dd-042d-411c-9150-59d87fe950c7.mp4

### Questions
@JorgeMucientes I've got two questions:

- is Kiwi planning to handle the "post successful upgrade" flow? After this PR, as you can see in the video, we'll navigate the user back to the "Preview" screen but the state of the Preview doesn't seem to refresh properly. If it's not in Kiwi scope, then Eagle will do this - we just have to sync on that 🙂
- I don't know if it's a known issue but I can't scroll the site which is in the preview.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt [hunk 1]
```diff
@@ -54,19 +58,15 @@ class LaunchStoreFragment : BaseFragment() {
...
     }
 
-    private fun openInWebView(url: String) {
-        findNavController().navigateSafely(
-            NavGraphMainDirections.actionGlobalWPComWebViewFragment(
-                urlToLoad = url
-            )
-        )
+    private fun startUpgradeFlow() {
+        startUpgradeFlowFactory.create(findNavController()).invoke(BANNER)
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt:79]: Interesting. Just curious what are the benefits of this approach to navigation VS invoking code like this directly: 
```kotlin 
navController.navigateSafely(
            NavGraphMainDirections.actionGlobalPlanUpgradeStartFragment(
                source = source
            )
        )
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreViewModel.kt [hunk 2]
```diff
@@ -92,11 +89,7 @@ class LaunchStoreViewModel @Inject constructor(
             FREE_TRIAL_UPGRADE_NOW_TAPPED,
             mapOf(AnalyticsTracker.KEY_SOURCE to AnalyticsTracker.VALUE_BANNER)
         )
-        triggerEvent(
-            UpgradeToEcommercePlan(
-                url = PLANS_URL + selectedSite.get().siteId
-            )
-        )
+        triggerEvent(UpgradeToEcommercePlan)
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreViewModel.kt:100]: Thanks for the house cleaning! 👍🏼

**Comment by JorgeMucientes** [comment]
Nice job @wzieba! Tracking works as expected and code looks good. 

> I don't know if it's a known issue but I can't scroll the site which is in the preview.

About that, it's a bug. I have a really small change that I can push to this branch let me know if I can proceed with pushing it so we can fix the issue in this PR.

> is Kiwi planning to handle the "post successful upgrade" flow? After this PR, as you can see in the video, we'll navigate the user back to the "Preview" screen but the state of the Preview doesn't seem to refresh properly. If it's not in Kiwi scope, then Eagle will do this - we just have to sync on that 🙂

I am not sure who should do this tbh. I did take a quick look at fixing it now, but it was not as straightforward as I expected. What I did is to make the `LaunchStoreViewModel` lifecycle aware. Then add this to the viewModel: 
```kotlin 
    override fun onResume(owner: LifecycleOwner) {
        _viewState.value = _viewState.value.copy(
            isTrialPlan = selectedSite.get().isFreeTrial
        )
    }
```

But apparently that is not enough, because after the plan is upgraded in the webview we are not refreshing the `selectedSite.plan`? It is still returning the freeTrial plan id. Do you plan to refresh this from the upgrade flow when the payment is processed successfully? Alternativelly I could fetch plan details every time we resume `LaunchStoreFragment` but I'd say that is less ideal. 

Let me know your thoughts 🙂

**Review by JorgeMucientes — APPROVED** [review]

**Comment by wzieba** [comment]
> I have a really small change that I can push to this branch let me know if I can proceed with pushing it so we can fix the issue in this PR.

Sure thing!

> Do you plan to refresh this from the upgrade flow when the payment is processed successfully?

That's a good idea, I think we should do this. I'll add this to our backlog as a part of `PlanUpgradeStartFragment` and it should probably fix the issue :)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt (hunk 1 above)
Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt:79]: Originally this class contained logic for preparing a "plan upgrade URL" (see [here](https://github.com/woocommerce/woocommerce-android/pull/8706/files#diff-309e584888f74aa47b629d03631241ee878d106f014dfa5488cd4b63256b812eR15))

I've decided to leave this class as I thought it might be good to have a single point for all of the invocations of the upgrade flow. I think we might add here sending a Tracks event, so VMs won't have to bother about it.

**Comment by JorgeMucientes** [comment]
> I'll add this to our backlog as a part of PlanUpgradeStartFragment and it should probably fix the issue :)

Great! Thank you @wzieba 👍🏼 

I've pushed 2 commits with small changes: 
- One to make the web view preview interactive
- Another to refresh the banner state in LaunchStoreFragment in `onResume` so once you apply the changes discussed earlier, when returning to LaunchStoreFragment the UI is updated accordingly. 

I'll leave the merging up to you, in case you want to check the changes I've added 🙂

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt (hunk 1 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/onboarding/launchstore/LaunchStoreFragment.kt:79]: I see. Thanks for clarifying 👍🏼

**Comment by wzieba** [comment]
Thank you @JorgeMucientes, the changes you introduced look good to me!
