### PR TITLE
Fix card reader permission crash in Android versions < 12

### LINKED ISSUE #10448: IllegalStateException: ACCESS_FINE_LOCATION, BLUETOOTH_CONNECT, BLUETOOTH_SCAN permission is required to discover extern...
Sentry Issue: [WOOCOMMERCE-ANDROID-8VA](https://a8c.sentry.io/issues/4728673795/?referrer=github_integration)

```
IllegalStateException: ACCESS_FINE_LOCATION, BLUETOOTH_CONNECT, BLUETOOTH_SCAN permission is required to discover external readers
    at com.woocommerce.android.cardreader.internal.connection.ConnectionManager.discoverReaders(ConnectionManager.kt:69)
    at com.woocommerce.android.cardreader.internal.CardReaderManagerImpl.discoverReaders(CardReaderManagerImpl.kt:88)
    at com.woocommerce.android.ui.payments.cardreader.connect.CardReaderConnectViewModel.startScanningIfNotStarted(CardReaderConnectViewModel.kt:262)
    at com.woocommerce.android.ui.payments.cardreader.connect.CardReaderConnectViewModel.access$triggerOpenUrlEventAndExitIfNeeded(CardReaderConnectViewModel.kt:82)
    at com.woocommerce.android.ui.payments.cardreader.connect.CardReaderConnectViewModel.access$startScanningIfNotStarted(CardReaderConnectViewModel.kt:82)
...
(50 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes #10448

### Description

This PR addresses a critical issue in our app's permission handling mechanism. We previously updated our permission checks to rely on the BLUETOOTH_CONNECT permission, which is applicable for Android 12 (API level 31) and above. However, this resulted in an oversight for devices running on Android versions 9, 10, and 11 (API levels 28-30), where the BLUETOOTH_CONNECT permission does not exist. Consequently, attempting to check this permission on these earlier versions led to the app incorrectly throwing an error and crashing, as the permission check would invariably return PackageManager.PERMISSION_DENIED.

To resolve this, we are checking the Android versions and check permissions accordingly. This change ensures compatibility across all supported Android versions and prevents crashes on devices running versions earlier than Android 12.

### Testing instructions

1. Create an order that is eligible for IPP
2. Navigate to the order detail screen
3. Click on Collect payment
4. Select "Card Reader"
5. Give all the permission it asks
6. Ensure the the whole IPP flow works without any issue
7. Please check this on both Android version < 12 and >= 12

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by malinajirka** [comment]
UPDATE: After discussing this on Slack, since the file doesn't contain any changes since the release of 16.6, the suggested approach will work as expected.

@̶A̶n̶i̶r̶u̶d̶h̶B̶h̶a̶t̶ ̶I̶ ̶b̶e̶l̶i̶e̶v̶e̶ ̶t̶h̶i̶s̶ ̶s̶u̶g̶g̶e̶s̶t̶i̶o̶n̶s̶ ̶
`̶`̶`̶T̶h̶e̶ ̶b̶a̶s̶e̶ ̶b̶r̶a̶n̶c̶h̶ ̶i̶s̶ ̶s̶e̶t̶ ̶t̶o̶ ̶t̶r̶u̶n̶k̶ ̶s̶i̶n̶c̶e̶ ̶t̶h̶e̶ ̶r̶e̶l̶e̶a̶s̶e̶/̶1̶6̶.̶6̶ ̶b̶r̶a̶n̶c̶h̶ ̶h̶a̶s̶ ̶a̶l̶r̶e̶a̶d̶y̶ ̶b̶e̶e̶n̶ ̶r̶e̶m̶o̶v̶e̶d̶.̶ ̶P̶l̶e̶a̶s̶e̶ ̶s̶e̶t̶ ̶t̶h̶e̶ ̶b̶a̶s̶e̶ ̶b̶r̶a̶n̶c̶h̶ ̶t̶o̶ ̶t̶h̶e̶ ̶n̶e̶w̶ ̶r̶e̶l̶e̶a̶s̶e̶ ̶b̶r̶a̶n̶c̶h̶ ̶b̶r̶a̶n̶c̶h̶ ̶o̶n̶c̶e̶ ̶i̶t̶ ̶i̶s̶ ̶c̶r̶e̶a̶t̶e̶d̶ ̶b̶e̶f̶o̶r̶e̶ ̶m̶e̶r̶g̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶P̶R̶`̶`̶`̶
  ̶w̶o̶n̶'̶t̶ ̶w̶o̶r̶k̶.̶ ̶
  
  T̶h̶e̶ ̶P̶R̶ ̶i̶s̶ ̶b̶a̶s̶e̶d̶ ̶o̶n̶ ̶`̶t̶r̶u̶n̶k̶`̶ ̶s̶o̶ ̶i̶f̶ ̶w̶e̶ ̶c̶h̶a̶n̶g̶e̶ ̶t̶h̶e̶ ̶t̶a̶r̶g̶e̶t̶ ̶b̶r̶a̶n̶c̶h̶,̶ ̶t̶h̶e̶ ̶P̶R̶ ̶w̶i̶l̶l̶ ̶c̶o̶n̶t̶a̶i̶n̶ ̶a̶l̶l̶ ̶t̶h̶e̶ ̶c̶h̶a̶n̶g̶e̶s̶ ̶m̶a̶d̶e̶ ̶s̶i̶n̶c̶e̶ ̶1̶6̶.̶6̶.̶ ̶ O̶r̶ ̶a̶m̶ ̶I̶ ̶m̶i̶s̶s̶i̶n̶g̶ ̶s̶o̶m̶e̶t̶h̶i̶n̶g̶?̶ ̶ ̶

I̶ ̶t̶h̶i̶n̶k̶ ̶w̶e̶ ̶n̶e̶e̶d̶ ̶t̶o̶:̶ ̶

1̶.̶ ̶C̶r̶e̶a̶t̶e̶ ̶a̶ ̶b̶r̶a̶n̶c̶h̶ ̶`̶r̶e̶l̶e̶a̶s̶e̶/̶1̶6̶.̶6̶.̶1̶`̶ ̶o̶n̶ ̶t̶o̶p̶ ̶o̶f̶ ̶t̶h̶e̶ ̶l̶a̶t̶e̶s̶t̶ ̶1̶6̶.̶6̶ ̶t̶a̶g̶.̶ ̶
2̶.̶ ̶C̶r̶e̶a̶t̶e̶ ̶a̶ ̶b̶r̶a̶n̶c̶h̶ ̶w̶i̶t̶h̶ ̶a̶ ̶f̶i̶x̶ ̶o̶n̶ ̶t̶o̶p̶ ̶o̶f̶ ̶`̶r̶e̶l̶e̶a̶s̶e̶/̶1̶6̶.̶6̶.̶1̶`̶.̶ ̶
3̶.̶ ̶C̶r̶e̶a̶t̶e̶ ̶a̶ ̶P̶R̶ ̶t̶a̶r̶g̶e̶t̶i̶n̶g̶ ̶`̶r̶e̶l̶e̶a̶s̶e̶/̶1̶6̶.̶6̶.̶1̶`̶.̶

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt [hunk 1]
```diff
@@ -58,36 +59,14 @@ internal class ConnectionManager(
...
-                            != PackageManager.PERMISSION_GRANTED ||
-                            application.checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)
-                            != PackageManager.PERMISSION_GRANTED
-                        ) {
-                            error(
-                                "ACCESS_FINE_LOCATION, BLUETOOTH_CONNECT, BLUETOOTH_SCAN " +
-                                    "permission is required to discover external readers"
-                            )
-                        }
+                        checkIfNecessaryPermissionsAreGranted()
```
Comment (kidinov) [inline libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt:60]: np: we can remove `@Suppress("ComplexMethod", "LongMethod")` now

Comment (AnirudhBhat) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt:60]: Done: https://github.com/woocommerce/woocommerce-android/pull/10459/commits/25bb5f5ca60a0c705b5c3f171751540cd540b6e4

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt [hunk 2]
```diff
@@ -120,6 +97,27 @@ internal class ConnectionManager(
             }
         }
 
+    private fun checkIfNecessaryPermissionsAreGranted() {
```
Comment (kidinov) [inline libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt:100]: np: probably it can be simplified:

```
    private fun checkIfNecessaryPermissionsAreGranted() {
        val permissionsToCheck = mutableListOf(Manifest.permission.ACCESS_FINE_LOCATION)

        val isAtLeastAndroidS = Build.VERSION.SDK_INT >= Build.VERSION_CODES.S
        if (isAtLeastAndroidS) {
            permissionsToCheck.add(Manifest.permission.BLUETOOTH_CONNECT)
            permissionsToCheck.add(Manifest.permission.BLUETOOTH_SCAN)
        }

        permissionsToCheck.forEach { permission ->
            if (application.checkSelfPermission(permission) != PackageManager.PERMISSION_GRANTED) {
                error("$permission permission is required to discover external readers")
            }
        }
    }
```

**Review by kidinov — APPROVED** [review]
Validated the fix on the emulator version 30

Left a couple of np, which can be ignored for now

Thanks!

**Comment by malinajirka** [comment]
@AnirudhBhat I have updated the target branch and merged the PR. Just noting that there is one more PR review comment from Andrei [here](https://github.com/woocommerce/woocommerce-android/pull/10459#discussion_r1432634148). If you decide not to act on it, please leave a comment and close it. Thanks!

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt (hunk 2 above)
Comment (AnirudhBhat) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt:100]: Sure. I'll take it in a separate PR since this is just a minor change and doesn't affect the functionality in any way. Thank you!
