### PR TITLE
issue/4478-payment-tutorial-tablets

### LINKED ISSUE #4478: Card Reader Tutorial is broken on tablets
**Describe the bug**
The layout of the tutorial is broken on tablets - content drawn on top of each other and outside borders of the view.

**To Reproduce**

- Use tablet
1. Clear app data or set the ` SHOW_CARD_READER_CONNECTED_TUTORIAL` flag to true using Flipper
2. Click on App settings
3. Click on "Manage card reader"
4. Click on "Connect to card reader"
5. Finish the connection and notice the tutorial looks broken

**Screenshots**
Screenshot_1627022756

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4478 - previously the payment tutorial was visually broken on tablets. This PR corrects this. Tablet portrait and landscape shots below. To test, I recommend changing the [onboarding click listener ](https://github.com/woocommerce/woocommerce-android/blob/3f310e4e6bb0d27c0c1d27f2bd5957c3d230bb98/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/MainSettingsFragment.kt#L124)to this, so you can easily view the tutorial:

```
childFragmentManager.beginTransaction()
                .add(CardReaderTutorialDialogFragment(), "TAG")
                .commitAllowingStateLoss()
```

landscape
portrait

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt [hunk 1]
```diff
@@ -25,22 +25,24 @@ class CardReaderTutorialViewPagerItemFragment : Fragment(R.layout.fragment_card_
...
                 binding.imageView.setImageResource(args.getInt(ARG_DRAWABLE_ID))
             }
 
-            // adjust the view sizes based on orientation
-            val ratio = if (isLandscape) {
-                (DisplayUtils.getDisplayPixelWidth() * RATIO_LANDSCAPE).toInt()
-            } else {
-                (DisplayUtils.getDisplayPixelWidth() * RATIO_PORTRAIT).toInt()
+            // adjust the view sizes based on orientation (skipped for tablets)
+            if (!isTablet) {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt]: ❓ I'm not familiar with the code - I realize it wasn't added in this PR, but I'd like to understand it since this PR touches the logic. What is the purpose of manually changing view dimentions? Can't we leave it up to the OS to switch between landscape and portrait layouts?

**Review by malinajirka — COMMENTED** [review]
Thanks @nbradbury for the quick fix!

I noticed that the layout doesn't have any padding on the sides on tablets, any idea why?

**Comment by nbradbury** [comment]
> What is the purpose of manually changing view dimentions? 

@malinajirka You're right, that's not necessary. Addressed in afe6a60.

> I noticed that the layout doesn't have any padding on the sides on tablets, any idea why?

Strange, it looks fine on my Nexus 10 emulator. I added some padding to the ViewPager item in afb73f1 and hopefully that fixes it for you.

**Review by malinajirka — APPROVED** [review]
I've tested this on phone and tablet in both landscape and portrait and it all looks great, thanks for working on this! ;)
