### PR TITLE
Fixes tracking for Blaze cta displayed from product detail

### LINKED ISSUE #9260: Fixes tracking for event blaze_entry_point_displayed
Currently we were tracking `blaze_entry_point_displayed` every time the product detail screen was opened. What we really want to do is track this event only when the actual Blaze cta is displayed from the overflow menu inside product detail screen.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Fixes: #9260

### Description

Intercept clicks on the overflow menu inside the product detail screen to track `blaze_entry_point_displayed` properly. I'm not a big fan of the implementation of this tracking as it is a bit hacky, but it the "cleanest" way I found to track click on the overlflow button. 

### Testing instructions

1. Log into a atomic public store
2. Open a published product
3. Check `blaze_entry_point_displayed` is NOT tracked
4. Click on the overflow menu and check the following event is tracked in the logs: `Tracked: blaze_entry_point_displayed, Properties: {"source":"product_more_menu","blog_id":205513046,"is_wpcom_store":false,"is_debug":true}`

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt [hunk 1]
```diff
@@ -79,7 +79,7 @@ class StoreCreationSummaryViewModel @Inject constructor(
                         tracker.track(
                             stat = AnalyticsEvent.SITE_CREATION_FREE_TRIAL_CREATED_SUCCESS,
                             properties = mapOf(
-                                AnalyticsTracker.KEY_BLOG_ID to newStore.data.siteId,
+                                AnalyticsTracker.KEY_NEW_SITE_ID to newStore.data.siteId,
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt:82]: This change (and the line above 409) should've been added to this [PR](https://github.com/woocommerce/woocommerce-android/pull/9264), but since it didn't make it on time, I'm adding it here to avoid opening more PRs targeting `release/14.1`. 
The reason for adding a new key is explained on the commit message but in essence: `blog_id  is a default property so it can be overwriten when used as a custom property. To be safe about accidentally overriding the value, we are adding a new key`

**Review by hafizrahman — APPROVED** [review]
Works great in my test. The solution doesn't feel that hack-ish to me. 

A possible nitpick is that this calls the tracking again if the menu is shown and then there's a configuration change, but I feel it's a non-blocking edge case.

I think we can ship this 🚢

**Comment by JorgeMucientes** [comment]
Hey @jkmassel sorry for yet another ping about merging fixes on `release/14.1`. 

There's no need to generate new betas for this. Just a friendly ping that we merged a couple more fixes in `release/14.1` and that the final release candidate to be published should include them :)
