### PR TITLE
Ensure the device is correctly unregistered after logout in all scenarios

### LINKED ISSUE #13611: App can sometimes ignore push registration after login
Currently, after login, we attempt to register the device with our servers, but in some cases, the app will skip this when it thinks that the device is already registered.
To reproduce:

1. Use two accounts: account A and account B, and a site connected only to Account A.
2. Start login and enter the site address.
3. Continue using account B.
4. In the Account Mismatch screen, tap on "Login using a different account"
5. Not enter the site address, and use account A.
6. You won't receive push notifications.

This happens because the device will be registered with account B, and our logout action in the account mismatch screen won't trigger an unregisteration.

The fix will touch different areas:
1. Make sure that the `AccountRepository#logout` function triggers device unregistration to make sure it occurs in all scenarios.
2. Update the function `AppInitializer#onAccountChanged` to use `Mode.FORCEFULLY`, as this happens during an account change.

`1` could be enough to fix the issue, but I think `2` makes sense too, and it's safer.

------
**Update:**

After checking this more, we won't handle `2` now, the `AppInitializer#onAccountChanged` is called on each launch regardless of whether the account was changed or not, so before implementing we'll need to update the `AccountStore` to ensure the event is emitted only when changed, but this will require more effort and it's outside of the scope of this fix.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #13611 

### Description
This PR fixes the linked issue by ensuring we unregister the device with our servers for each logout, we achieve this by moving the unregistration logic to the repository, which will ensure it will be called in all scenarios.

Failing to unregister the device was causing issues when the user has to change the account during the login that would prevent registering using the new account, this was because the app will believe the device is already registered.

### Steps to reproduce
1. Use two accounts: account A and account B, and a site connected only to Account A.
1. Start login and enter the site address.
1. Continue using account B.
1. In the Account Mismatch screen, tap on "Login using a different account"
1. Now enter the site address, and use account A.
1. Test push notifications.

### Testing information
- Confirm push notifications are received.
- Open the MC push notifications dashboard and confirm your device is registered with Account A.

### The tests that have been performed
^

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt [hunk 1]
```diff
@@ -21,37 +15,27 @@ class AppSettingsPresenter @Inject constructor(
...
-    }
-
-    @Suppress("unused", "UNUSED_PARAMETER")
-    @Subscribe(threadMode = ThreadMode.MAIN)
-    fun onDeviceUnregistered(event: OnDeviceUnregistered) {
-        // Now that we've unregistered the device, we can logout
         coroutineScope.launch {
             accountRepository.logout().let {
                 if (it) {
+                    clearCardReaderDataAction()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt:29]: This is a change from before: we won't clear the card reader data until the logout is successful. I feel this is a better approach, let me know what you think.

Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt:29]: Before, we were not clearing card reader data after logout, but now we will. This was a missing feature, and you have added it, correct?

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻 I confirm that it was not working before and has been fixed with this PR.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt:29]: Not exactly, we were clearing it, but it was [done](https://github.com/woocommerce/woocommerce-android/blob/819eea50ea769832c9e26e9b6880c4ebe78427d5/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/AppSettingsPresenter.kt#L34) before the logout, which means that if for some reason the logout failed, the data was still cleared.

**Comment by hichamboushaba** [comment]
@JorgeMucientes a heads up, we shipped this fix to the release branch, please create a new beta to include it at your earliest convenience.
