### PR TITLE
Fix the empty billing address issue

### LINKED ISSUE #2495: Empty customer info card
When an order contains no shipping and billing address and the app is run for the first time (the order is opened for the first time with data cleared), an empty Customer information card is shown.

image

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #2495.

| Empty billing | Empty shipping |
|---|---|
| image | image | 
| **Partial billing** | **No shipping or billing** |
| image | image |
 
**To test:**

Empty billing details

1. Clear the storage before testing the app
2. Open an order with no billing address
3. Verify that the both the Billing section and `Show billing` button is hidden

Empty shipping details

1. Open an order with no shipping address
2. Verify that the `No address specified` is shown
3. Verify that the billing details are shown, if available

Partial billing details

1. Open an order with only partially filled billing details
2. Verify that the available data is shown

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt [hunk 1]
```diff
@@ -35,9 +35,9 @@ class OrderDetailCustomerInfoView @JvmOverloads constructor(
         billingOnly: Boolean = false
     ) {
         // Populate Shipping & Billing information
-        val billingAddrFull = getBillingInformation(order)
-        val isShippingInfoEmpty = !order.hasSeparateShippingDetails()
-        val isBillingInfoEmpty = billingAddrFull.trim().isEmpty() &&
+        val billingAddressFull = getBillingInformation(order)
+        val isShippingInfoEmpty = !isShippingAvailable(order)
+        val isBillingInfoEmpty = billingAddressFull.trim().isEmpty() &&
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailCustomerInfoView.kt:40]: np: instead of `trim().isEmpty()` this could be simply `isBlank()`.
