### PR TITLE
[TTP] When tax is added then autorefund doesn't work because amount missmatches

### LINKED ISSUE #8966: [Mobile Payments] When tax is added then autorefund doesn't work because amount missmatches

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #8966

### Description

The PR fixes a bug when an auto refund of the test TTP paid didn't work because the amount that was about to be refund was incorrect due to a tax

### Testing instructions

* Enable tax calculation on your website
* Try TTP test payment both with tax included and tax exploded in the payment
* Notice that both are refunded automatically and successfully

### Images/gif

https://user-images.githubusercontent.com/4923871/236779479-8822ab82-d9e2-4274-91c6-90eb725c04aa.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt [hunk 1]
```diff
@@ -109,6 +109,13 @@ class TapToPaySummaryViewModel @Inject constructor(
         }
     }
 
+    private fun calculateRefundAmount(order: Order) =
+        if (order.feesLines.firstOrNull()?.taxStatus == Order.FeeLine.FeeLineTaxStatus.TAXABLE) {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt:113]: ❓ I think this is the core piece of logic that calculates the refund amount. Can we test this to make sure we won't do any errors here?

```

@Test
    fun `given try ttp payment flow with taxable status, when vm created, then correct refunded is calculated`() =
        testBlocking {
            // GIVEN
            val order = OrderTestUtils.generateTestOrder(
                orderId = 50L,
                total = BigDecimal("11"),
                totalTax = BigDecimal.TEN,
                feeLines = listOf(
                    Order.FeeLine(
                        id = 0L,
                        name = "",
                        total = BigDecimal.ONE,
                        totalTax = BigDecimal.ONE,
                        taxStatus = Order.FeeLine.FeeLineTaxStatus.TAXABLE
                    )
                )
            )
            val captor = argumentCaptor<BigDecimal>()

            // WHEN
            initViewModel(TapToPaySummaryFragment.TestTapToPayFlow.AfterPayment(order))

            // THEN
            verify(refundStore).createAmountRefund(
                any(),
                any(),
                captor.capture(),
                any(),
                any()
            )

            assertThat(captor.firstValue).isEqualTo(BigDecimal("11"))
        }

```


```

@Test
    fun `given try ttp payment flow with NONE status, when vm created, then correct refunded is calculated`() =
        testBlocking {
            // GIVEN
            val order = OrderTestUtils.generateTestOrder(
                orderId = 50L,
                total = BigDecimal("11"),
                totalTax = BigDecimal.TEN,
                feeLines = listOf(
                    Order.FeeLine(
                        id = 0L,
                        name = "",
                        total = BigDecimal.ONE,
                        totalTax = BigDecimal.ONE,
                        taxStatus = Order.FeeLine.FeeLineTaxStatus.NONE
                    )
                )
            )
            val captor = argumentCaptor<BigDecimal>()

            // WHEN
            initViewModel(TapToPaySummaryFragment.TestTapToPayFlow.AfterPayment(order))

            // THEN
            verify(refundStore).createAmountRefund(
                any(),
                any(),
                captor.capture(),
                any(),
                any()
            )

            assertThat(captor.firstValue).isEqualTo(BigDecimal("1"))
        }

```

WDYT?

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @kidinov. LGTM! I've left one minor comment that is not blocking for the merge.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/taptopay/summary/TapToPaySummaryViewModel.kt:113]: Tests that I've added  already also test this, but your variant is better so I update them 2da39dfa44969325dabf8b0228d98e2f64fc33e3

Thanks!
