### PR TITLE
Display manuals per country

### LINKED ISSUE #7194: [Mobile Payments] - Card Reader Manuals always showing 3 manuals for all stores
**Describe the bug**
This is a platform issue, after comparing the same stores on an iOS device. Currently, Android always displays 3 reader manuals regardless of where the store is located.

**To Reproduce**
1. Go to IPP > Card Reader Manuals
2. See that for all store types, all 3 card reader manuals are displayed

**Screenshots**
### **iOS:**
**Canada store:**
canada store

**US store:**
us store

### **Android:**
**All stores:**

all stores

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: OPPO Reno6 Z 5G
- Android version: 12
- WooCommerce Android version: v9.8 / v9.7

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #7194 

### Description

This PR:

-  removes the Card Reader Manuals row from the IPP Hub when the store is not in the US or Canada, and of course, shows the row only if it's US and Canada. 
- Adds the logic so, when on a Canadian store, only the wisepad3 Manual is displayed and when on a US store only the M2 and BBPOS chipper are displayed

### Testing instructions

Please test using a store in the US, a store in Canada and a store o an unsupported country:

US Store:
- Go to Menu - Payments -> Make sure the row `Card Reader Manuals` is displayed
- Click on `Card Reader Manuals` -> Make sure both the BBPOS Chipper and the M2 reader are displayed (and only those)

Canadian Store:
- Go to Menu - Payments -> Make sure the row `Card Reader Manuals` is displayed
- Click on `Card Reader Manuals` -> Make sure  the Wisepad3 is displayed (and only this one)

Unsupported Store:
- Go to Menu - Payments -> Make sure the row `Card Reader Manuals` is **NOT** displayed

### Images/gif

manualsScreen

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReadersMapper.kt [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+                )
+                WisePade3 -> ManualItem(
+                    icon = drawable.ic_wisepad3_reader,
+                    label = string.card_reader_wisepad_3_manual_card_reader,
+                    onManualClicked = clickListeners[it]!!
+                )
+                else -> error("$it doesn't have a manual")
+
+//            CotsDevice -> TODO()
+//            VerifoneP400 -> TODO()
```
Comment (rossanafmenezes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReadersMapper.kt:39]: I'm checking the icons and manual links to see if I can actually implement all of them now. But
based on this comment p91TBi-7SX-p2#comment-9715 should we add the Verifone one?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt [hunk 2]
```diff
@@ -48,9 +51,16 @@ class CardReaderHubViewModel @Inject constructor(
     private val cardReaderChecker: CardReaderOnboardingChecker,
     private val cashOnDeliverySettingsRepository: CashOnDeliverySettingsRepository,
     private val learnMoreUrlProvider: LearnMoreUrlProvider,
+    cardReaderCountryConfigProvider: CardReaderCountryConfigProvider,
+
     private val cardReaderTracker: CardReaderTracker,
 ) : ScopedViewModel(savedState) {
     private val arguments: CardReaderHubFragmentArgs by savedState.navArgs()
+    private val storeCountryCode: String? = wooStore.getStoreCountryCode(selectedSite.get())
+    private val countryConfig: CardReaderConfig =
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: np: you could probably omit type specification here

```
private val storeCountryCode = wooStore.getStoreCountryCode(selectedSite.get())
    private val countryConfig = cardReaderCountryConfigProvider.provideCountryConfigFor(storeCountryCode)
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt [hunk 3]
```diff
@@ -124,7 +134,7 @@ class CardReaderHubViewModel @Inject constructor(
         isOnboardingComplete: Boolean,
         cashOnDeliveryItem: ToggleableListItem
     ) =
-        listOf(
+        mutableListOf(
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: np: here is probably better to return an immutable list. Generally it's a good practice to work with immutable data where it's possible

```
    private fun createHubListWhenSinglePluginInstalled(
        isOnboardingComplete: Boolean,
        cashOnDeliveryItem: ToggleableListItem
    ): List<ListItem> = mutableListOf(
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt [hunk 4]
```diff
@@ -2,33 +2,42 @@ package com.woocommerce.android.ui.payments.cardreader.manuals
...
+            cardReaderManualsSupportedReadersMapper.mapSupportedReadersToManualItems(
+                cardReaderConfig,
+                mapOf(
+                    Chipper2X to ::onBbposManualClicked,
+                    StripeM2 to ::onM2ManualClicked,
+                    WisePade3 to ::onWisePad3ManualCardReaderClicked
+                )
+            )
+        }
+        else -> null
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt]: I think we should crash here because it's not a valid state of being on this screen when a country is not supported

```
else -> error("$it doesn't have a manual")
```

Also, I just realized that probably it would be even better to pass `CardReaderConfigForSupportedCountry` parameter as a navigation argument. It will give us:
* Compilation safety (we won't be able to even open this screen for a country which is not supported)
* A bit faster runtime because we won't need to run `getStoreCountryCode` for the second time

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt (hunk 2 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: Thank you 👍 removed

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt (hunk 3 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: Thanks! Also done 😄

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt (hunk 4 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt]: > Also, I just realized that probably it would be even better to pass CardReaderConfigForSupportedCountry parameter as a navigation argument. It will give us:
Compilation safety (we won't be able to even open this screen for a country which is not supported)

Sorry for the silly question, do you mean navigating from the hub to the manuals page?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsScreen.kt [hunk 5]
```diff
@@ -29,9 +29,11 @@ import com.woocommerce.android.R
 fun ManualsScreen(
     cardReaderManualsViewModel: CardReaderManualsViewModel = viewModel()
 ) {
-    ManualsList(
-        list = cardReaderManualsViewModel.manualState
-    )
+    cardReaderManualsViewModel.manualState?.let {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsScreen.kt]: That's can be like that now, `manualState` is not nullable anymore 


```
ManualsList(
        list = cardReaderManualsViewModel.manualState
    )
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt [hunk 6]
```diff
@@ -48,9 +51,15 @@ class CardReaderHubViewModel @Inject constructor(
     private val cardReaderChecker: CardReaderOnboardingChecker,
     private val cashOnDeliverySettingsRepository: CashOnDeliverySettingsRepository,
     private val learnMoreUrlProvider: LearnMoreUrlProvider,
+    cardReaderCountryConfigProvider: CardReaderCountryConfigProvider,
+
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: np: probably an unnecessary empty line?

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+            )
+        )
+        val actualManualItems = manualsMapper.mapSupportedReadersToManualItems(
+            supportedCountry,
+            mapOf(
+                SpecificReader.WisePade3 to ::onManualClicked
+            )
+        )
+
+        Assertions.assertThat(expectedManuals).isEqualTo(actualManualItems)
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt]: np: We usually use static import here, to avoid writing type here

```
assertThat(expectedManuals).isEqualTo(actualManualItems)
```

The same for the previous test

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+
+    @Test
+    fun `given US store, when screen shown, US readers are displayed`() {
+
+        val supportedCountry = CardReaderConfigForUSA
+        val expectedManualItems = listOf(
+            ManualItem(
+                icon = drawable.ic_chipper_reader,
+                label = string.card_reader_bbpos_manual_card_reader,
+                onManualClicked = ::onManualClicked
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt:32]: Probably you can use just an empty lambda here and then no need to have this dummy function at the bottom

```
onManualClicked = {}
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt (hunk 4 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt]: I drafted this patch, to showcase what I was saying. Wdyt about that?
[Pass_CardReaderConfigForSupportedCountry_to_build_Manuals_screen.patch.zip](https://github.com/woocommerce/woocommerce-android/files/9573990/Pass_CardReaderConfigForSupportedCountry_to_build_Manuals_screen.patch.zip)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt [hunk 9]
```diff
@@ -1,44 +1,57 @@
...
+                    WisePade3 to ::onWisePad3ManualCardReaderClicked
+                )
+            )
+        }
+        else -> error("Manual not available")
+    }
 
-    private fun onBbposManualClicked() {
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
+    fun onBbposManualClicked() {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt]: You might avoid having these methods public. There is a small trick in mocking you could use:

```
    @Test
    fun `given US store, when user click on chipper reader, then correct webview is displayed`() {
        whenever(wooStore.getStoreCountryCode(selectedSite.get())).thenReturn("US")
        whenever(cardReaderCountryConfigProvider.provideCountryConfigFor("US")).thenReturn(supportedCountryUs)
        whenever(cardReaderManualSupportedCountryMapper.mapSupportedReadersToManualItems(any(), any())).thenAnswer {
            listOf(
                ManualItem(
                    icon = R.drawable.ic_chipper_reader,
                    label = R.string.card_reader_bbpos_manual_card_reader,
                    onManualClicked = (it.arguments[1] as Map<SpecificReader, () -> Unit>)[Chipper2X] as () -> Unit
                ),
            )
        }

        initViewModel()
        viewModel.manualState.find {
            it.label == R.string.card_reader_bbpos_manual_card_reader
        }?.onManualClicked?.invoke()

        assertThat(viewModel.event.value).isEqualTo(
            CardReaderManualsViewModel.ManualEvents.NavigateToCardReaderManualLink(AppUrls.BBPOS_MANUAL_CARD_READER)
        )
    }
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsScreen.kt (hunk 5 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsScreen.kt]: ✅

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt (hunk 6 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/hub/CardReaderHubViewModel.kt]: ✅

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt (hunk 7 above)
Comment (rossanafmenezes) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt]: ✅

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt (hunk 8 above)
Comment (rossanafmenezes) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsSupportedReaderMapperTest.kt:32]: I tried that before but the tests fail. Maybe I'm missing something 🤔

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt (hunk 9 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/manuals/CardReaderManualsViewModel.kt]: Thank you! Done ✅

**Review by kidinov — APPROVED** [review]
Thank you for working on that!
