### PR TITLE
Fix crash on order details when tapping customer info buttons

### LINKED ISSUE #12913: IllegalStateException: View com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView{8bf0ca9 V.E........
Sentry Issue: [WOOCOMMERCE-ANDROID-DE9](https://a8c.sentry.io/issues/5783066098/?referrer=github_integration)

```
IllegalStateException: View com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView{8bf0ca9 V.E...... ......ID 0,3212-1080,4349 #7f0a0752 app:id/orderDetail_customerInfo} does not have a NavController set
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.navigateToShippingAddressEditingView(OrderDetailCustomerInfoView.kt:296)
    .let { findNavController().navigateSafely(it) }
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.showShippingAddress$lambda$6(OrderDetailCustomerInfoView.kt:285)
    navigateToShippingAddressEditingView(order.shippingAddress)
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.$r8$lambda$SDquVAdSEH6yCB6XnJw1ccPw8p8(OrderDetailCustomerInfoView.kt:0)
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView$$ExternalSyntheticLambda3.onClick(OrderDetailCustomerInfoView:0)
    at com.woocommerce.android.widgets.WCSelectableTextView.onSingleTapConfirmed(WCSelectableTextView.kt:73)
    return clickableParent?.performClick() ?: false
...
(11 additional frame(s) were not displayed)
```

### LINKED ISSUE #12919: IllegalStateException: View com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView{26af0b4 V.E........
Sentry Issue: [WOOCOMMERCE-ANDROID-D64](https://a8c.sentry.io/issues/5758848674/?referrer=github_integration)

```
IllegalStateException: View com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView{26af0b4 V.E...... ......ID 0,1119-720,2053 #7f0a0753 app:id/orderDetail_customerInfo} does not have a NavController set
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.navigateToBillingAddressEditingView(OrderDetailCustomerInfoView.kt:302)
    .let { findNavController().navigateSafely(it) }
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.showBillingInfo$lambda$0(OrderDetailCustomerInfoView.kt:119)
    navigateToBillingAddressEditingView(order.billingAddress)
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView.$r8$lambda$A4-qu9UH-gxY8HuxEI4EqVyHBwc(OrderDetailCustomerInfoView.kt:0)
    at com.woocommerce.android.ui.orders.details.views.OrderDetailCustomerInfoView$$ExternalSyntheticLambda1.onClick(OrderDetailCustomerInfoView:0)
    at com.woocommerce.android.widgets.WCSelectableTextView.onSingleTapConfirmed(WCSelectableTextView.kt:73)
    return clickableParent?.performClick() ?: false
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12913 
Closes: #12919 

### Description
This PR fixes a crash that can occur in order details screen when tapping on of the buttons of the `OrderDetailCustomerInfoView`, the crash occurs if the user tries to tap on the buttons after the view was detached from the window, this can happen during transition animations, and happens more frequently on tablets given how the navigation works with the dual pane mode.

For technical side, this crash happens because when the fragment view is destroyed, the `NavHostFragment` will [detach](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-fragment/src/main/java/androidx/navigation/fragment/NavHostFragment.kt;l=302?q=NavHostFra) the `navController`, so if a button click listener was to be invoked after this, the `findNavController` will throw the exception.

### Steps to reproduce
Please repeat the following on both `trunk` and this branch to confirm the fix.

1. Use a physical device.
2. Open the order list on dual pane mode (Either on a tablet, or alternatively on a phone by opening the order list when the phone is on landscape)
3. Use two fingers to tap instantly on both:
   - The shipping section of order details.
   - The row of another order.
4. Repeat 3 few times, and the app should crash occasionally on `trunk`, and shouldn't crash on this branch.

Alternatively, if the above wasn't enough to reproduce it, please apply the following patch to simulate it, the patch will trigger manually the click after the view is destroyed, which should cause the crash on `trunk` and would confirm the fix of this branch.

<details>
<summary>Patch</summary>

```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt	(revision 564631291444e615d443e2bd4f6e00d8252602d8)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt	(date 1731511463945)
@@ -40,7 +40,7 @@
         private const val TELEGRAM_PACKAGE_NAME = "org.telegram.messenger"
     }
 
-    private val binding = OrderDetailCustomerInfoBinding.inflate(LayoutInflater.from(ctx), this)
+    val binding = OrderDetailCustomerInfoBinding.inflate(LayoutInflater.from(ctx), this)
     private var isCustomerInfoViewExpanded = false
 
     override fun onSaveInstanceState(): Parcelable {
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt	(revision 564631291444e615d443e2bd4f6e00d8252602d8)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt	(date 1731508415600)
@@ -311,7 +311,9 @@
 
     override fun onDestroyView() {
         super.onDestroyView()
+        val customerInfoBinding = binding.orderDetailCustomerInfo.binding
         _binding = null
+        customerInfoBinding.customerInfoShippingAddressSection.callOnClick()
     }
 
     fun onPrepareMenu(menu: Menu) {
```
</details>

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by atorresveiga — APPROVED** [review]
> Use two fingers to tap instantly on both:
> The shipping section of order details.
> The row of another order.

🤯🤯
This test case is from another level @hichamboushaba. Great creativity coming up with this case 👏 

I tested the PR and can confirm that the change fixes the bug.

LGTM! :shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt [hunk 1]
```diff
@@ -290,13 +286,26 @@ class OrderDetailCustomerInfoView @JvmOverloads constructor(
...
+        if (!isAttachedToWindow) return
+
+        val action = OrderDetailFragmentDirections.actionOrderDetailFragmentToEditCustomerOrderNoteFragment(
+            order.id
+        )
+        findNavController().navigateSafely(action)
+    }
+
     private fun navigateToShippingAddressEditingView(address: Address) {
+        if (!isAttachedToWindow) return
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailCustomerInfoView.kt:299]: Simple and elegant solution. Great work!
