### PR TITLE
Fix for NotificationMessageHandler Concurrent Modification Exception

### LINKED ISSUE #10529: ConcurrentModificationException
Sentry Issue: [WOOCOMMERCE-ANDROID-7MY](https://a8c.sentry.io/issues/4385401839/?referrer=github_integration)

```
ConcurrentModificationException: None
    at com.woocommerce.android.notifications.push.NotificationMessageHandler.removeNotificationByNotificationIdFromSystemsBar(NotificationMessageHandler.kt:285)
    at com.woocommerce.android.notifications.push.NotificationMessageHandler.onPushNotificationDismissed(NotificationMessageHandler.kt:65)
    at com.woocommerce.android.notifications.NotificationsProcessingService$ActionProcessor.process(NotificationsProcessingService.kt:93)
    at com.woocommerce.android.notifications.NotificationsProcessingService.onStartCommand$lambda$0(NotificationsProcessingService.kt:73)
    at com.woocommerce.android.notifications.NotificationsProcessingService.$r8$lambda$vL_er2S_jmPXpnhNwO-H_iwSB8o(NotificationsProcessingService.kt:0)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #10529

### Optimization of Notification Processing:
In this PR, we have refined the handling of notification actions within the `NotificationsProcessingService` by directly invoking `actionProcessor.process()` on the service's main thread. This approach replaces the previous method of spawning a new thread for each action, specifically `Thread { actionProcessor.process() }.start()`, which was identified as a source of concurrency issues due to simultaneous modifications of shared notification state. This modification presumes that the actions triggered by process() are swift and non-blocking, ensuring the service's performance remains stable. 

### Simplification of Synchronization:
Given the shift to main-thread execution, we propose removing the `@Synchronized` annotation from methods within `NotificationMessageHandler`, This adjustment is underpinned by the observation that these methods are exclusively invoked by the `ActionProcessor`, now operating on the main thread, which negates the need for synchronization mechanisms initially put in place to manage concurrent access risks.

### Testing instructions

1. Send remote push notifications to the device or send push notifications to the store that would trigger the behavior in app. 

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
Hi @wzieba & @0nko I am trying to get push notifications to work on my device but I am having some challenges hence the reason I tagged two folks to review this PR. Let me know if you can do a test of this functionality for me. Thanks.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt [hunk 1]
```diff
@@ -259,18 +259,19 @@ class NotificationMessageHandler @Inject constructor(
...
-        ACTIVE_NOTIFICATIONS_MAP.asSequence()
-            .forEach { row ->
-                if (row.key == localPushId) {
-                    notificationBuilder.cancelNotification(row.key)
-                } else {
-                    keptNotifs[row.key] = row.value
-                }
+        val keysToRemove = mutableListOf<Int>()
+
+        ACTIVE_NOTIFICATIONS_MAP.forEach { (key, _) ->
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt]: Why is the iteration necessary here? The map keys are unique, so there can be at most 1 notification, which you can access with `ACTIVE_NOTIFICATIONS_MAP[localPushId]`.

**Review by 0nko — COMMENTED** [review]
Hey @jd-alexander, thanks for working on this! I left a comment in the code changes. 

Also, there are other places in the `NotificationMessageHandler` that iterate over `ACTIVE_NOTIFICATIONS_MAP`. At the same time, the map can be modified in `handleWooNotification()`, which is not synchronized, so I think the concurrent access could still happen. 

Like you mentioned, the `ConcurrentHashMap` would solve these problems.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt [hunk 2]
```diff
@@ -259,18 +259,19 @@ class NotificationMessageHandler @Inject constructor(
...
     @Synchronized
     fun removeNotificationByNotificationIdFromSystemsBar(localPushId: Int) {
-        val keptNotifs = HashMap<Int, Notification>()
-        ACTIVE_NOTIFICATIONS_MAP.asSequence()
-            .forEach { row ->
-                if (row.key == localPushId) {
-                    notificationBuilder.cancelNotification(row.key)
-                } else {
-                    keptNotifs[row.key] = row.value
-                }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt]: > Instead of modifying `ACTIVE_NOTIFICATIONS_MAP` during iteration, we first identify all the keys that need to be removed and collect them into a separate list (`keysToRemove`).

Could you please explain the modification that was happening here? I'm not sure if during the iteration, `ACTIVE_NOTIFICATIONS_MAP` could be changed.

**Review by wzieba — COMMENTED** [review]
I like the proposed improvement, it's more readable to me. But I'm not sure if this fixes the concurrency issue. As @0nko noticed, `ACTIVE_NOTIFICATIONS_MAP` is still available for modification for other methods in this class, making it not thread safe.

Btw. a related question: do you @jd-alexander @0nko know why we call method of this class on a new thread? I mean this line: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationsProcessingService.kt#L73

**Comment by 0nko** [comment]
> Btw. a related question: do you @jd-alexander @0nko know why we call method of this class on a new thread? I mean this line: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationsProcessingService.kt#L73

Nice catch! I have no idea why we create a new thread here but it seems to be the cause of this issue...

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt (hunk 2 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt]: You are right @wzieba I misread the logic here! 😎

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt (hunk 1 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt]: Agreed!

**Comment by jd-alexander** [comment]
> > Btw. a related question: do you @jd-alexander @0nko know why we call method of this class on a new thread? I mean this line: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/NotificationsProcessingService.kt#L73
> 
> Nice catch! I have no idea why we create a new thread here but it seems to be the cause of this issue...

Good stuff folks, thanks for chiming in on this issue. So since this spawning of a new thread seems to be the issue I need to find a way to reproduce this challenge because if it is issue then I wouldn't need to use `ConcurrentHashMap`.

**Comment by jd-alexander** [comment]
The follow-up solution based on the feedback involves removing the asynchronous thread spawning within the `onStartCommand` method of the `NotificationsProcessingService`. The previous implementation utilized `Thread { actionProcessor.process() }.start()` to handle notification actions, which introduced concurrency issues when accessing shared notification state. By executing actionProcessor.process() directly in the service's main thread, we eliminate the risk of concurrent modifications that led to the exception. This change assumes that the notification-related actions performed by process() are non-blocking and quick to execute. If this assumption holds, the service's responsiveness should remain unaffected. However, should further analysis reveal that the operations are indeed blocking, I am thinking we could use coroutines for more structured concurrency.

**Comment by wzieba** [comment]
I try to understand the reason behind calling `ActionProcessor#process` on a new thread, but I can't see. The first commit where this idea is introduced is https://github.com/woocommerce/woocommerce-android/pull/531/commits/d8c7229f94206e238125bd6ebd7b1f0ad31fd701 but it's still not clear to me. Edit: so I think it's safe to remove 🙂

As `ActionProcessor#process` is not called on the main thread, can we also remove `@Synchronized` from `NotificationMessageHandler#onLocalNotificationDismissed` and `NotificationMessageHandler#onPushNotificationDismissed` (and other chained methods)? Those methods are only executed from the `ActionProcessor` and since executed on the main thread - I see no need to add complexity of `@Synchronized`.

**Comment by jd-alexander** [comment]
> I try to understand the reason behind calling `ActionProcessor#process` on a new thread, but I can't see. The first commit where this idea is introduced is [d8c7229](https://github.com/woocommerce/woocommerce-android/commit/d8c7229f94206e238125bd6ebd7b1f0ad31fd701) but it's still not clear to me. Edit: so I think it's safe to remove 🙂
> 
> As `ActionProcessor#process` is not called on the main thread, can we also remove `@Synchronized` from `NotificationMessageHandler#onLocalNotificationDismissed` and `NotificationMessageHandler#onPushNotificationDismissed` (and other chained methods)? Those methods are only executed from the `ActionProcessor` and since executed on the main thread - I see no need to add complexity of `@Synchronized`.

Makes sense! I made these changes. @wzieba ready for another review. Also were you able to replicate the error because I cant.

**Comment by wzieba** [comment]
@jd-alexander 👋 thanks for applying changes

>  Also were you able to replicate the error because I cant.

It's indeed difficult to reproduce this problem on real life device, as it's concurrency issue that happens sometimes.

To reproduce the error, I've prepared a sample reproduction "test" (not intended for merge), see below. Some caveats:
- the stacktrace is not precisely the same, as `NotificationMessageHandler` uses random values for assigning local ids so I coulnd't use the same methods as in Sentry report stacktrace 
- I couldn't use `Service` here as `ServiceTestRule` doesn't support intent services

Nevertheless, the stacktrace _is_ similar and throws the same `ConcurrentModificationException`.

<details><summary>Reproduction</summary>

```PATCH
Subject: [PATCH] build: migrate dagger/hilt in tests
---
Index: WooCommerce/src/androidTest/kotlin/com/woocommerce/android/notifications/NotificationsProcessingServiceTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/androidTest/kotlin/com/woocommerce/android/notifications/NotificationsProcessingServiceTest.kt b/WooCommerce/src/androidTest/kotlin/com/woocommerce/android/notifications/NotificationsProcessingServiceTest.kt
new file mode 100644
--- /dev/null	(date 1707312440293)
+++ b/WooCommerce/src/androidTest/kotlin/com/woocommerce/android/notifications/NotificationsProcessingServiceTest.kt	(date 1707312440293)
@@ -0,0 +1,66 @@
+package com.woocommerce.android.notifications
+
+import androidx.test.ext.junit.runners.AndroidJUnit4
+import com.woocommerce.android.e2e.helpers.InitializationRule
+import com.woocommerce.android.model.Notification
+import com.woocommerce.android.notifications.push.NotificationMessageHandler
+import dagger.hilt.android.testing.HiltAndroidRule
+import dagger.hilt.android.testing.HiltAndroidTest
+import javax.inject.Inject
+import kotlin.time.Duration.Companion.seconds
+import org.junit.Assert.*
+import org.junit.Before
+import org.junit.Rule
+import org.junit.Test
+import org.junit.runner.RunWith
+
+@RunWith(AndroidJUnit4::class)
+@HiltAndroidTest
+class NotificationsProcessingServiceTest {
+
+    @get:Rule(order = 0)
+    val rule = HiltAndroidRule(this)
+
+    @get:Rule(order = 1)
+    val initRule = InitializationRule()
+
+    @Inject
+    lateinit var sut: NotificationMessageHandler
+
+    @Before
+    fun setUp() {
+        rule.inject()
+    }
+
+    @Test
+    fun failing() {
+        repeat(100) {
+            Thread {
+                sut.handleWooNotification(notification)
+                sut.onPushNotificationDismissed(0)
+            }.start()
+        }
+        Thread.sleep(10.seconds.inWholeMilliseconds)
+    }
+
+    @Test
+    fun passing() {
+        repeat(100) {
+            sut.handleWooNotification(notification)
+            sut.onPushNotificationDismissed(0)
+        }
+    }
+
+    private val notification = Notification(
+        0,
+        0,
+        0,
+        0,
+        "",
+        "",
+        "",
+        WooNotificationType.NEW_ORDER,
+        NotificationChannelType.NEW_ORDER
+    )
+
+}
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt	(revision d78e6d3cc0160e67ce3a4cf35e534a636c2c2f71)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt	(date 1707310275615)
@@ -148,7 +148,7 @@
         }
     }
 
-    private fun handleWooNotification(notification: Notification) {
+    fun handleWooNotification(notification: Notification) {
         val randomNumber = if (notification.noteType == NEW_ORDER) Random.nextInt() else 0
         val localPushId = getLocalPushIdForNoteId(notification.remoteNoteId, randomNumber)
         ACTIVE_NOTIFICATIONS_MAP[getLocalPushId(localPushId, randomNumber)] = notification

```
</details>

So I think, as we discussed, the proposed change should address the issue (I also verified scenario without `@Synchronized` annotations).

**Review by wzieba — APPROVED** [review]

**Comment by wzieba** [comment]
The only thing that bugs me is if in scenario of closing many (5+) notifications one by one will work fine. Could you please test this on the device @jd-alexander , just to be extra sure?

**Comment by jd-alexander** [comment]
Thanks for such awesome testing code @wzieba and thought review as well. 

> The only thing that bugs me is if in scenario of closing many (5+) notifications one by one will work fine. Could you please test this on the device @jd-alexander , just to be extra sure?

Thanks for such a thorough and thoughtful review and testing code @wzieba I appreciate it greatly.

**Comment by jd-alexander** [comment]
Tested this implementation with multiple notification dismissals and it works as expected.
