### PR TITLE
Fix incorrect notice when saving product as draft

### LINKED ISSUE #4371: Products: incorrect notice after saving a newly created product as a draft
Steps to reproduce:

1. Go to Products > Add new product ("+" at bottom right).
1. Add a title, description, and price.
1. Tap the overflow menu and select "Save as draft".
1. Observe that a "Product published" notice is displayed briefly at the bottom of the screen.
1. Go to the product list and check to see if the product state is a draft or if it was published.

**Result:** when creating a new product in the app and saving it as a draft for the first time, a notice appears and incorrectly states that the product was published when it was actually saved as a draft.

More > Save as draft|Incorrect notice saying "published"|Gif 
---|---|---
Screen Shot 2021-07-06 at Jul 6 2 05 30 PM|Screen Shot 2021-07-06 at Jul 6 2 01 35 PM|incorrect-notice-after-saving-draft

<sup>Tested with WCAndroid 7.0-rc-1 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-2sv-p2#comment-8976 /ht @anitaa1990)</sup>

Note: there's another issue open to request a more prominent "Publish" button for draft products which may also affect this flow, see https://github.com/woocommerce/woocommerce-android/issues/4361. cc @shiki

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #4371. This PR fixes the scenario where when creating a new product in the app and saving it as a draft for the first time, a notice appears and incorrectly states that the product was published when it was actually saved as a draft.

Screenshots
==========
| Expected  | Actual |
| ------------- | ------------- |
| image |  |

Showcase
==========

How to Test
==========
1. Go to Products > Add new product ("+" at bottom right).
1. Add a title, description, and price.
1. Tap the overflow menu and select "Save as draft".
1. Observe that a "Product published" notice is displayed briefly at the bottom of the screen.
1. Go to the product list and check to see if the product state is a draft or if it was published.

Update release notes:
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 1]
```diff
@@ -1508,11 +1509,6 @@ class ProductDetailViewModel @Inject constructor(
         viewState = viewState.copy(isProgressDialogShown = false)
     }
 
-    /**
-     * Returns true if the product draft has a status of DRAFT
-     */
-    fun isDraftProduct() = viewState.productDraft?.status?.let { it == DRAFT } ?: false
-
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:1515]: I decided to delete this method after refactoring `pickAddProductRequestSnackbarText`. I've noticed that this method was now only called by an unreferenced method that also got deleted: `getSubmitDetailProgressDialog`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt [hunk 2]
```diff
@@ -432,26 +432,6 @@ class ProductDetailFragment :
...
-                message = R.string.product_publish_dialog_message
-            }
-            else -> {
-                title = R.string.product_update_dialog_title
-                message = R.string.product_update_dialog_message
-            }
-        }
-        return CustomProgressDialog.show(getString(title), getString(message))
-    }
-
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt:454]: This method was no longer referenced and didn't have any reason to still exist.

Relates to this comment: https://github.com/woocommerce/woocommerce-android/pull/4379/files#r665795324

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 3]
```diff
@@ -697,15 +698,15 @@ class ProductDetailViewModel @Inject constructor(
...
                 string.product_detail_publish_product_draft_success
             } else {
                 string.product_detail_publish_product_success
             }
         } else {
-            if (isDraftProduct()) {
+            if (requestedProductStatus == DRAFT) {
                 string.product_detail_publish_product_draft_error
             } else {
                 string.product_detail_publish_product_error
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:712]: In order to update a product status, we call `addProduct()` to safely store the change inside the Woo Site, this method also set the `viewState.productDraft` to null right after finishing the POST request, since everything was submitted and now there's no product draft as there's no unsubmitted change. 

With that said, the reason for this bug was the fact that the `isDraftProduct` method goes to the `viewState.productDraft` to verify if the `status` is of `DRAFT` type, this will always return false on this scenario since the `productDraft` will be null after we submit the change, so instead of relying upon a product state, the `pickAddProductRequestSnackbarText` decides with text to show at the Snackbar considering the new status change requested.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt [hunk 4]
```diff
@@ -334,11 +334,9 @@ class ProductDetailViewModel_AddFlowTest : BaseUnitTest() {
 
         viewModel.start()
 
-        // change the status to draft so we can verify that isDraftProduct works - this will also
-        // force the viewModel to consider the product as changed, so when we click the back button
+        // this will force the viewModel to consider the product as changed, so when we click the back button
         // below it will show the discard dialog
         viewModel.updateProductDraft(productStatus = DRAFT)
-        assertThat(viewModel.isDraftProduct()).isTrue()
```
Comment (ThomazFB) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel_AddFlowTest.kt:341]: I was looking to avoid keeping an unreferenced method just to leave the unit test untouched, after evaluating this test behavior, I decided that it was safe to remove this assert since the main one will already fail if the `DRAFT` status is not set, which is the main assertion objective.

**Comment by hafizrahman** [comment]
> Observe that a "Product published" notice is displayed briefly at the bottom of the screen.

I think you meant "Product draft saved" there in the testing steps, otherwise everything works good in my tests!

**Review by hafizrahman — APPROVED** [review]
Code LGTM! Nice work with cleaning up unneeded code as well 🥳
