### PR TITLE
[Product Subscriptions] Handle downloadable files + fixes

### LINKED ISSUE #10174: Enable download files for subscription product types

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #10174 

### Description
This PR has three main changes:
1. Allows adding downloadable files to subscription products 4ebe63b and 86ef049.
2.  Adds "Linked Products" to the "more details" bottom sheet for subscriptions, we were allowing editing the option, but not adding it. bebffa2
3. Hides the "shipping" section for variable subscriptions p1700123140841619/1700057044.683779-slack-C03L1NF1EA3 536aadd

I also aligned the order of the fields between the different product types.

### Images/gif
| Before | After |
| --- | --- |
| Screenshot_20231116_095957 |Screenshot_20231116_095825 |
| Screenshot_20231116_100006 | Screenshot_20231116_095848 |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt [hunk 1]
```diff
@@ -188,8 +188,8 @@ class ProductDetailCardBuilder(
                 product.tags(),
                 product.shortDescription(),
                 product.linkedProducts(),
-                product.productType(),
-                product.downloads()
+                product.downloads(),
+                product.productType()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailCardBuilder.kt:193]: This is unrelated to the PR, I noticed that the order for simple products is different than the other types, where the product type is the last row for all of them. I believe this was just an accidental change due to a merge conflict (26145a7c3f7d86eee75eb7bdfed7a816706bd1d1), so I fixed it.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Nice job @hichamboushaba code looks good and changes work as expected. :shipit:
