### PR TITLE
Fix crash on site picker for accounts without woo sites

### LINKED ISSUE #10553: NoSuchElementException: Collection contains no element matching the predicate.
Sentry Issue: [WOOCOMMERCE-ANDROID-8J5](https://a8c.sentry.io/issues/4641555369/?referrer=github_integration)

```
NoSuchElementException: Collection contains no element matching the predicate.
    at com.woocommerce.android.ui.sitepicker.SitePickerViewModel.onContinueButtonClick(SitePickerViewModel.kt:466)
    at com.woocommerce.android.ui.sitepicker.SitePickerViewModel.onContinueButtonClick$default(SitePickerViewModel.kt:465)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment.updateStoreListView$lambda$3(SitePickerFragment.kt:247)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment.$r8$lambda$1KVl_jOqxi2Szi9OEHJvfQGRjlA(SitePickerFragment.kt:0)
    at com.woocommerce.android.ui.sitepicker.SitePickerFragment$$InternalSyntheticLambda$1$9287dcfcb461aad35295102d63e0b960f6c8c41b26af1f2238e09591e6a8223e$0.onClick(R8$$SyntheticClass:0)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by irfano**
Closes: #10553 

### Description

This fixes a crash that occurs when using the wrong account that does not have any Woo sites. When the mismatch screen is displayed, the primary button on the site picker screen was always visible. This PR checks existing woo sites to set the visibility of the primary button. 

### Steps to reproduce

1. Open the login flow and enter a Woo site address.
2. Enter your WP account that does not have any Woo sites.
3. When the jetpack connection error screen is displayed, navigate back.
4. On the site picker screen tap the "Continue" button.

### Testing information

- [ ] Login with an account that has Woo site (but wrong site)
- [ ] Login with an account without any Woo sites.

### The tests that have been performed

I tested the mismatch account screen with accounts that have Woo sites and accounts without any Woo sites.

### Images/gif

|before|after|
|-|-|
|| |

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/242">21.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt [hunk 1]
```diff
@@ -376,6 +376,31 @@ class SitePickerViewModelTest : BaseUnitTest() {
             assertThat(viewModel.event.value).isEqualTo(NavigateToAccountMismatchScreen(CONNECT_JETPACK, url))
         }
 
+    @Test
+    fun `given the site address does not match the user account and there is no woo site, continue button is hidden`() =
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModelTest.kt:380]: ❤️

**Review by hichamboushaba — APPROVED** [review]
Nice work @irfano, kudos for taking the time to find the root cause and not just make any attempts to hide the crash by catching the exception.

**Comment by irfano** [comment]
> ## Suspect Issues
> This pull request was deployed and Sentry observed the following issues:
> 
> * ‼️ **NullPointerException** `com.woocommerce.android.ui.sitepicker.SitePicke...` [View Issue](https://a8c.sentry.io/issues/6036834610/?referrer=github-pr-bot)

@atorresveiga, this crash was introduced in "20.9-rc-1." I'll monitor the trend, and if it appears significant, I may target the beta branch. Just keeping you informed since you’re managing the release.
