### PR TITLE
Issue/12108 fix crash on stats card

### LINKED ISSUE #12108: UninitializedPropertyAccessException: lateinit property statsTimeRangeSelection has not been initialized
Sentry Issue: [WOOCOMMERCE-ANDROID-C30](https://a8c.sentry.io/issues/5591026550/?referrer=github_integration)

```
UninitializedPropertyAccessException: lateinit property statsTimeRangeSelection has not been initialized
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.getChartXAxisLabelCount(DashboardStatsView.kt:229)
    val resId = when (statsTimeRangeSelection.selectionType) {
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.updateChartView(DashboardStatsView.kt:587)
    labelCount = getChartXAxisLabelCount()
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.updateView(DashboardStatsView.kt:392)
    updateChartView()
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsCardKt$StatsChart$2.invokeSuspend(DashboardStatsCard.kt:206)
    statsView.updateView(revenueStatsState.revenueStats)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12108 

### Description
This crash happens when we try to access the property `DashboardStatsView#statsTimeRangeSelection` before it gets initialized.

In the past, there was an [attempt](https://github.com/woocommerce/woocommerce-android/pull/11824) to fix this crash, but it didn't work well, it just resulted in a change of the stacktrace that leaded to a new Sentry issue being created.

In this PR, I'm attempting a new fix, my theory is that the cause of the crash is that we are passing a nullable `dateRange` argument to the `Composable` function, this nullable value comes from a call to `observeAsState`, the value would be `null` when we read it before the `LiveData` was initialized, and this can happen when the `dateRangeState` initialization takes longer than the time reading the stats takes, and here we have a race between two flows:
1. The stats are [read](https://github.com/woocommerce/woocommerce-android/blob/01ed20fb72073d2054f89e6141ced69da33ff4ac/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/data/StatsRepository.kt#L118) from the DB when we have a cache.
2. The `dateRangeState` will need data from both the `DataStore` and the `SharedPrefs`.

Now when `2` takes longer than `1`, we end up with the crash.

### Steps to reproduce
1. Apply the following patch on `trunk`:
```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt	(revision b232ce7bfab904abf2dabab7b2aed18d858aacf4)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt	(date 1721751399851)
@@ -38,6 +38,7 @@
 import dagger.hilt.android.lifecycle.HiltViewModel
 import kotlinx.coroutines.ExperimentalCoroutinesApi
 import kotlinx.coroutines.coroutineScope
+import kotlinx.coroutines.delay
 import kotlinx.coroutines.flow.MutableSharedFlow
 import kotlinx.coroutines.flow.MutableStateFlow
 import kotlinx.coroutines.flow.SharingStarted
@@ -91,6 +92,7 @@
         customDateRangeDataStore.dateRange,
         selectedChartDate
     ) { selectedRange, custom, selectedDate ->
+        delay(500)
         DateRangeState(
             rangeSelection = selectedRange,
             customRange = custom,
```
2. Launch the dashboard multiple times.
3. The app should crash.

### Testing information
1. Switch to the branch of this PR.
2. Apply the same patch from above.
3. Confirm the app doesn't crash.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
@JorgeMucientes I reverted the changes of your previous PR before attempting to fix this, please let me know if you have any concerns with this.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt [hunk 1]
```diff
@@ -49,7 +49,7 @@ fun DashboardStatsCard(
         }
     )
 ) {
-    val dateRange by viewModel.dateRangeState.observeAsState()
+    val dateRange = viewModel.dateRangeState.observeAsState().value ?: return
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt:52]: With this, while we initialize the `dateRangeState` property, the Composable won't show nothing, thus preventing the chance of the crash. Also, this won't be noticeable by the user, as we talk about milliseconds here.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by JorgeMucientes — APPROVED** [review]
Nice job @hichamboushaba. The code changes make sense and so does the explanation. It worked well in my tests. 
I was clearly mistaken thinking the race condition was caused by the `LaunchedEffect` async nature. 
Thanks for properly fixing this 👍🏼
