### PR TITLE
Fix localization crash on date shipped button in Add Order Tracking view

### LINKED ISSUE #1164: Shipment Tracking: Crash adding shipment tracking when device is set to language other than EN-US
**Describe the bug**

When my device is set to a language other than US English (EN-US), trying to add shipment tracking causes the app to crash.

The app can crash at two points:

1. If I tap the "Date shipped" field while adding the tracking.
2. When I tap "Add" after entering shipment details (if I don't tap the date field).

**To Reproduce**
1. Set your device language to something other than US English (e.g. UK English, Spanish).
2. Go to Orders.
3. Select an order with the Processing status.
4. Select Fulfill Order.
5. Select Add Tracking.
6. Tap on the date under "Date shipped" on the Add Tracking screen. Result: Crash.
7. Reopen the app and try to add tracking again. Enter a provider and tracking number and tap "Add" (without changing the date). Result: Crash.

**Expected behavior**

When I tap the "Date shipped" field, I expect a date picker to open. If I don't tap that field, I expect to be able to add shipment tracking with the selected date and other details I've entered.

Everything works as expected when the device is set to US English.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 2.1-rc-1

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1164 localization crashes by adding some logic to properly parse localized date strings. Also fixed the style of this button that had lost it's style since the default transparent button style was removed from the app theme due to conflicts in this same release. 

## To Test
Follow the same instructions listed in the original ticket #1164 

## Style fixes
Before and after shots:

 

## Note
This PR targets the `release/2.1` branch since this is a fix for the active beta cycle. These changes will also need to be merged into `develop`. cc: @jtreanor

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingFragment.kt [hunk 1]
```diff
@@ -18,12 +18,13 @@ import com.woocommerce.android.analytics.AnalyticsTracker.Stat.ORDER_SHIPMENT_TR
 import com.woocommerce.android.tools.NetworkStatus
 import com.woocommerce.android.ui.base.UIMessageResolver
 import com.woocommerce.android.ui.main.MainActivity.Companion.BackPressListener
+import com.woocommerce.android.util.DateUtils
+import org.wordpress.android.fluxc.utils.DateUtils as FluxCDateUtils
```
Comment (anitaa1990) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/AddOrderShipmentTrackingFragment.kt]: TIL'd about this 😄

**Comment by anitaa1990** [comment]
Thanks @AmandaRiu @nbradbury for taking this up 👍
