### PR TITLE
Use comma decimal separator in Currency Edit Text

### LINKED ISSUE #6213: Order Creation: Decimal values are rounded if decimal separator is a comma
**Describe the bug**

WooCommerce settings include a "Decimal separator" setting. This can be used to make the decimal separator on your store e.g. a comma instead of a period.

In Order Creation, if the decimal separator is a comma, the shipping and fee amounts are rounded to a whole amount (removing any decimal values from what I entered).

**To Reproduce**
1. In wp-admin, go to WooCommerce > Settings > Currency options > Decimal separator and set it to `,` (comma).
2. In the app, go to the Order tab and create a new order.
3. Tap "Add shipping".
4. Enter an amount with a decimal value (e.g. `$1,23`) and tap "Done."
5. Notice the new order screen now shows a Shipping amount but it is rounded (e.g. `$1,00`) instead of matching the amount entered.

You can repeat the same steps with a fee instead of shipping, with the same results.

**Screenshots**

Note that in my screenshots I was testing various unusual currency options, but the issue can be reproduced by only changing the decimal separator setting.

Add Shipping|New Order with rounded shipping
-|-
Screenshot_20220408-140140|Screenshot_20220408-140148

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #6213

### Description
`toBigDecimalOrNull` returns `null` when using a different decimal separator than `.`  I updated the code to replace the current decimal separator with `.` before converting the value to BigDecimal.

### Testing instructions

- In wp-admin, go to WooCommerce > Settings > Currency options > Decimal separator and set it to , (comma).

#### 1) Testing shipping

1. In the app, go to the Order tab and create a new order.
2. Tap "Add shipping".
3. Enter an amount with a decimal value (e.g. $1,23) and tap "Done."
4. Check that in the new order screen Shipping matches the amount entered (e.g $1,23).

---------------------
#### 2) Testing fees

1. In the app, go to the Order tab and create a new order.
2. Tap "Fees".
3. Enter an amount with a decimal value (e.g. $1,23) and tap "Done."
4. Check that in the new order screen Fees matches the amount entered (e.g $1,23).

### Images/gif

https://user-images.githubusercontent.com/18119390/166502333-24fa7bba-3ebe-492d-9122-bbc1056fd57f.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedCurrencyEditTextView.kt [hunk 1]
```diff
@@ -282,7 +282,7 @@ private class RegularCurrencyEditText(context: Context) : CurrencyEditText(conte
                 updatedText
             } else text
 
-            _value.value = text?.toString()?.toBigDecimalOrNull()
+            _value.value = text?.toString()?.replace(decimalSeparator, ".")?.toBigDecimalOrNull()
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedCurrencyEditTextView.kt:285]: @atorresveiga This fix is good and I'll merge it shortly. I'm wondering, though, if we need to do an audit of the app to see if this same issue happens elsewhere?

**Review by nbradbury — APPROVED** [review]
:shipit:

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedCurrencyEditTextView.kt (hunk 1 above)
Comment (atorresveiga) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCMaterialOutlinedCurrencyEditTextView.kt:285]: > I'm wondering, though, if we need to do an audit of the app to see if this same issue happens elsewhere?

Great question, @nbradbury. As the fix was on the EditText control itself, I believe we are safe from seeing this again 🤔
