### PR TITLE
Issue/6262 fix order filters count

### LINKED ISSUE #6262: Order list incorrectly shows applied filter
When I visit the order list, it shows that two filters are applied even though there are no filters. This persists even after clearing storage or uninstalling the app.

filter

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #6262 

### Description
When I visit the order list, it shows that two filters are applied even though there are no filters. This persists even after clearing storage or uninstalling the app.

We recently applied some [changes](https://github.com/woocommerce/woocommerce-android/pull/6159) in `AppPrefsWrapper`. Ideally, these changes shouldn't have any impact on the default values returned from preferences when there is no persisted value for a given key. But in that refactor we missed one method that it was returning `null` before the changes and now returns an empty string. This caused the bug where we returned a non-empty list of selected filters with just one element: an empty string. This caused `GetSelectedOrderFiltersCount` to wrongly calculate there are 2 filters selected.  

I initially applied [the missing call](https://github.com/woocommerce/woocommerce-android/pull/6264/commits/24075cc2bcd710eb3ed523770610e0f8eb746267) to  the function `.orNullIfEmpty()`, which is what we missed in this [PR](https://github.com/woocommerce/woocommerce-android/pull/6159). This ensures we return null value in case there is nothing saved in preferences for order filters. But given how `GetSelectedOrderFiltersCount` is implemented I thought this could be risky as changes in the future over the code could potentially lead to the same problem. Instead i applied a small fix in `OrderFiltersRepository` that ensures there are no blank elements inside the returned filter values from preferences.

### Testing instructions
- Open order list
- Check the value for filters tag matches the number of selected filters. 
- Select unselect different combination of filters and check the value is properly updated.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt [hunk 1]
```diff
@@ -9,7 +9,18 @@ import android.content.SharedPreferences.Editor
 import androidx.preference.PreferenceManager
 import com.woocommerce.android.AppPrefs.CardReaderOnboardingStatus.CARD_READER_ONBOARDING_COMPLETED
 import com.woocommerce.android.AppPrefs.CardReaderOnboardingStatus.CARD_READER_ONBOARDING_NOT_COMPLETED
-import com.woocommerce.android.AppPrefs.DeletablePrefKey.*
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt:12]: I have wildcards disabled as FluxC repo does not allow them through ktlint. In wc-android we don't have any rule that enforces us to avoid wildcard imports. I'm not sure if there is an agreement across the team on this but I think we shouldn't use them. In anycase let me know if i should revert this change.

**Review by nbradbury — APPROVED** [review]
Fix is good! We're having CI issues right now (unrelated to this PR), so I've enabled auto-merge.

**Comment by JorgeMucientes** [comment]
Heads up there are 2 failing workflows on circleCI unrelated to the changes from this PR. In fact the equivalent flows on Builkite passed without issues. I've reported the issue to #platform9 as there I think it is related to my user. More on the topic p1649948213279729-slack-CC7L49W13

So you can basically ignore those checks failing.

**Comment by JorgeMucientes** [comment]
Ok, I think we overlapped writing the message @nbradbury 🙂

Thanks for the review. I'll wait till issues are fixed to relaunch those workflows.

**Comment by nbradbury** [comment]
@JorgeMucientes Looks like our CI issues are resolved so I'm rerunning the checks.
