### PR TITLE
Handle fetching variations when duplicating variable products

### LINKED ISSUE #10232: Duplicating variable products doesn't work well
When trying to duplicate a variable product, if the app didn't fetch the variations before, the duplication would fail.

1. Create a variable product and some variations in wp-admin.
2. Open the product in the app.
3. Click on Duplicate.
4. Notice the failure.

This impacts Variable Subscriptions as well.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #10232 

### Description
Currently, when trying to duplicate a variable product, we use try to duplicate just the list of cached variations, which causes two issues:
1. The request fails when we try to duplicate a product for which we didn't fetch the variations yet.
2. We might use outdated data when the cached data is not up-to-date.

This PR adds logic to actually fetch variations before proceeding to duplicating them.

### Testing instructions
1. Create a variable product and some variations in wp-admin.
2. Open the product in the app.
3. Click on Duplicate.
4. Confirm the duplication works correctly, and the variations have correct data.

**Repeat also for a variable subscription.**

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/DuplicateProduct.kt [hunk 1]
```diff
@@ -49,9 +50,23 @@ class DuplicateProduct @Inject constructor(
...
+                isLoadingMore = true
+            } while (variationRepository.canLoadMoreProductVariations)
+        }.also {
+            if (it.size > 100) {
+                // The API doesn't allow to create more than 100 variations at once
+                WooLog.w(
+                    WooLog.T.PRODUCTS, "Variations list is too big: ${it.size}, " +
+                        "the duplicate will have only the first 100 variations"
+                )
+            }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/DuplicateProduct.kt]: The endpoint we use for the variations creation can handle only 100 items (https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-product-variations), while we can make multiple calls to handle the creation in this case, I think it's not worth it, as this should be a very rare case, WDYT?

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/DuplicateProduct.kt]: I agree.

**Review by 0nko — APPROVED** [review]
:shipit:
