### PR TITLE
Fix crash during logout

### LINKED ISSUE #5946: Crash during logout
**Describe the bug**
When I logout the app crashes with the following exception:
```
FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.woocommerce.android.dev, PID: 12315
    java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:48)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:220)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:13)
        at com.woocommerce.android.push.UnseenReviewsCountHandler$special$$inlined$flatMapLatest$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1.emit(Collect.kt:140)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$invokeSuspend$$inlined$collect$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**To Reproduce**
1. Go to More sectoin
2. Click on App settings
3. Click on "Logout"
4. See crash

**Expected behavior**
The app should not crash and should redirect the user to the login screen

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #5946

### Description
This PR just makes sure `null` values are ignored in the Flow returned from `selectedSite.observe()`, to avoid crashing the app on logout.

@jkmassel we need a new beta release to include this fix, if we are not already planning for one.

### Testing instructions

1. Go to More sectoin
2. Click on App settings
3. Click on "Logout"
4. Confirm the app doesn't crash

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt [hunk 1]
```diff
@@ -15,15 +15,17 @@ import javax.inject.Singleton
 class UnseenReviewsCountHandler @Inject constructor(
     @AppCoroutineScope private val appCoroutineScope: CoroutineScope,
     private val notificationStore: NotificationStore,
-    private val selectedSite: SelectedSite
+    selectedSite: SelectedSite
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt:18]: ❓ Is this change intentional?

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt:18]: Since we get the current site from the Flow returned in `selectedSite.observe()`, I updated the code to use it directly instead of making a separate call to `selectedSite.get()` [here](https://github.com/woocommerce/woocommerce-android/blob/626d2198c96165ae8f0d7c3caee2fc6e3b2d5841/WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt#L25), with this change, the `selectedSite` property became a property that's not used outside of the initialization, so Android Studio suggested removing the `val` keyword.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt [hunk 2]
```diff
@@ -15,15 +15,17 @@ import javax.inject.Singleton
...
 ) {
     private val unseenReviewsCount: SharedFlow<Int> =
-        selectedSite.observe().flatMapLatest {
-            notificationStore.observeNotificationsForSite(
-                site = selectedSite.get(),
-                filterBySubtype = listOf(STORE_REVIEW.toString())
-            )
-        }
+        selectedSite.observe()
+            .filterNotNull()
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: ❓ I'm wondering if this will work as expected. If selected site becomes null, will the app cancel `observeNotificationsForSite`? Tbh I'm not sure how `flatMapLatest` behaves, but I'd expect it cancels the original only when a new value reaches it -> which it doesn't because of the `filterNotNull`. Wdyt?

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: We could perhaps do something like
```
selectedSite.observe().flatMapLatest {
            if (it == null) {
                emptyFlow()
            } else {
                notificationStore.observeNotificationsForSite(
                    site = selectedSite.get(),
                    filterBySubtype = listOf(STORE_REVIEW.toString())
                )
            }
        }
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt (hunk 1 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt:18]: ahhh, I see :). Thanks for the clarification!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: This is a valid question.
> I'm not sure how flatMapLatest behaves, but I'd expect it cancels the original only when a new value reaches it

Yes, you are right, it won't cancel the original Flow.

But is this an issue? currently it's not, since for all cases where the `selectedSite` might send a `null` value, the use is either logged out, or the site is no longer available, and we will be showing either the login screen or the site picker, which means keeping the `notificationStore.observeNotificationsForSite` doesn't hurt, as we won't read the number of unread reviews.
It's even more, the `unseenReviewsCount` SharedFlow will most probably be cancelled on this case due to the usage of `SharingStarted.WhileSubscribed()`, as we will be leaving the More screen, the Flow will be cancelled, and will cause cancelling of the `SharedFlow` as well.

Still I agree with you, it's worth fixing, just to make the component more resilient to changes, let's say for example we start showing the number of unread notifications in another place that doesn't get cancelled during logout, I'll push a commit to update its logic.

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: > Still I agree with you, it's worth fixing, just to make the component more resilient to changes, 

This was my main concern. This is a type of code which is just a ticking bomb. Thanks for working on a fix!

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: Check my last commit: ee50667, I opted for returning a `flowOf(emptlyList)` to make sure we notify any observer that the number of unread notifications changed to `0` after moving to a `null` site.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: I'll add a test for this case to make sure it's documented.

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: The code I proposed in the previous comment might not work either, I'm not sure. If we use `emptyFlow` or `flowOf(emptyList)` the `map` and `distinctUntilChanged` won't get invoked as the empty flow won't emit anything. I'm wondering how `shareIn` works in such cases -> should we emit `0` for the `site==null` case?

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: [Perhaps something like this might work - wdyt?](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS41LjMxIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoicGFja2FnZSBjb20ud29vY29tbWVyY2UuYW5kcm9pZC5wdXNoXG5cbmltcG9ydCBjb20ud29vY29tbWVyY2UuYW5kcm9pZC5kaS5BcHBDb3JvdXRpbmVTY29wZVxuaW1wb3J0IGNvbS53b29jb21tZXJjZS5hbmRyb2lkLnRvb2xzLlNlbGVjdGVkU2l0ZVxuaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy5Db3JvdXRpbmVTY29wZVxuaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy5FeHBlcmltZW50YWxDb3JvdXRpbmVzQXBpXG5pbXBvcnQga290bGlueC5jb3JvdXRpbmVzLmZsb3cuKlxuaW1wb3J0IG9yZy53b3JkcHJlc3MuYW5kcm9pZC5mbHV4Yy5tb2RlbC5TaXRlTW9kZWxcbmltcG9ydCBvcmcud29yZHByZXNzLmFuZHJvaWQuZmx1eGMubW9kZWwubm90aWZpY2F0aW9uLk5vdGlmaWNhdGlvbk1vZGVsLlN1YmtpbmQuU1RPUkVfUkVWSUVXXG5pbXBvcnQgb3JnLndvcmRwcmVzcy5hbmRyb2lkLmZsdXhjLnN0b3JlLk5vdGlmaWNhdGlvblN0b3JlXG5pbXBvcnQgamF2YXguaW5qZWN0LkluamVjdFxuaW1wb3J0IGphdmF4LmluamVjdC5TaW5nbGV0b25cblxuQEV4cGVyaW1lbnRhbENvcm91dGluZXNBcGlcbkBTaW5nbGV0b25cbmNsYXNzIFVuc2VlblJldmlld3NDb3VudEhhbmRsZXIgQEluamVjdCBjb25zdHJ1Y3RvcihcbiAgICBAQXBwQ29yb3V0aW5lU2NvcGUgcHJpdmF0ZSB2YWwgYXBwQ29yb3V0aW5lU2NvcGU6IENvcm91dGluZVNjb3BlLFxuICAgIHByaXZhdGUgdmFsIG5vdGlmaWNhdGlvblN0b3JlOiBOb3RpZmljYXRpb25TdG9yZSxcbiAgICBzZWxlY3RlZFNpdGU6IFNlbGVjdGVkU2l0ZVxuKSB7XG4gICAgcHJpdmF0ZSB2YWwgdW5zZWVuUmV2aWV3c0NvdW50OiBTaGFyZWRGbG93PEludD4gPVxuICAgICAgICBzZWxlY3RlZFNpdGUub2JzZXJ2ZSgpLmZsYXRNYXBMYXRlc3QgeyBzaXRlIC0+XG4gICAgICAgICAgICBpZiAoc2l0ZSA9PSBudWxsKSB7XG4gICAgICAgICAgICAgICAgZmxvd09mKDApXG4gICAgICAgICAgICB9IGVsc2Uge1xuICAgICAgICAgICAgICAgIG9ic2VydmVDdXJyZW50U2l0ZU5vdGlmQ291bnQoc2l0ZSlcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgICAgICAgLnNoYXJlSW4oXG4gICAgICAgICAgICAgICAgc2NvcGUgPSBhcHBDb3JvdXRpbmVTY29wZSxcbiAgICAgICAgICAgICAgICBzdGFydGVkID0gU2hhcmluZ1N0YXJ0ZWQuV2hpbGVTdWJzY3JpYmVkKCksXG4gICAgICAgICAgICAgICAgcmVwbGF5ID0gMVxuICAgICAgICAgICAgKVxuXG4gICAgcHJpdmF0ZSBmdW4gb2JzZXJ2ZUN1cnJlbnRTaXRlTm90aWZDb3VudChzaXRlOiBTaXRlTW9kZWwpID0gbm90aWZpY2F0aW9uU3RvcmUub2JzZXJ2ZU5vdGlmaWNhdGlvbnNGb3JTaXRlKFxuICAgICAgICBzaXRlID0gc2l0ZSxcbiAgICAgICAgZmlsdGVyQnlTdWJ0eXBlID0gbGlzdE9mKFNUT1JFX1JFVklFVy50b1N0cmluZygpKVxuICAgIClcbiAgICAgICAgLm1hcCB7IGl0LmNvdW50IHsgbm90aWZpY2F0aW9uIC0+ICFub3RpZmljYXRpb24ucmVhZCB9IH1cbiAgICAgICAgLmRpc3RpbmN0VW50aWxDaGFuZ2VkKClcblxuICAgIGZ1biBvYnNlcnZlVW5zZWVuQ291bnQoKTogRmxvdzxJbnQ+ID0gdW5zZWVuUmV2aWV3c0NvdW50XG59XG4ifQ==)

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: > Perhaps something like this might work - wdyt?

Unless I'm missing something, it's the same code as using `flowOf(emptyList)`, since the `map` block will calculate the `count` on the emptyList, which would be `0`.

I think with the test it'll become clearer, I'm working on it right now.

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandler.kt]: ahh, you are right! I didn't realize that the list will actually get passed as an event. In that case, I think we are good! Thanks!

**Review by malinajirka — APPROVED** [review]
Tested and it works as expected! Great job and thanks for the discussions! I'm not merging in case you want to add tests as part of this PR.

**Comment by hichamboushaba** [comment]
Thanks @malinajirka for the review, a test case added: [5be11e1](https://github.com/woocommerce/woocommerce-android/pull/5947/commits/5be11e19eb5d2607c5e9a7e48fcc4fcea030248b) if you want to take a look 🙏.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import kotlinx.coroutines.test.TestCoroutineScope
+import org.assertj.core.api.Assertions.assertThat
+import org.junit.Before
+import org.junit.Test
+import org.mockito.kotlin.doReturn
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.whenever
+import org.wordpress.android.fluxc.store.NotificationStore
+
+// TODO add more test cases
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt:15]: I opted to leave this TODO comment here since IMO this is a component that needs to be properly tested in the future 🙂.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+        handler = UnseenReviewsCountHandler(
+            appCoroutineScope = TestCoroutineScope(coroutinesTestRule.testDispatcher),
+            notificationStore = notificationStore,
+            selectedSite = selectedSite
+        )
+    }
+
+    @Test
+    fun `when we get a null site, then emit 0 as count of unread reviews`() = testBlocking {
+        setup {
```
Comment (malinajirka) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt:33]: Nice solution for the eager initialisation! ❤️

**Comment by malinajirka** [comment]
Thanks for the test! Looks great. When the detekt issues are fixed, we can merge this 🚢

File: WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+import com.woocommerce.android.viewmodel.BaseUnitTest
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.flow.first
+import kotlinx.coroutines.flow.flowOf
+import kotlinx.coroutines.launch
+import kotlinx.coroutines.test.TestCoroutineScope
+import org.assertj.core.api.Assertions.assertThat
+import org.junit.Before
+import org.junit.Test
+import org.mockito.kotlin.doReturn
```
[the remark this answers is not in the document]
Comment (hichamboushaba) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/push/UnseenReviewsCountHandlerTests.kt]: 🤦
