### PR TITLE
[Compose] Fix back button orientation in RTL languages

### LINKED ISSUE #8252: [Compose] The back button has the wrong direction in RTL screens
In the Compose screens that use the composable `Toolbar`, the back buttons is not mirrored in the RTL screens, and it shows with the wrong direction:

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8252 

### Description
This PR aims at fixing the orientation of the back button in RTL languages, I did the fix in the `Toolbar` component, then I updated all of the Compose screens that weren't migrated last time to start using it.

When I wanted to start the migration, I found it hard to know which defaults the Toolbar would have, so I attempt a small refactor to the overloads to make it clear:
1. By default all of the `Toolbar` components have an optional navigation icon and its callback, and by default, it shows the back button.
2. We control the visibility of the navigation icon just with the `navigationIcon` property, meaning it's OK to have a non-null callback with a null `navigationIcon`. The goal of this is to make it easier to work with the component when the visibility of the button is conditional, so instead of having to remove the callback, we just nullify the `navigationIcon`. (check the comment for more clarification around the error check)
3. By default all of the `Toolbar` variants don't show any action button.
4. I removed the default help action button from the `Toolbar` component, and I created a new one called `ToolbarWithHelpButton`, this way it's clear when we want to use it.

All of this is done in the commit [c8647ef](https://github.com/woocommerce/woocommerce-android/pull/8257/commits/c8647ef9f4db2bd3a2a080a1e32d26946e7316c9), **please tell me what you think.**

### Testing instructions
1. Set the app's language to an RTL one (Arabit for example)
2. Open the app.
3. Open any Compose screen that uses the Compose toolbar (Signup screen or coupon details one)
4. Confirm the correct orientation of the back button.

### Images/gif
| Before | After |
| --- | --- |
| Screenshot_20230126_182927 | Screenshot_20230126_183114 |

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt [hunk 1]
```diff
@@ -87,15 +141,17 @@ fun Toolbar(
...
                     Icon(
                         navigationIcon,
-                        contentDescription = navigationIconContentDescription
+                        contentDescription = navigationIconContentDescription,
+                        modifier = Modifier.autoMirror()
                     )
                 }
-            } else if (onNavigationButtonClick == null && navigationIcon != null || onNavigationButtonClick != null) {
-                error("Both onNavigationButtonClick and navigationIcon must be set")
             }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/Toolbar.kt:155]: I refactored the check and the error here to allow having a null `navigationIcon` with a non-null `onNavigationButtonClick`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt [hunk 2]
```diff
@@ -78,31 +75,20 @@ fun AccountMismatchErrorScreen(viewModel: AccountMismatchErrorViewModel) {
...
-                        }) {
-                            Icon(Icons.Filled.ArrowBack, contentDescription = "Back")
-                        }
-                    }
+            ToolbarWithHelpButton(
+                navigationIcon = if (viewState.showNavigationIcon) {
+                    Icons.Filled.ArrowBack
+                } else {
+                    null
                 },
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/accountmismatch/AccountMismatchErrorScreen.kt:83]: An example of where the `navigationIcon` is conditional, and where having a `null` navigation with a non-null callback is useful.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/ModifierExts.kt [hunk 3]
```diff
@@ -40,3 +45,11 @@ fun Modifier.drawShadow(
         )
     }
 }
+
+@Stable
+fun Modifier.autoMirror(): Modifier = composed {
+    if (LocalLayoutDirection.current == LayoutDirection.Rtl)
+        this.scale(scaleX = -1f, scaleY = 1f)
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/ModifierExts.kt:52]: Nice! 👏

**Review by 0nko — APPROVED** [review]
Looks great, Hicham! Thanks for adding the improvements!  👍
