### PR TITLE
[Product AI v2] Unit tests for the Preview viewmodel + some fixes

### LINKED ISSUE #12101: [Product AI v2] Unit tests for the preview screen

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12101 

### Description
This PR adds unit tests for:
-  `AIProductPreviewViewModel`, and while working on those, I identified one issue that I fixed, more details on the [comment](https://github.com/woocommerce/woocommerce-android/pull/12109#discussion_r1686744549) below.
- `GenerateProductWithAI` usecase.

### Testing information
Green CI should be enough, but smoke testing the product creation with AI would be great too.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/SaveAiGeneratedProduct.kt [hunk 1]
```diff
@@ -17,7 +17,7 @@ class SaveAiGeneratedProduct @Inject constructor(
     suspend operator fun invoke(
         product: Product,
         selectedImage: Product.Image?
-    ): Pair<Boolean, Long> {
+    ): Result<Long> {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/SaveAiGeneratedProduct.kt:20]: This is unrelated to the PR, just an improvement to the API by returning a `Result` instead of a `Pair`.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt [hunk 2]
```diff
@@ -227,51 +228,53 @@ class AiProductPreviewViewModel @Inject constructor(
         val product = generatedProduct.value?.getOrNull()?.toProduct(selectedVariant.value) ?: return
         savingProductState.value = SavingProductState.Loading
         viewModelScope.launch {
-            uploadSelectedImage()
+            val image = uploadSelectedImage().onFailure {
+                return@launch
+            }.getOrNull()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt:233]: While working on the tests, I identified an issue with this logic, we were continuing with the product saving regardless of whether the image upload succeeded or not, so I updated the logic of `uploadSelectedImage` to return a `Result` that allows us to differentiate between its success and failure.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductModel.kt [hunk 3]
```diff
@@ -46,29 +49,30 @@ data class AIProductModel(
 
     companion object {
         fun fromJson(
+            gson: Gson,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/AIProductModel.kt:52]: I had to switch to using `Gson` here, JSONObject is not available in unit tests, as it's an Android only API.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt [hunk 4]
```diff
@@ -87,7 +90,7 @@ class GenerateProductWithAI @Inject constructor(
     }
 
     private suspend fun getTags(): Result<List<ProductTag>> {
-        return if (isProductCategoriesFetched) {
+        return if (isProductTagsFetched) {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/GenerateProductWithAI.kt:93]: Unit tests helped identify this bug too.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModel.kt:233]: Good catch 👍🏼

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt [hunk 5]
```diff
@@ -0,0 +1,308 @@
...
+    }
+    private val uploadImage: UploadImage = mock {
+        onBlocking { invoke(any()) } doSuspendableAnswer {
+            delay(100)
+            Result.success(SAMPLE_UPLOADED_IMAGE)
+        }
+    }
+    private val saveAiGeneratedProduct: SaveAiGeneratedProduct = mock {
+        onBlocking { invoke(any(), anyOrNull()) } doSuspendableAnswer {
+            delay(100)
```
Comment (JorgeMucientes) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt:53]: Out of curiosity, what is the reason for adding a delay to these mocked answers?

**Review by JorgeMucientes — APPROVED** [review]
Excellent work @hichamboushaba. Great tests and nice findings catching those bugs. 
Code looks great, I just left a question out of curiosity about the mocking approach. 
:shipit: 

PS: I smoke tested the flow and everything worked well.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt (hunk 5 above)
Comment (hichamboushaba) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt:53]: I should've put a comment here, sorry.
The goal of the `delay` is just to enforce a suspension, which allows to read the intermediate values of the observable `Flows` (for example the `Loading` value), with this, we need to make an explicit call to `advanceUntilIdle` before the test `Dispatcher` will advance the time to go past this delay.

Comment (JorgeMucientes) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ai/preview/AiProductPreviewViewModelTest.kt:53]: Thanks for clarifying, and nice way to be able to access intermediate values TIL 👍🏼
