### PR TITLE
Stop the menu crash on Product details and add logs to identify the cause

### LINKED ISSUE #3241: IllegalStateException: menu.findItem(R.id.menu_view_product) must not be null
Happening to 5 users (4 events) in the latest beta. (5.6-rc-1)

Sentry Issue: [WOOCOMMERCE-ANDROID-135](https://sentry.io/organizations/a8c/issues/2064324271/?referrer=github_integration)

```
IllegalStateException: menu.findItem(R.id.menu_view_product) must not be null
    at com.woocommerce.android.ui.products.ProductDetailFragment.onPrepareOptionsMenu(ProductDetailFragment.kt:288)
...
(19 additional frame(s) were not displayed)

menu.findItem(R.id.menu_view_product) must not be null
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
This PR is related to the issue #3241, the goal is to stop the crash, and add some logs to have more context about what's causing it in the first place.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt [hunk 1]
```diff
@@ -284,20 +286,36 @@ class ProductDetailFragment : BaseProductFragment(), OnGalleryImageInteractionLi
...
         super.onPrepareOptionsMenu(menu)
 
+        fun Menu.printItems(): String = buildString {
+            this@printItems.forEach {
+                append("${resources.getResourceName(it.itemId)}\n")
+            }
+        }
+
+        if (menu.findItem(R.id.menu_view_product) == null) {
+            val message = """menu.findItem(R.id.menu_view_product) is null
```
Comment (AliSoftware) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt:300]: nit, but I think it could be worth adding a comment to reference the GH issue (3241) somewhere here to explain why we go to all that null check dance and log things 🙃

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt:300]: Yes, a comment explaining what's going on here will be useful 👍

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt:300]: Done b3fde86b908df8ff1944aab9b2cbc01108dc67be

**Review by nbradbury — APPROVED** [review]
Looks good, and good idea to add all the menu items to the message :shipit:

**Comment by AliSoftware** [comment]
Thanks for the PR! This fix has been included in the new beta 5.6-rc-3.
