### PR TITLE
[Notifications] Fix for ConcurrentModificationException while handling notification

### LINKED ISSUE #12636: ConcurrentModificationException
Sentry Issue: [WOOCOMMERCE-ANDROID-9X2](https://a8c.sentry.io/issues/5131035834/?referrer=github_integration)

```
RuntimeException: Unable to start service com.woocommerce.android.notifications.NotificationsProcessingService@aed6fad with Intent { cat=[action_dismiss] cmp=com.woocommerce.android/.notifications.NotificationsProcessingService (has extras) }: java.util.ConcurrentModificationException
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4808)
    at android.app.ActivityThread.access$2100(ActivityThread.java:271)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2163)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
...
(5 additional frame(s) were not displayed)

ConcurrentModificationException: None
    at com.woocommerce.android.notifications.push.NotificationMessageHandler.removeNotificationByNotificationIdFromSystemsBar(NotificationMessageHandler.kt:243)
    .forEach { row ->
    at com.woocommerce.android.notifications.push.NotificationMessageHandler.onPushNotificationDismissed(NotificationMessageHandler.kt:56)
    removeNotificationByNotificationIdFromSystemsBar(notificationId)
    at com.woocommerce.android.notifications.NotificationsProcessingService$ActionProcessor.process(NotificationsProcessingService.kt:93)
    notificationMessageHandler.onPushNotificationDismissed(notificationId)
    at com.woocommerce.android.notifications.NotificationsProcessingService.onStartCommand(NotificationsProcessingService.kt:73)
    actionProcessor.process()
...
(13 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12636 

### Description

This PR addresses a crash peaMlT-TT-p2 related to notifications. While I couldn't reproduce the crash directly, I was able to analyze the stacktrace, identify the root cause, and reproduce the issue through a unit test.

The crash occurred because `ACTIVE_NOTIFICATIONS_MAP` was being modified concurrently by multiple threads, leading to a `ConcurrentModificationException`.

For example - In `ReviewDetailViewModel`, while loading product reviews, the map is modified on a background thread when `markReviewAsSeen(remoteReviewId, it)` is called. Simultaneously, if a new notification arrives or the user dismisses an existing notification, we attempt to modify the same `ACTIVE_NOTIFICATIONS_MAP`, which could lead to a `ConcurrentModificationException`.

The issue is resolved by adding the `@Synchronized` annotation, ensuring that only one thread can modify `ACTIVE_NOTIFICATIONS_MAP` at a time. After applying this fix, the unit test passes successfully.

### Steps to reproduce

1. Remove the `@Synchronized` annotation from `removeNotificationByNotificationIdFromSystemsBar` method
2. Run `remove notifications concurrently without throwing ConcurrentModificationException` unit test
3. Ensure the test fails with `ConcurrentModificationException`

### Testing information

I couldn't test this with real notifications, but the fact that the unit test passes after the fix provides enough confidence to assert that the `ConcurrentModificationException` crash has been resolved for this particular scenario.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt [hunk 1]
```diff
@@ -237,6 +240,7 @@ class NotificationMessageHandler @Inject constructor(
         updateNotificationsState()
     }
 
+    @Synchronized
     fun removeNotificationByNotificationIdFromSystemsBar(localPushId: Int) {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: We could use `ConcurrentHashMap` instead of `MutableMap` and remove the `@Synchronized` methods, and that would work too. However, given that concurrent access to notifications is infrequent and only happens during specific notification-related events, I opted to use the `@Synchronized` annotation for simplicity and minimal overhead.

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: Thanks for the extra info! I agree, additional argument for using synchronized is that we used to use it before [this PR](https://github.com/woocommerce/woocommerce-android/pull/10602/files) which likely introduced this crash.

**Review by malinajirka — APPROVED** [review]
Thanks @AnirudhBhat for working on this and providing detailed description! Great job reproducing it in a unit test, that gives me enough confidence these changes actually fix the issue.

I've smoke tested push notifications and they work as expected.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: @AnirudhBhat @malinajirka 👋

I would suggest to go with the thread-safe map:
* That's probably faster as we don't lock the whole object, but this is not really important
* More important, I think it is harder to break, because those @Synchronized here are not really clear why we have them here, and I think that's why they were removed. Alos, removing just 1 synchronized from any public method will return the crash, or the worst,  adding a new public method that touches the map will also cause the same issue again

Wdyt?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: @AnirudhBhat also kudos for the unit test!

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: @kidinov Thanks for the input and you raise a valid point here. My train of though was that 

1. Adding @Synchronized annotation would make it explicit that we are dealing with concurrency here and need to be careful of the modifications. 
2. While `ConcurrentHashMap` is thread safe in general. Some operation do require careful consideration before usage - especially operations that checks existing key and then update its value as these are not atomic and need to be refactored to use other methods like `putIfAbsent`.

Overall. I agree with you that with this approach, it's easy to make a mistake.I don't have a strong preference, and I can replace this implementation with `ConcurrentHashMap` in a separate PR.

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/push/NotificationMessageHandler.kt:244]: I looked up the code again, and actually, we already have public methods that don't have synchronised on them and that modify the map

```
    fun removeAllNotificationsFromSystemsBar() {
        clearNotifications()
        notificationBuilder.cancelAllNotifications()
    }
```

```
    fun markNotificationsOfTypeTapped(type: NotificationChannelType) {
        ACTIVE_NOTIFICATIONS_MAP.asSequence()
            .filter { it.value.channelType == type }
            .forEach { row ->
                analyticsTracker.trackNotificationAnalytics(PUSH_NOTIFICATION_TAPPED, row.value)
                analyticsTracker.flush()
            }
    }
```

So maybe the crash still can happen even now

Also, interestingly, even during writing the original code, it was considered that concurrent modification is possible, but no generic solution was applied

```
        // Using a copy of the map to avoid concurrency problems
        ACTIVE_NOTIFICATIONS_MAP.toMap().asSequence().forEach { row ->
```

ah, and `ACTIVE_NOTIFICATIONS_MAP` is not a constant, so it doesn't follow the naming convention

So overall yes, I'd suggest:
* Use concurrent map 
* Rename it to follow the convention
* Remove unnecessary copies of the map 
* Maybe extend the test to call all the public methods to validate the solution
