### PR TITLE
Fix the mixed out orders notes

### LINKED ISSUE #5970: Order Notes can get mixed up
The usage of `local` order id in the Order Notes SQL table without any Key constraints can cause issues when there are changes to the `Order` table that would trigger regeneration of the local id.

This can be reproduced by following these steps roughly:
1. Create a note on one of the orders.
2. Install version 8.2 of the app.
3. Open the order details of the order with the note.
4. Close the app.
5. Remove the order from the site (this might not be necessary, just to make sure the id is assigned to a different order).
6. Install version 8.3 of the app.
7. Open the order list.
8. Inspect the application’s DB, and check the column LOCAL_ORDER_ID of the WCOrderNote table for the note we created at step 1.
9. Go to the OrderEntity table, and check the Order that has the same order id as the previous step.
10. Open this order in the app, and notice the note shown there.

###### Originarlly reported in p4a5px-2Na-p2#comment-12625

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #5970 

⚠️ Please don't merge until the FluxC PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2299 is merged

### Description
This PR's goal is to fix #5970, but it was also a chance to migrate Order Notes from WellSql to Room.

##### Order notes fetching
1. Prepare an order with some notes.
2. Open order details.
3. Confirm the notes are fetched and displayed.

##### Adding order notes
1. Open order details.
2. Click on "Add note"
3. Add some text, and click on "Add"
4. Confirm the note is added and displayed in order details.

##### Adding a refund note
1. Open order details
2. Click on issue refund.
3. When requested, please enter a refund reason.
4. Finish the refund.
5. Confirm a note with the refund reason was added 

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteFragment.kt [hunk 1]
```diff
@@ -130,13 +130,12 @@ class AddOrderNoteFragment : BaseFragment(R.layout.fragment_add_order_note), Bac
...
-                    binding.addNoteIcon.setImageResource(noteIcon)
-                } else {
-                    binding.addNoteSwitch.isVisible = false
-                }
+                val noteIcon = if (it.isCustomerNote) R.drawable.ic_note_public else R.drawable.ic_note_private
+                binding.addNoteIcon.setImageResource(noteIcon)
+            }
+
+            new.showCustomerNoteSwitch.takeIfNotEqualTo(old?.showCustomerNoteSwitch) {
+                binding.addNoteSwitch.isVisible = it
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteFragment.kt:138]: This is not related to this PR, but it's a minor issue that I noticed on the screen, since we made the [code](https://github.com/woocommerce/woocommerce-android/blob/61763e980d4824c8b218544daa2c420eebd11aa8/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/notes/AddOrderNoteViewModel.kt#L70-L75) to check if the order has a billing email address suspendable, it resulted on a lazy calculation of `showCustomerNoteSwitch`, which made having it inside the `new.draftNote.takeIfNotEqualTo(old?.draftNote)` part causing the initial display of the UI not matching what the variable has, so the switch wasn't displayed until the `draftNote` was edited.

**Review by kidinov — COMMENTED** [review]
I tested it - works  fine. Ill take a look better look into the code tomorrow, lost my focus today already

**Review by kidinov — APPROVED** [review]
LGTM 👍
