### PR TITLE
Remove "See Report" button

### LINKED ISSUE #7827: [Analytics Hub] Remove the See Report button code
**Describe the bug**
This task is about removing `See Report` code so we don't have to maintain it.

Result of #7698

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #7827

### Description

This PR removes code for the feature we decided to not go in production.

### Testing instructions

Open the Analytics screen in debug and see if the layouts look correct.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsViewModelTest.kt [hunk 1]
```diff
@@ -512,7 +473,7 @@ class AnalyticsViewModelTest : BaseUnitTest() {
     }
 
     @Test
-    fun `when all data is fetched successfully then all Sentry conditions are satisfied`() = testBlocking {
+    fun `when all data is fetched successfully then all transaction conditions are satisfied`() = testBlocking {
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsViewModelTest.kt:476]: To increase readability, I've added a few changes to unit tests for the performance launcher. Hope that's fine!

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsViewModelTest.kt [hunk 2]
```diff
@@ -556,14 +517,14 @@ class AnalyticsViewModelTest : BaseUnitTest() {
 
         sut = givenAViewModel()
 
-        verify(transactionLauncher, times(1)).onRevenueFetched()
-        verify(transactionLauncher, times(0)).onOrdersFetched()
-        verify(transactionLauncher, times(1)).onProductsFetched()
-        verify(transactionLauncher, times(1)).onVisitorsFetched()
+        verify(transactionLauncher).onRevenueFetched()
```
Comment (atorresveiga) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/analytics/AnalyticsViewModelTest.kt:520]: Nice! TIL that calling the _verify_ like this will ensure only one call to the method

**Review by atorresveiga — APPROVED** [review]
Nice work @wzieba!

Everything is working as expected:

https://user-images.githubusercontent.com/18119390/202035752-abbfa6d4-a10e-45ad-96f0-ac199e38727b.mp4

LGTM! :shipit:
