### PR TITLE
[Crash] Camera with LENS_FACING_BACK not available making app crash when scanning barcode

### LINKED ISSUE #13007: IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
Sentry Issue: [WOOCOMMERCE-ANDROID-FG0](https://a8c.sentry.io/issues/5996795738/?referrer=github_integration)

```
IllegalArgumentException: Provided camera selector unable to resolve a camera for the given use case
    at com.woocommerce.android.ui.barcodescanner.BarcodeScannerKt$BarcodeScanner$1.invoke$lambda$4$lambda$3(BarcodeScanner.kt:82)
    val camera = cameraProvider.bindToLifecycle(
    at com.woocommerce.android.ui.barcodescanner.BarcodeScannerKt$BarcodeScanner$1.$r8$lambda$E9pOByP15Ihs0UvgBf31ijaQa0k(BarcodeScanner.kt:0)
    at com.woocommerce.android.ui.barcodescanner.BarcodeScannerKt$BarcodeScanner$1$$ExternalSyntheticLambda0.run(BarcodeScannerKt:0)
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by samiuelson**
## Camera with LENS_FACING_BACK not available making app crash when scanning barcode

Closes: #13007 

### Description

`ProcessCameraProvider::bindToLifecycle` is throwing `IllegalStateException` in case the requested camera is not available on the device. We were attempting to catch this exception, incorrectly though. The `try-catch` block was used outside the View.post {...} lambda in which the `ProcessCameraProvider::bindToLifecycle` was invoked asynchronously. This resulted in the exception not being caught. 

In other words, the `post` method schedules the code to run on the main thread, but the try-catch block only surrounds the scheduling call, not the actual execution of the code inside the post block.

### Steps to reproduce

To reproduce the crash, run the app on a device that lacks the `LENS_FACING_BACK` camera. An easy way to do that is to create an emulated device without cameras. Then:
1. Go to orders
2. Click the "barcode scanner" icon
3. Observe crash

### Testing information

Verify the crash is not happening.

### The tests that have been performed

I verified the crash is not happening on emulator without cameras.

### Images/gif

—

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/245">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanner.kt [hunk 1]
```diff
@@ -63,8 +63,8 @@ fun BarcodeScanner(
     DisposableEffect(lifecycleOwner) {
         val observer = LifecycleEventObserver { _, event ->
             if (event == Lifecycle.Event.ON_RESUME) {
-                try {
-                    previewView.post {
+                previewView.post {
+                    try {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/barcodescanner/BarcodeScanner.kt:67]: 💡 The `post` method schedules the code to run on the main thread, but the `try-catch` block only surrounds the scheduling call, not the actual execution of the code inside the post block.

**Review by malinajirka — APPROVED** [review]
Nice catch, thanks @samiuelson ! I've tested this on Pixel 8 emulator with disabled camera and it works like a charm! 👏 🚢
