### PR TITLE
Privacy Screen: Fix retry button 

### LINKED ISSUE #9091: [Privacy Choices] When tapping on "Retry", the app requests incorrect preference change
### Description

When the user taps on the "Retry" button on the "There was an error (...)" message on the Privacy Screen, the app requests update to incorrect state (opposite to what the user requested).

#### Reproduction
1. Open the Privacy Screen with Analytics enabled
2. Turn off the internet connection
3. Tap on "Analytics" switch
4. Assert you can see "There was an error (...)"
5. Turn on the internet connection, wait a second
6. Tap on "Retry"
7. Assert that the Analytics switch is enabled (you can also verify HTTP request via Flipper)

#### Expected behavior
On point 7, the request should **disable** Analytics, as this is what the user originally requested.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #9091

### Description

This PR contains 2 parts:
- refactor how we keep Analytics preference state. I've removed state kept in `PrivacySettingsViewModel` in favor of observing value directly from `SharedPreferences`. It's easier to follow a single source of truth and removes unnecessary distinguishment between WPCOM and non-WPCOM account
- fix of the issue described in #9091 

### Testing instructions

1. Open the Privacy Screen with Analytics enabled
2. Turn off the internet connection
3. Tap on "Analytics" switch
4. Assert you can see "There was an error (...)"
5. Turn on the internet connection, wait a second
6. Tap on "Retry"
7. Assert that the Analytics switch is **disabled** (you can also verify HTTP request via Flipper)

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/5845095/b8708e06-fadb-4728-8126-769918c7fbaa

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModel.kt [hunk 1]
```diff
@@ -87,33 +88,29 @@ class PrivacySettingsViewModel @Inject constructor(
...
+                        analyticsTrackerWrapper.sendUsageStats = checked
                     },
                     onFailure = {
-                        _state.value = _state.value?.copy(sendUsageStats = !checked)
+                        analyticsTrackerWrapper.sendUsageStats = !checked
                         triggerEvent(
                             MultiLiveEvent.Event.ShowActionSnackbar(
                                 resourceProvider.getString(R.string.settings_tracking_analytics_error_update)
-                            ) { onSendStatsSettingChanged(!checked) }
+                            ) { onSendStatsSettingChanged(checked) }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModel.kt:110]: Hotspot: the fix

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModelTest.kt [hunk 2]
```diff
@@ -93,45 +113,47 @@ class PrivacySettingsViewModelTest : BaseUnitTest(StandardTestDispatcher()) {
...
             // then
+            assertThat(analyticsTrackerWrapper.sendUsageStats).isFalse
+            verify(repository, never()).updateAccountSettings()
             assertThat(sut.state.value?.sendUsageStats).isFalse
-            assertThat(sut.event.value).isInstanceOf(MultiLiveEvent.Event.ShowActionSnackbar::class.java)
         }
 
     @Test
-    fun `given user is not WPCOM, when user opens the screen, load settings from local preferences`() =
+    fun `given failed API response, when user tapps on retry button, retry updating account settings`() =
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModelTest.kt:139]: Hotspot: it's not a changed test but rather a new one, to verify the provided fix

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModelTest.kt [hunk 3]
```diff
@@ -29,23 +35,37 @@ class PrivacySettingsViewModelTest : BaseUnitTest(StandardTestDispatcher()) {
         on { getString(any()) } doAnswer { it.arguments[0].toString() }
     }
 
+    val analyticsTrackerWrapper: AnalyticsTrackerWrapper = object : AnalyticsTrackerWrapper() {
```
Comment (wzieba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/prefs/PrivacySettingsViewModelTest.kt:38]: This fake implementation (in opposition to mock) "fakes" how `SharedPreferences` listener communicates about changes to `sendUsageStats`.

**Review by atorresveiga — APPROVED** [review]
Everything is working as expected. Great work!
LGTM! :shipit:
