### PR TITLE
Products List: improve handling of the FAB

### LINKED ISSUE #5230: Add Product FAB stays hidden after the product type sheet is dismissed
Steps to reproduce:
1. Open products list.
2. Click on the add product FAB.
3. Dismiss the product type sheet.
4. Notice that the FAB is still hidden.

### PR DESCRIPTION
**Pull request by hichamboushaba**
### Description
To deal with the expandable behavior of the toolbar, we had to move the add product FAB to the activity layout, and proxy all requests of showing/hiding it to the activity, and while this works well, it will create some issues when we need to show the FAB button in other screens, since the lifecycle of the fragments will complicate things (check @kidinov's trial [PR](https://github.com/woocommerce/woocommerce-android/pull/3613) especially this [comment](https://github.com/woocommerce/woocommerce-android/pull/3613))

This PR tries to make things simpler, but putting the FAB back to the fragment's layout, and to make sure it doesn't get hidden by the bottom nav, we adjust its `translationY` to accommodate for the `appBarLayout`'s offset.
With this change, the FAB will always be destroyed when we navigate to another Fragment, and we won't need any fancy solution to keep it in sync.

The PR also fixes bug #5230, check the comments for the cause.

### Testing instructions
This shouldn't cause any change to the behavior, except the bug fix, so just a small smoke testing for the FAB state, and confirming that the bug is fixed, by following the steps below should be enough:
1. Open products list.
2. Click on the add product FAB.
3. Dismiss the product type sheet.
4. Confirm that the FAB is visible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt [hunk 1]
```diff
@@ -170,24 +160,11 @@ class ProductListViewModel @Inject constructor(
...
-    private suspend fun cancelSearch() {
-        searchJob?.cancelAndJoin()
-        viewState = viewState.copy(
-            query = null,
-            isSearchActive = false,
-            isAddProductButtonVisible = false,
-            isEmptyViewVisible = false
-        )
-        _productList.value = productRepository.getProductList()
-    }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListViewModel.kt:189]: The `isAddProductButtonVisible = false` is what caused the bug #5230, but when we take a deeper look, it turns out the whole function `cancelSearch` is not useful anymore, since we don't show the FAB on search screen, so I removed it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt [hunk 2]
```diff
@@ -110,16 +111,32 @@ class ProductListFragment :
...
     }
 
+    private fun initAddProductFab(fabButton: FloatingActionButton) {
+        fabButton.setOnClickListener {
+            viewModel.onAddProductButtonClicked()
+        }
+
+        // Adjust translationY to keep the FAB always above the bottom nav
+        val appBarLayout = (requireActivity().findViewById<View>(R.id.app_bar_layout) as AppBarLayout)
+        appBarLayout.verticalOffsetChanges()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListFragment.kt:128]: This uses an extension that I added in the PR #4864, it uses internally the listener `OnOffsetChangedListener` but exposes the changes using a `Flow<Int>`.

**Comment by hichamboushaba** [comment]
@nbradbury this is not urgent, so feel free to move it to Milestone 8.1 if you can't review it before Monday 🙂.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt [hunk 3]
```diff
@@ -32,6 +32,5 @@ interface MainNavigationRouter {
     )
 
     fun showFeedbackSurvey()
-    fun showProductAddBottomSheet()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainNavigationRouter.kt:35]: Since this routing happens only in the ProductListFragment, I removed it from MainActivity, it's already very big 😄

**Review by nbradbury — APPROVED** [review]
@hichamboushaba I really like having the FAB handled by the product list fragment instead of the main activity, so this is great. :shipit:
