### PR TITLE
[Mobile Payments] Payment Type Selection Screen Crash

### LINKED ISSUE #9369: Crash. Order lateinit property order has not been initialized
Sentry Issue: [WOOCOMMERCE-ANDROID-6YF](https://a8c.sentry.io/issues/4210241231/?referrer=github_integration)

```
UninitializedPropertyAccessException: lateinit property order has not been initialized
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.trackPaymentMethodCompletion(SelectPaymentMethodViewModel.kt:308)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.trackPaymentMethodCompletion$default(SelectPaymentMethodViewModel.kt:303)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.onSharePaymentUrlCompleted(SelectPaymentMethodViewModel.kt:190)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.sharePaymentUrlLauncher$lambda$0(SelectPaymentMethodFragment.kt:42)
    at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.$r8$lambda$DkG-RZuJjoa69pWKgjAMPZlgQ0E
...
(21 additional frame(s) were not displayed)

RuntimeException: Failure delivering result ResultInfo{who=null, request=135382709, result=0, data=null} to activity {com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property order has not been initialized
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5439)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4805)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4860)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
...
(8 additional frame(s) were not displayed)

RuntimeException: Unable to resume activity {com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=135382709, result=0, data=null} to activity {com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property order has not been initialized
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4822)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4860)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #9369

### Description

The crash happens because order lateinit property was not initialized before used, because it's initialized in async way. The fix makes use of some sort suspended getter which is quite tricky. The simple fix would be changing "launch" on "runBlocking" but then it means some frames lost during the screen opening. So there is a trade-off between complexity and the UX. We may want to consider revert this and just use `runBlocking`

### Testing instructions

* Run different payment flows
* You may also simulate slow order fetching from the DB with `delay` on line 100

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt [hunk 1]
```diff
@@ -76,25 +80,29 @@ class SelectPaymentMethodViewModel @Inject constructor(
     private val _viewState = MutableLiveData<SelectPaymentMethodViewState>(Loading)
     val viewStateData: LiveData<SelectPaymentMethodViewState> = _viewState
 
-    private lateinit var order: Order
-    private lateinit var orderTotal: String
-    private lateinit var cardReaderPaymentFlowParam: Payment
+    private val _order = MutableStateFlow<Order?>(null)
+    private val order = _order.filterNotNull()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:84]: The idea is that if order is not initialized by requested then it'll suspend waiting while it will be there

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt [hunk 2]
```diff
@@ -103,26 +111,21 @@ class SelectPaymentMethodViewModel @Inject constructor(
...
     }
 
-    private suspend fun showPaymentState(param: PaymentOrRefund) {
-        order = orderStore.getOrderByIdAndSite(param.orderId, selectedSite.get())!!.let {
-            orderMapper.toAppModel(it)
-        }
-        val currencyCode = wooCommerceStore.getSiteSettings(selectedSite.get())?.currencyCode ?: ""
-        orderTotal = currencyFormatter.formatCurrency(order.total, currencyCode)
+    private suspend fun showPaymentState() {
         _viewState.value = buildSuccessState(
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: ❓ Trying to understand the problem here. I'm sorry if I'm missing some naive details here. Even in the earlier code, we were building a successful state only after initializing the order right? I mean the user could see and interact with the screen only after we got the order right?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: Good question!

I could reproduce this, actually. Turn on "don't keep activities", "share payment URL", hide the app and open. For some reason callback `StartActivityForResult` is called in this case and then `onSharePaymentUrlCompleted` before order is fetched

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: Hmm. I couldn't reproduce this in the latest `trunk`.

When the share dialog is opened, as soon as I start minimizing the app, the payment flow gets completed and when opened again, the payment hub screen is shown directly.


https://github.com/woocommerce/woocommerce-android/assets/1331230/ad086c48-deab-4459-a0f2-3b12f3dfac9e

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: @AnirudhBhat that's with "don't keep activities"? I can reproduce this every time (SDK 31)


https://github.com/woocommerce/woocommerce-android/assets/4923871/81672daf-c9f3-4bf0-9da5-75efcb195938

Also, changing `launch` to `runBlocking` on the line 84 fixes the problem as well while creating small (probably not visible on most devices). Shell, I revert this and apply a simple but "wrong" (accessing db in a blocking manner) for the sake of safety?

I am kinda not sure, I am afraid that at some moment we will disable blocking main thread access to the DB and the fix that is here still have to be applied. wdyt?

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: @kidinov Yes. You can see at the start of the video that I show that "don't keep activities" is enabled.

I tried it with Android 11 on the emulator and I was able to reproduce the crash!

> I am kinda not sure, I am afraid that at some moment we will disable blocking main thread access to the DB and the fix that is here still have to be applied. wdyt?

I share your concern. However, with our current solution, we track the case of process death while sharing the payment URL as `payment_flow_completed`. This will lead to incorrect assumptions while analyzing the data.

How about we just revert to the older solution and just add a check in the `trackPaymentMethodCompletion` method if the `order` is initialized or not? If not, we could track a `payment_flow_failure` event with the reason "Order not initialized(possibly process death while sharing payment URL)" and possibly, display a snack bar indicating that the previous payment URL sharing was not successful.

We could also use the current solution from the PR with the change of tracking the payment URL sharing failure when process death happens. 

The first approach sounds less complex and doesn't introduce any unintended side effects. I'm okay with either of the solution. WDYT?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: > I share your concern. However, with our current solution, we track the case of process death while sharing the payment URL as payment_flow_completed. This will lead to incorrect assumptions while analyzing the data.

True. But we are talking about a very, very rear case here. 3 issues per day on average. And frankly speaking, we don't know if it was shared or not anyway. We only track that the user returned from the system "share" dialog.

> How about we just revert to the older solution and just add a check in the trackPaymentMethodCompletion method if the order is initialized or not? If not, we could track a payment_flow_failure event with the reason "Order not initialized(possibly process death while sharing payment URL)" and possibly, display a snack bar indicating that the previous payment URL sharing was not successful.

To me, this option doesn't look too good. Probably worse than `runBlocking` approach, as It doesn't fix the actual problem - initializing lateinit property asynchronously. While this may fix this case, the same may happen when a new code is added, or something is changed (may this already happen with QR sharing?). I believe this may create more work in the long run for us because we may need to fix it again. wdyt?

> We could also use the current solution from the PR with the change of tracking the payment URL sharing failure when process death happens.

But how can we be sure if there is a failure? There are many options for sharing, and some of them involve other screens, e.g. "nearby sharing", so I am not sure if we can guarantee that it's a failure or it was shared and after that system killed our activity. In any case, this data doesn't bring anything to us, just because we don't know anyway if sharing happened or not

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: Makes sense. Let's go with the solution in this PR then? 
1. It fixes the crash
2. Later, if we disable blocking main thread access to the DB, we don't have to worry
3. Since we are not seeing this issue much in the production and it's hard for us to detect the payment failure, we can ignore the skew in the payment completed event since I believe the `payment_flow_complete` event might already be skewed because it's hard for us to know whether the user completed the flow or not.

WDYT?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt:115]: @AnirudhBhat sounds good to me

**Review by AnirudhBhat — APPROVED** [review]
LGTM :shipit:
