### PR TITLE
[Blaze] Fix spacing issue in Blaze Campaigns dashboard card

### LINKED ISSUE #13298: [Blaze] Campaign card has large space at bottom when display size is large
Reported by @itsmeichigo during beta testing for 21.4.

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #13298 

### Description

In the Blaze Campaigns dashboard card, the "Total" column might disappear if the combination of font size and display size setting on the device makes everything big. 

The fix proposed in the PR makes use of `FlowRow` to make the two columns responsive. They remain the same on smaller font and display size, but on bigger ones, the "Total" field will be pushed on its own row, keeping it readable at all sizes.

Previously:

| example 1: Total column is squished | example 2: Total column disappears |
|-|-|
| Image | Image |

With this PR:
| example 1 | example 2 |
|-|-|
| Screenshot_1736850084 | Screenshot_1736850069 |

Additionally, due to the `FlowRow` usage, this now brings a change in landscape/wider mode in general, where the two items will now be separated. I feel this should not be an issue since they are still readable:

| before | after |
|-|-|
| Screenshot_1736850473 | Screenshot_1736850559 |

### Steps to reproduce

1. Test with a site that is Blaze eligible and has existing or finished campaigns,
2. Enable the Blaze Campaigns card on Dashboard,
3. In the device Setting, play around with Font Size and Display Size. Both "Click-throughs" and "Total" column should be visible even at the largest size setting. Compare with screenshots above.

### Testing information

n/a

### The tests that have been performed

I tested the above in landscape and portait mode on API 35

### Images/gif

Included above.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt [hunk 1]
```diff
@@ -70,25 +70,23 @@ fun BlazeCampaignItem(
                     style = MaterialTheme.typography.subtitle1,
                     fontWeight = FontWeight.Bold,
                 )
-                Row(
-                    modifier = Modifier.padding(top = dimensionResource(id = R.dimen.major_100))
+                FlowRow(
+                    modifier = Modifier
+                        .padding(top = dimensionResource(id = R.dimen.major_100))
+                        .fillMaxWidth(),
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt]: Minor np. If we replace this for `wrapContentWidth()` we'll keep the prior design on landscape mode. 

Screenshot 2025-01-14 at 16 36 16
Screenshot 2025-01-14 at 16 36 00

```suggestion
                        .wrapContentWidth(),
```

**Review by JorgeMucientes — APPROVED** [review]
Nicely done @hafizrahman, good use of `FlowRow`. 

I left a minor suggestion and also have a question. Is this really a beta fix? I feel its not that critical, but not sure if this was discussed elsewhere.

**Comment by hafizrahman** [comment]
> I left a minor suggestion and also have a question. Is this really a beta fix? I feel its not that critical, but not sure if this was discussed elsewhere.

My thought was that:
1. This is discovered during beta testing (even though not related to any new code added during the sprint),
2. I would also consider a missing text/information to be an important bug

I'm fine with adding this to the next version, though, I just thought it'd be nice to ship it earlier and I suppose it won't be too time consuming to test before release.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt (hunk 1 above)
Comment (hafizrahman) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/campaigs/BlazeCampaignItem.kt]: Nice suggestion, thanks! TIL about `.wrapContentWidth()`. Works good in my check.

**Comment by JorgeMucientes** [comment]
Thanks for sharing your thoughts @hafizrahman 🙂. My 2 cents around that: 

> - This is discovered during beta testing (even though not related to any new code added during the sprint),
- To me, the fact that it is discovered in beta testing is not super relevant to consider it a beta fix. 
> - I would also consider a missing text/information to be an important bug
- I'd say this is the main point, impact. Missing information is important, I agree. However, if we think how many users will be impacted by this, I feel it would be a really low number. Users that have created a  Blaze campaign && have increased font size significantly && have a smaller screen (in my pixel Pro I had to set font size and display size to the max value to reproduce the bug). So, my overall feeling is that the impact is low enough to fix it in `trunk`.  

That being said, the change is small and safe. I don't want to block this PR or anything, so I'm good if you prefer merging this on the release branch 👍🏼.

**Comment by hafizrahman** [comment]
>  So, my overall feeling is that the impact is low enough to fix it in trunk.

Yeah, good point actually. Let's just bring it for the next release 👍🏼
