### PR TITLE
[Backend Receipts] Add tracking

### LINKED ISSUE #10633: [Backend Receipts] Add tracking
pfoUAQ-cg-p2

* Add to all receipt_* events property: source : backend or local so we can figure out what flow is used
* For the cases when downloading/creating/sharing a receipt fails, use the same RECEIPT_EMAIL_FAILED error with error_description error_type props (this can be different on iOS, use what makes sense to identify an error)
  * File creation failed file_creation_failed
  *File download failed file_download_failed
  *no_app_found error sent by the system
* We need to track cases when fetching a receipt URL from the backend fails. We can have RECEIPT_URL_FETCHING_FAILS with appropriate error_description error_type that comes from the backend as an error

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10633

### Description

pfoUAQ-cg-p2

The PR adds the following changes in the tracking
To all events:
```
RECEIPT_PRINT_TAPPED
RECEIPT_EMAIL_TAPPED
RECEIPT_EMAIL_FAILED
RECEIPT_PRINT_FAILED
RECEIPT_PRINT_CANCELED
RECEIPT_PRINT_SUCCESS
RECEIPT_VIEW_TAPPED
RECEIPT_URL_FETCHING_FAILS
```

Add to all receipt_* events property: `source` : `backend` or `local` so we can figure out what flow is used

And `RECEIPT_URL_FETCHING_FAILS` event when fetching of a receipt fails

### Testing instructions

* Go through receipts flows on the test site with WC that can generate and with older version
* Use logcat with "track" filter
* Notice the events mentioned above

For instance:
```
Tracked: receipt_view_tapped, Properties: {"order_id":1386,"status":null,"source":"backend","plugin_slug":"woocommerce-payments","country":"US","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}

Tracked: receipt_url_fetching_fails, Properties: {"source":"backend","plugin_slug":"woocommerce-payments","country":"US","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}

Tracked: receipt_print_tapped, Properties: {"source":"backend","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"CHIPPER_2X","card_reader_battery_level":"85 %","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}

Tracked: receipt_print_canceled, Properties: {"source":"backend","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"CHIPPER_2X","card_reader_battery_level":"85 %","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}

Tracked: receipt_email_tapped, Properties: {"source":"backend","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"CHIPPER_2X","card_reader_battery_level":"85 %","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}

Tracked: receipt_url_fetching_fails, Properties: {"source":"backend","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"CHIPPER_2X","card_reader_battery_level":"85 %","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
```

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Tested first with the test WC site:

```
2024-01-31 16:40:17.425 12659-12659 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: receipt_view_tapped, Properties: {"order_id":1394,"status":null,"source":"backend","plugin_slug":"unknown","country":"unknown","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
2024-01-31 16:40:57.805 12659-12659 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: receipt_print_tapped, Properties: {"source":"backend","plugin_slug":"unknown","country":"unknown","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
2024-01-31 16:41:10.975 12659-12659 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: receipt_print_canceled, Properties: {"source":"backend","plugin_slug":"unknown","country":"unknown","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
2024-01-31 16:41:43.440 12659-12659 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: receipt_view_tapped, Properties: {"order_id":1394,"status":null,"source":"backend","plugin_slug":"unknown","country":"unknown","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
2024-01-31 16:41:43.512 12659-12659 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: receipt_url_fetching_fails, Properties: {"source":"backend","plugin_slug":"unknown","country":"unknown","blog_id":0,"is_wpcom_store":false,"was_ecommerce_trial":null,"plan_product_slug":null,"store_id":"e337f176-b394-4849-a43b-128ab1538836","is_debug":true,"site_url":"https:\/\/very-child-traveler.jurassic.ninja"}
```

It seems like the plugin slug, country, and other properties are not being retrieved but maybe that's expected?

Should I also test pointing to a regular production site?

**Comment by kidinov** [comment]
@backwardstruck 

> It seems like the plugin slug, country, and other properties are not being retrieved but maybe that's expected?

That depends on the flow you go with - if it's IPP then we attach that (check my tracking in the PR description). This is not ideal and we are heading to have this prop to all payments events, but before this PR we didn't have that at all, so this is an improvement anyway

> Should I also test pointing to a regular production site?

If you feel confident that it works as expected then no =)

**Review by backwardstruck — APPROVED** [review]
Tested with a cash payment. Code changes look good!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt [hunk 1]
```diff
@@ -452,6 +452,7 @@ enum class AnalyticsEvent(val siteless: Boolean = false) {
     RECEIPT_PRINT_CANCELED,
     RECEIPT_PRINT_SUCCESS,
     RECEIPT_VIEW_TAPPED,
+    RECEIPT_URL_FETCHING_FAILS,
```
Comment (kingsleyagu21) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsEvent.kt:455]: RECEIPT_URL_TAPPED
