### PR TITLE
[Coupons] list improvements

### LINKED ISSUE #6338: [Coupons] - Need to tap twice to go back when the search field is not empty
**Describe the bug**
When there is text in the search field, the user would need to tap the back button twice to go back to the previous screen. The first tap clears the search field, the second tap is to go back.

**To Reproduce**
1. Go to Coupons > Search
2. Enter any text in the search field
3. Tap back button - User remains on the screen, search field cleared
4. Tap the back button again - User returns to the previous screen

**Screenshots**

https://user-images.githubusercontent.com/17252150/164582943-65ad4730-2e58-4277-88e1-56b0f70d23ab.mp4

**Expected behavior**
When tapping the back button, user should immediately return to the previous screen

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Oppo Reno6 Z 5G
- Android version: 12
- WooCommerce Android version: Pre-Alpha build: woocommerce-installable-build-pr6318-20b1d27.apk

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### LINKED ISSUE #6468: [Coupons] Improvements to the coupons list
Implement the following improvements to the coupons list:

- Pull-to-refresh.
- Show a loading indicator when loading the next page.
- An error indicator if the loading of the next page fails.

### LINKED ISSUE #6470: [Coupons] Loading subsequent pages has no UI
**Describe the bug**
When first opening the Coupons screen, skeleton loading UI is shown for the initial page load.

Scrolling down beyond the first page does not show a loading indicator, as I expected it would. It does load the next page of results, but this feels unpredictable and inconsistent, probably only because there's no UI. There's no way to know at the moment that there are more coupons to view.

**To Reproduce**
1. Add more than 10 coupons to a site
2. Go to `Menu > Coupons`
3. Observe that there are skeleton loading UI, if this is the first time you've opened Coupons
4. When the load completes, observe that you can see 10 coupons in the list
5. Scroll down
6. Observe that more coupons load, but there is no UI to show that a load is happening.

**Expected behavior**
> Skeleton loading view should be displayed on first load, subsequent loads should show coupons list with a loading indicator at the end of the list (will not reload the whole screen again on subsequent loads)
> – Test plan pdcxQM-s7-p2

**Mobile Environment**
Please include:
- Device: Pixel 6
- Android version: 12
- WooCommerce Android version: 9.1rc1

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://pointlessdivision.wpcomstaging.com
Site address (URL): https://pointlessdivision.wpcomstaging.com
WC Version: 6.4.1
REST API Version: ✔ 6.4.1
WC Blocks Version: ✔ 7.2.2
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.3.2
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.82.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.24-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.1
WC Database Prefix: wp_
Total Database Size: 12.30MB
Database Data Size: 10.68MB
Database Index Size: 1.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.30MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 6.08MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.33MB + Index: 0.06MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

amp_validated_url: 5
attachment: 37
jetpack_migration: 2
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
jp_vid_sitemap: 4
nav_menu_item: 6
page: 7
post: 6
product: 19
product_variation: 7
revision: 2
shop_coupon: 25
shop_order: 4
shop_order_refund: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Akismet Anti-Spam: by Automattic – 4.2.3
AMP: by AMP Project Contributors – 2.2.4
Crowdsignal Forms: by Automattic – 1.6.1
Facebook for WooCommerce: by Facebook – 2.6.13
WordPress.com Editing Toolkit: by Automattic – 3.32400
Gutenberg: by Gutenberg Team – 13.1.0
Jetpack: by Automattic – 11.0-a.1
Layout Grid: by Automattic – 1.8.1
Mailchimp for WooCommerce: by Mailchimp – 2.6.2
Page Optimize: by Automattic – 0.5.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.7

Storefront Powerpack: by WooCommerce – 2.0.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.1.2
WooCommerce Beta Tester: by WooCommerce – 2.0.5
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 4.1.0
WooCommerce Product Add-ons: by WooCommerce – 4.9.0
WooCommerce Shipping & Tax: by WooCommerce – 1.25.27
WooCommerce: by Automattic – 6.4.1

### Inactive Plugins (13) ###

Classic Editor: by WordPress Contributors – 1.6.2
Klarna Checkout for WooCommerce: by Krokedil – 2.7.4
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.9.1

WooCommerce Australia Post Shipping: by WooCommerce – 2.4.32
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.27
WooCommerce Eway Payment Gateway: by WooCommerce – 3.4.2
WooCommerce PayFast Gateway: by WooCommerce – 1.4.21
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Royal Mail: by WooCommerce – 2.5.43
WooCommerce Square: by WooCommerce – 3.0.1
WooCommerce Stripe Gateway: by WooCommerce – 6.3.0
WooCommerce UPS Shipping: by WooCommerce – 3.2.38
WooCommerce USPS Shipping: by WooCommerce – 4.4.72

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #24 - /shop/
Cart: #25 - /cart/
Checkout: #26 - /checkout/
My account: #27 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Homestore
Version: 2.0.34
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.1.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: /wordpress/themes/homestore/2.0.34/woocommerce/single-product/title.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://pointlessdivision.wpcomstaging.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — Iowa

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

Cash on delivery: products

### WooCommerce Payments ###

Version: 4.1.0
Connected to WPCOM: Yes
Blog ID: 200370280
Account ID: acct_1K1Wv42E0kcVNZoF

### Action Scheduler ###

Complete: 92
Oldest: 2022-04-25 15:16:08 +0100
Newest: 2022-05-09 11:18:49 +0100


### Status report information ###

Generated at: 2022-05-09 12:02:37 +01:00
```
</details>

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #6468 Closes: #6470 Closes #6338

### Description
This PR adds the following functionalities to the coupons list:
- Swipe-to-refresh.
- A loading indicator when loading the next page.
- An error Snackbar if the loading of the next page fails.
- Fixes a bug that resulted in #6338 

It adds also some unit tests for the CouponsListViewModel.

### Testing instructions
For all tests, make sure the coupons beta feature flag is enabled
#### Pagination loading indicator
1. Open coupons list.
2. Scroll down to trigger loading of next page.
3. Confirm a circular progress indicator is shown at the end of the list during loading.
4. Confirm the loading indicator is hidden when loading is completed.

#### Swipe to refresh
1. Open coupons list.
2. Swipe down to trigger refresh.
3. Confirm the list is refreshed, and the indicator is hidden when it's completed.

#### Error snackbar
1. Enable airplane mode.
2. Make some actions: swipe to refresh or search.
3. Confirm a snackbar is shown with an error message.

### Images/gif

https://user-images.githubusercontent.com/1657201/169901979-af3f3f99-533f-49e1-83b0-62f30571181c.mov

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt [hunk 1]
```diff
@@ -107,32 +117,34 @@ class CouponListFragment : BaseFragment(R.layout.fragment_coupon_list) {
...
                 }
                 return true
             }
 
-            override fun onQueryTextChange(newText: String?): Boolean {
+            override fun onMenuItemActionCollapse(item: MenuItem?): Boolean {
                 if (isAdded) {
-                    viewModel.onSearchQueryChanged(newText.orEmpty())
+                    searchView.setOnQueryTextListener(null)
+                    viewModel.onSearchStateChanged(open = false)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt:147]: These changes fixe #6338

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt [hunk 2]
```diff
@@ -29,36 +38,38 @@ class CouponListViewModel @Inject constructor(
...
+        flow = couponListHandler.couponsFlow
             .map { coupons -> coupons.map { it.toUiModel() } },
-        isLoading,
-        searchQuery
-    ) { coupons, isLoading, searchQuery ->
+        flow2 = loadingState.withIndex()
+            .debounce {
+                if (it.index != 0 && it.value == LoadingState.Idle) {
+                    // When resetting to Idle, wait a bit to make sure the coupons list has been fetched from DB
+                    LOADING_STATE_DELAY
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt:59]: Since we are observing the DB for reflecting the data changes, there is a slight delay between marking the loading as finished, and getting the data from the DB, this delay just makes sure the DB changes get to the UI before marking the loading as finished, to prevent flickering on the list.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt [hunk 3]
```diff
@@ -94,26 +109,47 @@ class CouponListViewModel @Inject constructor(
...
                     if (it.isNullOrEmpty()) 0L else AppConstants.SEARCH_TYPING_DELAY_MS
-                }.collectLatest {
+                }
+                .mapLatest { it } // Make sure downstream flow is cancelled on each emit
+                .collectIndexed { index, query ->
                     try {
-                        couponListHandler.fetchCoupons(searchQuery = it)
+                        couponListHandler.fetchCoupons(
+                            searchQuery = query,
+                            forceRefresh = index == 0 && query == null // Force refresh on initial loading
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt]: This is working well, I was just thinking it's a bit confusing that the initial non-search fetch is executed inside the `monitorSearchQuery()` method. I took me a moment to find it after seeing it was removed from `init()`. I like how it's automatically integrated, though. Maybe mentioning initial load in the method name could improve this?

**Review by 0nko — APPROVED** [review]
Looking great. 👍  I left a very minor comment in the code, but feel free to ignore it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt]: I actually felt the same, and nice job challenging me on this.
I did a small refactoring to this to bring back individual block of initial fetch, check 6ebc0b16644c98dba19f38aed8905b8e6f7b27e8 and let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt [hunk 4]
```diff
@@ -118,29 +121,41 @@ class CouponListViewModel @Inject constructor(
...
+        loadingState.value = LoadingState.Idle
+    }
+
     private fun monitorSearchQuery() {
         viewModelScope.launch {
             searchQuery
+                .withIndex()
+                .filterNot {
+                    // Skip initial value to avoid double fetching coupons
+                    it.index == 0 && it.value == null
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt:139]: I'm checking the `value` and the `index` both, as we save the search query to the saved state, and we don't want to skip the initial value when restoring from it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt (hunk 3 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListViewModel.kt]: Thanks for the updates, Hicham!
