### PR TITLE
Issue/4110 media adapter illegal state

### LINKED ISSUE #4110: IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling com.woocommerce.and...
Sentry Issue: [WOOCOMMERCE-ANDROID-1NE](https://sentry.io/organizations/a8c/issues/2418665625/?referrer=github_integration)

```
IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling com.woocommerce.android.ui.wpmediapicker.WPMediaGalleryView{6535319 VFED..... ........ 0,0-720,1344 #7f0a0770 app:id/wpMediaGallery}, adapter:com.woocommerce.android.ui.wpmediapicker.WPMediaGalleryView$WPMediaLibraryGalleryAdapter@17c6f81, layout:androidx.recyclerview.widget.GridLayoutManager@abaf826, context:com.woocommerce.android.ui.main.MainActivity@161f7e6
    at com.woocommerce.android.ui.wpmediapicker.WPMediaGalleryView$WPMediaLibraryGalleryAdapter.showImages(WPMediaGalleryView.kt:128)
    at com.woocommerce.android.ui.wpmediapicker.WPMediaGalleryView.showImages(WPMediaGalleryView.kt:104)
    at com.woocommerce.android.ui.wpmediapicker.WPMediaPickerFragment$setupObservers$1.onChanged(WPMediaPickerFragment.kt:121)
    at com.woocommerce.android.ui.wpmediapicker.WPMediaPickerFragment$setupObservers$1.onChanged(WPMediaPickerFragment.kt:34)
    at com.woocommerce.android.ui.wpmediapicker.WPMediaPickerViewModel.fetchMedia(WPMediaPickerViewModel.kt:93)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nbradbury**
Potentially fixes #4110 - This was another instance of the "Cannot call this method while RecyclerView is computing a layout or scrolling" exception, which can occur when updating a recycler multiple times or relying too heavily on `notifyDataSetChanged` for simple updates.

I wasn't able to reproduce the crash, but I did optimize `WPMediaGalleryView` to rely on `notifyItemChanged` rather `notifyDataSetChanged`, and I would think these changes would solve the crash.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt [hunk 1]
```diff
@@ -186,6 +204,15 @@ class WPMediaGalleryView @JvmOverloads constructor(
             return null
         }
 
+        private fun getImagePositionById(imageId: Long): Int {
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt]: Just an observation: you could simplify this function `imageList.indexOfFirst { it.id == imageId }`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt [hunk 2]
```diff
@@ -116,16 +116,34 @@ class WPMediaGalleryView @JvmOverloads constructor(
...
+
+    @Suppress("TooManyFunctions")
     private inner class WPMediaLibraryGalleryAdapter : RecyclerView.Adapter<WPMediaViewHolder>() {
         private val imageList = mutableListOf<Product.Image>()
 
         fun showImages(images: List<Product.Image>) {
             if (isSameImageList(images)) {
                 return
             }
+            val diffUtil = WPMediaLibraryDiffUtil(imageList, images)
```
Comment (0nko) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt:139]: NP: We can get rid of the `isSameImageList()` function, `DiffUtil` will take care of everything.

**Review by 0nko — APPROVED** [review]
Looks good, @nbradbury 👍. I left a couple of comments but fee free to ignore those.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt]: Good tip! Added in db7149b.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt (hunk 2 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/wpmediapicker/WPMediaGalleryView.kt:139]: Changed in 5e7805e.

**Comment by 0nko** [comment]
:shipit:
