### PR TITLE
Fix failing test in OrderDetailViewModel after migrating coroutines from 1.5 to 1.6

### LINKED ISSUE #6273: Fix failing test in OrderDetailViewModel after migrating coroutines from 1.5 to 1.6
It seems that the intention of [this method](https://github.com/woocommerce/woocommerce-android/blob/96839d09d9ad00de2e9ff2e2bb1ebf11c9d8cfb6/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt#L143) is to updateOrderState, then loadOrderNotes and after that re-render productAndShipping details. However, it looks like this commit (https://github.com/woocommerce/woocommerce-android/commit/9aaea01d683fad309649f8e4c487eed26e5676fc) changed the behavior, since updateOrderState is now asynchronous - the other two methods might be (probably will be) run before the order state gets updated => however, this breaks the behavior since the other two methods rely on orderState to be already updated, but it's not.

https://github.com/woocommerce/woocommerce-android/pull/6200#discussion_r851027975

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #6273 

### Description

The intention of [this method](https://github.com/woocommerce/woocommerce-android/blob/96839d09d9ad00de2e9ff2e2bb1ebf11c9d8cfb6/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt#L143) is to updateOrderState, then loadOrderNotes and after that re-render productAndShipping details. However, this commit (https://github.com/woocommerce/woocommerce-android/commit/9aaea01d683fad309649f8e4c487eed26e5676fc) changed the behavior, since updateOrderState is now asynchronous - the other two methods might be (probably will be) run before the order state gets updated => however, this breaks the behavior since the other two methods rely on orderState to be already updated, but it's not.

This was caught while migrating the coroutine from 1.5 to 1.6.

This PR removes launching `updateOrderState` in the new coroutine and instead makes it a suspend function and moves the coroutine into `displayOrderDetails` so that productAndShipping details won't execute before `updateOrderState`.

Props to @malinajirka  for catching this bug [here](https://github.com/woocommerce/woocommerce-android/pull/6200#discussion_r851027975)

### Testing instructions

Make sure Order Detail ViewModel unit tests pass after migrating coroutines from 1.5 to 1.6

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt [hunk 1]
```diff
@@ -456,32 +458,26 @@ final class OrderDetailViewModel @Inject constructor(
...
-                        isReceiptButtonsVisible = FeatureFlag.CARD_READER.isEnabled() &&
-                            !loadReceiptUrl().isNullOrEmpty()
-                    ),
-                    orderStatus = orderStatus,
-                    toolbarTitle = resourceProvider.getString(
-                        string.orderdetail_orderstatus_ordernum, order.number
-                    )
+    private suspend fun updateOrderState() {
+        val isPaymentCollectable = isPaymentCollectable(order)
+        withContext(coroutineDispatchers.main) {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: 🔍 Nitpick: I realize this is not technically related to this PR, but since we are touching this code anyway I'd like to ask about this part.
1. Any reason why we want to run `getOrderStatus` on the main thread (it's explicitly put in the `withContext(coroutineDispatchers.main)` block)? It seems that method is loading data from db, so might be better to run it on a bg thread, wdyt?
2. I believe `main` is the default dispatcher - so even the `isPaymentCollectable` will currently run on the main thread. Wdyt?

App Logs:
```
isPaymentCollectable [Dispatchers.Main.immediate]
getOrderStatus [Dispatchers.Main]
isPaymentCollectable [Dispatchers.Main.immediate]
getOrderStatus [Dispatchers.Main]
```

**Update: P.S. This viewmodel contains tons of issues like this, so feel free to ignore this comment.**

**Review by malinajirka — APPROVED** [review]
Thanks for the prompt fix @AnirudhBhat! LGTM, I think we can merge this PR. I've left one very minor incode comment - after I wrote it I realized that there are tens of similar issues throughout the vm, so feel free to just merge this PR. I'll leave the final decision to you.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: >Any reason why we want to run getOrderStatus on the main thread? It seems that method is loading data from db, so might be better to run it on a bg thread, wdyt?

For no particular reason, I just kept it similar to what we had before. But you are correct that it is a good idea to run it in the background thread.

>I believe main is the default dispatcher - so even the isPaymentCollectable will currently run on the main thread. Wdyt?

The code which access the database is being moved onto the background thread here https://github.com/woocommerce/woocommerce-android/blob/fad6a0665c0cd6445e88c94e21b69e9aca2ac0ae/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/payment/CardReaderPaymentCurrencySupportedChecker.kt#L24

I realised that we don't need `withContext(coroutineDispatchers.main) {` in `updateOrderState`. WDYT?

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: > The code which access the database is being moved onto the background thread

Ahh I see.

> I realised that we don't need withContext(coroutineDispatchers.main) { in updateOrderState. 

I think we should either remove it or move even the database on the bg thread. The current structure is a bit misleading. So yeah, let's just remove it for now and do a big refactoring of the whole vm one day.

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: Removed unnecessary thread switching https://github.com/woocommerce/woocommerce-android/pull/6274/commits/600d0840d033762024333c09734c2b16c4bc069a
