### PR TITLE
Fixes issue/3846-auth-error-changes

### LINKED ISSUE #3846: AuthFailureError: "Error fetching data", "Error fetching order", "No products yet" when logged in to a Jetpack site as a user with the Editor role
To prepare:

<sup>TL;DR have a Jetpack site with one Administrator Jetpack-connected account and one Editor Jetpack-connected account.</sup>

* Set up a WooCommerce store hosted somewhere other than WordPress.com.
* Install, activate, and connect Jetpack using a WordPress.com account.
* Go to WP Admin > Users and create an Editor account using a different WordPress.com account email.
* Log out of both WordPress.com and WP Admin.
* Log back in to WP Admin as the user you just created.
* Go to WP Admin > Jetpack Dashboard > Account connection and click the "Link to WordPress.com" link.
* Connect to the WordPress.com with the email address of the Editor account in WP Admin.
* You should end up with something that looks similar to [this screenshot](https://user-images.githubusercontent.com/1119271/114798908-b6d21600-9d53-11eb-936b-3604021753f3.png).

To test: 

1. Log in to the WooCommerce app as a Jetpack-connected user with an Editor role.
1. Browse around in the app.

**Result:** if I log in to the WooCommerce app with a user that is Jetpack-connected but has an Editor role, the app will show "Error fetching data", "Error fetching order", and "No products yet" (even though this site does have products) and you can see many API Volley errors in the app logs mentioning "AuthFailureError". ([4m50s](https://cloudup.com/cB5VN5a6uLe))

```
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
```

<details>
<summary>Full app logs for the timestamp matching the video</summary>

```
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCTS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCH_NOTIFICATIONS
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_REVIEWS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATION_HASHES
[Apr-15 24:22 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_REVIEWS
[Apr-15 24:22 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATIONS
[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:22 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
[Apr-15 24:22 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D92%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:22 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:22 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:22 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:30 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:30 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:30 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:30 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:31 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:31 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:31 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT
[Apr-15 24:31 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget%26status%3Dprocessing&json=true&locale=en_GB - exception: null
[Apr-15 24:31 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:31 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT
[Apr-15 24:31 ORDERS e] Error fetching a count of orders waiting to be fulfilled: Sorry, you cannot list resources.
[Apr-15 24:31 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:31 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:31 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:33 NOTIFS i] Sending FCM token to our remote services: *** REDACTED ***
[Apr-15 24:33 WP d] API Dispatching action: NotificationAction-REGISTER_DEVICE
[Apr-15 24:33 WP d] API Dispatching action: NotificationAction-REGISTERED_DEVICE
[Apr-15 24:33 WP i] NOTIFS Server response OK. Device ID: 41284679
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDERS_COUNT
[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:33 WP d] API WCLeaderboardsStore: fetchLeaderboards
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget%26status%3Dprocessing&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDERS_COUNT
[Apr-15 24:33 ORDERS e] Error fetching a count of orders waiting to be fulfilled: Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Fleaderboards%2F%26_method%3Dget%26before%3D2021-04-14T23%253A59%253A59%26after%3D2021-04-14T00%253A00%253A00%26per_page%3D3%26interval%3Dday&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D81%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:33 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:33 WP d] API WCGatewayStore: fetchAllGateways
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_LIST
[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCH_ORDER_STATUS_OPTIONS
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Freports%2Forders%2Ftotals%2F%26_method%3Dget&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_STATUS_OPTIONS
[Apr-15 24:33 ORDERS e] OrderListRepository - Error fetching order status options from the api : Sorry, you cannot list resources.
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D60%26offset%3D0%26status%3Dany%26_fields%3Did%252Cdate_created_gmt%252Cdate_modified_gmt&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: WCOrderAction-FETCHED_ORDER_LIST
[Apr-15 24:33 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Fpayment_gateways%2F%26_method%3Dget&json=true&locale=en_GB - exception: null
[Apr-15 24:33 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:33 WP d] API Dispatching action: ListAction-FETCHED_LIST_ITEMS
[Apr-15 24:33 ORDERS e] AUTHORIZATION_REQUIRED: Sorry, you cannot list resources.
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCH_NOTIFICATIONS
[Apr-15 24:34 WP d] API Dispatching action: WCProductAction-FETCH_PRODUCT_REVIEWS
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATION_HASHES
[Apr-15 24:34 WP d] API Dispatching action: NotificationAction-FETCHED_NOTIFICATIONS
[Apr-15 24:34 WP d] API Dispatching action: WCProductAction-FETCHED_PRODUCT_REVIEWS
[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCH_REVENUE_STATS
[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCH_NEW_VISITOR_STATS
[Apr-15 24:34 WP d] API Dispatching action: WCOrderAction-FETCH_HAS_ORDERS
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191940058/stats/visits/?unit=day&date=2021-04-14&quantity=1&stat_fields=visitors&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCHED_NEW_VISITOR_STATS
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching visitor stats: user cannot view stats
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc-analytics%2Freports%2Frevenue%2Fstats%2F%26_method%3Dget%26interval%3Dhour%26after%3D2021-04-14T00%253A00%253A00%26before%3D2021-04-14T23%253A59%253A59%26per_page%3D81%26order%3Dasc&json=true&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCStatsAction-FETCHED_REVENUE_STATS
[Apr-15 24:34 WP e] API Volley error on https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/191940058/rest-api/?path=%2Fwc%2Fv3%2Forders%2F%26_method%3Dget%26per_page%3D1%26offset%3D0%26status%3Dany&json=true&locale=en_GB - exception: null
[Apr-15 24:34 WP e] API StackTrace: com.android.volley.AuthFailureError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:195)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-15 24:34 WP d] API Dispatching action: WCOrderAction-FETCHED_HAS_ORDERS
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching stats: Sorry, you cannot list resources.
[Apr-15 24:34 DASHBOARD e] class com.woocommerce.android.ui.mystore.MyStorePresenter - Error fetching whether orders exist: Sorry, you cannot list resources.
```
</details>

Screen Shot 2021-04-14 at Apr 14 6 55 01 PM Screen Shot 2021-04-14 at Apr 14 6 55 15 PM Screen Shot 2021-04-14 at Apr 14 6 55 22 PM
<sup>Tested with WCAndroid 6.4-rc-2 on Pixel 3 Android 11 on favourite-saki.jurassic.ninja (WP 5.7.1-RC1 JP 9.6.1 WC 5.2.1) logged in as testuser031821 (which is a WordPress.com account username used to connect to the account with the same name on the Jetpack site and that has an Editor role there).</sup>

**Possible solutions:** 

1. Update the minimum requirements for the app to mention the account in WP Admin must be connected to Jetpack and must either be an Administrator or Shop Manager role. 
1. Add error handling for `AuthFailureError` to let the user know the role requirements and how to update that in WP Admin (make sure to note that an Administrator must make the change).

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3846. This PR adds the option to fetch the user role for a store and displays an error screen if they do not have admin or shop manager access. 

### Changes
- Adds a separate class `UserEligibilityFetcher` (forgive the name, please!) that fetches the user info from FluxC.
- This class is called: 
  - Every time the app is completely restarted 
  - When the user logs in for the first time. 
- If the API request is successful, we store a Boolean flag and the user email to `AppPrefs`. 
- Every time the app is opened, we check this Boolean flag to determine if the user has sufficient access.
- An error screen is displayed if they do not have admin or shop manager access.

### Screenshots
. 

#### Perquisites
- At the moment we only support Admin and Shop Manager role. Create multiple user accounts with different user roles on your test site. 
- You can install the [User Role Editor](https://user-images.githubusercontent.com/22608780/116804544-18a8c300-ab3d-11eb-880e-a60381940a82.png) plugin on your test site. This allows you to create multiple custom roles and assign multiple roles to the same user.

#### Scenario 1
- Login to your test site using an admin or shop manager credentials.
- You should be able to use the app as is without any issues.

#### Scenario 2
- Login to your test site using any credentials that does not include admin or shop manager.
- You should be able to see an error screen when you open the app.
- Click on the back button and verify that you are exited from the app.
- Click on the Help button and verify that you are able to see the support screen.
- Click on the `Retry` button and verify that, if the account has insufficient access, you see an error Snackbar. Try changing the user's access from `wp-admin` and click on the Retry button again. You should be redirected to the Stats screen.
- Click on the `Login to another account` button and verify that you are redirected to the Prologue screen.

#### Unit tests
- Run `UserEligibilityErrorViewModelTest` class.
- Run `UserEligibilityFetcherTest` class.

@designsimply I added you as a reviewer since you were the one that caught the bug in the first place 😄 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This is looking really good thanks @anitaa1990! I did notice that the background on the light version needs the white background please and also it seems the headers and dark buttons are a little different from the designs. 

Screen Shot 2021-05-21 at 3 17 03 pm

**Comment by anitaa1990** [comment]
Thank you for the quick review @adamzelinski ❤️ 

>  I did notice that the background on the light version needs the white background please and also it seems the headers and dark buttons are a little different from the designs.

I missed the light version background. Updated that and this is how it looks now. 
. 


I didn't add a title to the screen since this is something we check after the user is logged in, so `Log in` as a header here feels misleading. I couldn't think of anything else appropriate so just left it blank 😅 

Regarding the text styles, so the bottom buttons (`Retry` and `Login with another account`) are using the same styles as the ones defined for all the login screens. We're just reusing the same layout here to be consistent across the different error screens. Do we want to change it for all screens? We can do that but it out of scope for this PR. I'm happy to tackle the change in a different PR, if that's alright with you?

**Comment by ghost** [comment]
No that's cool @anitaa1990 thanks for updating the bg style the rest is fine to use the same styles

**Review by ghost — APPROVED** [review]

**Comment by nbradbury** [comment]
If I go to settings and switch to a store I don't have the correct user role for, I see the toast stating that the store was switched.

toast

When I tap the back button from there, I then see the screen stating I don't have the correct user role. Shouldn't the user role verification happen before then?

And if I tap the back button on that screen, it closes the app. The app also closes if I tap the back button on that screen during the initial login flow. In that situation, it should probably return the user to the first login screen.

**Comment by nbradbury** [comment]
This seems unnecessarily wordy. How about: "This app supports only Administrator and Shop Manager user roles. Please contact your store owner to upgrade your role."

role

Also, the toast that appears when you tap retry says "user access" - how about "user role" instead for consistency?

**Comment by nbradbury** [comment]
When the device is in landscape I see this:

landscape

In similar screens elsewhere in the app we hide the image in landscape (but not on tablets). Should we do that here? @adamzelinski

**Comment by nbradbury** [comment]
I'm not sure how, but I was able to login to the app with a "Contributor" user role. The dashboard showed a "Error fetching data" toast and the log showed "Error fetching visitor stats: user cannot view stats."

Screenshot_20210524_081020

I then went to settings, selected the same store, and tapped Done. When I returned to the dashboard, the app crashed with this:

```
 Process: com.woocommerce.android, PID: 2882
    java.lang.NullPointerException
        at com.woocommerce.android.ui.mystore.MyStoreFragment.getTabLayout(MyStoreFragment.kt:83)
        at com.woocommerce.android.ui.mystore.MyStoreFragment.getActiveGranularity(MyStoreFragment.kt:76)
        at com.woocommerce.android.ui.mystore.MyStoreFragment.access$getActiveGranularity$p(MyStoreFragment.kt:46)
        at com.woocommerce.android.ui.mystore.MyStoreFragment$refreshMyStoreStats$$inlined$run$lambda$1.invokeSuspend(MyStoreFragment.kt:319)
```

(I'm guessing that crash is unrelated to this PR.)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+        AnalyticsTracker.trackViewShown(this)
+    }
+
+    override fun onDestroyView() {
+        super.onDestroyView()
+        _binding = null
+    }
+
+    override fun onRequestAllowBackPress(): Boolean {
+        activity?.finish()
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt:164]: I mentioned this already, but here it probably makes more sense to return to the previous screen instead of closing the app when the back button is pressed.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+    }
+
+    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
+        super.onCreateOptionsMenu(menu, inflater)
+        inflater.inflate(R.menu.menu_login, menu)
+    }
+
+    override fun onOptionsItemSelected(item: MenuItem): Boolean {
+        if (item.itemId == R.id.help) {
+            startActivity(HelpActivity.createIntent(requireActivity(), Origin.USER_ELIGIBILITY_ERROR, null))
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt]: WDYT about logging the user role here? That could help HEs if the user contacts us from the help activity.

**Comment by nbradbury** [comment]
@anitaa1990 Done with my first round!

**Comment by ghost** [comment]
> "This app supports only Administrator and Shop Manager user roles. Please contact your store owner to upgrade your role."

> Also, the toast that appears when you tap retry says "user access" - how about "user role" instead for consistency?

I agree @nbradbury could we please make both of these changes.

**Comment by ghost** [comment]
> In similar screens elsewhere in the app we hide the image in landscape (but not on tablets). Should we do that here? 

Yes, thanks @nbradbury we will hide the image in landscape (but not on tablets)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt (hunk 2 above)
Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityErrorFragment.kt]: That's a very good idea! I added that in e044cc0

**Comment by anitaa1990** [comment]
Thank you for the review @nbradbury!

> In similar screens elsewhere in the app we hide the image in landscape (but not on tablets). Should we do that here?

Good point! I fixed this in 35b2981 

> This seems unnecessarily wordy. How about: "This app supports only Administrator and Shop Manager user roles. Please contact your store owner to upgrade your role."

👍 Done in 35b2981

> I'm not sure how, but I was able to login to the app with a "Contributor" user role. The dashboard showed a "Error fetching data" toast and the log showed "Error fetching visitor stats: user cannot view stats."

So I'm not really able to reproduce this scenario. But I had added logic in `SitePickerActivity` to fetch user role and store it in `AppPrefs` in the background. So it might be that `MainActivity` is called before the user could be fetched and stored in the background. So I updated the logic in `SitPickerActivity` to fetch the user role synchronously. So only after the user role is fetched and stored, we would redirect to the main activity (even if it results in an error). This is done in 102a761 and that should ensure that we don't allow users without admin or shop manager role into the app after login.

> If I go to settings and switch to a store I don't have the correct user role for, I see the toast stating that the store was switched.

I thought of this one but when testing I noticed that if I don't have access to that store, it is not listed in the store switcher list. But if this is happening when switching stores, the logic added in 102a761 should help fix this since that check happens when we switch store as well 👍 

> it probably makes more sense to return to the previous screen instead of closing the app when the back button is pressed.

So we are only able to get the user role from the API after the user is logged in successfully. So by the time they see this screen, they are logged in. So clicking the back button should ideally close the app. If we redirect to the login prologue screen we would have to log them out of the app first and they would have to login again each time they open the app. If we redirect them to the `MyStore` tab, none of the APIs would work in the app so they would just keep seeing an error, similar to the experience we have now.

Ready for another round @nbradbury 👍

**Comment by nbradbury** [comment]
~~I'm still able to login without the correct user role. In this screenshot, both of these stores are available even though that account has a Contributor role for both of them. When I tap Done, the app shows the dashboard screen with an "Error fetching data" toast.~~

**Comment by nbradbury** [comment]
@anitaa1990 Ignore that last message, I tested the app before I pulled changes 🤦

**Comment by nbradbury** [comment]
The changes here include a landscape layout of the eligibility screen that has no image, which means the image is missing even on landscape tablets. We wanted to still show the image on landscape tablets, since there's plenty of room for it.

tablet

Rather than using a separate layout, WDYT about sticking with a single layout and programmatically hiding the image when the orientation is landscape and the device isn't a tablet?

**Comment by nbradbury** [comment]
@anitaa1990 I closed the app when the eligibility screen was showing for a user that wasn't eligible for any stores they're a member of, and when I restarted it crashed with this:

```
java.lang.IllegalStateException: SelectedSite.get() was accessed before being initialized - siteId -1.
    Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
        at com.woocommerce.android.tools.SelectedSite.get(SelectedSite.kt:36)
        at com.woocommerce.android.ui.common.UserEligibilityFetcher.fetchUserInfo(UserEligibilityFetcher.kt:34)
        at com.woocommerce.android.ui.common.UserEligibilityFetcher$fetchUserEligibility$1.invokeSuspend(UserEligibilityFetcher.kt:27)
```

I had to clear storage in order to open the app again.

**Comment by nbradbury** [comment]
@anitaa1990 I just noticed the user name and role aren't appearing on the eligibility screen.

Screenshot_20210526_111920

On the previous screen, though, they appear just fine.

Screenshot_20210526_111504

**Comment by anitaa1990** [comment]
Hey @nbradbury! Thanks for the review! 

> The changes here include a landscape layout of the eligibility screen that has no image, which means the image is missing even on landscape tablets. We wanted to still show the image on landscape tablets, since there's plenty of room for it.

I like the idea of having a standard way to display images in tablets and landscape mode. I only made the changes at the moment to this screen but long term we might want to find a standard way to achieve this. Thanks for the suggestion! Fixed in abf5c0d.

> @anitaa1990 I closed the app when the eligibility screen was showing for a user that wasn't eligible for any stores they're a member of, and when I restarted it crashed with this:

I'm not able to reproduce this. There seems to be a lot of issues that keep happening when I try to fix the merge conflicts in this PR. I finally had to force push to fix those changes in e70f410. Can you test again and see if this is happening please? 

> @anitaa1990 I just noticed the user name and role aren't appearing on the eligibility screen.

I noticed that too! It should be fixed in abf5c0d. I also noticed that the app was crashing when clicking on the Help button and that was fixed too!

Ready for another round 👍

**Comment by nbradbury** [comment]
@anitaa1990 I can't reproduce that crash now, but I'm still not seeing the user info. The problem is [here in the viewmodel](https://github.com/woocommerce/woocommerce-android/pull/4074/files#diff-1c3ea75ddd6329dc433d5b6eea31160ff412b1f3a43d589d9b2a819d31e202bdR52), because the user email is empty.

Screen Shot 2021-05-26 at 1 00 01 PM

**Update:** I just noticed that if you view the help screen then hit the back button, the user name shows up.

Screenshot_1622049354

**Comment by anitaa1990** [comment]
> @anitaa1990 I can't reproduce that crash now, but I'm still not seeing the user info. The problem is here in the viewmodel, because the user email is empty.


~Hey @nbradbury I'm not actually able to reproduce that. Would you be able to add my email (reallychumma1@gmail.com) to your test site so I can check it out? As such, if we don't really have the email stored, we won't be able to get the user info so the user name and role would not be displayed. But I'm not sure why the email is empty and even more weird, why it's not showing the role and why it's showing after coming back from the Help screen.~

Scratch ☝️ I was able to reproduce the same issue with just the `Contributor` role. The email was not getting saved after the user logs in for the first time so it was blank, which was causing the username to be blank. Fixed in a1ea303.

Ready for another round 😅

**Review by nbradbury — APPROVED** [review]
@anitaa1990 I think you'll be delighted to hear that this all looks good now! :shipit:
