### PR TITLE
Issue/8178 fix user role fetch

### LINKED ISSUE #8178: App doesn't display user eligibility error after role change from wc-core
**Describe the bug**
When a logged user role is changed from `wc-core` to a role different from Administrator or ShopManager, the next time the App is opened from scratch (app has been killed) the app should display the following screen: 

Screenshot 2023-01-13 at 12 08 26

Right now the app needs to be killed twice in order to for it to properly refresh the user eligibility state and display the expected error screen. 

The reason for this bug is that in `MainActivity`, the code that checks user eligibility (checks a persisted flag) runs before we fetch and refresh the actual user role from the API that is triggered in the `AppInitializer`. 

Essentially, this code from `MainActivity.kt` runs before: 
```kotlin
        if (selectedSite.exists() && !presenter.isUserEligible()) {
            showUserEligibilityErrorScreen()
            return
        }
```
this other code from `AppInitializer.kt` that refreshes the status of user eligibility. 
```kotlin
    override fun onFirstActivityResumed() {
        // App is completely restarted
        if (networkStatus.isConnected()) {
            if (accountStore.hasAccessToken()) {
                // Update the WPCom account if the user is signed in using a WPCom account
                dispatcher.dispatch(AccountActionBuilder.newFetchAccountAction())
                dispatcher.dispatch(AccountActionBuilder.newFetchSettingsAction())
            }

            // Update the list of sites
            appCoroutineScope.launch {
                wooCommerceStore.fetchWooCommerceSites()

                // Added to fix this crash
                // https://github.com/woocommerce/woocommerce-android/issues/4842
                if (selectedSite.getSelectedSiteId() != -1 &&
                    !selectedSite.exists() &&
                    ProcessLifecycleOwner.get().lifecycle.currentState.isAtLeast(STARTED)
                ) {
                    // The previously selected site is not connected anymore, take the user to the site picker
                    WooLog.i(DASHBOARD, "Selected site no longer exists, showing site picker")
                    openMainActivity()
                }
            }

            // Update the user info
            if (selectedSite.exists()) {
                userEligibilityFetcher.fetchUserEligibility()
            }
        }
    }
```

Ideally whenever we refresh user eligibility state fetching fresh data from the API we should trigger an event to show the expected error screen if the user is not eligible anymore. If this turns out to be complex we can also ensure that `AppInitializer.kt` triggers opening `MainActivity` again once user role state has been updated and is not eligible anymore.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8178 

### Description
This PR fixes the above issue by making sure we re-open the MainActivity after the fetch if the user is ineligible.

### Testing instructions

1. Sign in to the app using a user that has a valid role.
2. Close the app.
3. Open the website then update the role to a role other than "admin" and "shop manager".
4. Re-open the app.
5. Confirm the app shows an error screen.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt [hunk 1]
```diff
@@ -232,10 +236,12 @@ class AppInitializer @Inject constructor() : ApplicationLifecycleListener {
         }
     }
 
-    private fun openMainActivity() {
-        val intent = Intent(application, MainActivity::class.java)
-        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
-        application.startActivity(intent)
+    private fun restartMainActivity() {
+        if (ProcessLifecycleOwner.get().lifecycle.currentState.isAtLeast(STARTED)) {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt:240]: I renamed the function to make it clear this would restart the activity, and I added the lifecycle's state check here instead of repeating it always, if it's called when the app is backgrounded, we don't want to pop the activity our of nowhere or the app to [crash](https://developer.android.com/guide/components/activities/background-starts).

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcherTest.kt [hunk 2]
```diff
@@ -41,31 +42,21 @@ class UserEligibilityFetcherTest : BaseUnitTest() {
...
+        whenever(userStore.fetchUserRole(any())).thenReturn(WooResult(expectedUser))
 
-        fetcher.fetchUserEligibility()
+        fetcher.fetchUserInfo()
 
-        assertThat(appPrefsWrapper.isUserEligible()).isEqualTo(expectedUser.isUserEligible())
-        assertThat(appPrefsWrapper.getUserEmail()).isEqualTo(expectedUser.email)
-        assertFalse(appPrefsWrapper.isUserEligible())
+        verify(appPrefsWrapper).setUserEmail(expectedUser.email)
+        verify(appPrefsWrapper).setIsUserEligible(expectedUser.isUserEligible())
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcherTest.kt:59]: This and the other test below didn't test what they say they test, as all what it was done is setting the mocks and then checking that they return what we set. I updated them to confirm the behavior against what `userStore` would return.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcher.kt [hunk 3]
```diff
@@ -2,37 +2,26 @@ package com.woocommerce.android.ui.common
...
-
-    fun fetchUserEligibility() {
-        launch(Dispatchers.Default) {
-            fetchUserInfo()?.let { updateUserInfo(it) }
+) {
+    suspend fun fetchUserInfo(): WCUserModel? {
+        return userStore.fetchUserRole(selectedSite.get()).model?.also {
+            updateUserInfo(it)
         }
     }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/UserEligibilityFetcher.kt:20]: Instead of having two functions, I opted to have a single suspendable one, and it automatically saves the data to the prefs, this way, the clients won't have to call `updateUserInfo` themselves.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for fixing this bug and making the code simpler and safer. Great job @hichamboushaba. Works perfect!
