### PR TITLE
[Bug] [IPP Feedback Survey] Error handling in `GetIPPFeedbackBannerData`

### LINKED ISSUE #8311: IllegalStateException: IPP feedback banner should not be shown to the current user & site.
Sentry Issue: [WOOCOMMERCE-ANDROID-5YD](https://a8c.sentry.io/issues/3922969988/?referrer=github_integration)

```
IllegalStateException: IPP feedback banner should not be shown to the current user & site.
    at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.requireShouldShowFeedbackBanner(GetIPPFeedbackBannerData.kt:80)
    at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.access$getIPP_NINJA_BANNER$delegate$cp(GetIPPFeedbackBannerData.kt:22)
    at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData.access$requireShouldShowFeedbackBanner(GetIPPFeedbackBannerData.kt:22)
    at com.woocommerce.android.ui.payments.feedback.ipp.GetIPPFeedbackBannerData$requireShouldShowFeedbackBanner$1.invokeSuspend
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by samiuelson**
This PR fixes error handling in `GetIPPFeedbackBannerData` use case. 

Closes: https://github.com/woocommerce/woocommerce-android/issues/8311

### Description

There were a few crashes reported (https://github.com/woocommerce/woocommerce-android/issues/8311), potentially happening in case `ShouldShowFeedbackBanner` conditions change during the execution of the target user group detection use case (`GetIPPFeedbackBannerData`). 

While I couldn't reproduce the crash, this PR fixes unsafe error handling design and replaces exception throwing by returning a null value and logging the error, so no crashes are supposed to happen.

### Testing instructions

The IPP survey banner should work as expected, and should not cause a crash.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt [hunk 1]
```diff
@@ -27,8 +27,8 @@ class GetIPPFeedbackBannerData @Inject constructor(
     private val logger: AppLogWrapper,
 ) {
     @Suppress("ReturnCount", "MaxLineLength")
-    suspend operator fun invoke(): IPPFeedbackBanner {
-        requireShouldShowFeedbackBanner()
+    suspend operator fun invoke(): IPPFeedbackBanner? {
+        if (!shouldShowFeedbackBanner()) return null
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt]: ⚠️ We should log this behavior else, we wouldn't know if this is happening for many users out there. Right now, it will fail silently. WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 2]
```diff
@@ -183,8 +183,12 @@ class OrderListViewModel @Inject constructor(
                 FeatureFlag.IPP_FEEDBACK_BANNER.isEnabled() && shouldShowFeedbackBanner()
             if (shouldShowFeedbackBanner) {
                 val bannerData = getIPPFeedbackBannerData()
-                viewState = viewState.copy(ippFeedbackBannerState = IPPSurveyFeedbackBannerState.Visible(bannerData))
-                trackIPPBannerEvent(AnalyticsEvent.IPP_FEEDBACK_BANNER_SHOWN)
+                if (bannerData != null) {
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:186]: ❓ What do you think about writing tests to verify this change?

1. Test that ensures that the view state isn't modified when banner data is null
2. Test that ensures that the track event is not called when the banner data is null

**Review by AnirudhBhat — COMMENTED** [review]
Thanks for taking care of this @samiuelson. I've left a couple of comments to think about. Let me know your thoughts on those.

**Comment by samiuelson** [comment]
> Thanks for taking care of this @samiuelson. I've left a couple of comments to think about. Let me know your thoughts on those.

Thanks, @AnirudhBhat for the review. I've added additional tests to verify correct view states and added the log in case the banner should not be shown.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt [hunk 3]
```diff
@@ -28,7 +28,10 @@ class GetIPPFeedbackBannerData @Inject constructor(
 ) {
     @Suppress("ReturnCount", "MaxLineLength")
     suspend operator fun invoke(): IPPFeedbackBanner? {
-        if (!shouldShowFeedbackBanner()) return null
+        if (!shouldShowFeedbackBanner()) {
+            logger.e(AppLog.T.API, "GetIPPFeedbackBannerData should not be shown.")
```
Comment (AnirudhBhat) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/feedback/ipp/GetIPPFeedbackBannerData.kt:32]: ❓ nitpick:  Sorry for not mentioning this in my first review. I was wondering if it's worth it to write a test to verify that we are logging in case of `shouldShowFeedbackBanner=false`. Same for other loggers as well.

Please feel free to ignore it if you think it's not worth doing this.

**Review by AnirudhBhat — APPROVED** [review]
I've left one minor nitpick that is non-blocking. LGTM :shipit:
