### PR TITLE
[Crash] `IllegalArgumentException` when navigating to Filters in Orders list

### LINKED ISSUE #12480: IllegalArgumentException: Navigation action/destination com.woocommerce.android:id/action_orderListFragment_to_orderFilterL...
Sentry Issue: [WOOCOMMERCE-ANDROID-9PP](https://a8c.sentry.io/issues/5078779302/?referrer=github_integration)

```
IllegalArgumentException: Navigation action/destination com.woocommerce.android:id/action_orderListFragment_to_orderFilterListFragment cannot be found from the current destination Destination(com.woocommerce.android:id/orderFilterCategoriesFragment)
    at com.woocommerce.android.extensions.NavControllerKt$navigateSafely$2.invoke(NavController.kt:66)
    navigate(resId, bundle, navOptions)
    at com.woocommerce.android.extensions.NavControllerKt$navigateSafely$2.invoke(NavController.kt:64)
    CallThrottler.throttle {
    at com.woocommerce.android.extensions.CallThrottler.throttle(NavController.kt:23)
    call()
    at com.woocommerce.android.extensions.NavControllerKt.navigateSafely(NavController.kt:64)
    CallThrottler.throttle {
    at com.woocommerce.android.extensions.NavControllerKt.navigateSafely$default(NavController.kt:59)
    fun NavController.navigateSafely(
...
(39 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by samiuelson**
## [Crash] IllegalArgumentException when navigating to Filters in Orders list

Closes: #12480 

### Description

Sentry [logs](https://a8c.sentry.io/issues/5078779302/?referrer=github_integration) revealed crash happening in the Orders screen when tapping the "Filters" button. 

As shared (p1725275700876619-slack-C6H8C3G23), I couldn't reproduce the crash. However, in this case, I think swallowing the exception, preventing the app from crashing and logging the error instead makes sense. For that, I just switched to the `navigateSafely` function that calls the navigation action in a try-catch block.

### Steps to reproduce

—
### Testing information

It's crucial to test against regression. The Filters screen/dialog should appear when tapping the "Filters" button in the Orders screen.

### The tests that have been performed

I verified the Filters screen/dialog is displayed correctly and filtering works in the Orders screen. Devices: Pixel 7 pro, Galaxy Tab, Android 14

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 1]
```diff
@@ -709,7 +709,9 @@ class OrderListFragment :
     }
 
     private fun showOrderFilters() {
-        findNavController().navigateSafely(R.id.action_orderListFragment_to_orderFilterListFragment)
+        findNavController().navigateSafely(
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt:712]: This function catches the exception internally, preventing the crash. The crash is happening because the Filters screen is already visible, so that's why I decided to swallow the exception.

Comment (backwardstruck) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt:712]: The code change seems fine since it can't be reproduced. 

Strange that is started occurring 6 months ago
in release 17.7-rc-2. I don't see which change might have caused that.

**Review by backwardstruck — APPROVED** [review]
Tested and didn't see any regressions on tablet emulator. 

Unrelated to this change, I noticed that we only show an 'x` for the product filter. I wonder if that's intentional. Maybe it's a bit misleading:

Screenshot_20240903_194745
