### PR TITLE
[Custom Fields] Fix issue where text formatting changes in Aztec are lost

### LINKED ISSUE #12783: [Custom Fields] Changing text format in Aztec is not detected until we change the text as well
Reported by @selanthiraiyan in the beta testing: "When I edit a custom field and change the type from “Text” to “HTML” the “Done” button is not enabled. I tried making some changes to the HTML using the buttons. The “Done” button is not enabled until I alter the text. Is this expected?"

https://github.com/user-attachments/assets/cc5fc37c-6363-4d59-895b-51fe769ce303

p1728992309521619/1728992304.294829-slack-C03L1NF1EA3

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12783 

### Description
This PR fixes a bug that was identified in the beta testing round: changing text formatting without changing the content wasn't detected.

The cause is that I used an `OnTextChangedListener` for Aztec, but the listener is not invoked when we change just the format, Aztec offers an alternative API to listen to the changes `AztecContentChangeWatcher` that fixes the issue.

### Steps to reproduce
1. Open an order in the app.
2. Tap on "Custom Details ✎"
3. Open an existing custom field.
4. Switch to the HTML mode.
5. Select the content, then change the Bold status.

### Testing information
- Confirm that the "Done" button will be enabled.
- Switch to the Text tab, and confirm the content was updated.

### The tests that have been performed

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/239">20.7</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt [hunk 1]
```diff
@@ -327,10 +328,16 @@ private fun InternalAztecEditor(
...
-                    if (!state.isHtmlEditorEnabled) return@doAfterTextChanged
-                    state.updateContent(aztec.visualEditor.toHtml())
+                val aztecObserver = object : AztecTextChangeObserver {
+                    override fun onContentChanged() {
+                        if (!state.isHtmlEditorEnabled) return
+                        state.updateContent(aztec.visualEditor.toHtml())
+                    }
                 }
+                // Save the observer as tag to hold a strong reference to it and avoid it being garbage collected
+                aztec.visualEditor.tag = aztecObserver
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt:338]: The listeners are saved as `WeakReference` in Aztec, so they get garbage collected unless we keep a strong reference to them.
Here I'm saving it as the View's tag, alternatively we can also use an explicit variable and `remember` it in Compose, I think this is less verbose, but if you see it as a hacky solution please let me know.

Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/aztec/AztecEditor.kt:338]: It might seem a bit hacky but the comment adds good context. I think it is fine as it is.

**Review by JorgeMucientes — APPROVED** [review]
Nice find about `AztecTextChangeObserver`. Thanks for fixing this @hichamboushaba. 
Works as expected :shipit:
