### PR TITLE
Fix wording on order paid with cash dialog

### LINKED ISSUE #6946: Wrong wording on marking an order that it was paid by cash
Since this can be done not only for simple payments but for already created orders, the This will create your order ... text looks a bit misleading.

image

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #6946 

### Description

This PR changes the text of the cash payment dialog based on if the payment was generated from an existing order or a simple payment.
context: p5T066-3oX-p2#comment-12933

It also adds a tracker for cash payments collected from an existing order ( #6949 )
context: p1657805095414379-slack-CGPNUU63E

### Testing instructions

1. Go to an unpaid existing order and click on collect payment - Cash
2. confirm the text says: `This will mark this order as paid if you received payment outside of WooCommerce`
3. Create a simple payment  order and click on collect payment - cash
4. confirm the text says: `This will create your order and mark it as paid if you received payment outside of WooCommerce`

### Images/gif

| Simple Payment | Existing Order |
| ---- | ---- |
|  |  |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt [hunk 1]
```diff
@@ -91,24 +92,50 @@ class SelectPaymentMethodViewModel @Inject constructor(
...
-                },
-                negativeButtonId = R.string.cancel
-            )
-        )
+        when (cardReaderPaymentFlowParam.paymentType) {
+            SIMPLE -> {
+                analyticsTrackerWrapper.track(
+                    AnalyticsEvent.PAYMENTS_FLOW_COLLECT,
+                    mapOf(
+                        AnalyticsTracker.KEY_PAYMENT_METHOD to VALUE_SIMPLE_PAYMENTS_COLLECT_CASH,
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt]: I am confused with that. Isn't like you send 

```
payment_method -> cash
```

In both cases anyway?

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt [hunk 2]
```diff
@@ -162,7 +162,7 @@ class SelectPaymentMethodViewModelTest : BaseUnitTest() {
     }
 
     @Test
-    fun `when on cash payment clicked, then show dialog event emitted`() = testBlocking {
+    fun `given order payment flow, when on cash payment clicked, then show dialog event emitted`() = testBlocking {
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt:165]: 👍

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt [hunk 3]
```diff
@@ -174,11 +174,32 @@ class SelectPaymentMethodViewModelTest : BaseUnitTest() {
...
-        assertThat((events.last() as ShowDialog).messageId).isEqualTo(R.string.simple_payments_cash_dlg_message)
+        assertThat((events.last() as ShowDialog).messageId).isEqualTo(R.string.existing_order_cash_dlg_message)
         assertThat((events.last() as ShowDialog).positiveButtonId).isEqualTo(R.string.simple_payments_cash_dlg_button)
         assertThat((events.last() as ShowDialog).negativeButtonId).isEqualTo(R.string.cancel)
     }
 
+    @Test
+    fun `given simple payment flow, when on cash payment clicked, then show dialog event emitted`() =
+        testBlocking {
+            // Given
```
Comment (kidinov) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModelTest.kt]: nit:  given, when, then are uppercased in other tests, so maybe it's good to keep it this way for consistency

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt [hunk 4]
```diff
@@ -91,24 +92,50 @@ class SelectPaymentMethodViewModel @Inject constructor(
...
-                titleId = R.string.simple_payments_cash_dlg_title,
-                messageId = R.string.simple_payments_cash_dlg_message,
-                positiveButtonId = R.string.simple_payments_cash_dlg_button,
-                positiveBtnAction = { _, _ ->
-                    onCashPaymentConfirmed()
-                },
-                negativeButtonId = R.string.cancel
-            )
-        )
+        when (cardReaderPaymentFlowParam.paymentType) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt]: If my understanding of the tracking here is correct then the whole method can be written in a more concise way:

```
    fun onCashPaymentClicked() {
        analyticsTrackerWrapper.track(
            AnalyticsEvent.PAYMENTS_FLOW_COLLECT,
            mapOf(
                AnalyticsTracker.KEY_PAYMENT_METHOD to VALUE_SIMPLE_PAYMENTS_COLLECT_CASH,
                cardReaderPaymentFlowParam.toAnalyticsFlowParams(),
            )
        )
        val messageIdForPaymentType = when (cardReaderPaymentFlowParam.paymentType) {
            SIMPLE -> R.string.simple_payments_cash_dlg_message
            ORDER -> R.string.existing_order_cash_dlg_message
        }
        triggerEvent(
            MultiLiveEvent.Event.ShowDialog(
                titleId = R.string.simple_payments_cash_dlg_title,
                messageId = messageIdForPaymentType,
                positiveButtonId = R.string.simple_payments_cash_dlg_button,
                positiveBtnAction = { _, _ ->
                    onCashPaymentConfirmed()
                },
                negativeButtonId = R.string.cancel
            )
        )
    }
```

**Review by kidinov — COMMENTED** [review]
The change's looking good to me! I left a couple of nitpicky comments, please take a look!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt (hunk 1 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt]: Thank you for reviewing it. I misunderstood the way this was being tracked.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt (hunk 4 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/SelectPaymentMethodViewModel.kt]: 💯 Thank you

**Review by kidinov — APPROVED** [review]
