### PR TITLE
Localize date formatting in shipment tracking card

### LINKED ISSUE #976: Orders: Date format in shipment tracking is not localized
**Describe the bug**

In the shipment tracking, the shipment date ("Shipped %s") is translated but the date format is not localized. As a result, the date is always formatted "month day, year" even for locales that use a different format.

**To Reproduce**
1. Add shipment tracking to an order in your store.
2. Confirm the tracking appears in the app with the correct date in English.
3. Change your device language to another language, e.g. Spanish.
4. Confirm the month is translated but the format doesn't change.

**Screenshots**

Shipment tracking in Spanish:

Screenshot_20190409-141612

**Expected behavior**

In Spanish, I expect the date to be formatted with the day first, e.g. "30 de agosto de 2018" instead of "agosto 30, 2018."

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1
- WooCommerce Android version: 1.6-rc-1

cc @AmandaRiu

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #976 

Swapped out the manual formatting in favor of `DateFormat.getLongDateFormat()` so the date string will be formatted to match the locale the device is currently in. 

Examples

**English**
Screen Shot 2019-04-15 at 12 01 36 PM

**Espaniol**
Screen Shot 2019-04-15 at 12 01 53 PM

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt [hunk 1]
```diff
@@ -103,20 +102,20 @@ object DateUtils {
     }
 
     /**
-     * Given an ISO8601 date of format YYYY-MM-DD, returns the stirng in the full format of ("MMM d, YYYY".
+     * Given a date of format YYYY-MM-DD, returns the string in the full format of ("MMM d, YYYY".
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt]: This comment should be rewritten to make it clear the returned date is localized.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/DateUtils.kt]: Nice catch! I've updated the method as well so it's super clear what it does and that it's localized. 398b4703ecc4958a3cfb8166fcbf466ea494c451

**Comment by AmandaRiu** [comment]
@nbradbury comments addressed. Ready for review.

**Comment by nbradbury** [comment]
:shipit:
