### PR TITLE
Fix crashes in Jetpack Activation flow

### LINKED ISSUE #8049: IllegalArgumentException: Site not cached
Sentry Issue: [WOOCOMMERCE-ANDROID-5EG](https://sentry.io/organizations/a8c/issues/3785096532/?referrer=github_integration)

```
IllegalArgumentException: Site not cached
    at com.woocommerce.android.ui.login.jetpack.main.JetpackActivationMainViewModel$site$1.invokeSuspend(JetpackActivationMainViewModel.kt:78)
...
(6 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8049

### Description
This PR fixes two scenarios that led to the crash we get in the ticket above:
1. The first case happens during Magic link connection, and I believe this has been happening since releasing the feature, as we shipped this [part](https://github.com/woocommerce/woocommerce-android/pull/8470), the Jetpack installation wasn't implemented yet, and we probably missed re-testing the whole flow later.
2. The second case happens when the user enters the address of an already connected site.

### Testing instructions
Optional: It would be great if you can reproduce the crashes first on `trunk` before testing with this branch.

##### Case 1:
1. Prepare a site where Jetpack is not connected (or not installed)
2. Connect to the site in the app using site credentials.
3. In the Dashboard, click on the Jetpack benefits banner.
4. Start the installation, then enter your WordPress.com email.
5. Use the magic link login.
6. Finish the installation.
7. The app would crash on trunk and wouldn't on this branch.

##### Case 2:
1. Sign in using WordPress.com email.
2. Open the site picker, then click on Add a store, then connect an existing store.
3. Enter the address while using `wp-admin` as suffix of a site already connected to the WordPress.com email.
4. 
    - On trunk, the app would attempt to start the Jetpack installation, and later would crash.
    - On this branch, the app would identify the site as already connected and select it as the active site.

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainFragment.kt [hunk 1]
```diff
@@ -96,12 +96,10 @@ class JetpackActivationMainFragment : BaseFragment() {
     }
 
     private fun goToStore() {
-        (requireActivity() as? MainActivity)?.handleSitePickerResult() ?: run {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainFragment.kt:99]: `handleSitePickerResult` uses the `restart` function in `MainActivity`, this function reuses the intent that was used for opening the screen, since for this case we are coming from the Magic link flow with a deeplink to the Jetpack installation, then the app would try to continue, but since the site is already connected, it would lead to the crash.

Instead of making any change to `handleSitePickerResult` that might impact other areas, I decided to go with the simple approach of fully restarting MainActivity.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thank you for fixing this @hichamboushaba 🏅 I spent quite some time looking into this crashes and I wasn't able to find the culprit of them so :kudos for it. 
The code looks good and the fix makes sense. However I was not able to reproduce `case 2` on `trunk`. The app didn't crash for me. It did crash for `case 1` though and I could verify it didn't on this PR branch. 

Let's keep an eye on Sentry after releasing this. :shipit:

**Comment by hichamboushaba** [comment]
Thanks for the review @JorgeMucientes 🙏 

> The code looks good and the fix makes sense. However I was not able to reproduce case 2 on trunk

The crash occurs after attempting the connection, meaning after entering the site credentials and fetching the site, at least it did crash for me at this step.
Anyway, regardless of the crash, we don't want the user to go through the flow for this case.
