### PR TITLE
Account for nullability

### LINKED ISSUE #956: Fatal Exception: java.lang.IllegalStateException: empty_view must not be null
From Fabric:

```
Fatal Exception: java.lang.IllegalStateException: empty_view must not be null
       at com.woocommerce.android.ui.orders.OrderListFragment.shouldShowFilterMenuItem(OrderListFragment.java:164)
       at com.woocommerce.android.ui.orders.OrderListFragment.refreshOptionsMenu(OrderListFragment.java:134)
       at com.woocommerce.android.ui.orders.OrderListFragment.onPrepareOptionsMenu(OrderListFragment.java:118)
       at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2575)
       at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManagerImpl.java:3353)
       at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:343)
       at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:548)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
       at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2576)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
       at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:522)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
       at android.view.Choreographer.doCallbacks(Choreographer.java:699)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6349)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**First Seen In:** `1.4`
**Users Affected:** `1`
**Source:** `5c9d5f34f8b88c296339865b-fabric`

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #956 by checking if the view is empty before accessing its `visibility` property. I'm not sure why this is happening since the view should be instantiated at the point of building the options menu, but I've added it to cover the null pointer exception. This crash had only happened one time for a single user.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt [hunk 1]
```diff
@@ -154,7 +154,7 @@ class OrderListFragment : TopLevelFragment(), OrderListContract.View,
 
     private fun shouldShowFilterMenuItem(): Boolean {
         return when {
-            (isShowingAllOrders() && empty_view.visibility == View.VISIBLE) -> false
+            (isShowingAllOrders() && empty_view?.visibility == View.VISIBLE) -> false
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt]: This works, but there's still a potential NPE here. If `empty_view` is null it means the fragment isn't attached, in which case accessing `childFragmentManager` below will cause an NPE. Returning `false` when `isAdded = false` should correct this.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderListFragment.kt]: Good call. Updated in 16834355b5cf86b7e8bc55e8d4adedd46538ad47

**Comment by AmandaRiu** [comment]
@nbradbury ready for second round

**Comment by nbradbury** [comment]
Looks good, let's :shipit: !
