### PR TITLE
Lock shipping lines when the screen is not idle or the order editable

### LINKED ISSUE #12869: Shipping Lines in Order Creation are editable at all times
**Describe the bug**
The shipping lines in the order creation/order edit flows, are editable at all times. For example, when the order is being refreshed, I'm able to edit the shipping lines even though all the other features on the other are disabled. I'm also able to edit shipping lines when I enter the edit mode on a paid order.

**To Reproduce**
1. Go to Order List
2. Click on Create Order
3. Add a product
5. Notice `Add shipping` button is disabled when the order is refreshed (this is expected behavior)
6. Add a shipping line
7. 🐛 Notice the added shipping line is editable when the order is refreshed
8. Add a product
9. 🐛  Notice `Add shipping` button is enabled when the order is refreshed (this is not expected)

1. Open detail of a paid order with a shipping line
2. Tap on Edit
3. Notice you can edit shipping lines even though the order is not editable

**Expected behavior**
Shipping line should be disabled when editing paid orders or when the order is being updated in the background in the order creation. The behavior should be consistent with Coupons when [this PR is merged](https://github.com/woocommerce/woocommerce-android/pull/12855).

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #12869 

### Description
This PR fixes the issue of the shipping lines being editable at all times. It does that by introducing the `ShippingLineSection` class that includes the isEnabled state. Relying on the isEnabled state value, the shipping lines section now locks(disabled) the interaction with the shipping lines controls if the isEnabled property is false,

### Testing information

1. Go to Order List
2. Click on Create Order
3. Add a product
4. Notice Add shipping button is disabled when the order is refreshed
5. Add a shipping line
6. Notice the added shipping line is disabled when the order is refreshed
7. Add a product
8. Notice Add shipping button is disabled when the order is refreshed

### The tests that have been performed
1. Testing that the shipping lines section is disabled when the order is refreshing or is not editable.

### Images/gif

https://github.com/user-attachments/assets/5c87bad7-0993-44e5-a9cf-4539bd198466

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 1]
```diff
@@ -380,30 +378,19 @@ class OrderCreateEditViewModel @Inject constructor(
...
-                    name = shippingLine.methodTitle,
-                    shippingMethod = method,
-                    amount = shippingLine.total
+    val shippingLineSection = viewStateData.liveData
+        .combineWith(
+            orderDraft.map { it.shippingLines },
+            getShippingMethodsWithOtherValue().asLiveData()
+        ) { viewState, shippingLines, shippingMethods ->
+            if (viewState == null || shippingLines == null || shippingMethods == null) return@combineWith null
+            shippingLines.toShippingLineDetails(shippingMethods)?.let { shippingLineDetails ->
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt:387]: I wrapped the shipping line mapping into an extension function and added some unit tests to improve the code documentation.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 2]
```diff
@@ -480,20 +467,20 @@ class OrderCreateEditViewModel @Inject constructor(
         }
     }
 
+    private var _isFirstShippingLineChange = true
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt:470]: Adding two observers to the same live data seems to be the source of the crash raised [here](https://a8c.slack.com/archives/C6H8C3G23/p1731051811921849). To avoid this kind of issue, I decided to follow a different approach, using the `_isFirstShippingLineChange` to check whether it was the first change on the shipping lines.

**Review by ThomazFB — APPROVED** [review]
I can confirm the PR fixes the issue, nice work with the fix @atorresveiga! Looks good
