### PR TITLE
Issue/10043 attempt jetpack connection fix

### LINKED ISSUE #10043: [REST API] Jetpack connection is broken for Application Passwords login
When trying to connect Jetpack using Application Passwords login, the WebView gets dismissed before the user can approve the connection, the same flow works correctly in iOS, so we need to compare the implementation and fix Android.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #10043 

### Description
While I couldn't reproduce 10043 consistently like what happened to me on Friday, I found some edge cases where it happens, and my theory is that they are caused by the instability of the `https://wordpress.com/jetpack/connect` that we use for Application Passwords flow. This PR attempts a way for the user to recover from the error, instead of offering a retry that doesn't help.
The retry logic we have in this screen, allows retrying just the last step, while when this issue occurs, we need to retry the `connection` step itself, and not just the `validation`, and this PR does this exactly.

The PR also adds a second fix, I'll explain in the comments below.

### Testing instructions
The test is not straightforward, either do it, or trust me that I did it 😅 
1. Create a site that has Jetpack but not connected.
2. Sign in to the site using the app.
3. Click on the Jetpack benefits banner.
4. Debug the app, and put a breakpoint at this [line](https://github.com/woocommerce/woocommerce-android/blob/4f61b6b2e176c679ee61d50dd7c9c5c9d9d33871/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt#L461).
5. Start the WordPress.com authentication, and proceed until the breakpoint is hit.
6. Go to the site, and start Jetpack connection, but don't click on Approve in the account screen (this establishes a site-only connection).
7. Go back to the app, and resume execution.
8. Notice that the WebView is dismissed automatically without connection, and an error is shown.
9. Click on Retry.
10. Confirm it allows you to retry the connection step, and you can connect successfully now.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt [hunk 1]
```diff
@@ -260,22 +266,23 @@ class JetpackActivationMainViewModel @Inject constructor(
                 )
             }
             .distinctUntilChanged()
-            .filter { it.state == StepState.Ongoing }
-            .map { it.type }
-            .onEach { stepType ->
+            .collectLatest { step ->
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:269]: I had to refactor this to allow stopping the `connectionStep` Flow collection when the step changes, otherwise the collection continues, and we keep showing the WebView without any user action.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt [hunk 2]
```diff
@@ -405,7 +410,7 @@ class JetpackActivationMainViewModel @Inject constructor(
     private suspend fun startJetpackConnection() {
         WooLog.d(WooLog.T.LOGIN, "Jetpack Activation: start Jetpack Connection")
         val currentSite = site.await()
-        val useApplicationPasswords = currentSite.connectionType == SiteConnectionType.ApplicationPasswords
+        val useApplicationPasswords = selectedSite.connectionType == SiteConnectionType.ApplicationPasswords
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: This is the second fix I mentioned, this was using the **Site** we are connecting Jetpack too as a way to see if the application is using Application Passwords, and that's not what we want, we want to check against the app's selected site.
Without this fix, the Jetpack connection from the Site Picker's "Connect an existing site" always assumed the app is using Application Passwords, and was using the less reliable endpoint `https://wordpress.com/jetpack/connect`, instead of the default one.

If interested, I can offer testing steps to reproduce the above and confirm the fix.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModelTest.kt [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+import org.mockito.kotlin.doSuspendableAnswer
+import org.mockito.kotlin.mock
+import org.mockito.kotlin.whenever
+import org.wordpress.android.fluxc.model.SiteModel
+
+/**
+ * This is still missing tests for some scenarios, for now it covers only the connection step and its flows.
+ */
+@OptIn(ExperimentalCoroutinesApi::class)
+class JetpackActivationMainViewModelTest : BaseUnitTest() {
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModelTest.kt:35]: We didn't have any tests for this class, as we were trying to get the feature ready ASAP, but with all the new features, its logic is getting more complicated, so I tried to add some tests, for now, it's just for the connection step.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: Hey @Hicham, while testing these changes I noticed some strange behavior, which could possibly be related to this change? Unsure about it though, because I'm still trying to wrap my ahead about all the different scenarios in which we can attempt to connect Jetpack and what happens behind scenes in each of those. 

It seems like we do not support connecting to an existing store that is already connected to Jetpack with another account. However the changes from this PR introduce an error while attempting that. 

**Scenario 1** Attempting to connect my account `mucidev@gmail.com` to an existing store that is already connected to Jetpack to a different account (jorge.mucientes@automattic.com)

- When running this scenario from `trunk` it seems that I'm able to connect my current accout `mucidev` to the existing store. However after finishing the connection flow, I'm prompted to log in entering the password of the WP.com account that was already connected to the site: 

https://github.com/woocommerce/woocommerce-android/assets/2663464/3ebfad79-4aa0-4679-820b-3546fdd58a6d

- When running this same scenario from `issue/10043-attempt-jetpack-connection-fix` results in an webview error where I'm stuck: 


https://github.com/woocommerce/woocommerce-android/assets/2663464/5277b98c-8162-4ea9-b443-67619f8b3173


**Scenario 2** Attempting to connect an existing store that is not connected to Jetpack. Both case work well. Just sharing for reference but nothing wrong here. 

- Running from `trunk` everything works well


https://github.com/woocommerce/woocommerce-android/assets/2663464/e757eddb-ff3d-4a20-a4a8-baf646881788


- Running form `issue/10043-attempt-jetpack-connection-fix` everything works as expected too


https://github.com/woocommerce/woocommerce-android/assets/2663464/7d3b777e-6634-43bc-851b-f4b62585e440

**Comment by JorgeMucientes** [comment]
Thanks for working on this @hichamboushaba. This type of bugs are always hard to diagnose and fix (I always have a hard time understanding everything that is going on tbh). I've tested the described instructions and everything works as expected. However, while doing some additional testing trying to figure out how things work, I found a new Jetpack connection flow that is not behaving as expected. And I think some of the changes from this PR have an impact on it. Please review my comment in case it rings the bell 🙂

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: Thanks for the extensive testing @JorgeMucientes.

> It seems like we do not support connecting to an existing store that is already connected to Jetpack with another account

Yes, we don't, because Jetpack doesn't offer a way to disconnect the previous account, and generally I receive an error that says that Jetpack is already connected, I'm not sure why in your case it offered you to connect a different account, which clearly didn't happen, it seems like a bug on Jetpack side.

> When running this same scenario from issue/10043-attempt-jetpack-connection-fix results in an webview error where I'm stuck:

I don't think the changes on the branch would impact this, the error seems like a caching issue, just same as what happened before (the first issue here https://github.com/woocommerce/woocommerce-android/pull/7936#issuecomment-1326422269)), can you clear the app's cache and retry the test? I'll try to the same too.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: > I don't think the changes on the branch would impact this, the error seems like a caching issue, just same as what happened before (the first issue here https://github.com/woocommerce/woocommerce-android/pull/7936#issuecomment-1326422269)), can you clear the app's cache and retry the test? I'll try to the same too.

@JorgeMucientes I confirmed this, but I needed to clear the app's data, not just the cache.
This is not something new in this PR, and it's not a bug of the app, but a weird behavior of the connection WebView after passing the redirect_uri in a previous session. Also in the next PR I'm working, it will be fixed as a side effect of other changes, as I will add the redirect URI to exit triggers regardless of the flow.

Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: Hey @hichamboushaba 

> Yes, we don't, because Jetpack doesn't offer a way to disconnect the previous account, and generally I receive an error that says that Jetpack is already connected,

Do we need to disconnect the previous account? Afaik Jetpack support connecting several WP account to the same site. 

> just same as what happened before (the first issue here https://github.com/woocommerce/woocommerce-android/pull/7936#issuecomment-1326422269)), can you clear the app's cache and retry the test? I'll try to the same too.

Good memory! After clearing the cache, out of the 2 tests I ran, one worked and the other didn't, it left me stuck in a blank WordPress page. See recording below. In any case, is an issue with the webview not loading and unrelated to this PR. 

https://github.com/woocommerce/woocommerce-android/assets/2663464/0ab02a67-782f-4800-95a5-810ae0c7c617

**Review by JorgeMucientes — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: > Do we need to disconnect the previous account? Afaik Jetpack support connecting several WP account to the same site.

Yes, because this is using the same wp-admin account which is already connected, Jetpack supports multiple accounts when using multiple wp-admin accounts, which is not what happens here.

> After clearing the cache, out of the 2 tests I ran, one worked and the other didn't, it left me stuck in a blank WordPress page

The blank WordPress page happens to me from time to time, I think it's an instability of Calypso, I'm not sure we can do anything here 🤷.

Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt:413]: > Yes, because this is using the same wp-admin account which is already connected, Jetpack supports multiple accounts when using multiple wp-admin accounts, which is not what happens here.

Oh that's true. Thanks for clarifying.
