### PR TITLE
Avoid race conditions and ensure statsTimeRangeSelection is set

### LINKED ISSUE #11776: UninitializedPropertyAccessException: lateinit property statsTimeRangeSelection has not been initialized
Sentry Issue: [WOOCOMMERCE-ANDROID-AXE](https://a8c.sentry.io/issues/5354507623/?referrer=github_integration)

```
UninitializedPropertyAccessException: lateinit property statsTimeRangeSelection has not been initialized
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.getChartXAxisLabelCount(DashboardStatsView.kt:230)
    val resId = when (statsTimeRangeSelection.selectionType) {
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.updateChartView(DashboardStatsView.kt:587)
    labelCount = getChartXAxisLabelCount()
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsView.updateView(DashboardStatsView.kt:393)
    updateChartView()
    at com.woocommerce.android.ui.dashboard.stats.DashboardStatsCardKt$StatsChart$4.invokeSuspend(DashboardStatsCard.kt:213)
    statsView.updateView(revenueStatsState.revenueStats)
...
(20 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #11776 

### Description

Tricky bug here. I'll try to provide context on what I think is happening and then explain the proposed solution.
The [crash](https://a8c.sentry.io/issues/5354507623/?project=1459556&referrer=github_integration) we are trying to resolve here is due to a race condition due to async updates of the UI.
The way we update the UI for the stats card is by using effects through `LaunchedEffect()` functions. [LaunchedEffect](https://developer.android.com/develop/ui/compose/side-effects#launchedeffect) starts a suspending function. That means that the order of execution of the following LaunchedEffects is not guaranteed: 

```kotlin
    LaunchedEffect(dateRange?.rangeSelection) {
        dateRange?.rangeSelection?.let { statsView.loadDashboardStats(it) }
    }

    LaunchedEffect(lastUpdateState) {
        statsView.showLastUpdate(lastUpdateState)
    }

    LaunchedEffect(revenueStatsState) {
        when (revenueStatsState) {
            is DashboardStatsViewModel.RevenueStatsViewState.Content -> {
                statsView.showErrorView(false)
                statsView.showSkeleton(false)
                statsView.updateView(revenueStatsState.revenueStats)
            }
...
        }
    }

    LaunchedEffect(visitorsStatsState) {
        visitorsStatsState?.let {
            statsView.showVisitorStats(it)
        }
    }
```

When the call to `statsView.updateView(revenueStatsState.revenueStats)` happens before the call to ` dateRange?.rangeSelection?.let { statsView.loadDashboardStats(it) }` the app will crash. 

About the proposed fix, I'll try to explain it right where the code changes are applied. That will provide better context

### Steps to reproduce
Applying a small delay inside `LaunchedEffect(dateRange?.rangeSelection)`:

```kotlin
    LaunchedEffect(dateRange?.rangeSelection) {
        delay(500)
        dateRange?.rangeSelection?.let { statsView.loadDashboardStats(it) }
    }
```
We'll be able to reproduce the race condition consistently and the crash will happen all the time.

### Testing information

- Activate the performance card in the dashboard. 
- Smoke test it by changing through all the different date ranges, by dragging your finger through the chart, by swiping to refresh, enabling "Don't Keep activities" and navigating back and forth to the dashboard scree. In essence, test any possible scenario for the card looking for possible UI issues.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt [hunk 1]
```diff
@@ -197,17 +197,10 @@ private fun StatsChart(
     // is applying all properties on each composition (even the unchanged ones) which creates issues with the legacy
     // view.
 
-    LaunchedEffect(dateRange?.rangeSelection) {
-        dateRange?.rangeSelection?.let { statsView.loadDashboardStats(it) }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt:201]: Move this call to line 203 inside `LaunchedEffect(revenueStatsState)`.
The reasons I did this are: 
- This will fix the race condition and ensure that whenever we load the chart the date range is set. 
- If `dateRange` is updated that means `revenueStatsState.Content` will be updated anyway. And vice-versa. So, I don't think we have the need of updating them independently, and removing that independence avoids potential race conditions and bugs.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt [hunk 2]
```diff
@@ -233,9 +226,16 @@ private fun StatsChart(
 
     LaunchedEffect(visitorsStatsState) {
         visitorsStatsState?.let {
-            statsView.showVisitorStats(it)
+            statsView.showVisitorStats(
+                it,
+                dateRange?.rangeSelection
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsCard.kt:231]: This `LaunchedEffect` is also subject to the race condition, and when updating visitors stats we need to ensure that a `rangeSelection` value is set. So, passing the `rangeSelection` as param ensures we won't see the `UninitializedPropertyAccessException` when updating visitor stats too.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt [hunk 3]
```diff
@@ -92,7 +92,6 @@ class DashboardStatsView @JvmOverloads constructor(
             // to appear, and we remove the chart's empty string so it doesn't briefly show
             // up before the chart data is added once the request completes
             if (value) {
-                clearStatsHeaderValues()
                 binding.chart.setNoDataText(null)
                 binding.chart.clear()
             } else {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt:97]: I'm not the biggest fan of this setter with "hidden" side effects. But eliminating the side effects while keeping the stats view bug free is not straightforward, hence I only removed one line that I felt it was safe to remove and that resolved and issue I explain next. 
The reason I removed `clearStatsHeaderValues()` after applying the changes to the `LaunchedEffect` effect function are the following: 
- Clearing the header values should be the responsibility of the loading states
- This change led to empty stats headers when the race condition happened and `statsView.showVisitorStats()` was being called before `statsView.loadDashboardStats(it)` in the code changes applied above to `DashboardStatsView`. 
- Unless I've missed something removing this didn't cause any unwanted UI states.

**Review by hafizrahman — APPROVED** [review]
The logic you explained makes sense to me, and looking at the original crash error this hopefully should be a good fix.

I did various tests on the emulator, also with changing orientations, etc, and I'm not seeing any issue.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt (hunk 3 above)
Comment (hafizrahman) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt:97]: > Unless I've missed something removing this didn't cause any unwanted UI states.

I'm also not seeing any issue in my tests.
