### PR TITLE
[Woo POS – Custom Payment UI] Fix state mismatch after system "back" in Payment failed screen

### LINKED ISSUE #13161: [Woo POS] Home screen state mismatch navigating back from Payment failed
There's a bug navigating back from Payment failed screen – Home screen state is mismatch, showing cart in Checkout mode, without "Checkout" button.

### PR DESCRIPTION
**Pull request by samiuelson**
### Fix for state mismatch after system "back" in Payment failed screen

Closes: #13161 

### Steps to reproduce

1. Go to POS (More > Point of sale)
2. Create order
3. Produce failed card payment
4. Press "back" button from Payment failed screen
5. Observe state mismatch:
Screenshot_20241218_153932

### Testing information

When clicking "back" in Payment failed screen, we should go back to "Checkout" state, and the reader should restart payment action. 

### The tests that have been performed

I verified the above scenario works fine.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/245">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt [hunk 1]
```diff
@@ -149,67 +150,91 @@ class WooPosTotalsViewModel @Inject constructor(
         cardReaderPaymentController?.stop()
     }
 
-    @Suppress("LongMethod")
     fun onUIEvent(event: WooPosTotalsUIEvent) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt:153]: 👍

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt [hunk 2]
```diff
@@ -149,67 +150,91 @@ class WooPosTotalsViewModel @Inject constructor(
...
                 }
             }
+        }
+    }
 
-            WooPosTotalsUIEvent.ConnectReaderClicked -> cardReaderFacade.connectToReader()
+    private fun handleBackPress() {
+        viewModelScope.launch {
+            when (state.value) {
+                is PaymentFailed, is PaymentInProgress -> {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/totals/WooPosTotalsViewModel.kt:231]: I am wondering if it would be more clear to have different events when the system is back invoked from different payment states? `OnBackFromPaymentFailed/Processed...Clicked` with one parent `OnBackFromPayments` class, so we can have `when` here without "else" and also we won't need to check the state. wdyt?

**Review by kidinov — APPROVED** [review]
The code looks good and tests well, apart from one thing, which may be something related to the emulated reader, but I can reliably reproduce stucking of the payment in the "preparing" state if you go back from processing a couple of times


https://github.com/user-attachments/assets/4e05a167-8e88-4ab6-ad3c-6433c82eb272

**Comment by samiuelson** [comment]
> The code looks good and tests well, apart from one thing, which may be something related to the emulated reader, but I can reliably reproduce stucking of the payment in the "preparing" state if you go back from processing a couple of times

Hmm, I do not see issue with the simulated reader. I'll spend some more time testing though. Thanks for sharing!
