### PR TITLE
Handle network error coupon order creation

### LINKED ISSUE #9314: Improve validation and network error messages in Order creation > Coupon Edit text field
The Order creation > Coupon Edit screen performs coupon validation by making API call and checking if the coupon code exists in the store. However, we don't show any error messages, just set error to the text field which results in highlighting it to red without any meaningful error message.

Expected behaviour: 
We should show two types of messages
1. "Entered coupon is invalid try different one"
2. "Something went wrong. Couldn't check the coupon. Try again" - this could be a retriable Snacbar

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #9314 (it's been closed already, this builds up on the previous PR)

### Description

This PR adds an option to handle the coupon validation error in two different ways:

First regarding the actual coupon code validation and then by handling a network error. 

### Testing instructions

1. Go to the orders tab
2. click on + to add a new order
3. add a product
4. click on Add coupon
5. type any random thing that is not a valid coupon code in the text field
6. click on Done
7. make sure the correct error message is displayed : `We couldn't find a coupon with that code. Please try again`
8. erase the code
9. disable the internet
10. type a coupon code (valid or invalid, doesn't matter)
11. make sure the correct error message is displayed `Something went wrong when validating your coupon code. Please try again`
12. enabled internet again
13. add a valid coupon code
14. makes sure it is properly added
15. try to remove the coupon
16. make sure the code is correctly removed

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt [hunk 1]
```diff
@@ -1,15 +1,31 @@
...
 class CouponValidator @Inject constructor(
     private val selectedSite: SelectedSite,
     private val store: CouponStore,
+    private val context: Context,
 ) {
-    suspend fun isCouponValid(code: String): Boolean {
-        val result = store.searchCoupons(selectedSite.get(), code).model ?: return false
-        return result.coupons.find { code.lowercase() == it.coupon.code?.lowercase() } != null
+    suspend fun isCouponValid(code: String): CouponValidationResult {
+        val networkAvailable = NetworkUtils.isNetworkAvailable(context)
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt]: ⚠️ We don't need to check if the network is available in the isCouponValid function. It would suit more for things like enabling/disabling the "Done" button, but not for coupon validation use case. Instead, we want here to look into the result returned by the `store.searchCoupons()`. If it returns an error, we want to return `NETWORK_ERROR`, if it's successful, we want it to execute the same logic as previously.
 
Sorry for the confusion, the issue description might not be very clear about it. Let me know if this makes sense.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt [hunk 2]
```diff
@@ -1,15 +1,31 @@
...
+        val validCoupon = coupons?.find { it.coupon.code?.equals(code, ignoreCase = true) == true }
+
+        return when {
+            !networkAvailable -> CouponValidationResult.NETWORK_ERROR
+            validCoupon != null -> CouponValidationResult.VALID
+            else -> CouponValidationResult.INVALID
+        }
+    }
+
+    enum class CouponValidationResult {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt:28]: ❤️ This is a good model for validation result

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt [hunk 3]
```diff
@@ -90,7 +100,7 @@ class OrderCreateCouponEditViewModel @Inject constructor(
         val validationState: ValidationState = ValidationState.IDLE,
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt]: 💡 Now, that the `ViewState.validationState` became dynamic it would be nice to improve the ViewState's error data model as well. It would be optimal to have the error message and "retriability" state computed by the view model instead of Fragment. Ideally, the validation error state would contain the following properties:
```kotlin
data class Error(
  message: String,
  isRetriable: Boolean,
)
```

1. In the fragment, we would just take the `message` String and display it. The advantage of having a more advanced view state model like this is that we move the logic of retrieving the error message to the view model and we can test it.

2. Other than that, now that we have two different error types we need to adjust the `isDoneButtonEnabled` state accordingly. If the coupon error indicates the coupon doesn't exist we should disable the Done button forcing user to change the code before they can retry. However, in case the error indicates the backend/network error we should enable the Done button so that the user can retry the operation without need to modify the coupon.

**Review by samiuelson — COMMENTED** [review]
Thanks @rossanafmenezes, that's solid work. I'd like to enhance a few parts of the implementation before shipping it. I've added a few comments with improvement ideas. Let me know if they make sense 🙂

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt (hunk 3 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt]: 1 - Fixed here   [f2958a7](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/f2958a77596f7e536cd52d33b38b95cd9b3946ad) and [599cca2](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/599cca2db9021d3ec6bd4b2830f63d6af426ae47) 

As discussed we decided the retriable was not needed. 

2 - Fixed here [0e27cac](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/0e27cac2c90dbd014561b161a22ec7e6e3e929d1)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt (hunk 1 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/CouponValidator.kt]: No worries and thank you for clarifying 😄 

Fixed here [f6eca04](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/f6eca0442af41f6f0aa8bc4305682982c3771c46)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt [hunk 4]
```diff
@@ -84,13 +97,23 @@ class OrderCreateCouponEditViewModel @Inject constructor(
...
-    enum class ValidationState { IDLE, IN_PROGRESS, ERROR }
+    @Parcelize
+    sealed class ValidationState : Parcelable {
+        @Parcelize
+        object Idle : ValidationState()
+        @Parcelize
+        object InProgress : ValidationState()
+        @Parcelize
+        data class Error(
+            val message: Int,
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt]:
```suggestion
            @StringRes  val message: Int,
```
💡 It would be nice to add `@StringRes` here

Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditViewModel.kt]: Thanks! Added here [8c6c278](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/8c6c278391f8fd12feab0659718a02e219ec4533)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditScreen.kt [hunk 5]
```diff
@@ -39,7 +38,12 @@ fun OrderCreateCouponEditScreen(
             .fillMaxWidth()
     ) {
         val focusRequester = remember { FocusRequester() }
-        val isError = state.value?.validationState == ERROR
+        val errorMessage: OrderCreateCouponEditViewModel.ValidationState.Error =
+            state.value?.validationState as? OrderCreateCouponEditViewModel.ValidationState.Error
+                ?: OrderCreateCouponEditViewModel.ValidationState.Error(R.string.order_creation_coupon_network_error)
+        val isError = state.value?.validationState == OrderCreateCouponEditViewModel.ValidationState
+            .Error(errorMessage.message)
+
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditScreen.kt:42]: 💡 These two `val`s could be simplified to this:
```kotlin
val isError = state.value?.validationState is ValidationState.Error
val errorMessage: Int? = (state.value?.validationState as? ValidationState.Error)?.message
```
It would be better to declare `errorMessage` closer to the place it's used (`Text(...)`) or maybe even to inline it.

**Review by samiuelson — COMMENTED** [review]
@rossanafmenezes It works well and looks good overall 👍🏼 I've added a tiny suggestion to clean up the code. Let me know what you think!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditScreen.kt (hunk 5 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/coupon/edit/OrderCreateCouponEditScreen.kt:42]: Makes sense. Thank you for pointing that out. Fixed here [e2a854f](https://github.com/woocommerce/woocommerce-android/pull/9365/commits/e2a854f3c6dc666b72b60e6d4e695b80fcbb4f0c)

**Review by samiuelson — APPROVED** [review]
LGTM! :shipit:
