### PR TITLE
[Beta fix] Fix crash with Composable DatePickerDialog

### LINKED ISSUE #11425: IllegalStateException: Size(2147483647 x 126) is out of range. Each dimension must be between 0 and 16777215.
Sentry Issue: [WOOCOMMERCE-ANDROID-AHF](https://a8c.sentry.io/issues/5283346082/?referrer=github_integration)

```
IllegalStateException: Size(2147483647 x 126) is out of range. Each dimension must be between 0 and 16777215.
    at com.woocommerce.android.ui.compose.component.DialogButtonsRowLayoutKt$DialogButtonsRowLayout$measurePolicy$1$1.measure-3p2s80s(DialogButtonsRowLayout.kt:61)
    return layout(constraints.maxWidth, height) {
    at com.woocommerce.android.ui.compose.component.DialogButtonsRowLayoutKt$DialogButtonsRowLayout$measurePolicy$1$1.maxIntrinsicWidth(DialogButtonsRowLayout.kt:0)
...
(102 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #11425 

### Description
We recently updated Compose version (https://github.com/woocommerce/woocommerce-android/pull/11330), and this update included a new [change](https://android-review.googlesource.com/c/platform/frameworks/support/+/2946951) to check the dimensions we pass during the layout, this change caused the app to crash when trying to use the `DatePickerDialog`.
The cause is that for the `DatePickerDialog` we use `DialogButtonsRowLayout` to lay the buttons as a stack when needed, and we use [Intrinsic measurements](https://developer.android.com/develop/ui/compose/layouts/intrinsic-measurements) to make sure the dialog's header can match the size of the dialog without going more than needed. In `DialogButtonsRowLayout` we were handling the intrinsic measurements of the `height`, but not the `width`, which meant that we got a `Constraint.Infinity` when trying to lay it out.

### Testing instructions
TC 1:
1. Open the app.
2. Open the coupons screen.
3. Click on ➕ to add a new coupon.
4. Click on "Expiry date".
5. Confirm the app doesn't crash.
6. Rotate your phone, and confirm the dialog layout is updated accordingly.

TC 2:
Check the previews of `DialogButtonsRowLayout` and confirm there is no regression.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/208">18.4 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/DialogButtonsRowLayout.kt [hunk 1]
```diff
@@ -58,26 +58,32 @@ fun DialogButtonsRowLayout(
                     placeables.maxOf { it.height }
                 }
 
-                return layout(constraints.maxWidth, height) {
+                val width = if (constraints.maxWidth != Constraints.Infinity) {
+                    constraints.maxWidth
+                } else {
+                    placeables.sumOf { it.width }
+                }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/compose/component/DialogButtonsRowLayout.kt:65]: This is not needed now with the intrinsics constraint fix below, but I added it to avoid any potential crash in the future if Compose made any other changes, and this is a safe check, the worst that could happen is that the buttons will be placed a bit to the left instead of being right justified.

**Review by malinajirka — APPROVED** [review]
Great investigation and fix @hichamboushaba!  I've been able to reproduce the crash and confirm it works as expected with the fix. I tested it on a phone and a tablet to double-check the dialog is rendered correctly.
