### PR TITLE
[Shipping Labels Revamp] Finish Purchased screen UI feedback and data

### LINKED ISSUE #12288: After purchasing a shipping label UI
Image

Design considerations:

> - After purchasing, you’re no longer “creating a shipping label,” and I think the screen title should reflect this. This deviates from order creation, but I don’t think it feels unexpected.
> - As mentioned earlier, let’s keep the order details screen the same for now – with one exception: Change the text on the button and have it navigate to the success screen.

❗ We will work on the updated order details screen on M4

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #12288 by adding the following behaviors to the Purchased Shipping Label screen:
-  Shipping Label data transfer between the main Shipping Label form and the Purchased screen
- Wire the `WooShippingLabelPurchasedScreen` implementation with the respective ViewModel and ViewState
- Proper handling of Tracking and Pick Up options and their respective URLs
- Wire the original Shipping Labels `learn more` screen with the Label printing tooltip
- Loading and Error feedback
- `WooShippingLabelPurchasedViewModel` unit test coverage

Screen Capture
==========
https://github.com/user-attachments/assets/e0332965-6d33-443b-85f7-3c04a6db11e8

How to Test
==========
1. Open the main Shipping Label screen
2. Since the Purchased screen is only accessible from the landscape screen binding, switch the device to landscape mode
3. Hit the Purchase button
4. Once in the Purchased Screen, verify that the Shipping data is correctly presented, the `track shipment` and the `schedule pickup` buttons are working properly.
5. Hit the Print Shipping Label and verify that for each of the Paper size, the Shipping Label is opened in a separate screen following the selected paper size.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/245">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+        viewModel.onPrintShippingLabelClicked()
+
+        assertThat(viewStateUpdates).hasSize(3)
+        assertThat(viewStateUpdates[0].isPrintingInProgress).isFalse()
+        assertThat(viewStateUpdates[1].isPrintingInProgress).isTrue()
+        assertThat(viewStateUpdates[2].isPrintingInProgress).isFalse()
+    }
+
+    @Test
+    fun `ViewState starts with LABEL paper size as default`() {
```
Comment (atorresveiga) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt:78]: FYI: In M4, we might need to update this because we plan to get the default paper size from the account settings

Comment (ThomazFB) [reply WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/purchased/WooShippingLabelPurchasedViewModelTest.kt:78]: Oh, that's useful information; thanks for letting me know! 🙏

**Review by atorresveiga — APPROVED** [review]
Everything is working as described. Nice unit test coverage @ThomazFB !

LGTM! :shipit:
