### PR TITLE
Track barcode format when the product search via SKU fails

### LINKED ISSUE #9126: Add barcode format to the product search via SKU failure event
The goal of this task is to add the barcode format used when the product search via SKU fails. This information gives us which barcode format is failing the most. Do we need to handle the checksum for that format ...etc

More context: p1685078975281749-slack-C025A8VV728

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #9126 

### Description

This PR tracks the barcode format when the product search via SKU fails. This information gives us which barcode format is failing the most. Do we need to handle the checksum for that format ...etc

More context: p1685078975281749-slack-C025A8VV728

### Testing instructions

1. Navigate to the order creation screen (Orders tab -> "+")
2. Tap on the barcode icon under the products section
3. Scan any invalid SKU with a different barcode format from the online barcode generator website
4. On product search via SKU failure, ensure product_search_via_sku_failure event is tracked
5. Ensure the `barcode_format` property is proper.
6. Repeat step 3 to 5 with different barcode formats.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleBarcodeFormatMapper.kt [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        }
+    }
+
+    sealed class BarcodeFormat(val formatName: String) : Parcelable {
+        @Parcelize
+        object FormatAztec : BarcodeFormat("aztec")
+        @Parcelize
+        object FormatCodaBar : BarcodeFormat("codabar")
+        @Parcelize
+        object FormatCode128 : BarcodeFormat("code 128")
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleBarcodeFormatMapper.kt]: np: maybe to use `code_128` etc as this is for tracking and we usually use this notation?

File: WooCommerce/src/main/res/navigation/nav_graph_main.xml [hunk 2]
```diff
@@ -108,6 +108,10 @@
                 android:name="sku"
                 app:argType="string"
                 app:nullable="true"/>
+            <argument
```
Comment (kidinov) [inline WooCommerce/src/main/res/navigation/nav_graph_main.xml:111]: np: you can consider putting Sku and BarcodeFormat in one structure, so there will be a compile time check that it should be either both SKU and BarcodeFormat or none of them

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleBarcodeFormatMapper.kt (hunk 1 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/GoogleBarcodeFormatMapper.kt]: Done here: https://github.com/woocommerce/woocommerce-android/pull/9129/commits/0429ad953d7fafedc119a648cd71b055a9825b99

**Review by kidinov — APPROVED** [review]
LGTM!

```
Tracked: product_search_via_sku_failure, Properties: {"source":"order_list","barcode_format":"qr code","reason":"Empty data response (no product found for the SKU)","blog_id":192152755,"is_wpcom_store":true,"is_debug":true}
```

File: WooCommerce/src/main/res/navigation/nav_graph_main.xml (hunk 2 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/res/navigation/nav_graph_main.xml:111]: Agree. I'll take this in a separate PR just so that we can merge and get the feature out to merchants.
