### PR TITLE
[Custom Amounts] Fix: Use currency code instead of symbol in Custom Amounts screen 

### LINKED ISSUE #13839: IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
Sentry Issue: [WOOCOMMERCE-ANDROID-K7T](https://a8c.sentry.io/issues/6340501333/?referrer=github_integration)

```
IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
    at com.woocommerce.android.ui.orders.creation.product.discount.CurrencySymbolFinder.findCurrencySymbol(CurrencySymbolFinder.kt:8)
    return Currency.getInstance(currencyCode).symbol
    at com.woocommerce.android.ui.orders.creation.OrderCreateEditViewModel.getCurrencySymbol(OrderCreateEditViewModel.kt:1963)
    fun getCurrencySymbol() = currencySymbolFinder.findCurrencySymbol(currentDraft.currency)
    at com.woocommerce.android.ui.orders.creation.OrderCreateEditFormFragment$bindShippingLinesSection$1$1$1$1.invoke$lambda$5$lambda$4(OrderCreateEditFormFragment.kt:433)
    currencyFormatter.formatCurrency(amount, viewModel.getCurrencySymbol())
    at com.woocommerce.android.ui.orders.creation.OrderCreateEditFormFragment$bindShippingLinesSection$1$1$1$1.$r8$lambda$oNQUuUOmrzYyJHRFv6Vbx_eU6qc(OrderCreateEditFormFragment.kt:0)
    at com.woocommerce.android.ui.orders.creation.OrderCreateEditFormFragment$bindShippingLinesSection$1$1$1$1$$ExternalSyntheticLambda2.invoke(OrderCreateEditFormFragment:0)
...
(245 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #13839 

### Description

This PR fixes a bug where the Custom Amounts screen was using the currency symbol (e.g., "₹", "$") instead of the currency code (e.g., "INR", "USD") when handling currency values. 

### Steps to reproduce

1. Navigate to Orders tab
2. Tap on "+" button to create a new order
3. Click on "Add custom amount" button
4. Enter custom amount and click on "Add custom amount" CTA
5. In the logs, ensure you see the stack trace that complains invalid currency code
6. After this PR, ensure you don't see the stack trace anymore when adding custom amounts

### The tests that have been performed

Tested adding, deleting custom amounts

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt [hunk 1]
```diff
@@ -734,7 +734,7 @@ class OrderCreateEditFormFragment :
                 OrderCreateEditNavigationTarget.CustomAmountDialog(
                     customAmountUIModel.copy(
                         type = FIXED_CUSTOM_AMOUNT,
-                        currency = viewModel.getCurrencySymbol()
+                        currency = viewModel.orderDraft.value?.currency
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt]: We really should use proper naming here and in the order, too. Reading this code I still have no idea what we actually passing both ways

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 2]
```diff
@@ -332,9 +332,11 @@ class OrderCreateEditViewModel @Inject constructor(
     val pendingSelectedItems: StateFlow<List<SelectedItem>> = _pendingSelectedItems
 
     val customAmounts: LiveData<List<CustomAmountUIModel>> = _orderDraft
-        .map { order -> order.feesLines }
-        .map { feeLines ->
-            feeLines.map { feeLine -> mapFeeLineToCustomAmountUiModel(feeLine, getCurrencySymbol()) }
+        .map { order ->
+            val currency = order.currency
+            order.feesLines.map { feeLine ->
+                mapFeeLineToCustomAmountUiModel(feeLine, currency)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt:339]: `operator fun invoke(feeLine: Order.FeeLine, orderCurrency: String)`

What is expected here? Currency code or currency symbol?

The same in other places, e.g. `CustomAmountUIModel::currency`

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt [hunk 3]
```diff
@@ -107,6 +113,14 @@ class CustomAmountsViewModel @Inject constructor(
         updateCustomAmountType()
     }
 
+    fun getCurrencySymbol(currencyCode: String?): String? {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt]: We should avoid exposing methods from the VMs and calling them from the fragment. We cannot predict when this will be called as we do not control the flow. Instead, the VM's state should represent a compile-time defined set of states that the view must represent. I think this should be refactored

**Review by kidinov — COMMENTED** [review]
@AnirudhBhat Thank you for working on this!

I haven't tested it yet, but I think the PR doesn't fix the root cause of the issue, which as I believe is confusing code. I think aside from fixing the confusing naming (calling everything `currency`), we should go further and clearly separate where currency code must be used and where currency symbol. Maybe it's a good place to use value classes so the compiler can help us.

```
    @JvmInline
    value class CurrencySymbol(private val s: String)

    @JvmInline
    value class CurrencyCode(private val s: String)
```

Another point - we should follow basic architecture rules. We should not get anything from the VMs, except from subsribing to the state changes and events stream. I realize that you can not fix all the cases in this PR, but at least not adding the new ones would be great


```
currency = viewModel.orderDraft.value?.currency
```

This is the same, and it's not good either. How do you know that the state is still the same at the moment of constructing navigation events and VM events? This is clear path to random inconsistencies, which not detectable and not fixable

**Comment by AnirudhBhat** [comment]
@kidinov Thanks for the review. I've refactored the code to reduce the naming confusion and changes to the way we fetch currency symbol and code from the view model. Please take a look and let me know what you think. https://github.com/woocommerce/woocommerce-android/pull/13875/commits/0bb148f192f2930430e16d7862514ca07e004fe0

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt [hunk 4]
```diff
@@ -729,12 +730,13 @@ class OrderCreateEditFormFragment :
         if (viewModel.orderContainsProductsOrCustomAmounts()) {
             displayCustomAmountTypeBottomSheet()
         } else {
+            val currencyCode = viewModel.currencyCodeLiveData.value?.value?.let { CurrencyCode(it) }
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditFormFragment.kt]: It looks like there might be a little confusion here! You're passing `customAmountUIModel`, which contains its `currencyCode`, and then you're also exposing another `currencyCodeLiveData` that uses the same order currency. 

On top of that, there are params

```
        customAmountUIModel: CustomAmountUIModel = CustomAmountUIModel.EMPTY,
        orderTotal: String = viewModel.orderDraft.value?.total.toString(),
```

And `orderTotal` never passed to the method? While `customAmountUIModel only once?

We shall receive and event from VM that contains the data we want to pass to another screen. We should not check here `viewModel.orderContainsProductsOrCustomAmounts()` either

Probably better not to touch it in this PR, but to fix it along with 

https://github.com/woocommerce/woocommerce-android/issues/13821
?
wdyt?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt [hunk 5]
```diff
@@ -316,6 +317,9 @@ class OrderCreateEditViewModel @Inject constructor(
     val selectedItems: StateFlow<List<SelectedItem>> =
         _orderDraft.map { order -> order.selectedItems() }.toStateFlow(emptyList())
 
+    val currencyCodeLiveData: LiveData<CurrencyCode?> =
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: I believe it's important to reconsider exposing this here. How can we ensure that when any navigation event or UI state reaches the fragment, this LiveData maintains its expected state? The event that triggers the change should carry all the necessary data; it's best that we get the state from the ViewModel

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt [hunk 6]
```diff
@@ -94,6 +103,14 @@ class CustomAmountsViewModel @Inject constructor(
             )
         }
 
+    val currencySymbolLiveData: LiveData<CurrencySymbol?> = liveData {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt]: It's the same here! Just place the data you need for navigation or the UI in the state and event when it's triggered, rather than pulling it later from the fragment

**Review by kidinov — COMMENTED** [review]
Thanks @AnirudhBhat for all the improvements! Looks much better to me! Could you please consider a couple of more comments I left?

**Comment by AnirudhBhat** [comment]
@kidinov Thanks for the review. I've improved the UI and the ViewModel state updation logic. Please take a look and let me know what you think. Thanks!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt [hunk 7]
```diff
@@ -97,6 +107,7 @@ class CustomAmountsViewModel @Inject constructor(
     private val args: CustomAmountsFragmentArgs by savedState.navArgs()
 
     init {
+        setCurrencySymbol()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt]: Just to validate that this is your expectation here. Order can be different, but there are two steps:
* You push and render the UI with the state that contains only the currency symbol 
* You push and render the UI with the rest of the state, including the currency symbol

So if the step 2 takes too much time a user is going to see only currency symbol there?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 5 above)
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Unused

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt (hunk 7 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt]: Maybe merge both steps into one?

**Review by kidinov — APPROVED** [review]
LGTM! I left a couple of minor comments, please take a look

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt (hunk 5 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreateEditViewModel.kt]: Removed : https://github.com/woocommerce/woocommerce-android/pull/13875/commits/78c3fbb2a9e003f12274792b0aac7bbadd07fbb9

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt (hunk 7 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/customamounts/CustomAmountsViewModel.kt]: Good call - Merged here: https://github.com/woocommerce/woocommerce-android/pull/13875/commits/78c3fbb2a9e003f12274792b0aac7bbadd07fbb9

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/255">22.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
