### PR TITLE
Background image uploads: product creation case

### LINKED ISSUE #4742: Handle background uploads for product creation flow.

### LINKED ISSUE #4743: Ongoing image uploads are lost when creating a new product
When creating a product, if you start uploading images before creating the product, they will get lost when you save the product.
To reproduce:

1. Go to product list.
2. Tap on the '+' button to create a new product.
3. Top on the add images button, and select local images.
4. When the images are still uploading.
5. Tap on "publish"
6. Notice that the uploads are not being displayed.

If you stay until the uploading finishes, the images will eventually get added to the product, but it's not a good experience.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #4742 and #4743

### Description
This PR updates logic of image uploads to handle products under creation, this is a summary of the flows:

1. If the update has been assigned an id (user already clicked on `save as draft` or `publish`), then the product will follow the same behavior as editing a regular product.
2. If the user saves the product while there are ongoing uploads, we'll cancel them and recreate new ones using the new product id (as the products are sequential, it means we'll cancel only the ongoing one, and remove the other ones from the queue).
3. If the user tries to leave the product screen while there are still ongoing uploads, and the product hasn't been saved, then we will do the following:
   - First, we will stop observing upload changes, this will make the handler responsible for the uploads, so it will cache the successful events.
   - If the user decides to discard changes, then we will just cancel uploads.
   - If the user decides to save the product as a draft, then the same flow as saving the product will take place, which means that the uploads will be assigned to the new product id, and be uploaded/saved in the background.
   - If the user decides to return to the product, then we will restart observing image upload changes.

### Testing instructions
The test cases will match the above changes.

##### Case 1
1. Click on create a product.
2. Make some changes and save the product (or publish it).
3. Add some images to the product (from local device)
4. While the images are still being uploaded, leave the product screen.
5. Confirm that the snackbar about image uploads is displayed, and that they continue the upload in the background.
6. Confirm that the product is updated afterwards with the uploaded images.

##### Case 2
1. Click on create a product.
2. Add some images to the product (from local device)
3. While the images are still being uploaded, click on save as draft (or publish).
4. Confirm that the ongoing and successful uploads are assigned to the new product.
5. Confirm that the upload continues, and that you can both wait and save the product, or leave the uploads to continue in the background.

##### Case 3
1. Click on create a product.
2. Add some images to the product (from local device)
3. While the images are still being uploaded, leave the product screen.
4. Confirm that the discard changes dialog is displayed.
5. Click on Save as draft button.
6. Confirm that once the product is saved, the upload continues in the background.
7. Confirm that the product is successfully updated with the new images.

##### Case 4
1. Click on create a product.
2. Add some images to the product (from local device)
3. While the images are still being uploaded, Swipe the app away from the recent app menu
4. Confirm that the upload is cancelled.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt [hunk 1]
```diff
@@ -199,6 +199,7 @@ class ProductImagesUploadWorker @Inject constructor(
             val doneUploads = uploadList.count { it.isDone }
             notificationHandler.update(doneUploads + 1, uploadList.size)
             try {
+                work.fetchedMedia.postId = work.productId
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/media/ProductImagesUploadWorker.kt:202]: This is not related to this PR, but it's something I missed in the previous PR #4720

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 2]
```diff
@@ -533,43 +537,42 @@ class ProductDetailViewModel @Inject constructor(
...
+            } else null
+
+            val message = if (isUploadingImagesForNonCreatedProduct) string.discard_images_message
+            else string.discard_message
+
             triggerEvent(
                 ShowDialog(
+                    messageId = message,
+                    positiveButtonId = string.discard,
+                    negativeButtonId = string.keep_editing,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:570]: I added an explicit to those, since we previously has been depending on default values specified here https://github.com/woocommerce/woocommerce-android/blob/697172b843b1357f402808f24d829fe13f91a721/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dialog/WooDialog.kt#L39-L40 And those can be changed for any reason, and IMO we should remove them.

**Review by 0nko — APPROVED** [review]
All the test cases work as expected, nice work 👍. 

I just noticed that I'm seeing a memory leak in CanaryLeak in the `ProductDetailFragment` (gallery view). This probably isn't related, though, so we can look at that later.

**Comment by 0nko** [comment]
We can merge after the conflicts are resolved.

**Comment by hichamboushaba** [comment]
Thanks @0nko for the review, I fixed the conflict, and I just noticed that we have a specific file for tests related to the creation flow, I moved the tests to it in 0e40d3c, if you want to take a second look 🙏

**Comment by 0nko** [comment]
Thanks! There's just some detekt issue.
