### PR TITLE
[Better Tablet Products] Fixed bug when after configuration change results of the search were lost

### LINKED ISSUE #10987: [Better Tablet Products] After configuration change search results are lost

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10987

### Description

The PR fixes a regression caused by this PR https://github.com/woocommerce/woocommerce-android/pull/10844/files

### Testing instructions

* Open products
* Start search
* Rotate the screen
* Notice that the results still there

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/bace9fcf-b5a6-4acc-a30c-f7ab84ea8239

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListToolbarHelper.kt [hunk 1]
```diff
@@ -155,8 +158,10 @@ class ProductListToolbarHelper @Inject constructor(
...
 
             val isSearchActive = viewModel?.viewStateLiveData?.liveData?.value?.isSearchActive == true
-            if (menuItem.isActionViewExpanded != isSearchActive) {
-                if (isSearchActive) {
+            if (isSearchActive) {
+                if (menuItem.isActionViewExpanded) {
+                    enableSearchListeners()
+                } else {
                     disableSearchListeners()
                     menuItem.expandActionView()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductListToolbarHelper.kt:166]: When the toolbar is used, it recreates its state itself, but it does it later than this code is executed (before that was called from "onPrepareMenu")

At the same time, we still need to hook search listeners after configuration changes that's why I added it on L163

**Comment by backwardstruck** [comment]
Able to reproduce the issue. Looks fixed in this branch.

**Review by backwardstruck — APPROVED** [review]
Thanks for the explanation about the search listeners. Make sense.
