### PR TITLE
[Woo POS] We end up in inconsistent state after failed payments flow

### LINKED ISSUE #12342: [Woo POS] We end up in inconsistent state after failed payments flow
To reproduce:
* Start the payment flow with amount that ends in the error with contact support button (55cents)
* When an error displayed click on contact support button
* Come back
* Notice that we show products and cart in the checkout state

### PR DESCRIPTION
**Pull request by backwardstruck**
[Woo POS] Fix Inconsistent State Post-Failed Payments

Closes: #12342  

### Description  
This PR addresses an issue where users could experience inconsistent application states upon resuming the app while in POS mode. Specifically, the checkout state was not preserved correctly, resulting in the app reverting to a cart state even though it should remain on the checkout screen.

The root cause of the issue was that cart-related state changes were mistakenly triggering during the checkout process, especially after the app was resumed from the background. This was due to `CartStatusChanged` events inappropriately influencing the screen state even during an ongoing checkout process. Upon resuming the app, these events were processed, leading to an incorrect transition back to the cart screen from the checkout screen.

### Steps to reproduce  

A.
1. Add items to the cart.
2. Proceed to checkout.
3. Send app to the background/lock the screen for 15 or more seconds and then resume.
4. Notice that prior to the fix, the app might revert to the cart screen.

B.
1. Start the payment flow with amount that ends in the error with contact support button (e.g. by adding a product to the cart that ends in $0.55 cents)
2. When an error displayed click on contact support button
3. Come back after waiting 15 - 20 seconds
4. Notice that we are in the Correct state

C. (possibly the same underlying issue appears in these steps identified by @kidinov )
1. Enable don't keep activities in developer options
2. Go to checkout
3. Hide and open the app

### Testing information  
Ensure that the checkout process is resilient to interruptions from background task executions or potential race conditions involving state changes:
- Test with rapidly switching between app and other apps to simulate real-world use cases.

### The tests that have been performed  
- Device Tests: Tested on physical Android tablet.
- Test Cases:
  - Simulated payment failure followed by immediate app backgrounding.
  - Normal checkout process to ensure no regressions were introduced.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.  
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.  
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by kidinov** [comment]
@backwardstruck 👋

> The root cause of the issue was that cart-related state changes were mistakenly triggering during the checkout process, especially after the app was resumed from the background

I think the main question is why is this being triggered. If the activity is running in the background and not killed, then why would anything be triggered 🤔 ? Did you understand? I thought maybe it's because the activity is killed (and the VMs), but actually, when the activity is killed, we end up in another inconsistent state. This could be related to this bug or maybe not - not sure, but we should fix that

It may be crucial to understand the root cause in order to avoid breaking something else with our fix

**Comment by kidinov** [comment]
@backwardstruck oops sorry I noticed that I attached the wrong video 🙈

To reproduce:
* Enable don't keep activities
* gow to checkout
* Hide and open the app

**Comment by backwardstruck** [comment]
> @backwardstruck oops sorry I noticed that I attached the wrong video 🙈
> 
> To reproduce:
> 
> * Enable don't keep activities
> * gow to checkout
> * Hide and open the app

Yes, I am able to reproduce. With more testing, I also found that `listenBottomEvents` is also called while in the product/cart screen after locking the screen for 15 seconds. I agree that we shouldn't necessarily be seeing this event in the first place, or at least we should know why it is being called.

**Comment by backwardstruck** [comment]
It seems that the state in `WooPosCartViewModel` is not saved correctly because we `scan` in the VM and detect the previous state incorrectly:

`scan(_state.value) { previousState, newState`

Somehow the previous state is the Old previous state, not the previous state that was set when we arrived on the checkout screen. I think it's OK that `scan` is being called but it should find that there is no change upon comparing `previousState` and `newState`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt [hunk 1]
```diff
@@ -48,7 +49,8 @@ class WooPosCartViewModel @Inject constructor(
             updateParentCartStatusIfCartChanged(previousState, newState)
             newState
         }
-        .asLiveData()
+        .distinctUntilChanged()
+        .asLiveData(viewModelScope.coroutineContext)
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: Unfortunately, these changes don't fix the issue either. I'm looking now at the lifecycle changes to see if we are saving/restoring the VM correctly.

**Comment by kidinov** [comment]
@backwardstruck 👋

I don't understand why`scan` even triggered. Does the activity die after 15 seconds?

If you feel stuck on this, please let me know - I can take a look tomorrow

**Comment by backwardstruck** [comment]
> @backwardstruck 👋
> 
> I don't understand why`scan` even triggered. Does the VM die if the activity in stop stat 15 seconds or so?
> 
> If you feel stuck on this, please let me know - I can take a look tomorrow

Indeed. It's very strange that something is causing the VM to be saved and restored, but only after 15 seconds, then causing `scan` to be called.

It appears that when the activity is paused or stopped for an extended period, the VM state might not be saved or restored correctly. This could be causing `scan` to use an outdated `previousState` upon resuming.

I considered that the VM might be getting destroyed if the activity is kept in the stopped state for too long.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt [hunk 2]
```diff
@@ -57,6 +60,16 @@ class WooPosCartViewModel @Inject constructor(
         listenEventsFromParent()
     }
 
+    fun onSave() {
+        Log.d("WooPosCartViewModel", "Saving state: ${_state.value}")
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: it seems that the state of the vm on Save is this:

```
WooPosCartState(cartStatus=EDITABLE, toolbar=Toolbar(icon=null, itemsCount=null, isClearAllButtonVisible=false), body=WithItems(itemsInCart=[Item(id=Id(productId=15, itemNumber=3), name=Garment-dyed Super Soft Slub Cotton Hoodie in Ash, price=$70.00, imageUrl=https://i0.wp.com/woototallyselflessbearcoconutsoap.blog/wp-content/uploads/2024/01/product-3-1.png?fit=600%2C818&ssl=1, isAppearanceAnimationPlayed=false), Item(id=Id(productId=15, itemNumber=2), name=Garment-dyed Super Soft Slub Cotton Hoodie in Ash, price=$70.00, imageUrl=https://i0.wp.com/woototallyselflessbearcoconutsoap.blog/wp-content/uploads/2024/01/product-3-1.png?fit=600%2C818&ssl=1, isAppearanceAnimationPlayed=false), Item(id=Id(productId=15, itemNumber=1), name=Garment-dyed Super Soft Slub Cotton Hoodie in Ash, price=$70.00, imageUrl=https://i0.wp.com/woototallyselflessbearcoconutsoap.blog/wp-content/uploads/2024/01/product-3-1.png?fit=600%2C818&ssl=1, isAppearanceAnimationPlayed=false)]), areItemsRemovable=true, isCheckoutButtonVisible=true)
```

Which i would have expected to show as checkout state rather than editable. So maybe we are somehow saving the previous state when we pause the activity while on the checkout screen.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AnirudhBhat** [comment]
@backwardstruck @kidinov I quickly looked at the code and it seems like the problem here is that`WooPosHomeViewModel` emits wrong event `ChildToParentEvent.CartStatusChanged.NotEmpty` instead of `CheckoutClicked(productIds=[PRODUCT_ID])` when resuming the POS from background.

This in turn causes `WooPosHomeScreen` to build incorrect scroll state
```

@Composable
private fun buildScrollStateForNavigationBetweenState(state: WooPosHomeState.ScreenPositionState): ScrollState {
    val scrollState = rememberScrollState()
    LaunchedEffect(state) {
        val animationSpec = spring<Float>(dampingRatio = 0.8f, stiffness = 200f)
        println("cartdebugging: updating scroll state! " + state.toString())
        when (state) {
            is WooPosHomeState.ScreenPositionState.Cart ->
                scrollState.animateScrollTo(
                    0,
                    animationSpec = animationSpec
                )

            is WooPosHomeState.ScreenPositionState.Checkout -> scrollState.animateScrollTo(
                scrollState.maxValue,
                animationSpec = animationSpec
            )
        }
    }
    return scrollState
}

```

>I don't understand why scan even triggered

AFAIU, `scan` is turned into `LiveData` and hence, it gets triggered when there is a lifecycle change which is expected behaviour. Am I missing something here?

**Comment by AnirudhBhat** [comment]
```

private fun updateParentCartStatusIfCartChanged(previousState: WooPosCartState, newState: WooPosCartState) {
        if (previousState.body.amountOfItems == newState.body.amountOfItems) return
        when (newState.body) {
            is WooPosCartState.Body.Empty -> {
                sendEventToParent(ChildToParentEvent.CartStatusChanged.Empty)
            }

            is WooPosCartState.Body.WithItems -> {
                sendEventToParent(ChildToParentEvent.CartStatusChanged.NotEmpty)
            }
        }
    }

```

When this method gets triggered on resume from background, we update the cart status to `NotEmpty` when its actually `CHECKOUT`

This `NotEmpty` is being handled in `WooPosHomeViewModel` and modifies the cart state accordingly

```
private fun handleCartStatusChanged(event: ChildToParentEvent.CartStatusChanged) {
        if (_state.value.screenPositionState is WooPosHomeState.ScreenPositionState.Checkout.Paid) {
            return
        }

        val newScreenPositionState = when (event) {
            ChildToParentEvent.CartStatusChanged.Empty -> WooPosHomeState.ScreenPositionState.Cart.Visible.Empty
            ChildToParentEvent.CartStatusChanged.NotEmpty -> WooPosHomeState.ScreenPositionState.Cart.Visible.NotEmpty
        }
        _state.value = _state.value.copy(screenPositionState = newScreenPositionState) // - We are updating the cart state as NotEmpty here when its actually Checkout.NotPaid?
    }

```

**Comment by AnirudhBhat** [comment]
```

private fun handleCartStatusChanged(event: ChildToParentEvent.CartStatusChanged) {
        if (_state.value.screenPositionState is WooPosHomeState.ScreenPositionState.Checkout.Paid) {
            return
        }

        val newScreenPositionState = when (event) {
            ChildToParentEvent.CartStatusChanged.Empty -> WooPosHomeState.ScreenPositionState.Cart.Visible.Empty
            ChildToParentEvent.CartStatusChanged.NotEmpty -> WooPosHomeState.ScreenPositionState.Cart.Visible.NotEmpty
        }
        _state.value = _state.value.copy(screenPositionState = newScreenPositionState) // - We are updating the cart state as NotEmpty here when its actually Checkout.NotPaid?
    }

```

I think its not necessary to update the parent about the cart status when the cart state is `CHECKOUT`. If my understanding is correct. A simple check like below would fix this issue

`if (newState.cartStatus == CHECKOUT) return`

**Comment by kidinov** [comment]
@backwardstruck I pushed a commit, which removes all the code that causes the troubles as we do not react now on the home screen level when the cart is empty or not. We used that when we were hiding it, but the design has changed now

7f48e667603008a9c45b963e9c647b0368edfc0d

**Comment by backwardstruck** [comment]
> ```
> 
> private fun handleCartStatusChanged(event: ChildToParentEvent.CartStatusChanged) {
>         if (_state.value.screenPositionState is WooPosHomeState.ScreenPositionState.Checkout.Paid) {
>             return
>         }
> 
>         val newScreenPositionState = when (event) {
>             ChildToParentEvent.CartStatusChanged.Empty -> WooPosHomeState.ScreenPositionState.Cart.Visible.Empty
>             ChildToParentEvent.CartStatusChanged.NotEmpty -> WooPosHomeState.ScreenPositionState.Cart.Visible.NotEmpty
>         }
>         _state.value = _state.value.copy(screenPositionState = newScreenPositionState) // - We are updating the cart state as NotEmpty here when its actually Checkout.NotPaid?
>     }
> ```
> 
> I think its not necessary to update the parent about the cart status when the cart state is `CHECKOUT`. If my understanding is correct. A simple check like below would fix this issue
> 
> `if (newState.cartStatus == CHECKOUT) return`

All these comments make sense @AnirudhBhat Thanks for helping to solve the mystery! Indeed, I had tried something like this earlier, but we were still not sure why the wrong status we being sent in the first place.

As you said, when onResume was called from background, the cart status was being incorrectly updated to `NotEmpty`.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/233">20.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt [hunk 3]
```diff
@@ -44,11 +43,7 @@ class WooPosCartViewModel @Inject constructor(
     )
 
     val state: LiveData<WooPosCartState> = _state
-        .scan(_state.value) { previousState, newState ->
-            updateParentCartStatusIfCartChanged(previousState, newState)
-            newState
-        }
-        .asLiveData()
+        .asLiveData(viewModelScope.coroutineContext)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: Do you think we need to specify context here?

**Review by kidinov — APPROVED** [review]
LGTM! I just left one question - not sure if that was intentional change

ah, and seems some tests still broken

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt (hunk 3 above)
Comment (backwardstruck) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: Indeed. That's unnecessary to be specified. Was a leftover from my earlier attempt.
