### PR TITLE
Issue/9997 restore fragment crash

### LINKED ISSUE #9997: RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.Ma...
Sentry Issue: [WOOCOMMERCE-ANDROID-36Q](https://a8c.sentry.io/issues/2975642260/?referrer=github_integration)

```
IllegalStateException: No instantiated fragment for (fb6815ce-8d63-4cd8-bc54-6e671708956f)
    at com.woocommerce.android.ui.main.AppUpgradeActivity.onCreate(AppUpgradeActivity.kt:59)
    at com.woocommerce.android.ui.main.MainActivity.onCreate(MainActivity.kt:266)
...
(26 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.ui.main.MainActivity}: java.lang.IllegalStateException: No instantiated fragment for (fb6815ce-8d63-4cd8-bc54-6e671708956f)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by 0nko**
Possibly fixes #9997.

I wasn't able to reproduce the exact same crash, but the issue, which is related to fragment restoration, is similar to [this one](https://issuetracker.google.com/issues/246519668), which I was able to reproduce. The solution is to update the `Fragment` library to 1.6.0+ version. Because the `Fragment` and its co-dependencies `Activity` & `Lifecycle` libraries were extremely outdated, I had to update all 3 of them. 

This PR updates the relevant dependencies and it could potentially fix many other issues that we are currently missing out on. I can confirm the updates fixed the issue above.

**To test:**
While these are minor version updates, we are jumping forward by over a year of releases. It would be great if we could thoroughly smoke-test the app to make sure nothing is broken.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt [hunk 1]
```diff
@@ -50,7 +52,10 @@ class AnalyticsHubFragment :
         super.onViewCreated(view, savedInstanceState)
         bind(view)
         setupResultHandlers(viewModel)
-        lifecycleScope.launchWhenStarted { viewModel.viewState.collect { newState -> handleStateChange(newState) } }
+        lifecycleScope.launch {
+            withStarted { } // suspend until the fragment is started
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt]: np, `withStarted` doesn't replicate the effect of `launchWhenStarted`, as the latter used a custom Dispatcher that pauses execution when the scope goes below the `Started` state.
As a proper replacement for the deprecated function, I suggest the following:
```kotlin
        viewLifecycleOwner.lifecycleScope.launch {
            viewModel.viewState.flowWithLifecycle(lifecycle).collect { newState -> handleStateChange(newState) }
        }
```

Note: A second fix that would make the code more consistent with the rest of the code base is to make `viewState` a `LiveData` but it would require more effort, so let's keep it for another time.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt [hunk 2]
```diff
@@ -409,7 +411,8 @@ class LoginActivity :
             .commitAllowingStateLoss()
     }
 
-    private fun showPrologueFragment() = lifecycleScope.launchWhenStarted {
+    private fun showPrologueFragment() = lifecycleScope.launch {
+        withStarted { } // suspend until the fragment is started
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt]: np, Is this really needed here? I know it's to replicate the effect of `launchWhenStarted`, but I wonder if `launchWhenStarted` was actually needed too.
And if we want to keep it, I would suggest the following format instead:
```kotlin
    private fun showPrologueFragment() = lifecycleScope.launch {
        withStarted {
            val prologueFragment = getPrologueFragment() ?: LoginPrologueFragment()
            changeFragment(prologueFragment, true, LoginPrologueFragment.TAG)
        }
    }
```
WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt [hunk 3]
```diff
@@ -532,11 +534,13 @@ class MyStoreFragment :
...
         // For the banner to be above the bottom navigation view when the toolbar is expanded
-        viewLifecycleOwner.lifecycleScope.launchWhenCreated {
+        viewLifecycleOwner.lifecycleScope.launch {
             // Due to this issue https://issuetracker.google.com/issues/181325977, we need to make sure
-            // we are using `launchWhenCreated` here, since if this view doesn't reach the created state,
+            // we are using `withCreated` here, since if this view doesn't reach the created state,
             // the scope will not get cancelled.
             // TODO: revisit this once https://issuetracker.google.com/issues/127528777 is implemented
+            // (no update as of Oct 2023)
+            withCreated { }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt]: np, same as above, I suggest you put the logic inside `withCreated` which is easier to read IMO.

**Review by hichamboushaba — APPROVED** [review]
Nice work @0nko, hopefully these updates fix the crashes.
I left some minor comments regarding the usage of `withStarted` and `withCreated`, please take a look at them.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt]: Oh ok, good to know! 👍

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt (hunk 2 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt]: > Is this really needed here?

I wasn't sure either and I wanted to minimize the risk of breaking something, so I add it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt (hunk 3 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt]: This would require adding another `launch` call inside `withCreated` because of the `collect()` suspend function, so I found this to be simpler. But if you prefer, I can put it inside.

**Comment by 0nko** [comment]
Thanks for the review, @hichamboushaba. I've addressed/replied to your comments. Ready for another round.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt (hunk 3 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt]: I see, I thought `withCreated` accepts a suspendable block too. You can leave it this way, or you can get around this with something like this:
```kotlin
viewLifecycleOwner.lifecycleScope.launch {
            withCreated {
                appBarLayout.verticalOffsetChanges()
                    .onEach { verticalOffset ->
                        binding.jetpackBenefitsBanner.root.translationY =
                            (abs(verticalOffset) - appBarLayout.totalScrollRange).toFloat()
                    }
                    .launchIn(this)
            }
}
```

Your choice 🙂

**Comment by hichamboushaba** [comment]
@0nko I replied to your comment above, and there is a detekt issue, once it's fixed, feel free to merge the PR.
Thank you 🙏

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt]: @hichamboushaba 

I'm just curious why this is not a proper replacement. If my understanding is correct, somebody from Google [recommends](https://issuetracker.google.com/issues/270049505#comment2) this approach as a replacement

Although, I agree that the proposal solution looks better than `withStarted`

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/hub/AnalyticsHubFragment.kt]: @kidinov the suggestion on the issue says: **"Let the suspending code continue to run to completion."**, and also has a comment  ` // Note: your code will continue to run even if the Lifecycle falls below STARTED`, and that's what I meant exactly, with `withStarted`, the flow collection will continue to happen also after the lifecycle gets stopped, while with `launchWhenStarted`, it used a hacky solution to create a custom [dispatcher](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/PausingDispatcher.kt;l=215) that pauses execution when the lifecycle is stopped, which means the code `newState -> handleStateChange(newState)` won't be called. (I said hacky because the Flow's upstream kept running regardless of the Lifecycle state, which is why it was deprecated)

For short-running suspendable functions, this doesn't have any difference, but for a Flow collection, it does have an impact, and that's why on the same ticket, the second suggestion below **"Cancel the suspending code and restart it when you come back above that state."** uses `repeatOnLifecycle` which is exactly the same as `flowWithLifecycle`.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt (hunk 3 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt]: I like your solution, thanks 👍
