### PR TITLE
Issue/4356 printing on configuration change 2

### LINKED ISSUE #4356: [Card Present Payments] The paymentflow stucks on the "loading" after the "print receipt" button clicked and configuration change happens
How to reproduce:

* Finish the payment flow
* Click on the "print receipt" button and change the orientation of the device right away
* Notice that loading is still in progress and "printing" preview is not shown

### PR DESCRIPTION
**Pull request by malinajirka**
Resolves #4356

This PR is heavily based on [the solution implemented](https://github.com/woocommerce/woocommerce-android/pull/4359) by @kidinov with a few changes.

I recommend reviewing this PR by commits.

Summary of the changes - for details refer to [the original PR](https://github.com/woocommerce/woocommerce-android/pull/4359)
- Print/Send buttons are hidden when the OS printing UI is being loaded
- the OS printing UI is reshown after a configuration change = fixes an infinite loading state after a configuration change

To test:
Refer to [the original PR](https://github.com/woocommerce/woocommerce-android/pull/4359) for test instructions and video previews. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt [hunk 1]
```diff
@@ -142,19 +132,17 @@ class CardReaderPaymentViewModel
     }
 
     @Suppress("LongParameterList")
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: Not needed anymore! =)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt [hunk 2]
```diff
@@ -313,6 +302,31 @@ class CardReaderPaymentViewModel
...
+
+    private fun Order.getPaymentDescription(): String =
+        resourceProvider.getString(
+            R.string.card_reader_payment_description,
+            this.number,
+            selectedSite.get().name.orEmpty()
+        )
+
+    // TODO cardreader don't hardcode currency symbol ($)
+    private fun getAmountLabel(order: Order) = "$${order.total}"
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: Wouldn't it make sense for consistency and general kotlin approach to have this as extension?

**Review by kidinov — CHANGES_REQUESTED** [review]
Looks great! Just left a couple of minor comments

**Comment by malinajirka** [comment]
Thanks for the review, good suggestions! It's ready for another round.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt (hunk 1 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: Fixed in https://github.com/woocommerce/woocommerce-android/pull/4388/commits/1a91d05e6b6367d3809a3c76cf88fb6a1a8c8d78

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt (hunk 2 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentViewModel.kt]: Fixed in https://github.com/woocommerce/woocommerce-android/pull/4388/commits/251963fccf40b78c03cca7528ccc0b4c7eb7d293

**Review by kidinov — APPROVED** [review]
👍
