### PR TITLE
check if listener is null before handling discovery error

### LINKED ISSUE #1663: EventBusException: Invoking subscriber failed
Sentry Issue: [WOOCOMMERCE-ANDROID-8P](https://sentry.io/organizations/a8c/issues/1379305666/?referrer=github_integration)

```
NullPointerException: Attempt to invoke interface method 'java.lang.String org.wordpress.android.login.LoginBaseDiscoveryFragment$LoginBaseDiscoveryListener.getRequestedSiteAddress()' on a null object reference
    at org.wordpress.android.login.LoginBaseDiscoveryFragment.onDiscoverySucceeded(LoginBaseDiscoveryFragment.java:43)
    at java.lang.reflect.Method.invoke(Method.java)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
...
(6 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:106)
...
(5 additional frame(s) were not displayed)

Invoking subscriber failed
```

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #1663. 

I have not been able to reproduce this crash but I believe it can happen when `mLoginBaseDiscoveryListener` [here](https://github.com/woocommerce/woocommerce-android/blob/d8f27b82031a4036e524c1c5cb80f5b6baa241a9/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java#L47) is `null`. This happens when the fragment is detached from the activity. My assumption is that the response is received from the API right at the moment when the fragment is detached which is causing the `NullPointerException`.

This PR adds a fix to check if the `mLoginBaseDiscoveryListener` is null before handling the discovery changes.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java [hunk 1]
```diff
@@ -38,6 +38,10 @@ void initiateDiscovery() {
     @SuppressWarnings("unused")
     @Subscribe(threadMode = ThreadMode.MAIN)
     public void onDiscoverySucceeded(OnDiscoveryResponse event) {
+        if (mLoginBaseDiscoveryListener == null) {
```
Comment (nbradbury) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java]: This change fixes the crash, but what does the user see when the listener is null? It seems like it fails silently, so the user doesn't know what happened.

Comment (anitaa1990) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java]: Good point! I noticed this is what is happening in a lot of the login error scenarios. If the [`mRequestedSiteAddress` is `null`](https://github.com/woocommerce/woocommerce-android/blob/d8f27b82031a4036e524c1c5cb80f5b6baa241a9/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java#L48) or if the [fragment is not yet added to its activity](https://github.com/woocommerce/woocommerce-android/blob/d8f27b82031a4036e524c1c5cb80f5b6baa241a9/libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java#L52), it is assumed that the user bailed and they will need to initiate the request again. It doesn't seem ideal but since this behaviour is being used in a lot of places in Wp-android discovery process and only a couple of user faced this issue in over a month in Woo but (and none in WP), so I _thought_ the chances of this happening is very low and following the same behaviour for the crash.

Comment (nbradbury) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java]: > so I _thought_ the chances of this happening is very low and following the same behaviour for the crash

Fair enough! I think we're good to :shipit:

**Review by nbradbury — APPROVED** [review]
