### PR TITLE
Remove QR code scanning CTA from login flow

### LINKED ISSUE #12301: Disable QR code scanner CTA from login flow.
Full context and discussion here: p1723448778949849-slack-C01SFMVEYAK

The QR code API that was hosted by Google, that we were using for the QR code login is now defunct. This is causing a broken image link in WooCommerce mobile logins. The stopgap right now is to remove the QR code image from the login email, but in the long run we should complete this task: https://github.com/woocommerce/team-ghidorah/issues/325

Screenshot 2024-08-12 at 09 44 54

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #12301 

### Description
Currently, the QR code generation is broken. The backend fix is not going to happen in the short term, so for now:
- we'll update the Woo login email template to remove the QR code entirely
- disable any mentions to QR code login from the Woo app.

Screenshot 2024-08-12 at 09 44 54

### Testing information
1.  Start login flow
2. Enter a WP.con / Jetpack connected site url
3. Enter WP.com email
4. Click on `Log in with magic link`
5. Check the button `Scan QR code to login` button is gone

| Before  | After |
| ------------- | ------------- |
|   |   | Cell  | Cell  |  

## Images/gif

- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
Small UI change and mostly removing code. Considered unit tests where unnecessary for this. 
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by irfano** [comment]
@JorgeMucientes, I think we can target beta 19.9 for this fix. WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt [hunk 1]
```diff
@@ -948,17 +942,6 @@ class LoginActivity :
         }
     }
 
-    override fun onScanQrCodeClicked(source: String) {
-        AnalyticsTracker.track(
-            stat = AnalyticsEvent.LOGIN_WITH_QR_CODE_BUTTON_TAPPED,
-            properties = mapOf(
-                KEY_FLOW to VALUE_LOGIN_WITH_WORDPRESS_COM,
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt:955]: We can also remove `AnalyticsTracker.VALUE_LOGIN_WITH_WORDPRESS_COM` since it's unused now.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt [hunk 2]
```diff
@@ -1005,25 +988,6 @@ class LoginActivity :
         }
     }
 
-    private fun openQrCodeScannerFragment() {
-        GmsBarcodeScanning.getClient(this).startScan()
-            .addOnSuccessListener { rawValue ->
-                if (ValidateScannedValue.validate(rawValue.rawValue)) {
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt:1011]: We can remove the `ValidateScannedValue` class, as it is no longer in use.

**Review by irfano — CHANGES_REQUESTED** [review]
The QR button is no longer visible. 🟢
I added two more comments for possible additional removals.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginActivity.kt:1011]: Good catch, removed!

**Comment by JorgeMucientes** [comment]
Thanks for the review and feedback @irfano. Applied your suggestions

> @JorgeMucientes, I think we can target beta 19.9 for this fix. WDYT?

About that. I'm not sure tbh. I think the most critical part to fix is the broken [QR in the login email itself](https://github.com/woocommerce/team-ghidorah/issues/343). Removing this CTA from the app feels less importan to me. The fact that the button is visible now is not blocking the user on any relevant action or flow from the app, since there's no QR code to be scanned. 
Imho it feels fine to merge this a regular task rather than a beta fix in `19.9`. 

Wdyt?

**Review by irfano — APPROVED** [review]
Okay, I agree with your comment. We can target `trunk`.
LGTM! 👍🏻 I'm merging now.
