### PR TITLE
[Woo POS] [Bug] No pictures shown in card reader tutorial

### LINKED ISSUE #11896: [Woo POS] No pictures are shown on the IPP explaining dialog with 3 pages

### PR DESCRIPTION
**Pull request by samiuelson**
Closes: #11896

### Description

This PR fixes the logic responsible for hiding and showing images in the card reader tutorial dialog, in various screen configurations (orientations with screen size classes).

This is how the bug looks on tablet:
<video src=https://github.com/user-attachments/assets/cf7fb878-667c-4e98-a442-053b02204ca9 width=400/>

Note: on a phone the behavior is correct—pictures are shown in portrait and hidden in landscape.

### Steps to reproduce

To trigger the tutorial, reinstall the app (or wipe app's data). Then attempt to collect a payment with external card reader.

### Testing information

1. Verify that the card reader tutorial shows pictures in the following configurations:
* Phone device, in portrait
* Tablet device, all orientations
2. Verify images are hidden on phone in landscape

- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt [hunk 1]
```diff
@@ -8,24 +8,25 @@ import androidx.fragment.app.Fragment
...
             binding.labelTextView.setText(args.getInt(ARG_LABEL_ID))
             binding.detailTextView.setText(args.getInt(ARG_DETAIL_ID))
 
-            // hide images in landscape
-            if (DisplayUtils.isLandscape(context)) {
-                binding.imageView.hide()
-            } else {
-                binding.imageView.setImageResource(args.getInt(ARG_DRAWABLE_ID))
-            }
+            UiHelpers.setImageOrHideInLandscapeOnCompactScreenHeightSizeClass(
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt:24]: I am wondering if we should also change the logic in this function to take into account the height of the screen, not its width. If we do, we just need to make sure that the other usages of this function will keep the same from logic point of view behavior

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt:24]:
```kotlin
fun setImageOrHideInLandscapeOnCompactScreenHeightSizeClass(
        imageView: ImageView,
        @DrawableRes resId: Int?,
        setInvisible: Boolean = false
    ) {
        val isLandscape = DisplayUtils.isLandscape(imageView.context)
        val isNotCompact = imageView.context.windowHeightSizeClass >= WindowSizeClass.Medium
        val shouldShowBasedOnOrientationAndSize = !isLandscape || isNotCompact
        val showImage = resId != null && shouldShowBasedOnOrientationAndSize
        updateVisibility(imageView, showImage, setInvisible)
        resId?.let {
            imageView.setImageResource(resId)
        }
    }
```
I'm not sure I understand the suggestion 🤔 

The image is shown:
* In landscape – only if `windowHeight >= Medium`
* In portrait – always

What additional scenarios do you think we should handle?

Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt:24]: @kidinov I recently updated this method to take into account screen-height instead of screen-width - [more on this PR](https://github.com/woocommerce/woocommerce-android/pull/12179/files). Do you think we need to do something more or did you perhaps just missed this update?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/tutorial/CardReaderTutorialViewPagerItemFragment.kt:24]: @samiuelson @malinajirka oh, I thought that the bug was there because the method worked only for the landscape, but the method was fixed already and the issue was that the method was not used 😀

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/230">20.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by kidinov — APPROVED** [review]
LGTM!
