### PR TITLE
Fix/9654 local notification fix

### LINKED ISSUE #9654: Store Creation: Local notification fixes
This issue aims to fix 2 things: 
- Avoid canceling scheduled local notifications when the user switches site
- Switch to the correct store upon tapping on a local notification the belongs to another site

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #9654

### Description

Fixes several issues related to local notifications: 
- Avoid canceling scheduled local notifications when the user switches to a different store.
- Switch to the correct store upon tapping on a local notification the belongs to another site.
- ~~Notifications missing the `siteId` were being scheduled but never displayed due to the logic in `PreconditionCheckWorker`:~~ 
```kotlin
    private fun proceedIfFreeTrialAndMatchesSite(siteId: Long?): Result {
        val site = selectedSite.get()
        return if (site.isFreeTrial && site.siteId == siteId) {
            Result.success()
        } else {
            cancelWork("Store plan upgraded or a different site. Cancelling work.")
        }
    }
```
~~This PR fixes that and ensures all the scheduled local notifications have the correct `siteId` so we can support site switching.~~
EDIT: As discussed below https://github.com/woocommerce/woocommerce-android/pull/9736#issuecomment-1709798125 not all local notifications are impacted by the previous code. And the ones that were impacted by the previous code had the proper `siteId` set. 

### Testing instructions

The changes in this PR mainly affect `StoreCreationCompletedNotification` so focusing our test around that notification should be enough.  
1. First apply the following change to make the notification trigger sooner after being scheduled: 
``` diff
Subject: [PATCH] Wait only 2 min for notification
---
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt	(revision a451a5453f1e7d721de5c9953805585f548cde03)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt	(date 1694072038449)
@@ -30,7 +30,7 @@
         title = R.string.local_notification_store_creation_complete_title,
         description = R.string.local_notification_store_creation_complete_description,
         type = LocalNotificationType.STORE_CREATION_FINISHED,
-        delay = 5,
+        delay = 2,
         delayUnit = TimeUnit.MINUTES
     ) {
 
```
2. Trigger store creation flow and press "Try for free". Wait for the loading to complete until you are taken to the first profiler step. You should see the following log before moving to the next step: 
```
Tracked: local_notification_scheduled, Properties: {"type":"store_creation_complete","blog_id":223209821,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"url"}
```
3. Kill the app
4. Wait for the notification to show up. We reduced the waiting time to 2 mins, it should be enough for the store to be ready.
5. Tap on the notification and notice how the stores is switched to the new one created one. 
6. Review the following event is only tracked once: 
```
Tracked: local_notification_tapped, Properties: {"type":"store_creation_complete","blog_id":223232803,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"url"}
```

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt [hunk 1]
```diff
@@ -103,21 +93,23 @@ class StoreNamePickerViewModel @Inject constructor(
...
-
-                localNotificationScheduler.scheduleNotification(
-                    StoreCreationIncompleteNotification(
-                        name,
-                        _viewState.value.storeName
-                    )
-                )
-            }
-        }
+        // TODO To be removed. With the new store creation flow this notification is no longer needed
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt:103]: Same as shared in prior comment. To be removed in subsequent changes. This notification doesn't make sense anymore with the current store creation flow, where a new site is created in a single step process.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt [hunk 2]
```diff
@@ -21,21 +22,29 @@ sealed class LocalNotification(
...
         delayUnit = TimeUnit.MINUTES
     ) {
+
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description, name)
         }
     }
 
-    data class StoreCreationIncompleteNotification(val name: String, val storeName: String) : LocalNotification(
+    data class StoreCreationIncompleteNotification(
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt:42]: Notification unused to be completely removed. Created an issue https://github.com/woocommerce/woocommerce-android/issues/9739 here to clean up this code.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt [hunk 3]
```diff
@@ -29,17 +32,25 @@ class LocalNotificationWorker @AssistedInject constructor(
...
+        val notificationId = inputData.getInt(LOCAL_NOTIFICATION_ID, -1)
         val title = inputData.getString(LOCAL_NOTIFICATION_TITLE)
         val description = inputData.getString(LOCAL_NOTIFICATION_DESC)
         val data = inputData.getString(LOCAL_NOTIFICATION_DATA)
+        val siteId = inputData.getLong(LOCAL_NOTIFICATION_SITE_ID, 0L)
+
+        // This means the new store is ready a we need to refresh the database with it
+        if (type == STORE_CREATION_FINISHED.value) {
+            sitePickerRepository.fetchWooCommerceSites()
+        }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotificationWorker.kt:50]: Refreshing the store list db once the new store is ready. This will enable to store switching upun tapping on the notification to work properly.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt [hunk 4]
```diff
@@ -177,11 +178,10 @@ class MainActivityViewModel @Inject constructor(
         }.exhaustive
     }
 
-    private fun changeSiteAndRestart(remoteSiteId: Long, restartEvent: Event) {
+    private fun changeSiteAndRestart(remoteSiteId: Long, restartEvent: RestartActivityEvent) {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivityViewModel.kt:181]: Small refactor to make the contract of this function and RestartActivity events more explicit.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt [hunk 5]
```diff
@@ -6,6 +6,7 @@ import com.woocommerce.android.viewmodel.ResourceProvider
 import java.util.concurrent.TimeUnit
 
 sealed class LocalNotification(
+    val localNotificationSiteId: Long,
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt]: np, why not use `siteId` same as the subclasses, then use `override val` in the constructors? IMO this will be clearer, and less verbose in the subclasses.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt [hunk 6]
```diff
@@ -44,18 +44,20 @@ class PreconditionCheckWorker @AssistedInject constructor(
...
 
             null -> cancelWork("Notification type is null. Cancelling work.")
         }
     }
 
-    private fun proceedIfFreeTrialAndMatchesSite(siteId: Long?): Result {
-        val site = selectedSite.get()
-        return if (site.isFreeTrial && site.siteId == siteId) {
+    private fun proceedIfFreeTrialAndMatchesSite(siteId: Long): Result {
+        if (siteId == 0L) return cancelWork("Site id is missing. Cancelling work.")
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt]: Not blocking: WDYT about reporting a Sentry error in this case? If I'm understanding the logic correctly, this should never happen, so reporting an error would let us if there is something not working right.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt:103]: Why not remove it now in the same PR though? 😄

**Review by hichamboushaba — APPROVED** [review]
Great work @JorgeMucientes 🥇, I left some minor comments, but none is blocking.

And I have a small remark regarding this point:
> - Notifications missing the siteId were being scheduled but never displayed due to the logic in PreconditionCheckWorker

It seems this never happened before, as all of the notifications that [went](https://github.com/woocommerce/woocommerce-android/blob/509cb5204ff07f58824cd975adda911676b78db4/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt#L43-L47) through the `proceedIfFreeTrialAndMatchesSite` function were already being passed a `siteId` in their constructor, or am I missing something?
I'm just trying to see if we can use this to explain the missing notifications, or if it's still just the first cause in the ticket (which could happen either after a manual site switching, or if the user dismissed the setup), or something else not identified yet.

And just to clarify, I'm not saying making the `siteId` mandatory is the wrong call, on the contrary, and I'm glad this would allow fixing the issue discussed here p1692878943214069-slack-C03L1NF1EA3 (I was pretty sure I created a ticket for this, but I can't find it 😕)

**Comment by JorgeMucientes** [comment]
Thanks for the review @hichamboushaba. I'll proceed to adress some of the suggestions you've shared :) 

> It seems this never happened before, as all of the notifications that [went](https://github.com/woocommerce/woocommerce-android/blob/509cb5204ff07f58824cd975adda911676b78db4/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt#L43-L47) through the proceedIfFreeTrialAndMatchesSite function were already being passed a siteId in their constructor, or am I missing something?

Not really. When building `StoreCreationCompletedNotification` (previously named `StoreCreationFinishedNotification`) and `StoreCreationIncompleteNotification` no `siteId` was set for existing `open val data: String?` field. So when reaching the `PreconditionCheckWorker` the id was null and the notification cancelled. You can easily test the scenario from the description of this PR in `trunk` and verify you'll never get notified after killing the app. 

> (I was pretty sure I created a ticket for this, but I can't find it 😕)

You did 😄 . It's the one linked to this PR: https://github.com/woocommerce/woocommerce-android/issues/9654 Only that I modified the title and description a bit.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt (hunk 1 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/name/StoreNamePickerViewModel.kt:103]: This will require removing code in several places. I didn't want to add extra noise to the PR.

**Comment by hichamboushaba** [comment]
> Not really. When building StoreCreationCompletedNotification (previously named StoreCreationFinishedNotification) and StoreCreationIncompleteNotification no siteId was set for existing open val data: String? field. So when reaching the PreconditionCheckWorker the id was null and the notification cancelled. You can easily test the scenario from the description of this PR in trunk and verify you'll never get notified after killing the app.

Actually, it doesn't go through the check at all, check the [code](https://github.com/woocommerce/woocommerce-android/blob/509cb5204ff07f58824cd975adda911676b78db4/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt#L40-L41), it directly return `Result.success` for both of these types.
And I already tested it before, when I started the discussion p1692878943214069-slack-C03L1NF1EA3 🙂, and as I remember I got the notification even though the site was different.

> You did 😄 . It's the one linked to this PR: https://github.com/woocommerce/woocommerce-android/issues/9654 Only that I modified the title and description a bit.

I see, this confused me completely. I still think these were two different issues, one is critical where we don't show the notifications at all, and this was just about not switching to the correct store when it's clicked.

**Comment by JorgeMucientes** [comment]
> Actually, it doesn't go through the check at all, check the [code](https://github.com/woocommerce/woocommerce-android/blob/509cb5204ff07f58824cd975adda911676b78db4/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt#L40-L41), it directly return Result.success for both of these types.

Ouch! That's true. I completely missed that. What I don't understand is why this notification (`StoreCreationCompletedNotification`) didn't work for me in `trunk` when I tested it in my Pixel 2. Very strange. ~~And surprisingly, now it does work.~~ It doesn't always work. If in `trunk` I follow the steps from this PR description, there are times I will never get the notification in my Pixel 2 where Work Manager should work always. However, I don't see any logs of the work being canceled or anything. So it's very rare.

> I see, this confused me completely. I still think these were two different issues, one is critical where we don't show the notifications at all, and this was just about not switching to the correct store when it's clicked. 

Yeah I agree and the original intent of this branch was actually to fix the issues from the ticket. And additionally, I thought I had fixed the critical issue. Which clearly seems I didn't 😅.

**Comment by hichamboushaba** [comment]
> And additionally, I thought I had fixed the critical issue. Which clearly seems I didn't 😅.

You still fixed it 🙌, for all of the notifications that had a `siteId` passed, we were ignoring them, and now we won't thanks to the changes of this PR 🎉, that's also what we discussed yesterday for you to fix.
What we don't know, is if this was the only cause or not, I hope it was, we'll see how the metrics change after publishing the update.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt (hunk 6 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt]: Done https://github.com/woocommerce/woocommerce-android/pull/9736/commits/8663459f3eebab892b572581e42bf86d5280b701. Sending a report rather than using `crashLogging.recordException(e, category)`. As we actually want to log an error in Sentry, rather than capture additional context for potential crashes happening related to this.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt (hunk 5 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt]: Done https://github.com/woocommerce/woocommerce-android/pull/9736/commits/96f4a865c6351c1be79f53961210e5c77eaf2f99 👍🏼

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt (hunk 6 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt]: Good point, I didn't check how `recordException` works in our API 🤦
