### PR TITLE
[FIX] Login with given site uses that site for wp.com flow

### LINKED ISSUE #10010: Login with given site uses that site for wp.com flow
To reproduce the bug

* Open a clean app
* Log in -> Enter a non WP.com site
* Go back to the main screen
* Create a new store -> login
* Enter wp.com email
* Notice that "it looks like is connected to a different wp.com account" error

### PR DESCRIPTION
**Pull request by kidinov**
Possible fixes: #10010

### Description

The issue is described here peaMlT-74-p2

I am not sure that this fixes the crash, but it may be. This, for sure, fixes another bug, though. The issue comes from the fact that the site URL stored in the app prefs is not deleted in some cases, and that's why the entered URL used later on is the "current site" URL, which leads to the different broken states.

To reproduce the bug 
* Open a clean app
* Log in -> Enter a non WP.com site
* Go back to the main screen
* Create a new store -> login
* Enter wp.com email
* Notice that "it looks like <site> is connected to a different wp.com account" error

My not proven theory is that in some cases, if the site entered on step 2 matches the wpcom account, but somehow [not wpcom](https://github.com/woocommerce/woocommerce-android/blob/9de926c0e9f38239937fdb32f50ad35b2c522bad/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/sitediscovery/SitePickerSiteDiscoveryViewModel.kt#L175) then JP activation flow started and crash happens, because URL from another site is used that we don't have credentials

@hichamboushaba @JorgeMucientes does this make any sense? Would you be able to think about more cases when we can end up in a bad state knowing about this potential issue? I see that the crash also happens when a user is already logged in, so I think we can keep the wrong site address even after successful login happened and then things go wrong when a user tries to change a site via site picler

### Testing instructions

Follow reproduction steps and notice that login works fine now

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt [hunk 1]
```diff
@@ -80,6 +80,7 @@ open class LoginPrologueFragment(@LayoutRes layout: Int) : Fragment(layout) {
     override fun onResume() {
         super.onResume()
         AnalyticsTracker.trackViewShown(this)
+        appPrefsWrapper.removeLoginSiteAddress()
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt]: Instead of putting it on `onResume` which IMO is not very clear to understand, I suggest making it as a reaction to the "Get Started" button, so it should go before this line instead https://github.com/woocommerce/woocommerce-android/blob/02b1b6ef5519a757f17e2d82ec551693b425c283/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt#L63

**Review by hichamboushaba — APPROVED** [review]
Thanks @kidinov, for the ping, while I don't think the change would have any impact on the crash itself (more on this below), this definitely fixes a bug, just please review my suggestion below before merging it.

> My not proven theory is that in some cases, if the site entered on step 2 matches the wpcom account, but somehow not wpcom then JP activation flow started and crash happens, because URL from another site is used that we don't have credentials

I don't think this would happen, if the site entered on step 2 is part of the user's sites, then the login will succeed, as it will be included in the `/me/sites` response.
If it doesn't, then this [path](https://github.com/woocommerce/woocommerce-android/blob/e1c1a9928ebe8fa146afd65f3f769bf6a352da7d/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerViewModel.kt#L317) will be used, and it's what triggers the Jetpack Installation/Connection flow.

As for the crash itself, I checked some recent logs from the Sentry event, and firstly I don't see any mentions of the site creation flow, so it's an additional reason why I don't think this fix is related to the crash. Secondly, it seems the issue I tried to fix with this [commit](https://github.com/woocommerce/woocommerce-android/commit/d3e0d8fe71b21f576e3d7c902c8bb46e66f2a61b) is still responsible for some crashes: the user enters the address of a site that's already connected to their account (so a site that was already shown in the site picker), but the `if` condition in that commit is not matched for some reason, I'll try to think more about this, and if I can think of the potential cause, I'll share it with you.

**Comment by hichamboushaba** [comment]
@kidinov please before merging this, update the PR to avoid closing the crash ticket 🙂.

**Comment by JorgeMucientes** [comment]
Thanks for tackling this @kidinov! 

This bug is pretty similar to this other issue we were discussing here: https://github.com/woocommerce/woocommerce-android/pull/9979.  And I think there might be other corner case flows where we attempt to use the persisted site url and maybe we should't. Like for example: 

- Open a clean app
- Log in -> Enter a non WP.com site
- Go back to the main screen
- Create a new store -> Sign up successfully
- Store creation flow triggered. 
- Kill the app
- Reopen it
- Notice how the account mismatch error screen is displayed, for the new WP.com account. 

Luckily, that flow should also be fixed once this PR is merged 👍🏼 

I do agree with Hicham though, that these cases are unrelated to these crashes: peaMlT-74-p2

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginPrologueFragment.kt]: Moved here https://github.com/woocommerce/woocommerce-android/pull/9995/commits/7bd80f86827fd0b445f7566cbcfbeb27a2627367
