### PR TITLE
fix: make StatsTimeRangeSelection parcelable

### LINKED ISSUE #8245: BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.woocommerce.android.ui...
Sentry Issue: [WOOCOMMERCE-ANDROID-5RZ](https://sentry.io/organizations/a8c/issues/3892343740/?referrer=github_integration)

```
NotSerializableException: com.woocommerce.android.ui.analytics.ranges.AnalyticsHubTimeRange
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
...
(76 additional frame(s) were not displayed)

BadParcelableException: Parcelable encountered IOException writing serializable object (name = com.woocommerce.android.ui.analytics.ranges.StatsTimeRangeSelection)
    at android.os.Parcel.writeSerializable(Parcel.java:2751)
    at android.os.Parcel.writeValue(Parcel.java:2517)
    at android.os.Parcel.writeValue(Parcel.java:2316)
    at android.os.Parcel.writeList(Parcel.java:1382)
    at android.os.Parcel.writeValue(Parcel.java:2460)
...
(70 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #8245 

### Description

This PR fixes the issue of the app crashing when saving the state of the Analytics Hub screen (when e.g. app goes to background). The problem was with `AnalyticsHubTimeRange` class - it was part of class `StatsTimeRangeSelection` which was `Serializable`. `Serializable` requires its members to be `Serializable` too (if they're objects) but `AnalyticsHubTimeRange` was not `Serializable` - it was `Parcelable`.

I've decided to make `StatsTimeRangeSelection` a `Parcelable` to fix this issue and improve performance (although it probably won't be visible to users).

#### First, reproduce the issue
1. Checkout `release/12.0`
2. Connect the phone to Flipper (Android won't always display a dialog about the crash)
3. Open Analytics Hub
4. Go to the phone's main screen
5. **Assert there was a crash** (Flipper should report it)

#### Check the fix
1. Checkout `issue/8245_fix_analytics_background_crash`
2. Connect the phone to Flipper (Android won't always display a dialog about the crash)
3. Open Analytics Hub
4. Go to the phone's main screen
5. **Assert there was not crash**

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/ranges/StatsTimeRangeSelection.kt [hunk 1]
```diff
@@ -45,65 +44,68 @@ data class AnalyticsHubTimeRange(
...
-    ) {
-        val rangeData = generateTimeRangeData(selectionType, referenceDate, locale, calendar)
-        this.selectionType = selectionType
-        currentRange = rangeData.currentRange
-        previousRange = rangeData.previousRange
-        currentRangeDescription = rangeData.formattedCurrentRange
-        previousRangeDescription = rangeData.formattedPreviousRange
-    }
+    companion object Factory {
+        fun build(
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/ranges/StatsTimeRangeSelection.kt:57]: I've refactored to a single `constructor` to be able to use `@Parcelize`. Hence this `Factory` which contains the logic of the previous two private constructors.

**Review by atorresveiga — APPROVED** [review]
Thanks for working on this @wzieba!
I was able to reproduce the crash on release `12.0` and can confirm that the fix is good.
Screenshot 2023-01-24 at 13 36 17

LGTM! :shipit:

**Comment by atorresveiga** [comment]
@spencertransier this fix is working great 👍

**Comment by spencertransier** [comment]
@wzieba Is this good to merge and make a new build?

**Comment by wzieba** [comment]
Sorry @spencertransier for late reaction. Yes, I'm merging this PR right away. cc: @spencertransier
