### PR TITLE
[Tablet] Fix Order Details Infinite Shimmer Issue

### LINKED ISSUE #10881: [Tablet Support M2] Order list's details pane displays shimmer effect in case there are no orders (e.g. newly created store)

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #10881

### Description

Shows an empty view for Order Details when no Orders exists. 

### Testing instructions
1. Use a store with no orders. 
2. Go to the orders tab. 
3. Observe the Empty View to the right. 

**N.B** The Order List currently shows the filters and the notice card. That is outside the scope of this issue but could be addressed here. Nonetheless in the interest of time and not having this shimmer effect this improvement could be shipped and the optimizations ticketed for further fixing. 

**Color**: I took the best approach I could think of standardizing the color across the products and orders. A better approach may exist but I couldn't find any in the moment. 

### Images/gif

<kbd></kbd>

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/197">17.7</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt [hunk 1]
```diff
@@ -67,23 +73,32 @@ class WCEmptyView @JvmOverloads constructor(ctx: Context, attrs: AttributeSet? =
      * Hide the image in landscape since there isn't enough room for it on most devices
      */
     private fun checkOrientation() {
-        binding.emptyViewImage.isVisible = !DisplayUtils.isLandscape(context)
+        binding.emptyViewImage.isVisible = forceShowImage || !DisplayUtils.isLandscape(context)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: np: I guess the idea was not to show a picture in the landscape as it doesn't fit the screen. That'll work fine in this case as "empty" details can be opened only on tablets, as this changes API for reusable elements, I'd at least call it `showImageInBothOrientations` or something like that, just to make it clear what it does

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt [hunk 2]
```diff
@@ -806,6 +808,20 @@ class OrderDetailFragment :
         }
     }
 
+    private fun showEmptyView(show: Boolean) {
+        if (show) {
+            binding.orderDetailContainer.visibility = View.GONE
+            binding.emptyView.show(
+                WCEmptyView.EmptyViewType.ORDER_DETAILS,
+                forceShowImage = true,
+                backgroundColorResId = R.color.default_window_background
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt]: Do you think this is needed? Maybe just to keep the default "empty" view color used there?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt [hunk 3]
```diff
@@ -197,9 +197,7 @@ class OrderDetailViewModel @Inject constructor(
                 } ?: fetchOrder(showSkeleton = true)
             }
         } else {
-            viewState = viewState.copy(
-                isOrderDetailSkeletonShown = true
-            )
+            viewState = viewState.copy(isOrderDetailEmpty = true)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: np: it would probably be better to show the loading state while it's still loading and the "empty" state only when nothing is selected in the left pane.

With this approach of passing -1 (why not -2 or -10? =) as an indicator, it's not really easy to do and, quite frankly, not really good practice. Just something to consider as following improvement

https://github.com/woocommerce/woocommerce-android/assets/4923871/9a8ba79f-9f06-468f-bc11-d5ff45725575

**Review by kidinov — APPROVED** [review]
I left a couple non blocking comments. LGTM!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt (hunk 2 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt]: I dont think it is needed However the order list and order details ended up having the same color as they both use the same empty view component. for the product details, I realized you utilized a different approach to showing the empty state that didn't involve the `EmptyView`

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt (hunk 3 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailViewModel.kt]: Good catch. Mine loaded so fast during testing that I didn't notice that hiccup. I am going to see if I can come up with a fix for this.

**Comment by jd-alexander** [comment]
@kidinov I made some more changes here. I wanted to land this in 17.7 but I don't want to put it in the cut now since the changes I have made are quite extensive. If necessary for this to land I will cut a beta with it (along side other fixes). But yes, due to the fact that the code changes are touching a part of the orders functionality that is very important, I rather properly review and testing to be sure existing functionality is not being broken. 

Also, I saw the `ProductsCommunicationViewModel` approach in the codebase hence the modeling but now when I think about I see that the approach taken with the `navigation` setup in the `TabletLayoutSetupHelper` may be able to work here and I had started that implementation in another [PR](https://github.com/woocommerce/woocommerce-android/pull/11011).

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt (hunk 2 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt]: Sorry for not following. You set a specific color here for the details part, which means that the color won't match between left and right panels when they are empty. Or your goal to make them be different? If it then in the night mode those colors are the same anyway

I'd keep it simple:
* Remove `backgroundColorResId` from the API
* Instead of passing `forceShowImage` flag, would just show image if screen height more than N dp. Current approach anyway doesn't make much sense as a device in landscape mode can be tall enough to accommodate picture and in portereit mode can be small enough to not accommodate it

So no changes to the API of the empty view at all

image

image

**Comment by kidinov** [comment]
@jd-alexander I like the approach you took. Just left a comment https://github.com/woocommerce/woocommerce-android/pull/11038#discussion_r1517512984 regarding changes to the empty view

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt (hunk 2 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/OrderDetailFragment.kt]: Agreed! I implemented the suggested changes.

**Comment by jd-alexander** [comment]
@kidinov this was the result of adding logic to show images for larger devices. 

Let me know if this is fine from a UI/UX standpoint. 

Screenshot_20240313_224355

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt [hunk 4]
```diff
@@ -67,9 +70,10 @@ class WCEmptyView @JvmOverloads constructor(ctx: Context, attrs: AttributeSet? =
      * Hide the image in landscape since there isn't enough room for it on most devices
      */
     private fun checkOrientation() {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: * We'd need to rename the method
* I think this won't work well, as these window classes are about width of a screen, so on landscape mode on a phone we still show the image. We need to rely on height of a screen to determine if we want to show that
image

**Review by kidinov — COMMENTED** [review]
@jd-alexander  I left a comment regarding the hiding of the image

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt (hunk 4 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]:
```
    private val minimumHeightDp = 600

  private fun isScreenHeightSufficient(): Boolean {
        val screenHeightDp = context.resources.displayMetrics.heightPixels / context.resources.displayMetrics.density
        return screenHeightDp >= minimumHeightDp
    }
    
    binding.emptyViewImage.isVisible = isScreenHeightSufficient()
```

Reliance on the height is causing a lot of errors, the initial solution I had presented with the additonal flag seemed to be better as we ended up not showing the image in landscape at all but only showing it in some cases, I am thinking I am thinking it is better to ust not show the image in landscape at all or we would need a flag to disable it for some views eg, this is on a Nexus 7 tablet. 
orders

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: > Reliance on the height is causing a lot of errors

Could you share what errors you think it causes? The picture itself has a specific height, and we want to show it only if there is enough space to do so. And more correct will be to use the space available for the view, not the screen size in general. The orientation does not really say anything about the height space we have, so reliance on this doesn't sound correct

The screenshot you posted doesn't really illustrate, in my opinion, the incorrectness of the approach, but more the way how the left pane layout is built, wdyt?

Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: Agreed. I reworked the solution to incorporate this feedback. Let me know if my new approach works.

**Comment by jd-alexander** [comment]
Thanks for the review @kidinov 

So I was exploring ways to solve the issue given your feedback and this is the idea I came up with. The change involves adding a global layout listener to WCEmptyView to dynamically adjust the visibility of emptyViewImage based on the height of its parent view. This ensures the image is only shown when there's sufficient space, as determined by comparing the parent view's height to a predefined minimum threshold. https://github.com/woocommerce/woocommerce-android/pull/11038/commits/42d8a5cc762219d8652d18e271e4428440549b86

I set it to `400dp` because I thought that allowed the image to be shown when there is sufficient space. Let me know what you think about this. 

I also called `isParentViewHeightSufficient` in two locations to support all scenarios that would trigger the state of the WCEmptyView. Any feedback on this is welcomed. 

Let me know if I interpreted your feedback correctly. 

### Screenshots from Various Screen Sizes: Phone, Small Tablet, Large Tablet

<kbd></kbd>

<kbd></kbd>

<kbd></kbd>

**Comment by jd-alexander** [comment]
I will need to do regression testing on all the screens that use this component if you are fine with this proposed solution. Let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt [hunk 5]
```diff
@@ -57,25 +60,37 @@ class WCEmptyView @JvmOverloads constructor(ctx: Context, attrs: AttributeSet? =
...
     }
 
+    @Suppress("LongMethod", "ComplexMethod")
     fun show(
         type: EmptyViewType,
         searchQueryOrFilter: String? = null,
         onButtonClick: (() -> Unit)? = null
     ) {
-        checkOrientation()
+        binding.emptyViewImage.isVisible = isParentViewHeightSufficient()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt:92]: ❤️

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt [hunk 6]
```diff
@@ -32,10 +34,10 @@ import com.woocommerce.android.widgets.WCEmptyView.EmptyViewType.SEARCH_RESULTS
 import com.woocommerce.android.widgets.WCEmptyView.EmptyViewType.SHIPPING_LABEL_CARRIER_RATES
 import com.woocommerce.android.widgets.WCEmptyView.EmptyViewType.SHIPPING_LABEL_SERVICE_PACKAGE_LIST
 import com.woocommerce.android.widgets.WCEmptyView.EmptyViewType.UNREAD_FILTERED_REVIEW_LIST
-import org.wordpress.android.util.DisplayUtils
 
 class WCEmptyView @JvmOverloads constructor(ctx: Context, attrs: AttributeSet? = null) : LinearLayout(ctx, attrs) {
     private val binding = WcEmptyViewBinding.inflate(LayoutInflater.from(context), this, true)
+    private val minimumHeightDp = MINIMUM_HEIGHT_DP
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: I'm just curious why we need another val here. Can't we use `MINIMUM_HEIGHT_DP` directly?

**Comment by kidinov** [comment]
@jd-alexander I like this approach! Thank you 🙏

File: WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt (hunk 6 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCEmptyView.kt]: Agreed. An oversight.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/203">18.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
I ignored the test issue causing the PR to fail but created an issue to fix it in short order as I know we dont want our test suite to have `ignore` lingering for long https://github.com/woocommerce/woocommerce-android/issues/11197

**Comment by kidinov** [comment]
@jd-alexander 

> I ignored the test issue causing the PR to fail but created an issue to fix it in short order as I know we dont want our test suite to have ignore lingering for long https://github.com/woocommerce/woocommerce-android/issues/11197

👍

That test is flaky, I believe
