### PR TITLE
[Dynamic Dashboards] Fix bugs reported in the beta testing

### LINKED ISSUE #11468: [Dynamic Dashboard] M1 bugs
- [x] App crashes upon tapping “View all tasks” button in the onboarding card when no tasks are loaded.
- [x] Inconsistent button titles between stats and top performers.
- [x] Wrong title for the top performers card..
- [x] Wrong title for the onboarding card.
- [x] Error view text is unreadable in dark mode.
- [x] Wrong title for the widget editor screen.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #11468 

### Description
This PR fixes the bugs reported during the beta testing, please check the linked issue for more details.

### Testing instructions
Check the list of bugs in the linked issue, and confirm all are fixed.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/WidgetError.kt [hunk 1]
```diff
@@ -52,7 +53,8 @@ fun WidgetError(
             text = errorMessage,
             style = TextStyle(
                 textAlign = TextAlign.Center,
-                fontSize = 18.sp
+                fontSize = 18.sp,
+                color = LocalContentColor.current
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/WidgetError.kt:57]: The `ClickableText` seems to not set the correct content color unlike `Text`, I didn't want to hardcore a color value here, I'm just passing the actual content color, just in the unlikely case that the background of the screen is changed.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingViewModel.kt [hunk 2]
```diff
@@ -146,8 +143,17 @@ class DashboardOnboardingViewModel @AssistedInject constructor(
...
+        private val onViewAllTapped: () -> Unit
+    ) {
+        val cardButton = if (!isLoading) {
+            DashboardWidgetAction(
+                titleResource = R.string.store_onboarding_task_view_all_tasks,
+                action = onViewAllTapped
+            )
+        } else {
+            null
+        }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/onboarding/DashboardOnboardingViewModel.kt:155]: I couldn't reproduce the crash, I think it was because of the division by zero that we fixed in #11463, but still, showing the onboarding with empty tasks doesn't feel right, I updated the logic to hide the button during loading.

**Review by 0nko — APPROVED** [review]
LGTM! :shipit:
