### PR TITLE
Supply the necessary mutability flags for PendingIntents

### LINKED ISSUE #5272: Add the appropriate flags FLAG_IMMUTABLE or FLAG_MUTABLE to our PendingIntents
When targetting Android 12, any usage of PendingIntent without the mutability flags will cause a crash.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #5272 

### Description
This simply adds the Immutable flag to our push notifications PendingIntents.

I took it also as a chance to add a utility class for handling the android versions checks, it's similar to [`BuildCompat`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/os/BuildCompat.java;l=33?q=BuildCompat&sq=) that the androidx libraries use.

### Testing instructions
1. Test push notifications and confirm that opening and dismissing a push notification works as expected.
2. Change targetSdkVersion to 31, then repeat the first test, and confirm that the app doesn't crash.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationsProcessingService.kt [hunk 1]
```diff
@@ -22,7 +23,12 @@ class NotificationsProcessingService : Service() {
             intent.putExtra(ARG_ACTION_TYPE, ARG_ACTION_NOTIFICATION_DISMISS)
             intent.putExtra(ARG_PUSH_ID, pushId)
             intent.addCategory(ARG_ACTION_NOTIFICATION_DISMISS)
-            return PendingIntent.getService(context, pushId, intent, PendingIntent.FLAG_CANCEL_CURRENT)
+            val flags = if (BuildCompat.isAtLeastS()) {
+                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
+            } else {
+                PendingIntent.FLAG_UPDATE_CURRENT
+            }
+            return PendingIntent.getService(context, pushId, intent, flags)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationsProcessingService.kt:31]: I used the flag `PendingIntent.FLAG_UPDATE_CURRENT` here instead of `PendingIntent.FLAG_CANCEL_CURRENT` since technically they will have the same result (the update flag will update the current one, the cancel flag will cancel the current one before creating a new one), but the former one is easier to understand as what it does.

**Review by anitaa1990 — APPROVED** [review]
Works great :shipit:
