### PR TITLE
Issue/735 nosuchelement notification ext

### LINKED ISSUE #735: NoSuchElementException in NotificationModelExtKt
```
Fatal Exception: java.util.NoSuchElementException: Key approve-comment is missing in the map.
       at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
       at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:263)
       at com.woocommerce.android.extensions.NotificationModelExtKt.isApproved(NotificationModelExt.kt:169)
       at com.woocommerce.android.extensions.NotificationModelExtKt.buildComment(NotificationModelExt.kt:145)
       at com.woocommerce.android.ui.notifications.ReviewDetailPresenter.getOrBuildCommentForNotification(ReviewDetailPresenter.kt:79)
```

[Fabric](https://fabric.io/automattic/android/apps/com.woocommerce.android/issues/5c4e50abf8b88c2963bf054d?time=last-ninety-days)

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #735 - fixes the `NoSuchElement` exception caused when reading the `ACTION_KEY_APPROVE` value when that key doesn't exist by first checking whether it exists. A similar change was made to the `ACTION_KEY_SPAM` reading, as that suffered the same problem.

screen shot 2019-02-01 at 7 51 30 am

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NotificationModelExt.kt [hunk 1]
```diff
@@ -165,14 +165,28 @@ fun NotificationModel.canModerate() = NotificationHelper
...
+    } ?: return false
+}
 
 /**
  * If true, user can mark this notification as spam.
  */
-fun NotificationModel.canMarkAsSpam() = NotificationHelper
-        .getCommentBlockFromBody(this)?.actions?.containsKey(ReviewActionKeys.ACTION_KEY_SPAM) ?: false
+fun NotificationModel.canMarkAsSpam(): Boolean {
+    NotificationHelper.getCommentBlockFromBody(this)?.actions?.let {
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NotificationModelExt.kt]: The original method was already checking for the existence of the key and if it exists it sends back `true` (regardless of the value of the key) -- this matches the functionality of WPAndroid. If the key is not present, then the user doesn't have permission to mark it as spam. This change should be reverted.

Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NotificationModelExt.kt]: 🤦‍♂️ Thanks for catching that, @AmandaRiu. I'll fix that right away.
