### PR TITLE
Fix feature feedback tag tracking

### LINKED ISSUE #6118: Feedback banner state is bound only to the requesting view
Description
==========
When adding a new type of Feedback Feature banner to a view that already contains a previous one, e.g. Order List view, the stored feedback state (Unanswered, Given, Dismissed) is bound only to the view, making every new Feedback feature affected by this state and not showing anything new ever again in case the merchant interacts with a banner for that view at any given time. 

Steps to reproduce
==========
1. Do a fresh install of the Woo app
2. Go to the Order list and hit `Dismiss` to the current feedback feature banner there
3. Go back to the code and add to the `FeedbackFeatureSettings` a new kind of Feature and change it inside the `ProductListFragment`
4. Verify that this new feature setting is still set as `Dismissed` because of the previous interaction with the banner, making the new Feature affected by the answer given to the old one.

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #6118 by refactoring how we store the state of Feedback using the feature as the state key, this way, we make the feedback state related to the feature itself, not the requesting view, and when a new Feature is added, a new state is stored.

⚠️ With this change, we will end up resetting the state of each Feedback banner interaction with all merchants, but since the banner is non-intrusive and this bug affects our capability of displaying the banner for new relevant features, I think it's worth it.

How to Test
==========
1. Do a fresh install of the Woo app
2. Go to the Order list and hit `Dismiss` to the current feedback feature banner there
3. Go back to the code and add to the `FeedbackFeatureSettings` a new kind of Feature and change it inside the `ProductListFragment`or any other view using Feedback banners.
4. Verify that this new feature state is still set as `Unanswered` and the banner is correctly displayed for that view.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt [hunk 1]
```diff
@@ -16,22 +16,25 @@ import com.woocommerce.android.analytics.AnalyticsTracker
...
 import com.woocommerce.android.ui.compose.theme.WooThemeWithBackground
 import com.woocommerce.android.ui.feedback.SurveyType
-import com.woocommerce.android.ui.orders.list.OrderListFragment
 import dagger.hilt.android.AndroidEntryPoint
 
 @AndroidEntryPoint
 class CouponListFragment : BaseFragment(R.layout.fragment_coupon_list) {
     companion object {
         const val TAG: String = "CouponListFragment"
+        val feedbackFeatureKey = FeatureFeedbackKey(TAG, SIMPLE_PAYMENTS)
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt]: NP: Should this be all caps?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt [hunk 2]
```diff
@@ -4,27 +4,30 @@ import com.woocommerce.android.FeedbackPrefs
...
+        PRODUCT_VARIATIONS,
+        PRODUCT_ADDONS,
+        SIMPLE_PAYMENTS,
+        COUPONS
     }
 
-    fun registerItselfWith(featureKey: String) {
-        FeedbackPrefs.setFeatureFeedbackSettings(featureKey, this)
+    data class FeatureFeedbackKey(
+        private val requestingView: String,
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt]: @ThomazFB I'm wondering if we really need `requestingView` here. Wouldn't `feature` alone be enough? I realize we show the `SIMPLE_PAYMENTS` banner in both the order list and coupon list, but if the user already dismissed it in one place, do we really want to show it again elsewhere?

**Comment by nbradbury** [comment]
@ThomazFB Code looks and works fine! Just left a couple of minor comments for you.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt (hunk 2 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/model/FeatureFeedbackSettings.kt]: I think that's a great way of thinking about this behavior, @nbradbury! I've updated the code to reflect your suggestion and it's ready for another round of testing, thank you a lot for this awesome idea!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/coupons/CouponListFragment.kt]: After introducing the changes you suggested removing the `requestingView`, those constants inside the companion object no longer exist, so there's no need to change anything here anymore.

**Review by nbradbury — APPROVED** [review]
Looks great, and changes are good! I'll approve this and enable auto-merge :shipit:
