### PR TITLE
[Mobile Payments] Handle incorrect pin error for UK and Canadian stores during IPP

### LINKED ISSUE #12350: IPP in UK and Canada Displays Unknown Error on Incorrect PIN entry
**Describe the bug**
When the user enters a wrong pin number or if we use `x.55` test amount in test mode, the app displays `The payment was declined for an unknown reason`.

**To Reproduce**
1. Go Order List
2. Start the order creation flow
3. Enter custom amount ending with x.55 (eg. 1.55)
4. Collect payment using a card reader
5. Notice the payment fails with an unknown error

**Screenshots**

Screenshot_20240816-091752

**Expected behavior**
The app should inform the user that an incorrect PIN was entered - ~something like `Incorrect PIN entered. Please try again`~ we can use the String from ios `An incorrect PIN has been entered. Try again, or use another means of payment`

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12350 

### Description

This PR addresses the handling of the "incorrect_pin" error from the Stripe Terminal SDK specifically for UK and Canadian stores. 
The changes have been made to following files:

`PaymentErrorMapper`
`CardReaderPaymentErrorMapper`
`CardPaymentStatus`
`CardReaderPaymentViewState`

Following message is displayed for incorrect pin: `An incorrect PIN has been entered. Try again, or use another means of payment`

### Steps to reproduce

1. Go Order List
2. Start the order creation flow
3. Enter custom amount ending with x.55 (eg. 1.55)
4. Collect payment using a card reader
5. Notice the payment fails with an unknown error

### Testing information

I've tested this in the main app and the POS app for Canadian store. NOTE: I tested this in a simulator as my WisePad 3 card reader seems to be broken.

Test for UK and Canadian stores to ensure "incorrect_pin" is handled correctly with appropriate message.

### Images/gif

**Before:**

[incorrect pin not handled](https://github.com/user-attachments/assets/1a6dfc83-ef7a-42dd-ba06-6cd38c7807f7)

**After:**

[incorrect pin handled](https://github.com/user-attachments/assets/905f5913-1989-4f75-bef8-ca6d861f4865)

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by malinajirka** [comment]
Thanks for working on this @AnirudhBhat! Unfortunately, I won't have capacity to review this PR or at least not before my AFK. I'm reassigning it to other Peacock's Android devs.

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt [hunk 1]
```diff
@@ -107,6 +108,8 @@ internal class PaymentErrorMapper {
             "offline_pin_required",
             "online_or_offline_pin_required" -> PinRequired
 
+            "incorrect_pin" -> IncorrectPin
```
Comment (kidinov) [inline libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt:111]: In the docs both `invalid_pin` and `incorrect_pin` has the same next steps:

```
The customer needs to try again using the correct PIN.
```

But for some reason we handle invalid pin as `PinRequired`.

On the other hand, it looks like the description is different.

```
The PIN entered is incorrect. This decline code only applies to payments made with a card reader.	
```
vs

```
The PIN entered is incorrect.
```

Hm, but still probably we should map both to the same `IncorrectPin` just in case 

<br class="Apple-interchange-newline">
```

https://docs.stripe.com/declines/codes

**Review by kidinov — APPROVED** [review]
I tested it on the US store with .55 and the same error code returned - works well

I left a comment which probably nice to address (if you think it makes sense)

**Comment by kidinov** [comment]
@AnirudhBhat 

This probably doesn't make sense already to do but jfyi `The author listed all the tests they ran` in the list which apparently you had to do

File: libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt (hunk 1 above)
Comment (AnirudhBhat) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt:111]: @kidinov One distinction I can see is that `incorrect_pin` seems to apply only for external card readers whereas `invalid_pin` applies for both external and builtin(Tap-to-pay) readers. We change the user facing message according to this.

Comment (kidinov) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt:111]: @AnirudhBhat that's probably correct. The issue is that the message for invalid_pin is

```
This card requires a PIN code and thus cannot be processed
```

Which I think not right. The message you added make more sense, wdyt?

Comment (AnirudhBhat) [reply libs/cardreader/src/main/java/com/woocommerce/android/cardreader/internal/payments/PaymentErrorMapper.kt:111]: Ah. Yeah, makes sense. I've mapped `invalid_pin` to `IncorrectPin` here: https://github.com/woocommerce/woocommerce-android/pull/12375/commits/60557bdd4d0407850d686e3c18bf1397e3324e52

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/232">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
