### PR TITLE
Media Upload: check filename before displaying upload error list

### LINKED ISSUE #5126: NullPointerException: state.media.fileName must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-2F4](https://sentry.io/organizations/a8c/issues/2696594102/?referrer=github_integration)

```
NullPointerException: state.media.fileName must not be null
    at com.woocommerce.android.ui.media.MediaUploadErrorListViewModel$ErrorUiModel.<init>(MediaUploadErrorListViewModel.kt:78)
    at com.woocommerce.android.ui.media.MediaUploadErrorListViewModel$2.invokeSuspend(MediaUploadErrorListViewModel.kt:50)
    at com.woocommerce.android.ui.media.MediaUploadErrorListViewModel$2.invokeSuspend(MediaUploadErrorListViewModel.kt:50)
    at com.woocommerce.android.ui.media.MediaUploadErrorListViewModel$2.invoke
    at com.woocommerce.android.ui.media.MediaUploadErrorListViewModel$2.invoke
...
(60 additional frame(s) were not displayed)
```

Last updated: Nov 1
Events so far: 223
Users affected: 123
Last seen in: v7.7

### PR DESCRIPTION
**Pull request by anitaa1990**
Closes: #5126 

### Description
I couldn't reproduce this issue but it is similar to the fix in #4828. There are cases when we might get a null url or fileName when the image upload process has failed. This used to happen in the downloadable files only but since v7.7 this has started occurring in the media upload error screen. We use the filename of the media for display purposes but since the filename is null, the app is crashing.

Since this has been happening for a while, I think we can target `develop` so that this issue will be fixed in the next beta.

### Testing
A small smoke test for image and downloadable file uploads should be enough.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt [hunk 1]
```diff
@@ -51,7 +51,9 @@ class MediaUploadErrorListAdapter : RecyclerView.Adapter<MediaUploadErrorListIte
         RecyclerView.ViewHolder(viewBinding.root) {
         fun bind(model: ErrorUiModel) {
             with(model) {
-                viewBinding.mediaFileName.text = fileName
+                if (fileName.isNotBlank()) {
+                    viewBinding.mediaFileName.text = fileName
+                }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt]: As this is part of a RecyclerView, we should update the view's value for every binding, to avoid keeping the old value when recycling the ViewHolder.
So we need to either set `viewBinding.mediaFileName.text` unconditionally, since it will just be empty if the filename is empty (simpler IMO), or change its visibility.
WDYT @anitaa1990 ? 🙂

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt]: Ahh, ok you mean we can remove the condition around this text since it can be displayed even if it is blank 😅 Ok, that makes sense 👍

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt]: Done in 49f6a6a

**Comment by anitaa1990** [comment]
Thanks for the review @hichamboushaba! Ready for another round 😊

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/media/MediaUploadErrorListAdapter.kt]: > ok you mean we can remove the condition around this text since it can be displayed even if it is blank

Yes, and the cause is that this can happen (unlikely but still possible):
1. A ViewHolder is used to show the error with a non-empty filename.
2. While scrolling, the same ViewHolder is being recycled to be used for an error with an empty filename.
3. With the condition in place, we won't update the `viewBinding.mediaFileName` value, but we will still display the old value.

**Review by hichamboushaba — APPROVED** [review]
Thanks for the quick fix @anitaa1990
