### PR TITLE
Issue/1928 woo log concurrent exception

### LINKED ISSUE #1928: RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.support.Wo...
Sentry Issue: [WOOCOMMERCE-ANDROID-CP](https://sentry.io/organizations/a8c/issues/1508510185/?referrer=github_integration)

```
ConcurrentModificationException: None
    at com.woocommerce.android.util.WooLog$LogEntryList.toHtmlList(WooLog.kt:236)
    at com.woocommerce.android.util.WooLog.toHtmlList(WooLog.kt:187)
    at com.woocommerce.android.support.WooLogViewerActivity$LogAdapter.<init>(WooLogViewerActivity.kt:112)
    at com.woocommerce.android.support.WooLogViewerActivity.onCreate(WooLogViewerActivity.kt:51)
...
(13 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.support.WooLogViewerActivity}: java.util.ConcurrentModificationException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2868)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2950)
    at android.app.ActivityThread.-wrap11
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
    at android.os.Handler.dispatchMessage(Handler.java:106)
...
(5 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{com.woocommerce.android/com.woocommerce.android.support.WooLogViewerActivity}: java.util.ConcurrentModificationException
```

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #1928 - our application log has apparently had a long-standing bug that could crash the app if a log entry was added while iterating the list of entries. You can easily reproduce this crash by adding the following line [here](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt#L245) and then viewing the log:

```
this.add(entry)
```

This PR resolves the concurrency exception by making a copy of the entry list and iterating that instead of the actual list.

As part of this PR, I also converted the log's string formatting to use Kotlin string templates.

Update release notes

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt [hunk 1]
```diff
@@ -75,7 +75,7 @@ object WooLog {
      * @param message The message you would like logged.
      */
     fun v(tag: T, message: String) {
-        Log.v(TAG + "-" + tag.toString(), message)
+        Log.v("$TAG-$tag", message)
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt]: There's a matching `test` version of this class in `WooCommerce/src/test/kotlin/com/woocommerce/android/util/WooLog.kt` that should probably also be updated for consistency.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt [hunk 2]
```diff
@@ -233,7 +233,9 @@ object WooLog {
          */
         fun toHtmlList(): ArrayList<String> {
             val list = ArrayList<String>()
-            for (entry in this) {
+            // work with a copy of the log entries in case they're modified while traversing them
+            val entries = ArrayList<LogEntry>().also { it.addAll(this) }
```
Comment (AmandaRiu) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt]: NP: recommend using Kotlin's `mutableListOf<>()` instead of `ArrayList<>()`. `mutableListOf` currently just returns `ArrayList()`, but the docs recommend using the kotlin version so that if a faster more optimal way of working with lists is implemented in the future then we'll always be using best version.

Ex:
```
val entries = mutableListOf<LogEntry>().also { it.addAll(this) }
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt (hunk 1 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt]: Ah, missed that. Corrected in 7c16769.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt (hunk 2 above)
Comment (nbradbury) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooLog.kt]: Done in fe90c80.
