### PR TITLE
Product Details: refactor menu handling

### LINKED ISSUE #4373: Products: "Save as draft" option does not appear in the overflow menu if the very first change you make to a new product is to change the status to "Draft" in the product settings
Steps to reproduce:

1. Go to Products > Add new product ("+" at bottom right).
1. Immediately change the status to a draft by going to More > Product settings > Status > Draft.
1. Add a title, description, and price.
1. Observe that the "Save as draft" never appears.
1. Repeat the steps above except add the product details before trying to save the new product as a draft.
1. Observe that now you can see a "Save as draft" option.

**Result:** if you change the status in product settings to "Draft" as the _very first step_ when creating a new product, then you are never offered the option to "Save as draft" in the overflow menu. ([3m43s](https://user-images.githubusercontent.com/1119271/124664121-37db0e00-de68-11eb-93c3-9d3bfe25ed1c.mp4))

New product > Product settings|Change status to draft|"Save as draft" never appears<br>even after making other changes
---|---|---
image|image|Screen Shot 2021-07-06 at Jul 6 2 35 34 PM

<sup>Tested with WCAndroid 7.0-rc-1 on Pixel 3 Android 11.</sup>

<sup>(internal reference: p5T066-2sv-p2#comment-8976 /ht @anitaa1990)</sup>

### PR DESCRIPTION
**Pull request by hichamboushaba**
### Description
After working on #6097, I noticed that the detection of `hasChanges` is not reactive enough, in the sense that when we move to async operations to unblock threads, it stops working correctly (you can simulate the issue by checking out the commit c1fb727da29a1601e210fce161ef93502e11046d, then adding a `delay` in the function `initializeStoredProductAfterRestoration`, you'll notice that the `save` button won't have the correct state after restoring the Activity).
Also the handling was not centralized, which made following what's going on hard.

This is an attempt at refactoring things, with two big parts:
1. Making the logic reactive, via two observable Flows `hasChanges` and `menuButtonsState`
2. Consolidating the logic of updating the buttons state UI wise in a single function `Menu#updateOptions`

Please feel free to suggest any changes, or if you feel the refactoring is not needed.

**An advice for reviewing**: it's best to review the commit 40cb809 independently, since it's not related to the changes, instead it just moves to using the suspendable function `getProductAsync` for fetching initial product.

##### Edit Product
| Button | Conditions for visibility |
| ---- | ------ |
| Save | Product has non-saved Changes |
| View Product | Product has status "Published" with visibility different than "Private" |
| Share | Always |
| Trash | Product details is opened from Products List | 
| Publish | Product has status "draft" |
| Save as draft | never |
| Product Settings | Always |

##### Add product
| Button | Conditions for visibility |
| ---- | ------ |
| Save | (Product was saved to the remote site **or** has draft status) **and** has nonsaved changes. This aligns behavior with iOS and fixes #4373 |
| View Product | Product was saved to the remote site **and** has status "Published |
| Share | Product was saved to the remote site |
| Trash | never | 
| Publish | Product not saved yet in the remote site **or** has "draft" status |
| Save as draft | Product not saved yet in the remote site **and** doesn't have "draft" as status  |
| Product Settings | Always |

* Product was saved to the remote site means the product was pushed either using "save as draft" or "publish"

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt [hunk 1]
```diff
@@ -526,5 +468,21 @@ class ProductDetailFragment :
...
+        findItem(R.id.menu_save)?.isVisible = state.saveOption
+        findItem(R.id.menu_save_as_draft)?.isVisible = state.saveAsDraftOption
+        findItem(R.id.menu_view_product)?.isVisible = state.viewProductOption
+        findItem(R.id.menu_publish)?.apply {
+            isVisible = state.publishOption
+            if (state.saveOption) {
+                setShowAsActionFlags(MenuItem.SHOW_AS_ACTION_NEVER)
+            } else {
+                setShowAsActionFlags(MenuItem.SHOW_AS_ACTION_IF_ROOM)
+            }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailFragment.kt:481]: This logic is replicating what was added in https://github.com/woocommerce/woocommerce-android/pull/5249.

**Comment by hichamboushaba** [comment]
@atorresveiga sorry for interfering with your work in https://github.com/woocommerce/woocommerce-android/pull/6033 😅, but since this is a bigger refactoring, I think once we approve this PR, you can safely close your PR, and concentrate on the badge changes on a different PR, WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 2]
```diff
@@ -94,12 +89,19 @@ class ProductDetailViewModel @Inject constructor(
...
         }
     }
     private var viewState by productDetailViewStateData
 
-    private var storedProduct: Product? = null
+    /**
+     * The goal of this is to allow composition of reactive streams using the product draft changes,
+     * we need a separate stream because [LiveDataDelegate] supports a single observer.
+     */
+    private val draftChanges = MutableStateFlow<Product?>(null)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:102]: I'm planning to create a different PR soon that updates `LiveDataDelegate` to support multiple observers, when this is done, we will be able to delete this intermediary `Flow`, and just replace its usages with:
`productDetailViewStateData.liveData.map { it.productDraft }.asFlow()`

**Comment by atorresveiga** [comment]
>...since this is a bigger refactoring, I think once we approve this PR, you can safely close your PR, and concentrate on the badge changes on a different PR

@hichamboushaba, No problem. I will create another PR with the badge changes once we approve this PR 😁

Excellent work, Hicham! The code looks good to me. I only have noticed the introduction of some wildcard imports (not sure about the team's opinion on wildcard imports), but I believe explicitly listing all imports improves code readability.

I have tested the PR and only have found this issue: 
When creating a new product and the product's status is Draft, if I press Save, the product is **published** instead of **saved as a draft**.

### Testing instructions:
1. Products -> New product
2. (Optional) -> Add a title
3. More menu (...) -> Product settings -> Status -> Draft
4. Check that Save and Publish switched places (Publish is now under the more menu)
5. Press Save
6. The product gets published and not saved as a draft.

https://user-images.githubusercontent.com/18119390/160884663-b1247755-862d-44b3-9f54-7c1b632ca049.mp4

**Comment by hichamboushaba** [comment]
Thanks @atorresveiga for the review 🙏 

> I only have noticed the introduction of some wildcard imports (not sure about the team's opinion on wildcard imports), but I believe explicitly listing all imports improves code readability.

We had a discussion about this before internally, the agreement was to allow both approaches, since Android Studio (and Intellij Idea) enables wildcard imports by default when there are more than 5 imports for a specific package, and we don't want to enforce anyone to update their settings.
Also, this is a subjective point, personally, I like Idea's default options, I think they are a good compromise between two extremes, and since the IDE takes care of the imports anyway, I don't review them on the PRs, which means whatever the PR writer had on his machine doesn't bother me 🙂.
Anyway, if you feel this is something that we should reconsider, feel free to restart the discussion internally.

> When creating a new product and the product's status is Draft, if I press Save, the product is published instead of saved as a draft.

Nice catch 👏, I'll check the code 🙂.

**Comment by hichamboushaba** [comment]
@atorresveiga the issue about saving a new product with `draft` status should be fixed by a02c959, I opted for having two distinct functions `onSaveClicked` and `onPublishClicked` to make the code clearer on possible paths and what it does.

I also added a test case for this scenario in 0393b16.

Ready for another round.

**Review by atorresveiga — APPROVED** [review]
Looks great @hichamboushaba! 🙌 I have tested the save have a draft issue and is working as expected. Great job by adding the unit test 👏
