### PR TITLE
Fix tracks connected info property naming

### LINKED ISSUE #1284: Tracks Issue: Invalid event property formatting
While testing completely unrelated code changes, I ran across these errors in logcat:
```
W/NosaraEvent: Properties should have lowercase name: hasJetpack
E/NosaraEvent: Cannot add the property: hasJetpack to the event. Property name must match: ^[a-z_][a-z0-9_]*$
W/NosaraEvent: Properties should have lowercase name: isJetpackConnected
E/NosaraEvent: Cannot add the property: isJetpackConnected to the event. Property name must match: ^[a-z_][a-z0-9_]*$
W/NosaraEvent: Properties should have lowercase name: urlAfterRedirects
E/NosaraEvent: Cannot add the property: urlAfterRedirects to the event. Property name must match: ^[a-z_][a-z0-9_]*$
W/NosaraEvent: Properties should have lowercase name: isJetpackActive
E/NosaraEvent: Cannot add the property: isJetpackActive to the event. Property name must match: ^[a-z_][a-z0-9_]*$
W/NosaraEvent: Properties should have lowercase name: isWPCom
E/NosaraEvent: Cannot add the property: isWPCom to the event. Property name must match: ^[a-z_][a-z0-9_]*$
W/NosaraEvent: Properties should have lowercase name: isWordPress
E/NosaraEvent: Cannot add the property: isWordPress to the event. Property name must match: ^[a-z_][a-z0-9_]*$
```

I checked Tracks Live View and verified the following event properties are not being recorded:
- `hasJetpack`
- `isJetpackConnected`
- `urlAfterRedirects`
- `isJetpackActive`
- `isWPCom`
- `isWordPress`

These properties need to be renamed to follow the pattern `^[a-z_][a-z0-9_]*$`:
- `has_jetpack`
- `is_jetpack_connected`
- `url_after_redirects`
- `is_jetpack_active`
- `is_wp_com`
- `is_wordpress`

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1284 by renaming the event properties for  `LOGIN_CONNECTED_SITE_INFO_SUCCEEDED` to conform to the tracks property naming convention. Also added a new property called `login_calculated_has_jetpack` to make it easier to report on whether or not jetpack is active and connected since determining that requires looking at several properties.

Logcat event:
```
Tracked: login_connected_site_info_succeeded, Properties: {"is_wp_com":"false","has_jetpack":"true","is_wordpress":"true","login_calculated_has_jetpack":"true","is_jetpack_active":"true","url_after_redirects":"http:\/\/testwooshop.mystagingwebsite.com","exists":"true","is_jetpack_connected":"true","url":"testwooshop.mystagingwebsite.com"}
```

I already verified in Tracks the new events are properly being saved, so the reviewer need only approve and merge :)

Screen Shot 2019-07-26 at 11 08 27 AM

This fix has been built off of the `2.2` release tag in the hopes that we can get it released as a hotfix.

cc: @jkmassel  @loremattei

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java [hunk 1]
```diff
@@ -402,13 +402,24 @@ public void onFetchedConnectSiteInfo(OnConnectSiteInfoChecked event) {
...
-            properties.put("isWPCom", Boolean.toString(event.info.isWPCom));
+            properties.put("has_jetpack", Boolean.toString(event.info.hasJetpack));
+            properties.put("is_jetpack_active", Boolean.toString(event.info.isJetpackActive));
+            properties.put("is_jetpack_connected", Boolean.toString(event.info.isJetpackConnected));
+            properties.put("is_wordpress", Boolean.toString(event.info.isWordPress));
+            properties.put("is_wp_com", Boolean.toString(event.info.isWPCom));
+
+            // Determining if jetpack is actually installed takes additional logic. This final
+            // calculated event property will make querying this event more straight-forward:
+            boolean hasJetpack = false;
```
Comment (nbradbury) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java]: Can we not rely on `event.info.hasJetpack` to determine this?

Comment (nbradbury) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java]: Nevermind that :)

**Comment by nbradbury** [comment]
:shipit:
