### PR TITLE
Fix ProductImageMap ConcurrentModificationException by Safely Managing WeakReferences

### LINKED ISSUE #10901: [Tablet Support M2] Crash when switching from one store to the next
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

```
Process: com.woocommerce.android.dev, PID: 18085
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                                                                    	at com.woocommerce.android.tools.ProductImageMap$get$2$2$1.invokeSuspend(ProductImageMap.kt:100)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7f67dde, Dispatchers.IO]
```
**To Reproduce**
1. Switch from one store to the next.
2. Click on the orders tab.
3. Observe the crash.

**Screenshots**

**Expected behavior**
The app should not crash when this switch is being done.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Nexus 10
- Android version: Android 13
- WooCommerce Android version: M2 Tablet Support

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #10901
### Description

In addressing the `ConcurrentModificationException` within the `ProductImageMap` class, we opted to refine our approach by removing the previously implemented `CopyOnWriteArrayList` and instead directly tackling the issue with WeakReference objects in the observer list. Thanks to @malinajirka for this exploration. 

The revised solution is an improvement to the PR https://github.com/woocommerce/woocommerce-android/pull/10902 It involves a two-step modification process: initially, the code iterates over the observer list, identifying any `WeakReference` objects that have been cleared due to garbage collection and adding them to a temporary list. This method prevents the direct modification of the observer list during iteration, which was the primary cause of the exception. 
Following this, the code iterates over the temporary list to safely remove the identified references from the original observer list. By reverting the `CopyOnWriteArrayList` implementation and focusing on the specific management of `WeakReference` objects, this solution effectively addresses the root cause of the exception, ensuring the integrity of the observer list without incurring the overhead associated with introducing `CopyOnWriteArrayList`.

### Testing instructions

1. Switch from one store to the next.
2. Open the Orders tab.
3. Notice no crash takes place.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt [hunk 1]
```diff
@@ -64,11 +63,15 @@ class ProductImageMap @Inject constructor(
...
                             observers.forEach { weakReference ->
-                                // notify the observer
-                                weakReference.get()?.onProductFetched(remoteProductId)
-                                    // remove the weak reference if the observer was garbage collected
-                                    ?: observers.remove(weakReference)
+                                // notify the observer or collect it for removal if it's been garbage collected
+                                weakReference.get()?.onProductFetched(remoteProductId) ?: toRemove.add(weakReference)
+                            }
+                            // Remove the collected references
+                            toRemove.forEach { weakReference ->
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt]: 🔍 Nitpick: I believe we can utilize `removeAll` method here for increased readability, instead of going one item at a time.

```
observers.removeAll(toRemove)
```

Wdyt?

**Review by malinajirka — APPROVED** [review]
I've reviewed and re-tested the code and LGTM. I've left one minor suggestions. 

I think it might be better to merge this after the code-freeze as it's Friday evening, having said that, it's up to you.

P.S. We could potentially also use an iterator which allows us to remove elements during iteration
```
val observersIterator = observers.iterator()
while (observersIterator.hasNext()) {
    // notify the observer or collect it for removal if it's been garbage collected
    observersIterator.next().get()?.onProductFetched(remoteProductId) 
        ?: observersIterator.remove()
}
```
Having said that, I'm not convinced it's more readable with the iterator.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt (hunk 1 above)
Comment (jd-alexander) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/tools/ProductImageMap.kt]: Yeah, we can use `removeAll` for sure. 😄

**Comment by jd-alexander** [comment]
> I think it might be better to merge this after the code-freeze as it's Friday evening, having said that, it's up to you.

Totally fine with merging after the code freeze.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
