### PR TITLE
[Blaze] Add dialog when no product is found during Blaze intro in More Menu.

### LINKED ISSUE #12503: "No product found" popup in Blaze creation flow
**Describe the bug**
When there is no product, the "Create campaign" button does nothing and returns to the menu tab.

**To Reproduce**
1. Log in with a site thas ni product.
2. Open the Menu tab.
3. Tap Blaze button.
4. Tap "Create campaign button".

**Screenshots**

[create-campaign.webm](https://github.com/user-attachments/assets/6db7121b-e3c2-40ea-ac6d-2834b7887c07)

**Expected behavior**
A "No product found" popup should be displayed like we do in iOS.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active,
  or [Storefront](https://woocommerce.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
- Device: Emulator
- Android version: 14
- WooCommerce Android version: 20.2

**WordPress Environment**
<details>
```
### System Status Report generated via the WooCommerce Android app ### 

 ### WordPress Environment ### 

WordPress Address (URL): https://usually-great.jurassic.ninja
Site Address (URL): https://usually-great.jurassic.ninja
WC Version: 9.2.3
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

 ### Server Environment ### 

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 1 GB
PHP Time Limit: 1200 s
PHP Max input Vars: 6144
cURL Version: 8.7.1, OpenSSL/3.0.11
Suhosin installed: –
MySQL Version: 10.6.17-MariaDB-log
PHP Post Max Size: 1 GB
Default Timezone: UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibye String: ✔
Remote Post: ✔
Remote Get: ✔

 ### Database ### 

WC Database Version: 9.2.3
WC Database Prefix: wp_
Total Database Size: 3.13 MB
Database Data Size: 1.35 MB
Database Index Size: 1.79 MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

 ### Security ### 

Secure Connection (HTTPS): ✔
Hide errors from visitors: ✔

 ### Active Plugins ### 

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team - 5.3.3
Jetpack: by Automattic - 13.8-a.7
WooCommerce: by Automattic - 9.2.3

 ### Settings ### 

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: 
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: 
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

 ### WC Pages ### 

Shop base:  Page ID #5
Cart:  Page ID #6
Checkout:  Page ID #7
My account:  Page ID #8
Terms and conditions: X Page not set

 ### Theme ### 

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
WooCommerce support: –
WooCommerce files: –
Outdated templates: –

 ### Templates ### 

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php

 ### Status report information ### 

Generated at: 2024-09-03 18:07:28 +0300
```
</details>

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #12503

### Description

Currently, there is an issue where if the site has no product, the Blaze intro screen has no way to proceed with creating the campaign. This PR fixes that by adding a product creation step from the intro.

### Steps to reproduce

1. Have a test site with no products, ideally a completely new site so Blaze campaign intro is still shown,
3. Go to More Menu, tap Blaze, ensure the "Get your products seen by millions" intro screen is shown,
4. Tap "Start your campaign" CTA button,
5. Ensure a "No products found" dialog is shown
6. Test that "Cancel" button is working (returns to the intro screen)
7.  Tap "Start your campaign" CTA button again, 
8. Test that the "Create product" dialog is shown (opens the product creation bottom sheet). This sheet is the same as displayed by the Onboarding card > "Add your first product" option, if you want to compare.
9. Go through the product creation process and ensure it goes well,
10. After product is created, close the product creation screen and ensure it goes back to the Blaze campaign intro screen,
11. Tap "Start your campaign" CTA button again, ensure it now opens the campaign creation correctly.

Optional: trash the Product and start over from step 3 to 5, ensure it shows the dialog again.

### Testing information

I tested this on an emulated Pixel 8 with API 32, following closely the steps above. I can't think of any edge cases yet, but let me know if there's other entry points aside from more menu that needs to be covered too.

### The tests that have been performed

I tested following the steps outlined above.

### Images/gif

| Dialog shown when no product exists | Bottom sheet shown when "Create Product" is tapped |
|-|-|
| Screenshot_20241126_135844 | Screenshot_20241126_135857 |

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt [hunk 1]
```diff
@@ -57,6 +58,28 @@ class BlazeCampaignCreationIntroFragment : BaseFragment() {
                     navigateToProductSelectorScreen()
                 }
 
+                is BlazeCampaignCreationIntroViewModel.ShowNoProductCTA -> {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt]: Np, and probably a matter of personal taste but I'd name this event `ShowNoProductDialog` to be explicit about showing a dialog. CTA sound to me like a button.

**Review by JorgeMucientes — APPROVED** [review]
Code looks good and works as expected. Nice job @hafizrahman. Just left a minor np, feel free to ignore it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt (hunk 1 above)
Comment (hafizrahman) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/intro/BlazeCampaignCreationIntroFragment.kt]: That's a good point, updated in https://github.com/woocommerce/woocommerce-android/pull/13001/commits/ba897b7c60f5ffdb622931a011d66b86cdc74fde

At first I called it CTA because at the end of the day, there is only one successful path we want merchants to go to (create a product), otherwise the rest of Blaze flow can't be continued. But it did indeed sound weird because the event is showing a dialog, not just a single CTA.

**Comment by hafizrahman** [comment]
I added an extra commit for cleaning up the dialog but it's not affecting anything in the test flow.
