### PR TITLE
Use plugin fetching to check Jetpack installation

### LINKED ISSUE #9397: [REST API] Incorrect endpoint used for checking Jetpack installation status
### Description:
WooCommerce 7.9+ added `/jetpack/v4/connection/data/` endpoint as part of the Jetpack Connection Package effort. This has a undesired side-effects, since the Android app uses this endpoint to determine whether Jetpack is installed on the side. The app expects 404 code to be returned when Jetpack is not installed, however, the endpoint on Woo 7.9+ returns an answer.

The iOS uses `/wp/v2/plugins/jetpack/jetpack` endpoint to determine if Jetpack is installed.

For the moment, there's an existing workaround on the backend side which returns 404 for mobile requests when full Jetpack plugin is NOT installed. Ideally, we’d remove this workaround after we update the Android app.

More context in peaMlT-7P-p2

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #9397. The PR updates the Jetpack installation & activation check by using a separate endpoint to fetch plugins. The JP connection and email address endpoint stayed the same.

**To test:**
1. Prepare a self-hosted site with WooCommerce but without Jetpack
2. Log in
3. Tap on the Jetpack promotion banner
4. Notice the next screen prompts you to install Jetpack
5. Go back to to main screen
6. Install & activate Jetpack on the site, but don't connect
7. Tap on the Jetpack banner
8. Notice the next screen either prompts you to connect an email address to Jetpack

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt [hunk 1]
```diff
@@ -5,46 +5,64 @@ import com.woocommerce.android.extensions.orNullIfEmpty
...
+                    return Result.failure(OnChangedException(result.error))
+                }
+                else -> {
+                    if (result.model!!.none { it.slug == JETPACK_SLUG && it.isActive }) {
+                        return Result.success(
+                            Pair(
+                                JetpackStatus(
+                                    isJetpackInstalled = false,
+                                    isJetpackConnected = false,
+                                    wpComEmail = null
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt]: Thanks @0nko for working on this, just one remark here: there could still be a Jetpack connection even when Jetpack is not installed, sorry if it wasn't clear enough in the P2, but I think we should make the two requests in all cases, and instead of `returning` here, we need just to get the `isJetpackInstalled` value, and then make the second call to get the `isJetpackConnected` and `wpComEmail` values.

This is needed as a preparation for handling: "Jetpack not installed, but connected using JCP", which will be implemented in the next ticket.

Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt]: Gotcha, thanks!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt [hunk 2]
```diff
@@ -5,72 +5,83 @@ import com.woocommerce.android.extensions.orNullIfEmpty
 import com.woocommerce.android.model.JetpackStatus
 import com.woocommerce.android.tools.SelectedSite
 import org.wordpress.android.fluxc.store.JetpackStore
+import org.wordpress.android.fluxc.store.WooCommerceStore
 import javax.inject.Inject
 
 /**
+ * First, a list of plugins is fetched from the site. If Jetpack is not installed, then the
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt]: np, we fetch the user data first now, so we need to update the comment.
But I'm wondering, do we really need the comment like this? I think the logic is straightforward, and this just adds a maintenance overhead, we can probably replace the lonc comment with just bits for the parts that are not very straightforward, like the 403 and 404 branches below, WDYT?

**Review by hichamboushaba — APPROVED** [review]
Nice work @0nko, code looks good, and works well, I tested with a site that has WooCommerce 7.8 (before adding Jetpack Connection and its workaround) with WCPay, using `trunk` the flow fails, and using this branch it works as expected 🎉.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt (hunk 2 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/jetpack/benefits/FetchJetpackStatus.kt]: Good catch. The comment was there before so I updated it, however, I agree that it's not really necessary.
