### PR TITLE
Handle order Add-ons loading failure

### LINKED ISSUE #4696: [Product Add-ons] Handle loading failure on `OrderedAddons` Fragment and ViewModel
When clicking at `View Add-ons` inside Order Details, we call a number of operations that can go wrong easily, especially considering that we do a workaround with the Add-ons data to be able to display everything. We should be able to recover from any possible loading error using cached data and/or giving an error prompt, as it is we do nothing as we can see here:

https://github.com/woocommerce/woocommerce-android/blob/347b90ea29bd46ccf69a1929c831f89851d14b1a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt#L108

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #4696 by refactoring the `OrderedAddonViewModel` to get cached data even when fetching recent information doesn't succeed. Also, it introduces a series of improvements for failure state at the view meanwhile refactoring the responsibilities between Fragment and ViewModel

Screenshots
==========
| Data loading successful  | Data loading failed |
| ------------- | ------------- |
| Screenshot_20210908_200706 | Screenshot_20210908_195401 |

How to Test
==========
Prerequisites: Have your site with the add ons plugin installed, configured, and with at least one product with add-ons and at least one order of the configured product including Global Add-ons.

⚠️ Note that you should configure both Product-specific and Global add-ons in your store in order to test this improvement properly.

## Data loading successful
1 - Launch the Woo app.
2 - Navigate to an order with a Product configured with Add-ons, verify if the View Add-ons Button is showing up for products that contain Add-ons inside the current Order, but doesn't show up for Products without Add-ons for that order or Products that don't have Add-ons configured at all.
3 - Click on View Add-ons and verify if the Ordered Addons view is displayed with all the expected data, including Global Add-ons data.

## Data loading failed

We shouldn't be able to reproduce this failure easily since the `View Add-ons` button shouldn't be visible if there's no Ordered Add-ons to display, so I suggest to try to reproduce this issue by hard-coding the failure state, to do so, go to `OrderedAddonsViewModel` and change the start method to look like this:
``` suggestion
    fun start(
        orderID: Long,
        orderItemID: Long,
        productID: Long
    ) = viewState.copy(isSkeletonShown = true).let { viewState = it }.also {
        launch(dispatchers.computation) {
            addonsRepository.updateGlobalAddonsSuccessfully()
            loadOrderAddonsData(orderID, orderItemID, productID)
                .let { null }
                ?.let { dispatchResult(it) }
                ?: handleFailure()
        }
    }
```
After doing this change, do the following:
1 - Launch the Woo app.
2 - Navigate to an order with a Product configured with Add-ons, verify if the View Add-ons Button is showing up for products that contain Add-ons inside the current Order, but doesn't show up for Products without Add-ons for that order or Products that don't have Add-ons configured at all.
3 - Click on View Add-ons and verify if the Ordered Addons view is displaying the failure dialog, and pressing OK dismiss the entire view back to Order Details.

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt [hunk 1]
```diff
@@ -99,23 +84,28 @@ class OrderedAddonFragment : BaseFragment(R.layout.fragment_ordered_addon) {
...
 
     private fun setupViews() {
         supportActionBar?.setHomeAsUpIndicator(R.drawable.ic_gridicons_cross_24dp)
         binding.addonsWipCard.initView(
             title = getString(R.string.ordered_add_ons_wip_title),
             message = getString(R.string.ordered_add_ons_wip_message),
-            onGiveFeedbackClick = ::onGiveFeedbackClicked,
-            onDismissClick = ::onDismissWIPCardClicked
+            onGiveFeedbackClick = viewModel::onGiveFeedbackClicked,
+            onDismissClick = viewModel::onDismissWIPCardClicked
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt:114]: To better fit what's expected from a ViewModel and Fragment, I decided to refactor this so everything related to the Feedback card event get handled by the ViewModel

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt [hunk 2]
```diff
@@ -139,55 +123,22 @@ class OrderedAddonFragment : BaseFragment(R.layout.fragment_ordered_addon) {
...
-
-        showWIPNoticeCard(false)
+    private fun onOrderedAddonsFailed() {
+        binding.addonsEditNotice.visibility = GONE
+        MaterialAlertDialogBuilder(requireContext())
+            .setTitle(R.string.ordered_add_ons_loading_failed_dialog_title)
+            .setMessage(R.string.ordered_add_ons_loading_failed_dialog_message)
+            .setCancelable(false)
+            .setPositiveButton(R.string.link_dialog_button_ok) { _, _ -> findNavController().navigateUp() }
+            .show()
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt]: The view is completely useless if it wasn't able to load the Add-on data, if the `View Add-ons` button was displayed at the Order Details (the button is only displayed when there's Ordered Add-ons detected) and the Ordered Addon View couldn't load anything, this would be a serious Illegal state situation, so this Dialog serves as an end of the line situation to the view.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt [hunk 3]
```diff
@@ -50,14 +63,43 @@ class OrderedAddonViewModel @Inject constructor(
...
         launch(dispatchers.computation) {
-            takeIf { addonsRepository.updateGlobalAddonsSuccessfully() }
-                ?.let { addonsRepository.getOrderAddonsData(orderID, orderItemID, productID) }
-                ?.let { mapAddonsFromOrderAttributes(it.first, it.second) }
+            addonsRepository.updateGlobalAddonsSuccessfully()
+            loadOrderAddonsData(orderID, orderItemID, productID)
+                ?.takeIf { it.isNotEmpty() }
                 ?.let { dispatchResult(it) }
-                ?: dispatchFailure()
+                ?: handleFailure()
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModel.kt:70]: This is the part that delivers the issue goal, now we ask to update Global Add-ons, but we will not depend on the success of this fetching to do it, if the request succeeds, the `loadOrderAddonsData` will get recent data that was just cached, if it fails, it will try to load what is available in cache, if nothing is available, we trigger the failure handling.

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt [hunk 4]
```diff
@@ -48,6 +53,14 @@ class OrderedAddonViewModelTest : BaseUnitTest() {
                 .doReturn(storeParametersMock)
         }
 
+        val editor = mock<SharedPreferences.Editor> { whenever(it.putBoolean(any(), any())).thenReturn(mock()) }
+        val preferences = mock<SharedPreferences> { whenever(it.edit()).thenReturn(editor) }
+        mock<Context> {
+            whenever(it.applicationContext).thenReturn(it)
+            whenever(it.getSharedPreferences(any(), any())).thenReturn(preferences)
+            FeedbackPrefs.init(it)
+        }
```
Comment (ThomazFB) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonViewModelTest.kt:62]: After moving the FeedbackState handling to the ViewModel, we need to mock the SharedPreferences operations and initialize the FeedbackPrefs.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt (hunk 2 above)
Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/addons/order/OrderedAddonFragment.kt]: > The view is completely useless if it wasn't able to load the Add-on data, if the View Add-ons button was displayed at the Order Details

True, good decision! 👍

**Review by wzieba — APPROVED** [review]
I've tested both positive and negative cases and also added a `delay` in `AddonsRepository#updateGlobalAddonsSuccessfully` to check how things work if it was a slow hosting provider e.g. 

Looks and works good, I have no concerns. Thank you @ThomazFB !

As you said, we'll have a minor conflict with #4751 - I'll merge this PR and will adjust in #4751 .
