### PR TITLE
Upsell card reader banner re-appears after dismissal and doing the pull to refresh on the order listing screen.

### LINKED ISSUE #7445: Upsell card reader banner re-appears after dismissal on pull to refresh
Upsell card reader banner re-appears after dismissal and doing the pull to refresh on the order listing screen.

Steps to reproduce
1. Navigate to the order listing screen
2. Dismiss the banner
3. Without navigating to any other screen, Pull to refresh in the order listing screen.
4. Notice the Banner re-appears again.

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #7445 

### Description

Upsell card reader banner re-appears after dismissal and doing the pull to refresh on the order listing screen.

**Steps to reproduce**

1. Navigate to the order listing screen
2. Dismiss the banner
3. **Without navigating to any other screen**, Pull to refresh in the order listing screen.
4. Notice the Banner re-appears again.

This PR fixes this as well as refactors the Banner display requirements logic.

### Images/gif

https://user-images.githubusercontent.com/1331230/191910420-44f276f6-c371-4820-bf70-ddc3ec2388f7.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 1]
```diff
@@ -456,6 +429,13 @@ class OrderListFragment :
         }
     }
 
+    private fun updateBannerState(orderListSize: Int) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: This extra VM -> Fragment -> VM communication purely because you want to know if it's in the landscape? If yes, then probably having some `LandscapeChecker` wrapper class and injecting in directly to the VM will improve the code and testability

**Review by kidinov — APPROVED** [review]
The bug seems to be fixed. I left generic suggesting regarding code improvement. Please feel free to merge that if you want to land it in the next release and then if you think the suggestion is valuable to make an improvement

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 2]
```diff
@@ -199,11 +198,12 @@ class OrderListFragment :
         binding.orderFiltersCard.setClickListener { viewModel.onFiltersButtonTapped() }
         initCreateOrderFAB(binding.createOrderButton)
         initSwipeBehaviour()
-        val isLandscape = DisplayUtils.isLandscape(context)
-        if (!isLandscape) {
-            lifecycleScope.launch {
-                viewModel.updateBannerState()
-            }
+        updateBannerState()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: We could probably just use `map` on `_pagedListData` and call `updateBannerState` from there. In this case, we could also make it not suspend and just lunch view model scope coroutine from there

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt [hunk 3]
```diff
@@ -188,11 +191,21 @@ class OrderListViewModel @Inject constructor(
...
+            canShowCardReaderUpsellBanner(System.currentTimeMillis()) &&
+            !isLandScape &&
+            !isOrderListEmpty
+    }
+
     suspend fun updateBannerState() {
+        updateBannerState(landscapeChecker, _pagedListData.value.isNullOrEmpty())
+    }
+
+    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListViewModel.kt:209]: Probably pushing something to the `pagedListWrapper` you could avoid having it public?

**Review by kidinov — COMMENTED** [review]
Thank you for addressing my comments!  Sorry, but I left a couple of more =)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt (hunk 2 above)
Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: >We could probably just use map on _pagedListData and call updateBannerState from there

The only reason for updating the banner state from the view here is to make sure the banner is not being displayed in landscape mode. The view model doesn't know when the view goes into the landscape mode and someone needs to tell it. 

Another way we can solve this is by checking for the landscape mode in `bannerDisplayViewLogic` method. In this approach, the only downside is that we cannot unit test the logic for banner display in landscape/portrait mode

Let me know if you have another approach in your mind.

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: > The only reason for updating the banner state from the view here is to make sure the banner is not being displayed in landscape mode. The view model doesn't know when the view goes into the landscape mode and someone needs to tell it.

Please correct me if I am wrong, but on configuration change, the view model with its livedatas will push the latest state to the view, that's why `map` will be called and `updateBannerState` as well, where you will change already if it's landscape or not

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: I think `map` gets called when the `livedata` it's observing is set some value. When a configuration change happens, the latest result from the livedatas are simply pushed into its observers, and `map` itself doesn't get called. WDYT?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: > the latest result from the livedatas are simply pushed into its observers, and map itself doesn't get called. WDYT?

That would be really magical behavior that somehow the code inside of map would be ignored in certain situations.  I assume you tried to map it on `_pagedListData`?

I didn't find a good approach to keep mutable mapped life data hidden and with a nice syntax

One might be (not really "kotlinish" way):

```
    private val _pagedListData = MediatorLiveData<PagedOrdersList>()
    fun getPagedListData(): LiveData<PagedOrdersList> = _pagedListData.map {
            println("pagedListData map")
            it
        }
```

Not ideal, but probably a bit better than calling pushing state multiple times to the composable

Having said that, I don't have a strong opinion on this, so it's totally up to you. You might find know a better approach here

Comment (AnirudhBhat) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt]: You are right. I had this implementation initially
```
private val _pagedListData = MediatorLiveData<PagedOrdersList>()
val pagedListData: LiveData<PagedOrdersList> = _pagedListData.map {
            println("pagedListData map")
            it
        }
```
It never occurred to me that the `val` caches its value 🤦 I have added a custom getter for the `val` and all of the banner state handling is being done in the `ViewModel` now. 

Thanks for the `map` idea 💡 

I'll be merging this PR now since I need to get this in by tomorrow. Please feel free to drop any other suggestions and I will make sure to look into those for the next release.
