### PR TITLE
[Shipping Labels] Handle loading account settings error

### LINKED ISSUE #13318: Loading account settings fails
When loading the account settings in the purchase shipping label flow, we should display an error if the request fails.

Image

https://teameaglep2.wordpress.com/2025/01/15/revamp-shipping-labels-recovering-from-errors/

### PR DESCRIPTION
**Pull request by irfano**
Closes: #13318 

### Description

This introduces a new error screen to the shipping labels creation screen. If fetching account settings fails, this error screen will appear. Currently, the Retry button is non-functional and will be addressed in #13598.
Reference for the error screen design: bsLNrhmi2xQZB4C0TzjmHB-fi-3374_21712 (I’m aware that this design is from a WIP/M4 version. We can update the screen later if the design changes.)

This also adds a top bar to loading screen.

#### To create fake error response from the endpoint
1. Go to Menu → Settings → Developer Options → API Faker
2. Tap + button.
3. Enter these settings:
```
Type: WordPress REST API
HTTP Method: GET
Path: /wcshipping/v1/account/settings
Status Code: 403
```
4. Tap Save.
5. Enable API Faker.

#### To display the error screen
1. Log in to a site that is eligible for shipping labels.
2. Go to orders.
3. Create a new order and complete the payment.
4. Open the order details and tap the "Create shipping label" button.

### Testing information

Please also test dark mode, light mode, large font, and vertical orientation.

### The tests that have been performed

Steps above.

### Images/gif

<details>
  <summary>Loading screen - First launch and second launch</summary>
  
[Screen_recording_20250220_150216.webm](https://github.com/user-attachments/assets/e9710869-39e7-4956-a124-7dcbe6b0f999)
  
</details>

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/251">21.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt [hunk 1]
```diff
@@ -674,6 +681,56 @@ private fun PackageSelectionAvailableCard(
     }
 }
 
+@Composable
+internal fun LoadingScreen(
```
Comment (atorresveiga) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/wooshippinglabels/WooShippingLabelCreationScreen.kt:685]: Nice!

**Review by atorresveiga — APPROVED** [review]
Great work @irfano! Thanks for also taking care of the loading screen.

LGTM! :shipit:
