### PR TITLE
Fix Flaky Variations Number Problem

### LINKED ISSUE #4210: Variations: Number of Variations Disappears After Creating a Variation
**Describe the bug**

The number of variations in the product details disappears after creating a variation. The variation is still there though, it's just not shown in the UI.

**To Reproduce**

1. Tap on Products tab → Big plus button. 
2. Choose Variable product. 
3. Add a variation and follow the flow until one variation is generated. 
4. When you're navigated back to the Product List, tap on “Variations (1 variation)”.
5. Navigate back. 
6. You'll notice that the “Variations (1 variation)“ button has been replaced by “Add variations“.

**Screenshots**

https://user-images.githubusercontent.com/198826/122105756-5eaca400-cdd6-11eb-9fe8-798439a0e35c.mov

**Expected behavior**

The “Variations (1 variation)” button should be displayed.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: `develop` (1fcdc0336)

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by shiki**
Fixes #4210. 

## Findings

Here is the video of the bug again for reference: 

https://user-images.githubusercontent.com/198826/122105756-5eaca400-cdd6-11eb-9fe8-798439a0e35c.mov

I'm not ashamed to say that it took me more than a day to figure this out. 😆 Even then, I'm still not very confident that I understood the problem correctly. 

Anyway, what I can deduce is that this is a race condition. 

Currently, `VariationsListViewModel` [can dictate](https://github.com/woocommerce/woocommerce-android/blob/7fb7ebf3f3be3b6d6e4bf61893ef2354fe8e8995/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt#L127-L129) the number of variations to display in the Product Detail page. This can become a problem if `VariationsListViewModel` has [an outdated `Product`](https://github.com/woocommerce/woocommerce-android/blob/7fb7ebf3f3be3b6d6e4bf61893ef2354fe8e8995/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationListViewModel.kt#L83-L86).

The reason why it works _sometimes_ is that after the user generates a variation, we do 2 things. Call `saveAttributeChanges` and `variationRepository.createEmptyVariation`:

https://github.com/woocommerce/woocommerce-android/blob/7fb7ebf3f3be3b6d6e4bf61893ef2354fe8e8995/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt#L363-L376

It's not clear which one should go first. I don't think it matters(?). What's important to know is that `saveAttributeChanges` can eventually [update the product to the site and save the result in the local database](https://github.com/woocommerce/woocommerce-android/blob/7fb7ebf3f3be3b6d6e4bf61893ef2354fe8e8995/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailRepository.kt#L238-L248), which is a `Product`. That latest `Product` can sometimes have the correct  [`numVariations`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/2dc146171e0ffa7537ded242a6a5a8376359909b/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductModel.kt#L389-L407). Sometimes it doesn't. This all depends on whether `createEmptyVariation` finishes first before `saveAttributesChanges`. 

image

If `createEmptyVariation` finishes first, the site's `numVariations` will be correct. And so we'll present the correct number all the time.

## Solution

I considered whether `createEmptyVariation` should be executed first and then we'll wait before calling `saveAttributeChanges`. But that seems incorrect since modifying attributes has the potential to wreak havoc in the number of variations (p91TBi-3Oc-p2#comment-2369).

But it might still be worth it to implement a sequencing of `saveAttributeChanges → wait → createEmptyVariation`. I'll let @ThomazFB chime in on that. 

I ended up adding an API fetch of the most recent `Product` instead so we'll have the most accurate number of variations. And it'll be saved locally in the database. 

https://github.com/woocommerce/woocommerce-android/blob/98ae08c78b0bf0999290917dacbbb42e355a506d/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt#L372-L379

Please do let me know if there's a better way to do this. I'm missing a lot of context of how `ProductDetailViewModel` works. Not to mention it's been a while since I've written Kotlin/Android. 😅 

## Testing

1. Tap on Products tab → Big plus button. 
2. Choose Variable product. 
3. Add a variation. 
4. Add a global attribute and select multiple options. 
5. Add a local attribute and add multiple options. 
4. Follow the flow until one variation is generated. 
4. When you're navigated back to the Product List, tap on “Variations (1 variation)”.
5. Navigate back. 
8. Confirm that the Variations row is still showing 1 variation. 
9. Tap on “Variations (1 variation)“ again. 
10. Generate a new variation. 
11. Navigate back. 
12. The Variations row should show a total of 2 variations. 
13. Tap on the Variations row again. 
14. Delete a variation. 
15. Navigate back.
15. The Variations row should show a total of 1 variation. 

## Author Checklist

- [x] If it's feasible, I have added unit tests. 
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 1]
```diff
@@ -360,13 +360,22 @@ class ProductDetailViewModel @Inject constructor(
...
         launch {
             viewState.productDraft?.let { draft ->
                 variationRepository.createEmptyVariation(draft)
-                    ?.let { updateProductDraft(numVariation = draft.numVariations + 1) }
+                    ?.let {
+                        val fetchedProduct = productRepository.fetchProduct(draft.remoteId)
+                        if (fetchedProduct != null) {
+                            updateProductState(productToUpdateFrom = fetchedProduct)
+                        }
+                    }
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt]: np: I think we would benefit of using a pipe operation for each of these steps to keep nullability handling in check individually, WDYT? Something like this:
```suggestion
                    ?.let { productRepository.fetchProduct(draft.remoteId) }
                    ?.let { updateProductState(productToUpdateFrom = it) }
```

**Comment by ThomazFB** [comment]
Impressive investigation and problem solving @shiki, thank you so much for taking your time to do this. The feature is working perfectly and I used your fix already to create the feature video demo without running into issues 😆, great work!

I just left a small note as a refactoring suggestion, let me know what you think about!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt (hunk 1 above)
Comment (shiki) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt]: @ThomazFB So I tested this and it looks like using this chain will result in different behavior. If `productRepository.fetchProduct` fails for some reason and returns `null`, then we would be triggering `ExitProductAttributeList` with **`variationsCreated` set to `false`**.

https://github.com/woocommerce/woocommerce-android/blob/98ae08c78b0bf0999290917dacbbb42e355a506d/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt#L380

And that will navigate the user _back_ instead of navigating them to the product detail page. 

I think this is not ideal and it's better to still navigate the user to the product detail page even if  `productRepository.fetchProduct` fails. What do you think? How can I present this logic using `?.let` or another magical chaining? 😄

**Comment by shiki** [comment]
@ThomazFB Thanks for reviewing! I responded to your comment. Let me know what you suggest!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt (hunk 1 above)
Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt]: I see, in that case, the only improvement I see is that we could avoid the direct `!= null` comparison just for syntax cohesion and use the `also` function as the side result operation from the `fetchProduct` call. Something like this maybe:

```
            viewState.productDraft?.let { draft ->
                variationRepository.createEmptyVariation(draft)
                    ?.let {
                        productRepository.fetchProduct(draft.remoteId)
                            ?.also { updateProductState(productToUpdateFrom = it) }
                        triggerEvent(ExitProductAttributeList(variationCreated = true))
                    } ?: triggerEvent(ExitProductAttributeList())
            }.also {
                attributeListViewState = attributeListViewState.copy(isCreatingVariationDialogShown = false)
            }
``` 

WDYT? I'm fine if you want to leave as it is too, I guess I'm being too nitpicky about this 😅

**Comment by ThomazFB** [comment]
just replied to your comment @shiki! Thanks for taking your time to reply, I'm good if you want to keep it as it is too! Let me know what you think.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt (hunk 1 above)
Comment (shiki) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt]: Ooh cool. Applied in 40f60b441a8f2c185ef90684187e4dff400a5d17.

>  I guess I'm being too nitpicky about this

Not at all. I'm rusty so I appreciate getting introduced to new things.

**Review by shiki — COMMENTED** [review]
@ThomazFB This is ready for another round!

**Review by ThomazFB — APPROVED** [review]
Nice, @shiki! Thanks for submitting my suggestions! LGTM :shipit:
