### PR TITLE
Fix the layout issue in the Woo update dialog

### LINKED ISSUE #13843: Update Woo dialog UI is broken
Image

* Too wide on a tablet
* Buttons I'd assume should be either 1/2 or wrap content
* Not sure that Dismiss must be a primary button

### PR DESCRIPTION
**Pull request by irfano**
Closes: #13843

### Description

This fixes the layout issue in the Woo update dialog, which was broken on tablets. I migrated the dialog to Compose and resolved the issue. This PR also updates the dialog’s style to align with the current design used in the app.

### Steps to reproduce

- Apply this patch to force the dialog: [Force_update_Woo_dialog.patch](https://github.com/user-attachments/files/19476992/Force_update_Woo_dialog.patch)
- Log in and open the site picker screen.

### The tests that have been performed

Steps above and screens below.

### Images/gif

|Before|After||
|-|-|-|
|||
||||

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialogFragment.kt [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+                            dismiss()
+                        }
+                    )
+                }
+            }
+        }
+
+        return Dialog(requireContext()).apply {
+            setContentView(composeView)
+            setCancelable(false)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialogFragment.kt]: np, this would create two dialogs (ie two windows), Compose's `AlertDialog` will create its own dialog, and we are creating another one here.

I'm just sharing this, I don't think it's a blocker, and I think the simplicity of the current solution.
Also, since this dialog is rarely (if at all) is shown, it's not an issue.

**Review by hichamboushaba — APPROVED** [review]
Thanks for fixing this @irfano 👍

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialogFragment.kt (hunk 1 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/WooUpgradeRequiredDialogFragment.kt]: Good catch @hichamboushaba! I’ve implemented a better solution by using a `ComposeView` in the `SitePickerFragment`. The `WooUpgradeDialog` remains the same, I simply removed the dialog fragment and integrated this composable dialog directly into the `SitePickerFragment`.
