### PR TITLE
Fix variations ANR

### LINKED ISSUE #4626: ApplicationNotResponding: ANR when loading cached variation.
Sentry Issue: [WOOCOMMERCE-ANDROID-20V](https://sentry.io/organizations/a8c/issues/2541455688/?referrer=github_integration)

```
ApplicationNotResponding: Application Not Responding for at least 5000 ms.
    at com.woocommerce.android.ui.products.variations.VariationDetailRepository.getCachedWCVariation(VariationDetailRepository.kt:102)
    at com.woocommerce.android.ui.products.variations.VariationDetailRepository.getVariation(VariationDetailRepository.kt:105)
    at com.woocommerce.android.ui.products.variations.VariationDetailViewModel$loadVariation$1.invokeSuspend(VariationDetailViewModel.kt:319)
    at com.woocommerce.android.ui.products.variations.VariationDetailViewModel.loadVariation(VariationDetailViewModel.kt:318)
    at com.woocommerce.android.ui.products.variations.VariationDetailViewModel.getOriginalVariation(VariationDetailViewModel.kt:72)
...
(57 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #4626 

### Description
This PR just updates `VariationDetailRepository#getVariation` to be suspendable, to avoid accessing the DB on the main thread, which was causing an ANR.
Most of the parts calling `getVariation` were already suspendable, so this didn't require a lot of changes.

### Testing instructions
Smoke test the following:
1. Variation details, and changing attributes.
2. Making modifications to shipping label packages that use variations.
3. Adding a variation in the Order Creation form. 

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesViewModel.kt [hunk 1]
```diff
@@ -83,9 +86,9 @@ class EditVariationAttributesViewModel @Inject constructor(
             }
         }
 
-    private fun List<ProductAttribute>.pairAttributeWithSelectedOption() =
+    private suspend fun List<ProductAttribute>.pairAttributeWithSelectedOption() =
         mapNotNull { attribute ->
-            selectedVariation?.attributes
+            selectedVariationDeferred.await()?.attributes
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesViewModel.kt:90]: Another way to implement this is to use a local variable instead of the property, but it would mean re-accessing the DB on each call to `pairAttributeWithSelectedOption`.
I opted for the usage of `async(start = LAZY)`, as it is the recommended approach to replace `by lazy` https://github.com/Kotlin/kotlinx.coroutines/issues/706#issuecomment-429922811

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesViewModel.kt [hunk 2]
```diff
@@ -34,14 +36,14 @@ class EditVariationAttributesViewModel @Inject constructor(
...
+    private val selectedVariationDeferred = async(start = LAZY) {
+        variationRepository.getVariation(
             viewState.parentProductID,
             viewState.editableVariationID
         )
+    }
 
-    private val parentProduct
-        get() = productRepository.getProduct(viewState.parentProductID)
+    private val parentProduct by lazy { productRepository.getProduct(viewState.parentProductID) }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/attributes/edit/EditVariationAttributesViewModel.kt:46]: This is unrelated to this PR, but it's an improvement to avoid hitting the DB on each access of the `parentProduct` property

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt [hunk 3]
```diff
@@ -319,6 +319,7 @@ class VariationDetailViewModel @Inject constructor(
             val variationInDb = variationRepository.getVariation(remoteProductId, remoteVariationId)
             if (variationInDb != null) {
                 originalVariation = variationInDb
+                showVariation(variationInDb)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt:323]: This was needed as the first call to `showVariation` here: https://github.com/woocommerce/woocommerce-android/blob/e19446af77be5dbbd7149a79769bfc26fa2f27eb/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt#L112-L114 won't get called, since `originalVariation` will be `null` on first instantiation of the ViewModel, because of the asyncronisity of `getVariation`, this resulted in a small delay before showing some parts of the screen, as the next call for `showVariation` was done after calling `fetchVariation`.

But in all cases, this should be temporary, we will need to update the logic a bit to avoid having to cache `originalVariation` in the `SavedState` as part of #5993, which means a different way to approach showing the variation.

**Comment by nbradbury** [comment]
@hichamboushaba Sorry to take a while to get to this after assigning myself. For some reason this PR was failing with:

```
Manifest merger failed with multiple errors, see logs
Duplicate class android.support.v4.app.INotificationSideChannel found in 
modules core-1.5.0-runtime (androidx.core:core:1.5.0) and 
support-compat-28.0.0-runtime (com.android.support:support-compat:28.0.0)
```

That made no sense to me since this PR makes no changes to the manifest, and `trunk` builds just fine. After a lot of attempts to resolve this, I changed `android.enableJetifier=false` to `true` and it worked.

I'm stumped as to why this was necessary, but thought I'd mention it. I'll get on with my review now!

**Update:** Okay, ignore all that. I had pulled  an earlier PR - #4963 - which had the same issue number 🤦

**Review by nbradbury — APPROVED** [review]
Nice work, all good! :shipit:
