### PR TITLE
 Fix payment selection landscape mode

### LINKED ISSUE #6933: [IPP] `Payment Gateway Selection` screen issues in landscape mode.
**Describe the bug**

There are a few issues I stumbled upon in this screen, when it was in landscape mode:

- The icon for `WCPay` is missing (both themes).
- The `Confirm Payment Method` button is located at the same distance from the payment methods buttons. It's fine for portrait mode, but not as user-friendly in landscape, because the merchant might not even guess that the button is there below, and will wonder why tapping the WCPay / Stripe cells results in nothing.
- [Possibly by design] The "card-in-hand" icon that is shown in portrait mode is absent in landscape mode.

https://user-images.githubusercontent.com/73365754/178713555-990c1bf1-8002-4dd6-9c73-5421d937e296.mp4

**To Reproduce**

1. Rotate the device to landscape mode
2. Tap `In-Person Payments` in `Settings`

**Expected behavior**
Obviously, the WCPay icon should be visible, and preferably, the need to scroll in order to see the `Confirm Payment Method` button should be minimized.

**Mobile Environment**
Please include:
- Device: Samsung A31
- Android version: 11
- WooCommerce Android version: 9.6-rc-1

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #6933 

### Description

It fixes the missing WCPay, checkmark and card holding icons. 
It also decreases the space between the Confirm Payment button in landscape mode
context: [p5T066-3oX-p2](p5T066-3oX-p2#comment-12931)

### Testing instructions

1. Log into a US-based site with both Stripe and WCPay installed
2. Go to the Menu
3. IPP settings
4. Test the Payment selection screen in landscape mode
5. make sure the WCPay, checkmark and the card holding hand icon are displayed
6. make sure the space between the confirm payment button is not too big and does not require a lot of scrolling
7. test the screen on other devices 

## Pixel 4
 

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt [hunk 1]
```diff
@@ -122,9 +122,9 @@ class CardReaderOnboardingFragment : BaseFragment(R.layout.fragment_card_reader_
         UiHelpers.setTextOrHide(binding.selectWcPayButton, state.selectWcPayButtonLabel)
         UiHelpers.setTextOrHide(binding.selectStripeButton, state.selectStripeButtonLabel)
         UiHelpers.setTextOrHide(binding.confirmPaymentMethod, state.confirmPaymentMethodButtonLabel)
-        UiHelpers.setImageOrHideInLandscape(binding.cardIllustration, state.cardIllustration)
-        UiHelpers.setImageOrHideInLandscape(binding.icSelectWcPay, state.icWcPayLogo)
-        UiHelpers.setImageOrHideInLandscape(binding.icCheckmarkWcPay, state.icCheckmarkWcPay)
+        binding.cardIllustration.setImageResource(state.cardIllustration)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/cardreader/onboarding/CardReaderOnboardingFragment.kt:125]: 👍

File: WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml [hunk 2]
```diff
@@ -103,7 +103,7 @@
         android:layout_height="@dimen/image_major_72"
         android:layout_marginStart="@dimen/major_100"
         android:layout_marginEnd="@dimen/major_100"
-        android:layout_marginBottom="@dimen/skeleton_text_large_width"
+        android:layout_marginBottom="@dimen/major_200"
```
Comment (kidinov) [inline WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml:101]: Noticed this:

image

In order to fix this, we probably need to remove the padding from scrollview in `fragment_card_reader_onboarding` and add margins to all the layouts we put inside, but probably address this in another PR

File: WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml [hunk 3]
```diff
@@ -148,6 +148,7 @@
         android:layout_width="match_parent"
         android:layout_height="wrap_content"
         android:layout_marginStart="@dimen/major_100"
+        android:layout_marginTop="@dimen/major_200"
```
Comment (kidinov) [inline WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml]: On a small screens we push the button way too down, while it probably not necessary 

image

This happens because we constraint `confirmPaymentMethod` and `selectStripeButton` to each other. We might consider  removing this from `confirmPaymentMethod`, so it will be always down on the screen (when possible)

```
android:layout_marginTop="@dimen/major_200"
app:layout_constraintTop_toBottomOf="@+id/selectStripeButton"
```

Comment (kidinov) [reply WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml]: And I think because of the similar approach it won't look good on a big screen:

image

I think we should build the constraints here in the following way:

* Constraint this block to the top while keeping a fixed margin between elements of the block:

image

* This is in between (in the center?)  the bottom button and the top block (a fixed margin between elements of the block):

image

* And the bottom just to the bottom:

Fill free to ping me tomorrow if you want to jump on a call so we can pair on that together!

**Review by kidinov — COMMENTED** [review]
I left some comments which are more generic suggestions to the layout, so please feel free to merge that and address, if you think this worth that, them latter

File: WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml (hunk 2 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml:101]: I will create a separate issue for this one :D

File: WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml (hunk 3 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml]: > This happens because we constraint confirmPaymentMethod and selectStripeButton to each other. We might consider removing this from confirmPaymentMethod, so it will be always down on the screen (when possible)

Thank you @kidinov ! I have fixed this one. The second comment I will ping you tomorrow so we can do it together 🤯

File: WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml (hunk 2 above)
Comment (rossanafmenezes) [reply WooCommerce/src/main/res/layout/fragment_card_reader_onboarding_select_payment_gateway.xml:101]: Created new issue here #6960

**Review by kidinov — APPROVED** [review]
