### PR TITLE
issue/4390-payment-gray-heading-lollipop

### LINKED ISSUE #4390: [Card Present Payments] Grey background on Android 5
**Describe the bug**
There is a grey background shown on Android 5 emulator on the card present payment payment flow (perhaps even the connection flow?)

**To Reproduce**
1. Open detail of an unpaid order in US dollars (make sure you site is eligible for in person payments)
2. Click on 'collect payment'
3. See the issue

**Screenshots**

**Mobile Environment**
Please include:
- Device: Emulator
- Android version: Android 5
- WooCommerce Android version: develop

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4390 by removing the title from `CardReaderConnectFragment` and `CardReaderPaymentDialog`.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt [hunk 1]
```diff
@@ -30,7 +31,10 @@ class CardReaderPaymentDialog : DialogFragment(R.layout.fragment_card_reader_pay
     @Inject lateinit var uiMessageResolver: UIMessageResolver
 
     override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
-        dialog!!.setCanceledOnTouchOutside(false)
+        dialog?.let {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/cardreader/CardReaderPaymentDialog.kt:34]: I think using `require/!!` is more appropriate here - we don't expect it to be null and if it is null the app is in a very weird state so crashing fast so the issue propagates to us (Sentry) is imho the most reasonable reaction. Wdyt?

P.S. I merging this PR since it fixes this issue and this comment is very minor.

**Review by malinajirka — APPROVED** [review]
LGTM, thanks!
