### PR TITLE
Crash removing products in Order Creation

### LINKED ISSUE #6456: Crash when removing a product that is not synced
**Describe the bug**
When adding a product to an Order in a slow connection, if we select the product before the Order is synced with the API and try to remove this product after the Order is synced, the app will crash because the **product itemId not synced (0)** will not match with the **product itemId synced**.

**To Reproduce**
1. Go to Orders -> Tap on (+) -> Create new order
2. Tap on Add product
3. Select a product, and before the Order is synced, tap on the product again
4. Wait a few seconds to let the order sync
5. Remove the product
6. Check that the app crashed with the error  `java.lang.IllegalStateException: Couldn't find the product with id 0`

**Screenshots**

https://user-images.githubusercontent.com/18119390/167161196-0c3720e8-8fe9-4ec3-a814-15abe5df584b.mp4

**Expected behavior**
The app doesn't crash removing products.

**Discussion**
p1651792618849919-slack-C02KUCFCSFP

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #6456

### Description
When adding a product to an Order in a slow connection, if we select the product before the Order is synced with the API and try to remove this product after the Order is synced, the app will crash because the **product itemId not synced** (0) will not match with the **product itemId synced**. To prevent this, now the app shows the product detail only to synced items.

### Testing instructions

1. Go to Orders -> Tap on (+) -> Create new order
2. Tap on Add product
3. Select a product, and before the Order is synced, tap on the product again
4. Check that the product is not clickable until the Order is synced.
5. Run tests in OrderCreationViewModelTest

### Images/gif

https://user-images.githubusercontent.com/18119390/167167188-39884664-df97-46e1-88ca-583ba769893c.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt [hunk 1]
```diff
@@ -360,3 +363,5 @@ data class ProductUIModel(
     val stockQuantity: Double,
     val stockStatus: ProductStockStatus
 )
+
+fun Order.Item.isSynced() = this.itemId != 0L
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModel.kt:367]: nice one!

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModelTest.kt [hunk 2]
```diff
@@ -672,6 +672,38 @@ class OrderCreationViewModelTest : BaseUnitTest() {
...
+
+        assertThat(lastReceivedEvent).isNotNull
+        lastReceivedEvent
+            .run { this as? ShowProductDetails }
+            ?.let { showProductDetailsEvent ->
+                val currentOrderItem = showProductDetailsEvent.item
+                assertThat(currentOrderItem).isEqualTo(orderItem)
+            } ?: fail("Last event should be of ShowProductDetails type")
+    }
+
```
Comment (ThomazFB) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/orders/creation/OrderCreationViewModelTest.kt:706]: Thanks for adding tests to cover this new constraint! Great work!

**Review by ThomazFB — APPROVED** [review]
Awesome work, @atorresveiga! Thanks for tackling this fix, the `isSynced` strategy works really well and blocks only non-synced products instead of the entire Product section, nicely done! :shipit:
