### PR TITLE
POS - Fix "Key already in use" crash

### LINKED ISSUE #13837: [Woo POS] Key ".." was already in use exception
**Describe the bug**
Add tens of products to the cart as fast as you can until the app crashes.

**To Reproduce**
1. Go to More section on a tablet with US/UK store
2. Click on Point of Sale
3. Start adding as many products as fast as you can
4. See crash

```Process: com.woocommerce.android.dev, PID: 1227
                                                                                                    java.lang.IllegalArgumentException: Key "101" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:453)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:895)
                                                                                                    	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:125)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw(LazyListMeasuredItemProvider.kt:55)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:49)
                                                                                                    	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-x0Ok8Vo(LazyListMeasure.kt:214)
```

**Expected behavior**
The app doesn't crash and all the products are added to the cart.

### PR DESCRIPTION
**Pull request by malinajirka**
Closes: #13837

### Description

This PR fixes a rare crash that occurs when the user adds a product (usually many products) to the cart.

### Steps to reproduce

1. Go to More section on a tablet with US/UK store
1. Click on Point of Sale
1. Start adding as many products as fast as you can
1. Observe the app crashes at some point

### Testing information

Smoke test the POS with focus on adding products to the cart. Also test the VM restoration works as expected. (P.S. I noticed the app sometime restarts from scratch, but I don't know why - doesn't seem to be related to this PR, since it was happening even before).

### The tests that have been performed

I've tested the above with `Don't keep activities` developer settings enabled.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt [hunk 1]
```diff
@@ -61,6 +62,13 @@ class WooPosCartViewModel @Inject constructor(
         .map { updateToolbarState(it) }
         .map { updateStateDependingOnCartStatus(it) }
 
+    // Set initial value to 1 or the biggest used number when VM is restored after a process death.
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: np: this comment doesn't give any more information than the code bellow, maybe we don't need this? If naming is needed to extra this to a method

```
    private fun goodNaming(): Int = (_state.value.body as? WooPosCartState.Body.WithItems)
        ?.itemsInCart?.maxOfOrNull { it.itemNumber } ?: 1
```
wdyt?

**Review by kidinov — APPROVED** [review]
I tested an it looks like it fixes the issue. I left one np, feel free to merge!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt (hunk 1 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/home/cart/WooPosCartViewModel.kt]: I see what you mean and I'm not a fan of comments either. However, in this case reasoning about the code isn't that straightforward (at least to me, anyway :P ).

When you want to understand what the code does, you need to:
- Understand that the value passed in is only `initialValue`
- Understand that `_state.value....` is null, unless it's after the process death
- Understand that itemsInCart.item.itemNumber returns values that were provided before the process death iteratively to each item.


I've updated this in 9d9cbb35e19a71f96157d9c8022925e6ce217337, however, in this case I think a comment might be a better solution. Anyway, not very important, so let's move on :).
