### PR TITLE
Use line_item id as unique identifier when displaying products

### LINKED ISSUE #3811: Variable product quantity show only 1 in order details
**Describe the bug**
This bug does not happen all the time, it has happened to me twice so far (within a month).
When a product variation is purchased with an amount of more than 1, in the mobile app only 1 is shown as the quantity.
(as you can see in screenshots).

**Screenshots**
k_mob

k_desk

**Expected behavior**
show the right quantity of the item that has been purchased.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Oneplus 6T, Samsung galaxy 9
- Android version: 10
- WooCommerce Android version: 6.2, 6.3

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): ***
Site address (URL): ***
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.16
PHP Post Max Size: 2 GB
PHP Time Limit: 3600
PHP Max Input Vars: 9000
cURL Version: 7.75.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.18-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 142.44MB
Database Data Size: 98.99MB
Database Index Size: 43.45MB
wp_woocommerce_sessions: Data: 0.38MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.39MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 5.02MB + Index: 1.33MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.34MB + Index: 1.89MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_db7_forms: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_crawler: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_crawler_blacklist: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_cssjs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 26.08MB + Index: 4.13MB + Engine InnoDB
wp_postmeta: Data: 34.45MB + Index: 15.69MB + Engine InnoDB
wp_posts: Data: 9.34MB + Index: 4.73MB + Engine InnoDB
wp_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.42MB + Index: 0.47MB + Engine InnoDB
wp_terms: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_term_relationships: Data: 1.44MB + Index: 0.39MB + Engine InnoDB
wp_term_taxonomy: Data: 0.33MB + Index: 0.41MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.39MB + Index: 0.64MB + Engine InnoDB
wp_wc_order_stats: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.45MB + Index: 0.73MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 9.52MB + Index: 5.23MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.44MB + Index: 0.47MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.44MB + Index: 0.48MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 19
acf-field-group: 7
attachment: 9152
dt_gallery: 24
dt_logos: 10
dt_slideshow: 3
dt_testimonials: 12
nav_menu_item: 166
oembed_cache: 9
page: 25
post: 160
product: 2259
product_variation: 3937
revision: 37
shop_order: 761
vc_grid_item: 5
vc_settings_preset: 1
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

The7 Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.9
Advanced Custom Fields: by Elliot Condon – 5.9.5
FiboSearch - AJAX Search for WooCommerce: by Damian Góra – 1.9.0
Async JavaScript: by Frank Goossens (futtta) – 2.20.12.09
Classic Editor: by WordPress Contributors – 1.6
Combar Plugins Package: by  – 0.9.5
Contact Form 7: by Takayuki Miyoshi – 5.4
Contact Form CFDB7: by Arshid – 1.2.5.9
The7 Elements: by Dream-Theme – 2.5.6
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2
Facebook for WooCommerce: by Facebook – 2.3.4
Invisible reCaptcha: by Mihai Chelaru – 1.2.3
Jetpack by WordPress.com: by Automattic – 9.5
The7 WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.20.6
LiteSpeed Cache: by LiteSpeed Technologies – 3.6.4
WooCommerce Load More Products: by BeRocket – 1.1.8
Merge + Minify + Refresh: by Launch Interactive – 1.12.1
The7 disable web fonts: by Dream Theme – 1.0.1
Compress JPEG & PNG images: by TinyPNG – 3.2.1
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.13
Gobit  Tranzilla: by Gobit software – 5.0.9
WooCommerce: by Automattic – 5.1.0
Yoast SEO: by Team Yoast – 16.0.2
WP Sitemap Page: by Tony Archambeau – 1.6.4

### Inactive Plugins (2) ###

Redirection: by John Godley – 5.0.1
YITH WooCommerce Catalog Mode: by YITH – 2.0.11

### Dropin Plugins (1) ###

object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2511 - /shop/
Cart: #2512 - /cart/
Checkout: #2513 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: #5409 - /terms/

### Theme ###

Name: the7dtchild
Version: 1.0.0
Author URL: http://dream-theme.com/
Child Theme: ✔
Parent Theme Name: The7
Parent Theme Version: 9.9.1
Parent Theme Author URL: http://dream-theme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/cart/mini-cart.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7-child/woocommerce/content-product.php
dt-the7/woocommerce/content-widget-product.php
dt-the7/woocommerce/content-widget-reviews.php
dt-the7-child/woocommerce/emails/admin-new-order.php
dt-the7-child/woocommerce/emails/customer-completed-order.php
dt-the7-child/woocommerce/emails/customer-on-hold-order.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/pagination.php
dt-the7-child/woocommerce/loop/result-count.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7-child/woocommerce/single-product/product-image.php
dt-the7-child/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php
dt-the7/woocommerce/content-product_cat.php

### Action Scheduler ###

Complete: 5,681
Oldest: 2021-03-06 14:29:37 +0200
Newest: 2021-04-06 15:26:19 +0300

Pending: 2
Oldest: 2021-04-06 15:27:44 +0300
Newest: 2021-04-06 15:39:30 +0300

### Status report information ###

Generated at: 2021-04-06 15:27:21 +03:00
</details>

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3811. There have been a few complaints from some merchants that the quantity displayed in the Order detail screen for variable products is incorrect. I was not able to reproduce this issue from my own test site but had to SSP into another site to reproduce it.

It seems that for a particular order, there are two variable products with quantity 2 and 1 respectively. But the app is displaying both products are 1. This was because the `variation_id` of both the products were the same. This was causing the incorrect quantity issue when we [were fetching non refunded products for display](https://github.com/woocommerce/woocommerce-android/blob/98b122bfe96ce34babf3d47f36d47483bec7d7a4/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt#L146).

I updated the logic to use the `line_item.id` instead of the `line_item.unique_id` since it looks like the `variation_id` is not unique. I didn't face any issues when testing the order detail screen for different scenarios so I assume everything is working correctly. But would like to get some feedback from reviewers to verify that everything is working fine. 

#### To test the original issue
- SSP into this [site](https://github.com/woocommerce/woocommerce-android/issues/3811#issuecomment-846451639). Please DM me for more details.
- Click on the Orders TAB and search for order number 2269.
- Notice that the product list displays the correct quantity (as sent from the API).

#### Smoke Testing
Since this change modifies the unique identifier we use in the app, it would be nice to test the following features. **Please perform these sites from your own test site.**:
- Try refunding an entire order and verify that the product list is not displayed. 
- Try refunding a product from an order that contains atleast 2 products. Verify that the product list displays the correct details.
- Try refunding orders that contain variable products, physical products and virtual products.

cc @nbradbury @hichamboushaba I assigned the PR to both of you because I thought you might have more context around order details and refunds in general :) 

I think this fix might be worth including in the new beta releasing today. cc @jkmassel since you will be taking care of the beta release this sprint 😄 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hichamboushaba — APPROVED** [review]
Tested and I confirm it works, thank @anitaa1990 for the fix :shipit:

**Comment by hichamboushaba** [comment]
Please hold on merging the PR, I will test the refund flow to confirm that it works as expected

**Review by hichamboushaba — CHANGES_REQUESTED** [review]
So this fixed the issue with quantities in the order details, but I can't see the items in the refund screen: 
Screen Shot 2021-06-14 at 12 00 38

I think the cause is that we are still relying on `uniqueId` in the `IssueRefundViewModel`.

**Comment by anitaa1990** [comment]
Thanks for the review @hichamboushaba! It looks like there are 14 places in the app where `unique_id` is being used, including refunds and shipping labels. Do you think we want to migrate all of that to `item_id` instead?

**Comment by anitaa1990** [comment]
huh, I just noticed that for shipping labels, the `productIds` [here](https://github.com/woocommerce/woocommerce-android/blob/b4839dca08fd8e5402f006a081c97a823aa693e1/WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabel.kt#L116) will be the `product_id` or the `variation_id` and there's a chance that we wouldn't be displaying all the product variations for that order

**Comment by hichamboushaba** [comment]
> Thanks for the review @hichamboushaba! It looks like there are 14 places in the app where `unique_id` is being used, including refunds and shipping labels. Do you think we want to migrate all of that to `item_id` instead? 

No, I think this is pretty specific to this flow: mapping items to refunds and substracting quantites, for everything else where we need the product or variation, we should keep using the uniqueId.

**Comment by hichamboushaba** [comment]
> huh, I just noticed that for shipping labels, the `productIds` [here](https://github.com/woocommerce/woocommerce-android/blob/b4839dca08fd8e5402f006a081c97a823aa693e1/WooCommerce/src/main/kotlin/com/woocommerce/android/model/ShippingLabel.kt#L116) will be the `product_id` or the `variation_id` and there's a chance that we wouldn't be displaying all the product variations for that order

We don't need to change anything here, the product is still mapped correctly: 
Screen Shot 2021-06-14 at 12 19 13

**Comment by hichamboushaba** [comment]
@anitaa1990 After thinking more about the issue, I think the fix would require more work than just using `item_id` instead of `uniqueId`, the cause is that the Refund.Item's `id` is different from Order.Item's `itemId`, so we can't use it for the mapping, we need instead to rely on a meta data item that's send with the API response that has `_refunded_item_id`: 
```
"line_items": [
				{
					"id": 230,
					"name": "Cap",
					"product_id": 45,
					"variation_id": 0,
					"quantity": -1,
					"tax_class": "",
					"subtotal": "-16.000",
					"subtotal_tax": "-3.200",
					"total": "-16.000",
					"total_tax": "-3.200",
					"taxes": [
						{
							"id": 1,
							"total": "-3.2",
							"subtotal": "-3.2"
						}
					],
					"meta_data": [
						{
							"id": 1779,
							"key": "_refunded_item_id",
							"value": "227",
							"display_key": "_refunded_item_id",
							"display_value": "227"
						}
					],
					"sku": "woo-cap",
					"price": 16,
					"parent_name": null
				}
			]
```
This should be similar to what was done with the shipping line refund here: https://github.com/woocommerce/woocommerce-android/blob/90731d48acb614aaaac8e9f8ddd9f008ece0daea/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt#L119-L127

**Comment by anitaa1990** [comment]
> @anitaa1990 After thinking more about the issue, I think the fix would require more work than just using item_id instead of uniqueId, the cause is that the Refund.Item's id is different from Order.Item's itemId, so we can't use it for the mapping, we need instead to rely on a meta data item that's send with the API response that has _refunded_item_id:

Thanks for the insight @hichamboushaba ! I just got to that part where I realised my fix won't work if the order contains refunded products 😥 I'll modify the fix to use `_refunded_item_id` and see how that works!

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt [hunk 1]
```diff
@@ -33,7 +33,8 @@ data class Refund(
         val total: BigDecimal = BigDecimal.ZERO,
         val totalTax: BigDecimal = BigDecimal.ZERO,
         val sku: String = "",
-        val price: BigDecimal = BigDecimal.ZERO
+        val price: BigDecimal = BigDecimal.ZERO,
+        val refundId: Long = 0
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt]: np, I would call this something clearer, like: `orderItemId`, WDYT?

**Review by hichamboushaba — COMMENTED** [review]
Looks good, I tested the functionality, and everything seems to work without issues.
I left on np comment regarding the naming of the property `refundId`, and there are some broken tests, once all fixed we can merge it.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt (hunk 1 above)
Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/model/Refund.kt]: Good point! Fixed in d58a93c 👍

**Comment by anitaa1990** [comment]
Thanks for the review @hichamboushaba! I fixed the nitpick and updated the FluxC hash and the fixed the failing unit test. Ready for another round!

**Review by hichamboushaba — APPROVED** [review]
Looks good, thanks for working on this @anitaa1990 👍 
FYI I enabled auto-merge for this
