### PR TITLE
[Dynamic Dashboard] Fix padding + fix JITM announcements

### LINKED ISSUE #13603: [Dashboard] JITM fragment is not shown
After the work on the dynamic dashboard, it seems we unintentionally broke the JITM fragment visibility, and it's now hidden always.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #13603

### Description
Fix two issues with the Dynamic Dashboard:
1. Ensures the JITM fragment is correctly initialized when needed, the issue was caused by our changes for the dynamic dashboard. The good news is that it seems we don't have any active JITM messages (Check the JITM dashboard), so hopefully this didn't have any production impact. (07e0f193fde619cc946b4798d27f4595c6bcacac)
2. Fixes the padding in the screen to avoid having a white space when scrolling, this was reported [here](https://github.com/woocommerce/woocommerce-android/pull/13590#pullrequestreview-2630831534) (74597ac3f775fee89654277743e5a1e92c345cd0 and 70b2302584ff4c838bc10d4de742167d3a41273a)

### Steps to reproduce
1. Add the following line to your `developer.properties` file (create one if it's missing):
```
wc.jitm_testing_json_file_name = jitm_testing.json
```
2. Launch the dashboard screen.

### Testing information
- Confirm the JITM fragment is shown (the example will show an IPP banner)
- Confirm there is now white spacing around the dashboard widgets (both when the JITM banner is shown and it's dismissed)

### The tests that have been performed
^

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/251">21.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt [hunk 1]
```diff
@@ -111,6 +111,7 @@ private fun DashboardWidgets(
                 .verticalScroll(rememberScrollState()),
             verticalArrangement = Arrangement.spacedBy(16.dp),
         ) {
+            Spacer(modifier = Modifier)
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt:114]: We don't set a `height` here because the parent `Column` already uses `verticalArrangement` of 16.dp, which will already add the needed spacing below the Spacer.

Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/DashboardContainer.kt:114]: TIL about this trick for adding an empty layout to force the vertical spacing at the top and end of the column. Nice. It's a bit counterintuitive at first, but it works great!

**Review by JorgeMucientes — APPROVED** [review]
Everything works as expected and the code looks good. Thanks for addressing this @hichamboushaba
