### PR TITLE
Issue-5267. Android 12 support for IPP. New bluetooth runtime permission

### LINKED ISSUE #5267: App crashes on android 12 during a reader connection
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

```
021-11-18 18:46:20.773 15180-15180/com.woocommerce.android.prealpha E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.prealpha, PID: 15180
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{5bc84a3 15180:com.woocommerce.android.prealpha/u0a390} (pid=15180, uid=10390) requires android.permission.BLUETOOTH_CONNECT
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2284)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
        at android.app.Activity.startActivityForResult(Activity.java:5404)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:588)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:211)
        at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
        at androidx.fragment.app.Fragment$9.launch(Fragment.java:3507)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectDialogFragment.observeEvents$lambda-8(CardReaderConnectDialogFragment.kt:198)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectDialogFragment.lambda$1uV5SDVGRNZQs4NtrOiA14ljO1g(Unknown Source:0)
        at com.woocommerce.android.ui.prefs.cardreader.connect.-$$Lambda$CardReaderConnectDialogFragment$1uV5SDVGRNZQs4NtrOiA14ljO1g.onChanged(Unknown Source:4)
        at com.woocommerce.android.viewmodel.SingleLiveEvent.observe$lambda-0(SingleLiveEvent.kt:52)
        at com.woocommerce.android.viewmodel.SingleLiveEvent.lambda$B2zauqpeSz_VYlwmzDz5fdMAYi0(Unknown Source:0)
        at com.woocommerce.android.viewmodel.-$$Lambda$SingleLiveEvent$B2zauqpeSz_VYlwmzDz5fdMAYi0.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.woocommerce.android.viewmodel.SingleLiveEvent.setValue(SingleLiveEvent.kt:65)
        at com.woocommerce.android.viewmodel.ScopedViewModel.triggerEvent(ScopedViewModel.kt:29)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel.access$triggerEvent(CardReaderConnectViewModel.kt:68)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$checkOnboardingState$1.invokeSuspend(CardReaderConnectViewModel.kt:216)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1047)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:975)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:665)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1201)
2021-11-18 18:46:20.773 15180-15180/com.woocommerce.android.prealpha E/AndroidRuntime:     at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1173)
```

### LINKED ISSUE #5297: Update location and Bluetooth permissions handling.
The handling of bluetooth permissions is different for apps that are targeting Android 12, it [requires](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher) handling new runtime permissions now.

But even though this shouldn't impact the apps that don't target Android 12, the app crashes now when using an Android 12 device (check https://github.com/woocommerce/woocommerce-android/issues/5267#issuecomment-974652157).

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #5297
Closes: #5267

### Description

The PR adds handling of the new  `BLUETOOTH_SCAN` and `BLUETOOTH_CONNECT` runtime permission, so we are ready for targeting SDK 31.

The new connection flow is the following:
Check Location permission -> Check Location service enabled -> Check BT permission -> Check BT enabled

#### Run all possible permutations of
* Location permission given/not given + precise/approximate 
* Location given/not given
* BT permission given/not given
* BT enabled/disabled
**+**
* A device with Android 30 and lower 
* A device Android 31
**+**
* Target SDK 30 
* Target SDK 31 (change in the code and recompile)

**Keep in mind that Android returns true on BT permission check when the target SDK is 30, but you run it on the device with Android 12 even if the "Devices nearby" permission is disabled**

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt [hunk 1]
```diff
@@ -254,7 +275,11 @@ class CardReaderConnectDialogFragment : DialogFragment(R.layout.card_reader_conn
     override fun onResume() {
         super.onResume()
         AnalyticsTracker.trackViewShown(this)
-        viewModel.onScreenResumed()
+    }
+
+    override fun onStart() {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectDialogFragment.kt:280]: BT permission requests return calls `onResume` even when the permission is not given in the Settings. At the same time, it won't show anything to a user, because apparently android allows us to ask it via launcher only once per change in settings or per app installation. So it was calling stack overflow

File: libs/cardreader/src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -2,5 +2,7 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
     package="com.woocommerce.android.cardreader">
 
+    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
```
Comment (kidinov) [inline libs/cardreader/src/main/AndroidManifest.xml:5]: @malinajirka looking into [the google doc](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) they say we should have 

```
    <!-- Request legacy Bluetooth permissions on older devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH"
                     android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
                     android:maxSdkVersion="30" />
```

But we never had this. `BLUETOOTH` actually comes from tracks library, but I don't see `BLUETOOTH_ADMIN` at all. I'm wondering how does this work now then?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 3]
```diff
@@ -148,7 +151,7 @@ class CardReaderConnectViewModel @Inject constructor(
 
     private fun onCheckLocationEnabledResult(enabled: Boolean) {
         if (enabled) {
-            onLocationStateVerified()
+            triggerEvent(CheckBluetoothPermissionsGiven(::onCheckBluetoothPermissionsResult))
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt:154]: @AnirudhBhat I removed the check on if we running android S and higher from here. I think it should make things more straightforward and easier to test. Wdyt?

File: libs/cardreader/src/main/AndroidManifest.xml (hunk 2 above)
Comment (hichamboushaba) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: I spent some time tracking this when I was working on my PR, and it comes from the stripe SDK, the SDK includes all the required permissions, and they are merged to our Manifest as well
Screen Shot 2021-11-22 at 11 05 24

IMO for consistency and for more clarity, we should include the `BLUETOOTH` and `BLUETOOTH_ADMIN` permissions explicitly in the module too.

Comment (kidinov) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: @hichamboushaba Weirdly that I don't see that in the merged manifest:

image

and the BT permission comes from Automattic-tracks library

Comment (hichamboushaba) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: I noticed the same thing, but my guess is that it's a bug on the feature in Android Studio, if you check the built APK from any of our branches, even before the changes included in this PR, you'll notice that the AndroidManifest has this:
```
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN" />

    <uses-permission
        android:name="android.permission.BLUETOOTH_CONNECT" />

    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission
        android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />

    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />
```
So when I checked the dependency manually as in my above screenshot, I saw that it's coming from it.

Comment (kidinov) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: I agree with @hichamboushaba having permissions explicitly mentioned in the manifest of the module makes sense to me. @malinajirka wdyt?

**Comment by AnirudhBhat** [comment]
@kidinov I haven't started testing this PR (I will, shortly 🙂 ). However, I noticed that there aren't any unit tests in this PR. Do we want to include unit tests here or is that something you plan to include as a part of separate PR?

btw, Thank you for working on this!

**Comment by kidinov** [comment]
@AnirudhBhat there are new/adjusted unit tests in `CardReaderConnectViewModelTest.kt` file

**Comment by AnirudhBhat** [comment]
Oops, totally missed that file. Thank you!

**Comment by AnirudhBhat** [comment]
Thanks for working on this @kidinov I've tested this on Android 12 (target SDK 30 and 31) and Android 11. It seems to work as expected except for Bluetooth scanning fails for Android 12 when targeting SDK 30 when "Nearby devices permission is reviked" which we have decided to ignore since we are planning to move to SDK 31 in the next sprint here paqN3M-pE-p2#comment-744. 
The code changes look good to me as well.

**Comment by kidinov** [comment]
@AnirudhBhat thanks for the reviews! Let's see if @malinajirka won't recover till Friday, we have to merge that without his approval

File: libs/cardreader/src/main/AndroidManifest.xml (hunk 2 above)
Comment (malinajirka) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: I agree! :)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt [hunk 4]
```diff
@@ -169,34 +172,53 @@ class CardReaderConnectViewModel @Inject constructor(
...
+    private fun onOpenBluetoothPermissionsSettingsClicked() {
+        triggerEvent(OpenPermissionsSettings)
+    }
+
     private fun onOpenBluetoothSettingsClicked() {
         triggerEvent(RequestEnableBluetooth(::onRequestEnableBluetoothResult))
     }
 
-    private fun onBluetoothStateVerified() {
+    private fun onDeviceReaderToConnect() {
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt]: ❓ Possible typo? Should it be `ready` instead of `reader`?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt [hunk 5]
```diff
@@ -24,13 +27,24 @@ object WooPermissionUtils {
...
 
-    fun hasFineLocationPermission(context: Context): Boolean {
-        return ContextCompat.checkSelfPermission(
-            context, permission.ACCESS_FINE_LOCATION
-        ) == PackageManager.PERMISSION_GRANTED
-    }
+    fun hasFineLocationPermission(context: Context) = context.checkIfPermissionGiven(ACCESS_FINE_LOCATION)
+
+    fun hasBluetoothScanPermission(context: Context) =
+        context.checkIfPermissionGiven(BLUETOOTH_SCAN) || androidROrLower()
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt]: I'm wondering if we should swap these two conditions - it seems we'll be checking permissions which don't exist on Android R or lower -> I'm a bit worried it might bite us, especially on some custom ROMs which might not expect to receive a non-existing permission request. Wdyt? (same comment applies to the other methods)

**Review by malinajirka — APPROVED** [review]
Thanks for working on this! LGTM, I've left a couple comments.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt (hunk 4 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt]: Thanks! Fixed - bd3e6850940b50b2d87cf8bcacb2b3478686121b

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt (hunk 5 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/WooPermissionUtils.kt]: Yep, good point. Fixed - b1e50239026ade22ea985280cb1e06f24874e3ef

File: libs/cardreader/src/main/AndroidManifest.xml (hunk 2 above)
Comment (kidinov) [reply libs/cardreader/src/main/AndroidManifest.xml:5]: Done! b6dd675e0c29484573e232b3ddefe87d82160b86

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt (hunk 4 above)
Comment (malinajirka) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt]: 🔍 Nitpick: `onCardReaderReadyToConnect` evokes to me that the card reader is prepared -> but I believe that's not the case, we haven't started scanning yet, right? We might want to consider renaming it to something like`onReadyToStartScanning` or `onPreconditionsMet` or `onPreparedToStartScanning`. Wdyt?

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/prefs/cardreader/connect/CardReaderConnectViewModel.kt]: Agree! a8c1f8862754afdb9f3e9940e6b906a95591e914
