### PR TITLE
Fix duplicate year to date in date range selector

### LINKED ISSUE #7680: [Analytics Hub] Fix duplicate `Year to Date` in the date range selection
The `Year to Date` option in the date range selection of the Analytics Hub is showing twice

Image

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #7680 by removing the duplicate resource of the `Year to Date` text inside the Date Range selection.

Screenshots
==========
| Before  | After |
| ------------- | ------------- |
| Screenshot_20221028_140131 | Screenshot_20221028_164501 |

How to Test
==========
1. Simply verify if the duplication of the Year to date is gone

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/AnalyticsFragment.kt [hunk 1]
```diff
@@ -72,13 +73,15 @@ class AnalyticsFragment :
...
+        val ranges = getDateRangeSelectorViewState().availableRangeDates.toTypedArray()
+        return AnalyticsFragmentDirections.actionAnalyticsFragmentToDateRangeSelector(
             requestKey = KEY_DATE_RANGE_SELECTOR_RESULT,
-            keys = getDateRangeSelectorViewState().availableRangeDates.toTypedArray(),
-            values = getDateRangeSelectorViewState().availableRangeDates.toTypedArray(),
+            keys = ranges,
+            values = ranges,
             selectedItem = getDateRangeSelectorViewState().selectedPeriod
         )
+    }
```
Comment (ThomazFB) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/analytics/AnalyticsFragment.kt]: I tried to do the fix with a distinct here, but that would be suboptimal since it wouldn't fix the duplication source, instead, I reverted the distinct but kept the refactor to avoid calling all this viewState conversion twice.

**Review by nbradbury — APPROVED** [review]
Fix is good! :shipit:
