### PR TITLE
Fix: Selected site timezone crash

### LINKED ISSUE #9232: NullPointerException: selectedSite.timezone must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-740](https://a8c.sentry.io/issues/4251269895/?referrer=github_integration)

```
NullPointerException: selectedSite.timezone must not be null
    at com.woocommerce.android.ui.mystore.MyStoreViewModel.trackLocalTimezoneDifferenceFromStore(MyStoreViewModel.kt:337)
    at com.woocommerce.android.ui.mystore.MyStoreViewModel.<init>(MyStoreViewModel.kt:141)
    at com.woocommerce.android.DaggerWooCommerceRelease_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get0(DaggerWooCommerceRelease_HiltComponents_SingletonC.java:6076)
    at com.woocommerce.android.DaggerWooCommerceRelease_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerWooCommerceRelease_HiltComponents_SingletonC.java:6341)
    at com.woocommerce.android.ui.mystore.MyStoreFragment.getMyStoreViewModel(MyStoreFragment.kt:96)
...
(42 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #9232 by creating a check to the SelectedSite `timezone`, ensuring it's not null before operating its value.

It's unclear when the timezone can be nullified in a real scenario, but we should be resilient since the REST API can return null site data.

Steps to reproduce
==========
1. Force the `SiteModel` to contain a `null` timezone value
2. Open the app
3. Verify the app crashes in the My Store section

How to Test
==========
1. Force the `SiteModel` to contain a `null` timezone value
2. Open the app
3. Verify the app works as expected, and the timezone track is not triggered

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by atorresveiga — APPROVED** [review]
Everything is looking great!
LGTM! :shipit:

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt [hunk 1]
```diff
@@ -611,6 +611,32 @@ class MyStoreViewModelTest : BaseUnitTest() {
         )
     }
 
+    @Test
+    fun `given the viewModel started, when the store timezone is null, then do nothing`() = testBlocking {
```
Comment (atorresveiga) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/mystore/MyStoreViewModelTest.kt:615]: Nice!
