### PR TITLE
Fix crash when logging in with site address

### LINKED ISSUE #8056: Crash when login in with site address
**Describe the bug**

**Disclaimer**: this bug only affects users that have `FeatureFlag.REST_API` enabled in WooCommerce, which so far is only developers.

While reviewing [this hotfix](https://github.com/woocommerce/woocommerce-android/pull/8050), I noticed the users experience a similar issue when trying to log in using their site address if the site address contains suffixes like `wp-admin` or `wp-login.php`. When trying to match the entered site address with the `siteModelList` in this function from[ `SiteUtils` ](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/9e07c99bb1142c607d99cbdd0fee665a127f9251/WordPressLoginFlow/src/main/java/org/wordpress/android/login/util/SiteUtils.java)

```kotlin 
    @Nullable
    private static SiteModel getSiteByMatchingUrl(List<SiteModel> siteModelList, String url) {
        if (siteModelList != null && !siteModelList.isEmpty()) {
            for (SiteModel siteModel : siteModelList) {
                String storedSiteUrl = UrlUtils.removeScheme(siteModel.getUrl()).replace("/", "");
                String incomingSiteUrl = UrlUtils.removeScheme(url).replace("/", "");
                if (storedSiteUrl.equalsIgnoreCase(incomingSiteUrl)) {
                    return siteModel;
                }
            }
        }
        return null;
    }
```
There won't be any match and thus null will be returned. If null is returned this recently added code in WooCommerce crashes: 

```kotlin
    override fun onSiteChanged(event: OnSiteChanged) {
        if (!event.isError && FeatureFlag.REST_API.isEnabled()) {
            val siteAddress = requireArguments().getString(ARG_INPUT_SITE_ADDRESS)
            val site = SiteUtils.getXMLRPCSiteByUrl(mSiteStore, siteAddress)!!
            selectedSite.set(site)
            mLoginListener.loggedInViaUsernamePassword(SiteUtils.getCurrentSiteIds(mSiteStore, false))
        } else {
            super.onSiteChanged(event)
        }
    }
```

Null pointer crash:
```
Caused by: java.lang.NullPointerException
	at com.woocommerce.android.ui.login.overrides.WooLoginUsernamePasswordFragment.onSiteChanged(WooLoginUsernamePasswordFragment.kt:49)
	at java.lang.reflect.Method.invoke(Native Method)
```

**Screenshots**

https://user-images.githubusercontent.com/2663464/209361919-96857d25-b67b-41af-9b79-3ef4e58d1c62.mp4

**Expected behaviour**

To fix the issue, we need to strip away any suffix from the site address, very similarly to what was done [here](https://github.com/woocommerce/woocommerce-android/pull/8050)

**Mobile Environment**
Please include:
- Device: Emulator
- Android version: 30
- WooCommerce Android version: 11.7

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Fixes: #8056

### Description
Fixes crash when trying to log in using their site address if the site address contains suffixes like wp-admin or wp-login.php

### Testing instructions
Log into the app using site address with `wp-admin` suffix and check that the app doesn't crash. 

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt [hunk 1]
```diff
@@ -14,3 +16,19 @@ class UrlUtils @Inject constructor(
         "${AppUrls.AUTOMATTIC_TOS}?locale=${LanguageUtils.getPatchedCurrentDeviceLanguage(context)}"
     }
 }
+
+/**
+ * Basic sanitization of the URL based on the same logic we use in the XMLRPC discovery
+ * see: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/94601a5d4c1c98068adde0352ecc25e6d0046f35/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java#L292
+ */
+fun String.sanitiseUrl(): String {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt]: Just a np, this extension will be suggested in the autocomplete for all of the `String` instances, this is not a blocker, but without context, it's not clear what it does. Before, it was a private extension inside the class `SitePickerSiteDiscoveryViewModel`, so it was clear what it was about.
WDYT about moving it inside `UrlUtils`? we can then keep it as an extension and call it by providing the context receiver: `with(urlUtils) { url.sanitiseUrl() }`, or make it a regular function.

**Review by hichamboushaba — APPROVED** [review]
Works well, thanks for taking care of this @JorgeMucientes 👍.

I left a comment above, but it's not a blocker, feel free to merge if you want 🙂.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt (hunk 1 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt]: Good point @hichamboushaba . I've moved it inside `UrlUtils` to make it clear “sanitizing” should only be applied to URLs.

**Review by hichamboushaba — APPROVED** [review]
Thanks for making the changes @JorgeMucientes 💯
