### PR TITLE
Integrate `Automattic-Tracks-Android 2.0.0`

### LINKED ISSUE #2455: Sentry additional data is empty
Our app is configured to report the `site_id` and `site_url` to Sentry, but for some reason these are always empty. It would be helpful to have that data when working on crashes.

Screen Shot 2020-05-19 at 4 29 00 PM

### LINKED ISSUE #3883: Integrate `2.0.0` version of `Automattic-Tracks-Android`
We should integrate a new version of `Tracks` library which gives us new features like `breadcrumbs` or `tags` support. Also, it fixes #2455

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #2455 
Closes: #3883 

### Context
This PR integrates `Tracks` in version `2.0.0` and adds all changes to comply with updated API.

### How to test
1. Checkout this PR
2. Make sure there's a valid `wc.sentry.dsn` value in `gradle.properties`
3. Apply git's `patch` that is available at the bottom of this PR description
4. Run the app - please log in if you're not
5. Go to Sentry dashboard
6. Go to `Issues` 

Make sure that there's
- [x] `Throwable` error with `This is just a test` message below
7. Click on the `Throwable` error

Make sure that there's
- [x] `site_id` in `tags` section
- [x] `site_url` in `tags` section
- [x] `test` in `tags` section
- [x] `locale` in `tags` section
- [x] `Test message` in `message` section
- [x] `MainActivity` `created` and then `started` in `breadcrumbs` section
- [x] `Test breadcrumb` in `breadcrumbs` section
- [x] User's email, id and username in `user section`

**Make sure to remove this event (by clicking on bin icon) after test**

```
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt	(revision d7833a7e3c6fbda92bd380fd31a88dfac21b577e)
+++ WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt	(date 1619469640000)
@@ -43,7 +43,7 @@
     }
 
     override fun crashLoggingEnabled(): Boolean {
-        return appPrefs.isCrashReportingEnabled()
+        return true
     }
 
     override fun extraKnownKeys(): List<ExtraKnownKey> {
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt	(revision d7833a7e3c6fbda92bd380fd31a88dfac21b577e)
+++ WooCommerce/src/main/kotlin/com/woocommerce/android/ui/mystore/MyStoreFragment.kt	(date 1619470055000)
@@ -181,6 +181,13 @@
         tabLayout.addOnTabSelectedListener(tabSelectedListener)
 
         refreshMyStoreStats(forced = this.isRefreshPending)
+
+        crashLogging.recordEvent("Test breadcrumb")
+        crashLogging.sendReport(
+            Throwable(message = "This is just a test"),
+            message = "Test message",
+            tags = mapOf("test" to "tag")
+        )
     }
 
     override fun onResume() {
```

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt [hunk 1]
```diff
@@ -123,8 +125,6 @@ open class WooCommerce : MultiDexApplication(), HasAndroidInjector, ApplicationL
         val wellSqlConfig = WooWellSqlConfig(applicationContext)
         WellSql.init(wellSqlConfig)
 
-        CrashUtils.initCrashLogging(this)
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt:126]: Sentry initialization has been moved to `SentryCrashLogging` constructor, which is an `internal` class of `Tracks` library: https://github.com/Automattic/Automattic-Tracks-Android/blob/develop/AutomatticTracks/src/main/java/com/automattic/android/tracks/crashlogging/internal/SentryCrashLogging.kt#L20

File: WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt [hunk 2]
```diff
@@ -305,15 +304,14 @@ open class WooCommerce : MultiDexApplication(), HasAndroidInjector, ApplicationL
             if (hasUserOptedOut != accountStore.account.tracksOptOut) {
                 AnalyticsTracker.sendUsageStats = !accountStore.account.tracksOptOut
             }
-            CrashUtils.setCurrentAccount(accountStore.account)
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/WooCommerce.kt:308]: This, and all similar data-related methods for crash logging, have been removed. From now, `Tracks` will request any data from [`WCCrashLoggingDataProvider`](https://github.com/woocommerce/woocommerce-android/pull/3891/files#diff-cebd451e19656003faa1efadc36f91a3324e41f8942ee6e44f0a4d366e1a23f7R15) before sending an event so it'll always be up to date.

Internally, `Tracks` uses [`SentryOptions.BeforeSendCallback` to append all data](https://github.com/Automattic/Automattic-Tracks-Android/blob/develop/AutomatticTracks/src/main/java/com/automattic/android/tracks/crashlogging/internal/SentryCrashLogging.kt#L31-L35)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt [hunk 3]
```diff
@@ -65,7 +64,6 @@ fun Date.isToday() =
     } catch (e: Exception) {
         with("Unable to match dateString with today date. (current dateString value: $this)") {
             WooLog.e(T.UTILS, this)
-            CrashUtils.logException(e, T.UTILS, this)
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/DateExt.kt:68]: I've removed this as it'd be quite unusual and confusing to pass `crashLogging` object to `Date.isToday` method. Also, I didn't find any issues reported by this line so I believe it's safe to assume it's not error prone.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/CrashLoggingModule.kt [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+import dagger.Binds
+import dagger.Module
+import dagger.Provides
+import javax.inject.Singleton
+
+@Module
+abstract class CrashLoggingModule {
+    companion object {
+        @Provides
+        @Singleton
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/CrashLoggingModule.kt:18]: We want to initialize `Sentry` only once, hence `CrashLogging` is a singleton.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+    override fun applicationContextProvider(): Map<String, String> {
+        with(selectedSite.getIfExists()) {
+            return if (this == null) {
+                emptyMap()
+            } else {
+                mapOf(
+                    SITE_ID_KEY to siteId.toString(),
+                    SITE_URL_KEY to url
+                )
+            }
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt]: Just one nitpick came to my mind, I should probably use `.orEmpty` method to make it cleaner.

Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt]: Where do you plan to use `.orEmpty`?
A possible improvement also is to rewrite it like this:
```kotlin
return selectedSite.getIfExists()?.let {
            mapOf(
                SITE_ID_KEY to it.siteId.toString(),
                SITE_URL_KEY to it.url
            )
        } ?: emptyMap()
```
But it's just a nitpick too 😄, so just pick whatever you think is best 😉

**Review by hichamboushaba — APPROVED** [review]
Great work @wzieba 👏, this is going to be a game-changer in debugging crashes.

Before merging, I wanted to suggest something, as we use a lot of fragments in the app, the automatic breadcrumbs reporting from the SDK won't be very helpful, as it will report only activities lifecycle, I don't know if they'll support fragment lifecycle reporting too or not https://github.com/getsentry/sentry-java/issues/1374
We can implement it in the client ourselves, by either using the `registerFragmentLifecycleCallbacks` like [this](https://github.com/woocommerce/woocommerce-android/blob/3118ac301e908c2816617fcce50ceebe42a1ef9f/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt#L203), or by calling `recordEvent` in our `BaseFragment` class.
This can be done in a separate PR if you like, I just wanted your opinion.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt (hunk 5 above)
Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/crashlogging/WCCrashLoggingDataProvider.kt]: Thanks! I like `.let{}` suggestion, I ended up using `.orEmpty()` instead of `?: emptyMap()` 🙂

**Comment by wzieba** [comment]
Thanks @hichamboushaba for the review! I also believe and hope that this will make debugging much easier 🤞 

> I wanted to suggest something, as we use a lot of fragments in the app, the automatic breadcrumbs reporting from the SDK won't be very helpful, as it will report only activities lifecycle, I don't know if they'll support fragment lifecycle reporting too or not getsentry/sentry-java#1374

Very good suggestion, they don't support it for the reasons described in the ticket you linked. They do want to add lifecycle-dependent tracker but until then it's good idea to implement this on our own.

I've created an issue in `Tracks` repository: https://github.com/Automattic/Automattic-Tracks-Android/issues/92 . I think it's good to add it there (instead our codebase) so other clients could use it out of the box.

---

bonus!

> the automatic breadcrumbs reporting from the SDK won't be very helpful, as it will report only activities lifecycle,

True - I also plan to add `SentryOkHttpInterceptor` which will [add http calls to breadcrumbs](https://docs.sentry.io/platforms/android/configuration/integrations/okhttp/) for even more information https://github.com/Automattic/Automattic-Tracks-Android/issues/90
