### PR TITLE
Use value capture instead of nullability bang at class field reference

### LINKED ISSUE #3982: IssueRefundsViewModel throws NullPointerException at `refundItems` value access
Sentry Issue: [WOOCOMMERCE-ANDROID-1JR](https://sentry.io/organizations/a8c/issues/2384410020/?referrer=github_integration)

```
NullPointerException: None
    at com.woocommerce.android.ui.refunds.IssueRefundViewModel$onRefundConfirmed$1$resultCall$1.invokeSuspend(IssueRefundViewModel.kt:376)
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #3982. A `NullPointerException` is happening as reported by Sentry at `IssueRefundViewModel`
```
com.woocommerce.android.ui.refunds.IssueRefundViewModel$onRefundConfirmed$1$resultCall$1 in invokeSuspend at line 376
```

We can see at the referred code from the stacktrace that we're using double bangs access at a nullable class field reference:

``` kotlin
if (!refundItems.value.isNullOrEmpty()) {
   refundItems.value!!.forEach { allItems.add(it.toDataModel()) }
}
```
This is a specially difficult issue to reproduce since it needs a race condition between the async coroutine running the `if` check and the double bang access, with the `refundItems.value` becoming null between those two operations in another thread. So I'm tackling this problem by capturing the value with a `let` enclosure to make sure we got the non-null value and avoid accessing the class field reference.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt [hunk 1]
```diff
@@ -371,8 +371,8 @@ class IssueRefundViewModel @AssistedInject constructor(
                         return@async when (commonState.refundType) {
                             ITEMS -> {
                                 val allItems = mutableListOf<WCRefundItem>()
-                                if (! refundItems.value.isNullOrEmpty()) {
-                                    refundItems.value!!.forEach { allItems.add(it.toDataModel()) }
+                                refundItems.value.takeIf { it.isNullOrEmpty().not() }?.let {
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt]: This seems unnecessarily complex. Can't it be just this?

```
refundItems.value?.let {
  it.forEach { item -> allItems.add(item.toDataModel()) }
}
```

Comment (ThomazFB) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/refunds/IssueRefundViewModel.kt]: Agreed! Thanks for the tip! Here's the change: https://github.com/woocommerce/woocommerce-android/pull/3983/commits/f1a796554dea4dde13f0668dd02243929eac2037

**Comment by ThomazFB** [comment]
Hey @nbradbury, thanks for the review! The PR is ready for a second round. Also, I submitted another double bang fix after our discussion with Hafiz right here: https://github.com/woocommerce/woocommerce-android/pull/3983/commits/89168d5798af892f0946dffffdd8d8373728bec6. Let me know what you think!

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:
