### PR TITLE
REST API: fix login issue when WordPress is installed in a custom subdirectory

### LINKED ISSUE #9829: Unable to load custom login pages from site credentials login screen
**Describe the bug**
From the Android app we fail to load custom login pages as fallback to the native site credentials login. More context: p1695633633661049-slack-C03L1NF1EA3

**To Reproduce**
1. Click on Log in button
2. Enter the following url:
3. Enter any value for site credentials
4. See error dialog
5. Click on "Try again with WP Admin page" 
6. An empty dialog with OK is displayed. 

**Screenshots**

https://github.com/woocommerce/woocommerce-android/assets/2663464/0e70ba63-7923-4e1d-8087-6d9a74a722ed

**Expected behavior**
In iOS the feature works as expected and the custom login page is loaded correctly:

https://github.com/woocommerce/woocommerce-android/assets/2663464/d20fcf65-6322-496a-aeef-dc55cd4ce4bb

## Fix
When persisting `site` model fetched from the `/wp-json/` root endpoint, we should use the url that the user has entered when trying to log in. This will ensure we match the site model saved into the database, after fetching site info from the API. The following patch will fix the issue by overriding the url from the response with the sanitized url entered by the user. However this code is common with Jetpack app, so maybe the rest client is not the best place for applying the changes? 

```diff
Subject: [PATCH] Add explanatory comment to the scrim color workaround
---
Index: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt b/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt
--- a/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt	(revision e28999f1c88bf0650bf0e08cf5d4cce762c303b7)
+++ b/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt	(date 1695646694816)
@@ -72,7 +72,7 @@
                     }
 
                     wpApiRestUrl = discoveredWpApiUrl
-                    this.url = response?.url ?: cleanedUrl.replaceBefore("://", urlScheme)
+                    this.url = payload.url
                     this.username = payload.username
                     this.password = payload.password
                 }

```

Additionally, we need to fix the UI error handling and avoid displaying and empty dialog with an `OK` button when an error occurs.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #9829 

⚠️ Don't merge until the FluxC commit is updated

### Description
This PR fixes a login issue that occurs when WordPress is installed in a custom subdirectory, and not in the server's root, users might make this change for security reasons to try to hide the login and admin URLs.
It has two changes:
1. First it fixes the UI of the error dialog.
2. It updates FluxC to bring the change https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2860 that fixes the log in issue.

### Testing instructions
1. Prepare a site according to these instructions https://wordpress.org/documentation/article/giving-wordpress-its-own-directory/#method-ii-with-url-change
2. Make sure the site doesn't have a Jetpack connection
3. Open the app, then attempt a login, the native login will fail.
4. Proceed with the wp-admin login
5. Enter site credentials and approve the Application Password creation.
6. Confirm the rest of the flow works as expected.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsScreen.kt [hunk 1]
```diff
@@ -233,19 +233,14 @@ private fun WebAuthorizationScreen(
...
             AlertDialog(
                 text = {
-                    Column {
-                        Text(text = viewState.errorDialogMessage.getText())
-                    }
+                    Text(text = viewState.errorDialogMessage.getText())
                 },
                 onDismissRequest = onErrorDialogDismissed,
-                buttons = {
-                    Column(modifier = Modifier.padding(horizontal = dimensionResource(id = R.dimen.major_100))) {
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/sitecredentials/LoginSiteCredentialsScreen.kt:242]: I don't remember why I used the `Column` here 😕, but it was the cause of not showing the alert content.

**Comment by JorgeMucientes** [comment]
Thank you for handling this @hichamboushaba 🏅 Tested it and login works as expected! I hope this will alleviate some issues with site credentials login. 

:shipit: (once FluxC change set is updated)

**Review by JorgeMucientes — APPROVED** [review]
