### PR TITLE
Fix the AI product generation

### LINKED ISSUE #11267: AI product generation is failing
The AI product generation is failing due to a change in the response, where the JSON format is invalid and cannot be deserialized. The prompt needs to get updated to address the issue.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #11267. The prompt is now more explicit about the expected response JSON format, which fixes the problem.

**To test:**
1. Start the app 
2. Tap on the Products tab
3. Tap on the Add product CTA
4. Select the AI generation option
5. Enter the name of the product
6. Enter the description
7. Tap on Create product details button
8. Notice the product details are successfully generated

**Edit:**
Please also test the product generation using package photo.

**Note: ** Please don't merge until the FluxC PR is merged.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          5 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>category: tracks</code> label.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>GiftCardsStat</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>GiftCardsState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Loading</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ViewState</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/204">18.1 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/204">18.1 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt [hunk 1]
```diff
@@ -116,7 +116,7 @@ object AIPrompts {
             keywords: "$keywords"
             tone: "$tone"
 
-            Expected json response format:
+            Your response should be in JSON format and don't send anything extra. Don't include the word JSON in your response:
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt:119]: Thank for handling this @0nko 

The fix works well and the product creation flow works again :) 
Just a quick question from reading the Slack thread: p1712673057952299/1712665486.827879-slack-C03L1NF1EA3
Have you tested the `json_object` suggested param??  Doesn't work now? It seems @selanthiraiyan tested it in the past, and it didn't work, but he was going to give it a try again.

**Review by JorgeMucientes — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt (hunk 1 above)
Comment (0nko) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ai/AIPrompts.kt:119]: That's a good idea. I've updated the code and added the required changes to [FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2988).

File: build.gradle [hunk 2]
```diff
@@ -98,7 +98,7 @@ tasks.register("installGitHooks", Copy) {
 }
 
 ext {
-    fluxCVersion = '2.74.0'
+    fluxCVersion = '2988-76fed8bf191e70f0553d7492c66c961f0becebcc'
```
Comment (JorgeMucientes) [inline build.gradle]: Ouch I didn't know we'd need to add FluxC changes. I think that might complicate things a bit since this is targeting `release` branch. 

We'll need to generate a new FluxC release, `2.75.0` but only containing the changes from `2.74.0` + [this PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2988). So after merging FluxC change to `trunk` we need to create a new branch from `2.74.0` [changeset](https://github.com/wordpress-mobile/WordPress-FluxC-Android/releases/tag/2.74.0) and then cherry-pick the merging of [this PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2988) into `trunk`

Or, maybe simpler if the `release/18.1` branch compiles correctly using FluxC lates `trunk` changeset, then we can create the new release `2.75.0` directly from FluxC's `trunk`

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for applying the changes @0nko 👏🏼 
Everything works as expected, including the package scanning feature 🙌🏼 
Ready to merge. I just left a minor comment about the need to create a new FluxC release. If we don't do this now, the release manager on Friday will have to. And I'm afraid that will be you 😆

File: build.gradle (hunk 2 above)
Comment (0nko) [reply build.gradle]: This PR is based on `release/18.1` which is referencing the `trunk`, so I think we can go ahead with your last suggestion.
