### PR TITLE
Crash reporting: some fixes to improve reporting when no WPCom account is present

### LINKED ISSUE #8232: [REST API] Crash reporting changes
Currently, we use the user_id of the WPCom account to set the Sentry user used in the crash reports, and this won't work with site credentials.

The subject is even broader, as currently when a crash occurs before login, it's assigned to the user id `0`, which looks like all crashes are affecting a single user, so to fix both issues, we just need to make sure we don't assign a user `id` to Sentry when we don't have an `id`, this way Sentry will make sure to use the `installationId` which uniquely identifies the installation instance (https://docs.sentry.io/platforms/android/enriching-events/identify-user/)

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #8232 

### Description
Currently, we use the `AccountModel` that we get from the `AccountStore` as the Sentry's user, but the logic doesn't take into account the logged-out state, where the `AccountStore` would return a [default value](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/2bb7fe8e003587ab2010e7150ad706d5011186bc/fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java#L1256).

This was impacting the error reports in the logged out state, and more importantly it would impact the reports after the REST API project.

This PR aims to make sure we don't set Sentry's user unless we have a valid account, and in the other cases, we pass `null` which would mean using the `installationId` by the SDK (https://docs.sentry.io/platforms/android/enriching-events/identify-user/).

### Testing instructions
Apply the patch from below, then test the following scenarios:

##### Logged out state
1. Clear the app's data.
2. Open the app.
3. Open Sentry, and check for an error report with the wording: `Test`
4. Check the user details, and confirm that there is a UUID in the user's ID.

##### WPCom login
1. Open the app.
2. Enter the address of a WPCom site.
3. You will be asked for the WordPress.com credentials, enter them.
4. When the login finished, open Sentry and check for the error report.
5. Check the user details and confirm that the user details match your WPCom account details.

##### Site credentials login
1. Open the app.
2. Enter the address of a selfhosted site.
3. You will be asked for the site credentials, enter them.
4. When the login finished, open Sentry and check for the error report.
5. Check the user details, and confirm that there is a UUID in the user's ID.

```patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt	(revision 931a5dc876444bf26234eb69582e1d91b747d0b2)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/experiment/RESTAPILoginExperiment.kt	(date 1674232031203)
@@ -43,7 +43,7 @@
     fun getCurrentVariant(): RESTAPILoginVariant = if (PackageUtils.isTesting()) {
         RESTAPILoginVariant.CONTROL
     } else {
-        remoteConfigRepository.getRestAPILoginVariant()
+        RESTAPILoginVariant.TREATMENT
     }
 
     enum class RESTAPILoginVariant {
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(revision 931a5dc876444bf26234eb69582e1d91b747d0b2)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/main/MainActivity.kt	(date 1674231697972)
@@ -224,6 +224,7 @@
         installSplashScreen()
 
         super.onCreate(savedInstanceState)
+        crashLogging.sendReport(Exception("Test"))
 
         // Verify authenticated session
         if (!presenter.userIsLoggedIn()) {
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt	(revision 931a5dc876444bf26234eb69582e1d91b747d0b2)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppPrefs.kt	(date 1674231697992)
@@ -422,7 +422,7 @@
 
     fun isCrashReportingEnabled(): Boolean {
         // default to False for debug builds
-        val default = !BuildConfig.DEBUG
+        val default = true//!BuildConfig.DEBUG
         return getBoolean(UndeletablePrefKey.ENABLE_CRASH_REPORTING, default)
     }
 
```

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MapExt.kt [hunk 1]
```diff
@@ -0,0 +1,4 @@
+package com.woocommerce.android.extensions
+
+@Suppress("UNCHECKED_CAST")
+fun <K, V : Any> Map<out K, V?>.filterNotNull(): Map<K, V> = filterValues { it != null } as Map<K, V>
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MapExt.kt:4]: It looks so standard-ish that I had to check if it doesn't exist in the stdlib. It doesn't! https://youtrack.jetbrains.com/issue/KT-4734

**Review by wzieba — COMMENTED** [review]
I have issues with `Site credentials login` case. When I use site credentials, I have UUID as the reporter in Sentry. But, if I'm correct, it is an issue with the test case description. Is it?

---

If that's the case: does it make sense to register at least a username in case reports from site-credentials logins? Or username + Sentry generated UUID? I'm not thinking about working on this in this PR, but as a thought for the future (and probably changes in the Tracks library).

**Comment by hichamboushaba** [comment]
> I have issues with Site credentials login case. When I use site credentials, I have UUID as the reporter in Sentry. But, if I'm correct, it is an issue with the test case description. Is it?

Sorry for this @wzieba, the description was wrong, we don't have a WPCom account when signing in using site credentials, so it should be there just a UUID.

> does it make sense to register at least a username in case reports from site-credentials logins?

I thought about it, but I didn't add it because I don't think it'll add any advantage, the username is specific to the site's website, so knowing it won't bring any benefit to us, as we can't match it with any of the other logs or reports, let me know if you think otherwise.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MapExt.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/MapExt.kt:4]: Yes, I added it because I didn't find one for Map 🙂

**Review by wzieba — APPROVED** [review]
>  it won't bring any benefit to us, as we can't match it with any of the other logs or reports, let me know if you think otherwise.

Yes, that's a good point. I don't see a clear benefit either. And if it'll happens to be useful in the future, we can always add it.
