### PR TITLE
Fix/9743 properly schedule notifications

### LINKED ISSUE #9743: WorkManager local notifications scheduled consecutively being replaced
When scheduling local notifications consecutively like we do in [StoreCreationSummaryViewModel](https://github.com/woocommerce/woocommerce-android/blob/9f7cbafa783fdff294c55fc952071758316c4162/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt#L101) we using: 
```kotlin
        workManager
            .beginUniqueWork(LOCAL_NOTIFICATION_WORK_NAME, REPLACE, buildPreconditionCheckWorkRequest(notification))
            .then(buildNotificationWorkRequest(notification))
            .enqueue()
```
This code has 2 problems: 
- The value used for `uniqueWorkName` is the same for all the notifications
- We are applying a `REPLACE` strategy. 

Because of this the work requests to schedule the notifications are being replaced, preventing the notifications from properly being scheduled. What is even worse, the actual code will run: 
```kotlin
        AnalyticsTracker.track(
            AnalyticsEvent.LOCAL_NOTIFICATION_SCHEDULED,
            mapOf(
                AnalyticsTracker.KEY_TYPE to notification.type.value,
                AnalyticsTracker.KEY_BLOG_ID to notification.siteId,
            )
        )
```
Making us think that the notifications are scheduled, when they're not. 

A quick fix to this could be applying a `uniqueWorkName` for each notification type. Something like: 
```kotlin
        workManager
            .beginUniqueWork(
                LOCAL_NOTIFICATION_WORK_NAME + notification.type.value,
                REPLACE,
                buildPreconditionCheckWorkRequest(notification)
            )
            .then(buildNotificationWorkRequest(notification))
            .enqueue()
```

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Fixes: #9743

### Description
When scheduling local notifications consecutively like we do in [StoreCreationSummaryViewModel](https://github.com/woocommerce/woocommerce-android/blob/9f7cbafa783fdff294c55fc952071758316c4162/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/storecreation/summary/StoreCreationSummaryViewModel.kt#L101) we're using: 
```kotlin
        workManager
            .beginUniqueWork(LOCAL_NOTIFICATION_WORK_NAME, REPLACE, buildPreconditionCheckWorkRequest(notification))
            .then(buildNotificationWorkRequest(notification))
            .enqueue()
```
This code has 2 problems: 
- The value used for `uniqueWorkName` is the same for all the notifications
- We are applying a `REPLACE` strategy. 

Because of this, the work requests to schedule the notifications are being replaced, preventing the notifications from properly being scheduled. What is even worse, the actual code will run: 
```kotlin
        AnalyticsTracker.track(
            AnalyticsEvent.LOCAL_NOTIFICATION_SCHEDULED,
            mapOf(
                AnalyticsTracker.KEY_TYPE to notification.type.value,
                AnalyticsTracker.KEY_BLOG_ID to notification.siteId,
            )
        )
```
Making us think that the notifications are scheduled, when they're not.  This is easy to reproduce:
1.  Run the app from `trunk` and set all of the LocalNotifications to be triggered after a few seconds. You can apply the patch below.
2. Run Store Creation flow and check how all notifications are scheduled (in theory): 
```
Tracked: local_notification_scheduled, Properties: {"type":"store_creation_complete","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
Tracked: local_notification_scheduled, Properties: {"type":"one_day_before_free_trial_expires","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
Tracked: local_notification_scheduled, Properties: {"type":"one_day_after_free_trial_expires","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
Tracked: local_notification_scheduled, Properties: {"type":"six_hours_after_free_trial_subscribed","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
Tracked: local_notification_scheduled, Properties: {"type":"free_trial_survey_24h_after_free_trial_subscribed","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
```
3. Kill the app
4. Wait a few minutes and see how none of the notifications are shown except for the last one to be scheduled: `free_trial_survey_24h_after_free_trial_subscribed`

### Testing instructions

Apply this patch:
```diff
Subject: [PATCH] Add better error handling
---
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt	(revision d84c533f31b295e6b198b24e9799d79ded6b7b09)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt	(date 1694101448007)
@@ -30,7 +30,7 @@
         title = R.string.local_notification_store_creation_complete_title,
         description = R.string.local_notification_store_creation_complete_description,
         type = LocalNotificationType.STORE_CREATION_FINISHED,
-        delay = 5,
+        delay = 2,
         delayUnit = TimeUnit.MINUTES
     ) {
 
@@ -48,8 +48,8 @@
         title = R.string.local_notification_without_free_trial_title,
         description = R.string.local_notification_without_free_trial_description,
         type = LocalNotificationType.STORE_CREATION_INCOMPLETE,
-        delay = 24,
-        delayUnit = TimeUnit.HOURS
+        delay = 3,
+        delayUnit = TimeUnit.MINUTES
     ) {
         override val data: String = storeName
 
@@ -66,8 +66,8 @@
         title = R.string.local_notification_one_day_before_free_trial_expires_title,
         description = R.string.local_notification_one_day_before_free_trial_expires_description,
         type = LocalNotificationType.FREE_TRIAL_EXPIRING,
-        delay = 13,
-        delayUnit = TimeUnit.DAYS
+        delay = 3,
+        delayUnit = TimeUnit.MINUTES
     ) {
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description, expiryDate)
@@ -82,8 +82,8 @@
         title = R.string.local_notification_one_day_after_free_trial_expires_title,
         description = R.string.local_notification_one_day_after_free_trial_expires_description,
         type = LocalNotificationType.FREE_TRIAL_EXPIRED,
-        delay = 15,
-        delayUnit = TimeUnit.DAYS
+        delay = 3,
+        delayUnit = TimeUnit.MINUTES
     ) {
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description, name)
@@ -95,8 +95,8 @@
         title = R.string.local_notification_upgrade_to_paid_plan_after_6_hours_title,
         description = R.string.local_notification_upgrade_to_paid_plan_after_6_hours_description,
         type = LocalNotificationType.SIX_HOURS_AFTER_FREE_TRIAL_SUBSCRIBED,
-        delay = 6,
-        delayUnit = TimeUnit.HOURS
+        delay = 3,
+        delayUnit = TimeUnit.MINUTES
     ) {
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description)
@@ -108,8 +108,8 @@
         title = R.string.local_notification_survey_after_24_hours_title,
         description = R.string.local_notification_survey_after_24_hours_description,
         type = LocalNotificationType.FREE_TRIAL_SURVEY_24H_AFTER_FREE_TRIAL_SUBSCRIBED,
-        delay = 24,
-        delayUnit = TimeUnit.HOURS
+        delay = 3,
+        delayUnit = TimeUnit.MINUTES
     ) {
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description)
@@ -122,7 +122,7 @@
         description = R.string.local_notification_still_exploring_description,
         type = LocalNotificationType.THREE_DAYS_AFTER_STILL_EXPLORING,
         delay = 3,
-        delayUnit = TimeUnit.DAYS
+        delayUnit = TimeUnit.MINUTES
     ) {
         override fun getDescriptionString(resourceProvider: ResourceProvider): String {
             return resourceProvider.getString(description)

```
Repeat the same steps from the previous section and check how all the notifications that were shown as scheduled in the logs: 
```
local_notification_scheduled, Properties: {"type":"store_creation_complete","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
local_notification_scheduled, Properties: {"type":"one_day_before_free_trial_expires","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
local_notification_scheduled, Properties: {"type":"one_day_after_free_trial_expires","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
local_notification_scheduled, Properties: {"type":"six_hours_after_free_trial_subscribed","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
local_notification_scheduled, Properties: {"type":"free_trial_survey_24h_after_free_trial_subscribed","blog_id":223247857,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"ecommerce-trial-bundle-monthly","is_debug":true,"site_url":"https:\/\/woo-honestly-observant-bluebird.wpcomstaging.com"}
```
Wait a couple minutes and as soon as you see the first notification appear, click on it. 
The rest of the notifications will be shown after a couple of minutes.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt [hunk 1]
```diff
@@ -95,8 +95,8 @@ sealed class LocalNotification(
         title = R.string.local_notification_upgrade_to_paid_plan_after_6_hours_title,
         description = R.string.local_notification_upgrade_to_paid_plan_after_6_hours_description,
         type = LocalNotificationType.SIX_HOURS_AFTER_FREE_TRIAL_SUBSCRIBED,
-        delay = 2,
-        delayUnit = TimeUnit.MINUTES
+        delay = 6,
+        delayUnit = TimeUnit.HOURS
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt:99]: I accidentally committed this changes in my previous PR and merged them into `trunk`. 🤦🏼 Too much testing local notifications today, my head is fried 😅

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt [hunk 2]
```diff
@@ -66,7 +66,9 @@ class PreconditionCheckWorker @AssistedInject constructor(
         return if (notificationLinkedSite.isFreeTrial) {
             Result.success()
         } else {
-            cancelWork("Store plan upgraded. Cancelling work.")
+            if (notificationLinkedSite == null) {
+                cancelWork("The site linked to the notifications doesn't exist in the db. Cancelling work.")
+            } else cancelWork("Store plan upgraded. Cancelling work.")
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt:71]: In line 65, the result from that could be null. I think it's only possible in testing scenarios for this to be null, but just in case I'm adding this small change to provide better context on why the work was cancelled.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt (hunk 1 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/LocalNotification.kt:99]: Oh, sorry for not catching it up in the review, me too I can't concentrate much because of the context switching with the Hack Week.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt:71]: Good point, it can even happen in real life I think, if the user deleted the site in trial 🤔

**Review by hichamboushaba — APPROVED** [review]
Really nice find @JorgeMucientes 👏, I'm pretty sure this explains the big drop of scheduled notifications.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/notifications/local/PreconditionCheckWorker.kt:71]: Yeah, in fact this just helped me to catch this https://github.com/woocommerce/woocommerce-android/pull/9744/files#diff-25d9ac3c08b2fbf1a49c4486a01f34058aa6a87b415dcffcbed22fba8167ba48R65 I had not noticed. The method used to retrieve the site was not correct. Resulting in 
`The site linked to the notifications doesn't exist in the db. Cancelling work.`
