### PR TITLE
Search in product detail fix

### LINKED ISSUE #3244: Toolbar search in product details
The search view is shown in the product detail screen when a new product is added while searching the product list.

image

**To reproduce:**
1. Go to Products
2. Tap on the Search icon
3. Tap on the Add product FAB
4. Notice the search view is visible

### PR DESCRIPTION
**Pull request by 0nko**
Fixes: #3244.

**To test:**

1. Go to Products
2. Tap on the Search icon
3. Tap on the Add product FAB
4. Notice the search is canceled

### CODE REVIEW

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt [hunk 1]
```diff
@@ -56,8 +56,7 @@ class ProductListViewModelTest : BaseUnitTest() {
                         savedState,
                         coroutineDispatchers,
                         productRepository,
-                        networkStatus,
-                        prefs
```
Comment (nbradbury) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt:60]: Since `prefs` is no longer used, we can delete [this line](https://github.com/woocommerce/woocommerce-android/blob/04007db072a0242fc2227d114e4376b6eaa0a31f/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductListViewModelTest.kt#L36) and the unused import.

**Comment by 0nko** [comment]
Ready for another round @nbradbury.

**Review by nbradbury — APPROVED** [review]
:shipit:
