### PR TITLE
[Bug] Fix for Orders screen stuck at skeleton loading view

### LINKED ISSUE #12142: Infinite Order Detail Loading Screen
**Describe the bug**
If I rotate my device during the order creation, I end up with an Order Detail screen with an infinite loading on my backstack.

**To Reproduce**
1. Go to Order List
2. Start Order Creation
3. Add any product
4. Rotate the device
5. Rotate it back
6. Tap on `Create`
7. Notice you are redirected to the newly created order
8. Press back and notice an infinite loading screen

**Screenshots**

https://github.com/user-attachments/assets/d2ab31bc-fce4-4b18-8f47-a0b546d10b68

**Expected behavior**
Tapping back from the detail of the newly created order should navigate me back directly to the order list.

**Mobile Environment**
Please include:
- Device: Pixel 8
- Android version: Android 14
- WooCommerce Android version: 19.6

### PR DESCRIPTION
**Pull request by samiuelson**
## [Bug] Fix for Orders screen stuck at skeleton loading view

Closes: #12142 

### Description

This PR intends to fix a bug in the Orders screen, resulting in infinite displaying of a "skeleton/shimmer" loading view.

### Steps to reproduce

Steps to reproduce the bug:
1. Go to Order List
2. Start Order Creation
3. Add any product
4. Rotate the device
5. Rotate it back
6. Tap on `Create`
7. Notice you are redirected to the newly created order
8. Press back and notice an infinite loading screen

https://github.com/user-attachments/assets/d2ab31bc-fce4-4b18-8f47-a0b546d10b68

### Testing information

It should be verified that the repro scenario mentioned above is no longer causing the bug. It's worth looking for regression in similar scenarios (e.g. screen rotations in orders screen on large screens, transitions from single pane layout to dual pane layout with split screen, etc.)

### The tests that have been performed

I verified that the bug repro scenario is no longer causing the issue. Additionally, I tested similar scenarios on compact and large screens.

Physical devices tested: 
* Pixel 8, Android 14
* Samsung Galaxy Tab, Android 14 

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/232">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 1]
```diff
@@ -293,11 +293,11 @@ class OrderListFragment :
     }
 
     private fun adjustUiForDeviceType(savedInstanceState: Bundle?) {
-        if (requireContext().windowSizeClass != WindowSizeClass.Compact) {
+        if (requireContext().windowSizeClass > WindowSizeClass.Compact) {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt:296]: Changed `!=` to `>` for the sake of code readability and safety (e.g. if we define a size class smaller than compact in the future)

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 2]
```diff
@@ -353,10 +359,13 @@ class OrderListFragment :
     override fun onSaveInstanceState(outState: Bundle) {
         outState.putBoolean(STATE_KEY_IS_SEARCHING, isSearching)
         outState.putString(STATE_KEY_SEARCH_QUERY, searchQuery)
-        if (requireContext().windowSizeClass != WindowSizeClass.Compact) {
-            val navHostFragment = childFragmentManager.findFragmentById(R.id.detailPaneContainer) as? NavHostFragment
-            val currentDestinationId = navHostFragment?.navController?.currentDestination?.id
-            outState.putInt(CURRENT_NAV_DESTINATION, currentDestinationId ?: -1)
+        if (findNavController().currentDestination?.id == R.id.orders) {
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt:362]: The root cause of the bug was here. The `onSaveInstanceState` is the Activity-level hook, and is called even if the `OrderListFragment` is not currently visible (is not at the top of the back stack). As a result, we were persisting the state of view in `Bundle` at incorrect moments (e.g. while the `OrderCreateEditForm` was the current destination).

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt [hunk 3]
```diff
@@ -353,10 +359,13 @@ class OrderListFragment :
     override fun onSaveInstanceState(outState: Bundle) {
         outState.putBoolean(STATE_KEY_IS_SEARCHING, isSearching)
         outState.putString(STATE_KEY_SEARCH_QUERY, searchQuery)
-        if (requireContext().windowSizeClass != WindowSizeClass.Compact) {
-            val navHostFragment = childFragmentManager.findFragmentById(R.id.detailPaneContainer) as? NavHostFragment
-            val currentDestinationId = navHostFragment?.navController?.currentDestination?.id
-            outState.putInt(CURRENT_NAV_DESTINATION, currentDestinationId ?: -1)
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt:359]: 💡 IMO, saving the `currentDestination.id` integer is misleading because we don't really need this value when restoring the state. The data we need when restoring Fragment's state is whether the last window size class was larger than compact.

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @samiuelson. Works as expected! 🚀
