### PR TITLE
[Woo POS]  Crash if activity dies during IPP flow

### LINKED ISSUE #12419: [Woo POS] The crash if activity dies during IPP flow
* Enabled don't keep activities
* Start payment collection flow
* Hide/open the app

```
     java.lang.IllegalArgumentException: Navigation action/destination com.woocommerce.android.dev:id/action_selectPaymentMethodFragment_to_cardReaderPaymentFlow cannot be found from the current destination Destination(com.woocommerce.android.dev:id/cardReaderConnectDialogFragment) label=CardReaderConnectDialogFragment
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1691)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1609)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:2169)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:213)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$handleEvents$1.invoke(SelectPaymentMethodFragment.kt:178)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.invoke(MultiLiveEvent.kt:43)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$observe$1.invoke(MultiLiveEvent.kt:40)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent.setValue(MultiLiveEvent.kt:56)
                                                                                                    	at com.woocommerce.android.viewmodel.MultiLiveEvent.setValue(MultiLiveEvent.kt:34)
                                                                                                    	at com.woocommerce.android.viewmodel.ScopedViewModel.triggerEvent(ScopedViewModel.kt:37)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.access$triggerEvent(SelectPaymentMethodViewModel.kt:64)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel$onBtReaderClicked$1.invokeSuspend(SelectPaymentMethodViewModel.kt:308)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:88)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel.onBtReaderClicked(SelectPaymentMethodViewModel.kt:305)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodViewModel$checkStatus$1.invokeSuspend(SelectPaymentMethodViewModel.kt:126)
```

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12419 

### Description

Take a look at my comments in the PR with an explanation of the problem for more content

@samiuelson I am not sure if the picked solutions are the best, so please look into this critically

### Steps to reproduce

* Enabled don't keep activities
* Start card payment flow
* Hide/open activity

But there is another crash happens when the above fixed:
* Enabled don't keep activities
* Start card payment flow
* Hide/open activity
* Cancel or finish the payment flow

### The tests that have been performed

I have tested the steps to reproduce. Also I retested the IPP flows

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt [hunk 1]
```diff
@@ -213,6 +213,18 @@ class SelectPaymentMethodFragment : BaseFragment(R.layout.fragment_select_paymen
                     findNavController().navigate(action)
                 }
 
+                is SkipScreenInPosAndNavigateToCardReaderPaymentFlow -> {
+                    if (findNavController().currentDestination?.id == R.id.selectPaymentMethodFragment) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt:213]: The crash happens because after the activity is recreated, the `SelectPaymentMethodVM` is recreated with the `WOO_POS` parameter, which initiates navigation. The issue is that the graph and position is restored, so we were trying to navigate from the destination which was not current

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt [hunk 2]
```diff
@@ -213,6 +213,18 @@ class SelectPaymentMethodFragment : BaseFragment(R.layout.fragment_select_paymen
                     findNavController().navigate(action)
                 }
 
+                is SkipScreenInPosAndNavigateToCardReaderPaymentFlow -> {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt:212]: I created another event to make sure that we do not interfere with the IPP

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt [hunk 3]
```diff
@@ -309,6 +309,13 @@ class SelectPaymentMethodViewModel @Inject constructor(
         }
     }
 
+    private fun skipScreenDuringPosFlow() {
+        launch {
+            OrderDurationRecorder.recordCardPaymentStarted()
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt]: I do not track click here, as we don't click it, so I think it was a bug before

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt [hunk 4]
```diff
@@ -10,37 +10,39 @@ import com.woocommerce.android.cardreader.CardReaderManager
...
 import kotlinx.coroutines.flow.Flow
-import kotlinx.coroutines.suspendCancellableCoroutine
+import kotlinx.coroutines.flow.MutableStateFlow
 import javax.inject.Inject
-import kotlin.coroutines.Continuation
-import kotlin.coroutines.resume
+import javax.inject.Singleton
 
-@ActivityRetainedScoped
+@Singleton
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt:18]: That's another issue I noticed after I fixed the navigation crash after activity restart. This Facade was recreated to, and `paymentContinuation` was null when the result was returned

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt [hunk 5]
```diff
@@ -56,14 +58,12 @@ class WooPosCardReaderFacade @Inject constructor(
...
     }
 
-    suspend fun collectPayment(orderId: Long): WooPosCardReaderPaymentResult {
-        return suspendCancellableCoroutine { continuation ->
-            paymentContinuation = continuation
-            val intent = WooPosCardReaderActivity.buildIntentForPayment(activity!!, orderId).apply {
-                addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP)
-            }
-            paymentResultLauncher!!.launch(intent)
+    fun collectPayment(orderId: Long) {
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt:61]: Again, as activity was recreated along with VM, nobody was already was in suspend state waiting for the result, so the result was completely lost. 

The solution I picked was to keep the payment result state in a `MutableStateFlow`

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt (hunk 3 above)
Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt]: I think it's better to remove `OrderDurationRecorder.recordCardPaymentStarted()` from this PR, to keep it simple – we don't read the elapsed time in POS so it doesn't make sense to reset the timer 🤔

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt [hunk 6]
```diff
@@ -23,6 +23,11 @@ data class NavigateToCardReaderPaymentFlow(
     val cardReaderType: CardReaderType
 ) : MultiLiveEvent.Event()
 
+data class SkipScreenInPosAndNavigateToCardReaderPaymentFlow(
```
Comment (samiuelson) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt:26]: 👍🏼 I think it's a good improvement. With that event, we should be able to remove the `SelectPaymentMethodViewModel.displayUi` prop and clean up the `SelectPaymentMethodFragment::onCreateView` as well. Wdut?

**Review by samiuelson — COMMENTED** [review]
👋🏼 @kidinov, good work. I managed to do an initial scan of the changes and shared some thoughts. I'll take a deeper look Friday.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt (hunk 1 above)
Comment (backwardstruck) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodFragment.kt:213]: So that explains why this only happens in POS. I wonder if we are going to see more of these issues where we try to navigate into the main app code from the POS graph.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt (hunk 3 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodViewModel.kt]: Removed here a859e6efad76f3a7f571787056a82f3ecd77ff24

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt (hunk 6 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/payments/methodselection/SelectPaymentMethodEvent.kt:26]: hm... I don't remember why `displayUi` was added (maybe blinking of the UI?), but the event itself doesn't change anything as before that was the same - we were just skipping the `SelectPaymentMethodFragment`.

In any case, I removed `displayUi` and I don't see the blinking

5bc76197a23992e38ad89233572ea6289b0330f3

**Review by samiuelson — APPROVED** [review]
Great investigation @kidinov 👍🏼 The fixes LGTM!

I tested the activity death scenario during payment on Galaxy Tab, Android 14.
