### PR TITLE
Issue/954 sign in option on jetpack req'd screen

### LINKED ISSUE #954: If site is inaccessible after logging in - there's no way to log in as a different user.
**Describe the bug**

Same issue with iOS: https://github.com/woocommerce/woocommerce-ios/issues/828

Basically if we log in and the sites are not accessible for some reason - it isn't possible to log out and log in as a different user which makes the troubleshooting workflow difficult (the only workaround is to re-install the app).

**To Reproduce**

1. Log in as a user with connection issues (one of examples - 1924167 zen)
2. It isn't possible to log in as a different user and we're "trapped" on site choice screen

**Expected behavior**

I'd hope to be able to log in as a different user if I'm unable to access a site as this particular user. Not sure if that's the best flow for regular users but this would definitely make troubleshooting easier as we wouldn't have to re-install the app to access a different account.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. Not applicable
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Android simulator
- Android version: 1.5-rc-2, also older versions
- WooCommerce Android version: 8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by AmandaRiu**
Addresses scenarios described in this ticket #1303 by adding a new button "Already have Jetpack? Sign in" that allows the user to bypass this warning and attempt to login to the site as normal. The hope is that if our check for Jetpack is not working properly the user will still have an option to login with the selected site. 

## Design
Screen Shot 2019-08-20 at 7 34 38 PM

## Implementation
- Updated Jetpack Required screen:
  - Removed "Contact support" button per the new design
  - Removed the now unused `LOGIN_JETPACK_REQUIRED_CONTACT_SUPPORT_BUTTON_TAPPED` track event
  - Added a new "Already have Jetpack? Sign in" bottom bar
  - Added new track event `LOGIN_JETPACK_REQUIRED_SIGN_IN_LINK_TAPPED` : `(url)` 
- Updated `SitePickerActivity` and added new logic for displaying a different view if the user bypassed the Jetpack required warning and the store the user is trying to log into is not included in the list of sites fetched for the user. A different message is displayed and includes an option to refresh the app. 
  - The primary (purple) button text has been tweaked to **TRY ANOTHER STORE**. The functionality of this process is no different with this PR, it just drops the user back to the beginning of the login process. (note: [a separate ticket](https://github.com/woocommerce/woocommerce-android/issues/1365) has been opened to address which screen this process should route the user to)
  - Added new tracks events:
    - `SITE_PICKER_AUTO_LOGIN_ERROR_NOT_CONNECTED_JETPACK` : (`url`)
    - `SITE_PICKER_TRY_ANOTHER_STORE_BUTTON_TAPPED`
    - `SITE_PICKER_NOT_CONNECTED_JETPACK_REFRESH_APP_LINK_TAPPED`
- Tracks spreadsheet has been updated with all the new events.

## Behavior

If unable to login due to missing jetpack a new screen is displayed. Note the change to the primary button from "TRY ANOTHER ACCOUNT" to "TRY ANOTHER **STORE**":

If the user fixes the Jetpack connection issue and clicks "**Refresh the app**" we will do the following:
- Send a request to fetch all the sites associated with the current user from the API
- Check if the site requested is in the list of sites.
- If it is, then Jetpack is working. Check if Woo is installed and continue the login process. If Woo is **not** installed, show the current **Not a woo site** error as normal.

#### Verify user can change the site to login into:
1. Attempt to login with a site that does not have Jetpack installed or connected. Verify Jetpack required screen is shown.
2. Hit the device "back" button to return to the site address input screen. 
3. Enter a different site that has jetpack installed and connected. Verify can login successfully.

#### Verify the user can continue the sign in process from the Jetpack required screen.
1. Attempt to login with a site that does not have Jetpack installed or connected. Verify Jetpack required screen is shown.
2. Click "sign in" link at the bottom. Verify the user is routed to the next screen in the login process.
3. Verify the user sees the "Unable to connect to jetpack" screen and can view the connected site or "try another store" successfully. 

#### Test refreshing the app after jetpack login error
1. Attempt to login with a site that does not have Jetpack installed or connected. Verify Jetpack required screen is shown.
2. Click "sign in" link at the bottom. Verify the user is routed to the next screen in the login process.
3. Verify the user sees the "Unable to connect to jetpack" screen and the button text says "Try another store"
4. Fix jetpack connection on the test site. 
5. Click "refresh the app" link
6. Verify user successfully logs in
7. Logout and complete the same steps in landscape mode.

#### Test logging in with site that does not have jetpack, then fix, then site does not have Woo
1. Attempt to login with a site that does not have Woo active and Jetpack is not connected. Verify Jetpack required screen is shown.
2. Click "sign in" link at the bottom. Verify the user is routed to the next screen in the login process.
3. Verify the user sees the "Unable to connect to jetpack" screen and the button text says "Try another store"
4. Fix jetpack connection on the test site. 
5. Click "refresh the app" link. Verify the "Not woo store" error screen is shown. 
6. Enable the Woo plugin on the test site.
7. Click "refresh the app" link. Verify the app logs into the site successfully.

#### Test logging in with site that does not have Woo Installed
1. Attempt to login to a site that has Jetpack but does not have Woo installed. 
2. Verify the appropriate "Not a Woo Store" message is displayed, and that the button text says "Try Another Account". 
3. Enable woo on the test site and click "Refresh the app"
4. Verify user successfully logs in.

## TODO (reviewer)
- [x] Validate the new track events

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by nbradbury** [comment]
The spannable looks off here - I think we want something more than "app to continue" to be clickable.

Screenshot_1566583803

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt [hunk 1]
```diff
@@ -494,6 +503,71 @@ class SitePickerActivity : AppCompatActivity(), SitePickerContract.View, OnSiteC
...
+        button_email_help.visibility = View.GONE
+
+        with(no_stores_view) {
+            val refreshAppText = getString(R.string.login_refresh_app)
+            val notConnectedText = getString(
+                    R.string.login_not_connected_jetpack,
+                    url,
+                    refreshAppText
+            )
+
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt]: Rather than use a `SpannableString` it might be simpler to define the string resource like this:

```
<string name="login_refresh_app">&lt;a href=\'click\'&gt;refresh the app&lt;a&gt;</string>
```

And then on the `TextView` use:

```
setText(Html.fromHtml(notConnectedText), TextView.BufferType.SPANNABLE)
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt [hunk 2]
```diff
@@ -98,10 +98,13 @@ class AnalyticsTracker private constructor(private val context: Context) {
         SITE_PICKER_AUTO_LOGIN_SUBMITTED(siteless = true),
         SITE_PICKER_AUTO_LOGIN_ERROR_NOT_CONNECTED_TO_USER(siteless = true),
         SITE_PICKER_AUTO_LOGIN_ERROR_NOT_WOO_STORE(siteless = true),
+        SITE_PICKER_AUTO_LOGIN_ERROR_NOT_CONNECTED_JETPACK(siteless = true),
         SITE_PICKER_TRY_ANOTHER_ACCOUNT_BUTTON_TAPPED(siteless = true),
+        SITE_PICKER_TRY_ANOTHER_STORE_BUTTON_TAPPED(siteless = true),
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt]: I don't see this event being tracked anywhere.

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/analytics/AnalyticsTracker.kt]: Nice catch! Not sure how I missed that one... fixed in 173535caee8a81227a791e996fa8efb59f92709b
Logcat:
```
Tracked: site_picker_try_another_store_button_tapped
```

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt (hunk 1 above)
Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt]: Love the tip! I see where you are coming from, but the reason for the span is that not all of the text is clickable, only part of it. So for localization I’d have to do some tricks to get that to work properly plus I’d have to use two different text views to display it which would not look as smooth as including it all in one text view. I also like the containment of the clickable span…it can be re-used and the usage of it is really straight-forward (I use it elsewhere in the app)

**Comment by nbradbury** [comment]
@AmandaRiu I'm finished reviewing - it all looks good, with the exception of the spannable bug.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt (hunk 1 above)
Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt]: Ok, ended up implementing anyway due to a problem with the wrong text being clickable. It's easy when the clickable element is at the end of the text, but in the middle it got a lot trickier. f0ddf39fccd58e0ddfb24080d3a45ede71445bb6

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt]: Unfortunately I couldn't figure out how to remove the underline. Nothing in Stackoverflow would work. so far I've tried:
```
paintFlags = 0
paintFlags = paintFlags and Paint and Paint.UNDERLINE_TEXT_FLAG.inv()
paintFlags = paintFlags and -Paint.UNDERLINE_TEXT_FLAG.inv()
```
I also tried setting `background="@null"` on the `TextView` with no luck :( I'm going to leave this for now and move on since I've burned a lot of time here. It can be addressed in a future release.

cc: @kyleaparker

Comment (AmandaRiu) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerActivity.kt]: Nevermind! Kylea updated the design so I reverted those code changes and updated the design in 994574756fce9893e2134493ceff6a57cef1996d. Now it looks like this:

**Review by nbradbury — APPROVED** [review]
:shipit:
