### PR TITLE
Open TOS from the login screen

### LINKED ISSUE #3871: `Terms of Service` link is not working or is not visible
**Describe the bug**
`Terms of Service` link is either hidden (on production) or doesn't link (on develop)

**To Reproduce**

### Issue 1
Building an app from current `develop`

1. Go to `Continue with WordPress.com`
2. See `By continuing, you agree to our Terms of Service` label
3. Click on it

Expected behavior: user should be linked to `Terms of Service`
Current behavior: nothing happens

### Issue 2

Downloading an app from Google Play Store

1. Go to `Continue with WordPress.com`

Expected behavior: user should see `By continuing, you agree to our Terms of Service` label
Current behavior: nothing happens

For the release variant I think this might be some timing issue as I can't find any intention in code to hide `Terms of Service` label. Those are usages of  

```kotlin
LoginEmailFragment#newInstance(String url,boolean optionalSiteCredsLayout, boolean isSignupFromLoginEnabled, **boolean hideTos**)
```

image

(the last method seems to be unused)

---

**Screenshots**

### For issue 1

https://user-images.githubusercontent.com/5845095/115428536-c72a3b00-a202-11eb-9550-e72e1bde7e8c.mov

### For issue 2

Screenshot 2021-04-20 at 17 54 42

**Mobile Environment**

| | Issue 1 | Issue 2 |
| --- | --- | --- |
| Device | Samsung SM-A520F | Xiaomi MI 9 | 
| Android version | 26 | 29 |
| WooCommerce Android version | 6.3 | 6adbdc3df65216d6549f177ca2959da91c39560b |

### PR DESCRIPTION
**Pull request by kidinov**
Implemented functionality of the opening TOS in chrome tab from the login screen. #3871 

It looks like that we started to show the TOSes links in [this commit](https://github.com/woocommerce/woocommerce-android/commit/88851bcd449f8792c5ee7b34552da154a30bdde7), but we forgot to implement the click listener. 

This PR implements it.

### How to test:
Login screen -> Continue with Wordpress -> Click on TOS link under email address
or
Login screen -> Continue with Wordpress -> Click on TOS link under continue with google

### Video

* [Debug build](https://d.pr/v/RfKYAw)
* [Release build](https://d.pr/v/mOvvt7)

Closes: #3871

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
+package com.woocommerce.android.util
+
+import android.content.Context
+import com.woocommerce.android.AppUrls
+import org.wordpress.android.util.LanguageUtils
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@Singleton
```
Comment (wzieba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt]: What's the reason for making `UrlUtils` a `singleton`? If it's about performance, I'd advice to remove the annotation or use `@Reusable`. If we use singleton, Dagger has to keep this object in the memory and effectively we have a memory leak (we keep a reference to an object we won't use). WDYT?

**Review by wzieba — APPROVED** [review]
Looks good, thanks!

One hint about videos: Github has now support for .mov and .mp4 files so maybe it's good to use this instead of 3rd party services. I'm just concerned about how long videos will be available there.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt (hunk 1 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt]: > One hint about videos: Github has now support for .mov and .mp4 files so maybe it's good to use this instead of 3rd party services. I'm just concerned about how long videos will be available there.

Thanks for the advice! I was usually doing so but during my support rotation learnings, it was advised to use this droplr tools. I think we have even paid version of it, so I was under impression that we use it. Apparently I was wrong so I'll come back with using adb video recording and publishing in on github =)

> What's the reason for making UrlUtils a singleton? If it's about performance, I'd advice to remove the annotation or use @Reusable. If we use singleton, Dagger has to keep this object in the memory and effectively we have a memory leak (we keep a reference to an object we won't use). WDYT?

Generated code just for reference:

### Singleton
```
  private UrlUtils urlUtils() {
    Object local = urlUtils;
    if (local instanceof MemoizedSentinel) {
      synchronized (local) {
        local = urlUtils;
        if (local instanceof MemoizedSentinel) {
          local = new UrlUtils(ApplicationContextModule_ProvideContextFactory.provideContext(applicationContextModule));
          urlUtils = DoubleCheck.reentrantCheck(urlUtils, local);
        }
      }
    }
    return (UrlUtils) local;
  }
```
### Reusable

```
    private UrlUtils urlUtils() {
      Object local = urlUtils;
      if (local == null) {
        local = new UrlUtils(ApplicationContextModule_ProvideContextFactory.provideContext(DaggerWooCommerceDebug_HiltComponents_SingletonC.this.applicationContextModule));
        urlUtils = (UrlUtils) local;
      }
      return (UrlUtils) local;
    }
```

### Unscoped

```
    private UrlUtils urlUtils() {
      return new UrlUtils(ApplicationContextModule_ProvideContextFactory.provideContext(DaggerWooCommerceDebug_HiltComponents_SingletonC.this.applicationContextModule));
    }
```

`Singleton` works for us, but we don't really have to be sure that we share the same instance across threads, so double-check locking is overhead here.

`Unscoped` creates too much unnecessary pressure on the heap, causes more GC runs, which we don't really need here because this is basically stateless until (it's actually not but we want the state to be calculated only once so it is haha).

So I think you are right and `Reusable` is the best option here and in other stateless utils unless we have to be sure that it's only one instance per app (e.g. retrofit or okhttp client)

Changed to `Reusable`!

Comment (wzieba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/UrlUtils.kt]: > I was usually doing so but during my support rotation learnings, it was advised to use this droplr tools. I think we have even paid version of it

I didn't know this, TIL! As we have a paid version, my concern is probably less valid.

> Generated code just for reference:

Thanks a lot for preparing this!

> Unscoped creates too much unnecessary pressure on the heap, causes more GC runs, which we don't really need here

You're right! After looking at the generated code, `Reusable` seems to be the best choice here.
