### PR TITLE
[Woo POS] Fix for app crashing in payment flow on config change

### LINKED ISSUE #12308: [Woo POS] The app crashes during payment flow on config change
* Start payment flow
* Init config change, e.g. change from dark to light mode
Notice crash

```
                                                                                                    java.lang.IllegalArgumentException: No destination with ID 2131364278 is on the NavController's back stack. The current destination is null
                                                                                                    	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2450)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleResult(FragmentExt.kt:90)
                                                                                                    	at com.woocommerce.android.extensions.FragmentExtKt.handleDialogResult(FragmentExt.kt:120)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.setupResultHandlers(SelectPaymentMethodFragment.kt:306)
                                                                                                    	at com.woocommerce.android.ui.payments.methodselection.SelectPaymentMethodFragment.onViewCreated(SelectPaymentMethodFragment.kt:87)
```

### PR DESCRIPTION
**Pull request by samiuelson**
##  Fix for app crashing in payment flow on config change

Closes: #12308 

### Description

The app was crashing in the payment flow on config change (e.g. when changing the device's dark/light theme). Debugging revealed multiple problems:
1. The nav graph was not properly inflated and set to `NavController` in `WooPosCardReaderActivity` when the Activity was recreated. It was set only during view model initialization and was thus ignored in case Activity died and was recreated, but VM survived.
2. `WooPosCardReaderFacade` was setting `WooPosCardReaderFacade.paymentContinuation` to null when the Activity was dying. After activity recreation, the `paymentContinuation` prop was null, and the payment result was not delivered down to the `WooPosTotalsViewModel`. As a result, the "payment successful" screen was not shown, leaving the user in the Totals screen – quite misleading.

The above issues were fixed by:
1. Refactoring the event-style state rendering of the `WooPosCardReaderActivity` state to a static state exposed by the VM's property.
2. Not allowing the `paymentContinuation` to be nulled during Activity recreation.

Additionally, the `registerForActivityResult` was improved, making it offensive when passing payment result back to VM via `paymentContinuation`.

### Steps to reproduce

1. Start payment flow
4. Init config change, e.g. change from dark to light mode
5. Notice crash:
```kotlin
java.lang.IllegalArgumentException: No destination with ID 2131364278 is on the NavController's back stack. The current destination is null
```
### Testing information

I've tested the POS payment collection flow with and without triggering configuration change (device dark/light mode switch) and confirmed the flow completes as expected. Samsung Galaxy Tab, Android 14.

Note: The IPP flow itself remains untouched so it's not necessary to test against regression in the store management mode. It would be great to test the card reader connection flow and payment collection flows in POS mode extensively though.

### Images/gif

https://github.com/user-attachments/assets/90072f11-a376-41e0-8c2e-62955673c1e6

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on all devices (phone/tablet) and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt [hunk 1]
```diff
@@ -26,7 +26,7 @@ class WooPosCardReaderActivity : AppCompatActivity(R.layout.activity_woo_pos_car
             R.id.woopos_card_reader_nav_host_fragment
         ) as NavHostFragment
 
-        observeEvents(navHostFragment)
+        setupNavGraph(navHostFragment)
```
Comment (backwardstruck) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderActivity.kt:29]: OK. I had suspected something like this was going on but I didn't come up with this solution in my [attempt](https://github.com/woocommerce/woocommerce-android/pull/12325).

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt [hunk 2]
```diff
@@ -38,13 +38,12 @@ class WooPosCardReaderFacade @Inject constructor(cardReaderManager: CardReaderMa
                 WooPosCardReaderPaymentResult.Failure
             }
 
-            paymentContinuation?.resume(paymentResult!!)
+            paymentContinuation!!.resume(paymentResult!!)
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderFacade.kt:41]: Just thinking about this change

I checked the code of that `registerForActivityResult` and looks like that they can return the result only of the starting activity is in between start and start, but I am wondering if there is a chance that the starting activity can be destroyed already after the callback called? Seems to be no as this will be run on the main thread, so looks a valid change to me

**Comment by kidinov** [comment]
@samiuelson 

> The nav graph was not properly inflated and set to NavController in WooPosCardReaderActivity when the Activity was recreated. It was set only during view model initialization and was thus ignored in case Activity died and was recreated, but VM survived.

But it uses live data, so is the latest event supposed to be delivered after active recreation? 🤔 Was it delivered to late or what am I missing?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt [hunk 3]
```diff
@@ -1,33 +1,37 @@
...
-    savedStateHandle: SavedStateHandle,
-) : ScopedViewModel(savedStateHandle) {
-    init {
-        when (val mode = savedStateHandle.get<WooPosCardReaderMode>(WOO_POS_CARD_READER_MODE_KEY)) {
-            is WooPosCardReaderMode.Connection -> {
-                triggerEvent(WooPosCardReaderEvent.Connection)
-            }
+class WooPosCardReaderViewModel @Inject constructor(val savedStateHandle: SavedStateHandle) :
+    ViewModel() {
+    val cardReaderMode: WooPosCardReaderMode
```
Comment (kidinov) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt:13]: I am wondering; maybe in order to bring some sense to the existence of this model, we should cache the value returned from savedStateHandle? Otherwise everytime `cardReaderMode` is hit we go to the bundle to take the value

**Comment by samiuelson** [comment]
> @samiuelson
> 
> > The nav graph was not properly inflated and set to NavController in WooPosCardReaderActivity when the Activity was recreated. It was set only during view model initialization and was thus ignored in case Activity died and was recreated, but VM survived.
> 
> But it uses live data, so is the latest event supposed to be delivered after active recreation? 🤔 Was it delivered to late or what am I missing?

Good question, @kidinov. The `_events` property in `ScopedViewModel` is instantiated using custom implementation of `MutableLivedata`:
```kotlin
val _event: MutableLiveData<Event> = MultiLiveEvent()
```
where
```kotlin
/**
 * A lifecycle-aware observable that sends only new updates after subscription, used for events like
 * navigation and Snackbar messages.
 *
 *
 * This avoids a common problem with events: on configuration change (like rotation) an update
 * can be emitted if the observer is active. This LiveData only calls the observable if there's an
 * explicit call to setValue() or call().
 *
 *
 * This is a mutation of SingleLiveEvent, which allows multiple observers. Once an observer marks the event as handled,
 * no other observers are notified and no further updates will be sent, similar to SingleLiveEvent.
 */
open class MultiLiveEvent<T : Event> : MutableLiveData<T>() {
    private val pending = AtomicBoolean(false)

    @MainThread
    override fun observe(owner: LifecycleOwner, observer: Observer<in T>) {
        super.observe(owner) { t ->
            if (pending.get()) {
                t.isHandled = true
                observer.onChanged(t)
                pending.compareAndSet(t.isHandled, false)
            }
        }
    }
}
```
Also, the docs above mention the implementation prevents replaying old events after subscription. So that's the reason the events were not re-emitted after `WooPosCardReaderActivity` was recreated.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt (hunk 3 above)
Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt:13]: The `WooPosCardReaderActivity` serves both for reader connection and payment collection actions. My initial train of thought was that it's safer to avoid caching in case the Activity is started/destroyed continuously with different `WOO_POS_CARD_READER_MODE_KEY` values (`Connection`/`Payment`), while the VM survives and provides stale value 🤔

Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt:13]: > Activity is started/destroyed continuously with different WOO_POS_CARD_READER_MODE_KEY values (Connection/Payment)

I recently added a "single_top" flag (maybe not merged yet), so maybe, yeah, it is safer to go this way. We don;t need the VM though then =)

Comment (samiuelson) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt:13]: Keeping `orderId` validation, etc. out of Activity can be useful, but I agree we don't need to employ the VM for it.

**Comment by kidinov** [comment]
@samiuelson Thanks for the explanation

🤦  yep, I completely missed that it's not lifedata we use but the thing for events

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt (hunk 3 above)
Comment (kidinov) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/woopos/cardreader/WooPosCardReaderViewModel.kt:13]: Yeah, but I'd keep it anyway, as there is still some kind of logic in it

**Review by kidinov — APPROVED** [review]
LGTM!

**Comment by kidinov** [comment]
@samiuelson My understanding that all the test you ran have to be added in the PR description though:

```
The author listed all the tests they ran
```

p1724156878421179-slack-C025A8VV728

**Comment by samiuelson** [comment]
> @samiuelson My understanding that all the test you ran have to be added in the PR description though:
> 
> ```
> The author listed all the tests they ran
> ```
> 
> p1724156878421179-slack-C025A8VV728

I briefly described the tests I did under "Testing information".
