### PR TITLE
Missing impressions icon

### LINKED ISSUE #12562: Missing Blaze impressions info icon when the impressions label copy is very long
**Describe the bug**
In Blaze edit budget screen, the label displayed above the impressions number should display an info icon. Tapping in that info icon would explain users, what impressions are. This is the expected behavior when the language is set to English: 

https://github.com/user-attachments/assets/6100b9b7-44b3-436c-a7e5-e3504484f041

However, when setting app language to a different local where this label becomes longer than 1 lines, the icon is missing. 

image

**Expected behavior**
The info icon should always be displayed.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #12562

### Description

Fixes an issue where the ℹ️ icon next to the impression label inside the Blaze budget screen, would go missing if the text was too long. 

### Steps to reproduce

From `trunk`
1. Set Woo app language to Spanish
2. Trigger Blaze campaign creation flow and navigate to the budget screen.
3. Check the ℹ️ icon is missing next to the impressions label. 

### Testing information

Repeat the steps above from this branch and verify that the ℹ️ icon is displayed correctly when the text is one line (English) and when the text is 2 lines (Spanish for example)

### The tests that have been performed

Tested Blaze campaign creation flow. 

### Images/gif

Expected UI: 

Screenshot 2024-09-19 at 13 35 45
Screenshot 2024-09-19 at 13 35 21

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt [hunk 1]
```diff
@@ -248,19 +254,39 @@ private fun CampaignImpressionsRow(
...
+                .clickable { onImpressionsInfoTapped() }
+                .padding(top = 8.dp, bottom = 8.dp, end = 8.dp),
+            verticalAlignment = Alignment.CenterVertically,
+        ) {
+            val id = "inlineIcon"
+            val text = buildAnnotatedString {
+                append(stringResource(id = R.string.blaze_campaign_budget_reach_forecast))
+                appendInlineContent(id = id, alternateText = "[Icon]")
+            }
+            val inlineContent = mapOf(
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/blaze/creation/budget/BlazeCampaignBudgetScreen.kt:269]: I ended up inlining the info icon to ensure it looks nice when the text is 2 lines.

**Review by hichamboushaba — APPROVED** [review]
Nice work, TIL about `InlineTextContent` 👍
