### PR TITLE
[Kotlin Warnings As Errors] Woo Commerce Module - Resolve Deprecated Warnings

### LINKED ISSUE #6819: Kotlin Warnings as Errors - Woo Commerce Module
Parent #6816

This issue is about resolving/suppressing the Kotlin compile warnings for the `WooCommerce` module.

- [ ] Resolve/Suppress all warnings. @ParaskP7 ⚙️ 
  - [x] Resolve/Suppress `Coroutines` related warnings. @ParaskP7 #6840
    1. This declaration is experimental and its usage should be marked with `@kotlinx.coroutines.ExperimentalCoroutinesApi` or `@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)`
    2. This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with`@kotlinx.coroutines.FlowPreview` or `@OptIn(kotlinx.coroutines.FlowPreview::class)` if you accept the drawback of relying on preview API
  - [x] Resolve/Suppress `Deprecated` related warnings. @ParaskP7 #6850
    1. `toLowerCase(...): String` is deprecated. Use lowercase() instead.
    2. `Xyz` is deprecated. Deprecated in Java
    3. `Xyz` is deprecated. Other
    4. Candidate resolution will be changed soon, please use fully qualified name to invoke the following closer candidate explicitly
  - [x] Resolve/Suppress `Type/Cast/When` related warnings. @ParaskP7 #6865
    - Type
      1. Unsafe use of a nullable receiver of type Xyz?
      2. Returning type parameter has been inferred to Nothing implicitly because Nothing is more specific than specified expected type. Please specify type arguments explicitly in accordance with expected type to hide this warning. Nothing can produce an exception at runtime. See KT-36776 for more details.
      3. Type mismatch: inferred type is Date? but Date was expected
      5. Elvis operator (?:) always returns the left operand of non-nullable type Boolean
      6. Unnecessary safe call on a non-null receiver
    - Cast
      1. Smart cast to `Xyz` is deprecated, because 'itemView' is a property declared in base class from different module
      2. Unchecked cast: Any to T
      3. No cast needed
    - When
      1. Non exhaustive 'when' statements
      2. 'when' is exhaustive so 'else' is redundant here
  - [x] Resolve/Suppress `Other` related warnings. @ParaskP7 #6865
    1. This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
    2. Parameter `xyz` is never used
    3. Name shadowed: payload
    4. Property would not be serialized into a `Parcel`. Add `@IgnoredOnParcel` annotation to remove the warning (#6895)
    5. Parcelize annotations from package `kotlinx.android.parcel` are deprecated. Change package to `kotlinx.parcelize`
  - [x] Resolve/Suppress `Test` related warnings. @ParaskP7 #6902
    - Coroutines
        1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
        2. 'runBlockingTest(suspend TestCoroutineScope.() -> Unit): Unit' is deprecated. Use `runTest` instead to support completing from other dispatchers. Please see the migration guide for details: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md (#6899)
        3. 'advanceTimeBy(Long): Unit' is deprecated. The name of this function is misleading: it not only advances the time, but also runs the tasks scheduled *at* the ending moment. (#6899)
        4. 'TestCoroutineDispatcher' is deprecated. The execution order of `TestCoroutineDispatcher` can be confusing, and the mechanism of pausing is typically misunderstood. Please use `StandardTestDispatcher` or `UnconfinedTestDispatcher` instead. (#6899)
        5. 'TestCoroutineScope(CoroutineContext = ...): TestCoroutineScope' is deprecated. This constructs a `TestCoroutineScope` with a deprecated `CoroutineDispatcher` by default. Please use `createTestCoroutineScope` instead. (#6899)
        6. 'runBlockingTest(CoroutineContext = ..., suspend TestCoroutineScope.() -> Unit): Unit' is deprecated. Use `runTest` instead to support completing from other dispatchers. Please see the migration guide for details: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md
    - Other
        1. 'XYX' is deprecated. Deprecated in Java
        2. Unchecked cast: Xyz to Xyz
        3. Parameter 'xyz' is never used
        4. Parameter 'xyz' is never used, could be renamed to _
        5. Name contains characters which can cause problems on Windows: " 
- [x] Enable all warnings as errors. @ParaskP7 #6902

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent: #6816
Partially Closes: #6819

### Description

This PR resolves all `Deprecated` related warnings for the `woocommerce` module:

- 24 warnings x `'toLowerCase(...): String' is deprecated. Use lowercase() instead.`
- 93 warnings x `'XYX' is deprecated. Deprecated in Java`
- 23 warnings x `'xyz' is deprecated. Other xyz.`
- 11 warnings x `Candidate resolution will be changed soon, please use fully qualified name to invoke the following closer candidate explicitly`

Warnings Resolution List:

1. `to lower/upper case`
    - [Resolve to lower case deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/d65aaccbbac0fd74d3234119fab7897c374dbf7a)
    - [Resolve to lower case deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/9564fee044080de63e2ed4ef47c03a1dbf53af08)
    - [Resolve to upper case deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/40ed6560f6d60fc8aa77fe75d6e5c5838fe49f7f)
2. [Resolve from html deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/ff33eb7725e6b57db33e0dc0d47e9e5a45b3c963)
3. [Resolve handler deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/e795d1c48c37a1224fb8f0e5f2364e372006a519)
4. [Resolve drawable color filter deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/2e5a4d4f8fbd02b018b8f05a67f61f12736e6f4a)
5. `custom tabs`
    - [Resolve custom tabs intent toolbar color deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/8b8023f8a09ba6507f3cebed40aacd04e8c7fa59)
    - [Resolve custom tabs intent menu item color deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/6f25f6242a2fb3e10fbde85db8e6f67019a2092f)
6. `kotlin`
    - [Resolve kotlin char to int deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/181b785a5d690cdb7a736bbd52b62b21d5cb8975)
    - [Resolve kotlin sum by deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/5bfba70bec96f31de1ba28575cac84957f18313d)
7. [Resolve lifecycle observe deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/f8a1c28ee224fe4a4c8d452fde1a1a38b1647e60)

Warnings Suppression List:

1. `connectivity`
    - [Suppress connectivity action deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/d00191ab0e51d57f68ec005b4ef9e46fb2b02e4f)
    - [Suppress network type and connectivity deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/f5b3e427d3c31a6e89aa8d71a305372cca45156e)
2. [Suppress bluetooth get default adapter deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/5242c08f6e2bbbeacd41d9f160a28189bee67b11)
3. `fragment`
    - [Suppress fragment retain instance deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/0df3ee9e04a574b2c70cf41347e50570001364ac)
    - [Suppress (dialog) fragment activity created deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/763058b4ffb232e622b914bff0482e22079d5a10)
    - [Suppress fragment pager adapter deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/70817ceda79fcb1dd7bdea4bd8b4a8f7bc6c1a46)
    - [Suppress fragment activity activity result deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/2b0a2a47eaf665a0190320630cd154d4691dadfc)
4. [Suppress progress dialog deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/c56fffcf72c96a9b16db3433355c90a708e44da3)
5. `fluxc`
    - [Suppress fluxc related update order status deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/7e997e430d5e0cc3520457a7a42b425e5bc7e81c)
    - [Suppress fluxc related selected site changed event warning](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/b30ec0ff22ca3b6d624e1a1dfc12deead084ee97)
6. `recycler view`
    - [Suppress recycler view adapter position deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/71c412abcb71e7d118dbee1933bd29b16c67495c)
    - [Suppress recycler view adapter position deprecated warnings.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/71c412abcb71e7d118dbee1933bd29b16c67495c)
    - [Suppress recycler view recycler listener deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/59aaf30e46598be25b30ebcb911751fce4e1a535)
7. [Suppress window manager flag fullscreen deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/40b495e75116a14069d3d2b91003fcf699e9f407)
8. [Suppress wordpress utils date time utils deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/0fd87c0b596677a48047fea7e7dd08bf342e2560)
9. [Suppress kotlin capitalize deprecated warning.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/2fc2ae77354ec1b6ac8fc21d1042399becae0976)

Refactor List:
1. [Remove unnecessary from html utility functions.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/a31e5e0f0a61e4cd79c52c4009c8072f07a21dba)
2. [Remove unused adjust dialog size ui helper function.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/66cf506d9641b96d01632c9f7a137bc7838b9d33)
3. [Remove redundant lifecycle observer related sam-constructors.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/f609daa434f849467ce366a04a243aa896d7f86d)

In addition to the above warning resolution list, the below `Detekt` warnings got resolved as well, leaving Detekt's `baseline.xml` file 69 entries shorter:

1. [Resolve (no) wildcard imports detekt warnings for java util.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/4a49cf7fefadeaf2c3186d2fc366be441a047611)
3. [Resolve (no) wildcard imports detekt warnings for product rev.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/7372f68d12f7f0cb95a823abd4da63fec35e7d84)
4. [Resolve (no) wildcard imports detekt warnings for lifecycle.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/5b0359faccbb92c5cb1c8074055ec8f99ad74a6d)
5. [Resolve (no) wildcard imports detekt warnings for shipping lab.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/f5f9e3def9cfa6c1bbe0be9c755a40dbcb1b2c6a)
6. [Resolve (no) wildcard imports detekt warnings for review det.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/4f6e26085b4513b8bd451895624a147fb39f39c7)
7. [Resolve no unused imports detekt warnings for ui helpers.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/c5f16804379c150e1f5098727439f85c5eb0eabb)

Finally, and in addition to the above, the below custom `Lint` warning needed to be resolved as well (the proper way):

1. [Resolve new api lint warnings for html from html static call.](https://github.com/woocommerce/woocommerce-android/pull/6850/commits/c311d30602930a098a402a7d9f94cbd6d41bd3d4)

-----

PS.1: @JorgeMucientes I added you as the main reviewer, that is, in addition to the @woocommerce/owl-team team itself, but randomly, since I just wanted someone from the `Woo Android` team to sing-off on that change for WCAndroid as well. PS: I am going to randomly add more of you in those PRs just so you become more aware of this change and how close we are on enabling `allWarningsAsErrors` by default everywhere. 🥇 

PS.2: With that PR merged to `trunk` there are going to be `44` such warnings left to be resolved for the `main` source of this module. It started with `319` such warnings, out of which, `124` were already solve by the [coroutines](https://github.com/woocommerce/woocommerce-android/pull/6840) sibling PR. 🎉 

### Testing instructions

- Verify that all the CI checks are successful.
- Smoke test the app and verify everything works as expected.

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt [hunk 1]
```diff
@@ -250,17 +249,6 @@ object StringUtils {
...
-     * Helper method for using the appropriate `Html.fromHtml()` for the build version.
-     */
-    fun fromHtml(htmlStr: String): Spanned {
-        return if (SystemVersionUtils.isAtLeastN()) {
-            Html.fromHtml(htmlStr, Html.FROM_HTML_MODE_LEGACY)
-        } else {
-            Html.fromHtml(htmlStr, Html.FROM_HTML_MODE_LEGACY)
-        }
-    }
-
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt:261]: Hmm, just thinking outloud here. We have a lot of calls to `Html.fromHtml(htmlStr, Html.FROM_HTML_MODE_LEGACY)` scattered across the codebase. I wonder if it might be interesting to keep a centralized utility method like this. If for any reason in the future we ever need to add custom logic like the one we had in this method (even though it was not doing anything useful in this case 😅 ), it would be very straight forward to update it. Whereas now we'd need to update all the usages across the app. 

I know this feels kind of YAGNI at this point, and even if we had a utility method like this there is no guarantee all developers will be aware of it and use it instead of calling Android's ` Html.fromHtml` directly. So, feel free to ignore this thoughts.

**Comment by JorgeMucientes** [comment]
Awesome job @ParaskP7 ! Super well-organized and documented PR 🥇 

I haven't seen anything concerning, I just left some random thoughs.  But in any case, any change derived from those, would be out of scope for this PR. 

Thank you for working on this ! Once again awesome "house cleaning" job 🙌🏼

**Review by JorgeMucientes — APPROVED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt (hunk 1 above)
Comment (ParaskP7) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt:261]: 👋 @JorgeMucientes !

Thank you so much for this comment and for sharing your thoughts about it! 🙇 

Actually there is already a utility like that but coming from Android itself, it is the `HtmlCompat.fromHtml(html, HtmlCompat.FROM_HTML_MODE_LEGACY)`, which was already used here and there. I then applied that everywhere with this c311d30602930a098a402a7d9f94cbd6d41bd3d4 commit. Thus, I am voting in favor of using `HtmlCompat.fromHtml(...)` instead of our own `StringUtils.fromHtml(...)`. Wdyt?

Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt:261]: Oh that's right! I missed we're now using `HtmlCompat` instead of `Html.fromHtml(htmlStr, Html.FROM_HTML_MODE_LEGACY)` 
Forget about what I said 😅 sorry for the noise.

Comment (ParaskP7) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/util/StringUtils.kt:261]: Coolio, I hear no noise and I am glad that you are so thorough! 🙏
