### PR TITLE
Fix issue where price was cleared on attribute change

### LINKED ISSUE #6345: Variations: Changing Attributes on a new variation discards the price changes
**Describe the bug**
When changing a variation's attributes, the price changes get discarded.

**To Reproduce**
1. Create a new variable product. Add an attribute like Size.
2. Generate a new variation.
3. On the variation page, tap Add Price and enter a value for the price. 
4. Navigate back to the variation page.
5. Tap on Attributes.
6. Change the attribute to a specific value.
7. Navigate back. 

Notice that the price gets discarded. The warning “Variations without price won't be shown...” is displayed. 

**Expected behavior**
The price changes should not be discarded.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Pixel 3
- Android version: 
- WooCommerce Android version: 9.0-rc-1

### PR DESCRIPTION
**Pull request by malinajirka**
Closes: #6345

### Description

This PR fixes an issue where price in variation detail gets cleared whenever one of the other values (attributes, visibility and inventory) is changed. This issue was recently introduced in [this PR](https://github.com/woocommerce/woocommerce-android/pull/6039) which fixed another bug related to setting price to 0. This PR hopefully fixes the issue while still supporting setting the price to 0.

Commit https://github.com/woocommerce/woocommerce-android/commit/b0acd149a905f22885c6fa419124a99e510ba2f7 is technically not necessary and doesn't fix anything - it simply makes the code between ProductVariationDetail and ProductDetail consistent.

### Testing instructions

1. Create a new variable product. Add an attribute like Size.
2. Generate a new variation.
3. On the variation page, tap Add Price and enter a value for the price.
4. Navigate back to the variation page.
5. Tap on Attributes.
6. Change the attribute to a specific value.
7. Navigate back.
8. Notice the price remains unchanged
-----------------

1. Click on the + button in the Products tab and create a new product.
2. Notice that the price section displays "Add Price".
3. Click on the "Add Price" section.
4. Click on the back button.
5. Notice the the menu option is not changed in any way.
6. Click on the "Add price" section again and enter any value in the regular price field and sale price field.
7. If the sale price entered is greater than the regular price, then an error message should be displayed.
8. Enter a regular price value greater than 0 and a sale price value less than the regular price and click on the Back button.
9. Notice the new values are updated correctly. Click on the Update/Save button. View the product page on the web and notice the values displayed correctly as entered.
10. Click on the "Add price" section again and update the regular price to 0 and leave the sale price as empty. Save the product. View the product page on the web and notice the price is displayed as 0.
11. Click on the "Add price" section again and leave the regular price empty and leave the sale price as empty. Save the product. View the product page on the web and notice the price is not displayed and the Add to Cart button is not displayed.
12. Test the above scenarios for a variation of a product.

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt [hunk 1]
```diff
@@ -200,8 +199,8 @@ class VariationDetailViewModel @Inject constructor(
         remoteVariationId: Long? = null,
         sku: String? = null,
         image: Optional<Image>? = null,
-        regularPrice: BigDecimal? = null,
-        salePrice: BigDecimal? = null,
+        regularPrice: BigDecimal? = viewState.variation?.regularPrice,
```
Comment (malinajirka) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/variations/VariationDetailViewModel.kt:202]: The root cause of the issue was that `null` was used in two different scenarios:
1. the caller of this method wanted to set the price to null (eg. `onVariationChanged(regularPrice = null)`)
2. the caller of this method didn't want to change the price at all and wanted to change one of the other attributes (eg. `onVariationChanged(sku = "abc123")`)

Both of these scenarios mapped `price` to `null` and it wasn't possible to differentiate between them.

This PR fixes the issue by setting the price to the original value if the caller doesn't want to change the price (`onVariationChanged(sku = "abc123")`). If the caller wants to change the price the value they pass to `price` will be actually set, even when it's 0 or null (eg. `onVariationChanged(regularPrice = null/0/999/.... )`).

File: RELEASE-NOTES.txt [hunk 2]
```diff
@@ -2,7 +2,7 @@
 
 9.1
 -----
-
+- [*] Variation Detail: Don't clear price on attribute/visibility/inventory change. [https://github.com/woocommerce/woocommerce-android/compare/issue/6345-fix-price-on-variations-2?expand=1]
```
Comment (nbradbury) [inline RELEASE-NOTES.txt:5]: np: I think I'd give this ** or ***

**Review by nbradbury — APPROVED** [review]
I won't hold this up just [for my nitpick](https://github.com/woocommerce/woocommerce-android/pull/6399/files#r860066247). Code is good, fix is good, and nice work tracking the problem down! :shipit:

File: RELEASE-NOTES.txt (hunk 2 above)
Comment (malinajirka) [reply RELEASE-NOTES.txt:5]: @nbradbury My understanding is that this is just a hint for whoever will write the final release notes. It is not the final version of what gets published to GP, right? If this is the string which will be published to GP I completely agree we should update it - I can do it in a separate PR.

Comment (nbradbury) [reply RELEASE-NOTES.txt:5]: That's correct, but the stars are a hint as to the priority of the change, and this strikes me as an important fix. But it is after all just a nitpick from me :)

Comment (malinajirka) [reply RELEASE-NOTES.txt:5]: Sorry, I was totally confused yesterday, I don't know what I was thinking. I thought you were suggesting to replace `attribute/visibility/inventory` with `attribute, visibility or inventory`.

Agree, I'll update the priority.

Comment (malinajirka) [reply RELEASE-NOTES.txt:5]: To close the loop https://github.com/woocommerce/woocommerce-android/pull/6411
