### PR TITLE
[Image Uploads] Fix displaying ongoing uploads in Product details

### LINKED ISSUE #6963: [Product image upload] ongoing uploads don't appear on the product details screen
Displaying the current uploads is broken in product details.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #6963 

### Description
This fixes a bug that resulted in not showing the ongoing uploads in product details, the cause is that `getRemoteProductId` depends on the current value of `viewState.productDraft`, and since we load the product asynchronously now, this value is null when we initiate the ViewModel.
The solution is to make sure we listen to changes of `productDraft`, and whenever we have a new value, we re-monitor image uploads using the last value.

This also fixes a bug where ongoing uploads are not displayed after saving a new product as a draft. 

#### Product Edit
1. Open product details.
2. Add some images from your device.
3. Go back to order details.
4. Confirm the ongoing uploads are shown in the gallery view.

#### Product creation
1. Open product creation form.
2. Add some images from your device.
3. Go back to order details.
4. Click on menu, and select save as draft, while the upload is ongoing.
5. Confirm the ongoing uploads are still shown in the gallery view.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt [hunk 1]
```diff
@@ -917,6 +919,18 @@ class ProductDetailViewModelTest : BaseUnitTest() {
...
+    fun `when the screen is just launched, then return the correct product id`() = testBlocking {
+        whenever(productRepository.getProductAsync(any())).doSuspendableAnswer {
+            // Makes sure this suspends
+            delay(10)
+            return@doSuspendableAnswer product
+        }
+        viewModel.start()
+
+        assertThat(viewModel.getRemoteProductId()).isEqualTo(PRODUCT_REMOTE_ID)
+    }
```
Comment (hichamboushaba) [inline WooCommerce/src/test/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModelTest.kt:932]: This test is not working before the changes above.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt [hunk 2]
```diff
@@ -1638,29 +1641,35 @@ class ProductDetailViewModel @Inject constructor(
...
-                        triggerEvent(HideImageUploadErrorSnackbar)
-                    } else {
-                        val errorMsg = resources.getMediaUploadErrorMessage(errorList.size)
-                        triggerEvent(
-                            ShowActionSnackbar(errorMsg) {
-                                triggerEvent(ProductNavigationTarget.ViewMediaUploadErrors(getRemoteProductId()))
+            draftChanges
+                .distinctUntilChanged { old, new -> old?.remoteId == new?.remoteId }
+                .map { getRemoteProductId() }
+                .filter { productId -> productId != DEFAULT_ADD_NEW_PRODUCT_ID || isAddFlowEntryPoint }
```
Comment (hichamboushaba) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt:1647]: This is just an optimization to avoid starting the monitoring with `DEFAULT_ADD_NEW_PRODUCT_ID` in edit flow (`getRemoteProductId` will return `DEFAULT_ADD_NEW_PRODUCT_ID` when `productDraft` is null)

**Review by nbradbury — APPROVED** [review]
Fix is good! :shipit:
