### PR TITLE
Site Selector: Switch to on-demand api version verification design like iOS

### LINKED ISSUE #691: Fetching api version for store always shows store has wrong api version
**Describe the bug**
If an error occurs while fetching the WooCommerce store version from the API, the **Store Selector** screen will display that store as not having the correct API version (even though it may). Here is a snippet of the original code:

```
@Suppress("unused")
@Subscribe(threadMode = ThreadMode.MAIN)
fun onApiVersionFetched(event: OnApiVersionFetched) {
    if (event.apiVersion == WooCommerceStore.WOO_API_NAMESPACE_V3) {
        supportedWCSites.add(event.site)
    } else {
        unsupportedWCSites.add(event.site)
    }

    val totalSitesChecked = supportedWCSites.size + unsupportedWCSites.size
    if (totalSitesChecked == wooCommerceStore.getWooCommerceSites().size) {
        loginEpilogueView?.showStoreList(supportedWCSites, unsupportedWCSites)
    }
}
```

if `event.isError == true`, the `event.apiVersion` will be set to an empty string, so `event.apiVersion != WooCommerceStore.WOO_API_NAMESPACE_V3` and therefore the store will show up as having the wrong api version. The fix will be to add some proper error handling.

### PR DESCRIPTION
**Pull request by AmandaRiu**
This PR fixes #691 and changes the design of the site selector to more closely match the iOS version.

The former design validated all stores up front and then displayed stores that did not meet the minimum api version requirements in a separate section. The problem was that if the store could not be validated for one reason or another, they would automatically show up in the "Update required" section, even though they _may_ be running the correct version of WooCommerce. A couple ideas were thrown around to address this like creating a separate section for the stores that could not be verified, but in the end we decided to match the iOS design since it allows more flexibility on how to handle the validation response at the individual site level.

The new design will show all Woo stores in a single list and then validation will happen when the user _**selects a store**_. There are three possible outcomes of this validation:
1. The store passes -> the **continue** button will enable
2. The store's api version does not meet the minimum requirements (failed) -> a dialog will be shown advising the user to upgrade their WooCommerce plugin.
3. The store cannot be verified for some reason (error) -> display a snack error message

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpiloguePresenter.kt [hunk 1]
```diff
@@ -83,15 +77,24 @@ class LoginEpiloguePresenter @Inject constructor(
     @Suppress("unused")
     @Subscribe(threadMode = ThreadMode.MAIN)
     fun onApiVersionFetched(event: OnApiVersionFetched) {
-        if (event.apiVersion == WooCommerceStore.WOO_API_NAMESPACE_V3) {
-            supportedWCSites.add(event.site)
-        } else {
-            unsupportedWCSites.add(event.site)
+        if (event.isError) {
+            WooLog.e(T.LOGIN, "Error fetching apiVersion for site [${event.site.siteId} : ${event.site.name}]! " +
+                    "${event.error?.message}")
```
Comment (aforcier) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginEpiloguePresenter.kt]: We should probably log the `error.type` here as well.

**Comment by AmandaRiu** [comment]
@aforcier Added error type to the error log message. Ready for second round.

**Comment by aforcier** [comment]
Looks good @AmandaRiu - :shipit: from me!

**Comment by aforcier** [comment]
Opened #699 to track adding a help button to this screen.
