### PR TITLE
Issue/13443 fix dashboard interacted tracking

### LINKED ISSUE #13443: Adjust tracking for `dynamic_dashboard_card_interacted`
There are some discrepancies and bugs on the way we track `dynamic_dashboard_card_interacted` in Android. Address them: 

- Add tracking to chart interactions. Do as iOS does and trigger `dynamic_dashboard_card_interacted` when the user: 
  - Taps on the chart
  - Releases the finger after dragging on the chart (we already handle this interactions to track `used_analytic`, so reusing that logic should work) 
- In Android tapping on Custom range  option for stats card or top performers when there’s no prior custom range added will fire the event twice. Fix that to track it only once. 
- Fire `_dynamic_dashboard_card_interacted` when tapping on View all Store Analytics CTA from top performers card.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #13443

### Description

Fixes several tracking issues related to the `dynamic_dashboard_card_interacted` event:

- Add tracking to chart interactions. Do as iOS does and trigger `dynamic_dashboard_card_interacted` when the user: 
  - Taps on the chart selecting a specific date
  - Releases the finger after dragging it over the chart 
- Tapping on the Custom range option for stats cards or top performers when there’s no prior custom range added will fire the event `dynamic_dashboard_card_interacted` twice. Fixed that
- Fire `_dynamic_dashboard_card_interacted` when tapping on View all Store Analytics CTA from top performers card.

Additionally, this PR introduces a slight change in the behavior. Previously, when there's already `Custom` persisted, tapping on `Custom` option would only load data for the previously selected custom range, and subsequent taps would do nothing. Now we are matching iOS behavior. Tapping on `Custom` option will always open the date range picker, with the prior custom range preselected. 

### Testing information
1. Clean install the app
2. Log into a site with some stats
3. Add Stats and Top performers cards to the dashboard

**Stats card **

1.. Select a custom range for the first time and check the following for the following events in the logcat: 
```
🔵 Tracked: woocommerceandroid_dynamic_dashboard_card_interacted, Properties: {"type":"performance"
🔵 Tracked: woocommerceandroid_dashboard_stats_custom_range_add_button_tapped
```
3. Tap `Save` on date range picker and ensure none of the above 2 events are tracked again (like on `trunk`)
4. Tap on the chart or drag your finger through it and check the following event is tracked for each interaction:
```
🔵 Tracked: woocommerceandroid_dynamic_dashboard_card_interacted, Properties: {"type":"performance"
```
5. Tap again on `Custom` range and check date range picker is opened and the following two events are tracked: 
```
🔵 Tracked: woocommerceandroid_dynamic_dashboard_card_interacted, Properties: {"type":"performance"
🔵 Tracked: woocommerceandroid_dashboard_stats_custom_range_edit_button_tapped
```

**Top Performers Card**
1. Repeat the above steps for top performers card and check the tracking behaves as expected (Skip step 4)
2. Tap on `View all store analytics` and check the following event is fired: 
```
🔵 Tracked: woocommerceandroid_dynamic_dashboard_card_interacted, Properties: {"type":"top_performers"
``` 

### The tests that have been performed

The above ☝🏼 
### Images/gif

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/250">21.7</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt [hunk 1]
```diff
@@ -180,10 +182,10 @@ class DashboardStatsView @JvmOverloads constructor(
                 .debounce(EVENT_EMITTER_INTERACTION_DEBOUNCE)
                 .collect {
                     usageTracksEventEmitter.interacted()
-
-                    if (statsTimeRangeSelection.selectionType == SelectionType.CUSTOM) {
-                        usageTracksEventEmitter.interactedWithCustomRange()
-                    }
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt:186]: This change is unrelated to the tracking fixes mentioned in the description. 
I'm removing this tracking as I don't think we are using it at all. I can't think of a case where we need to track user interactions over the line chart but just when a custom date range is selected. 

cc iOS folks: @itsmeichigo @pmusolino  so you are aware too because I see you track `dashboard_stats_custom_range_interacted`

Any concerns about removing it?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt [hunk 2]
```diff
@@ -141,28 +141,23 @@ class DashboardTopPerformersViewModel @AssistedInject constructor(
     }
 
     fun onRangeChanged(selectionType: SelectionType) {
```
Comment (JorgeMucientes) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: I not only fixed the tracking but also changed the logic a bit so that selecting a custom range from the drop-down behaves as iOS: it always opens the date picker, even when custom range is already selected

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt (hunk 1 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsView.kt:186]: I agree; there is no point in measuring this when only a custom date is selected.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt [hunk 3]
```diff
@@ -124,22 +124,31 @@ class DashboardStatsViewModel @AssistedInject constructor(
     }
 
     fun onRangeChanged(selectionType: SelectionType) {
-        parentViewModel.trackCardInteracted(DashboardWidget.Type.STATS.trackingIdentifier)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt:127]: Why did you remove `trackCardInteracted()` from here and add it to both `if` and `else` scopes? If I'm not mistaken, `trackCardInteracted()` was previously invoked once when `onRangeChanged()` was called, and it is still being invoked once every time `onRangeChanged()` is called.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 2 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: There's still a behavioral difference between iOS. On iOS, "Custom date" is not actually selected unless you choose dates and tap "Add" button on the date picker. But on Android, if I tap "X" button on the date picker without selecting the "SAVE" button, the "Custom" is still selected. 
It's a minor difference. I'm not sure which one is better, but we could align it with iOS. WDYT?

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt [hunk 4]
```diff
@@ -141,28 +141,23 @@ class DashboardTopPerformersViewModel @AssistedInject constructor(
...
-        parentViewModel.trackCardInteracted(DashboardWidget.Type.POPULAR_PRODUCTS.trackingIdentifier)
```
Comment (irfano) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:144]: I’ll make the same comment here. Can’t we just call `trackCardInteracted()` once here?

**Review by irfano — CHANGES_REQUESTED** [review]

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt (hunk 3 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt:127]: > Why did you remove trackCardInteracted() from here and add it to both if and else scopes?

Yeah, this is probably not straightforward to see and should've explained it on the first place. 

> If I'm not mistaken, trackCardInteracted() was previously invoked once when onRangeChanged() was called

Not really. With the prior implementation: 
- trackCardInteracted() was tracked always from `onRangeChanged` 
- onRangeChanged() was called from 2 places:
  - When selecting custom range from the drop down
  - From `onCustomRangeSelected() -> onRangeChanged()` which is called after tapping on `Save` button from date range picker. 

This implementation led to the event being tracked twice when adding a custom range for the first time. Which is one of the bugs this PR aims to fix.

>  and it is still being invoked once every time onRangeChanged() is called.

True, but the reason I had to move it inside `onEditCustomRangeTapped()` is because this function is not only called from  `onRangeChanged`. It is also called when custom range edit cta the ✏️ icon is tapped. And in this case we also need to track `trackCardInteracted`

Unsure I've explained myself. Let me know if you have further questions.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: Good point. I did have second thoughts on that. Since we are opening the date picker always, I guess it makes sense to follow iOS behavior. This will also ensure a more consistent tracking pattern. 
Change applied 👍🏼

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 4 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:144]: As explain above we need to track it inside `onEditCustomRangeTapped` as well.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 2 above)
Comment (hichamboushaba) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: > I not only fixed the tracking but also changed the logic a bit so that selecting a custom range from the drop-down behaves as iOS: it always opens the date picker, even when custom range is already selected

Just a thought on this, personally I think the behavior we had in Android is better in this regard, as it allows the user to restore the last used custom range quickly, and it could be beneficial in their flow, for example if they want to compare against last month, then for the whole current month, this would be easier than each time selecting the last month from the date picker.
And for information, we had a discussion about this previously (p1715109921454059/1715109882.889099-slack-C03L1NF1EA3) and my understanding there is that this is not an intentional behavior in iOS per se, but it's like this just because the implementation is simpler this way.

This is a minor point, but just wanted to share it for visibility on whether we want to change the behavior or not.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt (hunk 3 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/stats/DashboardStatsViewModel.kt:127]: > True, but the reason I had to move it inside onEditCustomRangeTapped() is because this function is not only called from onRangeChanged

Oh, I see! I missed that. Thanks for the explanation.

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 2 above)
Comment (irfano) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: Thanks for sharing the previous discussion. I don't have a strong opinion. Since this was intentional, we can revert your latest change, @JorgeMucientes! It's up to you.

**Review by irfano — APPROVED** [review]
I tested this, and LGTM! I'm approving but leaving the decision to revert your latest change up to you. 👍🏻

File: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt (hunk 2 above)
Comment (JorgeMucientes) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/ui/dashboard/topperformers/DashboardTopPerformersViewModel.kt:143]: Hey @hichamboushaba thanks for bringing up the past discussion and context. 

> I think the behavior we had in Android is better in this regard, as it allows the user to restore the last used custom range quickly, and it could be beneficial in their flow, for example if they want to compare against last month

Yeah, I think that is a valid point. So, I've added back the prior behavior, while avoiding the issues we had before with duplicated tracking 👍🏼 

https://github.com/user-attachments/assets/472ced32-82c8-4aa3-b2f8-827e868aae86
