### PR TITLE
Fixed bug where discard dialog was displayed when default tax class was selected

### LINKED ISSUE #2147: Product M1 release: discard dialog is displayed when default tax class is selected
When testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/2138), I noticed that `tax_class` by default is set an empty string but the default option displayed in the UI is Standard Rate. When Standard Rate is selected again, the discard dialog is displayed (even though it shouldn't) because the `tax_class` is saved as `standard`. instead of an empty string.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2147. The `tax_class` by default is set an empty string but the default option displayed in the UI is Standard Rate. When Standard Rate is selected again, the discard dialog is displayed (even though it shouldn't) because the `tax_class` is saved as standard instead of an empty string. This PR adds logic so that the default `tax_class` set is `standard` (which is what Core is doing).

#### Screenshots
(LEFT: Before the fix. RIGHT: after the fix)
. 

#### To test
- Click on a product from the products tab.
- Click on the `Inventory` section.
- Notice that the Tax class is set to `Standard Rate`.
- Click on the `Tax Class` field and select `Standard Rate` again.
- Click on the back/Home button.
- Notice the discard dialog is displayed, even when there are no changes to the product.
- Pull changes from this PR and verify that the discard dialog is not displayed in this scenario.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt [hunk 1]
```diff
@@ -274,7 +274,7 @@ fun WCProductModel.toAppModel(): Product {
         price = this.price.toBigDecimalOrNull()?.roundError(),
         salePrice = this.salePrice.toBigDecimalOrNull()?.roundError() ?: BigDecimal.ZERO,
         regularPrice = this.regularPrice.toBigDecimalOrNull()?.roundError() ?: BigDecimal.ZERO,
-        taxClass = this.taxClass,
+        taxClass = if (this.taxClass.isEmpty()) "standard" else this.taxClass,
```
Comment (nbradbury) [inline WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt]: This fix works just fine, but it's not well-documented. How about making "standard" a constant, and then adding a comment on this line explaining why this is being done?

Comment (anitaa1990) [reply WooCommerce/src/main/kotlin/com/woocommerce/android/model/Product.kt]: Fixed in f39176b 👍
